<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk1Topics20to22Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 20: Food and Drinks (食物和饮料) - 25 words
        $foodDrinksVocab = [
            [
                'topic_id' => 20,
                'word' => '水',
                'pinyin' => 'shuǐ',
                'simplified' => '水',
                'traditional' => '水',
                'part_of_speech' => 'noun',
                'meaning' => 'Water',
                'meaning_zh' => '水',
                'example_sentence' => '我喝水。',
                'example_translation' => 'I drink water.',
                'definition' => 'Water',
                'sentences' => ['我喝___。', '___很干净。', '一杯___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '茶',
                'pinyin' => 'chá',
                'simplified' => '茶',
                'traditional' => '茶',
                'part_of_speech' => 'noun',
                'meaning' => 'Tea',
                'meaning_zh' => '茶',
                'example_sentence' => '我喜欢喝茶。',
                'example_translation' => 'I like to drink tea.',
                'definition' => 'Tea',
                'sentences' => ['我喜欢喝___。', '___很香。', '绿___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '咖啡',
                'pinyin' => 'kā fēi',
                'simplified' => '咖啡',
                'traditional' => '咖啡',
                'part_of_speech' => 'noun',
                'meaning' => 'Coffee',
                'meaning_zh' => '咖啡',
                'example_sentence' => '我喝咖啡。',
                'example_translation' => 'I drink coffee.',
                'definition' => 'Coffee',
                'sentences' => ['我喝___。', '___很苦。', '一杯___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '牛奶',
                'pinyin' => 'niú nǎi',
                'simplified' => '牛奶',
                'traditional' => '牛奶',
                'part_of_speech' => 'noun',
                'meaning' => 'Milk',
                'meaning_zh' => '牛奶',
                'example_sentence' => '我喝牛奶。',
                'example_translation' => 'I drink milk.',
                'definition' => 'Milk',
                'sentences' => ['我喝___。', '___很新鲜。', '一瓶___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '果汁',
                'pinyin' => 'guǒ zhī',
                'simplified' => '果汁',
                'traditional' => '果汁',
                'part_of_speech' => 'noun',
                'meaning' => 'Fruit juice',
                'meaning_zh' => '果汁',
                'example_sentence' => '我喜欢喝果汁。',
                'example_translation' => 'I like to drink fruit juice.',
                'definition' => 'Fruit juice',
                'sentences' => ['我喜欢喝___。', '___很甜。', '橙___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '啤酒',
                'pinyin' => 'pí jiǔ',
                'simplified' => '啤酒',
                'traditional' => '啤酒',
                'part_of_speech' => 'noun',
                'meaning' => 'Beer',
                'meaning_zh' => '啤酒',
                'example_sentence' => '我不喝啤酒。',
                'example_translation' => 'I don\'t drink beer.',
                'definition' => 'Beer',
                'sentences' => ['我不喝___。', '___很凉。', '一瓶___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '酒',
                'pinyin' => 'jiǔ',
                'simplified' => '酒',
                'traditional' => '酒',
                'part_of_speech' => 'noun',
                'meaning' => 'Alcohol / Wine / Liquor',
                'meaning_zh' => '酒',
                'example_sentence' => '他喝酒。',
                'example_translation' => 'He drinks alcohol.',
                'definition' => 'Alcohol, wine, liquor',
                'sentences' => ['他喝___。', '___很烈。', '红___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '苹果',
                'pinyin' => 'píng guǒ',
                'simplified' => '苹果',
                'traditional' => '蘋果',
                'part_of_speech' => 'noun',
                'meaning' => 'Apple',
                'meaning_zh' => '苹果',
                'example_sentence' => '我喜欢吃苹果。',
                'example_translation' => 'I like to eat apples.',
                'definition' => 'Apple',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '香蕉',
                'pinyin' => 'xiāng jiāo',
                'simplified' => '香蕉',
                'traditional' => '香蕉',
                'part_of_speech' => 'noun',
                'meaning' => 'Banana',
                'meaning_zh' => '香蕉',
                'example_sentence' => '我喜欢吃香蕉。',
                'example_translation' => 'I like to eat bananas.',
                'definition' => 'Banana',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一根___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '橙子',
                'pinyin' => 'chéng zi',
                'simplified' => '橙子',
                'traditional' => '橙子',
                'part_of_speech' => 'noun',
                'meaning' => 'Orange',
                'meaning_zh' => '橙子',
                'example_sentence' => '我喜欢吃橙子。',
                'example_translation' => 'I like to eat oranges.',
                'definition' => 'Orange (fruit)',
                'sentences' => ['我喜欢吃___。', '___很酸。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '葡萄',
                'pinyin' => 'pú táo',
                'simplified' => '葡萄',
                'traditional' => '葡萄',
                'part_of_speech' => 'noun',
                'meaning' => 'Grape',
                'meaning_zh' => '葡萄',
                'example_sentence' => '我喜欢吃葡萄。',
                'example_translation' => 'I like to eat grapes.',
                'definition' => 'Grape',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一串___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '西瓜',
                'pinyin' => 'xī guā',
                'simplified' => '西瓜',
                'traditional' => '西瓜',
                'part_of_speech' => 'noun',
                'meaning' => 'Watermelon',
                'meaning_zh' => '西瓜',
                'example_sentence' => '夏天吃西瓜。',
                'example_translation' => 'Eat watermelon in summer.',
                'definition' => 'Watermelon',
                'sentences' => ['夏天吃___。', '___很甜。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '梨',
                'pinyin' => 'lí',
                'simplified' => '梨',
                'traditional' => '梨',
                'part_of_speech' => 'noun',
                'meaning' => 'Pear',
                'meaning_zh' => '梨',
                'example_sentence' => '我喜欢吃梨。',
                'example_translation' => 'I like to eat pears.',
                'definition' => 'Pear',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '桃子',
                'pinyin' => 'táo zi',
                'simplified' => '桃子',
                'traditional' => '桃子',
                'part_of_speech' => 'noun',
                'meaning' => 'Peach',
                'meaning_zh' => '桃子',
                'example_sentence' => '我喜欢吃桃子。',
                'example_translation' => 'I like to eat peaches.',
                'definition' => 'Peach',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '草莓',
                'pinyin' => 'cǎo méi',
                'simplified' => '草莓',
                'traditional' => '草莓',
                'part_of_speech' => 'noun',
                'meaning' => 'Strawberry',
                'meaning_zh' => '草莓',
                'example_sentence' => '我喜欢吃草莓。',
                'example_translation' => 'I like to eat strawberries.',
                'definition' => 'Strawberry',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一颗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '蛋糕',
                'pinyin' => 'dàn gāo',
                'simplified' => '蛋糕',
                'traditional' => '蛋糕',
                'part_of_speech' => 'noun',
                'meaning' => 'Cake',
                'meaning_zh' => '蛋糕',
                'example_sentence' => '生日蛋糕。',
                'example_translation' => 'Birthday cake.',
                'definition' => 'Cake',
                'sentences' => ['生日___。', '___很好吃。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '糖果',
                'pinyin' => 'táng guǒ',
                'simplified' => '糖果',
                'traditional' => '糖果',
                'part_of_speech' => 'noun',
                'meaning' => 'Candy / Sweet',
                'meaning_zh' => '糖果',
                'example_sentence' => '我喜欢吃糖果。',
                'example_translation' => 'I like to eat candy.',
                'definition' => 'Candy, sweet',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一颗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '巧克力',
                'pinyin' => 'qiǎo kè lì',
                'simplified' => '巧克力',
                'traditional' => '巧克力',
                'part_of_speech' => 'noun',
                'meaning' => 'Chocolate',
                'meaning_zh' => '巧克力',
                'example_sentence' => '我喜欢吃巧克力。',
                'example_translation' => 'I like to eat chocolate.',
                'definition' => 'Chocolate',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '冰淇淋',
                'pinyin' => 'bīng qí lín',
                'simplified' => '冰淇淋',
                'traditional' => '冰淇淋',
                'part_of_speech' => 'noun',
                'meaning' => 'Ice cream',
                'meaning_zh' => '冰淇淋',
                'example_sentence' => '我喜欢吃冰淇淋。',
                'example_translation' => 'I like to eat ice cream.',
                'definition' => 'Ice cream',
                'sentences' => ['我喜欢吃___。', '___很凉。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '汤',
                'pinyin' => 'tāng',
                'simplified' => '汤',
                'traditional' => '湯',
                'part_of_speech' => 'noun',
                'meaning' => 'Soup',
                'meaning_zh' => '汤',
                'example_sentence' => '我喝汤。',
                'example_translation' => 'I drink soup.',
                'definition' => 'Soup',
                'sentences' => ['我喝___。', '___很热。', '一碗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '粥',
                'pinyin' => 'zhōu',
                'simplified' => '粥',
                'traditional' => '粥',
                'part_of_speech' => 'noun',
                'meaning' => 'Porridge / Congee',
                'meaning_zh' => '粥',
                'example_sentence' => '我早上喝粥。',
                'example_translation' => 'I drink porridge in the morning.',
                'definition' => 'Porridge, congee',
                'sentences' => ['我早上喝___。', '___很好喝。', '一碗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '饼干',
                'pinyin' => 'bǐng gān',
                'simplified' => '饼干',
                'traditional' => '餅乾',
                'part_of_speech' => 'noun',
                'meaning' => 'Biscuit / Cookie',
                'meaning_zh' => '饼干',
                'example_sentence' => '我喜欢吃饼干。',
                'example_translation' => 'I like to eat biscuits.',
                'definition' => 'Biscuit, cookie',
                'sentences' => ['我喜欢吃___。', '___很脆。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '零食',
                'pinyin' => 'líng shí',
                'simplified' => '零食',
                'traditional' => '零食',
                'part_of_speech' => 'noun',
                'meaning' => 'Snack / Snacks',
                'meaning_zh' => '零食',
                'example_sentence' => '我喜欢吃零食。',
                'example_translation' => 'I like to eat snacks.',
                'definition' => 'Snack, snacks',
                'sentences' => ['我喜欢吃___。', '___很好吃。', '买___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '早餐',
                'pinyin' => 'zǎo cān',
                'simplified' => '早餐',
                'traditional' => '早餐',
                'part_of_speech' => 'noun',
                'meaning' => 'Breakfast',
                'meaning_zh' => '早餐',
                'example_sentence' => '我吃早餐。',
                'example_translation' => 'I eat breakfast.',
                'definition' => 'Breakfast',
                'sentences' => ['我吃___。', '___很重要。', '做___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 20,
                'word' => '午餐',
                'pinyin' => 'wǔ cān',
                'simplified' => '午餐',
                'traditional' => '午餐',
                'part_of_speech' => 'noun',
                'meaning' => 'Lunch',
                'meaning_zh' => '午餐',
                'example_sentence' => '我吃午餐。',
                'example_translation' => 'I eat lunch.',
                'definition' => 'Lunch',
                'sentences' => ['我吃___。', '___时间。', '准备___。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 21: The Weather and Nature (天气和自然) - 20 words
        $weatherNatureVocab = [
            [
                'topic_id' => 21,
                'word' => '天气',
                'pinyin' => 'tiān qì',
                'simplified' => '天气',
                'traditional' => '天氣',
                'part_of_speech' => 'noun',
                'meaning' => 'Weather',
                'meaning_zh' => '天气',
                'example_sentence' => '今天天气很好。',
                'example_translation' => 'The weather is very nice today.',
                'definition' => 'Weather',
                'sentences' => ['今天___很好。', '___怎么样？', '___预报。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '晴',
                'pinyin' => 'qíng',
                'simplified' => '晴',
                'traditional' => '晴',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sunny / Clear',
                'meaning_zh' => '晴',
                'example_sentence' => '今天是晴天。',
                'example_translation' => 'Today is sunny.',
                'definition' => 'Sunny, clear (weather)',
                'sentences' => ['今天是___天。', '___空万里。', '转___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '阴',
                'pinyin' => 'yīn',
                'simplified' => '阴',
                'traditional' => '陰',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cloudy / Overcast',
                'meaning_zh' => '阴',
                'example_sentence' => '今天是阴天。',
                'example_translation' => 'Today is cloudy.',
                'definition' => 'Cloudy, overcast',
                'sentences' => ['今天是___天。', '天___沉沉。', '___雨。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '雨',
                'pinyin' => 'yǔ',
                'simplified' => '雨',
                'traditional' => '雨',
                'part_of_speech' => 'noun',
                'meaning' => 'Rain',
                'meaning_zh' => '雨',
                'example_sentence' => '外面下雨了。',
                'example_translation' => 'It\'s raining outside.',
                'definition' => 'Rain',
                'sentences' => ['外面下___了。', '___很大。', '___天。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '雪',
                'pinyin' => 'xuě',
                'simplified' => '雪',
                'traditional' => '雪',
                'part_of_speech' => 'noun',
                'meaning' => 'Snow',
                'meaning_zh' => '雪',
                'example_sentence' => '外面下雪了。',
                'example_translation' => 'It\'s snowing outside.',
                'definition' => 'Snow',
                'sentences' => ['外面下___了。', '___很大。', '___天。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '风',
                'pinyin' => 'fēng',
                'simplified' => '风',
                'traditional' => '風',
                'part_of_speech' => 'noun',
                'meaning' => 'Wind',
                'meaning_zh' => '风',
                'example_sentence' => '今天风很大。',
                'example_translation' => 'The wind is very strong today.',
                'definition' => 'Wind',
                'sentences' => ['今天___很大。', '___景。', '刮___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '云',
                'pinyin' => 'yún',
                'simplified' => '云',
                'traditional' => '雲',
                'part_of_speech' => 'noun',
                'meaning' => 'Cloud',
                'meaning_zh' => '云',
                'example_sentence' => '天上有云。',
                'example_translation' => 'There are clouds in the sky.',
                'definition' => 'Cloud',
                'sentences' => ['天上有___。', '___很多。', '白___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '太阳',
                'pinyin' => 'tài yáng',
                'simplified' => '太阳',
                'traditional' => '太陽',
                'part_of_speech' => 'noun',
                'meaning' => 'Sun',
                'meaning_zh' => '太阳',
                'example_sentence' => '太阳出来了。',
                'example_translation' => 'The sun has come out.',
                'definition' => 'Sun',
                'sentences' => ['___出来了。', '___很热。', '晒___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '月亮',
                'pinyin' => 'yuè liang',
                'simplified' => '月亮',
                'traditional' => '月亮',
                'part_of_speech' => 'noun',
                'meaning' => 'Moon',
                'meaning_zh' => '月亮',
                'example_sentence' => '月亮很圆。',
                'example_translation' => 'The moon is very round.',
                'definition' => 'Moon',
                'sentences' => ['___很圆。', '___很亮。', '看___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '星星',
                'pinyin' => 'xīng xing',
                'simplified' => '星星',
                'traditional' => '星星',
                'part_of_speech' => 'noun',
                'meaning' => 'Star',
                'meaning_zh' => '星星',
                'example_sentence' => '天上有很多星星。',
                'example_translation' => 'There are many stars in the sky.',
                'definition' => 'Star',
                'sentences' => ['天上有很多___。', '___很亮。', '看___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '山',
                'pinyin' => 'shān',
                'simplified' => '山',
                'traditional' => '山',
                'part_of_speech' => 'noun',
                'meaning' => 'Mountain / Hill',
                'meaning_zh' => '山',
                'example_sentence' => '我爬山。',
                'example_translation' => 'I climb mountains.',
                'definition' => 'Mountain, hill',
                'sentences' => ['我爬___。', '___很高。', '___顶。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '河',
                'pinyin' => 'hé',
                'simplified' => '河',
                'traditional' => '河',
                'part_of_speech' => 'noun',
                'meaning' => 'River',
                'meaning_zh' => '河',
                'example_sentence' => '河水很清。',
                'example_translation' => 'The river water is very clear.',
                'definition' => 'River',
                'sentences' => ['___水很清。', '___边。', '过___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '海',
                'pinyin' => 'hǎi',
                'simplified' => '海',
                'traditional' => '海',
                'part_of_speech' => 'noun',
                'meaning' => 'Sea / Ocean',
                'meaning_zh' => '海',
                'example_sentence' => '我去海边。',
                'example_translation' => 'I go to the seaside.',
                'definition' => 'Sea, ocean',
                'sentences' => ['我去___边。', '___水。', '大___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '湖',
                'pinyin' => 'hú',
                'simplified' => '湖',
                'traditional' => '湖',
                'part_of_speech' => 'noun',
                'meaning' => 'Lake',
                'meaning_zh' => '湖',
                'example_sentence' => '湖水很清。',
                'example_translation' => 'The lake water is very clear.',
                'definition' => 'Lake',
                'sentences' => ['___水很清。', '___边。', '___泊。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '树',
                'pinyin' => 'shù',
                'simplified' => '树',
                'traditional' => '樹',
                'part_of_speech' => 'noun',
                'meaning' => 'Tree',
                'meaning_zh' => '树',
                'example_sentence' => '树很高。',
                'example_translation' => 'The tree is very tall.',
                'definition' => 'Tree',
                'sentences' => ['___很高。', '___木。', '种___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '花',
                'pinyin' => 'huā',
                'simplified' => '花',
                'traditional' => '花',
                'part_of_speech' => 'noun',
                'meaning' => 'Flower',
                'meaning_zh' => '花',
                'example_sentence' => '花很漂亮。',
                'example_translation' => 'The flowers are very beautiful.',
                'definition' => 'Flower',
                'sentences' => ['___很漂亮。', '___园。', '一朵___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '草',
                'pinyin' => 'cǎo',
                'simplified' => '草',
                'traditional' => '草',
                'part_of_speech' => 'noun',
                'meaning' => 'Grass',
                'meaning_zh' => '草',
                'example_sentence' => '草很绿。',
                'example_translation' => 'The grass is very green.',
                'definition' => 'Grass',
                'sentences' => ['___很绿。', '___地。', '一根___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '石头',
                'pinyin' => 'shí tou',
                'simplified' => '石头',
                'traditional' => '石頭',
                'part_of_speech' => 'noun',
                'meaning' => 'Stone / Rock',
                'meaning_zh' => '石头',
                'example_sentence' => '这是石头。',
                'example_translation' => 'This is a stone.',
                'definition' => 'Stone, rock',
                'sentences' => ['这是___。', '___很硬。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '土',
                'pinyin' => 'tǔ',
                'simplified' => '土',
                'traditional' => '土',
                'part_of_speech' => 'noun',
                'meaning' => 'Soil / Earth',
                'meaning_zh' => '土',
                'example_sentence' => '土很湿。',
                'example_translation' => 'The soil is very wet.',
                'definition' => 'Soil, earth, dirt',
                'sentences' => ['___很湿。', '___地。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 21,
                'word' => '火',
                'pinyin' => 'huǒ',
                'simplified' => '火',
                'traditional' => '火',
                'part_of_speech' => 'noun',
                'meaning' => 'Fire',
                'meaning_zh' => '火',
                'example_sentence' => '火很大。',
                'example_translation' => 'The fire is very big.',
                'definition' => 'Fire',
                'sentences' => ['___很大。', '___灾。', '生___。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 22: Useful Verbs (常用动词) - 30 words
        $usefulVerbsVocab = [
            [
                'topic_id' => 22,
                'word' => '能',
                'pinyin' => 'néng',
                'simplified' => '能',
                'traditional' => '能',
                'part_of_speech' => 'verb',
                'meaning' => 'Can / To be able to',
                'meaning_zh' => '能',
                'example_sentence' => '我能说中文。',
                'example_translation' => 'I can speak Chinese.',
                'definition' => 'Can, to be able to',
                'sentences' => ['我___说中文。', '___不能？', '___做。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '会',
                'pinyin' => 'huì',
                'simplified' => '会',
                'traditional' => '會',
                'part_of_speech' => 'verb',
                'meaning' => 'Can / Know how to',
                'meaning_zh' => '会',
                'example_sentence' => '我会说中文。',
                'example_translation' => 'I can speak Chinese.',
                'definition' => 'Can, know how to, will',
                'sentences' => ['我___说中文。', '___不会？', '___做。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '要',
                'pinyin' => 'yào',
                'simplified' => '要',
                'traditional' => '要',
                'part_of_speech' => 'verb',
                'meaning' => 'To want / Will',
                'meaning_zh' => '要',
                'example_sentence' => '我要学习。',
                'example_translation' => 'I want to study.',
                'definition' => 'To want, will, going to',
                'sentences' => ['我___学习。', '___不要？', '___去。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '想',
                'pinyin' => 'xiǎng',
                'simplified' => '想',
                'traditional' => '想',
                'part_of_speech' => 'verb',
                'meaning' => 'To want / To think / To miss',
                'meaning_zh' => '想',
                'example_sentence' => '我想去中国。',
                'example_translation' => 'I want to go to China.',
                'definition' => 'To want, to think, to miss',
                'sentences' => ['我___去中国。', '___什么？', '___家。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '可以',
                'pinyin' => 'kě yǐ',
                'simplified' => '可以',
                'traditional' => '可以',
                'part_of_speech' => 'verb',
                'meaning' => 'Can / May',
                'meaning_zh' => '可以',
                'example_sentence' => '可以进来吗？',
                'example_translation' => 'May I come in?',
                'definition' => 'Can, may, possible',
                'sentences' => ['___进来吗？', '___的。', '___不可以？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '知道',
                'pinyin' => 'zhī dào',
                'simplified' => '知道',
                'traditional' => '知道',
                'part_of_speech' => 'verb',
                'meaning' => 'To know',
                'meaning_zh' => '知道',
                'example_sentence' => '我知道了。',
                'example_translation' => 'I know.',
                'definition' => 'To know, to be aware of',
                'sentences' => ['我___了。', '你___吗？', '不___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '觉得',
                'pinyin' => 'jué de',
                'simplified' => '觉得',
                'traditional' => '覺得',
                'part_of_speech' => 'verb',
                'meaning' => 'To feel / To think',
                'meaning_zh' => '觉得',
                'example_sentence' => '我觉得很好。',
                'example_translation' => 'I think it\'s very good.',
                'definition' => 'To feel, to think',
                'sentences' => ['我___很好。', '你___呢？', '___怎么样？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '喜欢',
                'pinyin' => 'xǐ huan',
                'simplified' => '喜欢',
                'traditional' => '喜歡',
                'part_of_speech' => 'verb',
                'meaning' => 'To like',
                'meaning_zh' => '喜欢',
                'example_sentence' => '我喜欢中文。',
                'example_translation' => 'I like Chinese.',
                'definition' => 'To like, to be fond of',
                'sentences' => ['我___中文。', '___吃。', '不___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '帮助',
                'pinyin' => 'bāng zhù',
                'simplified' => '帮助',
                'traditional' => '幫助',
                'part_of_speech' => 'verb',
                'meaning' => 'To help',
                'meaning_zh' => '帮助',
                'example_sentence' => '请帮助我。',
                'example_translation' => 'Please help me.',
                'definition' => 'To help, to assist',
                'sentences' => ['请___我。', '___他。', '需要___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '等',
                'pinyin' => 'děng',
                'simplified' => '等',
                'traditional' => '等',
                'part_of_speech' => 'verb',
                'meaning' => 'To wait',
                'meaning_zh' => '等',
                'example_sentence' => '我等你。',
                'example_translation' => 'I wait for you.',
                'definition' => 'To wait, to wait for',
                'sentences' => ['我___你。', '___一下。', '___人。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '找',
                'pinyin' => 'zhǎo',
                'simplified' => '找',
                'traditional' => '找',
                'part_of_speech' => 'verb',
                'meaning' => 'To look for / To find',
                'meaning_zh' => '找',
                'example_sentence' => '我找书。',
                'example_translation' => 'I look for a book.',
                'definition' => 'To look for, to find, to seek',
                'sentences' => ['我___书。', '___人。', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '用',
                'pinyin' => 'yòng',
                'simplified' => '用',
                'traditional' => '用',
                'part_of_speech' => 'verb',
                'meaning' => 'To use',
                'meaning_zh' => '用',
                'example_sentence' => '我用筷子。',
                'example_translation' => 'I use chopsticks.',
                'definition' => 'To use',
                'sentences' => ['我___筷子。', '___什么？', '___电脑。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '学',
                'pinyin' => 'xué',
                'simplified' => '学',
                'traditional' => '學',
                'part_of_speech' => 'verb',
                'meaning' => 'To study / To learn',
                'meaning_zh' => '学',
                'example_sentence' => '我学中文。',
                'example_translation' => 'I study Chinese.',
                'definition' => 'To study, to learn',
                'sentences' => ['我___中文。', '___什么？', '___习。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '教',
                'pinyin' => 'jiāo',
                'simplified' => '教',
                'traditional' => '教',
                'part_of_speech' => 'verb',
                'meaning' => 'To teach',
                'meaning_zh' => '教',
                'example_sentence' => '老师教我们。',
                'example_translation' => 'The teacher teaches us.',
                'definition' => 'To teach',
                'sentences' => ['老师___我们。', '___什么？', '___书。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '懂',
                'pinyin' => 'dǒng',
                'simplified' => '懂',
                'traditional' => '懂',
                'part_of_speech' => 'verb',
                'meaning' => 'To understand',
                'meaning_zh' => '懂',
                'example_sentence' => '我懂了。',
                'example_translation' => 'I understand.',
                'definition' => 'To understand',
                'sentences' => ['我___了。', '你___吗？', '不___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '见面',
                'pinyin' => 'jiàn miàn',
                'simplified' => '见面',
                'traditional' => '見面',
                'part_of_speech' => 'verb',
                'meaning' => 'To meet',
                'meaning_zh' => '见面',
                'example_sentence' => '我们见面吧。',
                'example_translation' => 'Let\'s meet.',
                'definition' => 'To meet, to see each other',
                'sentences' => ['我们___吧。', '___了。', '想___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '开始',
                'pinyin' => 'kāi shǐ',
                'simplified' => '开始',
                'traditional' => '開始',
                'part_of_speech' => 'verb',
                'meaning' => 'To begin / To start',
                'meaning_zh' => '开始',
                'example_sentence' => '我们开始吧。',
                'example_translation' => 'Let\'s begin.',
                'definition' => 'To begin, to start',
                'sentences' => ['我们___吧。', '___了。', '___工作。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '结束',
                'pinyin' => 'jié shù',
                'simplified' => '结束',
                'traditional' => '結束',
                'part_of_speech' => 'verb',
                'meaning' => 'To end / To finish',
                'meaning_zh' => '结束',
                'example_sentence' => '工作结束了。',
                'example_translation' => 'Work is finished.',
                'definition' => 'To end, to finish',
                'sentences' => ['工作___了。', '___了。', '___时间。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '准备',
                'pinyin' => 'zhǔn bèi',
                'simplified' => '准备',
                'traditional' => '準備',
                'part_of_speech' => 'verb',
                'meaning' => 'To prepare',
                'meaning_zh' => '准备',
                'example_sentence' => '我准备考试。',
                'example_translation' => 'I prepare for the exam.',
                'definition' => 'To prepare, to get ready',
                'sentences' => ['我___考试。', '___什么？', '___好了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '介绍',
                'pinyin' => 'jiè shào',
                'simplified' => '介绍',
                'traditional' => '介紹',
                'part_of_speech' => 'verb',
                'meaning' => 'To introduce',
                'meaning_zh' => '介绍',
                'example_sentence' => '我介绍一下。',
                'example_translation' => 'Let me introduce.',
                'definition' => 'To introduce, to present',
                'sentences' => ['我___一下。', '___自己。', '___朋友。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '送',
                'pinyin' => 'sòng',
                'simplified' => '送',
                'traditional' => '送',
                'part_of_speech' => 'verb',
                'meaning' => 'To give / To deliver / To see off',
                'meaning_zh' => '送',
                'example_sentence' => '我送你礼物。',
                'example_translation' => 'I give you a gift.',
                'definition' => 'To give, to deliver, to see off',
                'sentences' => ['我___你礼物。', '___人。', '___东西。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '拿',
                'pinyin' => 'ná',
                'simplified' => '拿',
                'traditional' => '拿',
                'part_of_speech' => 'verb',
                'meaning' => 'To take / To hold',
                'meaning_zh' => '拿',
                'example_sentence' => '我拿书。',
                'example_translation' => 'I take a book.',
                'definition' => 'To take, to hold, to carry',
                'sentences' => ['我___书。', '___什么？', '___着。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '放',
                'pinyin' => 'fàng',
                'simplified' => '放',
                'traditional' => '放',
                'part_of_speech' => 'verb',
                'meaning' => 'To put / To place',
                'meaning_zh' => '放',
                'example_sentence' => '我放书。',
                'example_translation' => 'I put the book.',
                'definition' => 'To put, to place, to release',
                'sentences' => ['我___书。', '___在哪儿？', '___心。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '进',
                'pinyin' => 'jìn',
                'simplified' => '进',
                'traditional' => '進',
                'part_of_speech' => 'verb',
                'meaning' => 'To enter / To come in',
                'meaning_zh' => '进',
                'example_sentence' => '请进。',
                'example_translation' => 'Please come in.',
                'definition' => 'To enter, to come in',
                'sentences' => ['请___。', '___来。', '___去。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '出',
                'pinyin' => 'chū',
                'simplified' => '出',
                'traditional' => '出',
                'part_of_speech' => 'verb',
                'meaning' => 'To go out / To exit',
                'meaning_zh' => '出',
                'example_sentence' => '我出去。',
                'example_translation' => 'I go out.',
                'definition' => 'To go out, to exit, to come out',
                'sentences' => ['我___去。', '___来。', '___门。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '上',
                'pinyin' => 'shàng',
                'simplified' => '上',
                'traditional' => '上',
                'part_of_speech' => 'verb',
                'meaning' => 'To go up / To get on',
                'meaning_zh' => '上',
                'example_sentence' => '我上楼。',
                'example_translation' => 'I go upstairs.',
                'definition' => 'To go up, to get on, to attend',
                'sentences' => ['我___楼。', '___车。', '___课。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '下',
                'pinyin' => 'xià',
                'simplified' => '下',
                'traditional' => '下',
                'part_of_speech' => 'verb',
                'meaning' => 'To go down / To get off',
                'meaning_zh' => '下',
                'example_sentence' => '我下楼。',
                'example_translation' => 'I go downstairs.',
                'definition' => 'To go down, to get off',
                'sentences' => ['我___楼。', '___车。', '___课。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '回',
                'pinyin' => 'huí',
                'simplified' => '回',
                'traditional' => '回',
                'part_of_speech' => 'verb',
                'meaning' => 'To return / To go back',
                'meaning_zh' => '回',
                'example_sentence' => '我回家。',
                'example_translation' => 'I go home.',
                'definition' => 'To return, to go back',
                'sentences' => ['我___家。', '___来。', '___去。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '到',
                'pinyin' => 'dào',
                'simplified' => '到',
                'traditional' => '到',
                'part_of_speech' => 'verb',
                'meaning' => 'To arrive / To reach',
                'meaning_zh' => '到',
                'example_sentence' => '我到了。',
                'example_translation' => 'I arrived.',
                'definition' => 'To arrive, to reach, to',
                'sentences' => ['我___了。', '___家。', '___哪儿？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 22,
                'word' => '过',
                'pinyin' => 'guò',
                'simplified' => '过',
                'traditional' => '過',
                'part_of_speech' => 'verb',
                'meaning' => 'To pass / To cross',
                'meaning_zh' => '过',
                'example_sentence' => '我过马路。',
                'example_translation' => 'I cross the street.',
                'definition' => 'To pass, to cross, to spend (time)',
                'sentences' => ['我___马路。', '___来。', '___去。'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($foodDrinksVocab, $weatherNatureVocab, $usefulVerbsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
