<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyTranslation;
use Illuminate\Database\Seeder;

class Hsk1VocabularySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Disable foreign key checks
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Delete old vocabularies and translations
        VocabularyTranslation::truncate();
        Vocabulary::truncate();
        
        // Re-enable foreign key checks
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        // Topic 1: Hello and Goodbye (16 words)
        $helloGoodbyeVocab = [
            [
                'topic_id' => 1,
                'word' => '你好',
                'pinyin' => 'nǐ hǎo',
                'simplified' => '你好',
                'traditional' => '你好',
                'part_of_speech' => 'phrase',
                'meaning' => 'Hello',
                'meaning_zh' => '你好',
                'example_sentence' => '你好，我叫李明。',
                'example_translation' => 'Hello, my name is Li Ming.',
                'definition' => 'A common greeting',
                'stroke_count' => 9,
                'tone_pattern' => '3-3',
                'sentences' => ['___，你叫什么名字？', '早上见面时说___。', '___，很高兴认识你。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '再见',
                'pinyin' => 'zài jiàn',
                'simplified' => '再见',
                'traditional' => '再見',
                'part_of_speech' => 'phrase',
                'meaning' => 'Goodbye',
                'meaning_zh' => '再见',
                'example_sentence' => '再见，明天见！',
                'example_translation' => 'Goodbye, see you tomorrow!',
                'definition' => 'A farewell expression',
                'stroke_count' => 10,
                'tone_pattern' => '4-4',
                'sentences' => ['___，明天见！', '我要走了，___！', '下课后说___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '谢谢',
                'pinyin' => 'xiè xie',
                'simplified' => '谢谢',
                'traditional' => '謝謝',
                'part_of_speech' => 'phrase',
                'meaning' => 'Thank you',
                'meaning_zh' => '谢谢',
                'example_sentence' => '谢谢你的帮助。',
                'example_translation' => 'Thank you for your help.',
                'definition' => 'Expression of gratitude',
                'stroke_count' => 17,
                'tone_pattern' => '4-0',
                'sentences' => ['___你的帮助。', '非常___你。', '___，我很喜欢这个礼物。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '不客气',
                'pinyin' => 'bú kè qi',
                'simplified' => '不客气',
                'traditional' => '不客氣',
                'part_of_speech' => 'phrase',
                'meaning' => "You're welcome",
                'meaning_zh' => '不客气',
                'example_sentence' => '不客气，应该的。',
                'example_translation' => "You're welcome, it's my pleasure.",
                'definition' => 'Polite response to thanks',
                'stroke_count' => 14,
                'sentences' => ['___，应该的。', '谢谢你！___。', '___，不用谢。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '对不起',
                'pinyin' => 'duì bu qǐ',
                'simplified' => '对不起',
                'traditional' => '對不起',
                'part_of_speech' => 'phrase',
                'meaning' => 'Sorry',
                'meaning_zh' => '对不起',
                'example_sentence' => '对不起，我来晚了。',
                'example_translation' => 'Sorry, I came late.',
                'definition' => 'Apology expression',
                'sentences' => ['___，我来晚了。', '___，我错了。', '___，打扰一下。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '没关系',
                'pinyin' => 'méi guān xi',
                'simplified' => '没关系',
                'traditional' => '沒關係',
                'part_of_speech' => 'phrase',
                'meaning' => "It's okay / Never mind",
                'meaning_zh' => '没关系',
                'example_sentence' => '没关系，别担心。',
                'example_translation' => "It's okay, don't worry.",
                'definition' => "Response to apology",
                'sentences' => ['___，别担心。', '对不起！___。', '___，下次注意就好。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '请',
                'pinyin' => 'qǐng',
                'simplified' => '请',
                'traditional' => '請',
                'part_of_speech' => 'verb',
                'meaning' => 'Please / To invite',
                'meaning_zh' => '请',
                'example_sentence' => '请进。',
                'example_translation' => 'Please come in.',
                'definition' => 'Polite request word',
                'sentences' => ['___进。', '___坐。', '___问一下。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '早上好',
                'pinyin' => 'zǎo shang hǎo',
                'simplified' => '早上好',
                'traditional' => '早上好',
                'part_of_speech' => 'phrase',
                'meaning' => 'Good morning',
                'meaning_zh' => '早上好',
                'example_sentence' => '早上好，今天天气真好！',
                'example_translation' => 'Good morning, the weather is great today!',
                'definition' => 'Morning greeting',
                'sentences' => ['___，今天天气真好！', '___，睡得好吗？', '每天早上说___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '晚安',
                'pinyin' => 'wǎn ān',
                'simplified' => '晚安',
                'traditional' => '晚安',
                'part_of_speech' => 'phrase',
                'meaning' => 'Good night',
                'meaning_zh' => '晚安',
                'example_sentence' => '晚安，做个好梦。',
                'example_translation' => 'Good night, sweet dreams.',
                'definition' => 'Night-time farewell',
                'sentences' => ['___，做个好梦。', '睡觉前说___。', '___，明天见。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '您好',
                'pinyin' => 'nín hǎo',
                'simplified' => '您好',
                'traditional' => '您好',
                'part_of_speech' => 'phrase',
                'meaning' => 'Hello (formal)',
                'meaning_zh' => '您好',
                'example_sentence' => '您好，请问您贵姓？',
                'example_translation' => 'Hello, may I ask your surname?',
                'definition' => 'Formal greeting',
                'sentences' => ['___，请问您贵姓？', '对长辈说___。', '___，很高兴见到您。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '欢迎',
                'pinyin' => 'huān yíng',
                'simplified' => '欢迎',
                'traditional' => '歡迎',
                'part_of_speech' => 'verb',
                'meaning' => 'Welcome',
                'meaning_zh' => '欢迎',
                'example_sentence' => '欢迎来到中国！',
                'example_translation' => 'Welcome to China!',
                'definition' => 'To welcome someone',
                'sentences' => ['___来到中国！', '___光临！', '___你的到来。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '好',
                'pinyin' => 'hǎo',
                'simplified' => '好',
                'traditional' => '好',
                'part_of_speech' => 'adjective',
                'meaning' => 'Good / Okay',
                'meaning_zh' => '好',
                'example_sentence' => '这个主意很好。',
                'example_translation' => 'This idea is very good.',
                'definition' => 'Good, fine, okay',
                'sentences' => ['这个主意很___。', '你___吗？', '今天天气很___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '是',
                'pinyin' => 'shì',
                'simplified' => '是',
                'traditional' => '是',
                'part_of_speech' => 'verb',
                'meaning' => 'To be / Yes',
                'meaning_zh' => '是',
                'example_sentence' => '我是学生。',
                'example_translation' => 'I am a student.',
                'definition' => 'Linking verb "to be"',
                'sentences' => ['我___学生。', '他___老师。', '这___我的书。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '不是',
                'pinyin' => 'bú shì',
                'simplified' => '不是',
                'traditional' => '不是',
                'part_of_speech' => 'verb',
                'meaning' => "To not be / It's not",
                'meaning_zh' => '不是',
                'example_sentence' => '我不是老师。',
                'example_translation' => 'I am not a teacher.',
                'definition' => 'Negative form of 是',
                'sentences' => ['我___老师。', '这___我的。', '他___中国人。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '吗',
                'pinyin' => 'ma',
                'simplified' => '吗',
                'traditional' => '嗎',
                'part_of_speech' => 'particle',
                'meaning' => 'Question particle',
                'meaning_zh' => '吗',
                'example_sentence' => '你好吗？',
                'example_translation' => 'How are you?',
                'definition' => 'Particle forming yes/no questions',
                'sentences' => ['你好___？', '你是学生___？', '这是你的___？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '呢',
                'pinyin' => 'ne',
                'simplified' => '呢',
                'traditional' => '呢',
                'part_of_speech' => 'particle',
                'meaning' => 'And / What about',
                'meaning_zh' => '呢',
                'example_sentence' => '我很好，你呢？',
                'example_translation' => "I'm fine, and you?",
                'definition' => 'Particle for reciprocal questions',
                'sentences' => ['我很好，你___？', '他是学生，你___？', '这是我的，你的___？'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 2: People (14 words)
        $peopleVocab = [
            [
                'topic_id' => 2,
                'word' => '我',
                'pinyin' => 'wǒ',
                'simplified' => '我',
                'traditional' => '我',
                'part_of_speech' => 'pronoun',
                'meaning' => 'I / Me',
                'meaning_zh' => '我',
                'example_sentence' => '我是中国人。',
                'example_translation' => 'I am Chinese.',
                'definition' => 'First person singular pronoun',
                'sentences' => ['___是中国人。', '___叫李明。', '___很高兴。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '你',
                'pinyin' => 'nǐ',
                'simplified' => '你',
                'traditional' => '你',
                'part_of_speech' => 'pronoun',
                'meaning' => 'You (singular)',
                'meaning_zh' => '你',
                'example_sentence' => '你是学生吗？',
                'example_translation' => 'Are you a student?',
                'definition' => 'Second person singular pronoun',
                'sentences' => ['___好。', '___是学生吗？', '___叫什么名字？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '他',
                'pinyin' => 'tā',
                'simplified' => '他',
                'traditional' => '他',
                'part_of_speech' => 'pronoun',
                'meaning' => 'He / Him',
                'meaning_zh' => '他',
                'example_sentence' => '他是我的朋友。',
                'example_translation' => 'He is my friend.',
                'definition' => 'Third person singular pronoun (male)',
                'sentences' => ['___是我的朋友。', '___是老师。', '___很忙。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '她',
                'pinyin' => 'tā',
                'simplified' => '她',
                'traditional' => '她',
                'part_of_speech' => 'pronoun',
                'meaning' => 'She / Her',
                'meaning_zh' => '她',
                'example_sentence' => '她是我的同学。',
                'example_translation' => 'She is my classmate.',
                'definition' => 'Third person singular pronoun (female)',
                'sentences' => ['___是我的同学。', '___很漂亮。', '___是医生。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '我们',
                'pinyin' => 'wǒ men',
                'simplified' => '我们',
                'traditional' => '我們',
                'part_of_speech' => 'pronoun',
                'meaning' => 'We / Us',
                'meaning_zh' => '我们',
                'example_sentence' => '我们是好朋友。',
                'example_translation' => 'We are good friends.',
                'definition' => 'First person plural pronoun',
                'sentences' => ['___是好朋友。', '___一起去吧。', '___都是学生。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '你们',
                'pinyin' => 'nǐ men',
                'simplified' => '你们',
                'traditional' => '你們',
                'part_of_speech' => 'pronoun',
                'meaning' => 'You (plural)',
                'meaning_zh' => '你们',
                'example_sentence' => '你们好！',
                'example_translation' => 'Hello everyone!',
                'definition' => 'Second person plural pronoun',
                'sentences' => ['___好！', '___都是学生吗？', '___在哪里？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '他们',
                'pinyin' => 'tā men',
                'simplified' => '他们',
                'traditional' => '他們',
                'part_of_speech' => 'pronoun',
                'meaning' => 'They / Them',
                'meaning_zh' => '他们',
                'example_sentence' => '他们都是老师。',
                'example_translation' => 'They are all teachers.',
                'definition' => 'Third person plural pronoun',
                'sentences' => ['___都是老师。', '___在教室。', '___很忙。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '谁',
                'pinyin' => 'shéi / shuí',
                'simplified' => '谁',
                'traditional' => '誰',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Who',
                'meaning_zh' => '谁',
                'example_sentence' => '他是谁？',
                'example_translation' => 'Who is he?',
                'definition' => 'Interrogative pronoun for people',
                'sentences' => ['他是___？', '___来了？', '___的书？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '人',
                'pinyin' => 'rén',
                'simplified' => '人',
                'traditional' => '人',
                'part_of_speech' => 'noun',
                'meaning' => 'Person / People',
                'meaning_zh' => '人',
                'example_sentence' => '这里有很多人。',
                'example_translation' => 'There are many people here.',
                'definition' => 'Human being, person',
                'sentences' => ['这里有很多___。', '中国___。', '好___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '朋友',
                'pinyin' => 'péng you',
                'simplified' => '朋友',
                'traditional' => '朋友',
                'part_of_speech' => 'noun',
                'meaning' => 'Friend',
                'meaning_zh' => '朋友',
                'example_sentence' => '他是我的好朋友。',
                'example_translation' => 'He is my good friend.',
                'definition' => 'A person one knows well',
                'sentences' => ['他是我的___。', '好___。', '我有很多___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '老师',
                'pinyin' => 'lǎo shī',
                'simplified' => '老师',
                'traditional' => '老師',
                'part_of_speech' => 'noun',
                'meaning' => 'Teacher',
                'meaning_zh' => '老师',
                'example_sentence' => '她是我们的老师。',
                'example_translation' => 'She is our teacher.',
                'definition' => 'A person who teaches',
                'sentences' => ['她是我们的___。', '___好！', '中文___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '学生',
                'pinyin' => 'xué sheng',
                'simplified' => '学生',
                'traditional' => '學生',
                'part_of_speech' => 'noun',
                'meaning' => 'Student',
                'meaning_zh' => '学生',
                'example_sentence' => '我是学生。',
                'example_translation' => 'I am a student.',
                'definition' => 'A person who studies',
                'sentences' => ['我是___。', '中国___。', '大___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '名字',
                'pinyin' => 'míng zi',
                'simplified' => '名字',
                'traditional' => '名字',
                'part_of_speech' => 'noun',
                'meaning' => 'Name',
                'meaning_zh' => '名字',
                'example_sentence' => '你叫什么名字？',
                'example_translation' => 'What is your name?',
                'definition' => "A person's name",
                'sentences' => ['你叫什么___？', '我的___是李明。', '他的___很好听。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '什么',
                'pinyin' => 'shén me',
                'simplified' => '什么',
                'traditional' => '什麼',
                'part_of_speech' => 'pronoun',
                'meaning' => 'What',
                'meaning_zh' => '什么',
                'example_sentence' => '这是什么？',
                'example_translation' => 'What is this?',
                'definition' => 'Interrogative pronoun',
                'sentences' => ['这是___？', '你吃___？', '___时候？'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($helloGoodbyeVocab, $peopleVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
