<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk1Topics23to25Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 23: School (学校) - 25 words
        $schoolVocab = [
            [
                'topic_id' => 23,
                'word' => '学校',
                'pinyin' => 'xué xiào',
                'simplified' => '学校',
                'traditional' => '學校',
                'part_of_speech' => 'noun',
                'meaning' => 'School',
                'meaning_zh' => '学校',
                'example_sentence' => '我在学校。',
                'example_translation' => 'I am at school.',
                'definition' => 'School',
                'sentences' => ['我在___。', '___很大。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '大学',
                'pinyin' => 'dà xué',
                'simplified' => '大学',
                'traditional' => '大學',
                'part_of_speech' => 'noun',
                'meaning' => 'University / College',
                'meaning_zh' => '大学',
                'example_sentence' => '我上大学。',
                'example_translation' => 'I attend university.',
                'definition' => 'University, college',
                'sentences' => ['我上___。', '___生活。', '读___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '中学',
                'pinyin' => 'zhōng xué',
                'simplified' => '中学',
                'traditional' => '中學',
                'part_of_speech' => 'noun',
                'meaning' => 'Middle school / High school',
                'meaning_zh' => '中学',
                'example_sentence' => '我在中学学习。',
                'example_translation' => 'I study in middle school.',
                'definition' => 'Middle school, high school',
                'sentences' => ['我在___学习。', '___生。', '___老师。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '小学',
                'pinyin' => 'xiǎo xué',
                'simplified' => '小学',
                'traditional' => '小學',
                'part_of_speech' => 'noun',
                'meaning' => 'Primary school / Elementary school',
                'meaning_zh' => '小学',
                'example_sentence' => '我的孩子上小学。',
                'example_translation' => 'My child attends primary school.',
                'definition' => 'Primary school, elementary school',
                'sentences' => ['我的孩子上___。', '___生。', '___老师。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '教室',
                'pinyin' => 'jiào shì',
                'simplified' => '教室',
                'traditional' => '教室',
                'part_of_speech' => 'noun',
                'meaning' => 'Classroom',
                'meaning_zh' => '教室',
                'example_sentence' => '我在教室里。',
                'example_translation' => 'I am in the classroom.',
                'definition' => 'Classroom',
                'sentences' => ['我在___里。', '___很大。', '进___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '课',
                'pinyin' => 'kè',
                'simplified' => '课',
                'traditional' => '課',
                'part_of_speech' => 'noun',
                'meaning' => 'Class / Lesson',
                'meaning_zh' => '课',
                'example_sentence' => '我上课。',
                'example_translation' => 'I attend class.',
                'definition' => 'Class, lesson, course',
                'sentences' => ['我上___。', '___文。', '下___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '课本',
                'pinyin' => 'kè běn',
                'simplified' => '课本',
                'traditional' => '課本',
                'part_of_speech' => 'noun',
                'meaning' => 'Textbook',
                'meaning_zh' => '课本',
                'example_sentence' => '我有课本。',
                'example_translation' => 'I have a textbook.',
                'definition' => 'Textbook',
                'sentences' => ['我有___。', '___很厚。', '看___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '作业',
                'pinyin' => 'zuò yè',
                'simplified' => '作业',
                'traditional' => '作業',
                'part_of_speech' => 'noun',
                'meaning' => 'Homework / Assignment',
                'meaning_zh' => '作业',
                'example_sentence' => '我做作业。',
                'example_translation' => 'I do homework.',
                'definition' => 'Homework, assignment',
                'sentences' => ['我做___。', '___很多。', '写___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '考试',
                'pinyin' => 'kǎo shì',
                'simplified' => '考试',
                'traditional' => '考試',
                'part_of_speech' => 'noun',
                'meaning' => 'Exam / Test',
                'meaning_zh' => '考试',
                'example_sentence' => '明天考试。',
                'example_translation' => 'There is an exam tomorrow.',
                'definition' => 'Exam, test',
                'sentences' => ['明天___。', '___很难。', '准备___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '问题',
                'pinyin' => 'wèn tí',
                'simplified' => '问题',
                'traditional' => '問題',
                'part_of_speech' => 'noun',
                'meaning' => 'Question / Problem',
                'meaning_zh' => '问题',
                'example_sentence' => '我有问题。',
                'example_translation' => 'I have a question.',
                'definition' => 'Question, problem',
                'sentences' => ['我有___。', '___很难。', '回答___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '回答',
                'pinyin' => 'huí dá',
                'simplified' => '回答',
                'traditional' => '回答',
                'part_of_speech' => 'verb',
                'meaning' => 'To answer',
                'meaning_zh' => '回答',
                'example_sentence' => '我回答问题。',
                'example_translation' => 'I answer the question.',
                'definition' => 'To answer, to reply',
                'sentences' => ['我___问题。', '___对了。', '___不出来。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '黑板',
                'pinyin' => 'hēi bǎn',
                'simplified' => '黑板',
                'traditional' => '黑板',
                'part_of_speech' => 'noun',
                'meaning' => 'Blackboard',
                'meaning_zh' => '黑板',
                'example_sentence' => '黑板上有字。',
                'example_translation' => 'There are characters on the blackboard.',
                'definition' => 'Blackboard',
                'sentences' => ['___上有字。', '擦___。', '___很大。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '桌子',
                'pinyin' => 'zhuō zi',
                'simplified' => '桌子',
                'traditional' => '桌子',
                'part_of_speech' => 'noun',
                'meaning' => 'Desk / Table',
                'meaning_zh' => '桌子',
                'example_sentence' => '桌子上有书。',
                'example_translation' => 'There are books on the desk.',
                'definition' => 'Desk, table',
                'sentences' => ['___上有书。', '___很大。', '课___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '同学',
                'pinyin' => 'tóng xué',
                'simplified' => '同学',
                'traditional' => '同學',
                'part_of_speech' => 'noun',
                'meaning' => 'Classmate',
                'meaning_zh' => '同学',
                'example_sentence' => '他是我的同学。',
                'example_translation' => 'He is my classmate.',
                'definition' => 'Classmate, schoolmate',
                'sentences' => ['他是我的___。', '___们。', '___关系。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '图书馆',
                'pinyin' => 'tú shū guǎn',
                'simplified' => '图书馆',
                'traditional' => '圖書館',
                'part_of_speech' => 'noun',
                'meaning' => 'Library',
                'meaning_zh' => '图书馆',
                'example_sentence' => '我在图书馆看书。',
                'example_translation' => 'I read books in the library.',
                'definition' => 'Library',
                'sentences' => ['我在___看书。', '___很安静。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '操场',
                'pinyin' => 'cāo chǎng',
                'simplified' => '操场',
                'traditional' => '操場',
                'part_of_speech' => 'noun',
                'meaning' => 'Playground / Sports field',
                'meaning_zh' => '操场',
                'example_sentence' => '我们在操场上跑步。',
                'example_translation' => 'We run on the playground.',
                'definition' => 'Playground, sports field',
                'sentences' => ['我们在___上跑步。', '___很大。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '食堂',
                'pinyin' => 'shí táng',
                'simplified' => '食堂',
                'traditional' => '食堂',
                'part_of_speech' => 'noun',
                'meaning' => 'Cafeteria / Dining hall',
                'meaning_zh' => '食堂',
                'example_sentence' => '我在食堂吃饭。',
                'example_translation' => 'I eat in the cafeteria.',
                'definition' => 'Cafeteria, dining hall',
                'sentences' => ['我在___吃饭。', '___的菜。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '宿舍',
                'pinyin' => 'sù shè',
                'simplified' => '宿舍',
                'traditional' => '宿舍',
                'part_of_speech' => 'noun',
                'meaning' => 'Dormitory',
                'meaning_zh' => '宿舍',
                'example_sentence' => '我住宿舍。',
                'example_translation' => 'I live in the dormitory.',
                'definition' => 'Dormitory',
                'sentences' => ['我住___。', '___很干净。', '回___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '办公室',
                'pinyin' => 'bàn gōng shì',
                'simplified' => '办公室',
                'traditional' => '辦公室',
                'part_of_speech' => 'noun',
                'meaning' => 'Office',
                'meaning_zh' => '办公室',
                'example_sentence' => '老师在办公室。',
                'example_translation' => 'The teacher is in the office.',
                'definition' => 'Office',
                'sentences' => ['老师在___。', '___工作。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '汉语',
                'pinyin' => 'hàn yǔ',
                'simplified' => '汉语',
                'traditional' => '漢語',
                'part_of_speech' => 'noun',
                'meaning' => 'Chinese language',
                'meaning_zh' => '汉语',
                'example_sentence' => '我学汉语。',
                'example_translation' => 'I study Chinese.',
                'definition' => 'Chinese language',
                'sentences' => ['我学___。', '___课。', '___水平。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '中文',
                'pinyin' => 'zhōng wén',
                'simplified' => '中文',
                'traditional' => '中文',
                'part_of_speech' => 'noun',
                'meaning' => 'Chinese (written)',
                'meaning_zh' => '中文',
                'example_sentence' => '我会说中文。',
                'example_translation' => 'I can speak Chinese.',
                'definition' => 'Chinese language (written)',
                'sentences' => ['我会说___。', '___名字。', '___书。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '英语',
                'pinyin' => 'yīng yǔ',
                'simplified' => '英语',
                'traditional' => '英語',
                'part_of_speech' => 'noun',
                'meaning' => 'English language',
                'meaning_zh' => '英语',
                'example_sentence' => '我学英语。',
                'example_translation' => 'I study English.',
                'definition' => 'English language',
                'sentences' => ['我学___。', '___课。', '___老师。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '数学',
                'pinyin' => 'shù xué',
                'simplified' => '数学',
                'traditional' => '數學',
                'part_of_speech' => 'noun',
                'meaning' => 'Mathematics',
                'meaning_zh' => '数学',
                'example_sentence' => '我学数学。',
                'example_translation' => 'I study mathematics.',
                'definition' => 'Mathematics',
                'sentences' => ['我学___。', '___题。', '___课。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '历史',
                'pinyin' => 'lì shǐ',
                'simplified' => '历史',
                'traditional' => '歷史',
                'part_of_speech' => 'noun',
                'meaning' => 'History',
                'meaning_zh' => '历史',
                'example_sentence' => '我喜欢历史。',
                'example_translation' => 'I like history.',
                'definition' => 'History',
                'sentences' => ['我喜欢___。', '___课。', '中国___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 23,
                'word' => '音乐',
                'pinyin' => 'yīn yuè',
                'simplified' => '音乐',
                'traditional' => '音樂',
                'part_of_speech' => 'noun',
                'meaning' => 'Music',
                'meaning_zh' => '音乐',
                'example_sentence' => '我喜欢音乐。',
                'example_translation' => 'I like music.',
                'definition' => 'Music',
                'sentences' => ['我喜欢___。', '听___。', '___课。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 24: City (城市) - 25 words
        $cityVocab = [
            [
                'topic_id' => 24,
                'word' => '城市',
                'pinyin' => 'chéng shì',
                'simplified' => '城市',
                'traditional' => '城市',
                'part_of_speech' => 'noun',
                'meaning' => 'City',
                'meaning_zh' => '城市',
                'example_sentence' => '我住在城市里。',
                'example_translation' => 'I live in the city.',
                'definition' => 'City',
                'sentences' => ['我住在___里。', '___很大。', '大___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '街道',
                'pinyin' => 'jiē dào',
                'simplified' => '街道',
                'traditional' => '街道',
                'part_of_speech' => 'noun',
                'meaning' => 'Street',
                'meaning_zh' => '街道',
                'example_sentence' => '街道很干净。',
                'example_translation' => 'The street is very clean.',
                'definition' => 'Street',
                'sentences' => ['___很干净。', '___上。', '过___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '马路',
                'pinyin' => 'mǎ lù',
                'simplified' => '马路',
                'traditional' => '馬路',
                'part_of_speech' => 'noun',
                'meaning' => 'Road / Street',
                'meaning_zh' => '马路',
                'example_sentence' => '过马路要小心。',
                'example_translation' => 'Be careful when crossing the street.',
                'definition' => 'Road, street',
                'sentences' => ['过___要小心。', '___很宽。', '___上。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '商店',
                'pinyin' => 'shāng diàn',
                'simplified' => '商店',
                'traditional' => '商店',
                'part_of_speech' => 'noun',
                'meaning' => 'Shop / Store',
                'meaning_zh' => '商店',
                'example_sentence' => '我去商店买东西。',
                'example_translation' => 'I go to the store to buy things.',
                'definition' => 'Shop, store',
                'sentences' => ['我去___买东西。', '___里。', '小___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '超市',
                'pinyin' => 'chāo shì',
                'simplified' => '超市',
                'traditional' => '超市',
                'part_of_speech' => 'noun',
                'meaning' => 'Supermarket',
                'meaning_zh' => '超市',
                'example_sentence' => '我去超市。',
                'example_translation' => 'I go to the supermarket.',
                'definition' => 'Supermarket',
                'sentences' => ['我去___。', '___购物。', '___很大。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '饭店',
                'pinyin' => 'fàn diàn',
                'simplified' => '饭店',
                'traditional' => '飯店',
                'part_of_speech' => 'noun',
                'meaning' => 'Restaurant / Hotel',
                'meaning_zh' => '饭店',
                'example_sentence' => '我们去饭店吃饭。',
                'example_translation' => 'We go to the restaurant to eat.',
                'definition' => 'Restaurant, hotel',
                'sentences' => ['我们去___吃饭。', '___很大。', '___服务。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '宾馆',
                'pinyin' => 'bīn guǎn',
                'simplified' => '宾馆',
                'traditional' => '賓館',
                'part_of_speech' => 'noun',
                'meaning' => 'Hotel / Guesthouse',
                'meaning_zh' => '宾馆',
                'example_sentence' => '我住宾馆。',
                'example_translation' => 'I stay at a hotel.',
                'definition' => 'Hotel, guesthouse',
                'sentences' => ['我住___。', '___房间。', '___服务。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '医院',
                'pinyin' => 'yī yuàn',
                'simplified' => '医院',
                'traditional' => '醫院',
                'part_of_speech' => 'noun',
                'meaning' => 'Hospital',
                'meaning_zh' => '医院',
                'example_sentence' => '我去医院看病。',
                'example_translation' => 'I go to the hospital to see a doctor.',
                'definition' => 'Hospital',
                'sentences' => ['我去___看病。', '___很大。', '___里。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '银行',
                'pinyin' => 'yín háng',
                'simplified' => '银行',
                'traditional' => '銀行',
                'part_of_speech' => 'noun',
                'meaning' => 'Bank',
                'meaning_zh' => '银行',
                'example_sentence' => '我去银行取钱。',
                'example_translation' => 'I go to the bank to withdraw money.',
                'definition' => 'Bank',
                'sentences' => ['我去___取钱。', '___卡。', '___里。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '邮局',
                'pinyin' => 'yóu jú',
                'simplified' => '邮局',
                'traditional' => '郵局',
                'part_of_speech' => 'noun',
                'meaning' => 'Post office',
                'meaning_zh' => '邮局',
                'example_sentence' => '我去邮局寄信。',
                'example_translation' => 'I go to the post office to mail a letter.',
                'definition' => 'Post office',
                'sentences' => ['我去___寄信。', '___工作。', '___里。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '公司',
                'pinyin' => 'gōng sī',
                'simplified' => '公司',
                'traditional' => '公司',
                'part_of_speech' => 'noun',
                'meaning' => 'Company',
                'meaning_zh' => '公司',
                'example_sentence' => '我在公司工作。',
                'example_translation' => 'I work at a company.',
                'definition' => 'Company',
                'sentences' => ['我在___工作。', '___很大。', '___员工。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '火车站',
                'pinyin' => 'huǒ chē zhàn',
                'simplified' => '火车站',
                'traditional' => '火車站',
                'part_of_speech' => 'noun',
                'meaning' => 'Train station',
                'meaning_zh' => '火车站',
                'example_sentence' => '我在火车站等你。',
                'example_translation' => 'I wait for you at the train station.',
                'definition' => 'Train station, railway station',
                'sentences' => ['我在___等你。', '___很大。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '机场',
                'pinyin' => 'jī chǎng',
                'simplified' => '机场',
                'traditional' => '機場',
                'part_of_speech' => 'noun',
                'meaning' => 'Airport',
                'meaning_zh' => '机场',
                'example_sentence' => '我去机场。',
                'example_translation' => 'I go to the airport.',
                'definition' => 'Airport',
                'sentences' => ['我去___。', '___很大。', '___接人。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '公园',
                'pinyin' => 'gōng yuán',
                'simplified' => '公园',
                'traditional' => '公園',
                'part_of_speech' => 'noun',
                'meaning' => 'Park',
                'meaning_zh' => '公园',
                'example_sentence' => '我去公园散步。',
                'example_translation' => 'I go to the park for a walk.',
                'definition' => 'Park',
                'sentences' => ['我去___散步。', '___很美。', '___里。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '电影院',
                'pinyin' => 'diàn yǐng yuàn',
                'simplified' => '电影院',
                'traditional' => '電影院',
                'part_of_speech' => 'noun',
                'meaning' => 'Cinema / Movie theater',
                'meaning_zh' => '电影院',
                'example_sentence' => '我去电影院看电影。',
                'example_translation' => 'I go to the cinema to watch a movie.',
                'definition' => 'Cinema, movie theater',
                'sentences' => ['我去___看电影。', '___里。', '___票。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '书店',
                'pinyin' => 'shū diàn',
                'simplified' => '书店',
                'traditional' => '書店',
                'part_of_speech' => 'noun',
                'meaning' => 'Bookstore',
                'meaning_zh' => '书店',
                'example_sentence' => '我去书店买书。',
                'example_translation' => 'I go to the bookstore to buy books.',
                'definition' => 'Bookstore',
                'sentences' => ['我去___买书。', '___里。', '___很大。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '市场',
                'pinyin' => 'shì chǎng',
                'simplified' => '市场',
                'traditional' => '市場',
                'part_of_speech' => 'noun',
                'meaning' => 'Market',
                'meaning_zh' => '市场',
                'example_sentence' => '我去市场买菜。',
                'example_translation' => 'I go to the market to buy vegetables.',
                'definition' => 'Market',
                'sentences' => ['我去___买菜。', '___很热闹。', '___里。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '广场',
                'pinyin' => 'guǎng chǎng',
                'simplified' => '广场',
                'traditional' => '廣場',
                'part_of_speech' => 'noun',
                'meaning' => 'Square / Plaza',
                'meaning_zh' => '广场',
                'example_sentence' => '我在广场散步。',
                'example_translation' => 'I take a walk in the square.',
                'definition' => 'Square, plaza',
                'sentences' => ['我在___散步。', '___很大。', '___上。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '桥',
                'pinyin' => 'qiáo',
                'simplified' => '桥',
                'traditional' => '橋',
                'part_of_speech' => 'noun',
                'meaning' => 'Bridge',
                'meaning_zh' => '桥',
                'example_sentence' => '过桥。',
                'example_translation' => 'Cross the bridge.',
                'definition' => 'Bridge',
                'sentences' => ['过___。', '___很长。', '___上。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '红绿灯',
                'pinyin' => 'hóng lǜ dēng',
                'simplified' => '红绿灯',
                'traditional' => '紅綠燈',
                'part_of_speech' => 'noun',
                'meaning' => 'Traffic light',
                'meaning_zh' => '红绿灯',
                'example_sentence' => '在红绿灯那儿转弯。',
                'example_translation' => 'Turn at the traffic light.',
                'definition' => 'Traffic light',
                'sentences' => ['在___那儿转弯。', '___很多。', '等___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '路口',
                'pinyin' => 'lù kǒu',
                'simplified' => '路口',
                'traditional' => '路口',
                'part_of_speech' => 'noun',
                'meaning' => 'Intersection / Crossroad',
                'meaning_zh' => '路口',
                'example_sentence' => '在路口转弯。',
                'example_translation' => 'Turn at the intersection.',
                'definition' => 'Intersection, crossroad',
                'sentences' => ['在___转弯。', '___等你。', '___很多车。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '附近',
                'pinyin' => 'fù jìn',
                'simplified' => '附近',
                'traditional' => '附近',
                'part_of_speech' => 'noun',
                'meaning' => 'Nearby / Vicinity',
                'meaning_zh' => '附近',
                'example_sentence' => '我家附近有超市。',
                'example_translation' => 'There is a supermarket near my home.',
                'definition' => 'Nearby, vicinity, neighborhood',
                'sentences' => ['我家___有超市。', '___的人。', '___地区。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '地方',
                'pinyin' => 'dì fang',
                'simplified' => '地方',
                'traditional' => '地方',
                'part_of_speech' => 'noun',
                'meaning' => 'Place / Location',
                'meaning_zh' => '地方',
                'example_sentence' => '这是什么地方？',
                'example_translation' => 'What place is this?',
                'definition' => 'Place, location',
                'sentences' => ['这是什么___？', '___很美。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '地址',
                'pinyin' => 'dì zhǐ',
                'simplified' => '地址',
                'traditional' => '地址',
                'part_of_speech' => 'noun',
                'meaning' => 'Address',
                'meaning_zh' => '地址',
                'example_sentence' => '你的地址是什么？',
                'example_translation' => 'What is your address?',
                'definition' => 'Address',
                'sentences' => ['你的___是什么？', '写___。', '___不对。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 24,
                'word' => '地图',
                'pinyin' => 'dì tú',
                'simplified' => '地图',
                'traditional' => '地圖',
                'part_of_speech' => 'noun',
                'meaning' => 'Map',
                'meaning_zh' => '地图',
                'example_sentence' => '我看地图。',
                'example_translation' => 'I look at the map.',
                'definition' => 'Map',
                'sentences' => ['我看___。', '___上。', '___很详细。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 25: Free Time Activities (业余活动) - 25 words
        $freeTimeActivitiesVocab = [
            [
                'topic_id' => 25,
                'word' => '玩',
                'pinyin' => 'wán',
                'simplified' => '玩',
                'traditional' => '玩',
                'part_of_speech' => 'verb',
                'meaning' => 'To play / To have fun',
                'meaning_zh' => '玩',
                'example_sentence' => '我喜欢玩。',
                'example_translation' => 'I like to play.',
                'definition' => 'To play, to have fun',
                'sentences' => ['我喜欢___。', '___游戏。', '___儿。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '游戏',
                'pinyin' => 'yóu xì',
                'simplified' => '游戏',
                'traditional' => '遊戲',
                'part_of_speech' => 'noun',
                'meaning' => 'Game',
                'meaning_zh' => '游戏',
                'example_sentence' => '我玩游戏。',
                'example_translation' => 'I play games.',
                'definition' => 'Game',
                'sentences' => ['我玩___。', '___很有趣。', '电子___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '游泳',
                'pinyin' => 'yóu yǒng',
                'simplified' => '游泳',
                'traditional' => '游泳',
                'part_of_speech' => 'verb',
                'meaning' => 'To swim',
                'meaning_zh' => '游泳',
                'example_sentence' => '我喜欢游泳。',
                'example_translation' => 'I like to swim.',
                'definition' => 'To swim',
                'sentences' => ['我喜欢___。', '___池。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '跳舞',
                'pinyin' => 'tiào wǔ',
                'simplified' => '跳舞',
                'traditional' => '跳舞',
                'part_of_speech' => 'verb',
                'meaning' => 'To dance',
                'meaning_zh' => '跳舞',
                'example_sentence' => '我喜欢跳舞。',
                'example_translation' => 'I like to dance.',
                'definition' => 'To dance',
                'sentences' => ['我喜欢___。', '___很开心。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '唱歌',
                'pinyin' => 'chàng gē',
                'simplified' => '唱歌',
                'traditional' => '唱歌',
                'part_of_speech' => 'verb',
                'meaning' => 'To sing',
                'meaning_zh' => '唱歌',
                'example_sentence' => '我喜欢唱歌。',
                'example_translation' => 'I like to sing.',
                'definition' => 'To sing',
                'sentences' => ['我喜欢___。', '___很好听。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '画画',
                'pinyin' => 'huà huà',
                'simplified' => '画画',
                'traditional' => '畫畫',
                'part_of_speech' => 'verb',
                'meaning' => 'To draw / To paint',
                'meaning_zh' => '画画',
                'example_sentence' => '我喜欢画画。',
                'example_translation' => 'I like to draw.',
                'definition' => 'To draw, to paint',
                'sentences' => ['我喜欢___。', '___很有趣。', '学___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '拍照',
                'pinyin' => 'pāi zhào',
                'simplified' => '拍照',
                'traditional' => '拍照',
                'part_of_speech' => 'verb',
                'meaning' => 'To take a photo',
                'meaning_zh' => '拍照',
                'example_sentence' => '我喜欢拍照。',
                'example_translation' => 'I like to take photos.',
                'definition' => 'To take a photo, to photograph',
                'sentences' => ['我喜欢___。', '___留念。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '旅游',
                'pinyin' => 'lǚ yóu',
                'simplified' => '旅游',
                'traditional' => '旅遊',
                'part_of_speech' => 'verb',
                'meaning' => 'To travel / To tour',
                'meaning_zh' => '旅游',
                'example_sentence' => '我喜欢旅游。',
                'example_translation' => 'I like to travel.',
                'definition' => 'To travel, to tour',
                'sentences' => ['我喜欢___。', '___很开心。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '散步',
                'pinyin' => 'sàn bù',
                'simplified' => '散步',
                'traditional' => '散步',
                'part_of_speech' => 'verb',
                'meaning' => 'To take a walk / To stroll',
                'meaning_zh' => '散步',
                'example_sentence' => '我喜欢散步。',
                'example_translation' => 'I like to take walks.',
                'definition' => 'To take a walk, to stroll',
                'sentences' => ['我喜欢___。', '___很舒服。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '爬山',
                'pinyin' => 'pá shān',
                'simplified' => '爬山',
                'traditional' => '爬山',
                'part_of_speech' => 'verb',
                'meaning' => 'To climb a mountain / To hike',
                'meaning_zh' => '爬山',
                'example_sentence' => '我喜欢爬山。',
                'example_translation' => 'I like to climb mountains.',
                'definition' => 'To climb a mountain, to hike',
                'sentences' => ['我喜欢___。', '___很累。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '运动',
                'pinyin' => 'yùn dòng',
                'simplified' => '运动',
                'traditional' => '運動',
                'part_of_speech' => 'noun',
                'meaning' => 'Exercise / Sports',
                'meaning_zh' => '运动',
                'example_sentence' => '我喜欢运动。',
                'example_translation' => 'I like exercise.',
                'definition' => 'Exercise, sports, movement',
                'sentences' => ['我喜欢___。', '___很健康。', '___鞋。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '踢足球',
                'pinyin' => 'tī zú qiú',
                'simplified' => '踢足球',
                'traditional' => '踢足球',
                'part_of_speech' => 'verb',
                'meaning' => 'To play football/soccer',
                'meaning_zh' => '踢足球',
                'example_sentence' => '我喜欢踢足球。',
                'example_translation' => 'I like to play football.',
                'definition' => 'To play football, to play soccer',
                'sentences' => ['我喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '打篮球',
                'pinyin' => 'dǎ lán qiú',
                'simplified' => '打篮球',
                'traditional' => '打籃球',
                'part_of_speech' => 'verb',
                'meaning' => 'To play basketball',
                'meaning_zh' => '打篮球',
                'example_sentence' => '我喜欢打篮球。',
                'example_translation' => 'I like to play basketball.',
                'definition' => 'To play basketball',
                'sentences' => ['我喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '打乒乓球',
                'pinyin' => 'dǎ pīng pāng qiú',
                'simplified' => '打乒乓球',
                'traditional' => '打乒乓球',
                'part_of_speech' => 'verb',
                'meaning' => 'To play table tennis / Ping pong',
                'meaning_zh' => '打乒乓球',
                'example_sentence' => '我喜欢打乒乓球。',
                'example_translation' => 'I like to play table tennis.',
                'definition' => 'To play table tennis, ping pong',
                'sentences' => ['我喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '打网球',
                'pinyin' => 'dǎ wǎng qiú',
                'simplified' => '打网球',
                'traditional' => '打網球',
                'part_of_speech' => 'verb',
                'meaning' => 'To play tennis',
                'meaning_zh' => '打网球',
                'example_sentence' => '我喜欢打网球。',
                'example_translation' => 'I like to play tennis.',
                'definition' => 'To play tennis',
                'sentences' => ['我喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '打羽毛球',
                'pinyin' => 'dǎ yǔ máo qiú',
                'simplified' => '打羽毛球',
                'traditional' => '打羽毛球',
                'part_of_speech' => 'verb',
                'meaning' => 'To play badminton',
                'meaning_zh' => '打羽毛球',
                'example_sentence' => '我喜欢打羽毛球。',
                'example_translation' => 'I like to play badminton.',
                'definition' => 'To play badminton',
                'sentences' => ['我喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '看电影',
                'pinyin' => 'kàn diàn yǐng',
                'simplified' => '看电影',
                'traditional' => '看電影',
                'part_of_speech' => 'verb',
                'meaning' => 'To watch a movie',
                'meaning_zh' => '看电影',
                'example_sentence' => '我喜欢看电影。',
                'example_translation' => 'I like to watch movies.',
                'definition' => 'To watch a movie',
                'sentences' => ['我喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '电影',
                'pinyin' => 'diàn yǐng',
                'simplified' => '电影',
                'traditional' => '電影',
                'part_of_speech' => 'noun',
                'meaning' => 'Movie / Film',
                'meaning_zh' => '电影',
                'example_sentence' => '这部电影很好看。',
                'example_translation' => 'This movie is very good.',
                'definition' => 'Movie, film',
                'sentences' => ['这部___很好看。', '看___。', '___票。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '电视',
                'pinyin' => 'diàn shì',
                'simplified' => '电视',
                'traditional' => '電視',
                'part_of_speech' => 'noun',
                'meaning' => 'Television / TV',
                'meaning_zh' => '电视',
                'example_sentence' => '我看电视。',
                'example_translation' => 'I watch TV.',
                'definition' => 'Television, TV',
                'sentences' => ['我看___。', '___节目。', '___剧。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '上网',
                'pinyin' => 'shàng wǎng',
                'simplified' => '上网',
                'traditional' => '上網',
                'part_of_speech' => 'verb',
                'meaning' => 'To go online / To surf the internet',
                'meaning_zh' => '上网',
                'example_sentence' => '我喜欢上网。',
                'example_translation' => 'I like to go online.',
                'definition' => 'To go online, to surf the internet',
                'sentences' => ['我喜欢___。', '___聊天。', '___查资料。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '聊天',
                'pinyin' => 'liáo tiān',
                'simplified' => '聊天',
                'traditional' => '聊天',
                'part_of_speech' => 'verb',
                'meaning' => 'To chat',
                'meaning_zh' => '聊天',
                'example_sentence' => '我喜欢聊天。',
                'example_translation' => 'I like to chat.',
                'definition' => 'To chat, to talk',
                'sentences' => ['我喜欢___。', '___很开心。', '一起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '购物',
                'pinyin' => 'gòu wù',
                'simplified' => '购物',
                'traditional' => '購物',
                'part_of_speech' => 'verb',
                'meaning' => 'To shop / To go shopping',
                'meaning_zh' => '购物',
                'example_sentence' => '我喜欢购物。',
                'example_translation' => 'I like to shop.',
                'definition' => 'To shop, to go shopping',
                'sentences' => ['我喜欢___。', '___中心。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '休息',
                'pinyin' => 'xiū xi',
                'simplified' => '休息',
                'traditional' => '休息',
                'part_of_speech' => 'verb',
                'meaning' => 'To rest',
                'meaning_zh' => '休息',
                'example_sentence' => '我想休息。',
                'example_translation' => 'I want to rest.',
                'definition' => 'To rest, to take a break',
                'sentences' => ['我想___。', '___一下。', '___日。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '睡觉',
                'pinyin' => 'shuì jiào',
                'simplified' => '睡觉',
                'traditional' => '睡覺',
                'part_of_speech' => 'verb',
                'meaning' => 'To sleep',
                'meaning_zh' => '睡觉',
                'example_sentence' => '我想睡觉。',
                'example_translation' => 'I want to sleep.',
                'definition' => 'To sleep',
                'sentences' => ['我想___。', '___时间。', '去___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 25,
                'word' => '爱好',
                'pinyin' => 'ài hào',
                'simplified' => '爱好',
                'traditional' => '愛好',
                'part_of_speech' => 'noun',
                'meaning' => 'Hobby / Interest',
                'meaning_zh' => '爱好',
                'example_sentence' => '你的爱好是什么？',
                'example_translation' => 'What is your hobby?',
                'definition' => 'Hobby, interest',
                'sentences' => ['你的___是什么？', '我的___。', '___很多。'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($schoolVocab, $cityVocab, $freeTimeActivitiesVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
