<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk1Topics3to5Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 3: Numbers 0 to 100 (29 words)
        $numbersVocab = [
            [
                'topic_id' => 3,
                'word' => '零',
                'pinyin' => 'líng',
                'simplified' => '零',
                'traditional' => '零',
                'part_of_speech' => 'number',
                'meaning' => 'Zero',
                'meaning_zh' => '零',
                'example_sentence' => '这是零度。',
                'example_translation' => 'This is zero degrees.',
                'definition' => 'The number 0',
                'sentences' => ['温度是___度。', '___加一等于一。', '这个数字是___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '一',
                'pinyin' => 'yī',
                'simplified' => '一',
                'traditional' => '一',
                'part_of_speech' => 'number',
                'meaning' => 'One',
                'meaning_zh' => '一',
                'example_sentence' => '我有一本书。',
                'example_translation' => 'I have one book.',
                'definition' => 'The number 1',
                'sentences' => ['我有___本书。', '___加___等于二。', '___个人。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '二',
                'pinyin' => 'èr',
                'simplified' => '二',
                'traditional' => '二',
                'part_of_speech' => 'number',
                'meaning' => 'Two',
                'meaning_zh' => '二',
                'example_sentence' => '一加一等于二。',
                'example_translation' => 'One plus one equals two.',
                'definition' => 'The number 2',
                'sentences' => ['一加一等于___。', '第___个。', '___月是二月。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '三',
                'pinyin' => 'sān',
                'simplified' => '三',
                'traditional' => '三',
                'part_of_speech' => 'number',
                'meaning' => 'Three',
                'meaning_zh' => '三',
                'example_sentence' => '我有三个苹果。',
                'example_translation' => 'I have three apples.',
                'definition' => 'The number 3',
                'sentences' => ['我有___个苹果。', '___点钟。', '第___名。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '四',
                'pinyin' => 'sì',
                'simplified' => '四',
                'traditional' => '四',
                'part_of_speech' => 'number',
                'meaning' => 'Four',
                'meaning_zh' => '四',
                'example_sentence' => '一年有四个季节。',
                'example_translation' => 'There are four seasons in a year.',
                'definition' => 'The number 4',
                'sentences' => ['一年有___个季节。', '___点半。', '___月是四月。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '五',
                'pinyin' => 'wǔ',
                'simplified' => '五',
                'traditional' => '五',
                'part_of_speech' => 'number',
                'meaning' => 'Five',
                'meaning_zh' => '五',
                'example_sentence' => '我五岁了。',
                'example_translation' => 'I am five years old.',
                'definition' => 'The number 5',
                'sentences' => ['我___岁了。', '___个人。', '星期___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '六',
                'pinyin' => 'liù',
                'simplified' => '六',
                'traditional' => '六',
                'part_of_speech' => 'number',
                'meaning' => 'Six',
                'meaning_zh' => '六',
                'example_sentence' => '今天是六月六号。',
                'example_translation' => 'Today is June 6th.',
                'definition' => 'The number 6',
                'sentences' => ['今天是___月___号。', '___点钟。', '星期___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '七',
                'pinyin' => 'qī',
                'simplified' => '七',
                'traditional' => '七',
                'part_of_speech' => 'number',
                'meaning' => 'Seven',
                'meaning_zh' => '七',
                'example_sentence' => '七点起床。',
                'example_translation' => 'Get up at seven o\'clock.',
                'definition' => 'The number 7',
                'sentences' => ['___点起床。', '___月是七月。', '___天。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '八',
                'pinyin' => 'bā',
                'simplified' => '八',
                'traditional' => '八',
                'part_of_speech' => 'number',
                'meaning' => 'Eight',
                'meaning_zh' => '八',
                'example_sentence' => '八点上课。',
                'example_translation' => 'Class starts at eight.',
                'definition' => 'The number 8',
                'sentences' => ['___点上课。', '___月是八月。', '___个学生。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '九',
                'pinyin' => 'jiǔ',
                'simplified' => '九',
                'traditional' => '九',
                'part_of_speech' => 'number',
                'meaning' => 'Nine',
                'meaning_zh' => '九',
                'example_sentence' => '九点睡觉。',
                'example_translation' => 'Go to bed at nine.',
                'definition' => 'The number 9',
                'sentences' => ['___点睡觉。', '___个月。', '___十九。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '十',
                'pinyin' => 'shí',
                'simplified' => '十',
                'traditional' => '十',
                'part_of_speech' => 'number',
                'meaning' => 'Ten',
                'meaning_zh' => '十',
                'example_sentence' => '我有十块钱。',
                'example_translation' => 'I have ten yuan.',
                'definition' => 'The number 10',
                'sentences' => ['我有___块钱。', '___点钟。', '___月是十月。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '十一',
                'pinyin' => 'shí yī',
                'simplified' => '十一',
                'traditional' => '十一',
                'part_of_speech' => 'number',
                'meaning' => 'Eleven',
                'meaning_zh' => '十一',
                'example_sentence' => '十一点吃午饭。',
                'example_translation' => 'Have lunch at eleven.',
                'definition' => 'The number 11',
                'sentences' => ['___点吃午饭。', '___月是十一月。', '___号。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '十二',
                'pinyin' => 'shí èr',
                'simplified' => '十二',
                'traditional' => '十二',
                'part_of_speech' => 'number',
                'meaning' => 'Twelve',
                'meaning_zh' => '十二',
                'example_sentence' => '一年有十二个月。',
                'example_translation' => 'There are twelve months in a year.',
                'definition' => 'The number 12',
                'sentences' => ['一年有___个月。', '___点。', '___月是十二月。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '二十',
                'pinyin' => 'èr shí',
                'simplified' => '二十',
                'traditional' => '二十',
                'part_of_speech' => 'number',
                'meaning' => 'Twenty',
                'meaning_zh' => '二十',
                'example_sentence' => '我二十岁。',
                'example_translation' => 'I am twenty years old.',
                'definition' => 'The number 20',
                'sentences' => ['我___岁。', '___块钱。', '___个学生。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '三十',
                'pinyin' => 'sān shí',
                'simplified' => '三十',
                'traditional' => '三十',
                'part_of_speech' => 'number',
                'meaning' => 'Thirty',
                'meaning_zh' => '三十',
                'example_sentence' => '三十分钟。',
                'example_translation' => 'Thirty minutes.',
                'definition' => 'The number 30',
                'sentences' => ['___分钟。', '___号。', '___个人。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '四十',
                'pinyin' => 'sì shí',
                'simplified' => '四十',
                'traditional' => '四十',
                'part_of_speech' => 'number',
                'meaning' => 'Forty',
                'meaning_zh' => '四十',
                'example_sentence' => '四十个学生。',
                'example_translation' => 'Forty students.',
                'definition' => 'The number 40',
                'sentences' => ['___个学生。', '___块钱。', '___分钟。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '五十',
                'pinyin' => 'wǔ shí',
                'simplified' => '五十',
                'traditional' => '五十',
                'part_of_speech' => 'number',
                'meaning' => 'Fifty',
                'meaning_zh' => '五十',
                'example_sentence' => '五十块钱。',
                'example_translation' => 'Fifty yuan.',
                'definition' => 'The number 50',
                'sentences' => ['___块钱。', '___岁。', '___个。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '六十',
                'pinyin' => 'liù shí',
                'simplified' => '六十',
                'traditional' => '六十',
                'part_of_speech' => 'number',
                'meaning' => 'Sixty',
                'meaning_zh' => '六十',
                'example_sentence' => '一小时有六十分钟。',
                'example_translation' => 'There are sixty minutes in an hour.',
                'definition' => 'The number 60',
                'sentences' => ['一小时有___分钟。', '___岁。', '___个。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '七十',
                'pinyin' => 'qī shí',
                'simplified' => '七十',
                'traditional' => '七十',
                'part_of_speech' => 'number',
                'meaning' => 'Seventy',
                'meaning_zh' => '七十',
                'example_sentence' => '七十块钱。',
                'example_translation' => 'Seventy yuan.',
                'definition' => 'The number 70',
                'sentences' => ['___块钱。', '___岁。', '___分。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '八十',
                'pinyin' => 'bā shí',
                'simplified' => '八十',
                'traditional' => '八十',
                'part_of_speech' => 'number',
                'meaning' => 'Eighty',
                'meaning_zh' => '八十',
                'example_sentence' => '八十个人。',
                'example_translation' => 'Eighty people.',
                'definition' => 'The number 80',
                'sentences' => ['___个人。', '___块钱。', '___分。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '九十',
                'pinyin' => 'jiǔ shí',
                'simplified' => '九十',
                'traditional' => '九十',
                'part_of_speech' => 'number',
                'meaning' => 'Ninety',
                'meaning_zh' => '九十',
                'example_sentence' => '九十分。',
                'example_translation' => 'Ninety points.',
                'definition' => 'The number 90',
                'sentences' => ['___分。', '___块钱。', '___个。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '一百',
                'pinyin' => 'yī bǎi',
                'simplified' => '一百',
                'traditional' => '一百',
                'part_of_speech' => 'number',
                'meaning' => 'One hundred',
                'meaning_zh' => '一百',
                'example_sentence' => '一百块钱。',
                'example_translation' => 'One hundred yuan.',
                'definition' => 'The number 100',
                'sentences' => ['___块钱。', '___个学生。', '___分。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '百',
                'pinyin' => 'bǎi',
                'simplified' => '百',
                'traditional' => '百',
                'part_of_speech' => 'number',
                'meaning' => 'Hundred',
                'meaning_zh' => '百',
                'example_sentence' => '五百块。',
                'example_translation' => 'Five hundred yuan.',
                'definition' => 'The number 100 (counter)',
                'sentences' => ['五___块。', '三___个。', '两___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '千',
                'pinyin' => 'qiān',
                'simplified' => '千',
                'traditional' => '千',
                'part_of_speech' => 'number',
                'meaning' => 'Thousand',
                'meaning_zh' => '千',
                'example_sentence' => '一千块钱。',
                'example_translation' => 'One thousand yuan.',
                'definition' => 'The number 1000',
                'sentences' => ['一___块钱。', '五___个。', '三___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '万',
                'pinyin' => 'wàn',
                'simplified' => '万',
                'traditional' => '萬',
                'part_of_speech' => 'number',
                'meaning' => 'Ten thousand',
                'meaning_zh' => '万',
                'example_sentence' => '一万块钱。',
                'example_translation' => 'Ten thousand yuan.',
                'definition' => 'The number 10,000',
                'sentences' => ['一___块钱。', '十___个。', '五___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '多少',
                'pinyin' => 'duō shao',
                'simplified' => '多少',
                'traditional' => '多少',
                'part_of_speech' => 'question word',
                'meaning' => 'How many / How much',
                'meaning_zh' => '多少',
                'example_sentence' => '这个多少钱？',
                'example_translation' => 'How much is this?',
                'definition' => 'Question word for quantity',
                'sentences' => ['这个___钱？', '你有___本书？', '___个学生？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '几',
                'pinyin' => 'jǐ',
                'simplified' => '几',
                'traditional' => '幾',
                'part_of_speech' => 'question word',
                'meaning' => 'How many (small numbers)',
                'meaning_zh' => '几',
                'example_sentence' => '现在几点？',
                'example_translation' => 'What time is it now?',
                'definition' => 'Question word for numbers under 10',
                'sentences' => ['现在___点？', '你有___个？', '___月？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '个',
                'pinyin' => 'gè',
                'simplified' => '个',
                'traditional' => '個',
                'part_of_speech' => 'measure word',
                'meaning' => 'General measure word',
                'meaning_zh' => '个',
                'example_sentence' => '三个人。',
                'example_translation' => 'Three people.',
                'definition' => 'General counter for people and things',
                'sentences' => ['三___人。', '一___苹果。', '五___学生。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '块',
                'pinyin' => 'kuài',
                'simplified' => '块',
                'traditional' => '塊',
                'part_of_speech' => 'measure word',
                'meaning' => 'Yuan (money)',
                'meaning_zh' => '块',
                'example_sentence' => '十块钱。',
                'example_translation' => 'Ten yuan.',
                'definition' => 'Measure word for money (yuan)',
                'sentences' => ['十___钱。', '五___。', '多少___？'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 4: Family (21 words)
        $familyVocab = [
            [
                'topic_id' => 4,
                'word' => '家',
                'pinyin' => 'jiā',
                'simplified' => '家',
                'traditional' => '家',
                'part_of_speech' => 'noun',
                'meaning' => 'Home / Family',
                'meaning_zh' => '家',
                'example_sentence' => '我回家了。',
                'example_translation' => 'I went home.',
                'definition' => 'Home or family',
                'sentences' => ['我回___了。', '我___有五口人。', '在___吃饭。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '爸爸',
                'pinyin' => 'bà ba',
                'simplified' => '爸爸',
                'traditional' => '爸爸',
                'part_of_speech' => 'noun',
                'meaning' => 'Father / Dad',
                'meaning_zh' => '爸爸',
                'example_sentence' => '我爸爸是老师。',
                'example_translation' => 'My father is a teacher.',
                'definition' => 'Father, dad',
                'sentences' => ['我___是老师。', '___在工作。', '___很忙。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '妈妈',
                'pinyin' => 'mā ma',
                'simplified' => '妈妈',
                'traditional' => '媽媽',
                'part_of_speech' => 'noun',
                'meaning' => 'Mother / Mom',
                'meaning_zh' => '妈妈',
                'example_sentence' => '我妈妈很漂亮。',
                'example_translation' => 'My mother is very beautiful.',
                'definition' => 'Mother, mom',
                'sentences' => ['我___很漂亮。', '___做饭。', '___在家。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '儿子',
                'pinyin' => 'ér zi',
                'simplified' => '儿子',
                'traditional' => '兒子',
                'part_of_speech' => 'noun',
                'meaning' => 'Son',
                'meaning_zh' => '儿子',
                'example_sentence' => '他是我儿子。',
                'example_translation' => 'He is my son.',
                'definition' => 'Male child, son',
                'sentences' => ['他是我___。', '我有一个___。', '___上学。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '女儿',
                'pinyin' => 'nǚ ér',
                'simplified' => '女儿',
                'traditional' => '女兒',
                'part_of_speech' => 'noun',
                'meaning' => 'Daughter',
                'meaning_zh' => '女儿',
                'example_sentence' => '她是我女儿。',
                'example_translation' => 'She is my daughter.',
                'definition' => 'Female child, daughter',
                'sentences' => ['她是我___。', '我的___很可爱。', '___在学校。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '哥哥',
                'pinyin' => 'gē ge',
                'simplified' => '哥哥',
                'traditional' => '哥哥',
                'part_of_speech' => 'noun',
                'meaning' => 'Older brother',
                'meaning_zh' => '哥哥',
                'example_sentence' => '我哥哥很高。',
                'example_translation' => 'My older brother is very tall.',
                'definition' => 'Elder brother',
                'sentences' => ['我___很高。', '___在上海工作。', '___今年二十岁。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '弟弟',
                'pinyin' => 'dì di',
                'simplified' => '弟弟',
                'traditional' => '弟弟',
                'part_of_speech' => 'noun',
                'meaning' => 'Younger brother',
                'meaning_zh' => '弟弟',
                'example_sentence' => '我弟弟上小学。',
                'example_translation' => 'My younger brother goes to elementary school.',
                'definition' => 'Younger brother',
                'sentences' => ['我___上小学。', '___很调皮。', '___十岁了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '姐姐',
                'pinyin' => 'jiě jie',
                'simplified' => '姐姐',
                'traditional' => '姐姐',
                'part_of_speech' => 'noun',
                'meaning' => 'Older sister',
                'meaning_zh' => '姐姐',
                'example_sentence' => '我姐姐是医生。',
                'example_translation' => 'My older sister is a doctor.',
                'definition' => 'Elder sister',
                'sentences' => ['我___是医生。', '___在医院工作。', '___很温柔。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '妹妹',
                'pinyin' => 'mèi mei',
                'simplified' => '妹妹',
                'traditional' => '妹妹',
                'part_of_speech' => 'noun',
                'meaning' => 'Younger sister',
                'meaning_zh' => '妹妹',
                'example_sentence' => '我妹妹上中学。',
                'example_translation' => 'My younger sister goes to middle school.',
                'definition' => 'Younger sister',
                'sentences' => ['我___上中学。', '___很可爱。', '___喜欢画画。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '爷爷',
                'pinyin' => 'yé ye',
                'simplified' => '爷爷',
                'traditional' => '爺爺',
                'part_of_speech' => 'noun',
                'meaning' => 'Grandfather (paternal)',
                'meaning_zh' => '爷爷',
                'example_sentence' => '我爷爷七十岁了。',
                'example_translation' => 'My grandfather is seventy years old.',
                'definition' => 'Paternal grandfather',
                'sentences' => ['我___七十岁了。', '___很健康。', '___喜欢散步。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '奶奶',
                'pinyin' => 'nǎi nai',
                'simplified' => '奶奶',
                'traditional' => '奶奶',
                'part_of_speech' => 'noun',
                'meaning' => 'Grandmother (paternal)',
                'meaning_zh' => '奶奶',
                'example_sentence' => '我奶奶做饭很好吃。',
                'example_translation' => "My grandmother's cooking is delicious.",
                'definition' => 'Paternal grandmother',
                'sentences' => ['我___做饭很好吃。', '___在家。', '___很慈祥。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '外公',
                'pinyin' => 'wài gōng',
                'simplified' => '外公',
                'traditional' => '外公',
                'part_of_speech' => 'noun',
                'meaning' => 'Grandfather (maternal)',
                'meaning_zh' => '外公',
                'example_sentence' => '我外公住在北京。',
                'example_translation' => 'My maternal grandfather lives in Beijing.',
                'definition' => 'Maternal grandfather',
                'sentences' => ['我___住在北京。', '___很喜欢我。', '___每天看报纸。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '外婆',
                'pinyin' => 'wài pó',
                'simplified' => '外婆',
                'traditional' => '外婆',
                'part_of_speech' => 'noun',
                'meaning' => 'Grandmother (maternal)',
                'meaning_zh' => '外婆',
                'example_sentence' => '我外婆很疼我。',
                'example_translation' => 'My maternal grandmother loves me very much.',
                'definition' => 'Maternal grandmother',
                'sentences' => ['我___很疼我。', '___做的菜很好吃。', '___住在上海。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '孩子',
                'pinyin' => 'hái zi',
                'simplified' => '孩子',
                'traditional' => '孩子',
                'part_of_speech' => 'noun',
                'meaning' => 'Child / Children',
                'meaning_zh' => '孩子',
                'example_sentence' => '我有两个孩子。',
                'example_translation' => 'I have two children.',
                'definition' => 'Child, children',
                'sentences' => ['我有两个___。', '___在玩。', '___们很可爱。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '男孩',
                'pinyin' => 'nán hái',
                'simplified' => '男孩',
                'traditional' => '男孩',
                'part_of_speech' => 'noun',
                'meaning' => 'Boy',
                'meaning_zh' => '男孩',
                'example_sentence' => '那个男孩是我弟弟。',
                'example_translation' => 'That boy is my younger brother.',
                'definition' => 'Male child, boy',
                'sentences' => ['那个___是我弟弟。', '___在踢球。', '___很调皮。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '女孩',
                'pinyin' => 'nǚ hái',
                'simplified' => '女孩',
                'traditional' => '女孩',
                'part_of_speech' => 'noun',
                'meaning' => 'Girl',
                'meaning_zh' => '女孩',
                'example_sentence' => '那个女孩很漂亮。',
                'example_translation' => 'That girl is very pretty.',
                'definition' => 'Female child, girl',
                'sentences' => ['那个___很漂亮。', '___在跳舞。', '___喜欢唱歌。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '先生',
                'pinyin' => 'xiān sheng',
                'simplified' => '先生',
                'traditional' => '先生',
                'part_of_speech' => 'noun',
                'meaning' => 'Mr. / Husband',
                'meaning_zh' => '先生',
                'example_sentence' => '李先生是我的老师。',
                'example_translation' => 'Mr. Li is my teacher.',
                'definition' => 'Mister, sir, husband',
                'sentences' => ['李___是我的老师。', '我___在公司工作。', '王___，您好！'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '太太',
                'pinyin' => 'tài tai',
                'simplified' => '太太',
                'traditional' => '太太',
                'part_of_speech' => 'noun',
                'meaning' => 'Mrs. / Wife',
                'meaning_zh' => '太太',
                'example_sentence' => '这是李太太。',
                'example_translation' => 'This is Mrs. Li.',
                'definition' => 'Missus, madam, wife',
                'sentences' => ['这是李___。', '我___是医生。', '王___，您好！'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '丈夫',
                'pinyin' => 'zhàng fu',
                'simplified' => '丈夫',
                'traditional' => '丈夫',
                'part_of_speech' => 'noun',
                'meaning' => 'Husband',
                'meaning_zh' => '丈夫',
                'example_sentence' => '她的丈夫是医生。',
                'example_translation' => 'Her husband is a doctor.',
                'definition' => 'Husband',
                'sentences' => ['她的___是医生。', '我___很忙。', '___在公司工作。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '妻子',
                'pinyin' => 'qī zi',
                'simplified' => '妻子',
                'traditional' => '妻子',
                'part_of_speech' => 'noun',
                'meaning' => 'Wife',
                'meaning_zh' => '妻子',
                'example_sentence' => '他的妻子很漂亮。',
                'example_translation' => 'His wife is very beautiful.',
                'definition' => 'Wife',
                'sentences' => ['他的___很漂亮。', '我___是老师。', '___在家做饭。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 4,
                'word' => '爱',
                'pinyin' => 'ài',
                'simplified' => '爱',
                'traditional' => '愛',
                'part_of_speech' => 'verb',
                'meaning' => 'To love',
                'meaning_zh' => '爱',
                'example_sentence' => '我爱我的家人。',
                'example_translation' => 'I love my family.',
                'definition' => 'To love, love',
                'sentences' => ['我___我的家人。', '我___你。', '我们都___他。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 5: Colors (14 words)
        $colorsVocab = [
            [
                'topic_id' => 5,
                'word' => '红色',
                'pinyin' => 'hóng sè',
                'simplified' => '红色',
                'traditional' => '紅色',
                'part_of_speech' => 'noun',
                'meaning' => 'Red',
                'meaning_zh' => '红色',
                'example_sentence' => '我喜欢红色。',
                'example_translation' => 'I like red.',
                'definition' => 'The color red',
                'sentences' => ['我喜欢___。', '这是___的。', '___很漂亮。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '黄色',
                'pinyin' => 'huáng sè',
                'simplified' => '黄色',
                'traditional' => '黃色',
                'part_of_speech' => 'noun',
                'meaning' => 'Yellow',
                'meaning_zh' => '黄色',
                'example_sentence' => '香蕉是黄色的。',
                'example_translation' => 'Bananas are yellow.',
                'definition' => 'The color yellow',
                'sentences' => ['香蕉是___的。', '我穿___衣服。', '___很亮。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '蓝色',
                'pinyin' => 'lán sè',
                'simplified' => '蓝色',
                'traditional' => '藍色',
                'part_of_speech' => 'noun',
                'meaning' => 'Blue',
                'meaning_zh' => '蓝色',
                'example_sentence' => '天空是蓝色的。',
                'example_translation' => 'The sky is blue.',
                'definition' => 'The color blue',
                'sentences' => ['天空是___的。', '___很漂亮。', '我喜欢___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '绿色',
                'pinyin' => 'lǜ sè',
                'simplified' => '绿色',
                'traditional' => '綠色',
                'part_of_speech' => 'noun',
                'meaning' => 'Green',
                'meaning_zh' => '绿色',
                'example_sentence' => '草是绿色的。',
                'example_translation' => 'Grass is green.',
                'definition' => 'The color green',
                'sentences' => ['草是___的。', '树叶是___的。', '___很环保。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '白色',
                'pinyin' => 'bái sè',
                'simplified' => '白色',
                'traditional' => '白色',
                'part_of_speech' => 'noun',
                'meaning' => 'White',
                'meaning_zh' => '白色',
                'example_sentence' => '雪是白色的。',
                'example_translation' => 'Snow is white.',
                'definition' => 'The color white',
                'sentences' => ['雪是___的。', '___很干净。', '我穿___衬衫。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '黑色',
                'pinyin' => 'hēi sè',
                'simplified' => '黑色',
                'traditional' => '黑色',
                'part_of_speech' => 'noun',
                'meaning' => 'Black',
                'meaning_zh' => '黑色',
                'example_sentence' => '我的头发是黑色的。',
                'example_translation' => 'My hair is black.',
                'definition' => 'The color black',
                'sentences' => ['我的头发是___的。', '___很酷。', '___的鞋子。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '灰色',
                'pinyin' => 'huī sè',
                'simplified' => '灰色',
                'traditional' => '灰色',
                'part_of_speech' => 'noun',
                'meaning' => 'Gray',
                'meaning_zh' => '灰色',
                'example_sentence' => '天气不好，天是灰色的。',
                'example_translation' => 'The weather is bad, the sky is gray.',
                'definition' => 'The color gray',
                'sentences' => ['天是___的。', '___的云。', '___很低调。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '粉色',
                'pinyin' => 'fěn sè',
                'simplified' => '粉色',
                'traditional' => '粉色',
                'part_of_speech' => 'noun',
                'meaning' => 'Pink',
                'meaning_zh' => '粉色',
                'example_sentence' => '她喜欢粉色。',
                'example_translation' => 'She likes pink.',
                'definition' => 'The color pink',
                'sentences' => ['她喜欢___。', '___的花。', '___很可爱。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '紫色',
                'pinyin' => 'zǐ sè',
                'simplified' => '紫色',
                'traditional' => '紫色',
                'part_of_speech' => 'noun',
                'meaning' => 'Purple',
                'meaning_zh' => '紫色',
                'example_sentence' => '紫色的花很美。',
                'example_translation' => 'Purple flowers are beautiful.',
                'definition' => 'The color purple',
                'sentences' => ['___的花很美。', '我有___的衣服。', '___很神秘。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '橙色',
                'pinyin' => 'chéng sè',
                'simplified' => '橙色',
                'traditional' => '橙色',
                'part_of_speech' => 'noun',
                'meaning' => 'Orange',
                'meaning_zh' => '橙色',
                'example_sentence' => '橙子是橙色的。',
                'example_translation' => 'Oranges are orange.',
                'definition' => 'The color orange',
                'sentences' => ['橙子是___的。', '___很鲜艳。', '___的太阳。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '棕色',
                'pinyin' => 'zōng sè',
                'simplified' => '棕色',
                'traditional' => '棕色',
                'part_of_speech' => 'noun',
                'meaning' => 'Brown',
                'meaning_zh' => '棕色',
                'example_sentence' => '他的眼睛是棕色的。',
                'example_translation' => 'His eyes are brown.',
                'definition' => 'The color brown',
                'sentences' => ['他的眼睛是___的。', '___的桌子。', '___很自然。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '颜色',
                'pinyin' => 'yán sè',
                'simplified' => '颜色',
                'traditional' => '顏色',
                'part_of_speech' => 'noun',
                'meaning' => 'Color',
                'meaning_zh' => '颜色',
                'example_sentence' => '你喜欢什么颜色？',
                'example_translation' => 'What color do you like?',
                'definition' => 'Color, hue',
                'sentences' => ['你喜欢什么___？', '这个___很漂亮。', '___很鲜艳。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '红',
                'pinyin' => 'hóng',
                'simplified' => '红',
                'traditional' => '紅',
                'part_of_speech' => 'adjective',
                'meaning' => 'Red',
                'meaning_zh' => '红',
                'example_sentence' => '红苹果很甜。',
                'example_translation' => 'Red apples are very sweet.',
                'definition' => 'Red (adjective)',
                'sentences' => ['___苹果。', '___色的花。', '天很___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 5,
                'word' => '白',
                'pinyin' => 'bái',
                'simplified' => '白',
                'traditional' => '白',
                'part_of_speech' => 'adjective',
                'meaning' => 'White',
                'meaning_zh' => '白',
                'example_sentence' => '白色的云。',
                'example_translation' => 'White clouds.',
                'definition' => 'White (adjective)',
                'sentences' => ['___色的云。', '___纸。', '___衣服。'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($numbersVocab, $familyVocab, $colorsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
