<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk1Topics6to9Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 6: Months and Seasons (18 words)
        $monthsSeasonsVocab = [
            [
                'topic_id' => 6,
                'word' => '月',
                'pinyin' => 'yuè',
                'simplified' => '月',
                'traditional' => '月',
                'part_of_speech' => 'noun',
                'meaning' => 'Month / Moon',
                'meaning_zh' => '月',
                'example_sentence' => '一年有十二个月。',
                'example_translation' => 'There are twelve months in a year.',
                'definition' => 'Month, moon',
                'sentences' => ['一年有十二个___。', '这个___很忙。', '几___了？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '一月',
                'pinyin' => 'yī yuè',
                'simplified' => '一月',
                'traditional' => '一月',
                'part_of_speech' => 'noun',
                'meaning' => 'January',
                'meaning_zh' => '一月',
                'example_sentence' => '一月很冷。',
                'example_translation' => 'January is very cold.',
                'definition' => 'The first month',
                'sentences' => ['___很冷。', '___是新年。', '今天是___一号。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '二月',
                'pinyin' => 'èr yuè',
                'simplified' => '二月',
                'traditional' => '二月',
                'part_of_speech' => 'noun',
                'meaning' => 'February',
                'meaning_zh' => '二月',
                'example_sentence' => '二月有春节。',
                'example_translation' => 'February has Spring Festival.',
                'definition' => 'The second month',
                'sentences' => ['___有春节。', '___很短。', '今天是___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '三月',
                'pinyin' => 'sān yuè',
                'simplified' => '三月',
                'traditional' => '三月',
                'part_of_speech' => 'noun',
                'meaning' => 'March',
                'meaning_zh' => '三月',
                'example_sentence' => '三月是春天。',
                'example_translation' => 'March is spring.',
                'definition' => 'The third month',
                'sentences' => ['___是春天。', '___的天气很好。', '___八号。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '四月',
                'pinyin' => 'sì yuè',
                'simplified' => '四月',
                'traditional' => '四月',
                'part_of_speech' => 'noun',
                'meaning' => 'April',
                'meaning_zh' => '四月',
                'example_sentence' => '四月有清明节。',
                'example_translation' => 'April has Qingming Festival.',
                'definition' => 'The fourth month',
                'sentences' => ['___有清明节。', '___的花很美。', '___天气暖和。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '五月',
                'pinyin' => 'wǔ yuè',
                'simplified' => '五月',
                'traditional' => '五月',
                'part_of_speech' => 'noun',
                'meaning' => 'May',
                'meaning_zh' => '五月',
                'example_sentence' => '五月一号是劳动节。',
                'example_translation' => 'May 1st is Labor Day.',
                'definition' => 'The fifth month',
                'sentences' => ['___一号是劳动节。', '___天气很好。', '___有假期。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '六月',
                'pinyin' => 'liù yuè',
                'simplified' => '六月',
                'traditional' => '六月',
                'part_of_speech' => 'noun',
                'meaning' => 'June',
                'meaning_zh' => '六月',
                'example_sentence' => '六月很热。',
                'example_translation' => 'June is very hot.',
                'definition' => 'The sixth month',
                'sentences' => ['___很热。', '___要放暑假了。', '___一号儿童节。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '七月',
                'pinyin' => 'qī yuè',
                'simplified' => '七月',
                'traditional' => '七月',
                'part_of_speech' => 'noun',
                'meaning' => 'July',
                'meaning_zh' => '七月',
                'example_sentence' => '七月是暑假。',
                'example_translation' => 'July is summer vacation.',
                'definition' => 'The seventh month',
                'sentences' => ['___是暑假。', '___很热。', '___去旅游。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '八月',
                'pinyin' => 'bā yuè',
                'simplified' => '八月',
                'traditional' => '八月',
                'part_of_speech' => 'noun',
                'meaning' => 'August',
                'meaning_zh' => '八月',
                'example_sentence' => '八月还在放暑假。',
                'example_translation' => 'August is still summer vacation.',
                'definition' => 'The eighth month',
                'sentences' => ['___还在放暑假。', '___很热。', '___十五中秋节。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '九月',
                'pinyin' => 'jiǔ yuè',
                'simplified' => '九月',
                'traditional' => '九月',
                'part_of_speech' => 'noun',
                'meaning' => 'September',
                'meaning_zh' => '九月',
                'example_sentence' => '九月开学了。',
                'example_translation' => 'School starts in September.',
                'definition' => 'The ninth month',
                'sentences' => ['___开学了。', '___十号教师节。', '___天气凉爽。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '十月',
                'pinyin' => 'shí yuè',
                'simplified' => '十月',
                'traditional' => '十月',
                'part_of_speech' => 'noun',
                'meaning' => 'October',
                'meaning_zh' => '十月',
                'example_sentence' => '十月一号是国庆节。',
                'example_translation' => 'October 1st is National Day.',
                'definition' => 'The tenth month',
                'sentences' => ['___一号是国庆节。', '___是秋天。', '___有假期。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '十一月',
                'pinyin' => 'shí yī yuè',
                'simplified' => '十一月',
                'traditional' => '十一月',
                'part_of_speech' => 'noun',
                'meaning' => 'November',
                'meaning_zh' => '十一月',
                'example_sentence' => '十一月开始冷了。',
                'example_translation' => 'It starts to get cold in November.',
                'definition' => 'The eleventh month',
                'sentences' => ['___开始冷了。', '___是秋天。', '___的树叶变黄了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '十二月',
                'pinyin' => 'shí èr yuè',
                'simplified' => '十二月',
                'traditional' => '十二月',
                'part_of_speech' => 'noun',
                'meaning' => 'December',
                'meaning_zh' => '十二月',
                'example_sentence' => '十二月是冬天。',
                'example_translation' => 'December is winter.',
                'definition' => 'The twelfth month',
                'sentences' => ['___是冬天。', '___很冷。', '___二十五圣诞节。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '春天',
                'pinyin' => 'chūn tiān',
                'simplified' => '春天',
                'traditional' => '春天',
                'part_of_speech' => 'noun',
                'meaning' => 'Spring',
                'meaning_zh' => '春天',
                'example_sentence' => '春天很暖和。',
                'example_translation' => 'Spring is very warm.',
                'definition' => 'Spring season',
                'sentences' => ['___很暖和。', '___的花很美。', '我喜欢___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '夏天',
                'pinyin' => 'xià tiān',
                'simplified' => '夏天',
                'traditional' => '夏天',
                'part_of_speech' => 'noun',
                'meaning' => 'Summer',
                'meaning_zh' => '夏天',
                'example_sentence' => '夏天很热。',
                'example_translation' => 'Summer is very hot.',
                'definition' => 'Summer season',
                'sentences' => ['___很热。', '___可以游泳。', '___我去海边。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '秋天',
                'pinyin' => 'qiū tiān',
                'simplified' => '秋天',
                'traditional' => '秋天',
                'part_of_speech' => 'noun',
                'meaning' => 'Autumn / Fall',
                'meaning_zh' => '秋天',
                'example_sentence' => '秋天很凉爽。',
                'example_translation' => 'Autumn is very cool.',
                'definition' => 'Autumn season',
                'sentences' => ['___很凉爽。', '___的树叶变黄了。', '___是收获的季节。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '冬天',
                'pinyin' => 'dōng tiān',
                'simplified' => '冬天',
                'traditional' => '冬天',
                'part_of_speech' => 'noun',
                'meaning' => 'Winter',
                'meaning_zh' => '冬天',
                'example_sentence' => '冬天很冷。',
                'example_translation' => 'Winter is very cold.',
                'definition' => 'Winter season',
                'sentences' => ['___很冷。', '___会下雪。', '___要穿棉衣。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 6,
                'word' => '季节',
                'pinyin' => 'jì jié',
                'simplified' => '季节',
                'traditional' => '季節',
                'part_of_speech' => 'noun',
                'meaning' => 'Season',
                'meaning_zh' => '季节',
                'example_sentence' => '一年有四个季节。',
                'example_translation' => 'There are four seasons in a year.',
                'definition' => 'Season',
                'sentences' => ['一年有四个___。', '你喜欢什么___？', '每个___都有特点。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 7: Time and Date (24 words)
        $timeDateVocab = [
            [
                'topic_id' => 7,
                'word' => '时间',
                'pinyin' => 'shí jiān',
                'simplified' => '时间',
                'traditional' => '時間',
                'part_of_speech' => 'noun',
                'meaning' => 'Time',
                'meaning_zh' => '时间',
                'example_sentence' => '现在几点了？',
                'example_translation' => 'What time is it now?',
                'definition' => 'Time',
                'sentences' => ['现在什么___？', '___过得很快。', '我没有___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '点',
                'pinyin' => 'diǎn',
                'simplified' => '点',
                'traditional' => '點',
                'part_of_speech' => 'measure word',
                'meaning' => "O'clock",
                'meaning_zh' => '点',
                'example_sentence' => '现在三点。',
                'example_translation' => "It's three o'clock now.",
                'definition' => 'Hour, o\'clock',
                'sentences' => ['现在三___。', '几___了？', '八___上课。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '分',
                'pinyin' => 'fēn',
                'simplified' => '分',
                'traditional' => '分',
                'part_of_speech' => 'measure word',
                'meaning' => 'Minute',
                'meaning_zh' => '分',
                'example_sentence' => '三点十五分。',
                'example_translation' => 'Three fifteen.',
                'definition' => 'Minute',
                'sentences' => ['三点十五___。', '等我五___。', '还有十___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '半',
                'pinyin' => 'bàn',
                'simplified' => '半',
                'traditional' => '半',
                'part_of_speech' => 'number',
                'meaning' => 'Half',
                'meaning_zh' => '半',
                'example_sentence' => '三点半。',
                'example_translation' => 'Three thirty.',
                'definition' => 'Half, half past',
                'sentences' => ['三点___。', '___个小时。', '___天。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '刻',
                'pinyin' => 'kè',
                'simplified' => '刻',
                'traditional' => '刻',
                'part_of_speech' => 'measure word',
                'meaning' => 'Quarter (15 minutes)',
                'meaning_zh' => '刻',
                'example_sentence' => '三点一刻。',
                'example_translation' => 'Three fifteen.',
                'definition' => 'Quarter hour',
                'sentences' => ['三点一___。', '差一___九点。', '两___钟。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '小时',
                'pinyin' => 'xiǎo shí',
                'simplified' => '小时',
                'traditional' => '小時',
                'part_of_speech' => 'noun',
                'meaning' => 'Hour',
                'meaning_zh' => '小时',
                'example_sentence' => '两个小时。',
                'example_translation' => 'Two hours.',
                'definition' => 'Hour (duration)',
                'sentences' => ['两个___。', '一___有六十分钟。', '等了三___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '分钟',
                'pinyin' => 'fēn zhōng',
                'simplified' => '分钟',
                'traditional' => '分鐘',
                'part_of_speech' => 'noun',
                'meaning' => 'Minute',
                'meaning_zh' => '分钟',
                'example_sentence' => '十分钟。',
                'example_translation' => 'Ten minutes.',
                'definition' => 'Minute (duration)',
                'sentences' => ['十___。', '等我五___。', '还有二十___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '天',
                'pinyin' => 'tiān',
                'simplified' => '天',
                'traditional' => '天',
                'part_of_speech' => 'noun',
                'meaning' => 'Day / Sky',
                'meaning_zh' => '天',
                'example_sentence' => '今天星期几？',
                'example_translation' => 'What day is today?',
                'definition' => 'Day, sky, heaven',
                'sentences' => ['今___星期几？', '___气很好。', '三___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '今天',
                'pinyin' => 'jīn tiān',
                'simplified' => '今天',
                'traditional' => '今天',
                'part_of_speech' => 'noun',
                'meaning' => 'Today',
                'meaning_zh' => '今天',
                'example_sentence' => '今天是星期一。',
                'example_translation' => 'Today is Monday.',
                'definition' => 'Today',
                'sentences' => ['___是星期一。', '___天气很好。', '___我很忙。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '明天',
                'pinyin' => 'míng tiān',
                'simplified' => '明天',
                'traditional' => '明天',
                'part_of_speech' => 'noun',
                'meaning' => 'Tomorrow',
                'meaning_zh' => '明天',
                'example_sentence' => '明天见！',
                'example_translation' => 'See you tomorrow!',
                'definition' => 'Tomorrow',
                'sentences' => ['___见！', '___是星期二。', '___去北京。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '昨天',
                'pinyin' => 'zuó tiān',
                'simplified' => '昨天',
                'traditional' => '昨天',
                'part_of_speech' => 'noun',
                'meaning' => 'Yesterday',
                'meaning_zh' => '昨天',
                'example_sentence' => '昨天我去了北京。',
                'example_translation' => 'I went to Beijing yesterday.',
                'definition' => 'Yesterday',
                'sentences' => ['___我去了北京。', '___是星期天。', '___下雨了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期',
                'pinyin' => 'xīng qī',
                'simplified' => '星期',
                'traditional' => '星期',
                'part_of_speech' => 'noun',
                'meaning' => 'Week',
                'meaning_zh' => '星期',
                'example_sentence' => '今天星期几？',
                'example_translation' => 'What day is it today?',
                'definition' => 'Week',
                'sentences' => ['今天___几？', '这个___很忙。', '下___见。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期一',
                'pinyin' => 'xīng qī yī',
                'simplified' => '星期一',
                'traditional' => '星期一',
                'part_of_speech' => 'noun',
                'meaning' => 'Monday',
                'meaning_zh' => '星期一',
                'example_sentence' => '今天是星期一。',
                'example_translation' => 'Today is Monday.',
                'definition' => 'Monday',
                'sentences' => ['今天是___。', '___要上班。', '___很忙。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期二',
                'pinyin' => 'xīng qī èr',
                'simplified' => '星期二',
                'traditional' => '星期二',
                'part_of_speech' => 'noun',
                'meaning' => 'Tuesday',
                'meaning_zh' => '星期二',
                'example_sentence' => '星期二有课。',
                'example_translation' => 'There is class on Tuesday.',
                'definition' => 'Tuesday',
                'sentences' => ['___有课。', '明天是___。', '___去医院。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期三',
                'pinyin' => 'xīng qī sān',
                'simplified' => '星期三',
                'traditional' => '星期三',
                'part_of_speech' => 'noun',
                'meaning' => 'Wednesday',
                'meaning_zh' => '星期三',
                'example_sentence' => '星期三是周中。',
                'example_translation' => 'Wednesday is mid-week.',
                'definition' => 'Wednesday',
                'sentences' => ['___是周中。', '今天___。', '___有会议。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期四',
                'pinyin' => 'xīng qī sì',
                'simplified' => '星期四',
                'traditional' => '星期四',
                'part_of_speech' => 'noun',
                'meaning' => 'Thursday',
                'meaning_zh' => '星期四',
                'example_sentence' => '星期四去购物。',
                'example_translation' => 'Go shopping on Thursday.',
                'definition' => 'Thursday',
                'sentences' => ['___去购物。', '今天是___。', '___有考试。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期五',
                'pinyin' => 'xīng qī wǔ',
                'simplified' => '星期五',
                'traditional' => '星期五',
                'part_of_speech' => 'noun',
                'meaning' => 'Friday',
                'meaning_zh' => '星期五',
                'example_sentence' => '星期五下班后去聚餐。',
                'example_translation' => 'Have dinner together after work on Friday.',
                'definition' => 'Friday',
                'sentences' => ['___下班后去聚餐。', '明天是___。', '___很开心。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期六',
                'pinyin' => 'xīng qī liù',
                'simplified' => '星期六',
                'traditional' => '星期六',
                'part_of_speech' => 'noun',
                'meaning' => 'Saturday',
                'meaning_zh' => '星期六',
                'example_sentence' => '星期六休息。',
                'example_translation' => 'Rest on Saturday.',
                'definition' => 'Saturday',
                'sentences' => ['___休息。', '___去旅游。', '___睡懒觉。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '星期天',
                'pinyin' => 'xīng qī tiān',
                'simplified' => '星期天',
                'traditional' => '星期天',
                'part_of_speech' => 'noun',
                'meaning' => 'Sunday',
                'meaning_zh' => '星期天',
                'example_sentence' => '星期天不上班。',
                'example_translation' => 'No work on Sunday.',
                'definition' => 'Sunday',
                'sentences' => ['___不上班。', '___去教堂。', '___在家休息。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '周末',
                'pinyin' => 'zhōu mò',
                'simplified' => '周末',
                'traditional' => '周末',
                'part_of_speech' => 'noun',
                'meaning' => 'Weekend',
                'meaning_zh' => '周末',
                'example_sentence' => '周末愉快！',
                'example_translation' => 'Have a nice weekend!',
                'definition' => 'Weekend',
                'sentences' => ['___愉快！', '___去哪里？', '___休息。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '年',
                'pinyin' => 'nián',
                'simplified' => '年',
                'traditional' => '年',
                'part_of_speech' => 'noun',
                'meaning' => 'Year',
                'meaning_zh' => '年',
                'example_sentence' => '今年是2025年。',
                'example_translation' => 'This year is 2025.',
                'definition' => 'Year',
                'sentences' => ['今___是2025___。', '一___有十二个月。', '明___见。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '号',
                'pinyin' => 'hào',
                'simplified' => '号',
                'traditional' => '號',
                'part_of_speech' => 'measure word',
                'meaning' => 'Day of month / Number',
                'meaning_zh' => '号',
                'example_sentence' => '今天是十号。',
                'example_translation' => 'Today is the 10th.',
                'definition' => 'Date, number',
                'sentences' => ['今天是十___。', '几___了？', '一___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '现在',
                'pinyin' => 'xiàn zài',
                'simplified' => '现在',
                'traditional' => '現在',
                'part_of_speech' => 'noun',
                'meaning' => 'Now',
                'meaning_zh' => '现在',
                'example_sentence' => '现在几点？',
                'example_translation' => 'What time is it now?',
                'definition' => 'Now, at present',
                'sentences' => ['___几点？', '___开始。', '___很忙。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 7,
                'word' => '时候',
                'pinyin' => 'shí hou',
                'simplified' => '时候',
                'traditional' => '時候',
                'part_of_speech' => 'noun',
                'meaning' => 'Time / When',
                'meaning_zh' => '时候',
                'example_sentence' => '什么时候去？',
                'example_translation' => 'When are you going?',
                'definition' => 'Time, moment, when',
                'sentences' => ['什么___去？', '那个___。', '这个___很忙。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 8: Personal Information (12 words)
        $personalInfoVocab = [
            [
                'topic_id' => 8,
                'word' => '叫',
                'pinyin' => 'jiào',
                'simplified' => '叫',
                'traditional' => '叫',
                'part_of_speech' => 'verb',
                'meaning' => 'To be called / To call',
                'meaning_zh' => '叫',
                'example_sentence' => '我叫李明。',
                'example_translation' => 'My name is Li Ming.',
                'definition' => 'To be called, to call',
                'sentences' => ['我___李明。', '你___什么名字？', '他___我。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '岁',
                'pinyin' => 'suì',
                'simplified' => '岁',
                'traditional' => '歲',
                'part_of_speech' => 'measure word',
                'meaning' => 'Years old',
                'meaning_zh' => '岁',
                'example_sentence' => '我二十岁。',
                'example_translation' => 'I am twenty years old.',
                'definition' => 'Years of age',
                'sentences' => ['我二十___。', '你几___？', '他十___了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '国',
                'pinyin' => 'guó',
                'simplified' => '国',
                'traditional' => '國',
                'part_of_speech' => 'noun',
                'meaning' => 'Country',
                'meaning_zh' => '国',
                'example_sentence' => '中国很大。',
                'example_translation' => 'China is very big.',
                'definition' => 'Country, nation',
                'sentences' => ['中___很大。', '美___。', '哪个___？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '中国',
                'pinyin' => 'zhōng guó',
                'simplified' => '中国',
                'traditional' => '中國',
                'part_of_speech' => 'noun',
                'meaning' => 'China',
                'meaning_zh' => '中国',
                'example_sentence' => '我是中国人。',
                'example_translation' => 'I am Chinese.',
                'definition' => 'China',
                'sentences' => ['我是___人。', '___很大。', '___的文化。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '北京',
                'pinyin' => 'běi jīng',
                'simplified' => '北京',
                'traditional' => '北京',
                'part_of_speech' => 'noun',
                'meaning' => 'Beijing',
                'meaning_zh' => '北京',
                'example_sentence' => '我住在北京。',
                'example_translation' => 'I live in Beijing.',
                'definition' => 'Beijing, capital of China',
                'sentences' => ['我住在___。', '___是首都。', '去___旅游。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '上海',
                'pinyin' => 'shàng hǎi',
                'simplified' => '上海',
                'traditional' => '上海',
                'part_of_speech' => 'noun',
                'meaning' => 'Shanghai',
                'meaning_zh' => '上海',
                'example_sentence' => '上海很繁华。',
                'example_translation' => 'Shanghai is very prosperous.',
                'definition' => 'Shanghai city',
                'sentences' => ['___很繁华。', '我在___工作。', '___的东方明珠。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '电话',
                'pinyin' => 'diàn huà',
                'simplified' => '电话',
                'traditional' => '電話',
                'part_of_speech' => 'noun',
                'meaning' => 'Telephone / Phone call',
                'meaning_zh' => '电话',
                'example_sentence' => '这是我的电话号码。',
                'example_translation' => 'This is my phone number.',
                'definition' => 'Telephone, phone',
                'sentences' => ['这是我的___号码。', '打___。', '接___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '手机',
                'pinyin' => 'shǒu jī',
                'simplified' => '手机',
                'traditional' => '手機',
                'part_of_speech' => 'noun',
                'meaning' => 'Mobile phone',
                'meaning_zh' => '手机',
                'example_sentence' => '我的手机号码是多少？',
                'example_translation' => 'What is my mobile phone number?',
                'definition' => 'Cell phone, mobile phone',
                'sentences' => ['我的___号码是多少？', '___响了。', '用___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '认识',
                'pinyin' => 'rèn shi',
                'simplified' => '认识',
                'traditional' => '認識',
                'part_of_speech' => 'verb',
                'meaning' => 'To know / To recognize',
                'meaning_zh' => '认识',
                'example_sentence' => '很高兴认识你。',
                'example_translation' => 'Nice to meet you.',
                'definition' => 'To know, to recognize',
                'sentences' => ['很高兴___你。', '我___他。', '我们___吗？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '住',
                'pinyin' => 'zhù',
                'simplified' => '住',
                'traditional' => '住',
                'part_of_speech' => 'verb',
                'meaning' => 'To live / To stay',
                'meaning_zh' => '住',
                'example_sentence' => '我住在北京。',
                'example_translation' => 'I live in Beijing.',
                'definition' => 'To live, to reside',
                'sentences' => ['我___在北京。', '你___哪里？', '___酒店。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '工作',
                'pinyin' => 'gōng zuò',
                'simplified' => '工作',
                'traditional' => '工作',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Work / To work',
                'meaning_zh' => '工作',
                'example_sentence' => '我在公司工作。',
                'example_translation' => 'I work at a company.',
                'definition' => 'Work, job, to work',
                'sentences' => ['我在公司___。', '找___。', '___很忙。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 8,
                'word' => '学习',
                'pinyin' => 'xué xí',
                'simplified' => '学习',
                'traditional' => '學習',
                'part_of_speech' => 'verb',
                'meaning' => 'To study / To learn',
                'meaning_zh' => '学习',
                'example_sentence' => '我在学习中文。',
                'example_translation' => 'I am studying Chinese.',
                'definition' => 'To study, to learn',
                'sentences' => ['我在___中文。', '___很重要。', '努力___。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 9: The Body (9 words)
        $bodyVocab = [
            [
                'topic_id' => 9,
                'word' => '身体',
                'pinyin' => 'shēn tǐ',
                'simplified' => '身体',
                'traditional' => '身體',
                'part_of_speech' => 'noun',
                'meaning' => 'Body / Health',
                'meaning_zh' => '身体',
                'example_sentence' => '身体健康很重要。',
                'example_translation' => 'Good health is very important.',
                'definition' => 'Body, health',
                'sentences' => ['___健康很重要。', '我的___很好。', '注意___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '手',
                'pinyin' => 'shǒu',
                'simplified' => '手',
                'traditional' => '手',
                'part_of_speech' => 'noun',
                'meaning' => 'Hand',
                'meaning_zh' => '手',
                'example_sentence' => '洗手。',
                'example_translation' => 'Wash hands.',
                'definition' => 'Hand',
                'sentences' => ['洗___。', '举___。', '___机。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '脚',
                'pinyin' => 'jiǎo',
                'simplified' => '脚',
                'traditional' => '腳',
                'part_of_speech' => 'noun',
                'meaning' => 'Foot / Leg',
                'meaning_zh' => '脚',
                'example_sentence' => '我的脚很累。',
                'example_translation' => 'My feet are very tired.',
                'definition' => 'Foot, leg',
                'sentences' => ['我的___很累。', '___痛。', '踢___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '肚子',
                'pinyin' => 'dù zi',
                'simplified' => '肚子',
                'traditional' => '肚子',
                'part_of_speech' => 'noun',
                'meaning' => 'Belly / Stomach',
                'meaning_zh' => '肚子',
                'example_sentence' => '我肚子饿了。',
                'example_translation' => 'I am hungry.',
                'definition' => 'Belly, stomach',
                'sentences' => ['我___饿了。', '___痛。', '___很大。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '腿',
                'pinyin' => 'tuǐ',
                'simplified' => '腿',
                'traditional' => '腿',
                'part_of_speech' => 'noun',
                'meaning' => 'Leg',
                'meaning_zh' => '腿',
                'example_sentence' => '我的腿很长。',
                'example_translation' => 'My legs are very long.',
                'definition' => 'Leg',
                'sentences' => ['我的___很长。', '___痛。', '大___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '胳膊',
                'pinyin' => 'gē bo',
                'simplified' => '胳膊',
                'traditional' => '胳膊',
                'part_of_speech' => 'noun',
                'meaning' => 'Arm',
                'meaning_zh' => '胳膊',
                'example_sentence' => '我的胳膊很有力。',
                'example_translation' => 'My arms are very strong.',
                'definition' => 'Arm',
                'sentences' => ['我的___很有力。', '___痛。', '举起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '心',
                'pinyin' => 'xīn',
                'simplified' => '心',
                'traditional' => '心',
                'part_of_speech' => 'noun',
                'meaning' => 'Heart',
                'meaning_zh' => '心',
                'example_sentence' => '我很开心。',
                'example_translation' => 'I am very happy.',
                'definition' => 'Heart, mind',
                'sentences' => ['我很开___。', '___情很好。', '放___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '背',
                'pinyin' => 'bèi',
                'simplified' => '背',
                'traditional' => '背',
                'part_of_speech' => 'noun',
                'meaning' => 'Back',
                'meaning_zh' => '背',
                'example_sentence' => '我的背很痛。',
                'example_translation' => 'My back hurts.',
                'definition' => 'Back (of body)',
                'sentences' => ['我的___很痛。', '___包。', '转___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 9,
                'word' => '血',
                'pinyin' => 'xiě / xuè',
                'simplified' => '血',
                'traditional' => '血',
                'part_of_speech' => 'noun',
                'meaning' => 'Blood',
                'meaning_zh' => '血',
                'example_sentence' => '献血很有意义。',
                'example_translation' => 'Donating blood is very meaningful.',
                'definition' => 'Blood',
                'sentences' => ['献___很有意义。', '流___了。', '___压。'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($monthsSeasonsVocab, $timeDateVocab, $personalInfoVocab, $bodyVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
