<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk1Topics17to19Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 17: Basic Verbs (基本动词) - 25 words
        $basicVerbsVocab = [
            [
                'topic_id' => 17,
                'word' => '是',
                'pinyin' => 'shì',
                'simplified' => '是',
                'traditional' => '是',
                'part_of_speech' => 'verb',
                'meaning' => 'To be / Am, is, are',
                'meaning_zh' => '是',
                'example_sentence' => '我是学生。',
                'example_translation' => 'I am a student.',
                'definition' => 'To be, am, is, are',
                'sentences' => ['我___学生。', '他___老师。', '这___书。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '有',
                'pinyin' => 'yǒu',
                'simplified' => '有',
                'traditional' => '有',
                'part_of_speech' => 'verb',
                'meaning' => 'To have / There is/are',
                'meaning_zh' => '有',
                'example_sentence' => '我有一本书。',
                'example_translation' => 'I have a book.',
                'definition' => 'To have, to possess, there is/are',
                'sentences' => ['我___一本书。', '___人吗？', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '在',
                'pinyin' => 'zài',
                'simplified' => '在',
                'traditional' => '在',
                'part_of_speech' => 'verb',
                'meaning' => 'To be at / To be in',
                'meaning_zh' => '在',
                'example_sentence' => '我在家。',
                'example_translation' => 'I am at home.',
                'definition' => 'To be located at, to exist at',
                'sentences' => ['我___家。', '他___哪儿？', '___北京。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '来',
                'pinyin' => 'lái',
                'simplified' => '来',
                'traditional' => '來',
                'part_of_speech' => 'verb',
                'meaning' => 'To come',
                'meaning_zh' => '来',
                'example_sentence' => '请来我家。',
                'example_translation' => 'Please come to my house.',
                'definition' => 'To come, to arrive',
                'sentences' => ['请___我家。', '他___了。', '___吧。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '去',
                'pinyin' => 'qù',
                'simplified' => '去',
                'traditional' => '去',
                'part_of_speech' => 'verb',
                'meaning' => 'To go',
                'meaning_zh' => '去',
                'example_sentence' => '我去学校。',
                'example_translation' => 'I go to school.',
                'definition' => 'To go, to leave for',
                'sentences' => ['我___学校。', '___哪儿？', '___中国。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '吃',
                'pinyin' => 'chī',
                'simplified' => '吃',
                'traditional' => '吃',
                'part_of_speech' => 'verb',
                'meaning' => 'To eat',
                'meaning_zh' => '吃',
                'example_sentence' => '我吃饭。',
                'example_translation' => 'I eat (a meal).',
                'definition' => 'To eat, to have a meal',
                'sentences' => ['我___饭。', '___什么？', '___苹果。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '喝',
                'pinyin' => 'hē',
                'simplified' => '喝',
                'traditional' => '喝',
                'part_of_speech' => 'verb',
                'meaning' => 'To drink',
                'meaning_zh' => '喝',
                'example_sentence' => '我喝水。',
                'example_translation' => 'I drink water.',
                'definition' => 'To drink',
                'sentences' => ['我___水。', '___茶。', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '看',
                'pinyin' => 'kàn',
                'simplified' => '看',
                'traditional' => '看',
                'part_of_speech' => 'verb',
                'meaning' => 'To see / To look / To watch',
                'meaning_zh' => '看',
                'example_sentence' => '我看书。',
                'example_translation' => 'I read a book.',
                'definition' => 'To see, to look at, to watch, to read',
                'sentences' => ['我___书。', '___电视。', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '听',
                'pinyin' => 'tīng',
                'simplified' => '听',
                'traditional' => '聽',
                'part_of_speech' => 'verb',
                'meaning' => 'To listen / To hear',
                'meaning_zh' => '听',
                'example_sentence' => '我听音乐。',
                'example_translation' => 'I listen to music.',
                'definition' => 'To listen, to hear',
                'sentences' => ['我___音乐。', '___什么？', '___老师说。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '说',
                'pinyin' => 'shuō',
                'simplified' => '说',
                'traditional' => '說',
                'part_of_speech' => 'verb',
                'meaning' => 'To say / To speak',
                'meaning_zh' => '说',
                'example_sentence' => '我说中文。',
                'example_translation' => 'I speak Chinese.',
                'definition' => 'To say, to speak, to talk',
                'sentences' => ['我___中文。', '___什么？', '___英语。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '读',
                'pinyin' => 'dú',
                'simplified' => '读',
                'traditional' => '讀',
                'part_of_speech' => 'verb',
                'meaning' => 'To read / To study',
                'meaning_zh' => '读',
                'example_sentence' => '我读书。',
                'example_translation' => 'I read books.',
                'definition' => 'To read, to study',
                'sentences' => ['我___书。', '___大学。', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '写',
                'pinyin' => 'xiě',
                'simplified' => '写',
                'traditional' => '寫',
                'part_of_speech' => 'verb',
                'meaning' => 'To write',
                'meaning_zh' => '写',
                'example_sentence' => '我写字。',
                'example_translation' => 'I write characters.',
                'definition' => 'To write',
                'sentences' => ['我___字。', '___名字。', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '做',
                'pinyin' => 'zuò',
                'simplified' => '做',
                'traditional' => '做',
                'part_of_speech' => 'verb',
                'meaning' => 'To do / To make',
                'meaning_zh' => '做',
                'example_sentence' => '我做作业。',
                'example_translation' => 'I do homework.',
                'definition' => 'To do, to make, to produce',
                'sentences' => ['我___作业。', '___什么？', '___饭。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '坐',
                'pinyin' => 'zuò',
                'simplified' => '坐',
                'traditional' => '坐',
                'part_of_speech' => 'verb',
                'meaning' => 'To sit',
                'meaning_zh' => '坐',
                'example_sentence' => '请坐。',
                'example_translation' => 'Please sit.',
                'definition' => 'To sit, to take (transport)',
                'sentences' => ['请___。', '___飞机。', '___这儿。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '站',
                'pinyin' => 'zhàn',
                'simplified' => '站',
                'traditional' => '站',
                'part_of_speech' => 'verb',
                'meaning' => 'To stand',
                'meaning_zh' => '站',
                'example_sentence' => '请站起来。',
                'example_translation' => 'Please stand up.',
                'definition' => 'To stand',
                'sentences' => ['请___起来。', '___在这儿。', '___着。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '走',
                'pinyin' => 'zǒu',
                'simplified' => '走',
                'traditional' => '走',
                'part_of_speech' => 'verb',
                'meaning' => 'To walk / To go',
                'meaning_zh' => '走',
                'example_sentence' => '我走路去学校。',
                'example_translation' => 'I walk to school.',
                'definition' => 'To walk, to go, to leave',
                'sentences' => ['我___路去学校。', '___吧。', '___了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '跑',
                'pinyin' => 'pǎo',
                'simplified' => '跑',
                'traditional' => '跑',
                'part_of_speech' => 'verb',
                'meaning' => 'To run',
                'meaning_zh' => '跑',
                'example_sentence' => '他跑得很快。',
                'example_translation' => 'He runs very fast.',
                'definition' => 'To run',
                'sentences' => ['他___得很快。', '___步。', '快___！'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '睡',
                'pinyin' => 'shuì',
                'simplified' => '睡',
                'traditional' => '睡',
                'part_of_speech' => 'verb',
                'meaning' => 'To sleep',
                'meaning_zh' => '睡',
                'example_sentence' => '我睡觉。',
                'example_translation' => 'I sleep.',
                'definition' => 'To sleep',
                'sentences' => ['我___觉。', '___着了。', '___不着。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '起',
                'pinyin' => 'qǐ',
                'simplified' => '起',
                'traditional' => '起',
                'part_of_speech' => 'verb',
                'meaning' => 'To get up / To rise',
                'meaning_zh' => '起',
                'example_sentence' => '我起床了。',
                'example_translation' => 'I got up.',
                'definition' => 'To get up, to rise',
                'sentences' => ['我___床了。', '___来。', '___得很早。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '开',
                'pinyin' => 'kāi',
                'simplified' => '开',
                'traditional' => '開',
                'part_of_speech' => 'verb',
                'meaning' => 'To open / To turn on',
                'meaning_zh' => '开',
                'example_sentence' => '请开门。',
                'example_translation' => 'Please open the door.',
                'definition' => 'To open, to turn on, to drive',
                'sentences' => ['请___门。', '___灯。', '___车。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '关',
                'pinyin' => 'guān',
                'simplified' => '关',
                'traditional' => '關',
                'part_of_speech' => 'verb',
                'meaning' => 'To close / To turn off',
                'meaning_zh' => '关',
                'example_sentence' => '请关门。',
                'example_translation' => 'Please close the door.',
                'definition' => 'To close, to turn off, to shut',
                'sentences' => ['请___门。', '___灯。', '___电视。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '叫',
                'pinyin' => 'jiào',
                'simplified' => '叫',
                'traditional' => '叫',
                'part_of_speech' => 'verb',
                'meaning' => 'To be called / To call',
                'meaning_zh' => '叫',
                'example_sentence' => '我叫李明。',
                'example_translation' => 'My name is Li Ming.',
                'definition' => 'To be called, to call, to shout',
                'sentences' => ['我___李明。', '___什么名字？', '___他来。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '打',
                'pinyin' => 'dǎ',
                'simplified' => '打',
                'traditional' => '打',
                'part_of_speech' => 'verb',
                'meaning' => 'To hit / To play / To make (call)',
                'meaning_zh' => '打',
                'example_sentence' => '我打电话。',
                'example_translation' => 'I make a phone call.',
                'definition' => 'To hit, to strike, to play, to make',
                'sentences' => ['我___电话。', '___球。', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '给',
                'pinyin' => 'gěi',
                'simplified' => '给',
                'traditional' => '給',
                'part_of_speech' => 'verb',
                'meaning' => 'To give',
                'meaning_zh' => '给',
                'example_sentence' => '我给你书。',
                'example_translation' => 'I give you the book.',
                'definition' => 'To give, to provide',
                'sentences' => ['我___你书。', '___我。', '___他打电话。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 17,
                'word' => '问',
                'pinyin' => 'wèn',
                'simplified' => '问',
                'traditional' => '問',
                'part_of_speech' => 'verb',
                'meaning' => 'To ask',
                'meaning_zh' => '问',
                'example_sentence' => '我问你一个问题。',
                'example_translation' => 'I ask you a question.',
                'definition' => 'To ask, to inquire',
                'sentences' => ['我___你一个问题。', '___老师。', '___什么？'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 18: Household Items (家居用品) - 20 words
        $householdItemsVocab = [
            [
                'topic_id' => 18,
                'word' => '书',
                'pinyin' => 'shū',
                'simplified' => '书',
                'traditional' => '書',
                'part_of_speech' => 'noun',
                'meaning' => 'Book',
                'meaning_zh' => '书',
                'example_sentence' => '这是一本书。',
                'example_translation' => 'This is a book.',
                'definition' => 'Book',
                'sentences' => ['这是一本___。', '看___。', '___很有趣。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '笔',
                'pinyin' => 'bǐ',
                'simplified' => '笔',
                'traditional' => '筆',
                'part_of_speech' => 'noun',
                'meaning' => 'Pen / Writing instrument',
                'meaning_zh' => '笔',
                'example_sentence' => '我有一支笔。',
                'example_translation' => 'I have a pen.',
                'definition' => 'Pen, pencil, writing instrument',
                'sentences' => ['我有一支___。', '___很好用。', '借___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '本子',
                'pinyin' => 'běn zi',
                'simplified' => '本子',
                'traditional' => '本子',
                'part_of_speech' => 'noun',
                'meaning' => 'Notebook',
                'meaning_zh' => '本子',
                'example_sentence' => '我买了一个本子。',
                'example_translation' => 'I bought a notebook.',
                'definition' => 'Notebook',
                'sentences' => ['我买了一个___。', '___很厚。', '写___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '纸',
                'pinyin' => 'zhǐ',
                'simplified' => '纸',
                'traditional' => '紙',
                'part_of_speech' => 'noun',
                'meaning' => 'Paper',
                'meaning_zh' => '纸',
                'example_sentence' => '我需要一张纸。',
                'example_translation' => 'I need a piece of paper.',
                'definition' => 'Paper',
                'sentences' => ['我需要一张___。', '___很白。', '卫生___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '杯子',
                'pinyin' => 'bēi zi',
                'simplified' => '杯子',
                'traditional' => '杯子',
                'part_of_speech' => 'noun',
                'meaning' => 'Cup / Glass',
                'meaning_zh' => '杯子',
                'example_sentence' => '这是我的杯子。',
                'example_translation' => 'This is my cup.',
                'definition' => 'Cup, glass, mug',
                'sentences' => ['这是我的___。', '___很漂亮。', '一___水。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '碗',
                'pinyin' => 'wǎn',
                'simplified' => '碗',
                'traditional' => '碗',
                'part_of_speech' => 'noun',
                'meaning' => 'Bowl',
                'meaning_zh' => '碗',
                'example_sentence' => '一碗饭。',
                'example_translation' => 'A bowl of rice.',
                'definition' => 'Bowl',
                'sentences' => ['一___饭。', '___很大。', '洗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '盘子',
                'pinyin' => 'pán zi',
                'simplified' => '盘子',
                'traditional' => '盤子',
                'part_of_speech' => 'noun',
                'meaning' => 'Plate / Dish',
                'meaning_zh' => '盘子',
                'example_sentence' => '盘子里有菜。',
                'example_translation' => 'There are dishes on the plate.',
                'definition' => 'Plate, dish',
                'sentences' => ['___里有菜。', '___很漂亮。', '洗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '筷子',
                'pinyin' => 'kuài zi',
                'simplified' => '筷子',
                'traditional' => '筷子',
                'part_of_speech' => 'noun',
                'meaning' => 'Chopsticks',
                'meaning_zh' => '筷子',
                'example_sentence' => '我会用筷子。',
                'example_translation' => 'I can use chopsticks.',
                'definition' => 'Chopsticks',
                'sentences' => ['我会用___。', '___很长。', '一双___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '刀',
                'pinyin' => 'dāo',
                'simplified' => '刀',
                'traditional' => '刀',
                'part_of_speech' => 'noun',
                'meaning' => 'Knife',
                'meaning_zh' => '刀',
                'example_sentence' => '刀很快。',
                'example_translation' => 'The knife is sharp.',
                'definition' => 'Knife',
                'sentences' => ['___很快。', '用___切。', '一把___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '勺子',
                'pinyin' => 'sháo zi',
                'simplified' => '勺子',
                'traditional' => '勺子',
                'part_of_speech' => 'noun',
                'meaning' => 'Spoon',
                'meaning_zh' => '勺子',
                'example_sentence' => '用勺子喝汤。',
                'example_translation' => 'Use a spoon to eat soup.',
                'definition' => 'Spoon',
                'sentences' => ['用___喝汤。', '___很小。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '瓶子',
                'pinyin' => 'píng zi',
                'simplified' => '瓶子',
                'traditional' => '瓶子',
                'part_of_speech' => 'noun',
                'meaning' => 'Bottle',
                'meaning_zh' => '瓶子',
                'example_sentence' => '一瓶水。',
                'example_translation' => 'A bottle of water.',
                'definition' => 'Bottle',
                'sentences' => ['一___水。', '___是空的。', '___很大。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '包',
                'pinyin' => 'bāo',
                'simplified' => '包',
                'traditional' => '包',
                'part_of_speech' => 'noun',
                'meaning' => 'Bag / Package',
                'meaning_zh' => '包',
                'example_sentence' => '我有一个包。',
                'example_translation' => 'I have a bag.',
                'definition' => 'Bag, package, handbag',
                'sentences' => ['我有一个___。', '___很重。', '书___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '伞',
                'pinyin' => 'sǎn',
                'simplified' => '伞',
                'traditional' => '傘',
                'part_of_speech' => 'noun',
                'meaning' => 'Umbrella',
                'meaning_zh' => '伞',
                'example_sentence' => '带伞吧。',
                'example_translation' => 'Bring an umbrella.',
                'definition' => 'Umbrella',
                'sentences' => ['带___吧。', '___很漂亮。', '雨___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '钟',
                'pinyin' => 'zhōng',
                'simplified' => '钟',
                'traditional' => '鐘',
                'part_of_speech' => 'noun',
                'meaning' => 'Clock',
                'meaning_zh' => '钟',
                'example_sentence' => '墙上有一个钟。',
                'example_translation' => 'There is a clock on the wall.',
                'definition' => 'Clock',
                'sentences' => ['墙上有一个___。', '___很准。', '闹___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '镜子',
                'pinyin' => 'jìng zi',
                'simplified' => '镜子',
                'traditional' => '鏡子',
                'part_of_speech' => 'noun',
                'meaning' => 'Mirror',
                'meaning_zh' => '镜子',
                'example_sentence' => '照镜子。',
                'example_translation' => 'Look in the mirror.',
                'definition' => 'Mirror',
                'sentences' => ['照___。', '___很干净。', '___里。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '毛巾',
                'pinyin' => 'máo jīn',
                'simplified' => '毛巾',
                'traditional' => '毛巾',
                'part_of_speech' => 'noun',
                'meaning' => 'Towel',
                'meaning_zh' => '毛巾',
                'example_sentence' => '用毛巾擦手。',
                'example_translation' => 'Use a towel to dry hands.',
                'definition' => 'Towel',
                'sentences' => ['用___擦手。', '___很湿。', '洗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '肥皂',
                'pinyin' => 'fēi zào',
                'simplified' => '肥皂',
                'traditional' => '肥皂',
                'part_of_speech' => 'noun',
                'meaning' => 'Soap',
                'meaning_zh' => '肥皂',
                'example_sentence' => '用肥皂洗手。',
                'example_translation' => 'Wash hands with soap.',
                'definition' => 'Soap',
                'sentences' => ['用___洗手。', '___很香。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '牙刷',
                'pinyin' => 'yá shuā',
                'simplified' => '牙刷',
                'traditional' => '牙刷',
                'part_of_speech' => 'noun',
                'meaning' => 'Toothbrush',
                'meaning_zh' => '牙刷',
                'example_sentence' => '我的牙刷是蓝色的。',
                'example_translation' => 'My toothbrush is blue.',
                'definition' => 'Toothbrush',
                'sentences' => ['我的___是蓝色的。', '___很新。', '买___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '牙膏',
                'pinyin' => 'yá gāo',
                'simplified' => '牙膏',
                'traditional' => '牙膏',
                'part_of_speech' => 'noun',
                'meaning' => 'Toothpaste',
                'meaning_zh' => '牙膏',
                'example_sentence' => '牙膏用完了。',
                'example_translation' => 'The toothpaste is used up.',
                'definition' => 'Toothpaste',
                'sentences' => ['___用完了。', '___很好。', '一管___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 18,
                'word' => '梳子',
                'pinyin' => 'shū zi',
                'simplified' => '梳子',
                'traditional' => '梳子',
                'part_of_speech' => 'noun',
                'meaning' => 'Comb',
                'meaning_zh' => '梳子',
                'example_sentence' => '用梳子梳头。',
                'example_translation' => 'Use a comb to comb hair.',
                'definition' => 'Comb',
                'sentences' => ['用___梳头。', '___很漂亮。', '一把___。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 19: Food and Ingredients (食物和配料) - 30 words
        $foodIngredientsVocab = [
            [
                'topic_id' => 19,
                'word' => '饭',
                'pinyin' => 'fàn',
                'simplified' => '饭',
                'traditional' => '飯',
                'part_of_speech' => 'noun',
                'meaning' => 'Rice / Meal',
                'meaning_zh' => '饭',
                'example_sentence' => '我吃饭。',
                'example_translation' => 'I eat (a meal).',
                'definition' => 'Cooked rice, meal',
                'sentences' => ['我吃___。', '___很好吃。', '煮___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '面',
                'pinyin' => 'miàn',
                'simplified' => '面',
                'traditional' => '麵',
                'part_of_speech' => 'noun',
                'meaning' => 'Noodles',
                'meaning_zh' => '面',
                'example_sentence' => '我喜欢吃面。',
                'example_translation' => 'I like to eat noodles.',
                'definition' => 'Noodles',
                'sentences' => ['我喜欢吃___。', '___条。', '一碗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '包子',
                'pinyin' => 'bāo zi',
                'simplified' => '包子',
                'traditional' => '包子',
                'part_of_speech' => 'noun',
                'meaning' => 'Steamed bun',
                'meaning_zh' => '包子',
                'example_sentence' => '早上吃包子。',
                'example_translation' => 'Eat steamed buns in the morning.',
                'definition' => 'Steamed bun with filling',
                'sentences' => ['早上吃___。', '___很好吃。', '肉___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '饺子',
                'pinyin' => 'jiǎo zi',
                'simplified' => '饺子',
                'traditional' => '餃子',
                'part_of_speech' => 'noun',
                'meaning' => 'Dumpling',
                'meaning_zh' => '饺子',
                'example_sentence' => '我喜欢吃饺子。',
                'example_translation' => 'I like to eat dumplings.',
                'definition' => 'Dumpling',
                'sentences' => ['我喜欢吃___。', '___很好吃。', '包___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '面包',
                'pinyin' => 'miàn bāo',
                'simplified' => '面包',
                'traditional' => '麵包',
                'part_of_speech' => 'noun',
                'meaning' => 'Bread',
                'meaning_zh' => '面包',
                'example_sentence' => '早餐吃面包。',
                'example_translation' => 'Eat bread for breakfast.',
                'definition' => 'Bread',
                'sentences' => ['早餐吃___。', '___很新鲜。', '一片___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '鸡蛋',
                'pinyin' => 'jī dàn',
                'simplified' => '鸡蛋',
                'traditional' => '雞蛋',
                'part_of_speech' => 'noun',
                'meaning' => 'Egg / Chicken egg',
                'meaning_zh' => '鸡蛋',
                'example_sentence' => '我吃了两个鸡蛋。',
                'example_translation' => 'I ate two eggs.',
                'definition' => 'Chicken egg',
                'sentences' => ['我吃了两个___。', '___很新鲜。', '煮___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '肉',
                'pinyin' => 'ròu',
                'simplified' => '肉',
                'traditional' => '肉',
                'part_of_speech' => 'noun',
                'meaning' => 'Meat',
                'meaning_zh' => '肉',
                'example_sentence' => '我不吃肉。',
                'example_translation' => 'I don\'t eat meat.',
                'definition' => 'Meat',
                'sentences' => ['我不吃___。', '___很嫩。', '猪___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '菜',
                'pinyin' => 'cài',
                'simplified' => '菜',
                'traditional' => '菜',
                'part_of_speech' => 'noun',
                'meaning' => 'Dish / Vegetable',
                'meaning_zh' => '菜',
                'example_sentence' => '这个菜很好吃。',
                'example_translation' => 'This dish is delicious.',
                'definition' => 'Dish, vegetable, cuisine',
                'sentences' => ['这个___很好吃。', '___很新鲜。', '买___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '米',
                'pinyin' => 'mǐ',
                'simplified' => '米',
                'traditional' => '米',
                'part_of_speech' => 'noun',
                'meaning' => 'Rice (uncooked)',
                'meaning_zh' => '米',
                'example_sentence' => '买米。',
                'example_translation' => 'Buy rice.',
                'definition' => 'Uncooked rice',
                'sentences' => ['买___。', '___很白。', '一斤___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '油',
                'pinyin' => 'yóu',
                'simplified' => '油',
                'traditional' => '油',
                'part_of_speech' => 'noun',
                'meaning' => 'Oil',
                'meaning_zh' => '油',
                'example_sentence' => '炒菜用油。',
                'example_translation' => 'Use oil to stir-fry vegetables.',
                'definition' => 'Oil',
                'sentences' => ['炒菜用___。', '___很多。', '一瓶___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '盐',
                'pinyin' => 'yán',
                'simplified' => '盐',
                'traditional' => '鹽',
                'part_of_speech' => 'noun',
                'meaning' => 'Salt',
                'meaning_zh' => '盐',
                'example_sentence' => '加点盐。',
                'example_translation' => 'Add some salt.',
                'definition' => 'Salt',
                'sentences' => ['加点___。', '___很咸。', '一包___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '糖',
                'pinyin' => 'táng',
                'simplified' => '糖',
                'traditional' => '糖',
                'part_of_speech' => 'noun',
                'meaning' => 'Sugar / Candy',
                'meaning_zh' => '糖',
                'example_sentence' => '我喜欢吃糖。',
                'example_translation' => 'I like to eat candy.',
                'definition' => 'Sugar, candy',
                'sentences' => ['我喜欢吃___。', '___很甜。', '加___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '醋',
                'pinyin' => 'cù',
                'simplified' => '醋',
                'traditional' => '醋',
                'part_of_speech' => 'noun',
                'meaning' => 'Vinegar',
                'meaning_zh' => '醋',
                'example_sentence' => '加点醋。',
                'example_translation' => 'Add some vinegar.',
                'definition' => 'Vinegar',
                'sentences' => ['加点___。', '___很酸。', '一瓶___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '酱油',
                'pinyin' => 'jiàng yóu',
                'simplified' => '酱油',
                'traditional' => '醬油',
                'part_of_speech' => 'noun',
                'meaning' => 'Soy sauce',
                'meaning_zh' => '酱油',
                'example_sentence' => '加酱油。',
                'example_translation' => 'Add soy sauce.',
                'definition' => 'Soy sauce',
                'sentences' => ['加___。', '___很咸。', '一瓶___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '辣椒',
                'pinyin' => 'là jiāo',
                'simplified' => '辣椒',
                'traditional' => '辣椒',
                'part_of_speech' => 'noun',
                'meaning' => 'Chili pepper / Hot pepper',
                'meaning_zh' => '辣椒',
                'example_sentence' => '我不吃辣椒。',
                'example_translation' => 'I don\'t eat chili peppers.',
                'definition' => 'Chili pepper, hot pepper',
                'sentences' => ['我不吃___。', '___很辣。', '加___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '葱',
                'pinyin' => 'cōng',
                'simplified' => '葱',
                'traditional' => '蔥',
                'part_of_speech' => 'noun',
                'meaning' => 'Green onion / Scallion',
                'meaning_zh' => '葱',
                'example_sentence' => '加点葱。',
                'example_translation' => 'Add some green onions.',
                'definition' => 'Green onion, scallion',
                'sentences' => ['加点___。', '___很香。', '切___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '姜',
                'pinyin' => 'jiāng',
                'simplified' => '姜',
                'traditional' => '薑',
                'part_of_speech' => 'noun',
                'meaning' => 'Ginger',
                'meaning_zh' => '姜',
                'example_sentence' => '加点姜。',
                'example_translation' => 'Add some ginger.',
                'definition' => 'Ginger',
                'sentences' => ['加点___。', '___很辣。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '蒜',
                'pinyin' => 'suàn',
                'simplified' => '蒜',
                'traditional' => '蒜',
                'part_of_speech' => 'noun',
                'meaning' => 'Garlic',
                'meaning_zh' => '蒜',
                'example_sentence' => '加点蒜。',
                'example_translation' => 'Add some garlic.',
                'definition' => 'Garlic',
                'sentences' => ['加点___。', '___很香。', '一头___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '豆腐',
                'pinyin' => 'dòu fu',
                'simplified' => '豆腐',
                'traditional' => '豆腐',
                'part_of_speech' => 'noun',
                'meaning' => 'Tofu / Bean curd',
                'meaning_zh' => '豆腐',
                'example_sentence' => '我喜欢吃豆腐。',
                'example_translation' => 'I like to eat tofu.',
                'definition' => 'Tofu, bean curd',
                'sentences' => ['我喜欢吃___。', '___很嫩。', '一块___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '土豆',
                'pinyin' => 'tǔ dòu',
                'simplified' => '土豆',
                'traditional' => '土豆',
                'part_of_speech' => 'noun',
                'meaning' => 'Potato',
                'meaning_zh' => '土豆',
                'example_sentence' => '我喜欢吃土豆。',
                'example_translation' => 'I like to eat potatoes.',
                'definition' => 'Potato',
                'sentences' => ['我喜欢吃___。', '___很好吃。', '炒___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '西红柿',
                'pinyin' => 'xī hóng shì',
                'simplified' => '西红柿',
                'traditional' => '西紅柿',
                'part_of_speech' => 'noun',
                'meaning' => 'Tomato',
                'meaning_zh' => '西红柿',
                'example_sentence' => '西红柿炒鸡蛋。',
                'example_translation' => 'Scrambled eggs with tomatoes.',
                'definition' => 'Tomato',
                'sentences' => ['___炒鸡蛋。', '___很红。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '黄瓜',
                'pinyin' => 'huáng guā',
                'simplified' => '黄瓜',
                'traditional' => '黃瓜',
                'part_of_speech' => 'noun',
                'meaning' => 'Cucumber',
                'meaning_zh' => '黄瓜',
                'example_sentence' => '凉拌黄瓜。',
                'example_translation' => 'Cold cucumber salad.',
                'definition' => 'Cucumber',
                'sentences' => ['凉拌___。', '___很脆。', '一根___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '白菜',
                'pinyin' => 'bái cài',
                'simplified' => '白菜',
                'traditional' => '白菜',
                'part_of_speech' => 'noun',
                'meaning' => 'Chinese cabbage',
                'meaning_zh' => '白菜',
                'example_sentence' => '买白菜。',
                'example_translation' => 'Buy Chinese cabbage.',
                'definition' => 'Chinese cabbage, napa cabbage',
                'sentences' => ['买___。', '___很新鲜。', '炒___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '茄子',
                'pinyin' => 'qié zi',
                'simplified' => '茄子',
                'traditional' => '茄子',
                'part_of_speech' => 'noun',
                'meaning' => 'Eggplant',
                'meaning_zh' => '茄子',
                'example_sentence' => '我喜欢吃茄子。',
                'example_translation' => 'I like to eat eggplant.',
                'definition' => 'Eggplant',
                'sentences' => ['我喜欢吃___。', '___很好吃。', '一个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '萝卜',
                'pinyin' => 'luó bo',
                'simplified' => '萝卜',
                'traditional' => '蘿蔔',
                'part_of_speech' => 'noun',
                'meaning' => 'Radish / Carrot',
                'meaning_zh' => '萝卜',
                'example_sentence' => '买萝卜。',
                'example_translation' => 'Buy radish.',
                'definition' => 'Radish, carrot',
                'sentences' => ['买___。', '___很甜。', '一根___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '青菜',
                'pinyin' => 'qīng cài',
                'simplified' => '青菜',
                'traditional' => '青菜',
                'part_of_speech' => 'noun',
                'meaning' => 'Green vegetables',
                'meaning_zh' => '青菜',
                'example_sentence' => '吃青菜很健康。',
                'example_translation' => 'Eating green vegetables is healthy.',
                'definition' => 'Green vegetables, leafy greens',
                'sentences' => ['吃___很健康。', '___很新鲜。', '炒___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '蘑菇',
                'pinyin' => 'mó gu',
                'simplified' => '蘑菇',
                'traditional' => '蘑菇',
                'part_of_speech' => 'noun',
                'meaning' => 'Mushroom',
                'meaning_zh' => '蘑菇',
                'example_sentence' => '我喜欢吃蘑菇。',
                'example_translation' => 'I like to eat mushrooms.',
                'definition' => 'Mushroom',
                'sentences' => ['我喜欢吃___。', '___很鲜。', '炒___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '玉米',
                'pinyin' => 'yù mǐ',
                'simplified' => '玉米',
                'traditional' => '玉米',
                'part_of_speech' => 'noun',
                'meaning' => 'Corn / Maize',
                'meaning_zh' => '玉米',
                'example_sentence' => '我喜欢吃玉米。',
                'example_translation' => 'I like to eat corn.',
                'definition' => 'Corn, maize',
                'sentences' => ['我喜欢吃___。', '___很甜。', '一根___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '豆子',
                'pinyin' => 'dòu zi',
                'simplified' => '豆子',
                'traditional' => '豆子',
                'part_of_speech' => 'noun',
                'meaning' => 'Beans',
                'meaning_zh' => '豆子',
                'example_sentence' => '煮豆子。',
                'example_translation' => 'Cook beans.',
                'definition' => 'Beans',
                'sentences' => ['煮___。', '___很好吃。', '红___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 19,
                'word' => '花生',
                'pinyin' => 'huā shēng',
                'simplified' => '花生',
                'traditional' => '花生',
                'part_of_speech' => 'noun',
                'meaning' => 'Peanut',
                'meaning_zh' => '花生',
                'example_sentence' => '我喜欢吃花生。',
                'example_translation' => 'I like to eat peanuts.',
                'definition' => 'Peanut',
                'sentences' => ['我喜欢吃___。', '___很香。', '炸___。'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($basicVerbsVocab, $householdItemsVocab, $foodIngredientsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
