<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk1Topics10to12Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 10: The Head and Face (11 words)
        $headFaceVocab = [
            [
                'topic_id' => 10,
                'word' => '头',
                'pinyin' => 'tóu',
                'simplified' => '头',
                'traditional' => '頭',
                'part_of_speech' => 'noun',
                'meaning' => 'Head',
                'meaning_zh' => '头',
                'example_sentence' => '我的头很痛。',
                'example_translation' => 'My head hurts.',
                'definition' => 'Head',
                'sentences' => ['我的___很痛。', '___发。', '点___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '脸',
                'pinyin' => 'liǎn',
                'simplified' => '脸',
                'traditional' => '臉',
                'part_of_speech' => 'noun',
                'meaning' => 'Face',
                'meaning_zh' => '脸',
                'example_sentence' => '她的脸很漂亮。',
                'example_translation' => 'Her face is very beautiful.',
                'definition' => 'Face',
                'sentences' => ['她的___很漂亮。', '洗___。', '___红了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '眼睛',
                'pinyin' => 'yǎn jing',
                'simplified' => '眼睛',
                'traditional' => '眼睛',
                'part_of_speech' => 'noun',
                'meaning' => 'Eyes',
                'meaning_zh' => '眼睛',
                'example_sentence' => '她的眼睛很大。',
                'example_translation' => 'Her eyes are very big.',
                'definition' => 'Eyes',
                'sentences' => ['她的___很大。', '闭上___。', '___很累。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '耳朵',
                'pinyin' => 'ěr duo',
                'simplified' => '耳朵',
                'traditional' => '耳朵',
                'part_of_speech' => 'noun',
                'meaning' => 'Ears',
                'meaning_zh' => '耳朵',
                'example_sentence' => '我的耳朵听不清。',
                'example_translation' => "My ears can't hear clearly.",
                'definition' => 'Ears',
                'sentences' => ['我的___听不清。', '___很大。', '用___听。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '鼻子',
                'pinyin' => 'bí zi',
                'simplified' => '鼻子',
                'traditional' => '鼻子',
                'part_of_speech' => 'noun',
                'meaning' => 'Nose',
                'meaning_zh' => '鼻子',
                'example_sentence' => '我的鼻子不舒服。',
                'example_translation' => 'My nose is uncomfortable.',
                'definition' => 'Nose',
                'sentences' => ['我的___不舒服。', '___很高。', '用___闻。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '嘴',
                'pinyin' => 'zuǐ',
                'simplified' => '嘴',
                'traditional' => '嘴',
                'part_of_speech' => 'noun',
                'meaning' => 'Mouth',
                'meaning_zh' => '嘴',
                'example_sentence' => '张开嘴。',
                'example_translation' => 'Open your mouth.',
                'definition' => 'Mouth',
                'sentences' => ['张开___。', '___巴。', '闭___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '牙齿',
                'pinyin' => 'yá chǐ',
                'simplified' => '牙齿',
                'traditional' => '牙齒',
                'part_of_speech' => 'noun',
                'meaning' => 'Teeth',
                'meaning_zh' => '牙齿',
                'example_sentence' => '刷牙齿。',
                'example_translation' => 'Brush teeth.',
                'definition' => 'Teeth',
                'sentences' => ['刷___。', '___很白。', '___痛。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '舌头',
                'pinyin' => 'shé tou',
                'simplified' => '舌头',
                'traditional' => '舌頭',
                'part_of_speech' => 'noun',
                'meaning' => 'Tongue',
                'meaning_zh' => '舌头',
                'example_sentence' => '伸出舌头。',
                'example_translation' => 'Stick out your tongue.',
                'definition' => 'Tongue',
                'sentences' => ['伸出___。', '___很红。', '___头。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '头发',
                'pinyin' => 'tóu fa',
                'simplified' => '头发',
                'traditional' => '頭髮',
                'part_of_speech' => 'noun',
                'meaning' => 'Hair',
                'meaning_zh' => '头发',
                'example_sentence' => '她的头发很长。',
                'example_translation' => 'Her hair is very long.',
                'definition' => 'Hair',
                'sentences' => ['她的___很长。', '剪___。', '___很黑。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '脖子',
                'pinyin' => 'bó zi',
                'simplified' => '脖子',
                'traditional' => '脖子',
                'part_of_speech' => 'noun',
                'meaning' => 'Neck',
                'meaning_zh' => '脖子',
                'example_sentence' => '我的脖子很酸。',
                'example_translation' => 'My neck is very sore.',
                'definition' => 'Neck',
                'sentences' => ['我的___很酸。', '___很长。', '转___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 10,
                'word' => '脸色',
                'pinyin' => 'liǎn sè',
                'simplified' => '脸色',
                'traditional' => '臉色',
                'part_of_speech' => 'noun',
                'meaning' => 'Complexion / Facial expression',
                'meaning_zh' => '脸色',
                'example_sentence' => '你的脸色不好。',
                'example_translation' => 'Your complexion is not good.',
                'definition' => 'Complexion, facial color',
                'sentences' => ['你的___不好。', '___很差。', '___苍白。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 11: Opposite Adjectives (34 words)
        $oppositeAdjVocab = [
            [
                'topic_id' => 11,
                'word' => '大',
                'pinyin' => 'dà',
                'simplified' => '大',
                'traditional' => '大',
                'part_of_speech' => 'adjective',
                'meaning' => 'Big / Large',
                'meaning_zh' => '大',
                'example_sentence' => '这个房子很大。',
                'example_translation' => 'This house is very big.',
                'definition' => 'Big, large, great',
                'sentences' => ['这个房子很___。', '___学生。', '___小。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '小',
                'pinyin' => 'xiǎo',
                'simplified' => '小',
                'traditional' => '小',
                'part_of_speech' => 'adjective',
                'meaning' => 'Small / Little',
                'meaning_zh' => '小',
                'example_sentence' => '这个苹果很小。',
                'example_translation' => 'This apple is very small.',
                'definition' => 'Small, little, young',
                'sentences' => ['这个苹果很___。', '___孩。', '___狗。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '高',
                'pinyin' => 'gāo',
                'simplified' => '高',
                'traditional' => '高',
                'part_of_speech' => 'adjective',
                'meaning' => 'Tall / High',
                'meaning_zh' => '高',
                'example_sentence' => '他很高。',
                'example_translation' => 'He is very tall.',
                'definition' => 'Tall, high',
                'sentences' => ['他很___。', '___兴。', '山很___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '矮',
                'pinyin' => 'ǎi',
                'simplified' => '矮',
                'traditional' => '矮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Short (height)',
                'meaning_zh' => '矮',
                'example_sentence' => '我弟弟很矮。',
                'example_translation' => 'My younger brother is very short.',
                'definition' => 'Short in height, low',
                'sentences' => ['我弟弟很___。', '___个子。', '___树。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '长',
                'pinyin' => 'cháng',
                'simplified' => '长',
                'traditional' => '長',
                'part_of_speech' => 'adjective',
                'meaning' => 'Long',
                'meaning_zh' => '长',
                'example_sentence' => '她的头发很长。',
                'example_translation' => 'Her hair is very long.',
                'definition' => 'Long',
                'sentences' => ['她的头发很___。', '___时间。', '___江。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '短',
                'pinyin' => 'duǎn',
                'simplified' => '短',
                'traditional' => '短',
                'part_of_speech' => 'adjective',
                'meaning' => 'Short (length)',
                'meaning_zh' => '短',
                'example_sentence' => '这条裤子很短。',
                'example_translation' => 'These pants are very short.',
                'definition' => 'Short in length',
                'sentences' => ['这条裤子很___。', '___时间。', '___发。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '胖',
                'pinyin' => 'pàng',
                'simplified' => '胖',
                'traditional' => '胖',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fat / Plump',
                'meaning_zh' => '胖',
                'example_sentence' => '他有点胖。',
                'example_translation' => 'He is a bit fat.',
                'definition' => 'Fat, plump',
                'sentences' => ['他有点___。', '___子。', '变___了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '瘦',
                'pinyin' => 'shòu',
                'simplified' => '瘦',
                'traditional' => '瘦',
                'part_of_speech' => 'adjective',
                'meaning' => 'Thin / Skinny',
                'meaning_zh' => '瘦',
                'example_sentence' => '她很瘦。',
                'example_translation' => 'She is very thin.',
                'definition' => 'Thin, skinny, lean',
                'sentences' => ['她很___。', '___肉。', '太___了。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '多',
                'pinyin' => 'duō',
                'simplified' => '多',
                'traditional' => '多',
                'part_of_speech' => 'adjective',
                'meaning' => 'Many / Much / More',
                'meaning_zh' => '多',
                'example_sentence' => '人很多。',
                'example_translation' => 'There are many people.',
                'definition' => 'Many, much, more',
                'sentences' => ['人很___。', '___少钱？', '很___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '少',
                'pinyin' => 'shǎo',
                'simplified' => '少',
                'traditional' => '少',
                'part_of_speech' => 'adjective',
                'meaning' => 'Few / Little / Less',
                'meaning_zh' => '少',
                'example_sentence' => '时间很少。',
                'example_translation' => 'There is very little time.',
                'definition' => 'Few, little, less',
                'sentences' => ['时间很___。', '多___？', '___一点。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '新',
                'pinyin' => 'xīn',
                'simplified' => '新',
                'traditional' => '新',
                'part_of_speech' => 'adjective',
                'meaning' => 'New',
                'meaning_zh' => '新',
                'example_sentence' => '这是新书。',
                'example_translation' => 'This is a new book.',
                'definition' => 'New, fresh',
                'sentences' => ['这是___书。', '___年。', '___鲜。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '旧',
                'pinyin' => 'jiù',
                'simplified' => '旧',
                'traditional' => '舊',
                'part_of_speech' => 'adjective',
                'meaning' => 'Old / Used',
                'meaning_zh' => '旧',
                'example_sentence' => '这是旧书。',
                'example_translation' => 'This is an old book.',
                'definition' => 'Old, used, former',
                'sentences' => ['这是___书。', '___衣服。', '___房子。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '冷',
                'pinyin' => 'lěng',
                'simplified' => '冷',
                'traditional' => '冷',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cold',
                'meaning_zh' => '冷',
                'example_sentence' => '今天很冷。',
                'example_translation' => 'Today is very cold.',
                'definition' => 'Cold',
                'sentences' => ['今天很___。', '___水。', '___静。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '热',
                'pinyin' => 'rè',
                'simplified' => '热',
                'traditional' => '熱',
                'part_of_speech' => 'adjective',
                'meaning' => 'Hot',
                'meaning_zh' => '热',
                'example_sentence' => '夏天很热。',
                'example_translation' => 'Summer is very hot.',
                'definition' => 'Hot, heat',
                'sentences' => ['夏天很___。', '___水。', '___情。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '快',
                'pinyin' => 'kuài',
                'simplified' => '快',
                'traditional' => '快',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fast / Quick',
                'meaning_zh' => '快',
                'example_sentence' => '他跑得很快。',
                'example_translation' => 'He runs very fast.',
                'definition' => 'Fast, quick, soon',
                'sentences' => ['他跑得很___。', '___点。', '___乐。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '慢',
                'pinyin' => 'màn',
                'simplified' => '慢',
                'traditional' => '慢',
                'part_of_speech' => 'adjective',
                'meaning' => 'Slow',
                'meaning_zh' => '慢',
                'example_sentence' => '他走得很慢。',
                'example_translation' => 'He walks very slowly.',
                'definition' => 'Slow',
                'sentences' => ['他走得很___。', '___一点。', '___慢来。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '好',
                'pinyin' => 'hǎo',
                'simplified' => '好',
                'traditional' => '好',
                'part_of_speech' => 'adjective',
                'meaning' => 'Good / Well',
                'meaning_zh' => '好',
                'example_sentence' => '天气很好。',
                'example_translation' => 'The weather is very good.',
                'definition' => 'Good, well, fine',
                'sentences' => ['天气很___。', '___人。', '___吃。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '坏',
                'pinyin' => 'huài',
                'simplified' => '坏',
                'traditional' => '壞',
                'part_of_speech' => 'adjective',
                'meaning' => 'Bad / Broken',
                'meaning_zh' => '坏',
                'example_sentence' => '手机坏了。',
                'example_translation' => 'The phone is broken.',
                'definition' => 'Bad, broken, spoiled',
                'sentences' => ['手机___了。', '___人。', '___天气。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '贵',
                'pinyin' => 'guì',
                'simplified' => '贵',
                'traditional' => '貴',
                'part_of_speech' => 'adjective',
                'meaning' => 'Expensive',
                'meaning_zh' => '贵',
                'example_sentence' => '这个太贵了。',
                'example_translation' => 'This is too expensive.',
                'definition' => 'Expensive, valuable, honored',
                'sentences' => ['这个太___了。', '很___。', '___姓？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '便宜',
                'pinyin' => 'pián yi',
                'simplified' => '便宜',
                'traditional' => '便宜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cheap / Inexpensive',
                'meaning_zh' => '便宜',
                'example_sentence' => '这个很便宜。',
                'example_translation' => 'This is very cheap.',
                'definition' => 'Cheap, inexpensive',
                'sentences' => ['这个很___。', '___货。', '价格___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '漂亮',
                'pinyin' => 'piào liang',
                'simplified' => '漂亮',
                'traditional' => '漂亮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Beautiful / Pretty',
                'meaning_zh' => '漂亮',
                'example_sentence' => '她很漂亮。',
                'example_translation' => 'She is very beautiful.',
                'definition' => 'Beautiful, pretty, handsome',
                'sentences' => ['她很___。', '___的花。', '真___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '难看',
                'pinyin' => 'nán kàn',
                'simplified' => '难看',
                'traditional' => '難看',
                'part_of_speech' => 'adjective',
                'meaning' => 'Ugly',
                'meaning_zh' => '难看',
                'example_sentence' => '这件衣服很难看。',
                'example_translation' => 'This clothing is very ugly.',
                'definition' => 'Ugly, unsightly',
                'sentences' => ['这件衣服很___。', '太___了。', '___的颜色。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '干净',
                'pinyin' => 'gān jìng',
                'simplified' => '干净',
                'traditional' => '乾淨',
                'part_of_speech' => 'adjective',
                'meaning' => 'Clean',
                'meaning_zh' => '干净',
                'example_sentence' => '房间很干净。',
                'example_translation' => 'The room is very clean.',
                'definition' => 'Clean, neat',
                'sentences' => ['房间很___。', '___的衣服。', '保持___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '脏',
                'pinyin' => 'zāng',
                'simplified' => '脏',
                'traditional' => '髒',
                'part_of_speech' => 'adjective',
                'meaning' => 'Dirty',
                'meaning_zh' => '脏',
                'example_sentence' => '衣服很脏。',
                'example_translation' => 'The clothes are very dirty.',
                'definition' => 'Dirty, filthy',
                'sentences' => ['衣服很___。', '太___了。', '___水。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '忙',
                'pinyin' => 'máng',
                'simplified' => '忙',
                'traditional' => '忙',
                'part_of_speech' => 'adjective',
                'meaning' => 'Busy',
                'meaning_zh' => '忙',
                'example_sentence' => '我很忙。',
                'example_translation' => 'I am very busy.',
                'definition' => 'Busy, hurried',
                'sentences' => ['我很___。', '___碌。', '工作很___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '闲',
                'pinyin' => 'xián',
                'simplified' => '闲',
                'traditional' => '閒',
                'part_of_speech' => 'adjective',
                'meaning' => 'Free / Idle',
                'meaning_zh' => '闲',
                'example_sentence' => '我今天很闲。',
                'example_translation' => 'I am very free today.',
                'definition' => 'Free, idle, leisure',
                'sentences' => ['我今天很___。', '___着。', '___聊。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '对',
                'pinyin' => 'duì',
                'simplified' => '对',
                'traditional' => '對',
                'part_of_speech' => 'adjective',
                'meaning' => 'Correct / Right',
                'meaning_zh' => '对',
                'example_sentence' => '你说得对。',
                'example_translation' => 'You are right.',
                'definition' => 'Correct, right',
                'sentences' => ['你说得___。', '___不起。', '___的。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '错',
                'pinyin' => 'cuò',
                'simplified' => '错',
                'traditional' => '錯',
                'part_of_speech' => 'adjective',
                'meaning' => 'Wrong / Incorrect',
                'meaning_zh' => '错',
                'example_sentence' => '你错了。',
                'example_translation' => 'You are wrong.',
                'definition' => 'Wrong, incorrect, mistake',
                'sentences' => ['你___了。', '___误。', '不___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '难',
                'pinyin' => 'nán',
                'simplified' => '难',
                'traditional' => '難',
                'part_of_speech' => 'adjective',
                'meaning' => 'Difficult / Hard',
                'meaning_zh' => '难',
                'example_sentence' => '这个问题很难。',
                'example_translation' => 'This question is very difficult.',
                'definition' => 'Difficult, hard',
                'sentences' => ['这个问题很___。', '___过。', '___受。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '容易',
                'pinyin' => 'róng yì',
                'simplified' => '容易',
                'traditional' => '容易',
                'part_of_speech' => 'adjective',
                'meaning' => 'Easy',
                'meaning_zh' => '容易',
                'example_sentence' => '这个很容易。',
                'example_translation' => 'This is very easy.',
                'definition' => 'Easy, simple',
                'sentences' => ['这个很___。', '___学。', '不___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '远',
                'pinyin' => 'yuǎn',
                'simplified' => '远',
                'traditional' => '遠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Far / Distant',
                'meaning_zh' => '远',
                'example_sentence' => '学校很远。',
                'example_translation' => 'The school is very far.',
                'definition' => 'Far, distant, remote',
                'sentences' => ['学校很___。', '___方。', '永___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '近',
                'pinyin' => 'jìn',
                'simplified' => '近',
                'traditional' => '近',
                'part_of_speech' => 'adjective',
                'meaning' => 'Near / Close',
                'meaning_zh' => '近',
                'example_sentence' => '商店很近。',
                'example_translation' => 'The store is very near.',
                'definition' => 'Near, close, recent',
                'sentences' => ['商店很___。', '___视。', '___况。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '早',
                'pinyin' => 'zǎo',
                'simplified' => '早',
                'traditional' => '早',
                'part_of_speech' => 'adjective',
                'meaning' => 'Early',
                'meaning_zh' => '早',
                'example_sentence' => '你来得很早。',
                'example_translation' => 'You came very early.',
                'definition' => 'Early',
                'sentences' => ['你来得很___。', '___上。', '___安。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 11,
                'word' => '晚',
                'pinyin' => 'wǎn',
                'simplified' => '晚',
                'traditional' => '晚',
                'part_of_speech' => 'adjective',
                'meaning' => 'Late',
                'meaning_zh' => '晚',
                'example_sentence' => '太晚了。',
                'example_translation' => 'It\'s too late.',
                'definition' => 'Late, evening',
                'sentences' => ['太___了。', '___上。', '___安。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 12: House and Apartment (23 words)
        $houseVocab = [
            [
                'topic_id' => 12,
                'word' => '房子',
                'pinyin' => 'fáng zi',
                'simplified' => '房子',
                'traditional' => '房子',
                'part_of_speech' => 'noun',
                'meaning' => 'House',
                'meaning_zh' => '房子',
                'example_sentence' => '这个房子很大。',
                'example_translation' => 'This house is very big.',
                'definition' => 'House, building',
                'sentences' => ['这个___很大。', '买___。', '___间。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '房间',
                'pinyin' => 'fáng jiān',
                'simplified' => '房间',
                'traditional' => '房間',
                'part_of_speech' => 'noun',
                'meaning' => 'Room',
                'meaning_zh' => '房间',
                'example_sentence' => '房间很干净。',
                'example_translation' => 'The room is very clean.',
                'definition' => 'Room',
                'sentences' => ['___很干净。', '进___。', '三个___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '卧室',
                'pinyin' => 'wò shì',
                'simplified' => '卧室',
                'traditional' => '臥室',
                'part_of_speech' => 'noun',
                'meaning' => 'Bedroom',
                'meaning_zh' => '卧室',
                'example_sentence' => '我在卧室休息。',
                'example_translation' => 'I rest in the bedroom.',
                'definition' => 'Bedroom',
                'sentences' => ['我在___休息。', '___很大。', '主___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '客厅',
                'pinyin' => 'kè tīng',
                'simplified' => '客厅',
                'traditional' => '客廳',
                'part_of_speech' => 'noun',
                'meaning' => 'Living room',
                'meaning_zh' => '客厅',
                'example_sentence' => '我们在客厅看电视。',
                'example_translation' => 'We watch TV in the living room.',
                'definition' => 'Living room',
                'sentences' => ['我们在___看电视。', '___很大。', '___里。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '厨房',
                'pinyin' => 'chú fáng',
                'simplified' => '厨房',
                'traditional' => '廚房',
                'part_of_speech' => 'noun',
                'meaning' => 'Kitchen',
                'meaning_zh' => '厨房',
                'example_sentence' => '妈妈在厨房做饭。',
                'example_translation' => 'Mom is cooking in the kitchen.',
                'definition' => 'Kitchen',
                'sentences' => ['妈妈在___做饭。', '___很小。', '___用品。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '卫生间',
                'pinyin' => 'wèi shēng jiān',
                'simplified' => '卫生间',
                'traditional' => '衛生間',
                'part_of_speech' => 'noun',
                'meaning' => 'Bathroom / Toilet',
                'meaning_zh' => '卫生间',
                'example_sentence' => '卫生间在哪里？',
                'example_translation' => 'Where is the bathroom?',
                'definition' => 'Bathroom, toilet, restroom',
                'sentences' => ['___在哪里？', '上___。', '___很干净。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '阳台',
                'pinyin' => 'yáng tái',
                'simplified' => '阳台',
                'traditional' => '陽台',
                'part_of_speech' => 'noun',
                'meaning' => 'Balcony',
                'meaning_zh' => '阳台',
                'example_sentence' => '我在阳台上晒衣服。',
                'example_translation' => 'I dry clothes on the balcony.',
                'definition' => 'Balcony, terrace',
                'sentences' => ['我在___上晒衣服。', '___很大。', '___上。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '门',
                'pinyin' => 'mén',
                'simplified' => '门',
                'traditional' => '門',
                'part_of_speech' => 'noun',
                'meaning' => 'Door / Gate',
                'meaning_zh' => '门',
                'example_sentence' => '请开门。',
                'example_translation' => 'Please open the door.',
                'definition' => 'Door, gate, entrance',
                'sentences' => ['请开___。', '关___。', '___口。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '窗户',
                'pinyin' => 'chuāng hu',
                'simplified' => '窗户',
                'traditional' => '窗戶',
                'part_of_speech' => 'noun',
                'meaning' => 'Window',
                'meaning_zh' => '窗户',
                'example_sentence' => '打开窗户。',
                'example_translation' => 'Open the window.',
                'definition' => 'Window',
                'sentences' => ['打开___。', '关___。', '___外。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '墙',
                'pinyin' => 'qiáng',
                'simplified' => '墙',
                'traditional' => '牆',
                'part_of_speech' => 'noun',
                'meaning' => 'Wall',
                'meaning_zh' => '墙',
                'example_sentence' => '墙上有一幅画。',
                'example_translation' => 'There is a painting on the wall.',
                'definition' => 'Wall',
                'sentences' => ['___上有一幅画。', '白___。', '___壁。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '地板',
                'pinyin' => 'dì bǎn',
                'simplified' => '地板',
                'traditional' => '地板',
                'part_of_speech' => 'noun',
                'meaning' => 'Floor',
                'meaning_zh' => '地板',
                'example_sentence' => '地板很干净。',
                'example_translation' => 'The floor is very clean.',
                'definition' => 'Floor, flooring',
                'sentences' => ['___很干净。', '木___。', '擦___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '天花板',
                'pinyin' => 'tiān huā bǎn',
                'simplified' => '天花板',
                'traditional' => '天花板',
                'part_of_speech' => 'noun',
                'meaning' => 'Ceiling',
                'meaning_zh' => '天花板',
                'example_sentence' => '天花板很高。',
                'example_translation' => 'The ceiling is very high.',
                'definition' => 'Ceiling',
                'sentences' => ['___很高。', '___上。', '白色的___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '楼',
                'pinyin' => 'lóu',
                'simplified' => '楼',
                'traditional' => '樓',
                'part_of_speech' => 'noun',
                'meaning' => 'Building / Floor',
                'meaning_zh' => '楼',
                'example_sentence' => '我住在三楼。',
                'example_translation' => 'I live on the third floor.',
                'definition' => 'Building, floor, storey',
                'sentences' => ['我住在三___。', '上___。', '下___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '楼梯',
                'pinyin' => 'lóu tī',
                'simplified' => '楼梯',
                'traditional' => '樓梯',
                'part_of_speech' => 'noun',
                'meaning' => 'Stairs / Staircase',
                'meaning_zh' => '楼梯',
                'example_sentence' => '走楼梯上去。',
                'example_translation' => 'Go up the stairs.',
                'definition' => 'Stairs, staircase',
                'sentences' => ['走___上去。', '爬___。', '___口。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '电梯',
                'pinyin' => 'diàn tī',
                'simplified' => '电梯',
                'traditional' => '電梯',
                'part_of_speech' => 'noun',
                'meaning' => 'Elevator / Lift',
                'meaning_zh' => '电梯',
                'example_sentence' => '坐电梯上去。',
                'example_translation' => 'Take the elevator up.',
                'definition' => 'Elevator, lift',
                'sentences' => ['坐___上去。', '___坏了。', '等___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '院子',
                'pinyin' => 'yuàn zi',
                'simplified' => '院子',
                'traditional' => '院子',
                'part_of_speech' => 'noun',
                'meaning' => 'Yard / Courtyard',
                'meaning_zh' => '院子',
                'example_sentence' => '院子里有花。',
                'example_translation' => 'There are flowers in the yard.',
                'definition' => 'Yard, courtyard',
                'sentences' => ['___里有花。', '在___里玩。', '___很大。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '花园',
                'pinyin' => 'huā yuán',
                'simplified' => '花园',
                'traditional' => '花園',
                'part_of_speech' => 'noun',
                'meaning' => 'Garden',
                'meaning_zh' => '花园',
                'example_sentence' => '花园里有很多花。',
                'example_translation' => 'There are many flowers in the garden.',
                'definition' => 'Garden',
                'sentences' => ['___里有很多花。', '后___。', '___洋房。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '车库',
                'pinyin' => 'chē kù',
                'simplified' => '车库',
                'traditional' => '車庫',
                'part_of_speech' => 'noun',
                'meaning' => 'Garage',
                'meaning_zh' => '车库',
                'example_sentence' => '车停在车库里。',
                'example_translation' => 'The car is parked in the garage.',
                'definition' => 'Garage',
                'sentences' => ['车停在___里。', '___门。', '地下___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '屋顶',
                'pinyin' => 'wū dǐng',
                'simplified' => '屋顶',
                'traditional' => '屋頂',
                'part_of_speech' => 'noun',
                'meaning' => 'Roof',
                'meaning_zh' => '屋顶',
                'example_sentence' => '屋顶是红色的。',
                'example_translation' => 'The roof is red.',
                'definition' => 'Roof, housetop',
                'sentences' => ['___是红色的。', '上___。', '___漏水。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '地下室',
                'pinyin' => 'dì xià shì',
                'simplified' => '地下室',
                'traditional' => '地下室',
                'part_of_speech' => 'noun',
                'meaning' => 'Basement',
                'meaning_zh' => '地下室',
                'example_sentence' => '地下室很凉快。',
                'example_translation' => 'The basement is very cool.',
                'definition' => 'Basement, cellar',
                'sentences' => ['___很凉快。', '___停车。', '在___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '走廊',
                'pinyin' => 'zǒu láng',
                'simplified' => '走廊',
                'traditional' => '走廊',
                'part_of_speech' => 'noun',
                'meaning' => 'Corridor / Hallway',
                'meaning_zh' => '走廊',
                'example_sentence' => '走廊很长。',
                'example_translation' => 'The corridor is very long.',
                'definition' => 'Corridor, hallway, passage',
                'sentences' => ['___很长。', '在___里。', '___尽头。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '钥匙',
                'pinyin' => 'yào shi',
                'simplified' => '钥匙',
                'traditional' => '鑰匙',
                'part_of_speech' => 'noun',
                'meaning' => 'Key',
                'meaning_zh' => '钥匙',
                'example_sentence' => '我忘带钥匙了。',
                'example_translation' => 'I forgot to bring the key.',
                'definition' => 'Key (for lock)',
                'sentences' => ['我忘带___了。', '___在哪里？', '开___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 12,
                'word' => '租',
                'pinyin' => 'zū',
                'simplified' => '租',
                'traditional' => '租',
                'part_of_speech' => 'verb',
                'meaning' => 'To rent / To lease',
                'meaning_zh' => '租',
                'example_sentence' => '我租了一个房子。',
                'example_translation' => 'I rented a house.',
                'definition' => 'To rent, to lease, to hire',
                'sentences' => ['我___了一个房子。', '___金。', '出___。'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($headFaceVocab, $oppositeAdjVocab, $houseVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
