<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk1Topics13to16Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 13: Furniture and Home Appliances (9 words)
        $furnitureVocab = [
            [
                'topic_id' => 13,
                'word' => '桌子',
                'pinyin' => 'zhuō zi',
                'simplified' => '桌子',
                'traditional' => '桌子',
                'part_of_speech' => 'noun',
                'meaning' => 'Table / Desk',
                'meaning_zh' => '桌子',
                'example_sentence' => '桌子上有书。',
                'example_translation' => 'There are books on the table.',
                'definition' => 'Table, desk',
                'sentences' => ['___上有书。', '饭___。', '___子很大。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '椅子',
                'pinyin' => 'yǐ zi',
                'simplified' => '椅子',
                'traditional' => '椅子',
                'part_of_speech' => 'noun',
                'meaning' => 'Chair',
                'meaning_zh' => '椅子',
                'example_sentence' => '请坐这个椅子。',
                'example_translation' => 'Please sit on this chair.',
                'definition' => 'Chair',
                'sentences' => ['请坐这个___。', '___子很舒服。', '办公___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '床',
                'pinyin' => 'chuáng',
                'simplified' => '床',
                'traditional' => '床',
                'part_of_speech' => 'noun',
                'meaning' => 'Bed',
                'meaning_zh' => '床',
                'example_sentence' => '我在床上睡觉。',
                'example_translation' => 'I sleep on the bed.',
                'definition' => 'Bed',
                'sentences' => ['我在___上睡觉。', '___很软。', '起___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '沙发',
                'pinyin' => 'shā fā',
                'simplified' => '沙发',
                'traditional' => '沙發',
                'part_of_speech' => 'noun',
                'meaning' => 'Sofa / Couch',
                'meaning_zh' => '沙发',
                'example_sentence' => '我坐在沙发上看电视。',
                'example_translation' => 'I sit on the sofa watching TV.',
                'definition' => 'Sofa, couch',
                'sentences' => ['我坐在___上看电视。', '___很舒服。', '买___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '灯',
                'pinyin' => 'dēng',
                'simplified' => '灯',
                'traditional' => '燈',
                'part_of_speech' => 'noun',
                'meaning' => 'Light / Lamp',
                'meaning_zh' => '灯',
                'example_sentence' => '请开灯。',
                'example_translation' => 'Please turn on the light.',
                'definition' => 'Light, lamp',
                'sentences' => ['请开___。', '关___。', '___光。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '电视',
                'pinyin' => 'diàn shì',
                'simplified' => '电视',
                'traditional' => '電視',
                'part_of_speech' => 'noun',
                'meaning' => 'Television / TV',
                'meaning_zh' => '电视',
                'example_sentence' => '我在看电视。',
                'example_translation' => 'I am watching TV.',
                'definition' => 'Television, TV',
                'sentences' => ['我在看___。', '___机。', '___节目。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '电脑',
                'pinyin' => 'diàn nǎo',
                'simplified' => '电脑',
                'traditional' => '電腦',
                'part_of_speech' => 'noun',
                'meaning' => 'Computer',
                'meaning_zh' => '电脑',
                'example_sentence' => '我用电脑工作。',
                'example_translation' => 'I use the computer to work.',
                'definition' => 'Computer',
                'sentences' => ['我用___工作。', '___很慢。', '笔记本___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '空调',
                'pinyin' => 'kōng tiáo',
                'simplified' => '空调',
                'traditional' => '空調',
                'part_of_speech' => 'noun',
                'meaning' => 'Air conditioner',
                'meaning_zh' => '空调',
                'example_sentence' => '开空调吧，很热。',
                'example_translation' => "Let's turn on the air conditioner, it's very hot.",
                'definition' => 'Air conditioner, air conditioning',
                'sentences' => ['开___吧，很热。', '___坏了。', '___很凉快。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 13,
                'word' => '冰箱',
                'pinyin' => 'bīng xiāng',
                'simplified' => '冰箱',
                'traditional' => '冰箱',
                'part_of_speech' => 'noun',
                'meaning' => 'Refrigerator / Fridge',
                'meaning_zh' => '冰箱',
                'example_sentence' => '牛奶在冰箱里。',
                'example_translation' => 'The milk is in the fridge.',
                'definition' => 'Refrigerator, fridge',
                'sentences' => ['牛奶在___里。', '打开___。', '___里有什么？'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 14: Jobs (14 words)
        $jobsVocab = [
            [
                'topic_id' => 14,
                'word' => '医生',
                'pinyin' => 'yī shēng',
                'simplified' => '医生',
                'traditional' => '醫生',
                'part_of_speech' => 'noun',
                'meaning' => 'Doctor',
                'meaning_zh' => '医生',
                'example_sentence' => '她是医生。',
                'example_translation' => 'She is a doctor.',
                'definition' => 'Doctor, physician',
                'sentences' => ['她是___。', '看___。', '___说。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '护士',
                'pinyin' => 'hù shi',
                'simplified' => '护士',
                'traditional' => '護士',
                'part_of_speech' => 'noun',
                'meaning' => 'Nurse',
                'meaning_zh' => '护士',
                'example_sentence' => '那个护士很好。',
                'example_translation' => 'That nurse is very nice.',
                'definition' => 'Nurse',
                'sentences' => ['那个___很好。', '___站。', '___长。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '司机',
                'pinyin' => 'sī jī',
                'simplified' => '司机',
                'traditional' => '司機',
                'part_of_speech' => 'noun',
                'meaning' => 'Driver',
                'meaning_zh' => '司机',
                'example_sentence' => '他是出租车司机。',
                'example_translation' => 'He is a taxi driver.',
                'definition' => 'Driver, chauffeur',
                'sentences' => ['他是出租车___。', '___师傅。', '___很累。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '服务员',
                'pinyin' => 'fú wù yuán',
                'simplified' => '服务员',
                'traditional' => '服務員',
                'part_of_speech' => 'noun',
                'meaning' => 'Waiter / Waitress',
                'meaning_zh' => '服务员',
                'example_sentence' => '服务员，买单。',
                'example_translation' => 'Waiter, check please.',
                'definition' => 'Waiter, waitress, attendant',
                'sentences' => ['___，买单。', '___很热情。', '叫___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '厨师',
                'pinyin' => 'chú shī',
                'simplified' => '厨师',
                'traditional' => '廚師',
                'part_of_speech' => 'noun',
                'meaning' => 'Chef / Cook',
                'meaning_zh' => '厨师',
                'example_sentence' => '这个厨师很厉害。',
                'example_translation' => 'This chef is very skilled.',
                'definition' => 'Chef, cook',
                'sentences' => ['这个___很厉害。', '___做的菜。', '中国___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '警察',
                'pinyin' => 'jǐng chá',
                'simplified' => '警察',
                'traditional' => '警察',
                'part_of_speech' => 'noun',
                'meaning' => 'Police / Policeman',
                'meaning_zh' => '警察',
                'example_sentence' => '那是警察。',
                'example_translation' => 'That is a policeman.',
                'definition' => 'Police, policeman',
                'sentences' => ['那是___。', '___叔叔。', '报___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '律师',
                'pinyin' => 'lǜ shī',
                'simplified' => '律师',
                'traditional' => '律師',
                'part_of_speech' => 'noun',
                'meaning' => 'Lawyer',
                'meaning_zh' => '律师',
                'example_sentence' => '他是律师。',
                'example_translation' => 'He is a lawyer.',
                'definition' => 'Lawyer, attorney',
                'sentences' => ['他是___。', '___事务所。', '找___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '工人',
                'pinyin' => 'gōng rén',
                'simplified' => '工人',
                'traditional' => '工人',
                'part_of_speech' => 'noun',
                'meaning' => 'Worker',
                'meaning_zh' => '工人',
                'example_sentence' => '他们是工人。',
                'example_translation' => 'They are workers.',
                'definition' => 'Worker, laborer',
                'sentences' => ['他们是___。', '建筑___。', '___很辛苦。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '农民',
                'pinyin' => 'nóng mín',
                'simplified' => '农民',
                'traditional' => '農民',
                'part_of_speech' => 'noun',
                'meaning' => 'Farmer / Peasant',
                'meaning_zh' => '农民',
                'example_sentence' => '他是农民。',
                'example_translation' => 'He is a farmer.',
                'definition' => 'Farmer, peasant',
                'sentences' => ['他是___。', '___种地。', '___伯伯。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '经理',
                'pinyin' => 'jīng lǐ',
                'simplified' => '经理',
                'traditional' => '經理',
                'part_of_speech' => 'noun',
                'meaning' => 'Manager',
                'meaning_zh' => '经理',
                'example_sentence' => '他是经理。',
                'example_translation' => 'He is a manager.',
                'definition' => 'Manager, director',
                'sentences' => ['他是___。', '总___。', '___办公室。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '职员',
                'pinyin' => 'zhí yuán',
                'simplified' => '职员',
                'traditional' => '職員',
                'part_of_speech' => 'noun',
                'meaning' => 'Office worker / Staff',
                'meaning_zh' => '职员',
                'example_sentence' => '我是公司职员。',
                'example_translation' => 'I am a company employee.',
                'definition' => 'Office worker, staff member',
                'sentences' => ['我是公司___。', '___工作。', '办公室___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '记者',
                'pinyin' => 'jì zhě',
                'simplified' => '记者',
                'traditional' => '記者',
                'part_of_speech' => 'noun',
                'meaning' => 'Journalist / Reporter',
                'meaning_zh' => '记者',
                'example_sentence' => '她是记者。',
                'example_translation' => 'She is a journalist.',
                'definition' => 'Journalist, reporter',
                'sentences' => ['她是___。', '___采访。', '新闻___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '演员',
                'pinyin' => 'yǎn yuán',
                'simplified' => '演员',
                'traditional' => '演員',
                'part_of_speech' => 'noun',
                'meaning' => 'Actor / Actress',
                'meaning_zh' => '演员',
                'example_sentence' => '他是著名演员。',
                'example_translation' => 'He is a famous actor.',
                'definition' => 'Actor, actress, performer',
                'sentences' => ['他是著名___。', '___表演。', '电影___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 14,
                'word' => '歌手',
                'pinyin' => 'gē shǒu',
                'simplified' => '歌手',
                'traditional' => '歌手',
                'part_of_speech' => 'noun',
                'meaning' => 'Singer',
                'meaning_zh' => '歌手',
                'example_sentence' => '她是歌手。',
                'example_translation' => 'She is a singer.',
                'definition' => 'Singer',
                'sentences' => ['她是___。', '___唱歌。', '著名___。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 15: Clothes and Shoes (20 words)
        $clothesVocab = [
            [
                'topic_id' => 15,
                'word' => '衣服',
                'pinyin' => 'yī fu',
                'simplified' => '衣服',
                'traditional' => '衣服',
                'part_of_speech' => 'noun',
                'meaning' => 'Clothes / Clothing',
                'meaning_zh' => '衣服',
                'example_sentence' => '这件衣服很漂亮。',
                'example_translation' => 'This clothing is very beautiful.',
                'definition' => 'Clothes, clothing',
                'sentences' => ['这件___很漂亮。', '穿___。', '洗___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '裤子',
                'pinyin' => 'kù zi',
                'simplified' => '裤子',
                'traditional' => '褲子',
                'part_of_speech' => 'noun',
                'meaning' => 'Pants / Trousers',
                'meaning_zh' => '裤子',
                'example_sentence' => '我买了一条裤子。',
                'example_translation' => 'I bought a pair of pants.',
                'definition' => 'Pants, trousers',
                'sentences' => ['我买了一条___。', '___很长。', '牛仔___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '裙子',
                'pinyin' => 'qún zi',
                'simplified' => '裙子',
                'traditional' => '裙子',
                'part_of_speech' => 'noun',
                'meaning' => 'Skirt / Dress',
                'meaning_zh' => '裙子',
                'example_sentence' => '她穿着漂亮的裙子。',
                'example_translation' => 'She is wearing a beautiful skirt.',
                'definition' => 'Skirt, dress',
                'sentences' => ['她穿着漂亮的___。', '___很短。', '连衣___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '衬衫',
                'pinyin' => 'chèn shān',
                'simplified' => '衬衫',
                'traditional' => '襯衫',
                'part_of_speech' => 'noun',
                'meaning' => 'Shirt',
                'meaning_zh' => '衬衫',
                'example_sentence' => '我穿白衬衫。',
                'example_translation' => 'I wear a white shirt.',
                'definition' => 'Shirt, blouse',
                'sentences' => ['我穿白___。', '___很正式。', '长袖___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => 'T恤',
                'pinyin' => 'T xù',
                'simplified' => 'T恤',
                'traditional' => 'T恤',
                'part_of_speech' => 'noun',
                'meaning' => 'T-shirt',
                'meaning_zh' => 'T恤',
                'example_sentence' => '夏天穿T恤。',
                'example_translation' => 'Wear T-shirts in summer.',
                'definition' => 'T-shirt',
                'sentences' => ['夏天穿___。', '___很舒服。', '短袖___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '外套',
                'pinyin' => 'wài tào',
                'simplified' => '外套',
                'traditional' => '外套',
                'part_of_speech' => 'noun',
                'meaning' => 'Coat / Jacket',
                'meaning_zh' => '外套',
                'example_sentence' => '天冷了，穿外套吧。',
                'example_translation' => "It's cold, wear a jacket.",
                'definition' => 'Coat, jacket, outerwear',
                'sentences' => ['天冷了，穿___吧。', '___很厚。', '脱___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '毛衣',
                'pinyin' => 'máo yī',
                'simplified' => '毛衣',
                'traditional' => '毛衣',
                'part_of_speech' => 'noun',
                'meaning' => 'Sweater',
                'meaning_zh' => '毛衣',
                'example_sentence' => '冬天穿毛衣。',
                'example_translation' => 'Wear sweaters in winter.',
                'definition' => 'Sweater, woolen sweater',
                'sentences' => ['冬天穿___。', '___很暖和。', '织___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '鞋',
                'pinyin' => 'xié',
                'simplified' => '鞋',
                'traditional' => '鞋',
                'part_of_speech' => 'noun',
                'meaning' => 'Shoes',
                'meaning_zh' => '鞋',
                'example_sentence' => '这双鞋很舒服。',
                'example_translation' => 'These shoes are very comfortable.',
                'definition' => 'Shoes',
                'sentences' => ['这双___很舒服。', '___子。', '穿___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '袜子',
                'pinyin' => 'wà zi',
                'simplified' => '袜子',
                'traditional' => '襪子',
                'part_of_speech' => 'noun',
                'meaning' => 'Socks',
                'meaning_zh' => '袜子',
                'example_sentence' => '我买了一双袜子。',
                'example_translation' => 'I bought a pair of socks.',
                'definition' => 'Socks',
                'sentences' => ['我买了一双___。', '___很暖和。', '长___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '帽子',
                'pinyin' => 'mào zi',
                'simplified' => '帽子',
                'traditional' => '帽子',
                'part_of_speech' => 'noun',
                'meaning' => 'Hat / Cap',
                'meaning_zh' => '帽子',
                'example_sentence' => '他戴着帽子。',
                'example_translation' => 'He is wearing a hat.',
                'definition' => 'Hat, cap',
                'sentences' => ['他戴着___。', '___很酷。', '戴___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '围巾',
                'pinyin' => 'wéi jīn',
                'simplified' => '围巾',
                'traditional' => '圍巾',
                'part_of_speech' => 'noun',
                'meaning' => 'Scarf',
                'meaning_zh' => '围巾',
                'example_sentence' => '冬天戴围巾。',
                'example_translation' => 'Wear a scarf in winter.',
                'definition' => 'Scarf',
                'sentences' => ['冬天戴___。', '___很长。', '红色___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '眼镜',
                'pinyin' => 'yǎn jìng',
                'simplified' => '眼镜',
                'traditional' => '眼鏡',
                'part_of_speech' => 'noun',
                'meaning' => 'Glasses / Eyeglasses',
                'meaning_zh' => '眼镜',
                'example_sentence' => '我戴眼镜。',
                'example_translation' => 'I wear glasses.',
                'definition' => 'Glasses, eyeglasses',
                'sentences' => ['我戴___。', '___坏了。', '太阳___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '手套',
                'pinyin' => 'shǒu tào',
                'simplified' => '手套',
                'traditional' => '手套',
                'part_of_speech' => 'noun',
                'meaning' => 'Gloves',
                'meaning_zh' => '手套',
                'example_sentence' => '冬天戴手套。',
                'example_translation' => 'Wear gloves in winter.',
                'definition' => 'Gloves',
                'sentences' => ['冬天戴___。', '___很暖和。', '一副___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '穿',
                'pinyin' => 'chuān',
                'simplified' => '穿',
                'traditional' => '穿',
                'part_of_speech' => 'verb',
                'meaning' => 'To wear / To put on',
                'meaning_zh' => '穿',
                'example_sentence' => '我穿红色衣服。',
                'example_translation' => 'I wear red clothes.',
                'definition' => 'To wear, to put on (clothes)',
                'sentences' => ['我___红色衣服。', '___鞋。', '___什么？'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '戴',
                'pinyin' => 'dài',
                'simplified' => '戴',
                'traditional' => '戴',
                'part_of_speech' => 'verb',
                'meaning' => 'To wear / To put on (accessories)',
                'meaning_zh' => '戴',
                'example_sentence' => '我戴帽子。',
                'example_translation' => 'I wear a hat.',
                'definition' => 'To wear, to put on (accessories)',
                'sentences' => ['我___帽子。', '___眼镜。', '___手套。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '脱',
                'pinyin' => 'tuō',
                'simplified' => '脱',
                'traditional' => '脫',
                'part_of_speech' => 'verb',
                'meaning' => 'To take off / To remove',
                'meaning_zh' => '脱',
                'example_sentence' => '进门请脱鞋。',
                'example_translation' => 'Please take off your shoes when entering.',
                'definition' => 'To take off, to remove (clothes)',
                'sentences' => ['进门请___鞋。', '___衣服。', '___帽子。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '换',
                'pinyin' => 'huàn',
                'simplified' => '换',
                'traditional' => '換',
                'part_of_speech' => 'verb',
                'meaning' => 'To change / To exchange',
                'meaning_zh' => '换',
                'example_sentence' => '换衣服。',
                'example_translation' => 'Change clothes.',
                'definition' => 'To change, to exchange',
                'sentences' => ['___衣服。', '___鞋。', '___个。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '洗',
                'pinyin' => 'xǐ',
                'simplified' => '洗',
                'traditional' => '洗',
                'part_of_speech' => 'verb',
                'meaning' => 'To wash',
                'meaning_zh' => '洗',
                'example_sentence' => '洗衣服。',
                'example_translation' => 'Wash clothes.',
                'definition' => 'To wash, to clean',
                'sentences' => ['___衣服。', '___手。', '___澡。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '买',
                'pinyin' => 'mǎi',
                'simplified' => '买',
                'traditional' => '買',
                'part_of_speech' => 'verb',
                'meaning' => 'To buy',
                'meaning_zh' => '买',
                'example_sentence' => '我买衣服。',
                'example_translation' => 'I buy clothes.',
                'definition' => 'To buy, to purchase',
                'sentences' => ['我___衣服。', '___东西。', '___票。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 15,
                'word' => '卖',
                'pinyin' => 'mài',
                'simplified' => '卖',
                'traditional' => '賣',
                'part_of_speech' => 'verb',
                'meaning' => 'To sell',
                'meaning_zh' => '卖',
                'example_sentence' => '这里卖衣服。',
                'example_translation' => 'They sell clothes here.',
                'definition' => 'To sell',
                'sentences' => ['这里___衣服。', '___东西。', '___票。'],
                'level' => 'HSK1',
            ],
        ];

        // Topic 16: Animals (15 words)
        $animalsVocab = [
            [
                'topic_id' => 16,
                'word' => '狗',
                'pinyin' => 'gǒu',
                'simplified' => '狗',
                'traditional' => '狗',
                'part_of_speech' => 'noun',
                'meaning' => 'Dog',
                'meaning_zh' => '狗',
                'example_sentence' => '我家有一只狗。',
                'example_translation' => 'I have a dog at home.',
                'definition' => 'Dog',
                'sentences' => ['我家有一只___。', '___叫。', '___很可爱。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '猫',
                'pinyin' => 'māo',
                'simplified' => '猫',
                'traditional' => '貓',
                'part_of_speech' => 'noun',
                'meaning' => 'Cat',
                'meaning_zh' => '猫',
                'example_sentence' => '她养了一只猫。',
                'example_translation' => 'She has a cat.',
                'definition' => 'Cat',
                'sentences' => ['她养了一只___。', '___叫。', '___咪。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '鸟',
                'pinyin' => 'niǎo',
                'simplified' => '鸟',
                'traditional' => '鳥',
                'part_of_speech' => 'noun',
                'meaning' => 'Bird',
                'meaning_zh' => '鸟',
                'example_sentence' => '树上有一只鸟。',
                'example_translation' => 'There is a bird in the tree.',
                'definition' => 'Bird',
                'sentences' => ['树上有一只___。', '___飞。', '小___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '鱼',
                'pinyin' => 'yú',
                'simplified' => '鱼',
                'traditional' => '魚',
                'part_of_speech' => 'noun',
                'meaning' => 'Fish',
                'meaning_zh' => '鱼',
                'example_sentence' => '我喜欢吃鱼。',
                'example_translation' => 'I like to eat fish.',
                'definition' => 'Fish',
                'sentences' => ['我喜欢吃___。', '___游。', '养___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '马',
                'pinyin' => 'mǎ',
                'simplified' => '马',
                'traditional' => '馬',
                'part_of_speech' => 'noun',
                'meaning' => 'Horse',
                'meaning_zh' => '马',
                'example_sentence' => '马跑得很快。',
                'example_translation' => 'Horses run very fast.',
                'definition' => 'Horse',
                'sentences' => ['___跑得很快。', '骑___。', '___车。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '牛',
                'pinyin' => 'niú',
                'simplified' => '牛',
                'traditional' => '牛',
                'part_of_speech' => 'noun',
                'meaning' => 'Cow / Ox',
                'meaning_zh' => '牛',
                'example_sentence' => '牛在吃草。',
                'example_translation' => 'The cow is eating grass.',
                'definition' => 'Cow, ox, cattle',
                'sentences' => ['___在吃草。', '___奶。', '___肉。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '羊',
                'pinyin' => 'yáng',
                'simplified' => '羊',
                'traditional' => '羊',
                'part_of_speech' => 'noun',
                'meaning' => 'Sheep / Goat',
                'meaning_zh' => '羊',
                'example_sentence' => '山上有很多羊。',
                'example_translation' => 'There are many sheep on the mountain.',
                'definition' => 'Sheep, goat',
                'sentences' => ['山上有很多___。', '___毛。', '___肉。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '猪',
                'pinyin' => 'zhū',
                'simplified' => '猪',
                'traditional' => '豬',
                'part_of_speech' => 'noun',
                'meaning' => 'Pig',
                'meaning_zh' => '猪',
                'example_sentence' => '猪很胖。',
                'example_translation' => 'Pigs are very fat.',
                'definition' => 'Pig',
                'sentences' => ['___很胖。', '___肉。', '小___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '鸡',
                'pinyin' => 'jī',
                'simplified' => '鸡',
                'traditional' => '雞',
                'part_of_speech' => 'noun',
                'meaning' => 'Chicken',
                'meaning_zh' => '鸡',
                'example_sentence' => '我喜欢吃鸡肉。',
                'example_translation' => 'I like to eat chicken.',
                'definition' => 'Chicken',
                'sentences' => ['我喜欢吃___肉。', '___蛋。', '小___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '鸭',
                'pinyin' => 'yā',
                'simplified' => '鸭',
                'traditional' => '鴨',
                'part_of_speech' => 'noun',
                'meaning' => 'Duck',
                'meaning_zh' => '鸭',
                'example_sentence' => '鸭子在游泳。',
                'example_translation' => 'The duck is swimming.',
                'definition' => 'Duck',
                'sentences' => ['___子在游泳。', '北京烤___。', '___蛋。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '兔子',
                'pinyin' => 'tù zi',
                'simplified' => '兔子',
                'traditional' => '兔子',
                'part_of_speech' => 'noun',
                'meaning' => 'Rabbit',
                'meaning_zh' => '兔子',
                'example_sentence' => '兔子跑得很快。',
                'example_translation' => 'Rabbits run very fast.',
                'definition' => 'Rabbit',
                'sentences' => ['___跑得很快。', '___很可爱。', '小___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '老虎',
                'pinyin' => 'lǎo hǔ',
                'simplified' => '老虎',
                'traditional' => '老虎',
                'part_of_speech' => 'noun',
                'meaning' => 'Tiger',
                'meaning_zh' => '老虎',
                'example_sentence' => '老虎很凶。',
                'example_translation' => 'Tigers are very fierce.',
                'definition' => 'Tiger',
                'sentences' => ['___很凶。', '___在森林里。', '大___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '熊猫',
                'pinyin' => 'xióng māo',
                'simplified' => '熊猫',
                'traditional' => '熊貓',
                'part_of_speech' => 'noun',
                'meaning' => 'Panda',
                'meaning_zh' => '熊猫',
                'example_sentence' => '熊猫是中国的国宝。',
                'example_translation' => 'The panda is China\'s national treasure.',
                'definition' => 'Panda',
                'sentences' => ['___是中国的国宝。', '___吃竹子。', '大___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '猴子',
                'pinyin' => 'hóu zi',
                'simplified' => '猴子',
                'traditional' => '猴子',
                'part_of_speech' => 'noun',
                'meaning' => 'Monkey',
                'meaning_zh' => '猴子',
                'example_sentence' => '猴子很聪明。',
                'example_translation' => 'Monkeys are very smart.',
                'definition' => 'Monkey',
                'sentences' => ['___很聪明。', '___爬树。', '小___。'],
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 16,
                'word' => '大象',
                'pinyin' => 'dà xiàng',
                'simplified' => '大象',
                'traditional' => '大象',
                'part_of_speech' => 'noun',
                'meaning' => 'Elephant',
                'meaning_zh' => '大象',
                'example_sentence' => '大象很大。',
                'example_translation' => 'Elephants are very big.',
                'definition' => 'Elephant',
                'sentences' => ['___很大。', '___的鼻子很长。', '看___。'],
                'level' => 'HSK1',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($furnitureVocab, $jobsVocab, $clothesVocab, $animalsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
