<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics4to7Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 36: Asking for Directions (问路) - 20 words
        $directionsVocab = [
            [
                'topic_id' => 36,
                'word' => '左',
                'pinyin' => 'zuǒ',
                'simplified' => '左',
                'traditional' => '左',
                'part_of_speech' => 'noun',
                'meaning' => 'Left',
                'meaning_zh' => '左',
                'example_sentence' => '向左转。',
                'example_translation' => 'Turn left.',
                'definition' => 'Left (direction)',
                'sentences' => ['向___转。', '___边。', '___手边。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '右',
                'pinyin' => 'yòu',
                'simplified' => '右',
                'traditional' => '右',
                'part_of_speech' => 'noun',
                'meaning' => 'Right',
                'meaning_zh' => '右',
                'example_sentence' => '向右转。',
                'example_translation' => 'Turn right.',
                'definition' => 'Right (direction)',
                'sentences' => ['向___转。', '___边。', '___手边。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '前',
                'pinyin' => 'qián',
                'simplified' => '前',
                'traditional' => '前',
                'part_of_speech' => 'noun',
                'meaning' => 'Front / Forward',
                'meaning_zh' => '前',
                'example_sentence' => '向前走。',
                'example_translation' => 'Go forward.',
                'definition' => 'Front, forward, ahead',
                'sentences' => ['向___走。', '___面。', '___边。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '后',
                'pinyin' => 'hòu',
                'simplified' => '后',
                'traditional' => '後',
                'part_of_speech' => 'noun',
                'meaning' => 'Back / Behind',
                'meaning_zh' => '后',
                'example_sentence' => '在后面。',
                'example_translation' => 'It\'s in the back.',
                'definition' => 'Back, behind, rear',
                'sentences' => ['在___面。', '___边。', '___门。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '东',
                'pinyin' => 'dōng',
                'simplified' => '东',
                'traditional' => '東',
                'part_of_speech' => 'noun',
                'meaning' => 'East',
                'meaning_zh' => '东',
                'example_sentence' => '向东走。',
                'example_translation' => 'Go east.',
                'definition' => 'East (direction)',
                'sentences' => ['向___走。', '___边。', '___方。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '南',
                'pinyin' => 'nán',
                'simplified' => '南',
                'traditional' => '南',
                'part_of_speech' => 'noun',
                'meaning' => 'South',
                'meaning_zh' => '南',
                'example_sentence' => '向南走。',
                'example_translation' => 'Go south.',
                'definition' => 'South (direction)',
                'sentences' => ['向___走。', '___边。', '___方。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '西',
                'pinyin' => 'xī',
                'simplified' => '西',
                'traditional' => '西',
                'part_of_speech' => 'noun',
                'meaning' => 'West',
                'meaning_zh' => '西',
                'example_sentence' => '向西走。',
                'example_translation' => 'Go west.',
                'definition' => 'West (direction)',
                'sentences' => ['向___走。', '___边。', '___方。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '北',
                'pinyin' => 'běi',
                'simplified' => '北',
                'traditional' => '北',
                'part_of_speech' => 'noun',
                'meaning' => 'North',
                'meaning_zh' => '北',
                'example_sentence' => '向北走。',
                'example_translation' => 'Go north.',
                'definition' => 'North (direction)',
                'sentences' => ['向___走。', '___边。', '___方。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '直',
                'pinyin' => 'zhí',
                'simplified' => '直',
                'traditional' => '直',
                'part_of_speech' => 'adjective',
                'meaning' => 'Straight',
                'meaning_zh' => '直',
                'example_sentence' => '一直走。',
                'example_translation' => 'Go straight.',
                'definition' => 'Straight, direct',
                'sentences' => ['一___走。', '___接。', '___线。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '转',
                'pinyin' => 'zhuǎn',
                'simplified' => '转',
                'traditional' => '轉',
                'part_of_speech' => 'verb',
                'meaning' => 'To turn',
                'meaning_zh' => '转',
                'example_sentence' => '在路口转弯。',
                'example_translation' => 'Turn at the intersection.',
                'definition' => 'To turn, to rotate',
                'sentences' => ['___弯。', '向左___。', '___身。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '怎么走',
                'pinyin' => 'zěn me zǒu',
                'simplified' => '怎么走',
                'traditional' => '怎麼走',
                'part_of_speech' => 'phrase',
                'meaning' => 'How to get there',
                'meaning_zh' => '怎么走',
                'example_sentence' => '去机场怎么走？',
                'example_translation' => 'How do I get to the airport?',
                'definition' => 'How to get there, how to go',
                'sentences' => ['___？', '去那儿___？', '这里___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '远',
                'pinyin' => 'yuǎn',
                'simplified' => '远',
                'traditional' => '遠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Far',
                'meaning_zh' => '远',
                'example_sentence' => '离这里很远。',
                'example_translation' => 'It\'s far from here.',
                'definition' => 'Far, distant',
                'sentences' => ['很___。', '___吗？', '___近。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '近',
                'pinyin' => 'jìn',
                'simplified' => '近',
                'traditional' => '近',
                'part_of_speech' => 'adjective',
                'meaning' => 'Near / Close',
                'meaning_zh' => '近',
                'example_sentence' => '离这里很近。',
                'example_translation' => 'It\'s near here.',
                'definition' => 'Near, close',
                'sentences' => ['很___。', '___吗？', '___路。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '对面',
                'pinyin' => 'duì miàn',
                'simplified' => '对面',
                'traditional' => '對面',
                'part_of_speech' => 'noun',
                'meaning' => 'Opposite side / Across from',
                'meaning_zh' => '对面',
                'example_sentence' => '在银行对面。',
                'example_translation' => 'It\'s across from the bank.',
                'definition' => 'Opposite side, across from',
                'sentences' => ['在___。', '___的商店。', '___是什么？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '旁边',
                'pinyin' => 'páng biān',
                'simplified' => '旁边',
                'traditional' => '旁邊',
                'part_of_speech' => 'noun',
                'meaning' => 'Beside / Next to',
                'meaning_zh' => '旁边',
                'example_sentence' => '在超市旁边。',
                'example_translation' => 'It\'s next to the supermarket.',
                'definition' => 'Beside, next to, side',
                'sentences' => ['在___。', '___的房子。', '___是谁？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '中间',
                'pinyin' => 'zhōng jiān',
                'simplified' => '中间',
                'traditional' => '中間',
                'part_of_speech' => 'noun',
                'meaning' => 'Middle / Center',
                'meaning_zh' => '中间',
                'example_sentence' => '在中间。',
                'example_translation' => 'It\'s in the middle.',
                'definition' => 'Middle, center, between',
                'sentences' => ['在___。', '___的位置。', '___人。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '过',
                'pinyin' => 'guò',
                'simplified' => '过',
                'traditional' => '過',
                'part_of_speech' => 'verb',
                'meaning' => 'To pass / To cross',
                'meaning_zh' => '过',
                'example_sentence' => '过马路。',
                'example_translation' => 'Cross the street.',
                'definition' => 'To pass, to cross, to go through',
                'sentences' => ['___马路。', '___桥。', '___来。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '到',
                'pinyin' => 'dào',
                'simplified' => '到',
                'traditional' => '到',
                'part_of_speech' => 'verb',
                'meaning' => 'To arrive / To reach',
                'meaning_zh' => '到',
                'example_sentence' => '到学校了。',
                'example_translation' => 'I arrived at school.',
                'definition' => 'To arrive, to reach, to get to',
                'sentences' => ['___了。', '___家。', '___哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '离',
                'pinyin' => 'lí',
                'simplified' => '离',
                'traditional' => '離',
                'part_of_speech' => 'preposition',
                'meaning' => 'Away from / From',
                'meaning_zh' => '离',
                'example_sentence' => '离这里很近。',
                'example_translation' => 'It\'s close to here.',
                'definition' => 'Away from, from, to leave',
                'sentences' => ['___这里。', '___开。', '___家近。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 36,
                'word' => '拐',
                'pinyin' => 'guǎi',
                'simplified' => '拐',
                'traditional' => '拐',
                'part_of_speech' => 'verb',
                'meaning' => 'To turn / To make a turn',
                'meaning_zh' => '拐',
                'example_sentence' => '向左拐。',
                'example_translation' => 'Turn left.',
                'definition' => 'To turn, to make a turn',
                'sentences' => ['向左___。', '___弯。', '___角。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 37: Transportation (交通) - 20 words
        $transportationVocab = [
            [
                'topic_id' => 37,
                'word' => '地铁',
                'pinyin' => 'dì tiě',
                'simplified' => '地铁',
                'traditional' => '地鐵',
                'part_of_speech' => 'noun',
                'meaning' => 'Subway / Metro',
                'meaning_zh' => '地铁',
                'example_sentence' => '我坐地铁上班。',
                'example_translation' => 'I take the subway to work.',
                'definition' => 'Subway, metro, underground',
                'sentences' => ['坐___。', '___站。', '___线。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '公交车',
                'pinyin' => 'gōng jiāo chē',
                'simplified' => '公交车',
                'traditional' => '公交車',
                'part_of_speech' => 'noun',
                'meaning' => 'Bus',
                'meaning_zh' => '公交车',
                'example_sentence' => '我坐公交车去学校。',
                'example_translation' => 'I take the bus to school.',
                'definition' => 'Public bus',
                'sentences' => ['坐___。', '___站。', '___票。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '出租车',
                'pinyin' => 'chū zū chē',
                'simplified' => '出租车',
                'traditional' => '出租車',
                'part_of_speech' => 'noun',
                'meaning' => 'Taxi',
                'meaning_zh' => '出租车',
                'example_sentence' => '我打出租车回家。',
                'example_translation' => 'I take a taxi home.',
                'definition' => 'Taxi, cab',
                'sentences' => ['打___。', '坐___。', '___司机。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '火车',
                'pinyin' => 'huǒ chē',
                'simplified' => '火车',
                'traditional' => '火車',
                'part_of_speech' => 'noun',
                'meaning' => 'Train',
                'meaning_zh' => '火车',
                'example_sentence' => '我坐火车去北京。',
                'example_translation' => 'I take the train to Beijing.',
                'definition' => 'Train',
                'sentences' => ['坐___。', '___站。', '___票。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '飞机',
                'pinyin' => 'fēi jī',
                'simplified' => '飞机',
                'traditional' => '飛機',
                'part_of_speech' => 'noun',
                'meaning' => 'Airplane',
                'meaning_zh' => '飞机',
                'example_sentence' => '我坐飞机去上海。',
                'example_translation' => 'I take a plane to Shanghai.',
                'definition' => 'Airplane, aircraft',
                'sentences' => ['坐___。', '___票。', '___场。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '自行车',
                'pinyin' => 'zì xíng chē',
                'simplified' => '自行车',
                'traditional' => '自行車',
                'part_of_speech' => 'noun',
                'meaning' => 'Bicycle',
                'meaning_zh' => '自行车',
                'example_sentence' => '我骑自行车上学。',
                'example_translation' => 'I ride a bicycle to school.',
                'definition' => 'Bicycle, bike',
                'sentences' => ['骑___。', '___很方便。', '买___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '骑',
                'pinyin' => 'qí',
                'simplified' => '骑',
                'traditional' => '騎',
                'part_of_speech' => 'verb',
                'meaning' => 'To ride',
                'meaning_zh' => '骑',
                'example_sentence' => '我骑车上班。',
                'example_translation' => 'I ride to work.',
                'definition' => 'To ride (a bicycle, horse, etc.)',
                'sentences' => ['___车。', '___马。', '___自行车。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '开车',
                'pinyin' => 'kāi chē',
                'simplified' => '开车',
                'traditional' => '開車',
                'part_of_speech' => 'verb',
                'meaning' => 'To drive',
                'meaning_zh' => '开车',
                'example_sentence' => '我爸爸开车上班。',
                'example_translation' => 'My father drives to work.',
                'definition' => 'To drive a car',
                'sentences' => ['___上班。', '会___吗？', '___去。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '票',
                'pinyin' => 'piào',
                'simplified' => '票',
                'traditional' => '票',
                'part_of_speech' => 'noun',
                'meaning' => 'Ticket',
                'meaning_zh' => '票',
                'example_sentence' => '我买了一张票。',
                'example_translation' => 'I bought a ticket.',
                'definition' => 'Ticket',
                'sentences' => ['买___。', '一张___。', '___价。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '站',
                'pinyin' => 'zhàn',
                'simplified' => '站',
                'traditional' => '站',
                'part_of_speech' => 'noun',
                'meaning' => 'Station / Stop',
                'meaning_zh' => '站',
                'example_sentence' => '下一站是什么？',
                'example_translation' => 'What is the next stop?',
                'definition' => 'Station, stop',
                'sentences' => ['下一___。', '___台。', '___点。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '上车',
                'pinyin' => 'shàng chē',
                'simplified' => '上车',
                'traditional' => '上車',
                'part_of_speech' => 'verb',
                'meaning' => 'To get on (vehicle)',
                'meaning_zh' => '上车',
                'example_sentence' => '请上车。',
                'example_translation' => 'Please get on the vehicle.',
                'definition' => 'To get on a vehicle, to board',
                'sentences' => ['请___。', '___了。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '下车',
                'pinyin' => 'xià chē',
                'simplified' => '下车',
                'traditional' => '下車',
                'part_of_speech' => 'verb',
                'meaning' => 'To get off (vehicle)',
                'meaning_zh' => '下车',
                'example_sentence' => '在这里下车。',
                'example_translation' => 'Get off here.',
                'definition' => 'To get off a vehicle, to alight',
                'sentences' => ['在这里___。', '___了。', '___站。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '司机',
                'pinyin' => 'sī jī',
                'simplified' => '司机',
                'traditional' => '司機',
                'part_of_speech' => 'noun',
                'meaning' => 'Driver',
                'meaning_zh' => '司机',
                'example_sentence' => '他是出租车司机。',
                'example_translation' => 'He is a taxi driver.',
                'definition' => 'Driver, chauffeur',
                'sentences' => ['___师傅。', '___很好。', '___开车。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '堵车',
                'pinyin' => 'dǔ chē',
                'simplified' => '堵车',
                'traditional' => '堵車',
                'part_of_speech' => 'verb',
                'meaning' => 'Traffic jam / To be stuck in traffic',
                'meaning_zh' => '堵车',
                'example_sentence' => '路上堵车了。',
                'example_translation' => 'There\'s a traffic jam on the road.',
                'definition' => 'Traffic jam, to be stuck in traffic',
                'sentences' => ['___了。', '路上___。', '___很严重。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '慢',
                'pinyin' => 'màn',
                'simplified' => '慢',
                'traditional' => '慢',
                'part_of_speech' => 'adjective',
                'meaning' => 'Slow',
                'meaning_zh' => '慢',
                'example_sentence' => '车开得很慢。',
                'example_translation' => 'The car is going very slow.',
                'definition' => 'Slow',
                'sentences' => ['很___。', '___点儿。', '___慢走。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '快',
                'pinyin' => 'kuài',
                'simplified' => '快',
                'traditional' => '快',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fast / Quick',
                'meaning_zh' => '快',
                'example_sentence' => '地铁很快。',
                'example_translation' => 'The subway is very fast.',
                'definition' => 'Fast, quick, rapid',
                'sentences' => ['很___。', '___点儿。', '___车。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '换',
                'pinyin' => 'huàn',
                'simplified' => '换',
                'traditional' => '換',
                'part_of_speech' => 'verb',
                'meaning' => 'To change / To transfer',
                'meaning_zh' => '换',
                'example_sentence' => '我需要换车。',
                'example_translation' => 'I need to transfer.',
                'definition' => 'To change, to exchange, to transfer',
                'sentences' => ['___车。', '___线。', '___乘。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '走路',
                'pinyin' => 'zǒu lù',
                'simplified' => '走路',
                'traditional' => '走路',
                'part_of_speech' => 'verb',
                'meaning' => 'To walk',
                'meaning_zh' => '走路',
                'example_sentence' => '我走路去学校。',
                'example_translation' => 'I walk to school.',
                'definition' => 'To walk, to go on foot',
                'sentences' => ['___去。', '___很近。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '等',
                'pinyin' => 'děng',
                'simplified' => '等',
                'traditional' => '等',
                'part_of_speech' => 'verb',
                'meaning' => 'To wait',
                'meaning_zh' => '等',
                'example_sentence' => '我在等公交车。',
                'example_translation' => 'I am waiting for the bus.',
                'definition' => 'To wait, to await',
                'sentences' => ['___车。', '___人。', '___一下。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 37,
                'word' => '停',
                'pinyin' => 'tíng',
                'simplified' => '停',
                'traditional' => '停',
                'part_of_speech' => 'verb',
                'meaning' => 'To stop / To park',
                'meaning_zh' => '停',
                'example_sentence' => '车停在这里。',
                'example_translation' => 'The car is parked here.',
                'definition' => 'To stop, to halt, to park',
                'sentences' => ['___车。', '___下来。', '___了。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 38: Describing Emotions (描述情绪) - 20 words
        $emotionsVocab = [
            [
                'topic_id' => 38,
                'word' => '高兴',
                'pinyin' => 'gāo xìng',
                'simplified' => '高兴',
                'traditional' => '高興',
                'part_of_speech' => 'adjective',
                'meaning' => 'Happy / Glad',
                'meaning_zh' => '高兴',
                'example_sentence' => '我很高兴。',
                'example_translation' => 'I am very happy.',
                'definition' => 'Happy, glad, pleased',
                'sentences' => ['很___。', '___吗？', '___的事。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '快乐',
                'pinyin' => 'kuài lè',
                'simplified' => '快乐',
                'traditional' => '快樂',
                'part_of_speech' => 'adjective',
                'meaning' => 'Happy / Joyful',
                'meaning_zh' => '快乐',
                'example_sentence' => '祝你快乐！',
                'example_translation' => 'Wish you happiness!',
                'definition' => 'Happy, joyful, cheerful',
                'sentences' => ['很___。', '___的生活。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '累',
                'pinyin' => 'lèi',
                'simplified' => '累',
                'traditional' => '累',
                'part_of_speech' => 'adjective',
                'meaning' => 'Tired',
                'meaning_zh' => '累',
                'example_sentence' => '我很累。',
                'example_translation' => 'I am very tired.',
                'definition' => 'Tired, exhausted',
                'sentences' => ['很___。', '___吗？', '___死了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '忙',
                'pinyin' => 'máng',
                'simplified' => '忙',
                'traditional' => '忙',
                'part_of_speech' => 'adjective',
                'meaning' => 'Busy',
                'meaning_zh' => '忙',
                'example_sentence' => '我很忙。',
                'example_translation' => 'I am very busy.',
                'definition' => 'Busy',
                'sentences' => ['很___。', '___吗？', '___工作。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '生气',
                'pinyin' => 'shēng qì',
                'simplified' => '生气',
                'traditional' => '生氣',
                'part_of_speech' => 'adjective',
                'meaning' => 'Angry / Mad',
                'meaning_zh' => '生气',
                'example_sentence' => '他很生气。',
                'example_translation' => 'He is very angry.',
                'definition' => 'Angry, mad, to get angry',
                'sentences' => ['很___。', '___了。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '害怕',
                'pinyin' => 'hài pà',
                'simplified' => '害怕',
                'traditional' => '害怕',
                'part_of_speech' => 'adjective',
                'meaning' => 'Afraid / Scared',
                'meaning_zh' => '害怕',
                'example_sentence' => '我害怕黑暗。',
                'example_translation' => 'I am afraid of the dark.',
                'definition' => 'Afraid, scared, to fear',
                'sentences' => ['很___。', '___吗？', '___什么？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '担心',
                'pinyin' => 'dān xīn',
                'simplified' => '担心',
                'traditional' => '擔心',
                'part_of_speech' => 'verb',
                'meaning' => 'To worry',
                'meaning_zh' => '担心',
                'example_sentence' => '我很担心你。',
                'example_translation' => 'I am very worried about you.',
                'definition' => 'To worry, to be concerned',
                'sentences' => ['很___。', '___你。', '不要___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '难过',
                'pinyin' => 'nán guò',
                'simplified' => '难过',
                'traditional' => '難過',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sad',
                'meaning_zh' => '难过',
                'example_sentence' => '我很难过。',
                'example_translation' => 'I am very sad.',
                'definition' => 'Sad, unhappy, sorry',
                'sentences' => ['很___。', '___吗？', '___的事。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '紧张',
                'pinyin' => 'jǐn zhāng',
                'simplified' => '紧张',
                'traditional' => '緊張',
                'part_of_speech' => 'adjective',
                'meaning' => 'Nervous / Tense',
                'meaning_zh' => '紧张',
                'example_sentence' => '考试前我很紧张。',
                'example_translation' => 'I am very nervous before exams.',
                'definition' => 'Nervous, tense, intense',
                'sentences' => ['很___。', '___吗？', '___的时候。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '兴奋',
                'pinyin' => 'xīng fèn',
                'simplified' => '兴奋',
                'traditional' => '興奮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Excited',
                'meaning_zh' => '兴奋',
                'example_sentence' => '我很兴奋。',
                'example_translation' => 'I am very excited.',
                'definition' => 'Excited, thrilled',
                'sentences' => ['很___。', '___的心情。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '舒服',
                'pinyin' => 'shū fu',
                'simplified' => '舒服',
                'traditional' => '舒服',
                'part_of_speech' => 'adjective',
                'meaning' => 'Comfortable',
                'meaning_zh' => '舒服',
                'example_sentence' => '这个沙发很舒服。',
                'example_translation' => 'This sofa is very comfortable.',
                'definition' => 'Comfortable, at ease',
                'sentences' => ['很___。', '___吗？', '___的床。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '不舒服',
                'pinyin' => 'bù shū fu',
                'simplified' => '不舒服',
                'traditional' => '不舒服',
                'part_of_speech' => 'adjective',
                'meaning' => 'Uncomfortable / Unwell',
                'meaning_zh' => '不舒服',
                'example_sentence' => '我今天不舒服。',
                'example_translation' => 'I am not feeling well today.',
                'definition' => 'Uncomfortable, unwell, sick',
                'sentences' => ['___吗？', '有点___。', '___的感觉。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '满意',
                'pinyin' => 'mǎn yì',
                'simplified' => '满意',
                'traditional' => '滿意',
                'part_of_speech' => 'adjective',
                'meaning' => 'Satisfied',
                'meaning_zh' => '满意',
                'example_sentence' => '我很满意。',
                'example_translation' => 'I am very satisfied.',
                'definition' => 'Satisfied, content',
                'sentences' => ['很___。', '___吗？', '___的结果。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '失望',
                'pinyin' => 'shī wàng',
                'simplified' => '失望',
                'traditional' => '失望',
                'part_of_speech' => 'adjective',
                'meaning' => 'Disappointed',
                'meaning_zh' => '失望',
                'example_sentence' => '我很失望。',
                'example_translation' => 'I am very disappointed.',
                'definition' => 'Disappointed, to lose hope',
                'sentences' => ['很___。', '___吗？', '___的感觉。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '感兴趣',
                'pinyin' => 'gǎn xìng qù',
                'simplified' => '感兴趣',
                'traditional' => '感興趣',
                'part_of_speech' => 'verb',
                'meaning' => 'To be interested in',
                'meaning_zh' => '感兴趣',
                'example_sentence' => '我对音乐感兴趣。',
                'example_translation' => 'I am interested in music.',
                'definition' => 'To be interested in',
                'sentences' => ['___吗？', '对___。', '很___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '无聊',
                'pinyin' => 'wú liáo',
                'simplified' => '无聊',
                'traditional' => '無聊',
                'part_of_speech' => 'adjective',
                'meaning' => 'Boring / Bored',
                'meaning_zh' => '无聊',
                'example_sentence' => '这个电影很无聊。',
                'example_translation' => 'This movie is very boring.',
                'definition' => 'Boring, bored, dull',
                'sentences' => ['很___。', '___吗？', '___的事。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '有意思',
                'pinyin' => 'yǒu yì si',
                'simplified' => '有意思',
                'traditional' => '有意思',
                'part_of_speech' => 'adjective',
                'meaning' => 'Interesting',
                'meaning_zh' => '有意思',
                'example_sentence' => '这本书很有意思。',
                'example_translation' => 'This book is very interesting.',
                'definition' => 'Interesting, meaningful',
                'sentences' => ['很___。', '___吗？', '___的故事。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '放心',
                'pinyin' => 'fàng xīn',
                'simplified' => '放心',
                'traditional' => '放心',
                'part_of_speech' => 'verb',
                'meaning' => 'To rest assured / To set one\'s mind at ease',
                'meaning_zh' => '放心',
                'example_sentence' => '你放心吧。',
                'example_translation' => 'Don\'t worry.',
                'definition' => 'To rest assured, to be at ease',
                'sentences' => ['___吧。', '___了。', '___不下。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '着急',
                'pinyin' => 'zháo jí',
                'simplified' => '着急',
                'traditional' => '著急',
                'part_of_speech' => 'adjective',
                'meaning' => 'Anxious / Worried',
                'meaning_zh' => '着急',
                'example_sentence' => '别着急。',
                'example_translation' => 'Don\'t be anxious.',
                'definition' => 'Anxious, worried, in a hurry',
                'sentences' => ['很___。', '别___。', '___什么？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 38,
                'word' => '笑',
                'pinyin' => 'xiào',
                'simplified' => '笑',
                'traditional' => '笑',
                'part_of_speech' => 'verb',
                'meaning' => 'To laugh / To smile',
                'meaning_zh' => '笑',
                'example_sentence' => '他笑了。',
                'example_translation' => 'He laughed.',
                'definition' => 'To laugh, to smile',
                'sentences' => ['___了。', '___话。', '___容。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 39: Describing Appearance (描述外貌) - 20 words
        $appearanceVocab = [
            [
                'topic_id' => 39,
                'word' => '高',
                'pinyin' => 'gāo',
                'simplified' => '高',
                'traditional' => '高',
                'part_of_speech' => 'adjective',
                'meaning' => 'Tall / High',
                'meaning_zh' => '高',
                'example_sentence' => '他很高。',
                'example_translation' => 'He is very tall.',
                'definition' => 'Tall, high',
                'sentences' => ['很___。', '___个子。', '___大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '矮',
                'pinyin' => 'ǎi',
                'simplified' => '矮',
                'traditional' => '矮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Short (height)',
                'meaning_zh' => '矮',
                'example_sentence' => '他很矮。',
                'example_translation' => 'He is very short.',
                'definition' => 'Short (in height), low',
                'sentences' => ['很___。', '___个子。', '___小。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '胖',
                'pinyin' => 'pàng',
                'simplified' => '胖',
                'traditional' => '胖',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fat / Plump',
                'meaning_zh' => '胖',
                'example_sentence' => '他有点胖。',
                'example_translation' => 'He is a bit fat.',
                'definition' => 'Fat, plump, chubby',
                'sentences' => ['有点___。', '很___。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '瘦',
                'pinyin' => 'shòu',
                'simplified' => '瘦',
                'traditional' => '瘦',
                'part_of_speech' => 'adjective',
                'meaning' => 'Thin / Slim',
                'meaning_zh' => '瘦',
                'example_sentence' => '她很瘦。',
                'example_translation' => 'She is very thin.',
                'definition' => 'Thin, slim, lean',
                'sentences' => ['很___。', '___了。', '___身。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '漂亮',
                'pinyin' => 'piào liang',
                'simplified' => '漂亮',
                'traditional' => '漂亮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Beautiful / Pretty',
                'meaning_zh' => '漂亮',
                'example_sentence' => '她很漂亮。',
                'example_translation' => 'She is very beautiful.',
                'definition' => 'Beautiful, pretty, handsome',
                'sentences' => ['很___。', '___的女孩。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '帅',
                'pinyin' => 'shuài',
                'simplified' => '帅',
                'traditional' => '帥',
                'part_of_speech' => 'adjective',
                'meaning' => 'Handsome',
                'meaning_zh' => '帅',
                'example_sentence' => '他很帅。',
                'example_translation' => 'He is very handsome.',
                'definition' => 'Handsome, smart',
                'sentences' => ['很___。', '___哥。', '___气。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '丑',
                'pinyin' => 'chǒu',
                'simplified' => '丑',
                'traditional' => '醜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Ugly',
                'meaning_zh' => '丑',
                'example_sentence' => '这个很丑。',
                'example_translation' => 'This is very ugly.',
                'definition' => 'Ugly',
                'sentences' => ['很___。', '___吗？', '___陋。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '年轻',
                'pinyin' => 'nián qīng',
                'simplified' => '年轻',
                'traditional' => '年輕',
                'part_of_speech' => 'adjective',
                'meaning' => 'Young',
                'meaning_zh' => '年轻',
                'example_sentence' => '她很年轻。',
                'example_translation' => 'She is very young.',
                'definition' => 'Young, youthful',
                'sentences' => ['很___。', '___人。', '___时。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '老',
                'pinyin' => 'lǎo',
                'simplified' => '老',
                'traditional' => '老',
                'part_of_speech' => 'adjective',
                'meaning' => 'Old',
                'meaning_zh' => '老',
                'example_sentence' => '他老了。',
                'example_translation' => 'He is old.',
                'definition' => 'Old, aged',
                'sentences' => ['___了。', '___人。', '___师。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '长',
                'pinyin' => 'cháng',
                'simplified' => '长',
                'traditional' => '長',
                'part_of_speech' => 'adjective',
                'meaning' => 'Long',
                'meaning_zh' => '长',
                'example_sentence' => '她的头发很长。',
                'example_translation' => 'Her hair is very long.',
                'definition' => 'Long',
                'sentences' => ['很___。', '___头发。', '___短。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '短',
                'pinyin' => 'duǎn',
                'simplified' => '短',
                'traditional' => '短',
                'part_of_speech' => 'adjective',
                'meaning' => 'Short (length)',
                'meaning_zh' => '短',
                'example_sentence' => '他的头发很短。',
                'example_translation' => 'His hair is very short.',
                'definition' => 'Short (in length)',
                'sentences' => ['很___。', '___头发。', '___裤。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '大',
                'pinyin' => 'dà',
                'simplified' => '大',
                'traditional' => '大',
                'part_of_speech' => 'adjective',
                'meaning' => 'Big / Large',
                'meaning_zh' => '大',
                'example_sentence' => '这个很大。',
                'example_translation' => 'This is very big.',
                'definition' => 'Big, large, great',
                'sentences' => ['很___。', '___小。', '___家。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '小',
                'pinyin' => 'xiǎo',
                'simplified' => '小',
                'traditional' => '小',
                'part_of_speech' => 'adjective',
                'meaning' => 'Small / Little',
                'meaning_zh' => '小',
                'example_sentence' => '这个很小。',
                'example_translation' => 'This is very small.',
                'definition' => 'Small, little, young',
                'sentences' => ['很___。', '___孩子。', '___学。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '可爱',
                'pinyin' => 'kě ài',
                'simplified' => '可爱',
                'traditional' => '可愛',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cute / Lovely',
                'meaning_zh' => '可爱',
                'example_sentence' => '这个孩子很可爱。',
                'example_translation' => 'This child is very cute.',
                'definition' => 'Cute, lovely, adorable',
                'sentences' => ['很___。', '___的孩子。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '聪明',
                'pinyin' => 'cōng ming',
                'simplified' => '聪明',
                'traditional' => '聰明',
                'part_of_speech' => 'adjective',
                'meaning' => 'Smart / Clever',
                'meaning_zh' => '聪明',
                'example_sentence' => '他很聪明。',
                'example_translation' => 'He is very smart.',
                'definition' => 'Smart, clever, intelligent',
                'sentences' => ['很___。', '___的学生。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '干净',
                'pinyin' => 'gān jìng',
                'simplified' => '干净',
                'traditional' => '乾淨',
                'part_of_speech' => 'adjective',
                'meaning' => 'Clean',
                'meaning_zh' => '干净',
                'example_sentence' => '房间很干净。',
                'example_translation' => 'The room is very clean.',
                'definition' => 'Clean, neat',
                'sentences' => ['很___。', '___吗？', '___的房间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '脏',
                'pinyin' => 'zāng',
                'simplified' => '脏',
                'traditional' => '髒',
                'part_of_speech' => 'adjective',
                'meaning' => 'Dirty',
                'meaning_zh' => '脏',
                'example_sentence' => '衣服很脏。',
                'example_translation' => 'The clothes are very dirty.',
                'definition' => 'Dirty, filthy',
                'sentences' => ['很___。', '___了。', '___衣服。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '整齐',
                'pinyin' => 'zhěng qí',
                'simplified' => '整齐',
                'traditional' => '整齊',
                'part_of_speech' => 'adjective',
                'meaning' => 'Neat / Tidy',
                'meaning_zh' => '整齐',
                'example_sentence' => '书桌很整齐。',
                'example_translation' => 'The desk is very tidy.',
                'definition' => 'Neat, tidy, orderly',
                'sentences' => ['很___。', '___吗？', '___的桌子。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '厚',
                'pinyin' => 'hòu',
                'simplified' => '厚',
                'traditional' => '厚',
                'part_of_speech' => 'adjective',
                'meaning' => 'Thick',
                'meaning_zh' => '厚',
                'example_sentence' => '这本书很厚。',
                'example_translation' => 'This book is very thick.',
                'definition' => 'Thick, deep, generous',
                'sentences' => ['很___。', '___书。', '___薄。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 39,
                'word' => '薄',
                'pinyin' => 'báo',
                'simplified' => '薄',
                'traditional' => '薄',
                'part_of_speech' => 'adjective',
                'meaning' => 'Thin (thickness)',
                'meaning_zh' => '薄',
                'example_sentence' => '纸很薄。',
                'example_translation' => 'The paper is very thin.',
                'definition' => 'Thin (thickness), weak',
                'sentences' => ['很___。', '___纸。', '___衣服。'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($directionsVocab, $transportationVocab, $emotionsVocab, $appearanceVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
