<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics29to30Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 61: Public Services (公共服务) - 20 words
        $servicesVocab = [
            [
                'topic_id' => 61,
                'word' => '服务',
                'pinyin' => 'fú wù',
                'simplified' => '服务',
                'traditional' => '服務',
                'part_of_speech' => 'noun',
                'meaning' => 'Service',
                'meaning_zh' => '服务',
                'example_sentence' => '服务很好。',
                'example_translation' => 'The service is very good.',
                'definition' => 'Service, to serve',
                'sentences' => ['___很好。', '___员。', '___中心。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '银行',
                'pinyin' => 'yín háng',
                'simplified' => '银行',
                'traditional' => '銀行',
                'part_of_speech' => 'noun',
                'meaning' => 'Bank',
                'meaning_zh' => '银行',
                'example_sentence' => '去银行。',
                'example_translation' => 'Go to the bank.',
                'definition' => 'Bank',
                'sentences' => ['去___。', '___卡。', '___账户。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '邮局',
                'pinyin' => 'yóu jú',
                'simplified' => '邮局',
                'traditional' => '郵局',
                'part_of_speech' => 'noun',
                'meaning' => 'Post office',
                'meaning_zh' => '邮局',
                'example_sentence' => '去邮局寄信。',
                'example_translation' => 'Go to the post office to mail letters.',
                'definition' => 'Post office',
                'sentences' => ['去___。', '___在哪？', '___寄信。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '警察',
                'pinyin' => 'jǐng chá',
                'simplified' => '警察',
                'traditional' => '警察',
                'part_of_speech' => 'noun',
                'meaning' => 'Police',
                'meaning_zh' => '警察',
                'example_sentence' => '报警察。',
                'example_translation' => 'Call the police.',
                'definition' => 'Police',
                'sentences' => ['报___。', '___来了。', '___局。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '消防',
                'pinyin' => 'xiāo fáng',
                'simplified' => '消防',
                'traditional' => '消防',
                'part_of_speech' => 'noun',
                'meaning' => 'Fire department / Fire fighting',
                'meaning_zh' => '消防',
                'example_sentence' => '消防员来了。',
                'example_translation' => 'The firefighters came.',
                'definition' => 'Fire department, fire fighting',
                'sentences' => ['___员。', '___车。', '___演习。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '政府',
                'pinyin' => 'zhèng fǔ',
                'simplified' => '政府',
                'traditional' => '政府',
                'part_of_speech' => 'noun',
                'meaning' => 'Government',
                'meaning_zh' => '政府',
                'example_sentence' => '政府大楼。',
                'example_translation' => 'Government building.',
                'definition' => 'Government',
                'sentences' => ['___大楼。', '___部门。', '___工作。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '办公室',
                'pinyin' => 'bàn gōng shì',
                'simplified' => '办公室',
                'traditional' => '辦公室',
                'part_of_speech' => 'noun',
                'meaning' => 'Office',
                'meaning_zh' => '办公室',
                'example_sentence' => '在办公室工作。',
                'example_translation' => 'Work in the office.',
                'definition' => 'Office',
                'sentences' => ['在___。', '___工作。', '___环境。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '营业',
                'pinyin' => 'yíng yè',
                'simplified' => '营业',
                'traditional' => '營業',
                'part_of_speech' => 'verb',
                'meaning' => 'To be open for business',
                'meaning_zh' => '营业',
                'example_sentence' => '现在营业。',
                'example_translation' => 'Open for business now.',
                'definition' => 'To be open for business, to do business',
                'sentences' => ['___时间。', '___了。', '停止___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '预约',
                'pinyin' => 'yù yuē',
                'simplified' => '预约',
                'traditional' => '預約',
                'part_of_speech' => 'verb',
                'meaning' => 'To make an appointment',
                'meaning_zh' => '预约',
                'example_sentence' => '我要预约。',
                'example_translation' => 'I want to make an appointment.',
                'definition' => 'To make an appointment, to reserve',
                'sentences' => ['___时间。', '___了。', '需要___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '排队',
                'pinyin' => 'pái duì',
                'simplified' => '排队',
                'traditional' => '排隊',
                'part_of_speech' => 'verb',
                'meaning' => 'To queue / To line up',
                'meaning_zh' => '排队',
                'example_sentence' => '排队等候。',
                'example_translation' => 'Queue up and wait.',
                'definition' => 'To queue, to line up',
                'sentences' => ['___等。', '___买票。', '___的人。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '登记',
                'pinyin' => 'dēng jì',
                'simplified' => '登记',
                'traditional' => '登記',
                'part_of_speech' => 'verb',
                'meaning' => 'To register',
                'meaning_zh' => '登记',
                'example_sentence' => '请登记。',
                'example_translation' => 'Please register.',
                'definition' => 'To register, to check in',
                'sentences' => ['___信息。', '___了。', '___表。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '手续',
                'pinyin' => 'shǒu xù',
                'simplified' => '手续',
                'traditional' => '手續',
                'part_of_speech' => 'noun',
                'meaning' => 'Procedure / Formality',
                'meaning_zh' => '手续',
                'example_sentence' => '办手续。',
                'example_translation' => 'Handle procedures.',
                'definition' => 'Procedure, formality',
                'sentences' => ['办___。', '___很多。', '___完成。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '证件',
                'pinyin' => 'zhèng jiàn',
                'simplified' => '证件',
                'traditional' => '證件',
                'part_of_speech' => 'noun',
                'meaning' => 'ID / Certificate',
                'meaning_zh' => '证件',
                'example_sentence' => '请出示证件。',
                'example_translation' => 'Please show your ID.',
                'definition' => 'ID, certificate, credentials',
                'sentences' => ['出示___。', '___照片。', '___齐全。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '身份证',
                'pinyin' => 'shēn fèn zhèng',
                'simplified' => '身份证',
                'traditional' => '身份證',
                'part_of_speech' => 'noun',
                'meaning' => 'ID card',
                'meaning_zh' => '身份证',
                'example_sentence' => '带身份证。',
                'example_translation' => 'Bring your ID card.',
                'definition' => 'ID card, identity card',
                'sentences' => ['___号码。', '___复印件。', '出示___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '护照',
                'pinyin' => 'hù zhào',
                'simplified' => '护照',
                'traditional' => '護照',
                'part_of_speech' => 'noun',
                'meaning' => 'Passport',
                'meaning_zh' => '护照',
                'example_sentence' => '办护照。',
                'example_translation' => 'Apply for a passport.',
                'definition' => 'Passport',
                'sentences' => ['___号码。', '___有效期。', '___过期。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '签证',
                'pinyin' => 'qiān zhèng',
                'simplified' => '签证',
                'traditional' => '簽證',
                'part_of_speech' => 'noun',
                'meaning' => 'Visa',
                'meaning_zh' => '签证',
                'example_sentence' => '申请签证。',
                'example_translation' => 'Apply for a visa.',
                'definition' => 'Visa',
                'sentences' => ['___申请。', '___办理。', '___有效。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '申请',
                'pinyin' => 'shēn qǐng',
                'simplified' => '申请',
                'traditional' => '申請',
                'part_of_speech' => 'verb',
                'meaning' => 'To apply',
                'meaning_zh' => '申请',
                'example_sentence' => '申请工作。',
                'example_translation' => 'Apply for a job.',
                'definition' => 'To apply, application',
                'sentences' => ['___工作。', '___学校。', '___表。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '办理',
                'pinyin' => 'bàn lǐ',
                'simplified' => '办理',
                'traditional' => '辦理',
                'part_of_speech' => 'verb',
                'meaning' => 'To handle / To process',
                'meaning_zh' => '办理',
                'example_sentence' => '办理手续。',
                'example_translation' => 'Handle procedures.',
                'definition' => 'To handle, to process',
                'sentences' => ['___手续。', '___业务。', '___完成。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '咨询',
                'pinyin' => 'zī xún',
                'simplified' => '咨询',
                'traditional' => '諮詢',
                'part_of_speech' => 'verb',
                'meaning' => 'To consult / To inquire',
                'meaning_zh' => '咨询',
                'example_sentence' => '咨询问题。',
                'example_translation' => 'Consult about problems.',
                'definition' => 'To consult, to inquire',
                'sentences' => ['___台。', '___服务。', '___电话。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 61,
                'word' => '投诉',
                'pinyin' => 'tóu sù',
                'simplified' => '投诉',
                'traditional' => '投訴',
                'part_of_speech' => 'verb',
                'meaning' => 'To complain',
                'meaning_zh' => '投诉',
                'example_sentence' => '投诉服务。',
                'example_translation' => 'Complain about the service.',
                'definition' => 'To complain, complaint',
                'sentences' => ['___电话。', '___处理。', '___渠道。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 62: Cultural Customs (文化习俗) - 20 words
        $cultureVocab = [
            [
                'topic_id' => 62,
                'word' => '文化',
                'pinyin' => 'wén huà',
                'simplified' => '文化',
                'traditional' => '文化',
                'part_of_speech' => 'noun',
                'meaning' => 'Culture',
                'meaning_zh' => '文化',
                'example_sentence' => '中国文化。',
                'example_translation' => 'Chinese culture.',
                'definition' => 'Culture',
                'sentences' => ['___差异。', '___交流。', '___遗产。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '礼貌',
                'pinyin' => 'lǐ mào',
                'simplified' => '礼貌',
                'traditional' => '禮貌',
                'part_of_speech' => 'noun',
                'meaning' => 'Polite / Politeness',
                'meaning_zh' => '礼貌',
                'example_sentence' => '很礼貌。',
                'example_translation' => 'Very polite.',
                'definition' => 'Polite, politeness, courtesy',
                'sentences' => ['很___。', '___待人。', '___用语。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '尊重',
                'pinyin' => 'zūn zhòng',
                'simplified' => '尊重',
                'traditional' => '尊重',
                'part_of_speech' => 'verb',
                'meaning' => 'To respect',
                'meaning_zh' => '尊重',
                'example_sentence' => '尊重别人。',
                'example_translation' => 'Respect others.',
                'definition' => 'To respect, respect',
                'sentences' => ['___别人。', '___文化。', '___习俗。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '礼物',
                'pinyin' => 'lǐ wù',
                'simplified' => '礼物',
                'traditional' => '禮物',
                'part_of_speech' => 'noun',
                'meaning' => 'Gift / Present',
                'meaning_zh' => '礼物',
                'example_sentence' => '送礼物。',
                'example_translation' => 'Give a gift.',
                'definition' => 'Gift, present',
                'sentences' => ['送___。', '___盒。', '___包装。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '客人',
                'pinyin' => 'kè rén',
                'simplified' => '客人',
                'traditional' => '客人',
                'part_of_speech' => 'noun',
                'meaning' => 'Guest',
                'meaning_zh' => '客人',
                'example_sentence' => '欢迎客人。',
                'example_translation' => 'Welcome guests.',
                'definition' => 'Guest, visitor',
                'sentences' => ['___来了。', '招待___。', '___很多。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '主人',
                'pinyin' => 'zhǔ rén',
                'simplified' => '主人',
                'traditional' => '主人',
                'part_of_speech' => 'noun',
                'meaning' => 'Host / Owner',
                'meaning_zh' => '主人',
                'example_sentence' => '我是主人。',
                'example_translation' => 'I am the host.',
                'definition' => 'Host, owner, master',
                'sentences' => ['___好客。', '___热情。', '___家。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '招待',
                'pinyin' => 'zhāo dài',
                'simplified' => '招待',
                'traditional' => '招待',
                'part_of_speech' => 'verb',
                'meaning' => 'To receive / To entertain',
                'meaning_zh' => '招待',
                'example_sentence' => '招待客人。',
                'example_translation' => 'Entertain guests.',
                'definition' => 'To receive, to entertain',
                'sentences' => ['___客人。', '___所。', '___会。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '热情',
                'pinyin' => 'rè qíng',
                'simplified' => '热情',
                'traditional' => '熱情',
                'part_of_speech' => 'adjective',
                'meaning' => 'Enthusiastic / Warm',
                'meaning_zh' => '热情',
                'example_sentence' => '很热情。',
                'example_translation' => 'Very enthusiastic.',
                'definition' => 'Enthusiastic, warm, passionate',
                'sentences' => ['很___。', '___待人。', '___服务。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '客气',
                'pinyin' => 'kè qi',
                'simplified' => '客气',
                'traditional' => '客氣',
                'part_of_speech' => 'adjective',
                'meaning' => 'Polite / Courteous',
                'meaning_zh' => '客气',
                'example_sentence' => '不客气。',
                'example_translation' => 'You\'re welcome.',
                'definition' => 'Polite, courteous',
                'sentences' => ['不___。', '___话。', '太___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '打招呼',
                'pinyin' => 'dǎ zhāo hu',
                'simplified' => '打招呼',
                'traditional' => '打招呼',
                'part_of_speech' => 'verb',
                'meaning' => 'To greet',
                'meaning_zh' => '打招呼',
                'example_sentence' => '见面打招呼。',
                'example_translation' => 'Greet when meeting.',
                'definition' => 'To greet, to say hello',
                'sentences' => ['___了。', '先___。', '互相___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '握手',
                'pinyin' => 'wò shǒu',
                'simplified' => '握手',
                'traditional' => '握手',
                'part_of_speech' => 'verb',
                'meaning' => 'To shake hands',
                'meaning_zh' => '握手',
                'example_sentence' => '我们握手。',
                'example_translation' => 'We shake hands.',
                'definition' => 'To shake hands',
                'sentences' => ['___了。', '___致意。', '___礼。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '鞠躬',
                'pinyin' => 'jū gōng',
                'simplified' => '鞠躬',
                'traditional' => '鞠躬',
                'part_of_speech' => 'verb',
                'meaning' => 'To bow',
                'meaning_zh' => '鞠躬',
                'example_sentence' => '鞠躬致敬。',
                'example_translation' => 'Bow to show respect.',
                'definition' => 'To bow',
                'sentences' => ['___了。', '___礼。', '___致谢。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '敬酒',
                'pinyin' => 'jìng jiǔ',
                'simplified' => '敬酒',
                'traditional' => '敬酒',
                'part_of_speech' => 'verb',
                'meaning' => 'To toast / To propose a toast',
                'meaning_zh' => '敬酒',
                'example_sentence' => '敬酒祝贺。',
                'example_translation' => 'Toast to congratulate.',
                'definition' => 'To toast, to propose a toast',
                'sentences' => ['___了。', '___致词。', '___祝福。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '干杯',
                'pinyin' => 'gān bēi',
                'simplified' => '干杯',
                'traditional' => '乾杯',
                'part_of_speech' => 'verb',
                'meaning' => 'Cheers / Bottoms up',
                'meaning_zh' => '干杯',
                'example_sentence' => '我们干杯！',
                'example_translation' => 'Let\'s cheers!',
                'definition' => 'Cheers, bottoms up',
                'sentences' => ['___！', '一起___。', '___庆祝。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '吉祥',
                'pinyin' => 'jí xiáng',
                'simplified' => '吉祥',
                'traditional' => '吉祥',
                'part_of_speech' => 'adjective',
                'meaning' => 'Auspicious / Lucky',
                'meaning_zh' => '吉祥',
                'example_sentence' => '吉祥的日子。',
                'example_translation' => 'An auspicious day.',
                'definition' => 'Auspicious, lucky',
                'sentences' => ['___的。', '___物。', '___如意。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '幸运',
                'pinyin' => 'xìng yùn',
                'simplified' => '幸运',
                'traditional' => '幸運',
                'part_of_speech' => 'adjective',
                'meaning' => 'Lucky / Fortunate',
                'meaning_zh' => '幸运',
                'example_sentence' => '很幸运。',
                'example_translation' => 'Very lucky.',
                'definition' => 'Lucky, fortunate',
                'sentences' => ['很___。', '___的人。', '___儿。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '禁忌',
                'pinyin' => 'jìn jì',
                'simplified' => '禁忌',
                'traditional' => '禁忌',
                'part_of_speech' => 'noun',
                'meaning' => 'Taboo',
                'meaning_zh' => '禁忌',
                'example_sentence' => '文化禁忌。',
                'example_translation' => 'Cultural taboos.',
                'definition' => 'Taboo, to avoid as taboo',
                'sentences' => ['___很多。', '___事项。', '注意___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '迷信',
                'pinyin' => 'mí xìn',
                'simplified' => '迷信',
                'traditional' => '迷信',
                'part_of_speech' => 'noun',
                'meaning' => 'Superstition',
                'meaning_zh' => '迷信',
                'example_sentence' => '不要迷信。',
                'example_translation' => 'Don\'t be superstitious.',
                'definition' => 'Superstition, to be superstitious',
                'sentences' => ['___思想。', '___活动。', '不___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '风俗',
                'pinyin' => 'fēng sú',
                'simplified' => '风俗',
                'traditional' => '風俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom',
                'meaning_zh' => '风俗',
                'example_sentence' => '各地风俗不同。',
                'example_translation' => 'Customs differ in different places.',
                'definition' => 'Custom, convention',
                'sentences' => ['___不同。', '___习惯。', '地方___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 62,
                'word' => '规矩',
                'pinyin' => 'guī ju',
                'simplified' => '规矩',
                'traditional' => '規矩',
                'part_of_speech' => 'noun',
                'meaning' => 'Rule / Custom',
                'meaning_zh' => '规矩',
                'example_sentence' => '遵守规矩。',
                'example_translation' => 'Follow the rules.',
                'definition' => 'Rule, custom, well-behaved',
                'sentences' => ['___很多。', '遵守___。', '___人。'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($servicesVocab, $cultureVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
