<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics26to28Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 58: Chinese Food and Drinks (中国饮食) - 20 words
        $foodVocab = [
            [
                'topic_id' => 58,
                'word' => '饮食',
                'pinyin' => 'yǐn shí',
                'simplified' => '饮食',
                'traditional' => '飲食',
                'part_of_speech' => 'noun',
                'meaning' => 'Food and drink / Diet',
                'meaning_zh' => '饮食',
                'example_sentence' => '健康饮食很重要。',
                'example_translation' => 'A healthy diet is very important.',
                'definition' => 'Food and drink, diet, eating and drinking',
                'sentences' => ['健康___。', '___习惯。', '中国___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '面条',
                'pinyin' => 'miàn tiào',
                'simplified' => '面条',
                'traditional' => '麵條',
                'part_of_speech' => 'noun',
                'meaning' => 'Noodles',
                'meaning_zh' => '面条',
                'example_sentence' => '我喜欢吃面条。',
                'example_translation' => 'I like eating noodles.',
                'definition' => 'Noodles',
                'sentences' => ['吃___。', '一碗___。', '___很好吃。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '米饭',
                'pinyin' => 'mǐ fàn',
                'simplified' => '米饭',
                'traditional' => '米飯',
                'part_of_speech' => 'noun',
                'meaning' => 'Cooked rice',
                'meaning_zh' => '米饭',
                'example_sentence' => '我每天吃米饭。',
                'example_translation' => 'I eat rice every day.',
                'definition' => 'Cooked rice',
                'sentences' => ['吃___。', '一碗___。', '___很香。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '饺子',
                'pinyin' => 'jiǎo zi',
                'simplified' => '饺子',
                'traditional' => '餃子',
                'part_of_speech' => 'noun',
                'meaning' => 'Dumplings',
                'meaning_zh' => '饺子',
                'example_sentence' => '过年吃饺子。',
                'example_translation' => 'Eat dumplings during New Year.',
                'definition' => 'Dumplings (Chinese)',
                'sentences' => ['吃___。', '包___。', '___很好吃。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '包子',
                'pinyin' => 'bāo zi',
                'simplified' => '包子',
                'traditional' => '包子',
                'part_of_speech' => 'noun',
                'meaning' => 'Steamed bun',
                'meaning_zh' => '包子',
                'example_sentence' => '早上吃包子。',
                'example_translation' => 'Eat steamed buns in the morning.',
                'definition' => 'Steamed bun',
                'sentences' => ['吃___。', '一个___。', '___很好吃。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '馒头',
                'pinyin' => 'mán tou',
                'simplified' => '馒头',
                'traditional' => '饅頭',
                'part_of_speech' => 'noun',
                'meaning' => 'Steamed bread',
                'meaning_zh' => '馒头',
                'example_sentence' => '馒头很软。',
                'example_translation' => 'The steamed bread is very soft.',
                'definition' => 'Steamed bread (Chinese)',
                'sentences' => ['吃___。', '一个___。', '___很软。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '豆腐',
                'pinyin' => 'dòu fu',
                'simplified' => '豆腐',
                'traditional' => '豆腐',
                'part_of_speech' => 'noun',
                'meaning' => 'Tofu',
                'meaning_zh' => '豆腐',
                'example_sentence' => '我喜欢吃豆腐。',
                'example_translation' => 'I like eating tofu.',
                'definition' => 'Tofu, bean curd',
                'sentences' => ['吃___。', '麻婆___。', '___很嫩。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '豆浆',
                'pinyin' => 'dòu jiāng',
                'simplified' => '豆浆',
                'traditional' => '豆漿',
                'part_of_speech' => 'noun',
                'meaning' => 'Soy milk',
                'meaning_zh' => '豆浆',
                'example_sentence' => '早上喝豆浆。',
                'example_translation' => 'Drink soy milk in the morning.',
                'definition' => 'Soy milk',
                'sentences' => ['喝___。', '一杯___。', '___很香。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '油条',
                'pinyin' => 'yóu tiáo',
                'simplified' => '油条',
                'traditional' => '油條',
                'part_of_speech' => 'noun',
                'meaning' => 'Fried dough stick',
                'meaning_zh' => '油条',
                'example_sentence' => '豆浆配油条。',
                'example_translation' => 'Soy milk with fried dough sticks.',
                'definition' => 'Fried dough stick (Chinese breakfast)',
                'sentences' => ['吃___。', '___很脆。', '豆浆___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '火锅',
                'pinyin' => 'huǒ guō',
                'simplified' => '火锅',
                'traditional' => '火鍋',
                'part_of_speech' => 'noun',
                'meaning' => 'Hot pot',
                'meaning_zh' => '火锅',
                'example_sentence' => '冬天吃火锅。',
                'example_translation' => 'Eat hot pot in winter.',
                'definition' => 'Hot pot (Chinese cuisine)',
                'sentences' => ['吃___。', '___很辣。', '涮___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '炒饭',
                'pinyin' => 'chǎo fàn',
                'simplified' => '炒饭',
                'traditional' => '炒飯',
                'part_of_speech' => 'noun',
                'meaning' => 'Fried rice',
                'meaning_zh' => '炒饭',
                'example_sentence' => '我想吃炒饭。',
                'example_translation' => 'I want to eat fried rice.',
                'definition' => 'Fried rice',
                'sentences' => ['吃___。', '蛋___。', '___很香。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '炒菜',
                'pinyin' => 'chǎo cài',
                'simplified' => '炒菜',
                'traditional' => '炒菜',
                'part_of_speech' => 'noun',
                'meaning' => 'Stir-fried dish',
                'meaning_zh' => '炒菜',
                'example_sentence' => '妈妈在炒菜。',
                'example_translation' => 'Mom is stir-frying dishes.',
                'definition' => 'Stir-fried dish, to stir-fry',
                'sentences' => ['___很香。', '会___吗？', '___做饭。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '烤鸭',
                'pinyin' => 'kǎo yā',
                'simplified' => '烤鸭',
                'traditional' => '烤鴨',
                'part_of_speech' => 'noun',
                'meaning' => 'Roast duck',
                'meaning_zh' => '烤鸭',
                'example_sentence' => '北京烤鸭很有名。',
                'example_translation' => 'Beijing roast duck is very famous.',
                'definition' => 'Roast duck',
                'sentences' => ['北京___。', '吃___。', '___很好吃。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '小吃',
                'pinyin' => 'xiǎo chī',
                'simplified' => '小吃',
                'traditional' => '小吃',
                'part_of_speech' => 'noun',
                'meaning' => 'Snack / Street food',
                'meaning_zh' => '小吃',
                'example_sentence' => '这里的小吃很多。',
                'example_translation' => 'There are many snacks here.',
                'definition' => 'Snack, street food',
                'sentences' => ['吃___。', '___店。', '___很多。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '零食',
                'pinyin' => 'líng shí',
                'simplified' => '零食',
                'traditional' => '零食',
                'part_of_speech' => 'noun',
                'meaning' => 'Snacks',
                'meaning_zh' => '零食',
                'example_sentence' => '少吃零食。',
                'example_translation' => 'Eat fewer snacks.',
                'definition' => 'Snacks, nibbles',
                'sentences' => ['吃___。', '___很多。', '少吃___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '甜点',
                'pinyin' => 'tián diǎn',
                'simplified' => '甜点',
                'traditional' => '甜點',
                'part_of_speech' => 'noun',
                'meaning' => 'Dessert',
                'meaning_zh' => '甜点',
                'example_sentence' => '饭后吃甜点。',
                'example_translation' => 'Eat dessert after meal.',
                'definition' => 'Dessert, sweet',
                'sentences' => ['吃___。', '___很甜。', '___店。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '饮料',
                'pinyin' => 'yǐn liào',
                'simplified' => '饮料',
                'traditional' => '飲料',
                'part_of_speech' => 'noun',
                'meaning' => 'Beverage / Drink',
                'meaning_zh' => '饮料',
                'example_sentence' => '你要喝什么饮料？',
                'example_translation' => 'What beverage do you want to drink?',
                'definition' => 'Beverage, drink',
                'sentences' => ['喝___。', '___店。', '买___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '果汁',
                'pinyin' => 'guǒ zhī',
                'simplified' => '果汁',
                'traditional' => '果汁',
                'part_of_speech' => 'noun',
                'meaning' => 'Fruit juice',
                'meaning_zh' => '果汁',
                'example_sentence' => '我要一杯果汁。',
                'example_translation' => 'I want a glass of fruit juice.',
                'definition' => 'Fruit juice',
                'sentences' => ['喝___。', '一杯___。', '___很新鲜。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '味道',
                'pinyin' => 'wèi dào',
                'simplified' => '味道',
                'traditional' => '味道',
                'part_of_speech' => 'noun',
                'meaning' => 'Taste / Flavor',
                'meaning_zh' => '味道',
                'example_sentence' => '味道很好。',
                'example_translation' => 'The taste is very good.',
                'definition' => 'Taste, flavor',
                'sentences' => ['___很好。', '___不错。', '___怎么样？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 58,
                'word' => '菜单',
                'pinyin' => 'cài dān',
                'simplified' => '菜单',
                'traditional' => '菜單',
                'part_of_speech' => 'noun',
                'meaning' => 'Menu',
                'meaning_zh' => '菜单',
                'example_sentence' => '请给我菜单。',
                'example_translation' => 'Please give me the menu.',
                'definition' => 'Menu',
                'sentences' => ['看___。', '___在这里。', '点___。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 59: Festivals and Holidays (节日和假期) - 20 words
        $festivalVocab = [
            [
                'topic_id' => 59,
                'word' => '节日',
                'pinyin' => 'jié rì',
                'simplified' => '节日',
                'traditional' => '節日',
                'part_of_speech' => 'noun',
                'meaning' => 'Festival / Holiday',
                'meaning_zh' => '节日',
                'example_sentence' => '春节是重要的节日。',
                'example_translation' => 'Spring Festival is an important holiday.',
                'definition' => 'Festival, holiday',
                'sentences' => ['___快乐。', '中国___。', '___活动。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '假期',
                'pinyin' => 'jià qī',
                'simplified' => '假期',
                'traditional' => '假期',
                'part_of_speech' => 'noun',
                'meaning' => 'Holiday / Vacation',
                'meaning_zh' => '假期',
                'example_sentence' => '假期去旅游。',
                'example_translation' => 'Go traveling during the holiday.',
                'definition' => 'Holiday, vacation',
                'sentences' => ['___快乐。', '放___。', '___计划。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '春节',
                'pinyin' => 'chūn jié',
                'simplified' => '春节',
                'traditional' => '春節',
                'part_of_speech' => 'noun',
                'meaning' => 'Spring Festival / Chinese New Year',
                'meaning_zh' => '春节',
                'example_sentence' => '春节快乐！',
                'example_translation' => 'Happy Chinese New Year!',
                'definition' => 'Spring Festival, Chinese New Year',
                'sentences' => ['___快乐。', '过___。', '___期间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '过年',
                'pinyin' => 'guò nián',
                'simplified' => '过年',
                'traditional' => '過年',
                'part_of_speech' => 'verb',
                'meaning' => 'To celebrate the New Year',
                'meaning_zh' => '过年',
                'example_sentence' => '我们一起过年。',
                'example_translation' => 'We celebrate New Year together.',
                'definition' => 'To celebrate the New Year',
                'sentences' => ['___了。', '一起___。', '回家___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '中秋节',
                'pinyin' => 'zhōng qiū jié',
                'simplified' => '中秋节',
                'traditional' => '中秋節',
                'part_of_speech' => 'noun',
                'meaning' => 'Mid-Autumn Festival',
                'meaning_zh' => '中秋节',
                'example_sentence' => '中秋节吃月饼。',
                'example_translation' => 'Eat mooncakes during Mid-Autumn Festival.',
                'definition' => 'Mid-Autumn Festival',
                'sentences' => ['___快乐。', '___吃月饼。', '___赏月。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '端午节',
                'pinyin' => 'duān wǔ jié',
                'simplified' => '端午节',
                'traditional' => '端午節',
                'part_of_speech' => 'noun',
                'meaning' => 'Dragon Boat Festival',
                'meaning_zh' => '端午节',
                'example_sentence' => '端午节吃粽子。',
                'example_translation' => 'Eat zongzi during Dragon Boat Festival.',
                'definition' => 'Dragon Boat Festival',
                'sentences' => ['___快乐。', '___吃粽子。', '___赛龙舟。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '元宵节',
                'pinyin' => 'yuán xiāo jié',
                'simplified' => '元宵节',
                'traditional' => '元宵節',
                'part_of_speech' => 'noun',
                'meaning' => 'Lantern Festival',
                'meaning_zh' => '元宵节',
                'example_sentence' => '元宵节看灯笼。',
                'example_translation' => 'Watch lanterns during Lantern Festival.',
                'definition' => 'Lantern Festival',
                'sentences' => ['___快乐。', '___吃元宵。', '___看灯。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '国庆节',
                'pinyin' => 'guó qìng jié',
                'simplified' => '国庆节',
                'traditional' => '國慶節',
                'part_of_speech' => 'noun',
                'meaning' => 'National Day',
                'meaning_zh' => '国庆节',
                'example_sentence' => '国庆节放假。',
                'example_translation' => 'Have a holiday on National Day.',
                'definition' => 'National Day',
                'sentences' => ['___快乐。', '___放假。', '___旅游。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '庆祝',
                'pinyin' => 'qìng zhù',
                'simplified' => '庆祝',
                'traditional' => '慶祝',
                'part_of_speech' => 'verb',
                'meaning' => 'To celebrate',
                'meaning_zh' => '庆祝',
                'example_sentence' => '我们庆祝生日。',
                'example_translation' => 'We celebrate birthday.',
                'definition' => 'To celebrate',
                'sentences' => ['___节日。', '___生日。', '___成功。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '团圆',
                'pinyin' => 'tuán yuán',
                'simplified' => '团圆',
                'traditional' => '團圓',
                'part_of_speech' => 'verb',
                'meaning' => 'To reunite / Reunion',
                'meaning_zh' => '团圆',
                'example_sentence' => '过年一家人团圆。',
                'example_translation' => 'The family reunites for New Year.',
                'definition' => 'To reunite, reunion',
                'sentences' => ['家人___。', '___饭。', '___的日子。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '红包',
                'pinyin' => 'hóng bāo',
                'simplified' => '红包',
                'traditional' => '紅包',
                'part_of_speech' => 'noun',
                'meaning' => 'Red envelope / Money gift',
                'meaning_zh' => '红包',
                'example_sentence' => '过年给红包。',
                'example_translation' => 'Give red envelopes during New Year.',
                'definition' => 'Red envelope, money gift',
                'sentences' => ['发___。', '收___。', '___里有钱。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '月饼',
                'pinyin' => 'yuè bǐng',
                'simplified' => '月饼',
                'traditional' => '月餅',
                'part_of_speech' => 'noun',
                'meaning' => 'Mooncake',
                'meaning_zh' => '月饼',
                'example_sentence' => '中秋节吃月饼。',
                'example_translation' => 'Eat mooncakes during Mid-Autumn Festival.',
                'definition' => 'Mooncake',
                'sentences' => ['吃___。', '___很好吃。', '送___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '粽子',
                'pinyin' => 'zòng zi',
                'simplified' => '粽子',
                'traditional' => '粽子',
                'part_of_speech' => 'noun',
                'meaning' => 'Zongzi / Rice dumpling',
                'meaning_zh' => '粽子',
                'example_sentence' => '端午节吃粽子。',
                'example_translation' => 'Eat zongzi during Dragon Boat Festival.',
                'definition' => 'Zongzi, rice dumpling',
                'sentences' => ['吃___。', '包___。', '___很香。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '灯笼',
                'pinyin' => 'dēng long',
                'simplified' => '灯笼',
                'traditional' => '燈籠',
                'part_of_speech' => 'noun',
                'meaning' => 'Lantern',
                'meaning_zh' => '灯笼',
                'example_sentence' => '挂灯笼。',
                'example_translation' => 'Hang lanterns.',
                'definition' => 'Lantern',
                'sentences' => ['挂___。', '红___。', '看___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '烟花',
                'pinyin' => 'yān huā',
                'simplified' => '烟花',
                'traditional' => '煙花',
                'part_of_speech' => 'noun',
                'meaning' => 'Fireworks',
                'meaning_zh' => '烟花',
                'example_sentence' => '放烟花。',
                'example_translation' => 'Set off fireworks.',
                'definition' => 'Fireworks',
                'sentences' => ['放___。', '看___。', '___很美。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '鞭炮',
                'pinyin' => 'biān pào',
                'simplified' => '鞭炮',
                'traditional' => '鞭炮',
                'part_of_speech' => 'noun',
                'meaning' => 'Firecrackers',
                'meaning_zh' => '鞭炮',
                'example_sentence' => '放鞭炮。',
                'example_translation' => 'Set off firecrackers.',
                'definition' => 'Firecrackers',
                'sentences' => ['放___。', '___很响。', '___声。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '拜年',
                'pinyin' => 'bài nián',
                'simplified' => '拜年',
                'traditional' => '拜年',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay a New Year call',
                'meaning_zh' => '拜年',
                'example_sentence' => '去拜年。',
                'example_translation' => 'Go to pay New Year visits.',
                'definition' => 'To pay a New Year call, to wish a Happy New Year',
                'sentences' => ['去___。', '___了。', '互相___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '祝福',
                'pinyin' => 'zhù fú',
                'simplified' => '祝福',
                'traditional' => '祝福',
                'part_of_speech' => 'verb',
                'meaning' => 'To bless / Blessing',
                'meaning_zh' => '祝福',
                'example_sentence' => '祝福你！',
                'example_translation' => 'Bless you!',
                'definition' => 'To bless, blessing, to wish well',
                'sentences' => ['___你。', '___的话。', '送___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '传统节日。',
                'example_translation' => 'Traditional festival.',
                'definition' => 'Tradition, traditional',
                'sentences' => ['___节日。', '___文化。', '___习俗。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 59,
                'word' => '习俗',
                'pinyin' => 'xí sú',
                'simplified' => '习俗',
                'traditional' => '習俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom',
                'meaning_zh' => '习俗',
                'example_sentence' => '春节的习俗。',
                'example_translation' => 'Spring Festival customs.',
                'definition' => 'Custom, tradition',
                'sentences' => ['___很多。', '传统___。', '___文化。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 60: Technology and Media (科技和媒体) - 20 words
        $techVocab = [
            [
                'topic_id' => 60,
                'word' => '科技',
                'pinyin' => 'kē jì',
                'simplified' => '科技',
                'traditional' => '科技',
                'part_of_speech' => 'noun',
                'meaning' => 'Technology / Science and technology',
                'meaning_zh' => '科技',
                'example_sentence' => '科技发展很快。',
                'example_translation' => 'Technology develops very fast.',
                'definition' => 'Technology, science and technology',
                'sentences' => ['___发展。', '___产品。', '___公司。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '网络',
                'pinyin' => 'wǎng luò',
                'simplified' => '网络',
                'traditional' => '網絡',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet / Network',
                'meaning_zh' => '网络',
                'example_sentence' => '我用网络学习。',
                'example_translation' => 'I use the internet to study.',
                'definition' => 'Internet, network',
                'sentences' => ['上___。', '___很快。', '___时代。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '网站',
                'pinyin' => 'wǎng zhàn',
                'simplified' => '网站',
                'traditional' => '網站',
                'part_of_speech' => 'noun',
                'meaning' => 'Website',
                'meaning_zh' => '网站',
                'example_sentence' => '这个网站很好用。',
                'example_translation' => 'This website is very useful.',
                'definition' => 'Website',
                'sentences' => ['打开___。', '___很多。', '___首页。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '软件',
                'pinyin' => 'ruǎn jiàn',
                'simplified' => '软件',
                'traditional' => '軟件',
                'part_of_speech' => 'noun',
                'meaning' => 'Software',
                'meaning_zh' => '软件',
                'example_sentence' => '下载软件。',
                'example_translation' => 'Download software.',
                'definition' => 'Software',
                'sentences' => ['下载___。', '___很好用。', '___开发。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '硬件',
                'pinyin' => 'yìng jiàn',
                'simplified' => '硬件',
                'traditional' => '硬件',
                'part_of_speech' => 'noun',
                'meaning' => 'Hardware',
                'meaning_zh' => '硬件',
                'example_sentence' => '电脑硬件。',
                'example_translation' => 'Computer hardware.',
                'definition' => 'Hardware',
                'sentences' => ['___设备。', '___升级。', '___配置。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '应用',
                'pinyin' => 'yìng yòng',
                'simplified' => '应用',
                'traditional' => '應用',
                'part_of_speech' => 'noun',
                'meaning' => 'Application / App',
                'meaning_zh' => '应用',
                'example_sentence' => '手机应用。',
                'example_translation' => 'Mobile application.',
                'definition' => 'Application, app, to apply',
                'sentences' => ['下载___。', '___很多。', '___商店。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '程序',
                'pinyin' => 'chéng xù',
                'simplified' => '程序',
                'traditional' => '程序',
                'part_of_speech' => 'noun',
                'meaning' => 'Program / Procedure',
                'meaning_zh' => '程序',
                'example_sentence' => '运行程序。',
                'example_translation' => 'Run the program.',
                'definition' => 'Program, procedure',
                'sentences' => ['___运行。', '___开发。', '___设计。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '下载',
                'pinyin' => 'xià zài',
                'simplified' => '下载',
                'traditional' => '下載',
                'part_of_speech' => 'verb',
                'meaning' => 'To download',
                'meaning_zh' => '下载',
                'example_sentence' => '下载文件。',
                'example_translation' => 'Download the file.',
                'definition' => 'To download',
                'sentences' => ['___软件。', '___文件。', '___完成。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '上传',
                'pinyin' => 'shàng chuán',
                'simplified' => '上传',
                'traditional' => '上傳',
                'part_of_speech' => 'verb',
                'meaning' => 'To upload',
                'meaning_zh' => '上传',
                'example_sentence' => '上传照片。',
                'example_translation' => 'Upload photos.',
                'definition' => 'To upload',
                'sentences' => ['___照片。', '___文件。', '___成功。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '搜索',
                'pinyin' => 'sōu suǒ',
                'simplified' => '搜索',
                'traditional' => '搜索',
                'part_of_speech' => 'verb',
                'meaning' => 'To search',
                'meaning_zh' => '搜索',
                'example_sentence' => '在网上搜索。',
                'example_translation' => 'Search online.',
                'definition' => 'To search',
                'sentences' => ['___信息。', '___引擎。', '___结果。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '浏览',
                'pinyin' => 'liú lǎn',
                'simplified' => '浏览',
                'traditional' => '瀏覽',
                'part_of_speech' => 'verb',
                'meaning' => 'To browse',
                'meaning_zh' => '浏览',
                'example_sentence' => '浏览网页。',
                'example_translation' => 'Browse the webpage.',
                'definition' => 'To browse',
                'sentences' => ['___网页。', '___器。', '___信息。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '聊天',
                'pinyin' => 'liáo tiān',
                'simplified' => '聊天',
                'traditional' => '聊天',
                'part_of_speech' => 'verb',
                'meaning' => 'To chat',
                'meaning_zh' => '聊天',
                'example_sentence' => '在网上聊天。',
                'example_translation' => 'Chat online.',
                'definition' => 'To chat',
                'sentences' => ['___软件。', '___工具。', '___记录。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '发送',
                'pinyin' => 'fā sòng',
                'simplified' => '发送',
                'traditional' => '發送',
                'part_of_speech' => 'verb',
                'meaning' => 'To send',
                'meaning_zh' => '发送',
                'example_sentence' => '发送消息。',
                'example_translation' => 'Send a message.',
                'definition' => 'To send, to dispatch',
                'sentences' => ['___消息。', '___文件。', '___邮件。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '接收',
                'pinyin' => 'jiē shōu',
                'simplified' => '接收',
                'traditional' => '接收',
                'part_of_speech' => 'verb',
                'meaning' => 'To receive',
                'meaning_zh' => '接收',
                'example_sentence' => '接收文件。',
                'example_translation' => 'Receive the file.',
                'definition' => 'To receive',
                'sentences' => ['___消息。', '___文件。', '___信号。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '分享',
                'pinyin' => 'fēn xiǎng',
                'simplified' => '分享',
                'traditional' => '分享',
                'part_of_speech' => 'verb',
                'meaning' => 'To share',
                'meaning_zh' => '分享',
                'example_sentence' => '分享照片。',
                'example_translation' => 'Share photos.',
                'definition' => 'To share',
                'sentences' => ['___照片。', '___链接。', '___经验。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '关注',
                'pinyin' => 'guān zhù',
                'simplified' => '关注',
                'traditional' => '關注',
                'part_of_speech' => 'verb',
                'meaning' => 'To follow / To pay attention to',
                'meaning_zh' => '关注',
                'example_sentence' => '关注新闻。',
                'example_translation' => 'Follow the news.',
                'definition' => 'To follow, to pay attention to',
                'sentences' => ['___我。', '___新闻。', '___热点。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '媒体',
                'pinyin' => 'méi tǐ',
                'simplified' => '媒体',
                'traditional' => '媒體',
                'part_of_speech' => 'noun',
                'meaning' => 'Media',
                'meaning_zh' => '媒体',
                'example_sentence' => '社交媒体。',
                'example_translation' => 'Social media.',
                'definition' => 'Media',
                'sentences' => ['___报道。', '___平台。', '社交___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '视频',
                'pinyin' => 'shì pín',
                'simplified' => '视频',
                'traditional' => '視頻',
                'part_of_speech' => 'noun',
                'meaning' => 'Video',
                'meaning_zh' => '视频',
                'example_sentence' => '看视频。',
                'example_translation' => 'Watch video.',
                'definition' => 'Video',
                'sentences' => ['看___。', '___网站。', '___通话。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '直播',
                'pinyin' => 'zhí bō',
                'simplified' => '直播',
                'traditional' => '直播',
                'part_of_speech' => 'verb',
                'meaning' => 'Live broadcast / To livestream',
                'meaning_zh' => '直播',
                'example_sentence' => '看直播。',
                'example_translation' => 'Watch the live broadcast.',
                'definition' => 'Live broadcast, to livestream',
                'sentences' => ['看___。', '___平台。', '___间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 60,
                'word' => '更新',
                'pinyin' => 'gēng xīn',
                'simplified' => '更新',
                'traditional' => '更新',
                'part_of_speech' => 'verb',
                'meaning' => 'To update',
                'meaning_zh' => '更新',
                'example_sentence' => '更新软件。',
                'example_translation' => 'Update the software.',
                'definition' => 'To update, to renew',
                'sentences' => ['___软件。', '___版本。', '___内容。'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($foodVocab, $festivalVocab, $techVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
