<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics18to21Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 50: Activities (活动) - 20 words
        $activitiesVocab = [
            [
                'topic_id' => 50,
                'word' => '活动',
                'pinyin' => 'huó dòng',
                'simplified' => '活动',
                'traditional' => '活動',
                'part_of_speech' => 'noun',
                'meaning' => 'Activity',
                'meaning_zh' => '活动',
                'example_sentence' => '我们有活动。',
                'example_translation' => 'We have an activity.',
                'definition' => 'Activity, event',
                'sentences' => ['有___。', '___很多。', '参加___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '比赛',
                'pinyin' => 'bǐ sài',
                'simplified' => '比赛',
                'traditional' => '比賽',
                'part_of_speech' => 'noun',
                'meaning' => 'Competition / Match',
                'meaning_zh' => '比赛',
                'example_sentence' => '我们有比赛。',
                'example_translation' => 'We have a competition.',
                'definition' => 'Competition, match, contest',
                'sentences' => ['___开始。', '参加___。', '___很激烈。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '表演',
                'pinyin' => 'biǎo yǎn',
                'simplified' => '表演',
                'traditional' => '表演',
                'part_of_speech' => 'verb',
                'meaning' => 'To perform / Performance',
                'meaning_zh' => '表演',
                'example_sentence' => '他表演节目。',
                'example_translation' => 'He performs a show.',
                'definition' => 'To perform, performance, show',
                'sentences' => ['___节目。', '___很精彩。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '练习',
                'pinyin' => 'liàn xí',
                'simplified' => '练习',
                'traditional' => '練習',
                'part_of_speech' => 'verb',
                'meaning' => 'To practice / Exercise',
                'meaning_zh' => '练习',
                'example_sentence' => '我练习汉语。',
                'example_translation' => 'I practice Chinese.',
                'definition' => 'To practice, to exercise, practice',
                'sentences' => ['___汉语。', '___题。', '___很重要。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '考试',
                'pinyin' => 'kǎo shì',
                'simplified' => '考试',
                'traditional' => '考試',
                'part_of_speech' => 'noun',
                'meaning' => 'Exam / Test',
                'meaning_zh' => '考试',
                'example_sentence' => '明天有考试。',
                'example_translation' => 'There is an exam tomorrow.',
                'definition' => 'Exam, test, examination',
                'sentences' => ['有___。', '___结束。', '准备___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '复习',
                'pinyin' => 'fù xí',
                'simplified' => '复习',
                'traditional' => '複習',
                'part_of_speech' => 'verb',
                'meaning' => 'To review / To revise',
                'meaning_zh' => '复习',
                'example_sentence' => '我复习功课。',
                'example_translation' => 'I review my lessons.',
                'definition' => 'To review, to revise',
                'sentences' => ['___功课。', '___了吗？', '___很重要。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '讨论',
                'pinyin' => 'tǎo lùn',
                'simplified' => '讨论',
                'traditional' => '討論',
                'part_of_speech' => 'verb',
                'meaning' => 'To discuss',
                'meaning_zh' => '讨论',
                'example_sentence' => '我们讨论问题。',
                'example_translation' => 'We discuss the problem.',
                'definition' => 'To discuss, discussion',
                'sentences' => ['___问题。', '___一下。', '___结果。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '庆祝',
                'pinyin' => 'qìng zhù',
                'simplified' => '庆祝',
                'traditional' => '慶祝',
                'part_of_speech' => 'verb',
                'meaning' => 'To celebrate',
                'meaning_zh' => '庆祝',
                'example_sentence' => '我们庆祝生日。',
                'example_translation' => 'We celebrate the birthday.',
                'definition' => 'To celebrate, celebration',
                'sentences' => ['___生日。', '___节日。', '___一下。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '邀请',
                'pinyin' => 'yāo qǐng',
                'simplified' => '邀请',
                'traditional' => '邀請',
                'part_of_speech' => 'verb',
                'meaning' => 'To invite',
                'meaning_zh' => '邀请',
                'example_sentence' => '我邀请你来。',
                'example_translation' => 'I invite you to come.',
                'definition' => 'To invite, invitation',
                'sentences' => ['___你。', '___朋友。', '___了吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '参观',
                'pinyin' => 'cān guān',
                'simplified' => '参观',
                'traditional' => '參觀',
                'part_of_speech' => 'verb',
                'meaning' => 'To visit (a place)',
                'meaning_zh' => '参观',
                'example_sentence' => '我们参观博物馆。',
                'example_translation' => 'We visit the museum.',
                'definition' => 'To visit, to look around',
                'sentences' => ['___博物馆。', '___学校。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '访问',
                'pinyin' => 'fǎng wèn',
                'simplified' => '访问',
                'traditional' => '訪問',
                'part_of_speech' => 'verb',
                'meaning' => 'To visit (formally)',
                'meaning_zh' => '访问',
                'example_sentence' => '我们访问公司。',
                'example_translation' => 'We visit the company.',
                'definition' => 'To visit, to call on, visit',
                'sentences' => ['___公司。', '___客户。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '拜访',
                'pinyin' => 'bài fǎng',
                'simplified' => '拜访',
                'traditional' => '拜訪',
                'part_of_speech' => 'verb',
                'meaning' => 'To visit (someone)',
                'meaning_zh' => '拜访',
                'example_sentence' => '我拜访老师。',
                'example_translation' => 'I visit the teacher.',
                'definition' => 'To visit, to pay a visit to',
                'sentences' => ['___老师。', '___朋友。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '约会',
                'pinyin' => 'yuē huì',
                'simplified' => '约会',
                'traditional' => '約會',
                'part_of_speech' => 'noun',
                'meaning' => 'Appointment / Date',
                'meaning_zh' => '约会',
                'example_sentence' => '我有约会。',
                'example_translation' => 'I have an appointment.',
                'definition' => 'Appointment, date, engagement',
                'sentences' => ['有___。', '___时间。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '聚会',
                'pinyin' => 'jù huì',
                'simplified' => '聚会',
                'traditional' => '聚會',
                'part_of_speech' => 'noun',
                'meaning' => 'Party / Get-together',
                'meaning_zh' => '聚会',
                'example_sentence' => '我们有聚会。',
                'example_translation' => 'We have a party.',
                'definition' => 'Party, get-together, gathering',
                'sentences' => ['有___。', '___很开心。', '参加___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '野餐',
                'pinyin' => 'yě cān',
                'simplified' => '野餐',
                'traditional' => '野餐',
                'part_of_speech' => 'noun',
                'meaning' => 'Picnic',
                'meaning_zh' => '野餐',
                'example_sentence' => '我们去野餐。',
                'example_translation' => 'We go for a picnic.',
                'definition' => 'Picnic',
                'sentences' => ['去___。', '___很有趣。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '购物',
                'pinyin' => 'gòu wù',
                'simplified' => '购物',
                'traditional' => '購物',
                'part_of_speech' => 'verb',
                'meaning' => 'To shop / Shopping',
                'meaning_zh' => '购物',
                'example_sentence' => '我去购物。',
                'example_translation' => 'I go shopping.',
                'definition' => 'To shop, shopping',
                'sentences' => ['去___。', '___中心。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '娱乐',
                'pinyin' => 'yú lè',
                'simplified' => '娱乐',
                'traditional' => '娛樂',
                'part_of_speech' => 'noun',
                'meaning' => 'Entertainment',
                'meaning_zh' => '娱乐',
                'example_sentence' => '娱乐活动很多。',
                'example_translation' => 'There are many entertainment activities.',
                'definition' => 'Entertainment, recreation',
                'sentences' => ['___活动。', '___很多。', '___场所。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '休闲',
                'pinyin' => 'xiū xián',
                'simplified' => '休闲',
                'traditional' => '休閒',
                'part_of_speech' => 'adjective',
                'meaning' => 'Leisure / Relaxation',
                'meaning_zh' => '休闲',
                'example_sentence' => '这是休闲时间。',
                'example_translation' => 'This is leisure time.',
                'definition' => 'Leisure, relaxation, free time',
                'sentences' => ['___时间。', '___活动。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '露营',
                'pinyin' => 'lù yíng',
                'simplified' => '露营',
                'traditional' => '露營',
                'part_of_speech' => 'verb',
                'meaning' => 'To camp / Camping',
                'meaning_zh' => '露营',
                'example_sentence' => '我们去露营。',
                'example_translation' => 'We go camping.',
                'definition' => 'To camp, camping',
                'sentences' => ['去___。', '___很有趣。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 50,
                'word' => '度假',
                'pinyin' => 'dù jià',
                'simplified' => '度假',
                'traditional' => '度假',
                'part_of_speech' => 'verb',
                'meaning' => 'To go on vacation',
                'meaning_zh' => '度假',
                'example_sentence' => '我去度假。',
                'example_translation' => 'I go on vacation.',
                'definition' => 'To go on vacation, to take a holiday',
                'sentences' => ['去___。', '___村。', '___吗？'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 51: Health (健康) - 20 words
        $healthVocab = [
            [
                'topic_id' => 51,
                'word' => '健康',
                'pinyin' => 'jiàn kāng',
                'simplified' => '健康',
                'traditional' => '健康',
                'part_of_speech' => 'adjective',
                'meaning' => 'Healthy / Health',
                'meaning_zh' => '健康',
                'example_sentence' => '我很健康。',
                'example_translation' => 'I am very healthy.',
                'definition' => 'Healthy, health',
                'sentences' => ['很___。', '___吗？', '___生活。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '生病',
                'pinyin' => 'shēng bìng',
                'simplified' => '生病',
                'traditional' => '生病',
                'part_of_speech' => 'verb',
                'meaning' => 'To be sick / To fall ill',
                'meaning_zh' => '生病',
                'example_sentence' => '我生病了。',
                'example_translation' => 'I am sick.',
                'definition' => 'To be sick, to fall ill',
                'sentences' => ['___了。', '___吗？', '___很难受。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '感冒',
                'pinyin' => 'gǎn mào',
                'simplified' => '感冒',
                'traditional' => '感冒',
                'part_of_speech' => 'verb',
                'meaning' => 'To catch a cold / Cold',
                'meaning_zh' => '感冒',
                'example_sentence' => '我感冒了。',
                'example_translation' => 'I caught a cold.',
                'definition' => 'To catch a cold, cold, flu',
                'sentences' => ['___了。', '___很难受。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '发烧',
                'pinyin' => 'fā shāo',
                'simplified' => '发烧',
                'traditional' => '發燒',
                'part_of_speech' => 'verb',
                'meaning' => 'To have a fever',
                'meaning_zh' => '发烧',
                'example_sentence' => '他发烧了。',
                'example_translation' => 'He has a fever.',
                'definition' => 'To have a fever',
                'sentences' => ['___了。', '___吗？', '___很难受。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '咳嗽',
                'pinyin' => 'ké sou',
                'simplified' => '咳嗽',
                'traditional' => '咳嗽',
                'part_of_speech' => 'verb',
                'meaning' => 'To cough',
                'meaning_zh' => '咳嗽',
                'example_sentence' => '我咳嗽了。',
                'example_translation' => 'I coughed.',
                'definition' => 'To cough, cough',
                'sentences' => ['___了。', '___吗？', '___很厉害。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '头疼',
                'pinyin' => 'tóu téng',
                'simplified' => '头疼',
                'traditional' => '頭疼',
                'part_of_speech' => 'verb',
                'meaning' => 'To have a headache',
                'meaning_zh' => '头疼',
                'example_sentence' => '我头疼。',
                'example_translation' => 'I have a headache.',
                'definition' => 'To have a headache, headache',
                'sentences' => ['___了。', '___吗？', '___很厉害。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '肚子疼',
                'pinyin' => 'dù zi téng',
                'simplified' => '肚子疼',
                'traditional' => '肚子疼',
                'part_of_speech' => 'verb',
                'meaning' => 'To have a stomachache',
                'meaning_zh' => '肚子疼',
                'example_sentence' => '我肚子疼。',
                'example_translation' => 'I have a stomachache.',
                'definition' => 'To have a stomachache',
                'sentences' => ['___了。', '___吗？', '___很厉害。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '牙疼',
                'pinyin' => 'yá téng',
                'simplified' => '牙疼',
                'traditional' => '牙疼',
                'part_of_speech' => 'verb',
                'meaning' => 'To have a toothache',
                'meaning_zh' => '牙疼',
                'example_sentence' => '我牙疼。',
                'example_translation' => 'I have a toothache.',
                'definition' => 'To have a toothache, toothache',
                'sentences' => ['___了。', '___吗？', '___很厉害。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '疼',
                'pinyin' => 'téng',
                'simplified' => '疼',
                'traditional' => '疼',
                'part_of_speech' => 'verb',
                'meaning' => 'To hurt / To ache',
                'meaning_zh' => '疼',
                'example_sentence' => '这里很疼。',
                'example_translation' => 'It hurts here.',
                'definition' => 'To hurt, to ache, painful',
                'sentences' => ['很___。', '___吗？', '___不___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '看病',
                'pinyin' => 'kàn bìng',
                'simplified' => '看病',
                'traditional' => '看病',
                'part_of_speech' => 'verb',
                'meaning' => 'To see a doctor',
                'meaning_zh' => '看病',
                'example_sentence' => '我去看病。',
                'example_translation' => 'I go to see a doctor.',
                'definition' => 'To see a doctor, to see a patient',
                'sentences' => ['去___。', '___了吗？', '___很重要。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '医生',
                'pinyin' => 'yī shēng',
                'simplified' => '医生',
                'traditional' => '醫生',
                'part_of_speech' => 'noun',
                'meaning' => 'Doctor',
                'meaning_zh' => '医生',
                'example_sentence' => '医生很好。',
                'example_translation' => 'The doctor is very good.',
                'definition' => 'Doctor, physician',
                'sentences' => ['___说。', '___检查。', '___很好。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '护士',
                'pinyin' => 'hù shi',
                'simplified' => '护士',
                'traditional' => '護士',
                'part_of_speech' => 'noun',
                'meaning' => 'Nurse',
                'meaning_zh' => '护士',
                'example_sentence' => '护士很温柔。',
                'example_translation' => 'The nurse is very gentle.',
                'definition' => 'Nurse',
                'sentences' => ['___很好。', '___帮助。', '___站。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '药',
                'pinyin' => 'yào',
                'simplified' => '药',
                'traditional' => '藥',
                'part_of_speech' => 'noun',
                'meaning' => 'Medicine / Drug',
                'meaning_zh' => '药',
                'example_sentence' => '我吃药。',
                'example_translation' => 'I take medicine.',
                'definition' => 'Medicine, drug, medication',
                'sentences' => ['吃___。', '___店。', '___很苦。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '打针',
                'pinyin' => 'dǎ zhēn',
                'simplified' => '打针',
                'traditional' => '打針',
                'part_of_speech' => 'verb',
                'meaning' => 'To give an injection',
                'meaning_zh' => '打针',
                'example_sentence' => '我要打针。',
                'example_translation' => 'I need to get an injection.',
                'definition' => 'To give an injection, to get a shot',
                'sentences' => ['___了。', '___吗？', '___很疼。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '治疗',
                'pinyin' => 'zhì liáo',
                'simplified' => '治疗',
                'traditional' => '治療',
                'part_of_speech' => 'verb',
                'meaning' => 'To treat / Treatment',
                'meaning_zh' => '治疗',
                'example_sentence' => '医生治疗病人。',
                'example_translation' => 'The doctor treats the patient.',
                'definition' => 'To treat, treatment, therapy',
                'sentences' => ['___病人。', '___方法。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '身体',
                'pinyin' => 'shēn tǐ',
                'simplified' => '身体',
                'traditional' => '身體',
                'part_of_speech' => 'noun',
                'meaning' => 'Body / Health',
                'meaning_zh' => '身体',
                'example_sentence' => '我的身体很好。',
                'example_translation' => 'My health is very good.',
                'definition' => 'Body, health, physique',
                'sentences' => ['___很好。', '___不舒服。', '___健康。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '注意',
                'pinyin' => 'zhù yì',
                'simplified' => '注意',
                'traditional' => '注意',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay attention / To be careful',
                'meaning_zh' => '注意',
                'example_sentence' => '请注意安全。',
                'example_translation' => 'Please pay attention to safety.',
                'definition' => 'To pay attention, to be careful, attention',
                'sentences' => ['___安全。', '___身体。', '___了吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '保护',
                'pinyin' => 'bǎo hù',
                'simplified' => '保护',
                'traditional' => '保護',
                'part_of_speech' => 'verb',
                'meaning' => 'To protect',
                'meaning_zh' => '保护',
                'example_sentence' => '我们保护环境。',
                'example_translation' => 'We protect the environment.',
                'definition' => 'To protect, protection',
                'sentences' => ['___环境。', '___身体。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '小心',
                'pinyin' => 'xiǎo xīn',
                'simplified' => '小心',
                'traditional' => '小心',
                'part_of_speech' => 'verb',
                'meaning' => 'To be careful',
                'meaning_zh' => '小心',
                'example_sentence' => '请小心。',
                'example_translation' => 'Please be careful.',
                'definition' => 'To be careful, careful',
                'sentences' => ['___一点。', '___吗？', '___！'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 51,
                'word' => '锻炼',
                'pinyin' => 'duàn liàn',
                'simplified' => '锻炼',
                'traditional' => '鍛煉',
                'part_of_speech' => 'verb',
                'meaning' => 'To exercise / To work out',
                'meaning_zh' => '锻炼',
                'example_sentence' => '我每天锻炼。',
                'example_translation' => 'I exercise every day.',
                'definition' => 'To exercise, to work out, to train',
                'sentences' => ['___身体。', '___吗？', '___很重要。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 52: Sports (体育运动) - 20 words
        $sportsVocab = [
            [
                'topic_id' => 52,
                'word' => '足球',
                'pinyin' => 'zú qiú',
                'simplified' => '足球',
                'traditional' => '足球',
                'part_of_speech' => 'noun',
                'meaning' => 'Football / Soccer',
                'meaning_zh' => '足球',
                'example_sentence' => '我喜欢足球。',
                'example_translation' => 'I like football.',
                'definition' => 'Football, soccer',
                'sentences' => ['踢___。', '___比赛。', '___队。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '篮球',
                'pinyin' => 'lán qiú',
                'simplified' => '篮球',
                'traditional' => '籃球',
                'part_of_speech' => 'noun',
                'meaning' => 'Basketball',
                'meaning_zh' => '篮球',
                'example_sentence' => '我打篮球。',
                'example_translation' => 'I play basketball.',
                'definition' => 'Basketball',
                'sentences' => ['打___。', '___比赛。', '___场。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '排球',
                'pinyin' => 'pái qiú',
                'simplified' => '排球',
                'traditional' => '排球',
                'part_of_speech' => 'noun',
                'meaning' => 'Volleyball',
                'meaning_zh' => '排球',
                'example_sentence' => '我打排球。',
                'example_translation' => 'I play volleyball.',
                'definition' => 'Volleyball',
                'sentences' => ['打___。', '___比赛。', '___队。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '乒乓球',
                'pinyin' => 'pīng pāng qiú',
                'simplified' => '乒乓球',
                'traditional' => '乒乓球',
                'part_of_speech' => 'noun',
                'meaning' => 'Table tennis / Ping pong',
                'meaning_zh' => '乒乓球',
                'example_sentence' => '我打乒乓球。',
                'example_translation' => 'I play table tennis.',
                'definition' => 'Table tennis, ping pong',
                'sentences' => ['打___。', '___比赛。', '___台。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '羽毛球',
                'pinyin' => 'yǔ máo qiú',
                'simplified' => '羽毛球',
                'traditional' => '羽毛球',
                'part_of_speech' => 'noun',
                'meaning' => 'Badminton',
                'meaning_zh' => '羽毛球',
                'example_sentence' => '我打羽毛球。',
                'example_translation' => 'I play badminton.',
                'definition' => 'Badminton',
                'sentences' => ['打___。', '___比赛。', '___拍。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '网球',
                'pinyin' => 'wǎng qiú',
                'simplified' => '网球',
                'traditional' => '網球',
                'part_of_speech' => 'noun',
                'meaning' => 'Tennis',
                'meaning_zh' => '网球',
                'example_sentence' => '我打网球。',
                'example_translation' => 'I play tennis.',
                'definition' => 'Tennis',
                'sentences' => ['打___。', '___比赛。', '___场。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '棒球',
                'pinyin' => 'bàng qiú',
                'simplified' => '棒球',
                'traditional' => '棒球',
                'part_of_speech' => 'noun',
                'meaning' => 'Baseball',
                'meaning_zh' => '棒球',
                'example_sentence' => '我打棒球。',
                'example_translation' => 'I play baseball.',
                'definition' => 'Baseball',
                'sentences' => ['打___。', '___比赛。', '___队。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '高尔夫球',
                'pinyin' => 'gāo ěr fū qiú',
                'simplified' => '高尔夫球',
                'traditional' => '高爾夫球',
                'part_of_speech' => 'noun',
                'meaning' => 'Golf',
                'meaning_zh' => '高尔夫球',
                'example_sentence' => '他打高尔夫球。',
                'example_translation' => 'He plays golf.',
                'definition' => 'Golf',
                'sentences' => ['打___。', '___场。', '___杆。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '跑步',
                'pinyin' => 'pǎo bù',
                'simplified' => '跑步',
                'traditional' => '跑步',
                'part_of_speech' => 'verb',
                'meaning' => 'To run / Running',
                'meaning_zh' => '跑步',
                'example_sentence' => '我每天跑步。',
                'example_translation' => 'I run every day.',
                'definition' => 'To run, running, jogging',
                'sentences' => ['___很好。', '去___。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '跳跃',
                'pinyin' => 'tiào yuè',
                'simplified' => '跳跃',
                'traditional' => '跳躍',
                'part_of_speech' => 'verb',
                'meaning' => 'To jump / To leap',
                'meaning_zh' => '跳跃',
                'example_sentence' => '他跳跃得很高。',
                'example_translation' => 'He jumps very high.',
                'definition' => 'To jump, to leap',
                'sentences' => ['___很高。', '___了。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '滑冰',
                'pinyin' => 'huá bīng',
                'simplified' => '滑冰',
                'traditional' => '滑冰',
                'part_of_speech' => 'verb',
                'meaning' => 'To ice skate / Ice skating',
                'meaning_zh' => '滑冰',
                'example_sentence' => '我喜欢滑冰。',
                'example_translation' => 'I like ice skating.',
                'definition' => 'To ice skate, ice skating',
                'sentences' => ['喜欢___。', '去___。', '___场。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '滑雪',
                'pinyin' => 'huá xuě',
                'simplified' => '滑雪',
                'traditional' => '滑雪',
                'part_of_speech' => 'verb',
                'meaning' => 'To ski / Skiing',
                'meaning_zh' => '滑雪',
                'example_sentence' => '我喜欢滑雪。',
                'example_translation' => 'I like skiing.',
                'definition' => 'To ski, skiing',
                'sentences' => ['喜欢___。', '去___。', '___场。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '骑马',
                'pinyin' => 'qí mǎ',
                'simplified' => '骑马',
                'traditional' => '騎馬',
                'part_of_speech' => 'verb',
                'meaning' => 'To ride a horse',
                'meaning_zh' => '骑马',
                'example_sentence' => '我会骑马。',
                'example_translation' => 'I can ride a horse.',
                'definition' => 'To ride a horse, horse riding',
                'sentences' => ['会___。', '去___。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '瑜伽',
                'pinyin' => 'yú jiā',
                'simplified' => '瑜伽',
                'traditional' => '瑜伽',
                'part_of_speech' => 'noun',
                'meaning' => 'Yoga',
                'meaning_zh' => '瑜伽',
                'example_sentence' => '我练瑜伽。',
                'example_translation' => 'I practice yoga.',
                'definition' => 'Yoga',
                'sentences' => ['练___。', '___课。', '___垫。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '武术',
                'pinyin' => 'wǔ shù',
                'simplified' => '武术',
                'traditional' => '武術',
                'part_of_speech' => 'noun',
                'meaning' => 'Martial arts',
                'meaning_zh' => '武术',
                'example_sentence' => '他学武术。',
                'example_translation' => 'He learns martial arts.',
                'definition' => 'Martial arts, wushu',
                'sentences' => ['学___。', '___很厉害。', '___馆。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '太极拳',
                'pinyin' => 'tài jí quán',
                'simplified' => '太极拳',
                'traditional' => '太極拳',
                'part_of_speech' => 'noun',
                'meaning' => 'Tai chi',
                'meaning_zh' => '太极拳',
                'example_sentence' => '爷爷打太极拳。',
                'example_translation' => 'Grandpa practices tai chi.',
                'definition' => 'Tai chi, taijiquan',
                'sentences' => ['打___。', '___很好。', '练___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '教练',
                'pinyin' => 'jiào liàn',
                'simplified' => '教练',
                'traditional' => '教練',
                'part_of_speech' => 'noun',
                'meaning' => 'Coach / Trainer',
                'meaning_zh' => '教练',
                'example_sentence' => '教练很专业。',
                'example_translation' => 'The coach is very professional.',
                'definition' => 'Coach, trainer, instructor',
                'sentences' => ['___很好。', '___教我们。', '___说。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '队员',
                'pinyin' => 'duì yuán',
                'simplified' => '队员',
                'traditional' => '隊員',
                'part_of_speech' => 'noun',
                'meaning' => 'Team member',
                'meaning_zh' => '队员',
                'example_sentence' => '队员们很努力。',
                'example_translation' => 'The team members work very hard.',
                'definition' => 'Team member, player',
                'sentences' => ['___们。', '___很多。', '___训练。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '冠军',
                'pinyin' => 'guàn jūn',
                'simplified' => '冠军',
                'traditional' => '冠軍',
                'part_of_speech' => 'noun',
                'meaning' => 'Champion',
                'meaning_zh' => '冠军',
                'example_sentence' => '他是冠军。',
                'example_translation' => 'He is the champion.',
                'definition' => 'Champion, championship',
                'sentences' => ['___了。', '___很厉害。', '___奖杯。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 52,
                'word' => '训练',
                'pinyin' => 'xùn liàn',
                'simplified' => '训练',
                'traditional' => '訓練',
                'part_of_speech' => 'verb',
                'meaning' => 'To train / Training',
                'meaning_zh' => '训练',
                'example_sentence' => '我们每天训练。',
                'example_translation' => 'We train every day.',
                'definition' => 'To train, training',
                'sentences' => ['___很努力。', '___了。', '___场。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 53: Measure Words (量词) - 20 words
        $measureWordsVocab = [
            [
                'topic_id' => 53,
                'word' => '个',
                'pinyin' => 'gè',
                'simplified' => '个',
                'traditional' => '個',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (general)',
                'meaning_zh' => '个',
                'example_sentence' => '一个人。',
                'example_translation' => 'One person.',
                'definition' => 'Measure word for people and general objects',
                'sentences' => ['一___人。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '本',
                'pinyin' => 'běn',
                'simplified' => '本',
                'traditional' => '本',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (books)',
                'meaning_zh' => '本',
                'example_sentence' => '一本书。',
                'example_translation' => 'One book.',
                'definition' => 'Measure word for books',
                'sentences' => ['一___书。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '张',
                'pinyin' => 'zhāng',
                'simplified' => '张',
                'traditional' => '張',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (flat objects)',
                'meaning_zh' => '张',
                'example_sentence' => '一张纸。',
                'example_translation' => 'One piece of paper.',
                'definition' => 'Measure word for flat objects',
                'sentences' => ['一___纸。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '把',
                'pinyin' => 'bǎ',
                'simplified' => '把',
                'traditional' => '把',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (objects with handles)',
                'meaning_zh' => '把',
                'example_sentence' => '一把椅子。',
                'example_translation' => 'One chair.',
                'definition' => 'Measure word for objects with handles',
                'sentences' => ['一___椅子。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '支',
                'pinyin' => 'zhī',
                'simplified' => '支',
                'traditional' => '支',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (pens, sticks)',
                'meaning_zh' => '支',
                'example_sentence' => '一支笔。',
                'example_translation' => 'One pen.',
                'definition' => 'Measure word for pens, sticks',
                'sentences' => ['一___笔。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '只',
                'pinyin' => 'zhī',
                'simplified' => '只',
                'traditional' => '隻',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (animals, one of a pair)',
                'meaning_zh' => '只',
                'example_sentence' => '一只猫。',
                'example_translation' => 'One cat.',
                'definition' => 'Measure word for animals',
                'sentences' => ['一___猫。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '条',
                'pinyin' => 'tiáo',
                'simplified' => '条',
                'traditional' => '條',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (long, thin objects)',
                'meaning_zh' => '条',
                'example_sentence' => '一条鱼。',
                'example_translation' => 'One fish.',
                'definition' => 'Measure word for long, thin objects',
                'sentences' => ['一___鱼。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '件',
                'pinyin' => 'jiàn',
                'simplified' => '件',
                'traditional' => '件',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (clothing, matters)',
                'meaning_zh' => '件',
                'example_sentence' => '一件衣服。',
                'example_translation' => 'One piece of clothing.',
                'definition' => 'Measure word for clothing and matters',
                'sentences' => ['一___衣服。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '双',
                'pinyin' => 'shuāng',
                'simplified' => '双',
                'traditional' => '雙',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (pairs)',
                'meaning_zh' => '双',
                'example_sentence' => '一双鞋。',
                'example_translation' => 'One pair of shoes.',
                'definition' => 'Measure word for pairs',
                'sentences' => ['一___鞋。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '杯',
                'pinyin' => 'bēi',
                'simplified' => '杯',
                'traditional' => '杯',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (cups)',
                'meaning_zh' => '杯',
                'example_sentence' => '一杯水。',
                'example_translation' => 'One cup of water.',
                'definition' => 'Measure word for cups',
                'sentences' => ['一___水。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '瓶',
                'pinyin' => 'píng',
                'simplified' => '瓶',
                'traditional' => '瓶',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (bottles)',
                'meaning_zh' => '瓶',
                'example_sentence' => '一瓶水。',
                'example_translation' => 'One bottle of water.',
                'definition' => 'Measure word for bottles',
                'sentences' => ['一___水。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '碗',
                'pinyin' => 'wǎn',
                'simplified' => '碗',
                'traditional' => '碗',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (bowls)',
                'meaning_zh' => '碗',
                'example_sentence' => '一碗饭。',
                'example_translation' => 'One bowl of rice.',
                'definition' => 'Measure word for bowls',
                'sentences' => ['一___饭。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '盘',
                'pinyin' => 'pán',
                'simplified' => '盘',
                'traditional' => '盤',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (plates, dishes)',
                'meaning_zh' => '盘',
                'example_sentence' => '一盘菜。',
                'example_translation' => 'One plate of food.',
                'definition' => 'Measure word for plates and dishes',
                'sentences' => ['一___菜。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '辆',
                'pinyin' => 'liàng',
                'simplified' => '辆',
                'traditional' => '輛',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (vehicles)',
                'meaning_zh' => '辆',
                'example_sentence' => '一辆车。',
                'example_translation' => 'One car.',
                'definition' => 'Measure word for vehicles',
                'sentences' => ['一___车。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '层',
                'pinyin' => 'céng',
                'simplified' => '层',
                'traditional' => '層',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (floors, layers)',
                'meaning_zh' => '层',
                'example_sentence' => '三层楼。',
                'example_translation' => 'Three floors.',
                'definition' => 'Measure word for floors and layers',
                'sentences' => ['一___楼。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '块',
                'pinyin' => 'kuài',
                'simplified' => '块',
                'traditional' => '塊',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (pieces, yuan)',
                'meaning_zh' => '块',
                'example_sentence' => '一块钱。',
                'example_translation' => 'One yuan.',
                'definition' => 'Measure word for pieces and yuan',
                'sentences' => ['一___钱。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '次',
                'pinyin' => 'cì',
                'simplified' => '次',
                'traditional' => '次',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (times, occurrences)',
                'meaning_zh' => '次',
                'example_sentence' => '一次。',
                'example_translation' => 'One time.',
                'definition' => 'Measure word for times and occurrences',
                'sentences' => ['一___。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '些',
                'pinyin' => 'xiē',
                'simplified' => '些',
                'traditional' => '些',
                'part_of_speech' => 'measure word',
                'meaning' => 'Some / A little',
                'meaning_zh' => '些',
                'example_sentence' => '一些东西。',
                'example_translation' => 'Some things.',
                'definition' => 'Some, a little, a few',
                'sentences' => ['一___。', '这___。', '那___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '点',
                'pinyin' => 'diǎn',
                'simplified' => '点',
                'traditional' => '點',
                'part_of_speech' => 'measure word',
                'meaning' => 'A little / O\'clock',
                'meaning_zh' => '点',
                'example_sentence' => '一点水。',
                'example_translation' => 'A little water.',
                'definition' => 'A little, o\'clock, point',
                'sentences' => ['一___。', '两___。', '___钟。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 53,
                'word' => '种',
                'pinyin' => 'zhǒng',
                'simplified' => '种',
                'traditional' => '種',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word (types, kinds)',
                'meaning_zh' => '种',
                'example_sentence' => '一种水果。',
                'example_translation' => 'One kind of fruit.',
                'definition' => 'Measure word for types and kinds',
                'sentences' => ['一___。', '两___。', '几___？'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($activitiesVocab, $healthVocab, $sportsVocab, $measureWordsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
