<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics8to10Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 40: Hobbies and Interests (爱好和兴趣) - 20 words
        $hobbiesVocab = [
            [
                'topic_id' => 40,
                'word' => '爱好',
                'pinyin' => 'ài hào',
                'simplified' => '爱好',
                'traditional' => '愛好',
                'part_of_speech' => 'noun',
                'meaning' => 'Hobby / Interest',
                'meaning_zh' => '爱好',
                'example_sentence' => '你的爱好是什么？',
                'example_translation' => 'What is your hobby?',
                'definition' => 'Hobby, interest, to like',
                'sentences' => ['你的___是什么？', '我的___。', '___很多。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '喜欢',
                'pinyin' => 'xǐ huan',
                'simplified' => '喜欢',
                'traditional' => '喜歡',
                'part_of_speech' => 'verb',
                'meaning' => 'To like',
                'meaning_zh' => '喜欢',
                'example_sentence' => '我喜欢音乐。',
                'example_translation' => 'I like music.',
                'definition' => 'To like, to be fond of',
                'sentences' => ['我___。', '___什么？', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '跳舞',
                'pinyin' => 'tiào wǔ',
                'simplified' => '跳舞',
                'traditional' => '跳舞',
                'part_of_speech' => 'verb',
                'meaning' => 'To dance',
                'meaning_zh' => '跳舞',
                'example_sentence' => '我喜欢跳舞。',
                'example_translation' => 'I like to dance.',
                'definition' => 'To dance',
                'sentences' => ['我喜欢___。', '___很开心。', '一起___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '唱歌',
                'pinyin' => 'chàng gē',
                'simplified' => '唱歌',
                'traditional' => '唱歌',
                'part_of_speech' => 'verb',
                'meaning' => 'To sing',
                'meaning_zh' => '唱歌',
                'example_sentence' => '她喜欢唱歌。',
                'example_translation' => 'She likes to sing.',
                'definition' => 'To sing',
                'sentences' => ['喜欢___。', '___很好听。', '一起___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '看书',
                'pinyin' => 'kàn shū',
                'simplified' => '看书',
                'traditional' => '看書',
                'part_of_speech' => 'verb',
                'meaning' => 'To read (books)',
                'meaning_zh' => '看书',
                'example_sentence' => '我喜欢看书。',
                'example_translation' => 'I like to read books.',
                'definition' => 'To read books',
                'sentences' => ['喜欢___。', '在图书馆___。', '___学习。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '运动',
                'pinyin' => 'yùn dòng',
                'simplified' => '运动',
                'traditional' => '運動',
                'part_of_speech' => 'noun',
                'meaning' => 'Sports / Exercise',
                'meaning_zh' => '运动',
                'example_sentence' => '我喜欢运动。',
                'example_translation' => 'I like sports.',
                'definition' => 'Sports, exercise, movement',
                'sentences' => ['喜欢___。', '___很健康。', '___鞋。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '旅游',
                'pinyin' => 'lǚ yóu',
                'simplified' => '旅游',
                'traditional' => '旅遊',
                'part_of_speech' => 'verb',
                'meaning' => 'To travel / To tour',
                'meaning_zh' => '旅游',
                'example_sentence' => '我喜欢旅游。',
                'example_translation' => 'I like to travel.',
                'definition' => 'To travel, to tour, tourism',
                'sentences' => ['喜欢___。', '去___。', '___很开心。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '游泳',
                'pinyin' => 'yóu yǒng',
                'simplified' => '游泳',
                'traditional' => '游泳',
                'part_of_speech' => 'verb',
                'meaning' => 'To swim',
                'meaning_zh' => '游泳',
                'example_sentence' => '我喜欢游泳。',
                'example_translation' => 'I like to swim.',
                'definition' => 'To swim, swimming',
                'sentences' => ['喜欢___。', '___池。', '去___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '踢足球',
                'pinyin' => 'tī zú qiú',
                'simplified' => '踢足球',
                'traditional' => '踢足球',
                'part_of_speech' => 'verb',
                'meaning' => 'To play football/soccer',
                'meaning_zh' => '踢足球',
                'example_sentence' => '他喜欢踢足球。',
                'example_translation' => 'He likes to play football.',
                'definition' => 'To play football, to play soccer',
                'sentences' => ['喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '打篮球',
                'pinyin' => 'dǎ lán qiú',
                'simplified' => '打篮球',
                'traditional' => '打籃球',
                'part_of_speech' => 'verb',
                'meaning' => 'To play basketball',
                'meaning_zh' => '打篮球',
                'example_sentence' => '我喜欢打篮球。',
                'example_translation' => 'I like to play basketball.',
                'definition' => 'To play basketball',
                'sentences' => ['喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '弹钢琴',
                'pinyin' => 'tán gāng qín',
                'simplified' => '弹钢琴',
                'traditional' => '彈鋼琴',
                'part_of_speech' => 'verb',
                'meaning' => 'To play the piano',
                'meaning_zh' => '弹钢琴',
                'example_sentence' => '她会弹钢琴。',
                'example_translation' => 'She can play the piano.',
                'definition' => 'To play the piano',
                'sentences' => ['会___。', '___很好听。', '学___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '画画',
                'pinyin' => 'huà huà',
                'simplified' => '画画',
                'traditional' => '畫畫',
                'part_of_speech' => 'verb',
                'meaning' => 'To draw / To paint',
                'meaning_zh' => '画画',
                'example_sentence' => '我喜欢画画。',
                'example_translation' => 'I like to draw.',
                'definition' => 'To draw, to paint',
                'sentences' => ['喜欢___。', '___很有趣。', '学___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '拍照',
                'pinyin' => 'pāi zhào',
                'simplified' => '拍照',
                'traditional' => '拍照',
                'part_of_speech' => 'verb',
                'meaning' => 'To take photos',
                'meaning_zh' => '拍照',
                'example_sentence' => '我喜欢拍照。',
                'example_translation' => 'I like to take photos.',
                'definition' => 'To take photos, to photograph',
                'sentences' => ['喜欢___。', '___留念。', '一起___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '听音乐',
                'pinyin' => 'tīng yīn yuè',
                'simplified' => '听音乐',
                'traditional' => '聽音樂',
                'part_of_speech' => 'verb',
                'meaning' => 'To listen to music',
                'meaning_zh' => '听音乐',
                'example_sentence' => '我喜欢听音乐。',
                'example_translation' => 'I like to listen to music.',
                'definition' => 'To listen to music',
                'sentences' => ['喜欢___。', '___很放松。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '看电影',
                'pinyin' => 'kàn diàn yǐng',
                'simplified' => '看电影',
                'traditional' => '看電影',
                'part_of_speech' => 'verb',
                'meaning' => 'To watch movies',
                'meaning_zh' => '看电影',
                'example_sentence' => '我喜欢看电影。',
                'example_translation' => 'I like to watch movies.',
                'definition' => 'To watch movies',
                'sentences' => ['喜欢___。', '___很有趣。', '一起___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '玩游戏',
                'pinyin' => 'wán yóu xì',
                'simplified' => '玩游戏',
                'traditional' => '玩遊戲',
                'part_of_speech' => 'verb',
                'meaning' => 'To play games',
                'meaning_zh' => '玩游戏',
                'example_sentence' => '他喜欢玩游戏。',
                'example_translation' => 'He likes to play games.',
                'definition' => 'To play games',
                'sentences' => ['喜欢___。', '___很有趣。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '做饭',
                'pinyin' => 'zuò fàn',
                'simplified' => '做饭',
                'traditional' => '做飯',
                'part_of_speech' => 'verb',
                'meaning' => 'To cook',
                'meaning_zh' => '做饭',
                'example_sentence' => '我喜欢做饭。',
                'example_translation' => 'I like to cook.',
                'definition' => 'To cook, to prepare meals',
                'sentences' => ['喜欢___。', '___吗？', '___很有趣。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '爬山',
                'pinyin' => 'pá shān',
                'simplified' => '爬山',
                'traditional' => '爬山',
                'part_of_speech' => 'verb',
                'meaning' => 'To climb mountains / To hike',
                'meaning_zh' => '爬山',
                'example_sentence' => '周末我们去爬山。',
                'example_translation' => 'We go hiking on weekends.',
                'definition' => 'To climb mountains, to hike',
                'sentences' => ['去___。', '___很累。', '___很有趣。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '散步',
                'pinyin' => 'sàn bù',
                'simplified' => '散步',
                'traditional' => '散步',
                'part_of_speech' => 'verb',
                'meaning' => 'To take a walk',
                'meaning_zh' => '散步',
                'example_sentence' => '晚上我喜欢散步。',
                'example_translation' => 'I like to take walks in the evening.',
                'definition' => 'To take a walk, to stroll',
                'sentences' => ['喜欢___。', '___很舒服。', '去___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 40,
                'word' => '钓鱼',
                'pinyin' => 'diào yú',
                'simplified' => '钓鱼',
                'traditional' => '釣魚',
                'part_of_speech' => 'verb',
                'meaning' => 'To fish / To go fishing',
                'meaning_zh' => '钓鱼',
                'example_sentence' => '我爸爸喜欢钓鱼。',
                'example_translation' => 'My dad likes to fish.',
                'definition' => 'To fish, to go fishing',
                'sentences' => ['喜欢___。', '去___。', '___很有趣。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 41: Friends and Relationships (朋友和关系) - 20 words
        $relationshipsVocab = [
            [
                'topic_id' => 41,
                'word' => '朋友',
                'pinyin' => 'péng you',
                'simplified' => '朋友',
                'traditional' => '朋友',
                'part_of_speech' => 'noun',
                'meaning' => 'Friend',
                'meaning_zh' => '朋友',
                'example_sentence' => '他是我的朋友。',
                'example_translation' => 'He is my friend.',
                'definition' => 'Friend',
                'sentences' => ['我的___。', '___们。', '好___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '同事',
                'pinyin' => 'tóng shì',
                'simplified' => '同事',
                'traditional' => '同事',
                'part_of_speech' => 'noun',
                'meaning' => 'Colleague / Coworker',
                'meaning_zh' => '同事',
                'example_sentence' => '他是我的同事。',
                'example_translation' => 'He is my colleague.',
                'definition' => 'Colleague, coworker',
                'sentences' => ['我的___。', '___们。', '___关系。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '邻居',
                'pinyin' => 'lín jū',
                'simplified' => '邻居',
                'traditional' => '鄰居',
                'part_of_speech' => 'noun',
                'meaning' => 'Neighbor',
                'meaning_zh' => '邻居',
                'example_sentence' => '我的邻居很友好。',
                'example_translation' => 'My neighbor is very friendly.',
                'definition' => 'Neighbor',
                'sentences' => ['我的___。', '___很好。', '___们。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '爱',
                'pinyin' => 'ài',
                'simplified' => '爱',
                'traditional' => '愛',
                'part_of_speech' => 'verb',
                'meaning' => 'To love',
                'meaning_zh' => '爱',
                'example_sentence' => '我爱我的家人。',
                'example_translation' => 'I love my family.',
                'definition' => 'To love, love',
                'sentences' => ['我___你。', '___家人。', '___情。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '喜欢',
                'pinyin' => 'xǐ huan',
                'simplified' => '喜欢',
                'traditional' => '喜歡',
                'part_of_speech' => 'verb',
                'meaning' => 'To like',
                'meaning_zh' => '喜欢',
                'example_sentence' => '我喜欢他。',
                'example_translation' => 'I like him.',
                'definition' => 'To like, to be fond of',
                'sentences' => ['我___。', '___什么？', '___你。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '认识',
                'pinyin' => 'rèn shi',
                'simplified' => '认识',
                'traditional' => '認識',
                'part_of_speech' => 'verb',
                'meaning' => 'To know / To recognize',
                'meaning_zh' => '认识',
                'example_sentence' => '我认识他。',
                'example_translation' => 'I know him.',
                'definition' => 'To know, to recognize, to meet',
                'sentences' => ['我___他。', '___吗？', '___你很高兴。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '介绍',
                'pinyin' => 'jiè shào',
                'simplified' => '介绍',
                'traditional' => '介紹',
                'part_of_speech' => 'verb',
                'meaning' => 'To introduce',
                'meaning_zh' => '介绍',
                'example_sentence' => '我介绍一下。',
                'example_translation' => 'Let me introduce.',
                'definition' => 'To introduce, introduction',
                'sentences' => ['___一下。', '___自己。', '___朋友。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '见面',
                'pinyin' => 'jiàn miàn',
                'simplified' => '见面',
                'traditional' => '見面',
                'part_of_speech' => 'verb',
                'meaning' => 'To meet',
                'meaning_zh' => '见面',
                'example_sentence' => '我们明天见面。',
                'example_translation' => 'We will meet tomorrow.',
                'definition' => 'To meet, to see each other',
                'sentences' => ['我们___。', '___吧。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '聊天',
                'pinyin' => 'liáo tiān',
                'simplified' => '聊天',
                'traditional' => '聊天',
                'part_of_speech' => 'verb',
                'meaning' => 'To chat',
                'meaning_zh' => '聊天',
                'example_sentence' => '我们一起聊天。',
                'example_translation' => 'We chat together.',
                'definition' => 'To chat, to talk',
                'sentences' => ['一起___。', '___很开心。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '帮助',
                'pinyin' => 'bāng zhù',
                'simplified' => '帮助',
                'traditional' => '幫助',
                'part_of_speech' => 'verb',
                'meaning' => 'To help',
                'meaning_zh' => '帮助',
                'example_sentence' => '我帮助你。',
                'example_translation' => 'I help you.',
                'definition' => 'To help, help, assistance',
                'sentences' => ['___你。', '___别人。', '需要___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '关心',
                'pinyin' => 'guān xīn',
                'simplified' => '关心',
                'traditional' => '關心',
                'part_of_speech' => 'verb',
                'meaning' => 'To care about / To be concerned',
                'meaning_zh' => '关心',
                'example_sentence' => '我很关心你。',
                'example_translation' => 'I care about you very much.',
                'definition' => 'To care about, to be concerned',
                'sentences' => ['___你。', '很___。', '___别人。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '相信',
                'pinyin' => 'xiāng xìn',
                'simplified' => '相信',
                'traditional' => '相信',
                'part_of_speech' => 'verb',
                'meaning' => 'To believe / To trust',
                'meaning_zh' => '相信',
                'example_sentence' => '我相信你。',
                'example_translation' => 'I believe you.',
                'definition' => 'To believe, to trust',
                'sentences' => ['我___你。', '___吗？', '___自己。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb',
                'meaning' => 'To understand',
                'meaning_zh' => '理解',
                'example_sentence' => '我理解你。',
                'example_translation' => 'I understand you.',
                'definition' => 'To understand, understanding',
                'sentences' => ['我___。', '___吗？', '___别人。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '关系',
                'pinyin' => 'guān xi',
                'simplified' => '关系',
                'traditional' => '關係',
                'part_of_speech' => 'noun',
                'meaning' => 'Relationship',
                'meaning_zh' => '关系',
                'example_sentence' => '我们的关系很好。',
                'example_translation' => 'Our relationship is very good.',
                'definition' => 'Relationship, connection',
                'sentences' => ['___很好。', '___不好。', '___怎么样？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '友好',
                'pinyin' => 'yǒu hǎo',
                'simplified' => '友好',
                'traditional' => '友好',
                'part_of_speech' => 'adjective',
                'meaning' => 'Friendly',
                'meaning_zh' => '友好',
                'example_sentence' => '他很友好。',
                'example_translation' => 'He is very friendly.',
                'definition' => 'Friendly, amicable',
                'sentences' => ['很___。', '___的人。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '热情',
                'pinyin' => 'rè qíng',
                'simplified' => '热情',
                'traditional' => '熱情',
                'part_of_speech' => 'adjective',
                'meaning' => 'Enthusiastic / Warm',
                'meaning_zh' => '热情',
                'example_sentence' => '他很热情。',
                'example_translation' => 'He is very enthusiastic.',
                'definition' => 'Enthusiastic, warm, passionate',
                'sentences' => ['很___。', '___的人。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '礼貌',
                'pinyin' => 'lǐ mào',
                'simplified' => '礼貌',
                'traditional' => '禮貌',
                'part_of_speech' => 'adjective',
                'meaning' => 'Polite',
                'meaning_zh' => '礼貌',
                'example_sentence' => '他很礼貌。',
                'example_translation' => 'He is very polite.',
                'definition' => 'Polite, courteous, manners',
                'sentences' => ['很___。', '___的人。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '诚实',
                'pinyin' => 'chéng shí',
                'simplified' => '诚实',
                'traditional' => '誠實',
                'part_of_speech' => 'adjective',
                'meaning' => 'Honest',
                'meaning_zh' => '诚实',
                'example_sentence' => '他很诚实。',
                'example_translation' => 'He is very honest.',
                'definition' => 'Honest, truthful',
                'sentences' => ['很___。', '___的人。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '善良',
                'pinyin' => 'shàn liáng',
                'simplified' => '善良',
                'traditional' => '善良',
                'part_of_speech' => 'adjective',
                'meaning' => 'Kind / Good-hearted',
                'meaning_zh' => '善良',
                'example_sentence' => '她很善良。',
                'example_translation' => 'She is very kind.',
                'definition' => 'Kind, good-hearted, kindhearted',
                'sentences' => ['很___。', '___的人。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 41,
                'word' => '努力',
                'pinyin' => 'nǔ lì',
                'simplified' => '努力',
                'traditional' => '努力',
                'part_of_speech' => 'adjective',
                'meaning' => 'Hardworking / To work hard',
                'meaning_zh' => '努力',
                'example_sentence' => '他很努力。',
                'example_translation' => 'He is very hardworking.',
                'definition' => 'Hardworking, to work hard, to strive',
                'sentences' => ['很___。', '___学习。', '___工作。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 42: At School or Work (在学校或工作) - 20 words
        $schoolWorkVocab = [
            [
                'topic_id' => 42,
                'word' => '上课',
                'pinyin' => 'shàng kè',
                'simplified' => '上课',
                'traditional' => '上課',
                'part_of_speech' => 'verb',
                'meaning' => 'To attend class / To have class',
                'meaning_zh' => '上课',
                'example_sentence' => '我们上课了。',
                'example_translation' => 'We are having class.',
                'definition' => 'To attend class, to have class',
                'sentences' => ['我们___。', '___时间。', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '下课',
                'pinyin' => 'xià kè',
                'simplified' => '下课',
                'traditional' => '下課',
                'part_of_speech' => 'verb',
                'meaning' => 'To finish class',
                'meaning_zh' => '下课',
                'example_sentence' => '下课了。',
                'example_translation' => 'Class is over.',
                'definition' => 'To finish class, class is over',
                'sentences' => ['___了。', '___以后。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '学习',
                'pinyin' => 'xué xí',
                'simplified' => '学习',
                'traditional' => '學習',
                'part_of_speech' => 'verb',
                'meaning' => 'To study / To learn',
                'meaning_zh' => '学习',
                'example_sentence' => '我在学习汉语。',
                'example_translation' => 'I am studying Chinese.',
                'definition' => 'To study, to learn',
                'sentences' => ['___汉语。', '___很努力。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '教',
                'pinyin' => 'jiāo',
                'simplified' => '教',
                'traditional' => '教',
                'part_of_speech' => 'verb',
                'meaning' => 'To teach',
                'meaning_zh' => '教',
                'example_sentence' => '老师教我们汉语。',
                'example_translation' => 'The teacher teaches us Chinese.',
                'definition' => 'To teach',
                'sentences' => ['___我们。', '___汉语。', '___书。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '老师',
                'pinyin' => 'lǎo shī',
                'simplified' => '老师',
                'traditional' => '老師',
                'part_of_speech' => 'noun',
                'meaning' => 'Teacher',
                'meaning_zh' => '老师',
                'example_sentence' => '我的老师很好。',
                'example_translation' => 'My teacher is very good.',
                'definition' => 'Teacher',
                'sentences' => ['我的___。', '___们。', '___教我们。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '学生',
                'pinyin' => 'xué sheng',
                'simplified' => '学生',
                'traditional' => '學生',
                'part_of_speech' => 'noun',
                'meaning' => 'Student',
                'meaning_zh' => '学生',
                'example_sentence' => '我是学生。',
                'example_translation' => 'I am a student.',
                'definition' => 'Student',
                'sentences' => ['我是___。', '___们。', '___学习。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '会议',
                'pinyin' => 'huì yì',
                'simplified' => '会议',
                'traditional' => '會議',
                'part_of_speech' => 'noun',
                'meaning' => 'Meeting / Conference',
                'meaning_zh' => '会议',
                'example_sentence' => '我们有会议。',
                'example_translation' => 'We have a meeting.',
                'definition' => 'Meeting, conference',
                'sentences' => ['有___。', '开___。', '___室。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '公司',
                'pinyin' => 'gōng sī',
                'simplified' => '公司',
                'traditional' => '公司',
                'part_of_speech' => 'noun',
                'meaning' => 'Company',
                'meaning_zh' => '公司',
                'example_sentence' => '我在公司工作。',
                'example_translation' => 'I work at a company.',
                'definition' => 'Company',
                'sentences' => ['在___工作。', '___很大。', '___员工。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '工作',
                'pinyin' => 'gōng zuò',
                'simplified' => '工作',
                'traditional' => '工作',
                'part_of_speech' => 'verb',
                'meaning' => 'To work / Work',
                'meaning_zh' => '工作',
                'example_sentence' => '我在工作。',
                'example_translation' => 'I am working.',
                'definition' => 'To work, work, job',
                'sentences' => ['我___。', '___很忙。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '经理',
                'pinyin' => 'jīng lǐ',
                'simplified' => '经理',
                'traditional' => '經理',
                'part_of_speech' => 'noun',
                'meaning' => 'Manager',
                'meaning_zh' => '经理',
                'example_sentence' => '他是经理。',
                'example_translation' => 'He is a manager.',
                'definition' => 'Manager',
                'sentences' => ['___好。', '___办公室。', '___说。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '职员',
                'pinyin' => 'zhí yuán',
                'simplified' => '职员',
                'traditional' => '職員',
                'part_of_speech' => 'noun',
                'meaning' => 'Staff / Employee',
                'meaning_zh' => '职员',
                'example_sentence' => '我是公司职员。',
                'example_translation' => 'I am a company employee.',
                'definition' => 'Staff, employee, office worker',
                'sentences' => ['公司___。', '___们。', '___工作。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '项目',
                'pinyin' => 'xiàng mù',
                'simplified' => '项目',
                'traditional' => '項目',
                'part_of_speech' => 'noun',
                'meaning' => 'Project',
                'meaning_zh' => '项目',
                'example_sentence' => '这个项目很重要。',
                'example_translation' => 'This project is very important.',
                'definition' => 'Project, program',
                'sentences' => ['这个___。', '___很重要。', '___经理。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '任务',
                'pinyin' => 'rèn wu',
                'simplified' => '任务',
                'traditional' => '任務',
                'part_of_speech' => 'noun',
                'meaning' => 'Task / Assignment',
                'meaning_zh' => '任务',
                'example_sentence' => '我有任务。',
                'example_translation' => 'I have a task.',
                'definition' => 'Task, assignment, mission',
                'sentences' => ['有___。', '完成___。', '___很多。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '完成',
                'pinyin' => 'wán chéng',
                'simplified' => '完成',
                'traditional' => '完成',
                'part_of_speech' => 'verb',
                'meaning' => 'To complete / To finish',
                'meaning_zh' => '完成',
                'example_sentence' => '我完成了作业。',
                'example_translation' => 'I finished my homework.',
                'definition' => 'To complete, to finish, to accomplish',
                'sentences' => ['___作业。', '___任务。', '___了吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '报告',
                'pinyin' => 'bào gào',
                'simplified' => '报告',
                'traditional' => '報告',
                'part_of_speech' => 'noun',
                'meaning' => 'Report',
                'meaning_zh' => '报告',
                'example_sentence' => '我写报告。',
                'example_translation' => 'I write a report.',
                'definition' => 'Report, to report',
                'sentences' => ['写___。', '___很长。', '___完成。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '文件',
                'pinyin' => 'wén jiàn',
                'simplified' => '文件',
                'traditional' => '文件',
                'part_of_speech' => 'noun',
                'meaning' => 'Document / File',
                'meaning_zh' => '文件',
                'example_sentence' => '我需要这个文件。',
                'example_translation' => 'I need this document.',
                'definition' => 'Document, file',
                'sentences' => ['这个___。', '___很重要。', '___夹。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '电脑',
                'pinyin' => 'diàn nǎo',
                'simplified' => '电脑',
                'traditional' => '電腦',
                'part_of_speech' => 'noun',
                'meaning' => 'Computer',
                'meaning_zh' => '电脑',
                'example_sentence' => '我用电脑工作。',
                'example_translation' => 'I use a computer for work.',
                'definition' => 'Computer',
                'sentences' => ['用___。', '___工作。', '___很重要。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '打印',
                'pinyin' => 'dǎ yìn',
                'simplified' => '打印',
                'traditional' => '打印',
                'part_of_speech' => 'verb',
                'meaning' => 'To print',
                'meaning_zh' => '打印',
                'example_sentence' => '我打印文件。',
                'example_translation' => 'I print documents.',
                'definition' => 'To print',
                'sentences' => ['___文件。', '___机。', '___了吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '复印',
                'pinyin' => 'fù yìn',
                'simplified' => '复印',
                'traditional' => '複印',
                'part_of_speech' => 'verb',
                'meaning' => 'To photocopy',
                'meaning_zh' => '复印',
                'example_sentence' => '我需要复印这个。',
                'example_translation' => 'I need to photocopy this.',
                'definition' => 'To photocopy, to duplicate',
                'sentences' => ['___文件。', '___机。', '需要___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 42,
                'word' => '发邮件',
                'pinyin' => 'fā yóu jiàn',
                'simplified' => '发邮件',
                'traditional' => '發郵件',
                'part_of_speech' => 'verb',
                'meaning' => 'To send email',
                'meaning_zh' => '发邮件',
                'example_sentence' => '我给他发邮件。',
                'example_translation' => 'I send him an email.',
                'definition' => 'To send email',
                'sentences' => ['给他___。', '___了吗？', '需要___。'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($hobbiesVocab, $relationshipsVocab, $schoolWorkVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
