<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics1to3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 33: Daily Routine (日常生活) - 20 words
        $dailyRoutineVocab = [
            [
                'topic_id' => 33,
                'word' => '起床',
                'pinyin' => 'qǐ chuáng',
                'simplified' => '起床',
                'traditional' => '起床',
                'part_of_speech' => 'verb',
                'meaning' => 'To get up / To get out of bed',
                'meaning_zh' => '起床',
                'example_sentence' => '我每天早上七点起床。',
                'example_translation' => 'I get up at 7 AM every day.',
                'definition' => 'To get up, to get out of bed',
                'sentences' => ['我每天___。', '早上___。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '洗澡',
                'pinyin' => 'xǐ zǎo',
                'simplified' => '洗澡',
                'traditional' => '洗澡',
                'part_of_speech' => 'verb',
                'meaning' => 'To take a bath / To shower',
                'meaning_zh' => '洗澡',
                'example_sentence' => '我每天晚上洗澡。',
                'example_translation' => 'I take a shower every evening.',
                'definition' => 'To take a bath, to shower',
                'sentences' => ['我晚上___。', '___很舒服。', '去___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '刷牙',
                'pinyin' => 'shuā yá',
                'simplified' => '刷牙',
                'traditional' => '刷牙',
                'part_of_speech' => 'verb',
                'meaning' => 'To brush teeth',
                'meaning_zh' => '刷牙',
                'example_sentence' => '我起床后刷牙。',
                'example_translation' => 'I brush my teeth after getting up.',
                'definition' => 'To brush teeth',
                'sentences' => ['早上___。', '___洗脸。', '记得___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '洗脸',
                'pinyin' => 'xǐ liǎn',
                'simplified' => '洗脸',
                'traditional' => '洗臉',
                'part_of_speech' => 'verb',
                'meaning' => 'To wash face',
                'meaning_zh' => '洗脸',
                'example_sentence' => '我每天早上洗脸。',
                'example_translation' => 'I wash my face every morning.',
                'definition' => 'To wash face',
                'sentences' => ['早上___。', '___刷牙。', '用水___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '穿衣服',
                'pinyin' => 'chuān yī fu',
                'simplified' => '穿衣服',
                'traditional' => '穿衣服',
                'part_of_speech' => 'verb',
                'meaning' => 'To get dressed / To put on clothes',
                'meaning_zh' => '穿衣服',
                'example_sentence' => '我起床后穿衣服。',
                'example_translation' => 'I get dressed after getting up.',
                'definition' => 'To get dressed, to put on clothes',
                'sentences' => ['起床后___。', '___出门。', '快___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '吃早饭',
                'pinyin' => 'chī zǎo fàn',
                'simplified' => '吃早饭',
                'traditional' => '吃早飯',
                'part_of_speech' => 'verb',
                'meaning' => 'To have breakfast',
                'meaning_zh' => '吃早饭',
                'example_sentence' => '我每天八点吃早饭。',
                'example_translation' => 'I have breakfast at 8 AM every day.',
                'definition' => 'To have breakfast, to eat breakfast',
                'sentences' => ['早上___。', '___很重要。', '在家___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '上班',
                'pinyin' => 'shàng bān',
                'simplified' => '上班',
                'traditional' => '上班',
                'part_of_speech' => 'verb',
                'meaning' => 'To go to work',
                'meaning_zh' => '上班',
                'example_sentence' => '我每天九点上班。',
                'example_translation' => 'I go to work at 9 AM every day.',
                'definition' => 'To go to work, to start work',
                'sentences' => ['我去___。', '___时间。', '___很忙。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '下班',
                'pinyin' => 'xià bān',
                'simplified' => '下班',
                'traditional' => '下班',
                'part_of_speech' => 'verb',
                'meaning' => 'To get off work / To finish work',
                'meaning_zh' => '下班',
                'example_sentence' => '我下午六点下班。',
                'example_translation' => 'I get off work at 6 PM.',
                'definition' => 'To get off work, to finish work',
                'sentences' => ['___回家。', '___时间。', '___以后。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '吃午饭',
                'pinyin' => 'chī wǔ fàn',
                'simplified' => '吃午饭',
                'traditional' => '吃午飯',
                'part_of_speech' => 'verb',
                'meaning' => 'To have lunch',
                'meaning_zh' => '吃午饭',
                'example_sentence' => '我们中午十二点吃午饭。',
                'example_translation' => 'We have lunch at 12 noon.',
                'definition' => 'To have lunch, to eat lunch',
                'sentences' => ['中午___。', '一起___。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '吃晚饭',
                'pinyin' => 'chī wǎn fàn',
                'simplified' => '吃晚饭',
                'traditional' => '吃晚飯',
                'part_of_speech' => 'verb',
                'meaning' => 'To have dinner',
                'meaning_zh' => '吃晚饭',
                'example_sentence' => '我们晚上七点吃晚饭。',
                'example_translation' => 'We have dinner at 7 PM.',
                'definition' => 'To have dinner, to eat dinner',
                'sentences' => ['晚上___。', '一起___。', '___了吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '做作业',
                'pinyin' => 'zuò zuò yè',
                'simplified' => '做作业',
                'traditional' => '做作業',
                'part_of_speech' => 'verb',
                'meaning' => 'To do homework',
                'meaning_zh' => '做作业',
                'example_sentence' => '我每天晚上做作业。',
                'example_translation' => 'I do homework every evening.',
                'definition' => 'To do homework',
                'sentences' => ['晚上___。', '___很多。', '先___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '看电视',
                'pinyin' => 'kàn diàn shì',
                'simplified' => '看电视',
                'traditional' => '看電視',
                'part_of_speech' => 'verb',
                'meaning' => 'To watch TV',
                'meaning_zh' => '看电视',
                'example_sentence' => '我晚上喜欢看电视。',
                'example_translation' => 'I like to watch TV in the evening.',
                'definition' => 'To watch television',
                'sentences' => ['晚上___。', '喜欢___。', '___节目。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '睡觉',
                'pinyin' => 'shuì jiào',
                'simplified' => '睡觉',
                'traditional' => '睡覺',
                'part_of_speech' => 'verb',
                'meaning' => 'To sleep / To go to bed',
                'meaning_zh' => '睡觉',
                'example_sentence' => '我晚上十一点睡觉。',
                'example_translation' => 'I go to bed at 11 PM.',
                'definition' => 'To sleep, to go to bed',
                'sentences' => ['晚上___。', '___时间。', '早点___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '休息',
                'pinyin' => 'xiū xi',
                'simplified' => '休息',
                'traditional' => '休息',
                'part_of_speech' => 'verb',
                'meaning' => 'To rest / To take a break',
                'meaning_zh' => '休息',
                'example_sentence' => '我累了，想休息一下。',
                'example_translation' => 'I am tired and want to rest a bit.',
                'definition' => 'To rest, to take a break',
                'sentences' => ['累了___。', '___一下。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '锻炼',
                'pinyin' => 'duàn liàn',
                'simplified' => '锻炼',
                'traditional' => '鍛煉',
                'part_of_speech' => 'verb',
                'meaning' => 'To exercise / To work out',
                'meaning_zh' => '锻炼',
                'example_sentence' => '我每天早上锻炼。',
                'example_translation' => 'I exercise every morning.',
                'definition' => 'To exercise, to work out',
                'sentences' => ['早上___。', '___身体。', '去___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '准备',
                'pinyin' => 'zhǔn bèi',
                'simplified' => '准备',
                'traditional' => '準備',
                'part_of_speech' => 'verb',
                'meaning' => 'To prepare / To get ready',
                'meaning_zh' => '准备',
                'example_sentence' => '我准备考试。',
                'example_translation' => 'I prepare for the exam.',
                'definition' => 'To prepare, to get ready',
                'sentences' => ['___考试。', '___好了。', '___出门。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '出门',
                'pinyin' => 'chū mén',
                'simplified' => '出门',
                'traditional' => '出門',
                'part_of_speech' => 'verb',
                'meaning' => 'To go out / To leave home',
                'meaning_zh' => '出门',
                'example_sentence' => '我八点出门。',
                'example_translation' => 'I leave home at 8 o\'clock.',
                'definition' => 'To go out, to leave home',
                'sentences' => ['早上___。', '___上班。', '___时间。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '回家',
                'pinyin' => 'huí jiā',
                'simplified' => '回家',
                'traditional' => '回家',
                'part_of_speech' => 'verb',
                'meaning' => 'To go home / To return home',
                'meaning_zh' => '回家',
                'example_sentence' => '我下班后回家。',
                'example_translation' => 'I go home after work.',
                'definition' => 'To go home, to return home',
                'sentences' => ['下班___。', '___吃饭。', '___休息。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '打扫',
                'pinyin' => 'dǎ sǎo',
                'simplified' => '打扫',
                'traditional' => '打掃',
                'part_of_speech' => 'verb',
                'meaning' => 'To clean / To sweep',
                'meaning_zh' => '打扫',
                'example_sentence' => '我周末打扫房间。',
                'example_translation' => 'I clean the room on weekends.',
                'definition' => 'To clean, to sweep, to tidy up',
                'sentences' => ['___房间。', '___卫生。', '___干净。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 33,
                'word' => '洗衣服',
                'pinyin' => 'xǐ yī fu',
                'simplified' => '洗衣服',
                'traditional' => '洗衣服',
                'part_of_speech' => 'verb',
                'meaning' => 'To wash clothes / To do laundry',
                'meaning_zh' => '洗衣服',
                'example_sentence' => '我周末洗衣服。',
                'example_translation' => 'I do laundry on weekends.',
                'definition' => 'To wash clothes, to do laundry',
                'sentences' => ['周末___。', '___很累。', '___机。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 34: At the Restaurant (在餐厅) - 20 words
        $restaurantVocab = [
            [
                'topic_id' => 34,
                'word' => '点菜',
                'pinyin' => 'diǎn cài',
                'simplified' => '点菜',
                'traditional' => '點菜',
                'part_of_speech' => 'verb',
                'meaning' => 'To order food',
                'meaning_zh' => '点菜',
                'example_sentence' => '我们点菜吧。',
                'example_translation' => 'Let\'s order food.',
                'definition' => 'To order food, to order dishes',
                'sentences' => ['我们___吧。', '___了吗？', '服务员___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '菜单',
                'pinyin' => 'cài dān',
                'simplified' => '菜单',
                'traditional' => '菜單',
                'part_of_speech' => 'noun',
                'meaning' => 'Menu',
                'meaning_zh' => '菜单',
                'example_sentence' => '请给我菜单。',
                'example_translation' => 'Please give me the menu.',
                'definition' => 'Menu',
                'sentences' => ['请给我___。', '看___。', '___上有什么？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '服务员',
                'pinyin' => 'fú wù yuán',
                'simplified' => '服务员',
                'traditional' => '服務員',
                'part_of_speech' => 'noun',
                'meaning' => 'Waiter / Waitress / Server',
                'meaning_zh' => '服务员',
                'example_sentence' => '服务员，买单！',
                'example_translation' => 'Waiter, check please!',
                'definition' => 'Waiter, waitress, server',
                'sentences' => ['___，买单！', '___很好。', '叫___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '米饭',
                'pinyin' => 'mǐ fàn',
                'simplified' => '米饭',
                'traditional' => '米飯',
                'part_of_speech' => 'noun',
                'meaning' => 'Cooked rice',
                'meaning_zh' => '米饭',
                'example_sentence' => '我要一碗米饭。',
                'example_translation' => 'I want a bowl of rice.',
                'definition' => 'Cooked rice, steamed rice',
                'sentences' => ['一碗___。', '吃___。', '___很好吃。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '筷子',
                'pinyin' => 'kuài zi',
                'simplified' => '筷子',
                'traditional' => '筷子',
                'part_of_speech' => 'noun',
                'meaning' => 'Chopsticks',
                'meaning_zh' => '筷子',
                'example_sentence' => '请给我一双筷子。',
                'example_translation' => 'Please give me a pair of chopsticks.',
                'definition' => 'Chopsticks',
                'sentences' => ['一双___。', '用___吃饭。', '___在哪儿？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '碗',
                'pinyin' => 'wǎn',
                'simplified' => '碗',
                'traditional' => '碗',
                'part_of_speech' => 'noun',
                'meaning' => 'Bowl',
                'meaning_zh' => '碗',
                'example_sentence' => '请给我一个碗。',
                'example_translation' => 'Please give me a bowl.',
                'definition' => 'Bowl',
                'sentences' => ['一个___。', '___很大。', '___里有饭。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '盘子',
                'pinyin' => 'pán zi',
                'simplified' => '盘子',
                'traditional' => '盤子',
                'part_of_speech' => 'noun',
                'meaning' => 'Plate / Dish',
                'meaning_zh' => '盘子',
                'example_sentence' => '请给我一个盘子。',
                'example_translation' => 'Please give me a plate.',
                'definition' => 'Plate, dish',
                'sentences' => ['一个___。', '___很干净。', '___里有菜。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '汤',
                'pinyin' => 'tāng',
                'simplified' => '汤',
                'traditional' => '湯',
                'part_of_speech' => 'noun',
                'meaning' => 'Soup',
                'meaning_zh' => '汤',
                'example_sentence' => '这个汤很好喝。',
                'example_translation' => 'This soup is delicious.',
                'definition' => 'Soup',
                'sentences' => ['___很好喝。', '喝___。', '一碗___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '味道',
                'pinyin' => 'wèi dao',
                'simplified' => '味道',
                'traditional' => '味道',
                'part_of_speech' => 'noun',
                'meaning' => 'Taste / Flavor',
                'meaning_zh' => '味道',
                'example_sentence' => '这个菜味道很好。',
                'example_translation' => 'This dish tastes very good.',
                'definition' => 'Taste, flavor',
                'sentences' => ['___很好。', '___怎么样？', '___不错。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '好吃',
                'pinyin' => 'hǎo chī',
                'simplified' => '好吃',
                'traditional' => '好吃',
                'part_of_speech' => 'adjective',
                'meaning' => 'Delicious / Tasty',
                'meaning_zh' => '好吃',
                'example_sentence' => '这个菜很好吃。',
                'example_translation' => 'This dish is very delicious.',
                'definition' => 'Delicious, tasty',
                'sentences' => ['很___。', '___吗？', '___的菜。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '饱',
                'pinyin' => 'bǎo',
                'simplified' => '饱',
                'traditional' => '飽',
                'part_of_speech' => 'adjective',
                'meaning' => 'Full (stomach)',
                'meaning_zh' => '饱',
                'example_sentence' => '我吃饱了。',
                'example_translation' => 'I am full.',
                'definition' => 'Full, satisfied (after eating)',
                'sentences' => ['我___了。', '吃___。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '饿',
                'pinyin' => 'è',
                'simplified' => '饿',
                'traditional' => '餓',
                'part_of_speech' => 'adjective',
                'meaning' => 'Hungry',
                'meaning_zh' => '饿',
                'example_sentence' => '我很饿。',
                'example_translation' => 'I am very hungry.',
                'definition' => 'Hungry',
                'sentences' => ['我很___。', '___了吗？', '___死了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '渴',
                'pinyin' => 'kě',
                'simplified' => '渴',
                'traditional' => '渴',
                'part_of_speech' => 'adjective',
                'meaning' => 'Thirsty',
                'meaning_zh' => '渴',
                'example_sentence' => '我很渴。',
                'example_translation' => 'I am very thirsty.',
                'definition' => 'Thirsty',
                'sentences' => ['我很___。', '___了吗？', '___死了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '买单',
                'pinyin' => 'mǎi dān',
                'simplified' => '买单',
                'traditional' => '買單',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay the bill / Check please',
                'meaning_zh' => '买单',
                'example_sentence' => '服务员，买单！',
                'example_translation' => 'Waiter, check please!',
                'definition' => 'To pay the bill, to settle the account',
                'sentences' => ['服务员，___！', '我来___。', '___了吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '便宜',
                'pinyin' => 'pián yi',
                'simplified' => '便宜',
                'traditional' => '便宜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cheap / Inexpensive',
                'meaning_zh' => '便宜',
                'example_sentence' => '这个饭店很便宜。',
                'example_translation' => 'This restaurant is very cheap.',
                'definition' => 'Cheap, inexpensive',
                'sentences' => ['很___。', '___吗？', '___的饭店。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '贵',
                'pinyin' => 'guì',
                'simplified' => '贵',
                'traditional' => '貴',
                'part_of_speech' => 'adjective',
                'meaning' => 'Expensive',
                'meaning_zh' => '贵',
                'example_sentence' => '这个饭店很贵。',
                'example_translation' => 'This restaurant is very expensive.',
                'definition' => 'Expensive, costly',
                'sentences' => ['很___。', '太___了。', '___不___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '辣',
                'pinyin' => 'là',
                'simplified' => '辣',
                'traditional' => '辣',
                'part_of_speech' => 'adjective',
                'meaning' => 'Spicy / Hot',
                'meaning_zh' => '辣',
                'example_sentence' => '这个菜很辣。',
                'example_translation' => 'This dish is very spicy.',
                'definition' => 'Spicy, hot (taste)',
                'sentences' => ['很___。', '___吗？', '太___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '甜',
                'pinyin' => 'tián',
                'simplified' => '甜',
                'traditional' => '甜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sweet',
                'meaning_zh' => '甜',
                'example_sentence' => '这个菜很甜。',
                'example_translation' => 'This dish is very sweet.',
                'definition' => 'Sweet',
                'sentences' => ['很___。', '___味道。', '___的菜。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '咸',
                'pinyin' => 'xián',
                'simplified' => '咸',
                'traditional' => '鹹',
                'part_of_speech' => 'adjective',
                'meaning' => 'Salty',
                'meaning_zh' => '咸',
                'example_sentence' => '这个汤太咸了。',
                'example_translation' => 'This soup is too salty.',
                'definition' => 'Salty',
                'sentences' => ['太___了。', '___吗？', '有点___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 34,
                'word' => '酸',
                'pinyin' => 'suān',
                'simplified' => '酸',
                'traditional' => '酸',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sour',
                'meaning_zh' => '酸',
                'example_sentence' => '这个菜有点酸。',
                'example_translation' => 'This dish is a bit sour.',
                'definition' => 'Sour, tart',
                'sentences' => ['有点___。', '___的味道。', '很___。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 35: Shopping (购物) - 20 words
        $shoppingVocab = [
            [
                'topic_id' => 35,
                'word' => '买',
                'pinyin' => 'mǎi',
                'simplified' => '买',
                'traditional' => '買',
                'part_of_speech' => 'verb',
                'meaning' => 'To buy',
                'meaning_zh' => '买',
                'example_sentence' => '我想买衣服。',
                'example_translation' => 'I want to buy clothes.',
                'definition' => 'To buy, to purchase',
                'sentences' => ['我想___。', '___东西。', '___了吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '卖',
                'pinyin' => 'mài',
                'simplified' => '卖',
                'traditional' => '賣',
                'part_of_speech' => 'verb',
                'meaning' => 'To sell',
                'meaning_zh' => '卖',
                'example_sentence' => '这个商店卖衣服。',
                'example_translation' => 'This shop sells clothes.',
                'definition' => 'To sell',
                'sentences' => ['___东西。', '___什么？', '___完了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '试',
                'pinyin' => 'shì',
                'simplified' => '试',
                'traditional' => '試',
                'part_of_speech' => 'verb',
                'meaning' => 'To try / To test',
                'meaning_zh' => '试',
                'example_sentence' => '我可以试一下吗？',
                'example_translation' => 'Can I try it on?',
                'definition' => 'To try, to test, to try on',
                'sentences' => ['我想___一下。', '______看。', '可以___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '件',
                'pinyin' => 'jiàn',
                'simplified' => '件',
                'traditional' => '件',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for clothes',
                'meaning_zh' => '件',
                'example_sentence' => '我买了一件衣服。',
                'example_translation' => 'I bought a piece of clothing.',
                'definition' => 'Measure word for clothes, matters',
                'sentences' => ['一___衣服。', '两___。', '___数。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '双',
                'pinyin' => 'shuāng',
                'simplified' => '双',
                'traditional' => '雙',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for pairs',
                'meaning_zh' => '双',
                'example_sentence' => '我买了一双鞋子。',
                'example_translation' => 'I bought a pair of shoes.',
                'definition' => 'Measure word for pairs (shoes, chopsticks, etc.)',
                'sentences' => ['一___鞋。', '___筷子。', '___手套。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '条',
                'pinyin' => 'tiáo',
                'simplified' => '条',
                'traditional' => '條',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for long things',
                'meaning_zh' => '条',
                'example_sentence' => '我买了一条裤子。',
                'example_translation' => 'I bought a pair of pants.',
                'definition' => 'Measure word for long, narrow things',
                'sentences' => ['一___裤子。', '___河。', '___鱼。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '颜色',
                'pinyin' => 'yán sè',
                'simplified' => '颜色',
                'traditional' => '顏色',
                'part_of_speech' => 'noun',
                'meaning' => 'Color',
                'meaning_zh' => '颜色',
                'example_sentence' => '你喜欢什么颜色？',
                'example_translation' => 'What color do you like?',
                'definition' => 'Color',
                'sentences' => ['什么___？', '___很好看。', '___不错。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '红',
                'pinyin' => 'hóng',
                'simplified' => '红',
                'traditional' => '紅',
                'part_of_speech' => 'adjective',
                'meaning' => 'Red',
                'meaning_zh' => '红',
                'example_sentence' => '我喜欢红色。',
                'example_translation' => 'I like red.',
                'definition' => 'Red (color)',
                'sentences' => ['___色。', '___的衣服。', '___花。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '黄',
                'pinyin' => 'huáng',
                'simplified' => '黄',
                'traditional' => '黃',
                'part_of_speech' => 'adjective',
                'meaning' => 'Yellow',
                'meaning_zh' => '黄',
                'example_sentence' => '黄色很好看。',
                'example_translation' => 'Yellow is very nice.',
                'definition' => 'Yellow (color)',
                'sentences' => ['___色。', '___的花。', '___河。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '蓝',
                'pinyin' => 'lán',
                'simplified' => '蓝',
                'traditional' => '藍',
                'part_of_speech' => 'adjective',
                'meaning' => 'Blue',
                'meaning_zh' => '蓝',
                'example_sentence' => '蓝色是我最喜欢的颜色。',
                'example_translation' => 'Blue is my favorite color.',
                'definition' => 'Blue (color)',
                'sentences' => ['___色。', '___天。', '___的衣服。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '绿',
                'pinyin' => 'lǜ',
                'simplified' => '绿',
                'traditional' => '綠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Green',
                'meaning_zh' => '绿',
                'example_sentence' => '这是绿色的树。',
                'example_translation' => 'This is a green tree.',
                'definition' => 'Green (color)',
                'sentences' => ['___色。', '___树。', '___茶。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '大小',
                'pinyin' => 'dà xiǎo',
                'simplified' => '大小',
                'traditional' => '大小',
                'part_of_speech' => 'noun',
                'meaning' => 'Size',
                'meaning_zh' => '大小',
                'example_sentence' => '这个大小合适吗？',
                'example_translation' => 'Is this size suitable?',
                'definition' => 'Size, dimension',
                'sentences' => ['___合适。', '什么___？', '___不对。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '合适',
                'pinyin' => 'hé shì',
                'simplified' => '合适',
                'traditional' => '合適',
                'part_of_speech' => 'adjective',
                'meaning' => 'Suitable / Appropriate',
                'meaning_zh' => '合适',
                'example_sentence' => '这件衣服很合适。',
                'example_translation' => 'This piece of clothing fits well.',
                'definition' => 'Suitable, appropriate, fitting',
                'sentences' => ['很___。', '___吗？', '___的衣服。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '打折',
                'pinyin' => 'dǎ zhé',
                'simplified' => '打折',
                'traditional' => '打折',
                'part_of_speech' => 'verb',
                'meaning' => 'To give a discount / On sale',
                'meaning_zh' => '打折',
                'example_sentence' => '这个商店打折。',
                'example_translation' => 'This shop is having a sale.',
                'definition' => 'To give a discount, on sale',
                'sentences' => ['___了。', '___吗？', '___商品。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '收银台',
                'pinyin' => 'shōu yín tái',
                'simplified' => '收银台',
                'traditional' => '收銀台',
                'part_of_speech' => 'noun',
                'meaning' => 'Cashier / Checkout counter',
                'meaning_zh' => '收银台',
                'example_sentence' => '收银台在哪里？',
                'example_translation' => 'Where is the cashier?',
                'definition' => 'Cashier, checkout counter',
                'sentences' => ['___在哪里？', '去___。', '___付钱。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '付钱',
                'pinyin' => 'fù qián',
                'simplified' => '付钱',
                'traditional' => '付錢',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay money',
                'meaning_zh' => '付钱',
                'example_sentence' => '我去付钱。',
                'example_translation' => 'I will go pay.',
                'definition' => 'To pay money',
                'sentences' => ['去___。', '___了吗？', '___方式。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '现金',
                'pinyin' => 'xiàn jīn',
                'simplified' => '现金',
                'traditional' => '現金',
                'part_of_speech' => 'noun',
                'meaning' => 'Cash',
                'meaning_zh' => '现金',
                'example_sentence' => '我用现金付。',
                'example_translation' => 'I pay with cash.',
                'definition' => 'Cash, ready money',
                'sentences' => ['用___付。', '___支付。', '有___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '刷卡',
                'pinyin' => 'shuā kǎ',
                'simplified' => '刷卡',
                'traditional' => '刷卡',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay by card / To swipe card',
                'meaning_zh' => '刷卡',
                'example_sentence' => '我可以刷卡吗？',
                'example_translation' => 'Can I pay by card?',
                'definition' => 'To pay by card, to swipe card',
                'sentences' => ['可以___吗？', '___支付。', '___机。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '找钱',
                'pinyin' => 'zhǎo qián',
                'simplified' => '找钱',
                'traditional' => '找錢',
                'part_of_speech' => 'verb',
                'meaning' => 'To give change',
                'meaning_zh' => '找钱',
                'example_sentence' => '请给我找钱。',
                'example_translation' => 'Please give me the change.',
                'definition' => 'To give change, to make change',
                'sentences' => ['给我___。', '___了吗？', '不用___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 35,
                'word' => '小票',
                'pinyin' => 'xiǎo piào',
                'simplified' => '小票',
                'traditional' => '小票',
                'part_of_speech' => 'noun',
                'meaning' => 'Receipt',
                'meaning_zh' => '小票',
                'example_sentence' => '请给我小票。',
                'example_translation' => 'Please give me the receipt.',
                'definition' => 'Receipt',
                'sentences' => ['给我___。', '___在哪里？', '保留___。'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($dailyRoutineVocab, $restaurantVocab, $shoppingVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
