<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics22to25Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 54: Time Expressions (时间表达) - 20 words
        $timeVocab = [
            [
                'topic_id' => 54,
                'word' => '时候',
                'pinyin' => 'shí hou',
                'simplified' => '时候',
                'traditional' => '時候',
                'part_of_speech' => 'noun',
                'meaning' => 'Time / Moment',
                'meaning_zh' => '时候',
                'example_sentence' => '什么时候？',
                'example_translation' => 'When? / What time?',
                'definition' => 'Time, moment, when',
                'sentences' => ['什么___？', '___到了。', '___很长。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '时间',
                'pinyin' => 'shí jiān',
                'simplified' => '时间',
                'traditional' => '時間',
                'part_of_speech' => 'noun',
                'meaning' => 'Time',
                'meaning_zh' => '时间',
                'example_sentence' => '我没有时间。',
                'example_translation' => 'I don\'t have time.',
                'definition' => 'Time, period',
                'sentences' => ['有___吗？', '___很长。', '___到了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '刚才',
                'pinyin' => 'gāng cái',
                'simplified' => '刚才',
                'traditional' => '剛才',
                'part_of_speech' => 'adverb',
                'meaning' => 'Just now',
                'meaning_zh' => '刚才',
                'example_sentence' => '刚才我看到他了。',
                'example_translation' => 'I saw him just now.',
                'definition' => 'Just now, a moment ago',
                'sentences' => ['___我看到。', '___说的。', '___很忙。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '刚',
                'pinyin' => 'gāng',
                'simplified' => '刚',
                'traditional' => '剛',
                'part_of_speech' => 'adverb',
                'meaning' => 'Just (recently)',
                'meaning_zh' => '刚',
                'example_sentence' => '我刚到。',
                'example_translation' => 'I just arrived.',
                'definition' => 'Just, just now, recently',
                'sentences' => ['___到。', '___开始。', '___来。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '马上',
                'pinyin' => 'mǎ shàng',
                'simplified' => '马上',
                'traditional' => '馬上',
                'part_of_speech' => 'adverb',
                'meaning' => 'Immediately / Right away',
                'meaning_zh' => '马上',
                'example_sentence' => '我马上来。',
                'example_translation' => 'I will come right away.',
                'definition' => 'Immediately, right away, at once',
                'sentences' => ['___来。', '___就好。', '___开始。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '立刻',
                'pinyin' => 'lì kè',
                'simplified' => '立刻',
                'traditional' => '立刻',
                'part_of_speech' => 'adverb',
                'meaning' => 'Immediately / At once',
                'meaning_zh' => '立刻',
                'example_sentence' => '请立刻去。',
                'example_translation' => 'Please go at once.',
                'definition' => 'Immediately, at once, instantly',
                'sentences' => ['___去。', '___来。', '___开始。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '立即',
                'pinyin' => 'lì jí',
                'simplified' => '立即',
                'traditional' => '立即',
                'part_of_speech' => 'adverb',
                'meaning' => 'Immediately / Promptly',
                'meaning_zh' => '立即',
                'example_sentence' => '请立即回复。',
                'example_translation' => 'Please reply immediately.',
                'definition' => 'Immediately, promptly',
                'sentences' => ['___回复。', '___行动。', '___处理。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '已经',
                'pinyin' => 'yǐ jīng',
                'simplified' => '已经',
                'traditional' => '已經',
                'part_of_speech' => 'adverb',
                'meaning' => 'Already',
                'meaning_zh' => '已经',
                'example_sentence' => '我已经到了。',
                'example_translation' => 'I have already arrived.',
                'definition' => 'Already',
                'sentences' => ['___到了。', '___完成了。', '___知道了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '正在',
                'pinyin' => 'zhèng zài',
                'simplified' => '正在',
                'traditional' => '正在',
                'part_of_speech' => 'adverb',
                'meaning' => 'In the process of',
                'meaning_zh' => '正在',
                'example_sentence' => '我正在学习。',
                'example_translation' => 'I am studying.',
                'definition' => 'In the process of, -ing',
                'sentences' => ['___学习。', '___工作。', '___吃饭。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '刚刚',
                'pinyin' => 'gāng gang',
                'simplified' => '刚刚',
                'traditional' => '剛剛',
                'part_of_speech' => 'adverb',
                'meaning' => 'Just / Just now',
                'meaning_zh' => '刚刚',
                'example_sentence' => '刚刚发生的。',
                'example_translation' => 'It just happened.',
                'definition' => 'Just, just now',
                'sentences' => ['___发生。', '___来的。', '___说的。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '将要',
                'pinyin' => 'jiāng yào',
                'simplified' => '将要',
                'traditional' => '將要',
                'part_of_speech' => 'adverb',
                'meaning' => 'Will / About to',
                'meaning_zh' => '将要',
                'example_sentence' => '我将要离开。',
                'example_translation' => 'I will leave.',
                'definition' => 'Will, about to, going to',
                'sentences' => ['___离开。', '___开始。', '___到来。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '快要',
                'pinyin' => 'kuài yào',
                'simplified' => '快要',
                'traditional' => '快要',
                'part_of_speech' => 'adverb',
                'meaning' => 'About to / Soon',
                'meaning_zh' => '快要',
                'example_sentence' => '快要下雨了。',
                'example_translation' => 'It is about to rain.',
                'definition' => 'About to, soon, nearly',
                'sentences' => ['___下雨了。', '___开始了。', '___到了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '曾经',
                'pinyin' => 'céng jīng',
                'simplified' => '曾经',
                'traditional' => '曾經',
                'part_of_speech' => 'adverb',
                'meaning' => 'Once / Ever',
                'meaning_zh' => '曾经',
                'example_sentence' => '我曾经去过。',
                'example_translation' => 'I once went there.',
                'definition' => 'Once, ever, formerly',
                'sentences' => ['___去过。', '___见过。', '___学过。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '从来',
                'pinyin' => 'cóng lái',
                'simplified' => '从来',
                'traditional' => '從來',
                'part_of_speech' => 'adverb',
                'meaning' => 'Always / Ever',
                'meaning_zh' => '从来',
                'example_sentence' => '我从来没去过。',
                'example_translation' => 'I have never been there.',
                'definition' => 'Always, ever (usually with 没/不)',
                'sentences' => ['___没有。', '___不。', '___都是。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '终于',
                'pinyin' => 'zhōng yú',
                'simplified' => '终于',
                'traditional' => '終於',
                'part_of_speech' => 'adverb',
                'meaning' => 'Finally / At last',
                'meaning_zh' => '终于',
                'example_sentence' => '我终于明白了。',
                'example_translation' => 'I finally understand.',
                'definition' => 'Finally, at last, eventually',
                'sentences' => ['___明白了。', '___完成了。', '___到了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '突然',
                'pinyin' => 'tū rán',
                'simplified' => '突然',
                'traditional' => '突然',
                'part_of_speech' => 'adverb',
                'meaning' => 'Suddenly',
                'meaning_zh' => '突然',
                'example_sentence' => '他突然来了。',
                'example_translation' => 'He suddenly came.',
                'definition' => 'Suddenly, all of a sudden',
                'sentences' => ['___来了。', '___发生。', '___下雨。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '渐渐',
                'pinyin' => 'jiàn jiàn',
                'simplified' => '渐渐',
                'traditional' => '漸漸',
                'part_of_speech' => 'adverb',
                'meaning' => 'Gradually',
                'meaning_zh' => '渐渐',
                'example_sentence' => '天渐渐黑了。',
                'example_translation' => 'It gradually got dark.',
                'definition' => 'Gradually, little by little',
                'sentences' => ['___明白。', '___变化。', '___好了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '慢慢',
                'pinyin' => 'màn màn',
                'simplified' => '慢慢',
                'traditional' => '慢慢',
                'part_of_speech' => 'adverb',
                'meaning' => 'Slowly',
                'meaning_zh' => '慢慢',
                'example_sentence' => '慢慢来。',
                'example_translation' => 'Take it slow.',
                'definition' => 'Slowly, gradually',
                'sentences' => ['___来。', '___走。', '___学。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '永远',
                'pinyin' => 'yǒng yuǎn',
                'simplified' => '永远',
                'traditional' => '永遠',
                'part_of_speech' => 'adverb',
                'meaning' => 'Forever / Always',
                'meaning_zh' => '永远',
                'example_sentence' => '我永远爱你。',
                'example_translation' => 'I will love you forever.',
                'definition' => 'Forever, always, eternally',
                'sentences' => ['___爱你。', '___记得。', '___不忘。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 54,
                'word' => '暂时',
                'pinyin' => 'zàn shí',
                'simplified' => '暂时',
                'traditional' => '暫時',
                'part_of_speech' => 'adverb',
                'meaning' => 'Temporarily / For now',
                'meaning_zh' => '暂时',
                'example_sentence' => '暂时没有。',
                'example_translation' => 'Temporarily not available.',
                'definition' => 'Temporarily, for the time being',
                'sentences' => ['___没有。', '___不行。', '___等等。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 55: Frequency (频率) - 20 words
        $frequencyVocab = [
            [
                'topic_id' => 55,
                'word' => '总是',
                'pinyin' => 'zǒng shì',
                'simplified' => '总是',
                'traditional' => '總是',
                'part_of_speech' => 'adverb',
                'meaning' => 'Always',
                'meaning_zh' => '总是',
                'example_sentence' => '他总是迟到。',
                'example_translation' => 'He is always late.',
                'definition' => 'Always, invariably',
                'sentences' => ['___迟到。', '___这样。', '___忘记。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '常常',
                'pinyin' => 'cháng cháng',
                'simplified' => '常常',
                'traditional' => '常常',
                'part_of_speech' => 'adverb',
                'meaning' => 'Often',
                'meaning_zh' => '常常',
                'example_sentence' => '我常常去。',
                'example_translation' => 'I often go.',
                'definition' => 'Often, frequently',
                'sentences' => ['___去。', '___来。', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '经常',
                'pinyin' => 'jīng cháng',
                'simplified' => '经常',
                'traditional' => '經常',
                'part_of_speech' => 'adverb',
                'meaning' => 'Often / Frequently',
                'meaning_zh' => '经常',
                'example_sentence' => '我经常运动。',
                'example_translation' => 'I often exercise.',
                'definition' => 'Often, frequently, regularly',
                'sentences' => ['___运动。', '___去。', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '通常',
                'pinyin' => 'tōng cháng',
                'simplified' => '通常',
                'traditional' => '通常',
                'part_of_speech' => 'adverb',
                'meaning' => 'Usually',
                'meaning_zh' => '通常',
                'example_sentence' => '我通常七点起床。',
                'example_translation' => 'I usually get up at seven.',
                'definition' => 'Usually, normally',
                'sentences' => ['___七点。', '___这样。', '___在家。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '平常',
                'pinyin' => 'píng cháng',
                'simplified' => '平常',
                'traditional' => '平常',
                'part_of_speech' => 'adverb',
                'meaning' => 'Ordinary / Usually',
                'meaning_zh' => '平常',
                'example_sentence' => '平常我不吃辣。',
                'example_translation' => 'Usually I don\'t eat spicy food.',
                'definition' => 'Ordinary, usual, usually',
                'sentences' => ['___不吃。', '___这样。', '___很忙。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '有时候',
                'pinyin' => 'yǒu shí hou',
                'simplified' => '有时候',
                'traditional' => '有時候',
                'part_of_speech' => 'adverb',
                'meaning' => 'Sometimes',
                'meaning_zh' => '有时候',
                'example_sentence' => '有时候我去。',
                'example_translation' => 'Sometimes I go.',
                'definition' => 'Sometimes, at times',
                'sentences' => ['___去。', '___来。', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '有时',
                'pinyin' => 'yǒu shí',
                'simplified' => '有时',
                'traditional' => '有時',
                'part_of_speech' => 'adverb',
                'meaning' => 'Sometimes',
                'meaning_zh' => '有时',
                'example_sentence' => '有时下雨。',
                'example_translation' => 'Sometimes it rains.',
                'definition' => 'Sometimes, occasionally',
                'sentences' => ['___下雨。', '___去。', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '偶尔',
                'pinyin' => 'ǒu ěr',
                'simplified' => '偶尔',
                'traditional' => '偶爾',
                'part_of_speech' => 'adverb',
                'meaning' => 'Occasionally',
                'meaning_zh' => '偶尔',
                'example_sentence' => '我偶尔去。',
                'example_translation' => 'I occasionally go.',
                'definition' => 'Occasionally, once in a while',
                'sentences' => ['___去。', '___来。', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '很少',
                'pinyin' => 'hěn shǎo',
                'simplified' => '很少',
                'traditional' => '很少',
                'part_of_speech' => 'adverb',
                'meaning' => 'Seldom / Rarely',
                'meaning_zh' => '很少',
                'example_sentence' => '我很少去。',
                'example_translation' => 'I seldom go.',
                'definition' => 'Seldom, rarely, very few',
                'sentences' => ['___去。', '___来。', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '从不',
                'pinyin' => 'cóng bù',
                'simplified' => '从不',
                'traditional' => '從不',
                'part_of_speech' => 'adverb',
                'meaning' => 'Never',
                'meaning_zh' => '从不',
                'example_sentence' => '我从不迟到。',
                'example_translation' => 'I never arrive late.',
                'definition' => 'Never',
                'sentences' => ['___迟到。', '___说谎。', '___放弃。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '每天',
                'pinyin' => 'měi tiān',
                'simplified' => '每天',
                'traditional' => '每天',
                'part_of_speech' => 'noun',
                'meaning' => 'Every day',
                'meaning_zh' => '每天',
                'example_sentence' => '我每天学习。',
                'example_translation' => 'I study every day.',
                'definition' => 'Every day, daily',
                'sentences' => ['___学习。', '___工作。', '___运动。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '每周',
                'pinyin' => 'měi zhōu',
                'simplified' => '每周',
                'traditional' => '每週',
                'part_of_speech' => 'noun',
                'meaning' => 'Every week',
                'meaning_zh' => '每周',
                'example_sentence' => '我每周去一次。',
                'example_translation' => 'I go once a week.',
                'definition' => 'Every week, weekly',
                'sentences' => ['___去。', '___一次。', '___开会。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '每月',
                'pinyin' => 'měi yuè',
                'simplified' => '每月',
                'traditional' => '每月',
                'part_of_speech' => 'noun',
                'meaning' => 'Every month',
                'meaning_zh' => '每月',
                'example_sentence' => '我每月去一次。',
                'example_translation' => 'I go once a month.',
                'definition' => 'Every month, monthly',
                'sentences' => ['___去。', '___一次。', '___工资。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '每年',
                'pinyin' => 'měi nián',
                'simplified' => '每年',
                'traditional' => '每年',
                'part_of_speech' => 'noun',
                'meaning' => 'Every year',
                'meaning_zh' => '每年',
                'example_sentence' => '我每年去一次。',
                'example_translation' => 'I go once a year.',
                'definition' => 'Every year, annual, yearly',
                'sentences' => ['___去。', '___一次。', '___旅游。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '一直',
                'pinyin' => 'yì zhí',
                'simplified' => '一直',
                'traditional' => '一直',
                'part_of_speech' => 'adverb',
                'meaning' => 'All along / Continuously',
                'meaning_zh' => '一直',
                'example_sentence' => '我一直在这里。',
                'example_translation' => 'I have been here all along.',
                'definition' => 'All along, continuously, straight',
                'sentences' => ['___在。', '___走。', '___等。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '不断',
                'pinyin' => 'bú duàn',
                'simplified' => '不断',
                'traditional' => '不斷',
                'part_of_speech' => 'adverb',
                'meaning' => 'Continuously / Constantly',
                'meaning_zh' => '不断',
                'example_sentence' => '不断学习。',
                'example_translation' => 'Keep learning continuously.',
                'definition' => 'Continuously, constantly, unceasingly',
                'sentences' => ['___学习。', '___进步。', '___努力。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '反复',
                'pinyin' => 'fǎn fù',
                'simplified' => '反复',
                'traditional' => '反復',
                'part_of_speech' => 'adverb',
                'meaning' => 'Repeatedly',
                'meaning_zh' => '反复',
                'example_sentence' => '反复练习。',
                'example_translation' => 'Practice repeatedly.',
                'definition' => 'Repeatedly, again and again',
                'sentences' => ['___练习。', '___说。', '___检查。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '再三',
                'pinyin' => 'zài sān',
                'simplified' => '再三',
                'traditional' => '再三',
                'part_of_speech' => 'adverb',
                'meaning' => 'Over and over again',
                'meaning_zh' => '再三',
                'example_sentence' => '我再三提醒你。',
                'example_translation' => 'I remind you again and again.',
                'definition' => 'Over and over again, repeatedly',
                'sentences' => ['___提醒。', '___考虑。', '___强调。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '几次',
                'pinyin' => 'jǐ cì',
                'simplified' => '几次',
                'traditional' => '幾次',
                'part_of_speech' => 'noun',
                'meaning' => 'Several times',
                'meaning_zh' => '几次',
                'example_sentence' => '我去过几次。',
                'example_translation' => 'I have been there several times.',
                'definition' => 'Several times, a few times',
                'sentences' => ['___了。', '___来。', '___去。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 55,
                'word' => '多次',
                'pinyin' => 'duō cì',
                'simplified' => '多次',
                'traditional' => '多次',
                'part_of_speech' => 'adverb',
                'meaning' => 'Many times',
                'meaning_zh' => '多次',
                'example_sentence' => '我去过多次。',
                'example_translation' => 'I have been there many times.',
                'definition' => 'Many times, repeatedly',
                'sentences' => ['___去过。', '___说过。', '___强调。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 56: Question Words (疑问词) - 20 words
        $questionVocab = [
            [
                'topic_id' => 56,
                'word' => '什么',
                'pinyin' => 'shén me',
                'simplified' => '什么',
                'traditional' => '什麼',
                'part_of_speech' => 'pronoun',
                'meaning' => 'What',
                'meaning_zh' => '什么',
                'example_sentence' => '这是什么？',
                'example_translation' => 'What is this?',
                'definition' => 'What',
                'sentences' => ['___？', '___时候？', '为___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '谁',
                'pinyin' => 'shéi',
                'simplified' => '谁',
                'traditional' => '誰',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Who',
                'meaning_zh' => '谁',
                'example_sentence' => '他是谁？',
                'example_translation' => 'Who is he?',
                'definition' => 'Who',
                'sentences' => ['___？', '___的？', '___来？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '哪',
                'pinyin' => 'nǎ',
                'simplified' => '哪',
                'traditional' => '哪',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Which',
                'meaning_zh' => '哪',
                'example_sentence' => '哪一个？',
                'example_translation' => 'Which one?',
                'definition' => 'Which',
                'sentences' => ['___一个？', '___里？', '___个？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '哪里',
                'pinyin' => 'nǎ li',
                'simplified' => '哪里',
                'traditional' => '哪裡',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Where',
                'meaning_zh' => '哪里',
                'example_sentence' => '你去哪里？',
                'example_translation' => 'Where are you going?',
                'definition' => 'Where',
                'sentences' => ['在___？', '去___？', '从___来？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '哪儿',
                'pinyin' => 'nǎr',
                'simplified' => '哪儿',
                'traditional' => '哪兒',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Where',
                'meaning_zh' => '哪儿',
                'example_sentence' => '你去哪儿？',
                'example_translation' => 'Where are you going?',
                'definition' => 'Where (colloquial)',
                'sentences' => ['在___？', '去___？', '从___来？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '怎么',
                'pinyin' => 'zěn me',
                'simplified' => '怎么',
                'traditional' => '怎麼',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How / Why',
                'meaning_zh' => '怎么',
                'example_sentence' => '怎么去？',
                'example_translation' => 'How to go?',
                'definition' => 'How, why',
                'sentences' => ['___去？', '___做？', '___了？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '怎么样',
                'pinyin' => 'zěn me yàng',
                'simplified' => '怎么样',
                'traditional' => '怎麼樣',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How / How about',
                'meaning_zh' => '怎么样',
                'example_sentence' => '天气怎么样？',
                'example_translation' => 'How is the weather?',
                'definition' => 'How, how about, what about',
                'sentences' => ['___？', '觉得___？', '天气___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '为什么',
                'pinyin' => 'wèi shén me',
                'simplified' => '为什么',
                'traditional' => '為什麼',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Why',
                'meaning_zh' => '为什么',
                'example_sentence' => '为什么不去？',
                'example_translation' => 'Why not go?',
                'definition' => 'Why',
                'sentences' => ['___？', '___不去？', '___这样？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '几',
                'pinyin' => 'jǐ',
                'simplified' => '几',
                'traditional' => '幾',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How many',
                'meaning_zh' => '几',
                'example_sentence' => '几点了？',
                'example_translation' => 'What time is it?',
                'definition' => 'How many, several',
                'sentences' => ['___点？', '___个？', '___岁？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '多少',
                'pinyin' => 'duō shao',
                'simplified' => '多少',
                'traditional' => '多少',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How many / How much',
                'meaning_zh' => '多少',
                'example_sentence' => '多少钱？',
                'example_translation' => 'How much money?',
                'definition' => 'How many, how much',
                'sentences' => ['___钱？', '___个？', '___岁？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '多',
                'pinyin' => 'duō',
                'simplified' => '多',
                'traditional' => '多',
                'part_of_speech' => 'adverb',
                'meaning' => 'How (degree)',
                'meaning_zh' => '多',
                'example_sentence' => '多大？',
                'example_translation' => 'How old?',
                'definition' => 'How (degree), many, much',
                'sentences' => ['___大？', '___高？', '___远？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '多久',
                'pinyin' => 'duō jiǔ',
                'simplified' => '多久',
                'traditional' => '多久',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How long',
                'meaning_zh' => '多久',
                'example_sentence' => '要多久？',
                'example_translation' => 'How long does it take?',
                'definition' => 'How long, how much time',
                'sentences' => ['___？', '要___？', '___了？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '多远',
                'pinyin' => 'duō yuǎn',
                'simplified' => '多远',
                'traditional' => '多遠',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How far',
                'meaning_zh' => '多远',
                'example_sentence' => '有多远？',
                'example_translation' => 'How far is it?',
                'definition' => 'How far',
                'sentences' => ['有___？', '___？', '离这里___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '多大',
                'pinyin' => 'duō dà',
                'simplified' => '多大',
                'traditional' => '多大',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How old / How big',
                'meaning_zh' => '多大',
                'example_sentence' => '你多大了？',
                'example_translation' => 'How old are you?',
                'definition' => 'How old, how big',
                'sentences' => ['___了？', '有___？', '___年纪？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '多高',
                'pinyin' => 'duō gāo',
                'simplified' => '多高',
                'traditional' => '多高',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How tall / How high',
                'meaning_zh' => '多高',
                'example_sentence' => '你多高？',
                'example_translation' => 'How tall are you?',
                'definition' => 'How tall, how high',
                'sentences' => ['你___？', '有___？', '___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '哪些',
                'pinyin' => 'nǎ xiē',
                'simplified' => '哪些',
                'traditional' => '哪些',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Which (plural)',
                'meaning_zh' => '哪些',
                'example_sentence' => '哪些人？',
                'example_translation' => 'Which people?',
                'definition' => 'Which (plural)',
                'sentences' => ['___人？', '___东西？', '___地方？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '如何',
                'pinyin' => 'rú hé',
                'simplified' => '如何',
                'traditional' => '如何',
                'part_of_speech' => 'pronoun',
                'meaning' => 'How',
                'meaning_zh' => '如何',
                'example_sentence' => '情况如何？',
                'example_translation' => 'How is the situation?',
                'definition' => 'How (formal)',
                'sentences' => ['___？', '情况___？', '觉得___？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '是否',
                'pinyin' => 'shì fǒu',
                'simplified' => '是否',
                'traditional' => '是否',
                'part_of_speech' => 'adverb',
                'meaning' => 'Whether or not',
                'meaning_zh' => '是否',
                'example_sentence' => '你是否同意？',
                'example_translation' => 'Do you agree or not?',
                'definition' => 'Whether or not',
                'sentences' => ['___同意？', '___可以？', '___知道？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '难道',
                'pinyin' => 'nán dào',
                'simplified' => '难道',
                'traditional' => '難道',
                'part_of_speech' => 'adverb',
                'meaning' => 'Could it be that',
                'meaning_zh' => '难道',
                'example_sentence' => '难道你不知道吗？',
                'example_translation' => 'Could it be that you don\'t know?',
                'definition' => 'Could it be that, is it possible that',
                'sentences' => ['___不知道？', '___是真的？', '___这样？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 56,
                'word' => '究竟',
                'pinyin' => 'jiū jìng',
                'simplified' => '究竟',
                'traditional' => '究竟',
                'part_of_speech' => 'adverb',
                'meaning' => 'Actually / After all',
                'meaning_zh' => '究竟',
                'example_sentence' => '究竟是什么？',
                'example_translation' => 'What actually is it?',
                'definition' => 'Actually, after all, in the end',
                'sentences' => ['___是什么？', '___怎么样？', '___为什么？'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 57: Common Adjectives (常用形容词) - 20 words
        $adjectivesVocab = [
            [
                'topic_id' => 57,
                'word' => '新',
                'pinyin' => 'xīn',
                'simplified' => '新',
                'traditional' => '新',
                'part_of_speech' => 'adjective',
                'meaning' => 'New',
                'meaning_zh' => '新',
                'example_sentence' => '这是新的。',
                'example_translation' => 'This is new.',
                'definition' => 'New',
                'sentences' => ['___的。', '___东西。', '___朋友。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '旧',
                'pinyin' => 'jiù',
                'simplified' => '旧',
                'traditional' => '舊',
                'part_of_speech' => 'adjective',
                'meaning' => 'Old / Used',
                'meaning_zh' => '旧',
                'example_sentence' => '这是旧的。',
                'example_translation' => 'This is old.',
                'definition' => 'Old, used, former',
                'sentences' => ['___的。', '___东西。', '___朋友。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '快',
                'pinyin' => 'kuài',
                'simplified' => '快',
                'traditional' => '快',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fast / Quick',
                'meaning_zh' => '快',
                'example_sentence' => '他跑得很快。',
                'example_translation' => 'He runs very fast.',
                'definition' => 'Fast, quick, soon',
                'sentences' => ['很___。', '___一点。', '___要到了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '慢',
                'pinyin' => 'màn',
                'simplified' => '慢',
                'traditional' => '慢',
                'part_of_speech' => 'adjective',
                'meaning' => 'Slow',
                'meaning_zh' => '慢',
                'example_sentence' => '他走得很慢。',
                'example_translation' => 'He walks very slowly.',
                'definition' => 'Slow',
                'sentences' => ['很___。', '___一点。', '___慢来。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '早',
                'pinyin' => 'zǎo',
                'simplified' => '早',
                'traditional' => '早',
                'part_of_speech' => 'adjective',
                'meaning' => 'Early',
                'meaning_zh' => '早',
                'example_sentence' => '我来得很早。',
                'example_translation' => 'I came very early.',
                'definition' => 'Early',
                'sentences' => ['很___。', '___上。', '___安。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '晚',
                'pinyin' => 'wǎn',
                'simplified' => '晚',
                'traditional' => '晚',
                'part_of_speech' => 'adjective',
                'meaning' => 'Late',
                'meaning_zh' => '晚',
                'example_sentence' => '他来得很晚。',
                'example_translation' => 'He came very late.',
                'definition' => 'Late, evening',
                'sentences' => ['很___。', '___上。', '___安。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '远',
                'pinyin' => 'yuǎn',
                'simplified' => '远',
                'traditional' => '遠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Far',
                'meaning_zh' => '远',
                'example_sentence' => '很远。',
                'example_translation' => 'Very far.',
                'definition' => 'Far, distant',
                'sentences' => ['很___。', '___不___？', '___处。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '近',
                'pinyin' => 'jìn',
                'simplified' => '近',
                'traditional' => '近',
                'part_of_speech' => 'adjective',
                'meaning' => 'Near / Close',
                'meaning_zh' => '近',
                'example_sentence' => '很近。',
                'example_translation' => 'Very near.',
                'definition' => 'Near, close',
                'sentences' => ['很___。', '___不___？', '___处。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '容易',
                'pinyin' => 'róng yì',
                'simplified' => '容易',
                'traditional' => '容易',
                'part_of_speech' => 'adjective',
                'meaning' => 'Easy',
                'meaning_zh' => '容易',
                'example_sentence' => '很容易。',
                'example_translation' => 'Very easy.',
                'definition' => 'Easy, simple',
                'sentences' => ['很___。', '___吗？', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '难',
                'pinyin' => 'nán',
                'simplified' => '难',
                'traditional' => '難',
                'part_of_speech' => 'adjective',
                'meaning' => 'Difficult',
                'meaning_zh' => '难',
                'example_sentence' => '很难。',
                'example_translation' => 'Very difficult.',
                'definition' => 'Difficult, hard',
                'sentences' => ['很___。', '___吗？', '___做。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '简单',
                'pinyin' => 'jiǎn dān',
                'simplified' => '简单',
                'traditional' => '簡單',
                'part_of_speech' => 'adjective',
                'meaning' => 'Simple',
                'meaning_zh' => '简单',
                'example_sentence' => '很简单。',
                'example_translation' => 'Very simple.',
                'definition' => 'Simple, easy',
                'sentences' => ['很___。', '___吗？', '___的。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '复杂',
                'pinyin' => 'fù zá',
                'simplified' => '复杂',
                'traditional' => '複雜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Complex / Complicated',
                'meaning_zh' => '复杂',
                'example_sentence' => '很复杂。',
                'example_translation' => 'Very complicated.',
                'definition' => 'Complex, complicated',
                'sentences' => ['很___。', '___吗？', '___的。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '重要',
                'pinyin' => 'zhòng yào',
                'simplified' => '重要',
                'traditional' => '重要',
                'part_of_speech' => 'adjective',
                'meaning' => 'Important',
                'meaning_zh' => '重要',
                'example_sentence' => '很重要。',
                'example_translation' => 'Very important.',
                'definition' => 'Important, significant',
                'sentences' => ['很___。', '___吗？', '___的事。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '特别',
                'pinyin' => 'tè bié',
                'simplified' => '特别',
                'traditional' => '特別',
                'part_of_speech' => 'adjective',
                'meaning' => 'Special / Especially',
                'meaning_zh' => '特别',
                'example_sentence' => '特别好。',
                'example_translation' => 'Especially good.',
                'definition' => 'Special, especially, particularly',
                'sentences' => ['___好。', '___的。', '___喜欢。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '普通',
                'pinyin' => 'pǔ tōng',
                'simplified' => '普通',
                'traditional' => '普通',
                'part_of_speech' => 'adjective',
                'meaning' => 'Ordinary / Common',
                'meaning_zh' => '普通',
                'example_sentence' => '很普通。',
                'example_translation' => 'Very ordinary.',
                'definition' => 'Ordinary, common, average',
                'sentences' => ['很___。', '___的。', '___人。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '正确',
                'pinyin' => 'zhèng què',
                'simplified' => '正确',
                'traditional' => '正確',
                'part_of_speech' => 'adjective',
                'meaning' => 'Correct / Right',
                'meaning_zh' => '正确',
                'example_sentence' => '这是正确的。',
                'example_translation' => 'This is correct.',
                'definition' => 'Correct, right, accurate',
                'sentences' => ['___的。', '___吗？', '___答案。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '错误',
                'pinyin' => 'cuò wù',
                'simplified' => '错误',
                'traditional' => '錯誤',
                'part_of_speech' => 'adjective',
                'meaning' => 'Wrong / Incorrect',
                'meaning_zh' => '错误',
                'example_sentence' => '这是错误的。',
                'example_translation' => 'This is wrong.',
                'definition' => 'Wrong, incorrect, error, mistake',
                'sentences' => ['___的。', '___吗？', '___了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '清楚',
                'pinyin' => 'qīng chu',
                'simplified' => '清楚',
                'traditional' => '清楚',
                'part_of_speech' => 'adjective',
                'meaning' => 'Clear',
                'meaning_zh' => '清楚',
                'example_sentence' => '说得很清楚。',
                'example_translation' => 'Said very clearly.',
                'definition' => 'Clear, distinct',
                'sentences' => ['很___。', '___吗？', '___地说。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '明白',
                'pinyin' => 'míng bai',
                'simplified' => '明白',
                'traditional' => '明白',
                'part_of_speech' => 'adjective',
                'meaning' => 'Clear / To understand',
                'meaning_zh' => '明白',
                'example_sentence' => '我明白了。',
                'example_translation' => 'I understand.',
                'definition' => 'Clear, to understand',
                'sentences' => ['___了。', '___吗？', '___的。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 57,
                'word' => '真',
                'pinyin' => 'zhēn',
                'simplified' => '真',
                'traditional' => '真',
                'part_of_speech' => 'adjective',
                'meaning' => 'Real / True / Really',
                'meaning_zh' => '真',
                'example_sentence' => '真好。',
                'example_translation' => 'Really good.',
                'definition' => 'Real, true, really, truly',
                'sentences' => ['___好。', '___的吗？', '___是。'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($timeVocab, $frequencyVocab, $questionVocab, $adjectivesVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
