<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk2Topics11to13Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 43: Places in the City (城市的地方) - 20 words
        $cityPlacesVocab = [
            [
                'topic_id' => 43,
                'word' => '银行',
                'pinyin' => 'yín háng',
                'simplified' => '银行',
                'traditional' => '銀行',
                'part_of_speech' => 'noun',
                'meaning' => 'Bank',
                'meaning_zh' => '银行',
                'example_sentence' => '我去银行。',
                'example_translation' => 'I go to the bank.',
                'definition' => 'Bank',
                'sentences' => ['去___。', '___在哪里？', '___卡。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '邮局',
                'pinyin' => 'yóu jú',
                'simplified' => '邮局',
                'traditional' => '郵局',
                'part_of_speech' => 'noun',
                'meaning' => 'Post office',
                'meaning_zh' => '邮局',
                'example_sentence' => '邮局在哪里？',
                'example_translation' => 'Where is the post office?',
                'definition' => 'Post office',
                'sentences' => ['___在哪里？', '去___。', '___寄信。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '医院',
                'pinyin' => 'yī yuàn',
                'simplified' => '医院',
                'traditional' => '醫院',
                'part_of_speech' => 'noun',
                'meaning' => 'Hospital',
                'meaning_zh' => '医院',
                'example_sentence' => '我去医院。',
                'example_translation' => 'I go to the hospital.',
                'definition' => 'Hospital',
                'sentences' => ['去___。', '___看病。', '___在哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '超市',
                'pinyin' => 'chāo shì',
                'simplified' => '超市',
                'traditional' => '超市',
                'part_of_speech' => 'noun',
                'meaning' => 'Supermarket',
                'meaning_zh' => '超市',
                'example_sentence' => '我去超市买东西。',
                'example_translation' => 'I go to the supermarket to buy things.',
                'definition' => 'Supermarket',
                'sentences' => ['去___。', '___买东西。', '___在哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '商店',
                'pinyin' => 'shāng diàn',
                'simplified' => '商店',
                'traditional' => '商店',
                'part_of_speech' => 'noun',
                'meaning' => 'Shop / Store',
                'meaning_zh' => '商店',
                'example_sentence' => '这是一个商店。',
                'example_translation' => 'This is a shop.',
                'definition' => 'Shop, store',
                'sentences' => ['___在哪里？', '去___。', '___买东西。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '图书馆',
                'pinyin' => 'tú shū guǎn',
                'simplified' => '图书馆',
                'traditional' => '圖書館',
                'part_of_speech' => 'noun',
                'meaning' => 'Library',
                'meaning_zh' => '图书馆',
                'example_sentence' => '我在图书馆看书。',
                'example_translation' => 'I read in the library.',
                'definition' => 'Library',
                'sentences' => ['在___看书。', '去___。', '___很安静。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '公园',
                'pinyin' => 'gōng yuán',
                'simplified' => '公园',
                'traditional' => '公園',
                'part_of_speech' => 'noun',
                'meaning' => 'Park',
                'meaning_zh' => '公园',
                'example_sentence' => '我们去公园。',
                'example_translation' => 'We go to the park.',
                'definition' => 'Park, public garden',
                'sentences' => ['去___。', '___很大。', '___散步。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '电影院',
                'pinyin' => 'diàn yǐng yuàn',
                'simplified' => '电影院',
                'traditional' => '電影院',
                'part_of_speech' => 'noun',
                'meaning' => 'Cinema / Movie theater',
                'meaning_zh' => '电影院',
                'example_sentence' => '我们去电影院。',
                'example_translation' => 'We go to the cinema.',
                'definition' => 'Cinema, movie theater',
                'sentences' => ['去___。', '___看电影。', '___在哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '饭店',
                'pinyin' => 'fàn diàn',
                'simplified' => '饭店',
                'traditional' => '飯店',
                'part_of_speech' => 'noun',
                'meaning' => 'Restaurant / Hotel',
                'meaning_zh' => '饭店',
                'example_sentence' => '我们去饭店吃饭。',
                'example_translation' => 'We go to the restaurant to eat.',
                'definition' => 'Restaurant, hotel',
                'sentences' => ['去___。', '___吃饭。', '___很好。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '咖啡馆',
                'pinyin' => 'kā fēi guǎn',
                'simplified' => '咖啡馆',
                'traditional' => '咖啡館',
                'part_of_speech' => 'noun',
                'meaning' => 'Cafe / Coffee shop',
                'meaning_zh' => '咖啡馆',
                'example_sentence' => '我们在咖啡馆见面。',
                'example_translation' => 'We meet at the cafe.',
                'definition' => 'Cafe, coffee shop',
                'sentences' => ['去___。', '在___。', '___喝咖啡。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '机场',
                'pinyin' => 'jī chǎng',
                'simplified' => '机场',
                'traditional' => '機場',
                'part_of_speech' => 'noun',
                'meaning' => 'Airport',
                'meaning_zh' => '机场',
                'example_sentence' => '我去机场。',
                'example_translation' => 'I go to the airport.',
                'definition' => 'Airport',
                'sentences' => ['去___。', '___很大。', '___在哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '火车站',
                'pinyin' => 'huǒ chē zhàn',
                'simplified' => '火车站',
                'traditional' => '火車站',
                'part_of_speech' => 'noun',
                'meaning' => 'Train station',
                'meaning_zh' => '火车站',
                'example_sentence' => '我在火车站。',
                'example_translation' => 'I am at the train station.',
                'definition' => 'Train station, railway station',
                'sentences' => ['在___。', '去___。', '___在哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '学校',
                'pinyin' => 'xué xiào',
                'simplified' => '学校',
                'traditional' => '學校',
                'part_of_speech' => 'noun',
                'meaning' => 'School',
                'meaning_zh' => '学校',
                'example_sentence' => '我去学校。',
                'example_translation' => 'I go to school.',
                'definition' => 'School',
                'sentences' => ['去___。', '在___。', '___学习。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '大学',
                'pinyin' => 'dà xué',
                'simplified' => '大学',
                'traditional' => '大學',
                'part_of_speech' => 'noun',
                'meaning' => 'University',
                'meaning_zh' => '大学',
                'example_sentence' => '我在大学学习。',
                'example_translation' => 'I study at the university.',
                'definition' => 'University, college',
                'sentences' => ['在___。', '上___。', '___学生。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '办公室',
                'pinyin' => 'bàn gōng shì',
                'simplified' => '办公室',
                'traditional' => '辦公室',
                'part_of_speech' => 'noun',
                'meaning' => 'Office',
                'meaning_zh' => '办公室',
                'example_sentence' => '我在办公室工作。',
                'example_translation' => 'I work in the office.',
                'definition' => 'Office',
                'sentences' => ['在___。', '___工作。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '体育馆',
                'pinyin' => 'tǐ yù guǎn',
                'simplified' => '体育馆',
                'traditional' => '體育館',
                'part_of_speech' => 'noun',
                'meaning' => 'Gymnasium / Sports center',
                'meaning_zh' => '体育馆',
                'example_sentence' => '我们去体育馆运动。',
                'example_translation' => 'We go to the gym to exercise.',
                'definition' => 'Gymnasium, sports center',
                'sentences' => ['去___。', '___运动。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '游泳池',
                'pinyin' => 'yóu yǒng chí',
                'simplified' => '游泳池',
                'traditional' => '游泳池',
                'part_of_speech' => 'noun',
                'meaning' => 'Swimming pool',
                'meaning_zh' => '游泳池',
                'example_sentence' => '我们去游泳池。',
                'example_translation' => 'We go to the swimming pool.',
                'definition' => 'Swimming pool',
                'sentences' => ['去___。', '___游泳。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '广场',
                'pinyin' => 'guǎng chǎng',
                'simplified' => '广场',
                'traditional' => '廣場',
                'part_of_speech' => 'noun',
                'meaning' => 'Square / Plaza',
                'meaning_zh' => '广场',
                'example_sentence' => '我们在广场。',
                'example_translation' => 'We are at the square.',
                'definition' => 'Square, plaza',
                'sentences' => ['在___。', '___很大。', '去___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '动物园',
                'pinyin' => 'dòng wù yuán',
                'simplified' => '动物园',
                'traditional' => '動物園',
                'part_of_speech' => 'noun',
                'meaning' => 'Zoo',
                'meaning_zh' => '动物园',
                'example_sentence' => '我们去动物园。',
                'example_translation' => 'We go to the zoo.',
                'definition' => 'Zoo, zoological garden',
                'sentences' => ['去___。', '___看动物。', '___很有趣。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 43,
                'word' => '博物馆',
                'pinyin' => 'bó wù guǎn',
                'simplified' => '博物馆',
                'traditional' => '博物館',
                'part_of_speech' => 'noun',
                'meaning' => 'Museum',
                'meaning_zh' => '博物馆',
                'example_sentence' => '我们去博物馆。',
                'example_translation' => 'We go to the museum.',
                'definition' => 'Museum',
                'sentences' => ['去___。', '___很有趣。', '___在哪里？'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 44: At Home (在家) - 20 words
        $homeVocab = [
            [
                'topic_id' => 44,
                'word' => '房间',
                'pinyin' => 'fáng jiān',
                'simplified' => '房间',
                'traditional' => '房間',
                'part_of_speech' => 'noun',
                'meaning' => 'Room',
                'meaning_zh' => '房间',
                'example_sentence' => '我的房间很大。',
                'example_translation' => 'My room is very big.',
                'definition' => 'Room',
                'sentences' => ['___很大。', '我的___。', '___干净。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '卧室',
                'pinyin' => 'wò shì',
                'simplified' => '卧室',
                'traditional' => '臥室',
                'part_of_speech' => 'noun',
                'meaning' => 'Bedroom',
                'meaning_zh' => '卧室',
                'example_sentence' => '我在卧室睡觉。',
                'example_translation' => 'I sleep in the bedroom.',
                'definition' => 'Bedroom',
                'sentences' => ['在___睡觉。', '___很舒服。', '我的___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '客厅',
                'pinyin' => 'kè tīng',
                'simplified' => '客厅',
                'traditional' => '客廳',
                'part_of_speech' => 'noun',
                'meaning' => 'Living room',
                'meaning_zh' => '客厅',
                'example_sentence' => '我在客厅看电视。',
                'example_translation' => 'I watch TV in the living room.',
                'definition' => 'Living room',
                'sentences' => ['在___。', '___很大。', '___看电视。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '厨房',
                'pinyin' => 'chú fáng',
                'simplified' => '厨房',
                'traditional' => '廚房',
                'part_of_speech' => 'noun',
                'meaning' => 'Kitchen',
                'meaning_zh' => '厨房',
                'example_sentence' => '妈妈在厨房做饭。',
                'example_translation' => 'Mom cooks in the kitchen.',
                'definition' => 'Kitchen',
                'sentences' => ['在___做饭。', '___很干净。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '卫生间',
                'pinyin' => 'wèi shēng jiān',
                'simplified' => '卫生间',
                'traditional' => '衛生間',
                'part_of_speech' => 'noun',
                'meaning' => 'Bathroom / Toilet',
                'meaning_zh' => '卫生间',
                'example_sentence' => '卫生间在哪里？',
                'example_translation' => 'Where is the bathroom?',
                'definition' => 'Bathroom, toilet, restroom',
                'sentences' => ['___在哪里？', '去___。', '___很干净。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '阳台',
                'pinyin' => 'yáng tái',
                'simplified' => '阳台',
                'traditional' => '陽台',
                'part_of_speech' => 'noun',
                'meaning' => 'Balcony',
                'meaning_zh' => '阳台',
                'example_sentence' => '我在阳台上。',
                'example_translation' => 'I am on the balcony.',
                'definition' => 'Balcony',
                'sentences' => ['在___。', '___很大。', '___上。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '门',
                'pinyin' => 'mén',
                'simplified' => '门',
                'traditional' => '門',
                'part_of_speech' => 'noun',
                'meaning' => 'Door',
                'meaning_zh' => '门',
                'example_sentence' => '请开门。',
                'example_translation' => 'Please open the door.',
                'definition' => 'Door, gate',
                'sentences' => ['开___。', '关___。', '___在哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '窗户',
                'pinyin' => 'chuāng hu',
                'simplified' => '窗户',
                'traditional' => '窗戶',
                'part_of_speech' => 'noun',
                'meaning' => 'Window',
                'meaning_zh' => '窗户',
                'example_sentence' => '请开窗户。',
                'example_translation' => 'Please open the window.',
                'definition' => 'Window',
                'sentences' => ['开___。', '关___。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '床',
                'pinyin' => 'chuáng',
                'simplified' => '床',
                'traditional' => '床',
                'part_of_speech' => 'noun',
                'meaning' => 'Bed',
                'meaning_zh' => '床',
                'example_sentence' => '我在床上睡觉。',
                'example_translation' => 'I sleep in bed.',
                'definition' => 'Bed',
                'sentences' => ['在___上。', '___很舒服。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '桌子',
                'pinyin' => 'zhuō zi',
                'simplified' => '桌子',
                'traditional' => '桌子',
                'part_of_speech' => 'noun',
                'meaning' => 'Table / Desk',
                'meaning_zh' => '桌子',
                'example_sentence' => '书在桌子上。',
                'example_translation' => 'The book is on the table.',
                'definition' => 'Table, desk',
                'sentences' => ['在___上。', '___很大。', '___上有什么？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '椅子',
                'pinyin' => 'yǐ zi',
                'simplified' => '椅子',
                'traditional' => '椅子',
                'part_of_speech' => 'noun',
                'meaning' => 'Chair',
                'meaning_zh' => '椅子',
                'example_sentence' => '我坐在椅子上。',
                'example_translation' => 'I sit on the chair.',
                'definition' => 'Chair',
                'sentences' => ['坐在___上。', '___很舒服。', '___在哪里？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '沙发',
                'pinyin' => 'shā fā',
                'simplified' => '沙发',
                'traditional' => '沙發',
                'part_of_speech' => 'noun',
                'meaning' => 'Sofa',
                'meaning_zh' => '沙发',
                'example_sentence' => '我坐在沙发上。',
                'example_translation' => 'I sit on the sofa.',
                'definition' => 'Sofa, couch',
                'sentences' => ['坐在___上。', '___很舒服。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '灯',
                'pinyin' => 'dēng',
                'simplified' => '灯',
                'traditional' => '燈',
                'part_of_speech' => 'noun',
                'meaning' => 'Light / Lamp',
                'meaning_zh' => '灯',
                'example_sentence' => '请开灯。',
                'example_translation' => 'Please turn on the light.',
                'definition' => 'Light, lamp',
                'sentences' => ['开___。', '关___。', '___很亮。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '冰箱',
                'pinyin' => 'bīng xiāng',
                'simplified' => '冰箱',
                'traditional' => '冰箱',
                'part_of_speech' => 'noun',
                'meaning' => 'Refrigerator',
                'meaning_zh' => '冰箱',
                'example_sentence' => '水在冰箱里。',
                'example_translation' => 'The water is in the refrigerator.',
                'definition' => 'Refrigerator, fridge',
                'sentences' => ['在___里。', '___很大。', '___里有什么？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '空调',
                'pinyin' => 'kōng tiáo',
                'simplified' => '空调',
                'traditional' => '空調',
                'part_of_speech' => 'noun',
                'meaning' => 'Air conditioner',
                'meaning_zh' => '空调',
                'example_sentence' => '请开空调。',
                'example_translation' => 'Please turn on the air conditioner.',
                'definition' => 'Air conditioner, air conditioning',
                'sentences' => ['开___。', '关___。', '___很凉快。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '电视',
                'pinyin' => 'diàn shì',
                'simplified' => '电视',
                'traditional' => '電視',
                'part_of_speech' => 'noun',
                'meaning' => 'Television / TV',
                'meaning_zh' => '电视',
                'example_sentence' => '我看电视。',
                'example_translation' => 'I watch TV.',
                'definition' => 'Television, TV',
                'sentences' => ['看___。', '___很大。', '___节目。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '电话',
                'pinyin' => 'diàn huà',
                'simplified' => '电话',
                'traditional' => '電話',
                'part_of_speech' => 'noun',
                'meaning' => 'Telephone / Phone',
                'meaning_zh' => '电话',
                'example_sentence' => '我打电话。',
                'example_translation' => 'I make a phone call.',
                'definition' => 'Telephone, phone, phone call',
                'sentences' => ['打___。', '___号码。', '___响了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '钥匙',
                'pinyin' => 'yào shi',
                'simplified' => '钥匙',
                'traditional' => '鑰匙',
                'part_of_speech' => 'noun',
                'meaning' => 'Key',
                'meaning_zh' => '钥匙',
                'example_sentence' => '钥匙在哪里？',
                'example_translation' => 'Where is the key?',
                'definition' => 'Key',
                'sentences' => ['___在哪里？', '我的___。', '___找不到。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '墙',
                'pinyin' => 'qiáng',
                'simplified' => '墙',
                'traditional' => '牆',
                'part_of_speech' => 'noun',
                'meaning' => 'Wall',
                'meaning_zh' => '墙',
                'example_sentence' => '墙上有画。',
                'example_translation' => 'There is a painting on the wall.',
                'definition' => 'Wall',
                'sentences' => ['___上。', '___很白。', '___很高。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 44,
                'word' => '地板',
                'pinyin' => 'dì bǎn',
                'simplified' => '地板',
                'traditional' => '地板',
                'part_of_speech' => 'noun',
                'meaning' => 'Floor',
                'meaning_zh' => '地板',
                'example_sentence' => '地板很干净。',
                'example_translation' => 'The floor is very clean.',
                'definition' => 'Floor, flooring',
                'sentences' => ['___很干净。', '在___上。', '___很滑。'],
                'level' => 'HSK2',
            ],
        ];

        // Topic 45: Weather and Seasons (天气和季节) - 20 words
        $weatherVocab = [
            [
                'topic_id' => 45,
                'word' => '天气',
                'pinyin' => 'tiān qì',
                'simplified' => '天气',
                'traditional' => '天氣',
                'part_of_speech' => 'noun',
                'meaning' => 'Weather',
                'meaning_zh' => '天气',
                'example_sentence' => '今天天气很好。',
                'example_translation' => 'The weather is very good today.',
                'definition' => 'Weather',
                'sentences' => ['___很好。', '___怎么样？', '___预报。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '晴天',
                'pinyin' => 'qíng tiān',
                'simplified' => '晴天',
                'traditional' => '晴天',
                'part_of_speech' => 'noun',
                'meaning' => 'Sunny day',
                'meaning_zh' => '晴天',
                'example_sentence' => '今天是晴天。',
                'example_translation' => 'Today is sunny.',
                'definition' => 'Sunny day, clear sky',
                'sentences' => ['今天是___。', '___很好。', '___出去玩。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '阴天',
                'pinyin' => 'yīn tiān',
                'simplified' => '阴天',
                'traditional' => '陰天',
                'part_of_speech' => 'noun',
                'meaning' => 'Cloudy / Overcast',
                'meaning_zh' => '阴天',
                'example_sentence' => '今天是阴天。',
                'example_translation' => 'Today is cloudy.',
                'definition' => 'Cloudy day, overcast',
                'sentences' => ['今天是___。', '___不冷。', '___可能下雨。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '下雨',
                'pinyin' => 'xià yǔ',
                'simplified' => '下雨',
                'traditional' => '下雨',
                'part_of_speech' => 'verb',
                'meaning' => 'To rain',
                'meaning_zh' => '下雨',
                'example_sentence' => '今天下雨了。',
                'example_translation' => 'It rained today.',
                'definition' => 'To rain',
                'sentences' => ['今天___。', '___了。', '会___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '下雪',
                'pinyin' => 'xià xuě',
                'simplified' => '下雪',
                'traditional' => '下雪',
                'part_of_speech' => 'verb',
                'meaning' => 'To snow',
                'meaning_zh' => '下雪',
                'example_sentence' => '今天下雪了。',
                'example_translation' => 'It snowed today.',
                'definition' => 'To snow',
                'sentences' => ['今天___。', '___了。', '___很美。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '刮风',
                'pinyin' => 'guā fēng',
                'simplified' => '刮风',
                'traditional' => '颳風',
                'part_of_speech' => 'verb',
                'meaning' => 'To be windy',
                'meaning_zh' => '刮风',
                'example_sentence' => '今天刮风了。',
                'example_translation' => 'It is windy today.',
                'definition' => 'To be windy, to blow (wind)',
                'sentences' => ['今天___。', '___了。', '___很大。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '热',
                'pinyin' => 'rè',
                'simplified' => '热',
                'traditional' => '熱',
                'part_of_speech' => 'adjective',
                'meaning' => 'Hot',
                'meaning_zh' => '热',
                'example_sentence' => '今天很热。',
                'example_translation' => 'It is very hot today.',
                'definition' => 'Hot, heat',
                'sentences' => ['今天很___。', '___不___？', '___死了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '冷',
                'pinyin' => 'lěng',
                'simplified' => '冷',
                'traditional' => '冷',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cold',
                'meaning_zh' => '冷',
                'example_sentence' => '今天很冷。',
                'example_translation' => 'It is very cold today.',
                'definition' => 'Cold',
                'sentences' => ['今天很___。', '___不___？', '___死了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '凉快',
                'pinyin' => 'liáng kuai',
                'simplified' => '凉快',
                'traditional' => '涼快',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cool / Pleasantly cool',
                'meaning_zh' => '凉快',
                'example_sentence' => '今天很凉快。',
                'example_translation' => 'It is very cool today.',
                'definition' => 'Cool, pleasantly cool',
                'sentences' => ['今天很___。', '___一下。', '___吗？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '暖和',
                'pinyin' => 'nuǎn huo',
                'simplified' => '暖和',
                'traditional' => '暖和',
                'part_of_speech' => 'adjective',
                'meaning' => 'Warm',
                'meaning_zh' => '暖和',
                'example_sentence' => '今天很暖和。',
                'example_translation' => 'It is very warm today.',
                'definition' => 'Warm',
                'sentences' => ['今天很___。', '___吗？', '___的。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '春天',
                'pinyin' => 'chūn tiān',
                'simplified' => '春天',
                'traditional' => '春天',
                'part_of_speech' => 'noun',
                'meaning' => 'Spring',
                'meaning_zh' => '春天',
                'example_sentence' => '春天很美。',
                'example_translation' => 'Spring is very beautiful.',
                'definition' => 'Spring, springtime',
                'sentences' => ['___很美。', '___来了。', '___的花。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '夏天',
                'pinyin' => 'xià tiān',
                'simplified' => '夏天',
                'traditional' => '夏天',
                'part_of_speech' => 'noun',
                'meaning' => 'Summer',
                'meaning_zh' => '夏天',
                'example_sentence' => '夏天很热。',
                'example_translation' => 'Summer is very hot.',
                'definition' => 'Summer, summertime',
                'sentences' => ['___很热。', '___游泳。', '___的天气。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '秋天',
                'pinyin' => 'qiū tiān',
                'simplified' => '秋天',
                'traditional' => '秋天',
                'part_of_speech' => 'noun',
                'meaning' => 'Autumn / Fall',
                'meaning_zh' => '秋天',
                'example_sentence' => '秋天很凉快。',
                'example_translation' => 'Autumn is very cool.',
                'definition' => 'Autumn, fall',
                'sentences' => ['___很凉快。', '___的叶子。', '___来了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '冬天',
                'pinyin' => 'dōng tiān',
                'simplified' => '冬天',
                'traditional' => '冬天',
                'part_of_speech' => 'noun',
                'meaning' => 'Winter',
                'meaning_zh' => '冬天',
                'example_sentence' => '冬天很冷。',
                'example_translation' => 'Winter is very cold.',
                'definition' => 'Winter, wintertime',
                'sentences' => ['___很冷。', '___下雪。', '___的衣服。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '季节',
                'pinyin' => 'jì jié',
                'simplified' => '季节',
                'traditional' => '季節',
                'part_of_speech' => 'noun',
                'meaning' => 'Season',
                'meaning_zh' => '季节',
                'example_sentence' => '你喜欢什么季节？',
                'example_translation' => 'What season do you like?',
                'definition' => 'Season',
                'sentences' => ['什么___？', '___很美。', '四个___。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '温度',
                'pinyin' => 'wēn dù',
                'simplified' => '温度',
                'traditional' => '溫度',
                'part_of_speech' => 'noun',
                'meaning' => 'Temperature',
                'meaning_zh' => '温度',
                'example_sentence' => '今天温度很高。',
                'example_translation' => 'The temperature is very high today.',
                'definition' => 'Temperature',
                'sentences' => ['___很高。', '___很低。', '___怎么样？'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '太阳',
                'pinyin' => 'tài yáng',
                'simplified' => '太阳',
                'traditional' => '太陽',
                'part_of_speech' => 'noun',
                'meaning' => 'Sun',
                'meaning_zh' => '太阳',
                'example_sentence' => '太阳很大。',
                'example_translation' => 'The sun is very bright.',
                'definition' => 'Sun',
                'sentences' => ['___很大。', '___出来了。', '___下山了。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '云',
                'pinyin' => 'yún',
                'simplified' => '云',
                'traditional' => '雲',
                'part_of_speech' => 'noun',
                'meaning' => 'Cloud',
                'meaning_zh' => '云',
                'example_sentence' => '天上有云。',
                'example_translation' => 'There are clouds in the sky.',
                'definition' => 'Cloud',
                'sentences' => ['天上有___。', '___很多。', '___很白。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '风',
                'pinyin' => 'fēng',
                'simplified' => '风',
                'traditional' => '風',
                'part_of_speech' => 'noun',
                'meaning' => 'Wind',
                'meaning_zh' => '风',
                'example_sentence' => '风很大。',
                'example_translation' => 'The wind is very strong.',
                'definition' => 'Wind',
                'sentences' => ['___很大。', '___很小。', '___吹。'],
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 45,
                'word' => '雨伞',
                'pinyin' => 'yǔ sǎn',
                'simplified' => '雨伞',
                'traditional' => '雨傘',
                'part_of_speech' => 'noun',
                'meaning' => 'Umbrella',
                'meaning_zh' => '雨伞',
                'example_sentence' => '我带雨伞。',
                'example_translation' => 'I bring an umbrella.',
                'definition' => 'Umbrella',
                'sentences' => ['带___。', '我的___。', '___在哪里？'],
                'level' => 'HSK2',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($cityPlacesVocab, $homeVocab, $weatherVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
