<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics28to30Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 89: Weather and Seasons (天气和季节) - 20 words
        $weatherSeasonsVocab = [
            [
                'topic_id' => 89,
                'word' => '天气',
                'pinyin' => 'tiān qì',
                'simplified' => '天气',
                'traditional' => '天氣',
                'part_of_speech' => 'noun',
                'meaning' => 'Weather',
                'meaning_zh' => '天气',
                'example_sentence' => '天气很好。',
                'example_translation' => 'The weather is very good.',
                'definition' => 'Weather',
                'sentences' => ['___怎么样？', '___预报。', '___变化。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '气温',
                'pinyin' => 'qì wēn',
                'simplified' => '气温',
                'traditional' => '氣溫',
                'part_of_speech' => 'noun',
                'meaning' => 'Temperature',
                'meaning_zh' => '气温',
                'example_sentence' => '气温很高。',
                'example_translation' => 'The temperature is very high.',
                'definition' => 'Temperature, air temperature',
                'sentences' => ['___上升。', '___下降。', '___多少？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '季节',
                'pinyin' => 'jì jié',
                'simplified' => '季节',
                'traditional' => '季節',
                'part_of_speech' => 'noun',
                'meaning' => 'Season',
                'meaning_zh' => '季节',
                'example_sentence' => '春天是美丽的季节。',
                'example_translation' => 'Spring is a beautiful season.',
                'definition' => 'Season',
                'sentences' => ['四___。', '什么___？', '___变化。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '春天',
                'pinyin' => 'chūn tiān',
                'simplified' => '春天',
                'traditional' => '春天',
                'part_of_speech' => 'noun',
                'meaning' => 'Spring',
                'meaning_zh' => '春天',
                'example_sentence' => '春天来了。',
                'example_translation' => 'Spring has come.',
                'definition' => 'Spring',
                'sentences' => ['___的花。', '___天气。', '___到了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '夏天',
                'pinyin' => 'xià tiān',
                'simplified' => '夏天',
                'traditional' => '夏天',
                'part_of_speech' => 'noun',
                'meaning' => 'Summer',
                'meaning_zh' => '夏天',
                'example_sentence' => '夏天很热。',
                'example_translation' => 'Summer is very hot.',
                'definition' => 'Summer',
                'sentences' => ['___游泳。', '___假期。', '___到了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '秋天',
                'pinyin' => 'qiū tiān',
                'simplified' => '秋天',
                'traditional' => '秋天',
                'part_of_speech' => 'noun',
                'meaning' => 'Autumn / Fall',
                'meaning_zh' => '秋天',
                'example_sentence' => '秋天很凉爽。',
                'example_translation' => 'Autumn is very cool.',
                'definition' => 'Autumn, fall',
                'sentences' => ['___的叶子。', '___收获。', '___来了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '冬天',
                'pinyin' => 'dōng tiān',
                'simplified' => '冬天',
                'traditional' => '冬天',
                'part_of_speech' => 'noun',
                'meaning' => 'Winter',
                'meaning_zh' => '冬天',
                'example_sentence' => '冬天很冷。',
                'example_translation' => 'Winter is very cold.',
                'definition' => 'Winter',
                'sentences' => ['___下雪。', '___滑冰。', '___到了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '晴天',
                'pinyin' => 'qíng tiān',
                'simplified' => '晴天',
                'traditional' => '晴天',
                'part_of_speech' => 'noun',
                'meaning' => 'Sunny day / Clear weather',
                'meaning_zh' => '晴天',
                'example_sentence' => '今天是晴天。',
                'example_translation' => 'Today is a sunny day.',
                'definition' => 'Sunny day, clear weather',
                'sentences' => ['___出门。', '___很好。', '___多云。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '阴天',
                'pinyin' => 'yīn tiān',
                'simplified' => '阴天',
                'traditional' => '陰天',
                'part_of_speech' => 'noun',
                'meaning' => 'Cloudy day / Overcast',
                'meaning_zh' => '阴天',
                'example_sentence' => '今天是阴天。',
                'example_translation' => 'Today is cloudy.',
                'definition' => 'Cloudy day, overcast',
                'sentences' => ['___要下雨。', '___很闷。', '___转晴。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '刮风',
                'pinyin' => 'guā fēng',
                'simplified' => '刮风',
                'traditional' => '刮風',
                'part_of_speech' => 'verb',
                'meaning' => 'To be windy / Blow (wind)',
                'meaning_zh' => '刮风',
                'example_sentence' => '今天刮风。',
                'example_translation' => 'It\'s windy today.',
                'definition' => 'To be windy, blow (wind)',
                'sentences' => ['___了。', '___下雨。', '___很大。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '下雨',
                'pinyin' => 'xià yǔ',
                'simplified' => '下雨',
                'traditional' => '下雨',
                'part_of_speech' => 'verb',
                'meaning' => 'To rain',
                'meaning_zh' => '下雨',
                'example_sentence' => '今天下雨了。',
                'example_translation' => 'It\'s raining today.',
                'definition' => 'To rain',
                'sentences' => ['___了。', '要___。', '___天。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '下雪',
                'pinyin' => 'xià xuě',
                'simplified' => '下雪',
                'traditional' => '下雪',
                'part_of_speech' => 'verb',
                'meaning' => 'To snow',
                'meaning_zh' => '下雪',
                'example_sentence' => '冬天下雪。',
                'example_translation' => 'It snows in winter.',
                'definition' => 'To snow',
                'sentences' => ['___了。', '要___。', '___天。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '云',
                'pinyin' => 'yún',
                'simplified' => '云',
                'traditional' => '雲',
                'part_of_speech' => 'noun',
                'meaning' => 'Cloud',
                'meaning_zh' => '云',
                'example_sentence' => '天上有云。',
                'example_translation' => 'There are clouds in the sky.',
                'definition' => 'Cloud',
                'sentences' => ['白___。', '___朵。', '___彩。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '雾',
                'pinyin' => 'wù',
                'simplified' => '雾',
                'traditional' => '霧',
                'part_of_speech' => 'noun',
                'meaning' => 'Fog / Mist',
                'meaning_zh' => '雾',
                'example_sentence' => '早上有雾。',
                'example_translation' => 'There is fog in the morning.',
                'definition' => 'Fog, mist',
                'sentences' => ['大___。', '___天。', '___气。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '风',
                'pinyin' => 'fēng',
                'simplified' => '风',
                'traditional' => '風',
                'part_of_speech' => 'noun',
                'meaning' => 'Wind',
                'meaning_zh' => '风',
                'example_sentence' => '风很大。',
                'example_translation' => 'The wind is strong.',
                'definition' => 'Wind',
                'sentences' => ['___大。', '___景。', '___格。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '雨',
                'pinyin' => 'yǔ',
                'simplified' => '雨',
                'traditional' => '雨',
                'part_of_speech' => 'noun',
                'meaning' => 'Rain',
                'meaning_zh' => '雨',
                'example_sentence' => '雨很大。',
                'example_translation' => 'The rain is heavy.',
                'definition' => 'Rain',
                'sentences' => ['下___。', '大___。', '___天。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '雪',
                'pinyin' => 'xuě',
                'simplified' => '雪',
                'traditional' => '雪',
                'part_of_speech' => 'noun',
                'meaning' => 'Snow',
                'meaning_zh' => '雪',
                'example_sentence' => '雪很白。',
                'example_translation' => 'The snow is very white.',
                'definition' => 'Snow',
                'sentences' => ['下___。', '白___。', '___花。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '冰',
                'pinyin' => 'bīng',
                'simplified' => '冰',
                'traditional' => '冰',
                'part_of_speech' => 'noun',
                'meaning' => 'Ice',
                'meaning_zh' => '冰',
                'example_sentence' => '水变成冰。',
                'example_translation' => 'Water turns into ice.',
                'definition' => 'Ice',
                'sentences' => ['___块。', '___箱。', '滑___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '凉快',
                'pinyin' => 'liáng kuai',
                'simplified' => '凉快',
                'traditional' => '涼快',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cool / Pleasantly cool',
                'meaning_zh' => '凉快',
                'example_sentence' => '这里很凉快。',
                'example_translation' => 'It\'s very cool here.',
                'definition' => 'Cool, pleasantly cool',
                'sentences' => ['很___。', '___一下。', '___的地方。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 89,
                'word' => '暖和',
                'pinyin' => 'nuǎn huo',
                'simplified' => '暖和',
                'traditional' => '暖和',
                'part_of_speech' => 'adjective',
                'meaning' => 'Warm',
                'meaning_zh' => '暖和',
                'example_sentence' => '房间很暖和。',
                'example_translation' => 'The room is very warm.',
                'definition' => 'Warm',
                'sentences' => ['很___。', '___的衣服。', '___起来。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 90: Festivals and Celebrations (节日和庆祝) - 20 words
        $festivalsVocab = [
            [
                'topic_id' => 90,
                'word' => '节日',
                'pinyin' => 'jié rì',
                'simplified' => '节日',
                'traditional' => '節日',
                'part_of_speech' => 'noun',
                'meaning' => 'Festival / Holiday',
                'meaning_zh' => '节日',
                'example_sentence' => '今天是节日。',
                'example_translation' => 'Today is a festival.',
                'definition' => 'Festival, holiday',
                'sentences' => ['传统___。', '___快乐。', '___庆祝。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '春节',
                'pinyin' => 'chūn jié',
                'simplified' => '春节',
                'traditional' => '春節',
                'part_of_speech' => 'noun',
                'meaning' => 'Spring Festival / Chinese New Year',
                'meaning_zh' => '春节',
                'example_sentence' => '春节快乐！',
                'example_translation' => 'Happy Spring Festival!',
                'definition' => 'Spring Festival, Chinese New Year',
                'sentences' => ['___到了。', '___假期。', '过___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '元旦',
                'pinyin' => 'yuán dàn',
                'simplified' => '元旦',
                'traditional' => '元旦',
                'part_of_speech' => 'noun',
                'meaning' => 'New Year\'s Day',
                'meaning_zh' => '元旦',
                'example_sentence' => '元旦快乐！',
                'example_translation' => 'Happy New Year\'s Day!',
                'definition' => 'New Year\'s Day (January 1st)',
                'sentences' => ['___假期。', '___晚会。', '庆祝___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '中秋节',
                'pinyin' => 'zhōng qiū jié',
                'simplified' => '中秋节',
                'traditional' => '中秋節',
                'part_of_speech' => 'noun',
                'meaning' => 'Mid-Autumn Festival',
                'meaning_zh' => '中秋节',
                'example_sentence' => '中秋节吃月饼。',
                'example_translation' => 'Eat mooncakes at Mid-Autumn Festival.',
                'definition' => 'Mid-Autumn Festival',
                'sentences' => ['___快乐。', '___赏月。', '过___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '国庆节',
                'pinyin' => 'guó qìng jié',
                'simplified' => '国庆节',
                'traditional' => '國慶節',
                'part_of_speech' => 'noun',
                'meaning' => 'National Day',
                'meaning_zh' => '国庆节',
                'example_sentence' => '国庆节放假。',
                'example_translation' => 'National Day holiday.',
                'definition' => 'National Day',
                'sentences' => ['___快乐。', '___假期。', '庆祝___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '圣诞节',
                'pinyin' => 'shèng dàn jié',
                'simplified' => '圣诞节',
                'traditional' => '聖誕節',
                'part_of_speech' => 'noun',
                'meaning' => 'Christmas',
                'meaning_zh' => '圣诞节',
                'example_sentence' => '圣诞节快乐！',
                'example_translation' => 'Merry Christmas!',
                'definition' => 'Christmas',
                'sentences' => ['___快乐。', '___礼物。', '过___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '生日',
                'pinyin' => 'shēng rì',
                'simplified' => '生日',
                'traditional' => '生日',
                'part_of_speech' => 'noun',
                'meaning' => 'Birthday',
                'meaning_zh' => '生日',
                'example_sentence' => '生日快乐！',
                'example_translation' => 'Happy birthday!',
                'definition' => 'Birthday',
                'sentences' => ['___快乐。', '___礼物。', '过___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '假期',
                'pinyin' => 'jià qī',
                'simplified' => '假期',
                'traditional' => '假期',
                'part_of_speech' => 'noun',
                'meaning' => 'Holiday / Vacation',
                'meaning_zh' => '假期',
                'example_sentence' => '假期旅游。',
                'example_translation' => 'Travel during the holiday.',
                'definition' => 'Holiday, vacation',
                'sentences' => ['___安排。', '放___。', '___计划。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '放假',
                'pinyin' => 'fàng jià',
                'simplified' => '放假',
                'traditional' => '放假',
                'part_of_speech' => 'verb',
                'meaning' => 'To have a holiday / Day off',
                'meaning_zh' => '放假',
                'example_sentence' => '明天放假。',
                'example_translation' => 'Tomorrow is a day off.',
                'definition' => 'To have a holiday, day off',
                'sentences' => ['___了。', '___几天。', '___期间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '庆祝',
                'pinyin' => 'qìng zhù',
                'simplified' => '庆祝',
                'traditional' => '慶祝',
                'part_of_speech' => 'verb',
                'meaning' => 'To celebrate',
                'meaning_zh' => '庆祝',
                'example_sentence' => '庆祝生日。',
                'example_translation' => 'Celebrate birthday.',
                'definition' => 'To celebrate',
                'sentences' => ['___节日。', '___成功。', '___活动。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '祝贺',
                'pinyin' => 'zhù hè',
                'simplified' => '祝贺',
                'traditional' => '祝賀',
                'part_of_speech' => 'verb',
                'meaning' => 'To congratulate',
                'meaning_zh' => '祝贺',
                'example_sentence' => '祝贺你！',
                'example_translation' => 'Congratulations to you!',
                'definition' => 'To congratulate',
                'sentences' => ['___你。', '___成功。', '表示___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '礼物',
                'pinyin' => 'lǐ wù',
                'simplified' => '礼物',
                'traditional' => '禮物',
                'part_of_speech' => 'noun',
                'meaning' => 'Gift / Present',
                'meaning_zh' => '礼物',
                'example_sentence' => '送礼物。',
                'example_translation' => 'Give a gift.',
                'definition' => 'Gift, present',
                'sentences' => ['___盒。', '送___。', '收到___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '红包',
                'pinyin' => 'hóng bāo',
                'simplified' => '红包',
                'traditional' => '紅包',
                'part_of_speech' => 'noun',
                'meaning' => 'Red envelope / Money gift',
                'meaning_zh' => '红包',
                'example_sentence' => '给红包。',
                'example_translation' => 'Give red envelope.',
                'definition' => 'Red envelope, money gift',
                'sentences' => ['发___。', '收___。', '___里。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '蛋糕',
                'pinyin' => 'dàn gāo',
                'simplified' => '蛋糕',
                'traditional' => '蛋糕',
                'part_of_speech' => 'noun',
                'meaning' => 'Cake',
                'meaning_zh' => '蛋糕',
                'example_sentence' => '生日蛋糕。',
                'example_translation' => 'Birthday cake.',
                'definition' => 'Cake',
                'sentences' => ['一块___。', '吃___。', '___店。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '月饼',
                'pinyin' => 'yuè bǐng',
                'simplified' => '月饼',
                'traditional' => '月餅',
                'part_of_speech' => 'noun',
                'meaning' => 'Mooncake',
                'meaning_zh' => '月饼',
                'example_sentence' => '吃月饼。',
                'example_translation' => 'Eat mooncakes.',
                'definition' => 'Mooncake',
                'sentences' => ['一个___。', '___好吃。', '送___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '团圆',
                'pinyin' => 'tuán yuán',
                'simplified' => '团圆',
                'traditional' => '團圓',
                'part_of_speech' => 'verb',
                'meaning' => 'To reunite / Reunion',
                'meaning_zh' => '团圆',
                'example_sentence' => '家人团圆。',
                'example_translation' => 'Family reunion.',
                'definition' => 'To reunite, reunion',
                'sentences' => ['___饭。', '全家___。', '___快乐。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '聚会',
                'pinyin' => 'jù huì',
                'simplified' => '聚会',
                'traditional' => '聚會',
                'part_of_speech' => 'noun',
                'meaning' => 'Party / Gathering',
                'meaning_zh' => '聚会',
                'example_sentence' => '参加聚会。',
                'example_translation' => 'Attend a party.',
                'definition' => 'Party, gathering, get-together',
                'sentences' => ['___活动。', '朋友___。', '举办___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '晚会',
                'pinyin' => 'wǎn huì',
                'simplified' => '晚会',
                'traditional' => '晚會',
                'part_of_speech' => 'noun',
                'meaning' => 'Evening party / Gala',
                'meaning_zh' => '晚会',
                'example_sentence' => '参加晚会。',
                'example_translation' => 'Attend an evening party.',
                'definition' => 'Evening party, gala',
                'sentences' => ['___节目。', '春节___。', '举办___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '烟花',
                'pinyin' => 'yān huā',
                'simplified' => '烟花',
                'traditional' => '煙花',
                'part_of_speech' => 'noun',
                'meaning' => 'Fireworks',
                'meaning_zh' => '烟花',
                'example_sentence' => '放烟花。',
                'example_translation' => 'Set off fireworks.',
                'definition' => 'Fireworks',
                'sentences' => ['___表演。', '看___。', '___爆竹。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 90,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '传统节日。',
                'example_translation' => 'Traditional festival.',
                'definition' => 'Tradition, traditional',
                'sentences' => ['___文化。', '___习俗。', '___的。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 91: Culture and Customs (文化和习俗) - 20 words
        $cultureCustomsVocab = [
            [
                'topic_id' => 91,
                'word' => '文化',
                'pinyin' => 'wén huà',
                'simplified' => '文化',
                'traditional' => '文化',
                'part_of_speech' => 'noun',
                'meaning' => 'Culture',
                'meaning_zh' => '文化',
                'example_sentence' => '中国文化。',
                'example_translation' => 'Chinese culture.',
                'definition' => 'Culture',
                'sentences' => ['___交流。', '___传统。', '___差异。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '习俗',
                'pinyin' => 'xí sú',
                'simplified' => '习俗',
                'traditional' => '習俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Convention',
                'meaning_zh' => '习俗',
                'example_sentence' => '传统习俗。',
                'example_translation' => 'Traditional customs.',
                'definition' => 'Custom, convention',
                'sentences' => ['___文化。', '地方___。', '___传统。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '风俗',
                'pinyin' => 'fēng sú',
                'simplified' => '风俗',
                'traditional' => '風俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Social conventions',
                'meaning_zh' => '风俗',
                'example_sentence' => '各地风俗。',
                'example_translation' => 'Customs of various places.',
                'definition' => 'Custom, social conventions',
                'sentences' => ['___习惯。', '___不同。', '地方___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '历史',
                'pinyin' => 'lì shǐ',
                'simplified' => '历史',
                'traditional' => '歷史',
                'part_of_speech' => 'noun',
                'meaning' => 'History',
                'meaning_zh' => '历史',
                'example_sentence' => '学习历史。',
                'example_translation' => 'Study history.',
                'definition' => 'History',
                'sentences' => ['___课。', '___悠久。', '___文化。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '古代',
                'pinyin' => 'gǔ dài',
                'simplified' => '古代',
                'traditional' => '古代',
                'part_of_speech' => 'noun',
                'meaning' => 'Ancient times',
                'meaning_zh' => '古代',
                'example_sentence' => '古代历史。',
                'example_translation' => 'Ancient history.',
                'definition' => 'Ancient times',
                'sentences' => ['___文化。', '___的。', '___建筑。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '现代',
                'pinyin' => 'xiàn dài',
                'simplified' => '现代',
                'traditional' => '現代',
                'part_of_speech' => 'noun',
                'meaning' => 'Modern times',
                'meaning_zh' => '现代',
                'example_sentence' => '现代社会。',
                'example_translation' => 'Modern society.',
                'definition' => 'Modern times, contemporary',
                'sentences' => ['___化。', '___的。', '___人。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '艺术',
                'pinyin' => 'yì shù',
                'simplified' => '艺术',
                'traditional' => '藝術',
                'part_of_speech' => 'noun',
                'meaning' => 'Art',
                'meaning_zh' => '艺术',
                'example_sentence' => '艺术作品。',
                'example_translation' => 'Art work.',
                'definition' => 'Art',
                'sentences' => ['___家。', '___品。', '___馆。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '音乐',
                'pinyin' => 'yīn yuè',
                'simplified' => '音乐',
                'traditional' => '音樂',
                'part_of_speech' => 'noun',
                'meaning' => 'Music',
                'meaning_zh' => '音乐',
                'example_sentence' => '听音乐。',
                'example_translation' => 'Listen to music.',
                'definition' => 'Music',
                'sentences' => ['___会。', '___家。', '___课。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '歌曲',
                'pinyin' => 'gē qǔ',
                'simplified' => '歌曲',
                'traditional' => '歌曲',
                'part_of_speech' => 'noun',
                'meaning' => 'Song',
                'meaning_zh' => '歌曲',
                'example_sentence' => '唱歌曲。',
                'example_translation' => 'Sing a song.',
                'definition' => 'Song',
                'sentences' => ['___好听。', '流行___。', '___名字。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '舞蹈',
                'pinyin' => 'wǔ dǎo',
                'simplified' => '舞蹈',
                'traditional' => '舞蹈',
                'part_of_speech' => 'noun',
                'meaning' => 'Dance',
                'meaning_zh' => '舞蹈',
                'example_sentence' => '跳舞蹈。',
                'example_translation' => 'Dance.',
                'definition' => 'Dance',
                'sentences' => ['___表演。', '___课。', '___家。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '电影',
                'pinyin' => 'diàn yǐng',
                'simplified' => '电影',
                'traditional' => '電影',
                'part_of_speech' => 'noun',
                'meaning' => 'Movie / Film',
                'meaning_zh' => '电影',
                'example_sentence' => '看电影。',
                'example_translation' => 'Watch a movie.',
                'definition' => 'Movie, film',
                'sentences' => ['___院。', '___票。', '___明星。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '戏剧',
                'pinyin' => 'xì jù',
                'simplified' => '戏剧',
                'traditional' => '戲劇',
                'part_of_speech' => 'noun',
                'meaning' => 'Drama / Play / Theater',
                'meaning_zh' => '戏剧',
                'example_sentence' => '看戏剧。',
                'example_translation' => 'Watch a play.',
                'definition' => 'Drama, play, theater',
                'sentences' => ['___表演。', '___院。', '___作品。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '京剧',
                'pinyin' => 'jīng jù',
                'simplified' => '京剧',
                'traditional' => '京劇',
                'part_of_speech' => 'noun',
                'meaning' => 'Peking Opera',
                'meaning_zh' => '京剧',
                'example_sentence' => '看京剧。',
                'example_translation' => 'Watch Peking Opera.',
                'definition' => 'Peking Opera',
                'sentences' => ['___表演。', '___脸谱。', '___演员。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '书法',
                'pinyin' => 'shū fǎ',
                'simplified' => '书法',
                'traditional' => '書法',
                'part_of_speech' => 'noun',
                'meaning' => 'Calligraphy',
                'meaning_zh' => '书法',
                'example_sentence' => '练书法。',
                'example_translation' => 'Practice calligraphy.',
                'definition' => 'Calligraphy',
                'sentences' => ['___作品。', '___课。', '___家。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '绘画',
                'pinyin' => 'huì huà',
                'simplified' => '绘画',
                'traditional' => '繪畫',
                'part_of_speech' => 'noun',
                'meaning' => 'Painting / Drawing',
                'meaning_zh' => '绘画',
                'example_sentence' => '学习绘画。',
                'example_translation' => 'Study painting.',
                'definition' => 'Painting, drawing',
                'sentences' => ['___作品。', '___课。', '___艺术。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '诗歌',
                'pinyin' => 'shī gē',
                'simplified' => '诗歌',
                'traditional' => '詩歌',
                'part_of_speech' => 'noun',
                'meaning' => 'Poetry / Poem',
                'meaning_zh' => '诗歌',
                'example_sentence' => '读诗歌。',
                'example_translation' => 'Read poetry.',
                'definition' => 'Poetry, poem',
                'sentences' => ['___朗诵。', '古代___。', '___作品。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '小说',
                'pinyin' => 'xiǎo shuō',
                'simplified' => '小说',
                'traditional' => '小說',
                'part_of_speech' => 'noun',
                'meaning' => 'Novel / Fiction',
                'meaning_zh' => '小说',
                'example_sentence' => '看小说。',
                'example_translation' => 'Read a novel.',
                'definition' => 'Novel, fiction',
                'sentences' => ['___家。', '___作品。', '写___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '武术',
                'pinyin' => 'wǔ shù',
                'simplified' => '武术',
                'traditional' => '武術',
                'part_of_speech' => 'noun',
                'meaning' => 'Martial arts / Wushu',
                'meaning_zh' => '武术',
                'example_sentence' => '学武术。',
                'example_translation' => 'Learn martial arts.',
                'definition' => 'Martial arts, wushu',
                'sentences' => ['___表演。', '___课。', '___馆。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '太极拳',
                'pinyin' => 'tài jí quán',
                'simplified' => '太极拳',
                'traditional' => '太極拳',
                'part_of_speech' => 'noun',
                'meaning' => 'Tai Chi',
                'meaning_zh' => '太极拳',
                'example_sentence' => '打太极拳。',
                'example_translation' => 'Practice Tai Chi.',
                'definition' => 'Tai Chi',
                'sentences' => ['___运动。', '___课。', '练___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 91,
                'word' => '民族',
                'pinyin' => 'mín zú',
                'simplified' => '民族',
                'traditional' => '民族',
                'part_of_speech' => 'noun',
                'meaning' => 'Ethnic group / Nationality',
                'meaning_zh' => '民族',
                'example_sentence' => '少数民族。',
                'example_translation' => 'Ethnic minority.',
                'definition' => 'Ethnic group, nationality',
                'sentences' => ['___文化。', '___特色。', '___舞蹈。'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($weatherSeasonsVocab, $festivalsVocab, $cultureCustomsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
