<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics21to24Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 82: Conjunctions and Prepositions (连词和介词) - 20 words
        $conjunctionsVocab = [
            [
                'topic_id' => 82,
                'word' => '因为',
                'pinyin' => 'yīn wèi',
                'simplified' => '因为',
                'traditional' => '因為',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Because',
                'meaning_zh' => '因为',
                'example_sentence' => '因为下雨，所以不去。',
                'example_translation' => 'Because it\'s raining, I won\'t go.',
                'definition' => 'Because',
                'sentences' => ['___生病。', '___太忙。', '___喜欢。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '所以',
                'pinyin' => 'suǒ yǐ',
                'simplified' => '所以',
                'traditional' => '所以',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Therefore / So',
                'meaning_zh' => '所以',
                'example_sentence' => '下雨了，所以不去。',
                'example_translation' => 'It\'s raining, so I won\'t go.',
                'definition' => 'Therefore, so',
                'sentences' => ['___决定。', '___没去。', '___要。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '如果',
                'pinyin' => 'rú guǒ',
                'simplified' => '如果',
                'traditional' => '如果',
                'part_of_speech' => 'conjunction',
                'meaning' => 'If',
                'meaning_zh' => '如果',
                'example_sentence' => '如果下雨，就不去。',
                'example_translation' => 'If it rains, I won\'t go.',
                'definition' => 'If',
                'sentences' => ['___可以。', '___有空。', '___同意。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '要是',
                'pinyin' => 'yào shi',
                'simplified' => '要是',
                'traditional' => '要是',
                'part_of_speech' => 'conjunction',
                'meaning' => 'If',
                'meaning_zh' => '要是',
                'example_sentence' => '要是下雨，就不去。',
                'example_translation' => 'If it rains, I won\'t go.',
                'definition' => 'If',
                'sentences' => ['___可以。', '___有时间。', '___愿意。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '虽然',
                'pinyin' => 'suī rán',
                'simplified' => '虽然',
                'traditional' => '雖然',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Although / Though',
                'meaning_zh' => '虽然',
                'example_sentence' => '虽然累，但是继续。',
                'example_translation' => 'Although tired, continue.',
                'definition' => 'Although, though',
                'sentences' => ['___很难。', '___下雨。', '___不多。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '但是',
                'pinyin' => 'dàn shì',
                'simplified' => '但是',
                'traditional' => '但是',
                'part_of_speech' => 'conjunction',
                'meaning' => 'But / However',
                'meaning_zh' => '但是',
                'example_sentence' => '很难，但是要坚持。',
                'example_translation' => 'It\'s difficult, but must persist.',
                'definition' => 'But, however',
                'sentences' => ['___不行。', '___可以。', '___没有。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '不过',
                'pinyin' => 'bú guò',
                'simplified' => '不过',
                'traditional' => '不過',
                'part_of_speech' => 'conjunction',
                'meaning' => 'But / However',
                'meaning_zh' => '不过',
                'example_sentence' => '不错，不过还要改进。',
                'example_translation' => 'Not bad, but still need to improve.',
                'definition' => 'But, however',
                'sentences' => ['___没关系。', '___可以。', '___要注意。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '而且',
                'pinyin' => 'ér qiě',
                'simplified' => '而且',
                'traditional' => '而且',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Moreover / And',
                'meaning_zh' => '而且',
                'example_sentence' => '便宜，而且质量好。',
                'example_translation' => 'Cheap, and good quality.',
                'definition' => 'Moreover, and, furthermore',
                'sentences' => ['___很好。', '___方便。', '___便宜。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '或者',
                'pinyin' => 'huò zhě',
                'simplified' => '或者',
                'traditional' => '或者',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Or',
                'meaning_zh' => '或者',
                'example_sentence' => '茶或者咖啡。',
                'example_translation' => 'Tea or coffee.',
                'definition' => 'Or',
                'sentences' => ['___明天。', '___他。', '___那个。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '还是',
                'pinyin' => 'hái shi',
                'simplified' => '还是',
                'traditional' => '還是',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Or (in questions) / Still',
                'meaning_zh' => '还是',
                'example_sentence' => '茶还是咖啡？',
                'example_translation' => 'Tea or coffee?',
                'definition' => 'Or (in questions), still',
                'sentences' => ['___好。', '___不行。', '你___他？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '除了',
                'pinyin' => 'chú le',
                'simplified' => '除了',
                'traditional' => '除了',
                'part_of_speech' => 'preposition',
                'meaning' => 'Except / Besides',
                'meaning_zh' => '除了',
                'example_sentence' => '除了他，都去了。',
                'example_translation' => 'Except him, everyone went.',
                'definition' => 'Except, besides',
                'sentences' => ['___这个。', '___之外。', '___我。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '对于',
                'pinyin' => 'duì yú',
                'simplified' => '对于',
                'traditional' => '對於',
                'part_of_speech' => 'preposition',
                'meaning' => 'Regarding / As for',
                'meaning_zh' => '对于',
                'example_sentence' => '对于这个问题。',
                'example_translation' => 'Regarding this problem.',
                'definition' => 'Regarding, as for, with regard to',
                'sentences' => ['___我。', '___这事。', '___他。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '关于',
                'pinyin' => 'guān yú',
                'simplified' => '关于',
                'traditional' => '關於',
                'part_of_speech' => 'preposition',
                'meaning' => 'About / Concerning',
                'meaning_zh' => '关于',
                'example_sentence' => '关于这个话题。',
                'example_translation' => 'About this topic.',
                'definition' => 'About, concerning',
                'sentences' => ['___学习。', '___工作。', '___他。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '根据',
                'pinyin' => 'gēn jù',
                'simplified' => '根据',
                'traditional' => '根據',
                'part_of_speech' => 'preposition',
                'meaning' => 'According to / Based on',
                'meaning_zh' => '根据',
                'example_sentence' => '根据规定。',
                'example_translation' => 'According to the regulations.',
                'definition' => 'According to, based on',
                'sentences' => ['___情况。', '___报告。', '___经验。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '通过',
                'pinyin' => 'tōng guò',
                'simplified' => '通过',
                'traditional' => '通過',
                'part_of_speech' => 'preposition',
                'meaning' => 'Through / By means of',
                'meaning_zh' => '通过',
                'example_sentence' => '通过学习。',
                'example_translation' => 'Through learning.',
                'definition' => 'Through, by means of, to pass',
                'sentences' => ['___努力。', '___考试。', '___这个。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '由于',
                'pinyin' => 'yóu yú',
                'simplified' => '由于',
                'traditional' => '由於',
                'part_of_speech' => 'preposition',
                'meaning' => 'Due to / Owing to',
                'meaning_zh' => '由于',
                'example_sentence' => '由于下雨。',
                'example_translation' => 'Due to the rain.',
                'definition' => 'Due to, owing to, because of',
                'sentences' => ['___天气。', '___原因。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '为了',
                'pinyin' => 'wèi le',
                'simplified' => '为了',
                'traditional' => '為了',
                'part_of_speech' => 'preposition',
                'meaning' => 'For / In order to',
                'meaning_zh' => '为了',
                'example_sentence' => '为了学习。',
                'example_translation' => 'For learning.',
                'definition' => 'For, in order to',
                'sentences' => ['___你。', '___工作。', '___健康。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '向',
                'pinyin' => 'xiàng',
                'simplified' => '向',
                'traditional' => '向',
                'part_of_speech' => 'preposition',
                'meaning' => 'Towards / To',
                'meaning_zh' => '向',
                'example_sentence' => '向前走。',
                'example_translation' => 'Walk forward.',
                'definition' => 'Towards, to, from',
                'sentences' => ['___他学习。', '___东。', '___你道歉。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '按照',
                'pinyin' => 'àn zhào',
                'simplified' => '按照',
                'traditional' => '按照',
                'part_of_speech' => 'preposition',
                'meaning' => 'According to / In accordance with',
                'meaning_zh' => '按照',
                'example_sentence' => '按照规定。',
                'example_translation' => 'According to regulations.',
                'definition' => 'According to, in accordance with',
                'sentences' => ['___计划。', '___要求。', '___标准。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 82,
                'word' => '无论',
                'pinyin' => 'wú lùn',
                'simplified' => '无论',
                'traditional' => '無論',
                'part_of_speech' => 'conjunction',
                'meaning' => 'No matter / Regardless of',
                'meaning_zh' => '无论',
                'example_sentence' => '无论如何。',
                'example_translation' => 'No matter what.',
                'definition' => 'No matter, regardless of',
                'sentences' => ['___谁。', '___什么。', '___怎样。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 83: Measure Words (量词) - 20 words
        $measureWordsVocab = [
            [
                'topic_id' => 83,
                'word' => '个',
                'pinyin' => 'gè',
                'simplified' => '个',
                'traditional' => '個',
                'part_of_speech' => 'measure word',
                'meaning' => 'General measure word',
                'meaning_zh' => '个',
                'example_sentence' => '一个人。',
                'example_translation' => 'One person.',
                'definition' => 'General measure word for people, things',
                'sentences' => ['一___。', '两___。', '几___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '位',
                'pinyin' => 'wèi',
                'simplified' => '位',
                'traditional' => '位',
                'part_of_speech' => 'measure word',
                'meaning' => 'Polite measure word for people',
                'meaning_zh' => '位',
                'example_sentence' => '一位老师。',
                'example_translation' => 'One teacher.',
                'definition' => 'Polite measure word for people',
                'sentences' => ['一___。', '几___？', '这___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '张',
                'pinyin' => 'zhāng',
                'simplified' => '张',
                'traditional' => '張',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for flat objects',
                'meaning_zh' => '张',
                'example_sentence' => '一张纸。',
                'example_translation' => 'One sheet of paper.',
                'definition' => 'Measure word for flat objects (paper, table, bed)',
                'sentences' => ['一___桌子。', '___票。', '___照片。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '条',
                'pinyin' => 'tiáo',
                'simplified' => '条',
                'traditional' => '條',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for long objects',
                'meaning_zh' => '条',
                'example_sentence' => '一条鱼。',
                'example_translation' => 'One fish.',
                'definition' => 'Measure word for long objects (fish, pants, road)',
                'sentences' => ['一___路。', '___裤子。', '___消息。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '件',
                'pinyin' => 'jiàn',
                'simplified' => '件',
                'traditional' => '件',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for clothing and matters',
                'meaning_zh' => '件',
                'example_sentence' => '一件衣服。',
                'example_translation' => 'One piece of clothing.',
                'definition' => 'Measure word for clothing, matters, affairs',
                'sentences' => ['一___事。', '___衬衫。', '___行李。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '双',
                'pinyin' => 'shuāng',
                'simplified' => '双',
                'traditional' => '雙',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for pairs',
                'meaning_zh' => '双',
                'example_sentence' => '一双鞋。',
                'example_translation' => 'A pair of shoes.',
                'definition' => 'Measure word for pairs (shoes, chopsticks)',
                'sentences' => ['一___。', '___筷子。', '___手。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '只',
                'pinyin' => 'zhī',
                'simplified' => '只',
                'traditional' => '隻',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for animals',
                'meaning_zh' => '只',
                'example_sentence' => '一只猫。',
                'example_translation' => 'One cat.',
                'definition' => 'Measure word for animals, boats, containers',
                'sentences' => ['一___狗。', '___鸟。', '___眼睛。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '本',
                'pinyin' => 'běn',
                'simplified' => '本',
                'traditional' => '本',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for books',
                'meaning_zh' => '本',
                'example_sentence' => '一本书。',
                'example_translation' => 'One book.',
                'definition' => 'Measure word for books, magazines',
                'sentences' => ['一___。', '___杂志。', '___字典。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '支',
                'pinyin' => 'zhī',
                'simplified' => '支',
                'traditional' => '支',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for stick-like objects',
                'meaning_zh' => '支',
                'example_sentence' => '一支笔。',
                'example_translation' => 'One pen.',
                'definition' => 'Measure word for stick-like objects (pen, cigarette)',
                'sentences' => ['一___。', '___铅笔。', '___烟。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '把',
                'pinyin' => 'bǎ',
                'simplified' => '把',
                'traditional' => '把',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for objects with handle',
                'meaning_zh' => '把',
                'example_sentence' => '一把椅子。',
                'example_translation' => 'One chair.',
                'definition' => 'Measure word for objects with handle (chair, knife)',
                'sentences' => ['一___刀。', '___雨伞。', '___锁。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '杯',
                'pinyin' => 'bēi',
                'simplified' => '杯',
                'traditional' => '杯',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for cups',
                'meaning_zh' => '杯',
                'example_sentence' => '一杯水。',
                'example_translation' => 'A cup of water.',
                'definition' => 'Measure word for cups, glasses',
                'sentences' => ['一___茶。', '___咖啡。', '___酒。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '瓶',
                'pinyin' => 'píng',
                'simplified' => '瓶',
                'traditional' => '瓶',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for bottles',
                'meaning_zh' => '瓶',
                'example_sentence' => '一瓶水。',
                'example_translation' => 'A bottle of water.',
                'definition' => 'Measure word for bottles',
                'sentences' => ['一___。', '___啤酒。', '___牛奶。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '碗',
                'pinyin' => 'wǎn',
                'simplified' => '碗',
                'traditional' => '碗',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for bowls',
                'meaning_zh' => '碗',
                'example_sentence' => '一碗饭。',
                'example_translation' => 'A bowl of rice.',
                'definition' => 'Measure word for bowls',
                'sentences' => ['一___。', '___汤。', '___面。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '盘',
                'pinyin' => 'pán',
                'simplified' => '盘',
                'traditional' => '盤',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for dishes/plates',
                'meaning_zh' => '盘',
                'example_sentence' => '一盘菜。',
                'example_translation' => 'A plate of food.',
                'definition' => 'Measure word for dishes, plates',
                'sentences' => ['一___。', '___水果。', '___点心。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '块',
                'pinyin' => 'kuài',
                'simplified' => '块',
                'traditional' => '塊',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for pieces / Yuan',
                'meaning_zh' => '块',
                'example_sentence' => '一块钱。',
                'example_translation' => 'One yuan.',
                'definition' => 'Measure word for pieces, chunks, yuan',
                'sentences' => ['一___。', '___蛋糕。', '___肉。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '层',
                'pinyin' => 'céng',
                'simplified' => '层',
                'traditional' => '層',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for floors/layers',
                'meaning_zh' => '层',
                'example_sentence' => '一层楼。',
                'example_translation' => 'One floor.',
                'definition' => 'Measure word for floors, layers',
                'sentences' => ['一___。', '___楼。', '第三___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '辆',
                'pinyin' => 'liàng',
                'simplified' => '辆',
                'traditional' => '輛',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for vehicles',
                'meaning_zh' => '辆',
                'example_sentence' => '一辆车。',
                'example_translation' => 'One car.',
                'definition' => 'Measure word for vehicles',
                'sentences' => ['一___。', '___汽车。', '___自行车。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '种',
                'pinyin' => 'zhǒng',
                'simplified' => '种',
                'traditional' => '種',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for kinds/types',
                'meaning_zh' => '种',
                'example_sentence' => '一种方法。',
                'example_translation' => 'One kind of method.',
                'definition' => 'Measure word for kinds, types',
                'sentences' => ['一___。', '各___。', '___类。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '次',
                'pinyin' => 'cì',
                'simplified' => '次',
                'traditional' => '次',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for times/occasions',
                'meaning_zh' => '次',
                'example_sentence' => '一次机会。',
                'example_translation' => 'One opportunity.',
                'definition' => 'Measure word for times, occasions',
                'sentences' => ['一___。', '几___？', '第一___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 83,
                'word' => '遍',
                'pinyin' => 'biàn',
                'simplified' => '遍',
                'traditional' => '遍',
                'part_of_speech' => 'measure word',
                'meaning' => 'Measure word for times (from beginning to end)',
                'meaning_zh' => '遍',
                'example_sentence' => '读一遍。',
                'example_translation' => 'Read once through.',
                'definition' => 'Measure word for times (complete action)',
                'sentences' => ['一___。', '再说一___。', '看三___。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 84: Common Phrases (常用短语) - 20 words
        $commonPhrasesVocab = [
            [
                'topic_id' => 84,
                'word' => '一定',
                'pinyin' => 'yí dìng',
                'simplified' => '一定',
                'traditional' => '一定',
                'part_of_speech' => 'adverb',
                'meaning' => 'Certainly / Must',
                'meaning_zh' => '一定',
                'example_sentence' => '一定要去。',
                'example_translation' => 'Must go.',
                'definition' => 'Certainly, must, surely',
                'sentences' => ['___要。', '___会。', '___能。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '一直',
                'pinyin' => 'yì zhí',
                'simplified' => '一直',
                'traditional' => '一直',
                'part_of_speech' => 'adverb',
                'meaning' => 'Always / All along / Straight',
                'meaning_zh' => '一直',
                'example_sentence' => '一直在这里。',
                'example_translation' => 'Always here.',
                'definition' => 'Always, all along, straight',
                'sentences' => ['___往前。', '___等。', '___坚持。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '一起',
                'pinyin' => 'yì qǐ',
                'simplified' => '一起',
                'traditional' => '一起',
                'part_of_speech' => 'adverb',
                'meaning' => 'Together',
                'meaning_zh' => '一起',
                'example_sentence' => '一起去。',
                'example_translation' => 'Go together.',
                'definition' => 'Together',
                'sentences' => ['___做。', '___吃饭。', '___学习。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '一边',
                'pinyin' => 'yì biān',
                'simplified' => '一边',
                'traditional' => '一邊',
                'part_of_speech' => 'adverb',
                'meaning' => 'At the same time / One side',
                'meaning_zh' => '一边',
                'example_sentence' => '一边吃一边看。',
                'example_translation' => 'Eat while watching.',
                'definition' => 'At the same time, one side',
                'sentences' => ['___...___。', '___走___说。', '在___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '一些',
                'pinyin' => 'yì xiē',
                'simplified' => '一些',
                'traditional' => '一些',
                'part_of_speech' => 'measure word',
                'meaning' => 'Some / A few',
                'meaning_zh' => '一些',
                'example_sentence' => '买一些东西。',
                'example_translation' => 'Buy some things.',
                'definition' => 'Some, a few',
                'sentences' => ['___人。', '___问题。', '___建议。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '一会儿',
                'pinyin' => 'yí huìr',
                'simplified' => '一会儿',
                'traditional' => '一會兒',
                'part_of_speech' => 'noun',
                'meaning' => 'A moment / A while',
                'meaning_zh' => '一会儿',
                'example_sentence' => '等一会儿。',
                'example_translation' => 'Wait a moment.',
                'definition' => 'A moment, a while',
                'sentences' => ['___就好。', '___见。', '过___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '有点儿',
                'pinyin' => 'yǒu diǎnr',
                'simplified' => '有点儿',
                'traditional' => '有點兒',
                'part_of_speech' => 'adverb',
                'meaning' => 'A little / Somewhat',
                'meaning_zh' => '有点儿',
                'example_sentence' => '有点儿累。',
                'example_translation' => 'A little tired.',
                'definition' => 'A little, somewhat',
                'sentences' => ['___难。', '___贵。', '___冷。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '不少',
                'pinyin' => 'bù shǎo',
                'simplified' => '不少',
                'traditional' => '不少',
                'part_of_speech' => 'adjective',
                'meaning' => 'Quite a lot / Many',
                'meaning_zh' => '不少',
                'example_sentence' => '人不少。',
                'example_translation' => 'Quite a lot of people.',
                'definition' => 'Quite a lot, many, not few',
                'sentences' => ['___人。', '___钱。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '不错',
                'pinyin' => 'bú cuò',
                'simplified' => '不错',
                'traditional' => '不錯',
                'part_of_speech' => 'adjective',
                'meaning' => 'Not bad / Pretty good',
                'meaning_zh' => '不错',
                'example_sentence' => '味道不错。',
                'example_translation' => 'The taste is not bad.',
                'definition' => 'Not bad, pretty good',
                'sentences' => ['___的。', '___！', '还___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '没关系',
                'pinyin' => 'méi guān xi',
                'simplified' => '没关系',
                'traditional' => '沒關係',
                'part_of_speech' => 'phrase',
                'meaning' => 'It doesn\'t matter / Never mind',
                'meaning_zh' => '没关系',
                'example_sentence' => '没关系，不要紧。',
                'example_translation' => 'It doesn\'t matter, no problem.',
                'definition' => 'It doesn\'t matter, never mind',
                'sentences' => ['___。', '___的。', '真的___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '不要紧',
                'pinyin' => 'bú yào jǐn',
                'simplified' => '不要紧',
                'traditional' => '不要緊',
                'part_of_speech' => 'phrase',
                'meaning' => 'It doesn\'t matter / Not serious',
                'meaning_zh' => '不要紧',
                'example_sentence' => '不要紧，没事。',
                'example_translation' => 'It doesn\'t matter, it\'s okay.',
                'definition' => 'It doesn\'t matter, not serious',
                'sentences' => ['___。', '___的。', '真___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '怎么办',
                'pinyin' => 'zěn me bàn',
                'simplified' => '怎么办',
                'traditional' => '怎麼辦',
                'part_of_speech' => 'phrase',
                'meaning' => 'What to do',
                'meaning_zh' => '怎么办',
                'example_sentence' => '这怎么办？',
                'example_translation' => 'What should we do about this?',
                'definition' => 'What to do, what shall we do',
                'sentences' => ['___？', '该___？', '不知道___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '怎么样',
                'pinyin' => 'zěn me yàng',
                'simplified' => '怎么样',
                'traditional' => '怎麼樣',
                'part_of_speech' => 'phrase',
                'meaning' => 'How / How about',
                'meaning_zh' => '怎么样',
                'example_sentence' => '今天怎么样？',
                'example_translation' => 'How is today?',
                'definition' => 'How, how about',
                'sentences' => ['___？', '___啊？', '感觉___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '多少',
                'pinyin' => 'duō shao',
                'simplified' => '多少',
                'traditional' => '多少',
                'part_of_speech' => 'question word',
                'meaning' => 'How many / How much',
                'meaning_zh' => '多少',
                'example_sentence' => '多少钱？',
                'example_translation' => 'How much money?',
                'definition' => 'How many, how much',
                'sentences' => ['___？', '___人？', '___岁？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '为什么',
                'pinyin' => 'wèi shén me',
                'simplified' => '为什么',
                'traditional' => '為什麼',
                'part_of_speech' => 'question word',
                'meaning' => 'Why',
                'meaning_zh' => '为什么',
                'example_sentence' => '为什么不去？',
                'example_translation' => 'Why not go?',
                'definition' => 'Why',
                'sentences' => ['___？', '___要？', '___不？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '到底',
                'pinyin' => 'dào dǐ',
                'simplified' => '到底',
                'traditional' => '到底',
                'part_of_speech' => 'adverb',
                'meaning' => 'After all / In the end / On earth',
                'meaning_zh' => '到底',
                'example_sentence' => '到底怎么了？',
                'example_translation' => 'What on earth happened?',
                'definition' => 'After all, in the end, on earth',
                'sentences' => ['___是什么？', '___要不要？', '___去不去？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '其实',
                'pinyin' => 'qí shí',
                'simplified' => '其实',
                'traditional' => '其實',
                'part_of_speech' => 'adverb',
                'meaning' => 'Actually / In fact',
                'meaning_zh' => '其实',
                'example_sentence' => '其实很简单。',
                'example_translation' => 'Actually it\'s very simple.',
                'definition' => 'Actually, in fact',
                'sentences' => ['___不是。', '___很好。', '___我知道。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '其他',
                'pinyin' => 'qí tā',
                'simplified' => '其他',
                'traditional' => '其他',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Other / Others',
                'meaning_zh' => '其他',
                'example_sentence' => '其他人。',
                'example_translation' => 'Other people.',
                'definition' => 'Other, others',
                'sentences' => ['___的。', '___地方。', '___事情。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '各种',
                'pinyin' => 'gè zhǒng',
                'simplified' => '各种',
                'traditional' => '各種',
                'part_of_speech' => 'pronoun',
                'meaning' => 'Various / All kinds of',
                'meaning_zh' => '各种',
                'example_sentence' => '各种方法。',
                'example_translation' => 'Various methods.',
                'definition' => 'Various, all kinds of',
                'sentences' => ['___各样。', '___问题。', '___颜色。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 84,
                'word' => '这样',
                'pinyin' => 'zhè yàng',
                'simplified' => '这样',
                'traditional' => '這樣',
                'part_of_speech' => 'pronoun',
                'meaning' => 'This way / Like this / Such',
                'meaning_zh' => '这样',
                'example_sentence' => '就这样吧。',
                'example_translation' => 'Let\'s do it this way.',
                'definition' => 'This way, like this, such',
                'sentences' => ['___做。', '___的人。', '___好。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 85: Numbers and Time (数字和时间) - 20 words
        $numbersTimeVocab = [
            [
                'topic_id' => 85,
                'word' => '数字',
                'pinyin' => 'shù zì',
                'simplified' => '数字',
                'traditional' => '數字',
                'part_of_speech' => 'noun',
                'meaning' => 'Number / Numeral / Figure',
                'meaning_zh' => '数字',
                'example_sentence' => '写数字。',
                'example_translation' => 'Write numbers.',
                'definition' => 'Number, numeral, figure',
                'sentences' => ['___很大。', '___统计。', '___化。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '数量',
                'pinyin' => 'shù liàng',
                'simplified' => '数量',
                'traditional' => '數量',
                'part_of_speech' => 'noun',
                'meaning' => 'Quantity / Amount',
                'meaning_zh' => '数量',
                'example_sentence' => '数量很多。',
                'example_translation' => 'Large quantity.',
                'definition' => 'Quantity, amount',
                'sentences' => ['___多。', '___统计。', '___有限。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '百',
                'pinyin' => 'bǎi',
                'simplified' => '百',
                'traditional' => '百',
                'part_of_speech' => 'number',
                'meaning' => 'Hundred',
                'meaning_zh' => '百',
                'example_sentence' => '一百人。',
                'example_translation' => 'One hundred people.',
                'definition' => 'Hundred',
                'sentences' => ['一___。', '___分之。', '___年。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '千',
                'pinyin' => 'qiān',
                'simplified' => '千',
                'traditional' => '千',
                'part_of_speech' => 'number',
                'meaning' => 'Thousand',
                'meaning_zh' => '千',
                'example_sentence' => '一千元。',
                'example_translation' => 'One thousand yuan.',
                'definition' => 'Thousand',
                'sentences' => ['一___。', '___米。', '___年。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '万',
                'pinyin' => 'wàn',
                'simplified' => '万',
                'traditional' => '萬',
                'part_of_speech' => 'number',
                'meaning' => 'Ten thousand',
                'meaning_zh' => '万',
                'example_sentence' => '一万人。',
                'example_translation' => 'Ten thousand people.',
                'definition' => 'Ten thousand',
                'sentences' => ['一___。', '___元。', '___一。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '半',
                'pinyin' => 'bàn',
                'simplified' => '半',
                'traditional' => '半',
                'part_of_speech' => 'number',
                'meaning' => 'Half',
                'meaning_zh' => '半',
                'example_sentence' => '半个小时。',
                'example_translation' => 'Half an hour.',
                'definition' => 'Half',
                'sentences' => ['___天。', '___年。', '一___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '倍',
                'pinyin' => 'bèi',
                'simplified' => '倍',
                'traditional' => '倍',
                'part_of_speech' => 'measure word',
                'meaning' => 'Times / -fold',
                'meaning_zh' => '倍',
                'example_sentence' => '两倍。',
                'example_translation' => 'Two times.',
                'definition' => 'Times, -fold, multiple',
                'sentences' => ['三___。', '___数。', '___增。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '刻',
                'pinyin' => 'kè',
                'simplified' => '刻',
                'traditional' => '刻',
                'part_of_speech' => 'measure word',
                'meaning' => 'Quarter (of an hour)',
                'meaning_zh' => '刻',
                'example_sentence' => '三点一刻。',
                'example_translation' => 'Three fifteen.',
                'definition' => 'Quarter (of an hour), 15 minutes',
                'sentences' => ['一___。', '三___。', '差一___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '钟头',
                'pinyin' => 'zhōng tóu',
                'simplified' => '钟头',
                'traditional' => '鐘頭',
                'part_of_speech' => 'noun',
                'meaning' => 'Hour',
                'meaning_zh' => '钟头',
                'example_sentence' => '两个钟头。',
                'example_translation' => 'Two hours.',
                'definition' => 'Hour',
                'sentences' => ['一个___。', '几个___？', '___前。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '秒',
                'pinyin' => 'miǎo',
                'simplified' => '秒',
                'traditional' => '秒',
                'part_of_speech' => 'measure word',
                'meaning' => 'Second',
                'meaning_zh' => '秒',
                'example_sentence' => '十秒钟。',
                'example_translation' => 'Ten seconds.',
                'definition' => 'Second',
                'sentences' => ['一___。', '___钟。', '几___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '刚',
                'pinyin' => 'gāng',
                'simplified' => '刚',
                'traditional' => '剛',
                'part_of_speech' => 'adverb',
                'meaning' => 'Just / Just now',
                'meaning_zh' => '刚',
                'example_sentence' => '刚到。',
                'example_translation' => 'Just arrived.',
                'definition' => 'Just, just now',
                'sentences' => ['___好。', '___来。', '___开始。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '刚好',
                'pinyin' => 'gāng hǎo',
                'simplified' => '刚好',
                'traditional' => '剛好',
                'part_of_speech' => 'adverb',
                'meaning' => 'Just right / Happen to',
                'meaning_zh' => '刚好',
                'example_sentence' => '刚好十点。',
                'example_translation' => 'Just right at ten o\'clock.',
                'definition' => 'Just right, happen to',
                'sentences' => ['___合适。', '___在这。', '___够。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '曾经',
                'pinyin' => 'céng jīng',
                'simplified' => '曾经',
                'traditional' => '曾經',
                'part_of_speech' => 'adverb',
                'meaning' => 'Once / Ever',
                'meaning_zh' => '曾经',
                'example_sentence' => '曾经去过。',
                'example_translation' => 'Have been there before.',
                'definition' => 'Once, ever, formerly',
                'sentences' => ['___有过。', '___说过。', '___是。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '从前',
                'pinyin' => 'cóng qián',
                'simplified' => '从前',
                'traditional' => '從前',
                'part_of_speech' => 'noun',
                'meaning' => 'In the past / Formerly',
                'meaning_zh' => '从前',
                'example_sentence' => '从前有一个人。',
                'example_translation' => 'Once upon a time there was a person.',
                'definition' => 'In the past, formerly, once upon a time',
                'sentences' => ['___的事。', '___这里。', '___是。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '过去',
                'pinyin' => 'guò qu',
                'simplified' => '过去',
                'traditional' => '過去',
                'part_of_speech' => 'noun',
                'meaning' => 'Past / To pass',
                'meaning_zh' => '过去',
                'example_sentence' => '过去的事。',
                'example_translation' => 'Things of the past.',
                'definition' => 'Past, to pass',
                'sentences' => ['___了。', '___的时候。', '___看看。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '现在',
                'pinyin' => 'xiàn zài',
                'simplified' => '现在',
                'traditional' => '現在',
                'part_of_speech' => 'noun',
                'meaning' => 'Now / Present',
                'meaning_zh' => '现在',
                'example_sentence' => '现在几点？',
                'example_translation' => 'What time is it now?',
                'definition' => 'Now, present, current',
                'sentences' => ['___开始。', '___的。', '从___起。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '将来',
                'pinyin' => 'jiāng lái',
                'simplified' => '将来',
                'traditional' => '將來',
                'part_of_speech' => 'noun',
                'meaning' => 'Future / In the future',
                'meaning_zh' => '将来',
                'example_sentence' => '将来的计划。',
                'example_translation' => 'Future plans.',
                'definition' => 'Future, in the future',
                'sentences' => ['___会。', '___的事。', '___想。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '未来',
                'pinyin' => 'wèi lái',
                'simplified' => '未来',
                'traditional' => '未來',
                'part_of_speech' => 'noun',
                'meaning' => 'Future',
                'meaning_zh' => '未来',
                'example_sentence' => '未来会更好。',
                'example_translation' => 'The future will be better.',
                'definition' => 'Future',
                'sentences' => ['___的。', '___发展。', '___计划。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '永远',
                'pinyin' => 'yǒng yuǎn',
                'simplified' => '永远',
                'traditional' => '永遠',
                'part_of_speech' => 'adverb',
                'meaning' => 'Forever / Always',
                'meaning_zh' => '永远',
                'example_sentence' => '永远记得。',
                'example_translation' => 'Remember forever.',
                'definition' => 'Forever, always, permanently',
                'sentences' => ['___不会。', '___爱你。', '___是。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 85,
                'word' => '暂时',
                'pinyin' => 'zàn shí',
                'simplified' => '暂时',
                'traditional' => '暫時',
                'part_of_speech' => 'adverb',
                'meaning' => 'Temporarily / For the moment',
                'meaning_zh' => '暂时',
                'example_sentence' => '暂时不去。',
                'example_translation' => 'Not going for now.',
                'definition' => 'Temporarily, for the moment',
                'sentences' => ['___的。', '___没有。', '___等待。'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($conjunctionsVocab, $measureWordsVocab, $commonPhrasesVocab, $numbersTimeVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
