<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics8to11Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 70: Apologies and Thanks (道歉和感谢) - 20 words
        $apologiesVocab = [
            [
                'topic_id' => 70,
                'word' => '道歉',
                'pinyin' => 'dào qiàn',
                'simplified' => '道歉',
                'traditional' => '道歉',
                'part_of_speech' => 'verb',
                'meaning' => 'To apologize',
                'meaning_zh' => '道歉',
                'example_sentence' => '我向你道歉。',
                'example_translation' => 'I apologize to you.',
                'definition' => 'To apologize, apology',
                'sentences' => ['___了。', '___态度。', '向你___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '对不起',
                'pinyin' => 'duì bu qǐ',
                'simplified' => '对不起',
                'traditional' => '對不起',
                'part_of_speech' => 'phrase',
                'meaning' => 'I\'m sorry',
                'meaning_zh' => '对不起',
                'example_sentence' => '对不起，我迟到了。',
                'example_translation' => 'Sorry, I\'m late.',
                'definition' => 'Sorry, excuse me',
                'sentences' => ['___！', '___，打扰了。', '___，我错了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '抱歉',
                'pinyin' => 'bào qiàn',
                'simplified' => '抱歉',
                'traditional' => '抱歉',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sorry / To feel apologetic',
                'meaning_zh' => '抱歉',
                'example_sentence' => '真抱歉。',
                'example_translation' => 'Really sorry.',
                'definition' => 'Sorry, to feel apologetic',
                'sentences' => ['很___。', '___了。', '___打扰。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '不好意思',
                'pinyin' => 'bù hǎo yì si',
                'simplified' => '不好意思',
                'traditional' => '不好意思',
                'part_of_speech' => 'phrase',
                'meaning' => 'Sorry / Embarrassed',
                'meaning_zh' => '不好意思',
                'example_sentence' => '不好意思，麻烦你了。',
                'example_translation' => 'Sorry to trouble you.',
                'definition' => 'Sorry, embarrassed, feel embarrassed',
                'sentences' => ['___！', '___说。', '___问。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '原谅',
                'pinyin' => 'yuán liàng',
                'simplified' => '原谅',
                'traditional' => '原諒',
                'part_of_speech' => 'verb',
                'meaning' => 'To forgive / To excuse',
                'meaning_zh' => '原谅',
                'example_sentence' => '请原谅我。',
                'example_translation' => 'Please forgive me.',
                'definition' => 'To forgive, to excuse',
                'sentences' => ['___我。', '___他。', '___错误。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '宽恕',
                'pinyin' => 'kuān shù',
                'simplified' => '宽恕',
                'traditional' => '寬恕',
                'part_of_speech' => 'verb',
                'meaning' => 'To forgive / To pardon',
                'meaning_zh' => '宽恕',
                'example_sentence' => '请宽恕我的错误。',
                'example_translation' => 'Please forgive my mistake.',
                'definition' => 'To forgive, to pardon',
                'sentences' => ['___他。', '___错误。', '___我。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '感谢',
                'pinyin' => 'gǎn xiè',
                'simplified' => '感谢',
                'traditional' => '感謝',
                'part_of_speech' => 'verb',
                'meaning' => 'To thank',
                'meaning_zh' => '感谢',
                'example_sentence' => '感谢你的帮助。',
                'example_translation' => 'Thank you for your help.',
                'definition' => 'To thank, thanks',
                'sentences' => ['___你。', '___帮助。', '___支持。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '谢谢',
                'pinyin' => 'xiè xie',
                'simplified' => '谢谢',
                'traditional' => '謝謝',
                'part_of_speech' => 'verb',
                'meaning' => 'Thank you',
                'meaning_zh' => '谢谢',
                'example_sentence' => '谢谢你！',
                'example_translation' => 'Thank you!',
                'definition' => 'Thank you, thanks',
                'sentences' => ['___！', '___帮忙。', '___你。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '感恩',
                'pinyin' => 'gǎn ēn',
                'simplified' => '感恩',
                'traditional' => '感恩',
                'part_of_speech' => 'verb',
                'meaning' => 'To be grateful',
                'meaning_zh' => '感恩',
                'example_sentence' => '我很感恩。',
                'example_translation' => 'I am very grateful.',
                'definition' => 'To be grateful, gratitude',
                'sentences' => ['___之心。', '___的心。', '___节。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '麻烦',
                'pinyin' => 'má fan',
                'simplified' => '麻烦',
                'traditional' => '麻煩',
                'part_of_speech' => 'verb',
                'meaning' => 'To trouble / Troublesome',
                'meaning_zh' => '麻烦',
                'example_sentence' => '麻烦你了。',
                'example_translation' => 'Sorry to trouble you.',
                'definition' => 'To trouble, troublesome, trouble',
                'sentences' => ['___你。', '很___。', '___的事。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '客气',
                'pinyin' => 'kè qi',
                'simplified' => '客气',
                'traditional' => '客氣',
                'part_of_speech' => 'adjective',
                'meaning' => 'Polite / Courteous',
                'meaning_zh' => '客气',
                'example_sentence' => '不用客气。',
                'example_translation' => 'You\'re welcome.',
                'definition' => 'Polite, courteous, modest',
                'sentences' => ['不___。', '太___了。', '___话。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '礼貌',
                'pinyin' => 'lǐ mào',
                'simplified' => '礼貌',
                'traditional' => '禮貌',
                'part_of_speech' => 'noun',
                'meaning' => 'Polite / Courtesy',
                'meaning_zh' => '礼貌',
                'example_sentence' => '很有礼貌。',
                'example_translation' => 'Very polite.',
                'definition' => 'Polite, courtesy, manners',
                'sentences' => ['有___。', '___用语。', '___待人。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '尊重',
                'pinyin' => 'zūn zhòng',
                'simplified' => '尊重',
                'traditional' => '尊重',
                'part_of_speech' => 'verb',
                'meaning' => 'To respect',
                'meaning_zh' => '尊重',
                'example_sentence' => '我尊重你的选择。',
                'example_translation' => 'I respect your choice.',
                'definition' => 'To respect, respect',
                'sentences' => ['___他人。', '___意见。', '___选择。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '帮忙',
                'pinyin' => 'bāng máng',
                'simplified' => '帮忙',
                'traditional' => '幫忙',
                'part_of_speech' => 'verb',
                'meaning' => 'To help / To do a favor',
                'meaning_zh' => '帮忙',
                'example_sentence' => '请帮忙。',
                'example_translation' => 'Please help.',
                'definition' => 'To help, to do a favor',
                'sentences' => ['___了。', '___吗？', '___的事。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '帮助',
                'pinyin' => 'bāng zhù',
                'simplified' => '帮助',
                'traditional' => '幫助',
                'part_of_speech' => 'verb',
                'meaning' => 'To help',
                'meaning_zh' => '帮助',
                'example_sentence' => '谢谢你的帮助。',
                'example_translation' => 'Thank you for your help.',
                'definition' => 'To help, help, assistance',
                'sentences' => ['___他人。', '___我。', '___很大。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '支援',
                'pinyin' => 'zhī yuán',
                'simplified' => '支援',
                'traditional' => '支援',
                'part_of_speech' => 'verb',
                'meaning' => 'To support / To assist',
                'meaning_zh' => '支援',
                'example_sentence' => '感谢你的支援。',
                'example_translation' => 'Thank you for your support.',
                'definition' => 'To support, to assist, support',
                'sentences' => ['___我。', '___工作。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '照顾',
                'pinyin' => 'zhào gù',
                'simplified' => '照顾',
                'traditional' => '照顧',
                'part_of_speech' => 'verb',
                'meaning' => 'To take care of / To look after',
                'meaning_zh' => '照顾',
                'example_sentence' => '谢谢你照顾我。',
                'example_translation' => 'Thank you for taking care of me.',
                'definition' => 'To take care of, to look after',
                'sentences' => ['___他。', '___好。', '___自己。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '关心',
                'pinyin' => 'guān xīn',
                'simplified' => '关心',
                'traditional' => '關心',
                'part_of_speech' => 'verb',
                'meaning' => 'To care about / To be concerned',
                'meaning_zh' => '关心',
                'example_sentence' => '谢谢你关心我。',
                'example_translation' => 'Thank you for caring about me.',
                'definition' => 'To care about, to be concerned',
                'sentences' => ['___他。', '___你。', '___的人。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '体谅',
                'pinyin' => 'tǐ liàng',
                'simplified' => '体谅',
                'traditional' => '體諒',
                'part_of_speech' => 'verb',
                'meaning' => 'To understand / To make allowances for',
                'meaning_zh' => '体谅',
                'example_sentence' => '请体谅我的难处。',
                'example_translation' => 'Please understand my difficulties.',
                'definition' => 'To understand, to make allowances for',
                'sentences' => ['___他。', '___一下。', '___困难。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 70,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb',
                'meaning' => 'To understand',
                'meaning_zh' => '理解',
                'example_sentence' => '谢谢你的理解。',
                'example_translation' => 'Thank you for your understanding.',
                'definition' => 'To understand, understanding',
                'sentences' => ['___我。', '___了。', '___能力。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 71: Invitations and Suggestions (邀请和建议) - 20 words
        $invitationsVocab = [
            [
                'topic_id' => 71,
                'word' => '邀请',
                'pinyin' => 'yāo qǐng',
                'simplified' => '邀请',
                'traditional' => '邀請',
                'part_of_speech' => 'verb',
                'meaning' => 'To invite',
                'meaning_zh' => '邀请',
                'example_sentence' => '我邀请你参加。',
                'example_translation' => 'I invite you to attend.',
                'definition' => 'To invite, invitation',
                'sentences' => ['___你。', '___朋友。', '___函。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '邀请函',
                'pinyin' => 'yāo qǐng hán',
                'simplified' => '邀请函',
                'traditional' => '邀請函',
                'part_of_speech' => 'noun',
                'meaning' => 'Invitation letter',
                'meaning_zh' => '邀请函',
                'example_sentence' => '收到邀请函。',
                'example_translation' => 'Received the invitation letter.',
                'definition' => 'Invitation letter',
                'sentences' => ['___发出。', '___收到。', '___内容。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '接受',
                'pinyin' => 'jiē shòu',
                'simplified' => '接受',
                'traditional' => '接受',
                'part_of_speech' => 'verb',
                'meaning' => 'To accept',
                'meaning_zh' => '接受',
                'example_sentence' => '我接受你的邀请。',
                'example_translation' => 'I accept your invitation.',
                'definition' => 'To accept',
                'sentences' => ['___邀请。', '___了。', '___建议。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '拒绝',
                'pinyin' => 'jù jué',
                'simplified' => '拒绝',
                'traditional' => '拒絕',
                'part_of_speech' => 'verb',
                'meaning' => 'To refuse / To reject',
                'meaning_zh' => '拒绝',
                'example_sentence' => '我不能拒绝。',
                'example_translation' => 'I can\'t refuse.',
                'definition' => 'To refuse, to reject',
                'sentences' => ['___了。', '___邀请。', '___理由。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '参加',
                'pinyin' => 'cān jiā',
                'simplified' => '参加',
                'traditional' => '參加',
                'part_of_speech' => 'verb',
                'meaning' => 'To participate / To attend',
                'meaning_zh' => '参加',
                'example_sentence' => '我参加活动。',
                'example_translation' => 'I participate in the activity.',
                'definition' => 'To participate, to attend',
                'sentences' => ['___活动。', '___会议。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '出席',
                'pinyin' => 'chū xí',
                'simplified' => '出席',
                'traditional' => '出席',
                'part_of_speech' => 'verb',
                'meaning' => 'To attend / To be present',
                'meaning_zh' => '出席',
                'example_sentence' => '出席会议。',
                'example_translation' => 'Attend the meeting.',
                'definition' => 'To attend, to be present',
                'sentences' => ['___会议。', '___活动。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '聚会',
                'pinyin' => 'jù huì',
                'simplified' => '聚会',
                'traditional' => '聚會',
                'part_of_speech' => 'noun',
                'meaning' => 'Gathering / Party',
                'meaning_zh' => '聚会',
                'example_sentence' => '参加聚会。',
                'example_translation' => 'Attend the party.',
                'definition' => 'Gathering, party, to get together',
                'sentences' => ['___了。', '___活动。', '家庭___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '派对',
                'pinyin' => 'pài duì',
                'simplified' => '派对',
                'traditional' => '派對',
                'part_of_speech' => 'noun',
                'meaning' => 'Party',
                'meaning_zh' => '派对',
                'example_sentence' => '举办派对。',
                'example_translation' => 'Hold a party.',
                'definition' => 'Party',
                'sentences' => ['___很热闹。', '生日___。', '___活动。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '约会',
                'pinyin' => 'yuē huì',
                'simplified' => '约会',
                'traditional' => '約會',
                'part_of_speech' => 'noun',
                'meaning' => 'Date / Appointment',
                'meaning_zh' => '约会',
                'example_sentence' => '我有个约会。',
                'example_translation' => 'I have a date.',
                'definition' => 'Date, appointment',
                'sentences' => ['___了。', '___时间。', '___对象。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '约定',
                'pinyin' => 'yuē dìng',
                'simplified' => '约定',
                'traditional' => '約定',
                'part_of_speech' => 'verb',
                'meaning' => 'To agree on / To arrange',
                'meaning_zh' => '约定',
                'example_sentence' => '我们约定明天见。',
                'example_translation' => 'We agreed to meet tomorrow.',
                'definition' => 'To agree on, to arrange, agreement',
                'sentences' => ['___时间。', '___了。', '___地点。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '提议',
                'pinyin' => 'tí yì',
                'simplified' => '提议',
                'traditional' => '提議',
                'part_of_speech' => 'verb',
                'meaning' => 'To propose / Proposal',
                'meaning_zh' => '提议',
                'example_sentence' => '我提议去公园。',
                'example_translation' => 'I propose going to the park.',
                'definition' => 'To propose, proposal',
                'sentences' => ['___了。', '___方案。', '___讨论。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '建议',
                'pinyin' => 'jiàn yì',
                'simplified' => '建议',
                'traditional' => '建議',
                'part_of_speech' => 'verb',
                'meaning' => 'To suggest / Suggestion',
                'meaning_zh' => '建议',
                'example_sentence' => '我建议早点去。',
                'example_translation' => 'I suggest going earlier.',
                'definition' => 'To suggest, suggestion',
                'sentences' => ['___你。', '___很好。', '___方案。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '推荐',
                'pinyin' => 'tuī jiàn',
                'simplified' => '推荐',
                'traditional' => '推薦',
                'part_of_speech' => 'verb',
                'meaning' => 'To recommend',
                'meaning_zh' => '推荐',
                'example_sentence' => '我推荐这家餐厅。',
                'example_translation' => 'I recommend this restaurant.',
                'definition' => 'To recommend, recommendation',
                'sentences' => ['___给你。', '___书。', '___餐厅。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '欢迎',
                'pinyin' => 'huān yíng',
                'simplified' => '欢迎',
                'traditional' => '歡迎',
                'part_of_speech' => 'verb',
                'meaning' => 'To welcome',
                'meaning_zh' => '欢迎',
                'example_sentence' => '欢迎你来！',
                'example_translation' => 'Welcome!',
                'definition' => 'To welcome, welcome',
                'sentences' => ['___你。', '___光临。', '___参加。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '期待',
                'pinyin' => 'qī dài',
                'simplified' => '期待',
                'traditional' => '期待',
                'part_of_speech' => 'verb',
                'meaning' => 'To expect / To look forward to',
                'meaning_zh' => '期待',
                'example_sentence' => '我期待见到你。',
                'example_translation' => 'I look forward to seeing you.',
                'definition' => 'To expect, to look forward to',
                'sentences' => ['___你。', '___已久。', '___的事。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '盼望',
                'pinyin' => 'pàn wàng',
                'simplified' => '盼望',
                'traditional' => '盼望',
                'part_of_speech' => 'verb',
                'meaning' => 'To hope for / To long for',
                'meaning_zh' => '盼望',
                'example_sentence' => '我盼望见到你。',
                'example_translation' => 'I hope to see you.',
                'definition' => 'To hope for, to long for',
                'sentences' => ['___你。', '___已久。', '___的事。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '安排',
                'pinyin' => 'ān pái',
                'simplified' => '安排',
                'traditional' => '安排',
                'part_of_speech' => 'verb',
                'meaning' => 'To arrange / To plan',
                'meaning_zh' => '安排',
                'example_sentence' => '我安排时间。',
                'example_translation' => 'I arrange the time.',
                'definition' => 'To arrange, to plan, arrangement',
                'sentences' => ['___好了。', '___时间。', '___活动。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '商量',
                'pinyin' => 'shāng liang',
                'simplified' => '商量',
                'traditional' => '商量',
                'part_of_speech' => 'verb',
                'meaning' => 'To discuss / To consult',
                'meaning_zh' => '商量',
                'example_sentence' => '我们商量一下。',
                'example_translation' => 'Let\'s discuss it.',
                'definition' => 'To discuss, to consult',
                'sentences' => ['___了。', '___时间。', '___方案。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '决定',
                'pinyin' => 'jué dìng',
                'simplified' => '决定',
                'traditional' => '決定',
                'part_of_speech' => 'verb',
                'meaning' => 'To decide / Decision',
                'meaning_zh' => '决定',
                'example_sentence' => '我决定去。',
                'example_translation' => 'I decide to go.',
                'definition' => 'To decide, decision',
                'sentences' => ['___了。', '___方案。', '___权。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 71,
                'word' => '选择',
                'pinyin' => 'xuǎn zé',
                'simplified' => '选择',
                'traditional' => '選擇',
                'part_of_speech' => 'verb',
                'meaning' => 'To choose / Choice',
                'meaning_zh' => '选择',
                'example_sentence' => '这是你的选择。',
                'example_translation' => 'This is your choice.',
                'definition' => 'To choose, choice',
                'sentences' => ['___了。', '___方案。', '___权。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 72: Feelings and Relationships (感情和关系) - 20 words
        $relationshipsVocab = [
            [
                'topic_id' => 72,
                'word' => '感情',
                'pinyin' => 'gǎn qíng',
                'simplified' => '感情',
                'traditional' => '感情',
                'part_of_speech' => 'noun',
                'meaning' => 'Emotion / Feeling / Affection',
                'meaning_zh' => '感情',
                'example_sentence' => '我们的感情很好。',
                'example_translation' => 'Our relationship is very good.',
                'definition' => 'Emotion, feeling, affection',
                'sentences' => ['___深厚。', '___问题。', '___交流。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '关系',
                'pinyin' => 'guān xi',
                'simplified' => '关系',
                'traditional' => '關係',
                'part_of_speech' => 'noun',
                'meaning' => 'Relationship / Connection',
                'meaning_zh' => '关系',
                'example_sentence' => '我们的关系很好。',
                'example_translation' => 'Our relationship is very good.',
                'definition' => 'Relationship, connection',
                'sentences' => ['___好。', '___复杂。', '___网。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '爱',
                'pinyin' => 'ài',
                'simplified' => '爱',
                'traditional' => '愛',
                'part_of_speech' => 'verb',
                'meaning' => 'To love',
                'meaning_zh' => '爱',
                'example_sentence' => '我爱你。',
                'example_translation' => 'I love you.',
                'definition' => 'To love, love',
                'sentences' => ['___你。', '___情。', '___的人。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '喜欢',
                'pinyin' => 'xǐ huan',
                'simplified' => '喜欢',
                'traditional' => '喜歡',
                'part_of_speech' => 'verb',
                'meaning' => 'To like',
                'meaning_zh' => '喜欢',
                'example_sentence' => '我喜欢你。',
                'example_translation' => 'I like you.',
                'definition' => 'To like',
                'sentences' => ['___你。', '___的东西。', '很___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '讨厌',
                'pinyin' => 'tǎo yàn',
                'simplified' => '讨厌',
                'traditional' => '討厭',
                'part_of_speech' => 'verb',
                'meaning' => 'To dislike / To hate',
                'meaning_zh' => '讨厌',
                'example_sentence' => '我讨厌这个。',
                'example_translation' => 'I hate this.',
                'definition' => 'To dislike, to hate, annoying',
                'sentences' => ['___他。', '___的人。', '很___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '恨',
                'pinyin' => 'hèn',
                'simplified' => '恨',
                'traditional' => '恨',
                'part_of_speech' => 'verb',
                'meaning' => 'To hate',
                'meaning_zh' => '恨',
                'example_sentence' => '我恨他。',
                'example_translation' => 'I hate him.',
                'definition' => 'To hate, hatred',
                'sentences' => ['___他。', '___意。', '___不得。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '想念',
                'pinyin' => 'xiǎng niàn',
                'simplified' => '想念',
                'traditional' => '想念',
                'part_of_speech' => 'verb',
                'meaning' => 'To miss / To think of',
                'meaning_zh' => '想念',
                'example_sentence' => '我想念你。',
                'example_translation' => 'I miss you.',
                'definition' => 'To miss, to think of',
                'sentences' => ['___你。', '___家人。', '___的人。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '思念',
                'pinyin' => 'sī niàn',
                'simplified' => '思念',
                'traditional' => '思念',
                'part_of_speech' => 'verb',
                'meaning' => 'To miss / To long for',
                'meaning_zh' => '思念',
                'example_sentence' => '我思念家乡。',
                'example_translation' => 'I miss my hometown.',
                'definition' => 'To miss, to long for',
                'sentences' => ['___家乡。', '___之情。', '___的人。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '信任',
                'pinyin' => 'xìn rèn',
                'simplified' => '信任',
                'traditional' => '信任',
                'part_of_speech' => 'verb',
                'meaning' => 'To trust',
                'meaning_zh' => '信任',
                'example_sentence' => '我信任你。',
                'example_translation' => 'I trust you.',
                'definition' => 'To trust, trust',
                'sentences' => ['___你。', '___关系。', '___度。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '相信',
                'pinyin' => 'xiāng xìn',
                'simplified' => '相信',
                'traditional' => '相信',
                'part_of_speech' => 'verb',
                'meaning' => 'To believe',
                'meaning_zh' => '相信',
                'example_sentence' => '我相信你。',
                'example_translation' => 'I believe you.',
                'definition' => 'To believe',
                'sentences' => ['___你。', '___自己。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '怀疑',
                'pinyin' => 'huái yí',
                'simplified' => '怀疑',
                'traditional' => '懷疑',
                'part_of_speech' => 'verb',
                'meaning' => 'To doubt / To suspect',
                'meaning_zh' => '怀疑',
                'example_sentence' => '我怀疑他。',
                'example_translation' => 'I doubt him.',
                'definition' => 'To doubt, to suspect',
                'sentences' => ['___他。', '___了。', '___对象。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '嫉妒',
                'pinyin' => 'jí dù',
                'simplified' => '嫉妒',
                'traditional' => '嫉妒',
                'part_of_speech' => 'verb',
                'meaning' => 'To be jealous / Jealousy',
                'meaning_zh' => '嫉妒',
                'example_sentence' => '不要嫉妒别人。',
                'example_translation' => 'Don\'t be jealous of others.',
                'definition' => 'To be jealous, jealousy',
                'sentences' => ['___他。', '___心。', '___的人。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '羡慕',
                'pinyin' => 'xiàn mù',
                'simplified' => '羡慕',
                'traditional' => '羨慕',
                'part_of_speech' => 'verb',
                'meaning' => 'To envy / To admire',
                'meaning_zh' => '羡慕',
                'example_sentence' => '我羡慕你。',
                'example_translation' => 'I envy you.',
                'definition' => 'To envy, to admire',
                'sentences' => ['___他。', '___的生活。', '很___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '依赖',
                'pinyin' => 'yī lài',
                'simplified' => '依赖',
                'traditional' => '依賴',
                'part_of_speech' => 'verb',
                'meaning' => 'To depend on / To rely on',
                'meaning_zh' => '依赖',
                'example_sentence' => '不要依赖别人。',
                'example_translation' => 'Don\'t depend on others.',
                'definition' => 'To depend on, to rely on',
                'sentences' => ['___他人。', '___性。', '___关系。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '独立',
                'pinyin' => 'dú lì',
                'simplified' => '独立',
                'traditional' => '獨立',
                'part_of_speech' => 'adjective',
                'meaning' => 'Independent',
                'meaning_zh' => '独立',
                'example_sentence' => '要独立生活。',
                'example_translation' => 'Live independently.',
                'definition' => 'Independent, independence',
                'sentences' => ['___了。', '___生活。', '___思考。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '亲密',
                'pinyin' => 'qīn mì',
                'simplified' => '亲密',
                'traditional' => '親密',
                'part_of_speech' => 'adjective',
                'meaning' => 'Intimate / Close',
                'meaning_zh' => '亲密',
                'example_sentence' => '我们关系很亲密。',
                'example_translation' => 'Our relationship is very close.',
                'definition' => 'Intimate, close',
                'sentences' => ['___关系。', '___朋友。', '___接触。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '疏远',
                'pinyin' => 'shū yuǎn',
                'simplified' => '疏远',
                'traditional' => '疏遠',
                'part_of_speech' => 'verb',
                'meaning' => 'To drift apart / To become estranged',
                'meaning_zh' => '疏远',
                'example_sentence' => '我们疏远了。',
                'example_translation' => 'We drifted apart.',
                'definition' => 'To drift apart, to become estranged',
                'sentences' => ['___了。', '___关系。', '___朋友。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '友谊',
                'pinyin' => 'yǒu yì',
                'simplified' => '友谊',
                'traditional' => '友誼',
                'part_of_speech' => 'noun',
                'meaning' => 'Friendship',
                'meaning_zh' => '友谊',
                'example_sentence' => '珍惜友谊。',
                'example_translation' => 'Cherish friendship.',
                'definition' => 'Friendship',
                'sentences' => ['___深厚。', '___长存。', '___第一。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '友情',
                'pinyin' => 'yǒu qíng',
                'simplified' => '友情',
                'traditional' => '友情',
                'part_of_speech' => 'noun',
                'meaning' => 'Friendship',
                'meaning_zh' => '友情',
                'example_sentence' => '我们的友情很深。',
                'example_translation' => 'Our friendship is very deep.',
                'definition' => 'Friendship',
                'sentences' => ['___深厚。', '___珍贵。', '___万岁。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 72,
                'word' => '爱情',
                'pinyin' => 'ài qíng',
                'simplified' => '爱情',
                'traditional' => '愛情',
                'part_of_speech' => 'noun',
                'meaning' => 'Love / Romance',
                'meaning_zh' => '爱情',
                'example_sentence' => '真挚的爱情。',
                'example_translation' => 'True love.',
                'definition' => 'Love, romance',
                'sentences' => ['___故事。', '___甜蜜。', '___长久。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 73: In the City (在城市) - 20 words
        $cityVocab = [
            [
                'topic_id' => 73,
                'word' => '城市',
                'pinyin' => 'chéng shì',
                'simplified' => '城市',
                'traditional' => '城市',
                'part_of_speech' => 'noun',
                'meaning' => 'City',
                'meaning_zh' => '城市',
                'example_sentence' => '我住在城市里。',
                'example_translation' => 'I live in the city.',
                'definition' => 'City',
                'sentences' => ['___生活。', '___建设。', '___发展。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '街道',
                'pinyin' => 'jiē dào',
                'simplified' => '街道',
                'traditional' => '街道',
                'part_of_speech' => 'noun',
                'meaning' => 'Street',
                'meaning_zh' => '街道',
                'example_sentence' => '街道很干净。',
                'example_translation' => 'The street is very clean.',
                'definition' => 'Street',
                'sentences' => ['___宽阔。', '___整洁。', '___办事处。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '马路',
                'pinyin' => 'mǎ lù',
                'simplified' => '马路',
                'traditional' => '馬路',
                'part_of_speech' => 'noun',
                'meaning' => 'Road / Street',
                'meaning_zh' => '马路',
                'example_sentence' => '过马路要小心。',
                'example_translation' => 'Be careful when crossing the road.',
                'definition' => 'Road, street',
                'sentences' => ['过___。', '___宽。', '___边。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '人行道',
                'pinyin' => 'rén xíng dào',
                'simplified' => '人行道',
                'traditional' => '人行道',
                'part_of_speech' => 'noun',
                'meaning' => 'Sidewalk / Pavement',
                'meaning_zh' => '人行道',
                'example_sentence' => '走人行道。',
                'example_translation' => 'Walk on the sidewalk.',
                'definition' => 'Sidewalk, pavement',
                'sentences' => ['___上。', '___宽。', '___狭窄。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '红绿灯',
                'pinyin' => 'hóng lǜ dēng',
                'simplified' => '红绿灯',
                'traditional' => '紅綠燈',
                'part_of_speech' => 'noun',
                'meaning' => 'Traffic light',
                'meaning_zh' => '红绿灯',
                'example_sentence' => '等红绿灯。',
                'example_translation' => 'Wait for the traffic light.',
                'definition' => 'Traffic light',
                'sentences' => ['___路口。', '___变绿。', '___坏了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '斑马线',
                'pinyin' => 'bān mǎ xiàn',
                'simplified' => '斑马线',
                'traditional' => '斑馬線',
                'part_of_speech' => 'noun',
                'meaning' => 'Crosswalk / Zebra crossing',
                'meaning_zh' => '斑马线',
                'example_sentence' => '走斑马线。',
                'example_translation' => 'Use the crosswalk.',
                'definition' => 'Crosswalk, zebra crossing',
                'sentences' => ['___上。', '___过马路。', '___处。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '路口',
                'pinyin' => 'lù kǒu',
                'simplified' => '路口',
                'traditional' => '路口',
                'part_of_speech' => 'noun',
                'meaning' => 'Intersection / Crossroads',
                'meaning_zh' => '路口',
                'example_sentence' => '在路口左转。',
                'example_translation' => 'Turn left at the intersection.',
                'definition' => 'Intersection, crossroads',
                'sentences' => ['___处。', '___转弯。', '___等待。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '十字路口',
                'pinyin' => 'shí zì lù kǒu',
                'simplified' => '十字路口',
                'traditional' => '十字路口',
                'part_of_speech' => 'noun',
                'meaning' => 'Crossroads / Intersection',
                'meaning_zh' => '十字路口',
                'example_sentence' => '在十字路口等我。',
                'example_translation' => 'Wait for me at the crossroads.',
                'definition' => 'Crossroads, intersection',
                'sentences' => ['___处。', '___转弯。', '___见面。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '拐角',
                'pinyin' => 'guǎi jiǎo',
                'simplified' => '拐角',
                'traditional' => '拐角',
                'part_of_speech' => 'noun',
                'meaning' => 'Corner / Turning',
                'meaning_zh' => '拐角',
                'example_sentence' => '在拐角处转弯。',
                'example_translation' => 'Turn at the corner.',
                'definition' => 'Corner, turning',
                'sentences' => ['___处。', '___商店。', '___转弯。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '广场',
                'pinyin' => 'guǎng chǎng',
                'simplified' => '广场',
                'traditional' => '廣場',
                'part_of_speech' => 'noun',
                'meaning' => 'Square / Plaza',
                'meaning_zh' => '广场',
                'example_sentence' => '在广场散步。',
                'example_translation' => 'Take a walk in the square.',
                'definition' => 'Square, plaza',
                'sentences' => ['___上。', '___很大。', '___活动。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '公园',
                'pinyin' => 'gōng yuán',
                'simplified' => '公园',
                'traditional' => '公園',
                'part_of_speech' => 'noun',
                'meaning' => 'Park',
                'meaning_zh' => '公园',
                'example_sentence' => '去公园玩。',
                'example_translation' => 'Go to the park to play.',
                'definition' => 'Park',
                'sentences' => ['___里。', '___散步。', '___游玩。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '建筑',
                'pinyin' => 'jiàn zhù',
                'simplified' => '建筑',
                'traditional' => '建築',
                'part_of_speech' => 'noun',
                'meaning' => 'Building / Architecture',
                'meaning_zh' => '建筑',
                'example_sentence' => '这是古老的建筑。',
                'example_translation' => 'This is an ancient building.',
                'definition' => 'Building, architecture',
                'sentences' => ['___物。', '___风格。', '___师。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '大楼',
                'pinyin' => 'dà lóu',
                'simplified' => '大楼',
                'traditional' => '大樓',
                'part_of_speech' => 'noun',
                'meaning' => 'Building / Tower',
                'meaning_zh' => '大楼',
                'example_sentence' => '办公大楼。',
                'example_translation' => 'Office building.',
                'definition' => 'Building, tower, tall building',
                'sentences' => ['___高。', '办公___。', '___里。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '高楼',
                'pinyin' => 'gāo lóu',
                'simplified' => '高楼',
                'traditional' => '高樓',
                'part_of_speech' => 'noun',
                'meaning' => 'Tall building / High-rise',
                'meaning_zh' => '高楼',
                'example_sentence' => '高楼大厦。',
                'example_translation' => 'Tall buildings.',
                'definition' => 'Tall building, high-rise',
                'sentences' => ['___大厦。', '___林立。', '___层。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '桥',
                'pinyin' => 'qiáo',
                'simplified' => '桥',
                'traditional' => '橋',
                'part_of_speech' => 'noun',
                'meaning' => 'Bridge',
                'meaning_zh' => '桥',
                'example_sentence' => '过桥。',
                'example_translation' => 'Cross the bridge.',
                'definition' => 'Bridge',
                'sentences' => ['过___。', '___上。', '___梁。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '河',
                'pinyin' => 'hé',
                'simplified' => '河',
                'traditional' => '河',
                'part_of_speech' => 'noun',
                'meaning' => 'River',
                'meaning_zh' => '河',
                'example_sentence' => '河边散步。',
                'example_translation' => 'Walk by the river.',
                'definition' => 'River',
                'sentences' => ['___边。', '___流。', '___水。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '噪音',
                'pinyin' => 'zào yīn',
                'simplified' => '噪音',
                'traditional' => '噪音',
                'part_of_speech' => 'noun',
                'meaning' => 'Noise',
                'meaning_zh' => '噪音',
                'example_sentence' => '城市里噪音很大。',
                'example_translation' => 'There is a lot of noise in the city.',
                'definition' => 'Noise',
                'sentences' => ['___大。', '___污染。', '___扰民。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '交通',
                'pinyin' => 'jiāo tōng',
                'simplified' => '交通',
                'traditional' => '交通',
                'part_of_speech' => 'noun',
                'meaning' => 'Traffic / Transportation',
                'meaning_zh' => '交通',
                'example_sentence' => '交通很方便。',
                'example_translation' => 'Transportation is very convenient.',
                'definition' => 'Traffic, transportation',
                'sentences' => ['___堵塞。', '___工具。', '___便利。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '拥堵',
                'pinyin' => 'yōng dǔ',
                'simplified' => '拥堵',
                'traditional' => '擁堵',
                'part_of_speech' => 'verb',
                'meaning' => 'To be congested / Traffic jam',
                'meaning_zh' => '拥堵',
                'example_sentence' => '道路拥堵。',
                'example_translation' => 'The road is congested.',
                'definition' => 'To be congested, traffic jam, congestion',
                'sentences' => ['___了。', '___严重。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 73,
                'word' => '热闹',
                'pinyin' => 'rè nao',
                'simplified' => '热闹',
                'traditional' => '熱鬧',
                'part_of_speech' => 'adjective',
                'meaning' => 'Lively / Bustling',
                'meaning_zh' => '热闹',
                'example_sentence' => '街上很热闹。',
                'example_translation' => 'The street is very lively.',
                'definition' => 'Lively, bustling, busy',
                'sentences' => ['很___。', '___的街道。', '___非凡。'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($apologiesVocab, $invitationsVocab, $relationshipsVocab, $cityVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
