<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics12to15Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 74: Transportation (交通工具) - 20 words
        $transportationVocab = [
            [
                'topic_id' => 74,
                'word' => '交通工具',
                'pinyin' => 'jiāo tōng gōng jù',
                'simplified' => '交通工具',
                'traditional' => '交通工具',
                'part_of_speech' => 'noun',
                'meaning' => 'Transportation / Vehicle',
                'meaning_zh' => '交通工具',
                'example_sentence' => '选择交通工具。',
                'example_translation' => 'Choose a means of transportation.',
                'definition' => 'Transportation, vehicle, means of transport',
                'sentences' => ['___方便。', '___多样。', '___选择。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '地铁',
                'pinyin' => 'dì tiě',
                'simplified' => '地铁',
                'traditional' => '地鐵',
                'part_of_speech' => 'noun',
                'meaning' => 'Subway / Metro',
                'meaning_zh' => '地铁',
                'example_sentence' => '坐地铁上班。',
                'example_translation' => 'Take the subway to work.',
                'definition' => 'Subway, metro, underground',
                'sentences' => ['___站。', '___线路。', '___快。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '公交车',
                'pinyin' => 'gōng jiāo chē',
                'simplified' => '公交车',
                'traditional' => '公交車',
                'part_of_speech' => 'noun',
                'meaning' => 'Bus',
                'meaning_zh' => '公交车',
                'example_sentence' => '坐公交车。',
                'example_translation' => 'Take the bus.',
                'definition' => 'Bus, public bus',
                'sentences' => ['___站。', '___路线。', '___方便。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '出租车',
                'pinyin' => 'chū zū chē',
                'simplified' => '出租车',
                'traditional' => '出租車',
                'part_of_speech' => 'noun',
                'meaning' => 'Taxi',
                'meaning_zh' => '出租车',
                'example_sentence' => '打出租车。',
                'example_translation' => 'Take a taxi.',
                'definition' => 'Taxi, cab',
                'sentences' => ['___司机。', '___费用。', '打___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '私家车',
                'pinyin' => 'sī jiā chē',
                'simplified' => '私家车',
                'traditional' => '私家車',
                'part_of_speech' => 'noun',
                'meaning' => 'Private car',
                'meaning_zh' => '私家车',
                'example_sentence' => '开私家车。',
                'example_translation' => 'Drive a private car.',
                'definition' => 'Private car',
                'sentences' => ['___数量。', '___出行。', '___限行。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '自行车',
                'pinyin' => 'zì xíng chē',
                'simplified' => '自行车',
                'traditional' => '自行車',
                'part_of_speech' => 'noun',
                'meaning' => 'Bicycle',
                'meaning_zh' => '自行车',
                'example_sentence' => '骑自行车。',
                'example_translation' => 'Ride a bicycle.',
                'definition' => 'Bicycle, bike',
                'sentences' => ['___道。', '骑___。', '___停放。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '电动车',
                'pinyin' => 'diàn dòng chē',
                'simplified' => '电动车',
                'traditional' => '電動車',
                'part_of_speech' => 'noun',
                'meaning' => 'Electric vehicle / E-bike',
                'meaning_zh' => '电动车',
                'example_sentence' => '骑电动车。',
                'example_translation' => 'Ride an electric bike.',
                'definition' => 'Electric vehicle, e-bike',
                'sentences' => ['___充电。', '___方便。', '___限速。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '摩托车',
                'pinyin' => 'mó tuō chē',
                'simplified' => '摩托车',
                'traditional' => '摩托車',
                'part_of_speech' => 'noun',
                'meaning' => 'Motorcycle',
                'meaning_zh' => '摩托车',
                'example_sentence' => '骑摩托车。',
                'example_translation' => 'Ride a motorcycle.',
                'definition' => 'Motorcycle, motorbike',
                'sentences' => ['___驾照。', '___头盔。', '___快。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '火车',
                'pinyin' => 'huǒ chē',
                'simplified' => '火车',
                'traditional' => '火車',
                'part_of_speech' => 'noun',
                'meaning' => 'Train',
                'meaning_zh' => '火车',
                'example_sentence' => '坐火车去。',
                'example_translation' => 'Go by train.',
                'definition' => 'Train',
                'sentences' => ['___站。', '___票。', '___时刻表。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '高铁',
                'pinyin' => 'gāo tiě',
                'simplified' => '高铁',
                'traditional' => '高鐵',
                'part_of_speech' => 'noun',
                'meaning' => 'High-speed rail',
                'meaning_zh' => '高铁',
                'example_sentence' => '坐高铁很快。',
                'example_translation' => 'Taking the high-speed rail is very fast.',
                'definition' => 'High-speed rail, bullet train',
                'sentences' => ['___站。', '___票。', '___速度。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '飞机',
                'pinyin' => 'fēi jī',
                'simplified' => '飞机',
                'traditional' => '飛機',
                'part_of_speech' => 'noun',
                'meaning' => 'Airplane',
                'meaning_zh' => '飞机',
                'example_sentence' => '坐飞机去。',
                'example_translation' => 'Go by airplane.',
                'definition' => 'Airplane, plane',
                'sentences' => ['___场。', '___票。', '___起飞。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '轮船',
                'pinyin' => 'lún chuán',
                'simplified' => '轮船',
                'traditional' => '輪船',
                'part_of_speech' => 'noun',
                'meaning' => 'Ship / Steamship',
                'meaning_zh' => '轮船',
                'example_sentence' => '坐轮船旅行。',
                'example_translation' => 'Travel by ship.',
                'definition' => 'Ship, steamship, boat',
                'sentences' => ['___码头。', '___票。', '___航行。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '站台',
                'pinyin' => 'zhàn tái',
                'simplified' => '站台',
                'traditional' => '站台',
                'part_of_speech' => 'noun',
                'meaning' => 'Platform',
                'meaning_zh' => '站台',
                'example_sentence' => '在站台等车。',
                'example_translation' => 'Wait for the train on the platform.',
                'definition' => 'Platform',
                'sentences' => ['___上。', '___号。', '___候车。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '车票',
                'pinyin' => 'chē piào',
                'simplified' => '车票',
                'traditional' => '車票',
                'part_of_speech' => 'noun',
                'meaning' => 'Ticket (for bus/train)',
                'meaning_zh' => '车票',
                'example_sentence' => '买车票。',
                'example_translation' => 'Buy a ticket.',
                'definition' => 'Ticket for bus or train',
                'sentences' => ['___价格。', '___售罄。', '___预订。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '机票',
                'pinyin' => 'jī piào',
                'simplified' => '机票',
                'traditional' => '機票',
                'part_of_speech' => 'noun',
                'meaning' => 'Plane ticket',
                'meaning_zh' => '机票',
                'example_sentence' => '订机票。',
                'example_translation' => 'Book a plane ticket.',
                'definition' => 'Plane ticket, air ticket',
                'sentences' => ['___价格。', '___预订。', '___打折。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '司机',
                'pinyin' => 'sī jī',
                'simplified' => '司机',
                'traditional' => '司機',
                'part_of_speech' => 'noun',
                'meaning' => 'Driver',
                'meaning_zh' => '司机',
                'example_sentence' => '出租车司机。',
                'example_translation' => 'Taxi driver.',
                'definition' => 'Driver',
                'sentences' => ['___师傅。', '___驾驶。', '___技术。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '乘客',
                'pinyin' => 'chéng kè',
                'simplified' => '乘客',
                'traditional' => '乘客',
                'part_of_speech' => 'noun',
                'meaning' => 'Passenger',
                'meaning_zh' => '乘客',
                'example_sentence' => '很多乘客。',
                'example_translation' => 'Many passengers.',
                'definition' => 'Passenger',
                'sentences' => ['___上车。', '___下车。', '___数量。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '上车',
                'pinyin' => 'shàng chē',
                'simplified' => '上车',
                'traditional' => '上車',
                'part_of_speech' => 'verb',
                'meaning' => 'To get on (a vehicle)',
                'meaning_zh' => '上车',
                'example_sentence' => '请上车。',
                'example_translation' => 'Please get on.',
                'definition' => 'To get on, to board',
                'sentences' => ['___了。', '___地点。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '下车',
                'pinyin' => 'xià chē',
                'simplified' => '下车',
                'traditional' => '下車',
                'part_of_speech' => 'verb',
                'meaning' => 'To get off (a vehicle)',
                'meaning_zh' => '下车',
                'example_sentence' => '到站下车。',
                'example_translation' => 'Get off at the stop.',
                'definition' => 'To get off, to alight',
                'sentences' => ['___了。', '___地点。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 74,
                'word' => '换乘',
                'pinyin' => 'huàn chéng',
                'simplified' => '换乘',
                'traditional' => '換乘',
                'part_of_speech' => 'verb',
                'meaning' => 'To transfer / To change (vehicles)',
                'meaning_zh' => '换乘',
                'example_sentence' => '需要换乘。',
                'example_translation' => 'Need to transfer.',
                'definition' => 'To transfer, to change vehicles',
                'sentences' => ['___地铁。', '___站。', '___方便。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 75: Travel and Tourism (旅行和旅游) - 20 words
        $travelVocab = [
            [
                'topic_id' => 75,
                'word' => '旅行',
                'pinyin' => 'lǚ xíng',
                'simplified' => '旅行',
                'traditional' => '旅行',
                'part_of_speech' => 'verb',
                'meaning' => 'To travel / Travel',
                'meaning_zh' => '旅行',
                'example_sentence' => '去旅行。',
                'example_translation' => 'Go traveling.',
                'definition' => 'To travel, travel, trip',
                'sentences' => ['___计划。', '___社。', '___经历。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '旅游',
                'pinyin' => 'lǚ yóu',
                'simplified' => '旅游',
                'traditional' => '旅遊',
                'part_of_speech' => 'verb',
                'meaning' => 'To tour / Tourism',
                'meaning_zh' => '旅游',
                'example_sentence' => '去旅游。',
                'example_translation' => 'Go sightseeing.',
                'definition' => 'To tour, tourism, sightseeing',
                'sentences' => ['___景点。', '___城市。', '___业。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '旅客',
                'pinyin' => 'lǚ kè',
                'simplified' => '旅客',
                'traditional' => '旅客',
                'part_of_speech' => 'noun',
                'meaning' => 'Traveler / Tourist',
                'meaning_zh' => '旅客',
                'example_sentence' => '很多旅客。',
                'example_translation' => 'Many travelers.',
                'definition' => 'Traveler, tourist, passenger',
                'sentences' => ['___众多。', '___服务。', '___需求。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '游客',
                'pinyin' => 'yóu kè',
                'simplified' => '游客',
                'traditional' => '遊客',
                'part_of_speech' => 'noun',
                'meaning' => 'Tourist / Visitor',
                'meaning_zh' => '游客',
                'example_sentence' => '游客很多。',
                'example_translation' => 'There are many tourists.',
                'definition' => 'Tourist, visitor',
                'sentences' => ['___中心。', '___数量。', '___服务。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '景点',
                'pinyin' => 'jǐng diǎn',
                'simplified' => '景点',
                'traditional' => '景點',
                'part_of_speech' => 'noun',
                'meaning' => 'Scenic spot / Tourist attraction',
                'meaning_zh' => '景点',
                'example_sentence' => '著名景点。',
                'example_translation' => 'Famous scenic spot.',
                'definition' => 'Scenic spot, tourist attraction',
                'sentences' => ['___门票。', '___介绍。', '___参观。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '风景',
                'pinyin' => 'fēng jǐng',
                'simplified' => '风景',
                'traditional' => '風景',
                'part_of_speech' => 'noun',
                'meaning' => 'Scenery / Landscape',
                'meaning_zh' => '风景',
                'example_sentence' => '风景很美。',
                'example_translation' => 'The scenery is very beautiful.',
                'definition' => 'Scenery, landscape, view',
                'sentences' => ['___优美。', '___区。', '___如画。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '名胜',
                'pinyin' => 'míng shèng',
                'simplified' => '名胜',
                'traditional' => '名勝',
                'part_of_speech' => 'noun',
                'meaning' => 'Famous scenic spot',
                'meaning_zh' => '名胜',
                'example_sentence' => '名胜古迹。',
                'example_translation' => 'Famous historical sites.',
                'definition' => 'Famous scenic spot, place of interest',
                'sentences' => ['___古迹。', '___区。', '___保护。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '古迹',
                'pinyin' => 'gǔ jì',
                'simplified' => '古迹',
                'traditional' => '古蹟',
                'part_of_speech' => 'noun',
                'meaning' => 'Historic site / Ruins',
                'meaning_zh' => '古迹',
                'example_sentence' => '参观古迹。',
                'example_translation' => 'Visit historic sites.',
                'definition' => 'Historic site, ruins, relic',
                'sentences' => ['___保护。', '___价值。', '___修复。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '博物馆',
                'pinyin' => 'bó wù guǎn',
                'simplified' => '博物馆',
                'traditional' => '博物館',
                'part_of_speech' => 'noun',
                'meaning' => 'Museum',
                'meaning_zh' => '博物馆',
                'example_sentence' => '参观博物馆。',
                'example_translation' => 'Visit the museum.',
                'definition' => 'Museum',
                'sentences' => ['___展览。', '___门票。', '___参观。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '展览',
                'pinyin' => 'zhǎn lǎn',
                'simplified' => '展览',
                'traditional' => '展覽',
                'part_of_speech' => 'noun',
                'meaning' => 'Exhibition',
                'meaning_zh' => '展览',
                'example_sentence' => '参观展览。',
                'example_translation' => 'Visit the exhibition.',
                'definition' => 'Exhibition, to exhibit',
                'sentences' => ['___会。', '___馆。', '___内容。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '导游',
                'pinyin' => 'dǎo yóu',
                'simplified' => '导游',
                'traditional' => '導遊',
                'part_of_speech' => 'noun',
                'meaning' => 'Tour guide',
                'meaning_zh' => '导游',
                'example_sentence' => '导游介绍。',
                'example_translation' => 'The tour guide introduces.',
                'definition' => 'Tour guide',
                'sentences' => ['___讲解。', '___服务。', '___费用。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '酒店',
                'pinyin' => 'jiǔ diàn',
                'simplified' => '酒店',
                'traditional' => '酒店',
                'part_of_speech' => 'noun',
                'meaning' => 'Hotel',
                'meaning_zh' => '酒店',
                'example_sentence' => '住酒店。',
                'example_translation' => 'Stay at a hotel.',
                'definition' => 'Hotel',
                'sentences' => ['___预订。', '___房间。', '___服务。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '宾馆',
                'pinyin' => 'bīn guǎn',
                'simplified' => '宾馆',
                'traditional' => '賓館',
                'part_of_speech' => 'noun',
                'meaning' => 'Hotel / Guesthouse',
                'meaning_zh' => '宾馆',
                'example_sentence' => '住宾馆。',
                'example_translation' => 'Stay at a hotel.',
                'definition' => 'Hotel, guesthouse',
                'sentences' => ['___房间。', '___价格。', '___设施。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '房间',
                'pinyin' => 'fáng jiān',
                'simplified' => '房间',
                'traditional' => '房間',
                'part_of_speech' => 'noun',
                'meaning' => 'Room',
                'meaning_zh' => '房间',
                'example_sentence' => '预订房间。',
                'example_translation' => 'Book a room.',
                'definition' => 'Room',
                'sentences' => ['___号。', '___干净。', '___价格。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '护照',
                'pinyin' => 'hù zhào',
                'simplified' => '护照',
                'traditional' => '護照',
                'part_of_speech' => 'noun',
                'meaning' => 'Passport',
                'meaning_zh' => '护照',
                'example_sentence' => '带护照。',
                'example_translation' => 'Bring passport.',
                'definition' => 'Passport',
                'sentences' => ['___号码。', '___有效期。', '___办理。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '签证',
                'pinyin' => 'qiān zhèng',
                'simplified' => '签证',
                'traditional' => '簽證',
                'part_of_speech' => 'noun',
                'meaning' => 'Visa',
                'meaning_zh' => '签证',
                'example_sentence' => '办签证。',
                'example_translation' => 'Apply for a visa.',
                'definition' => 'Visa',
                'sentences' => ['___申请。', '___材料。', '___有效期。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '行李',
                'pinyin' => 'xíng li',
                'simplified' => '行李',
                'traditional' => '行李',
                'part_of_speech' => 'noun',
                'meaning' => 'Luggage / Baggage',
                'meaning_zh' => '行李',
                'example_sentence' => '收拾行李。',
                'example_translation' => 'Pack luggage.',
                'definition' => 'Luggage, baggage',
                'sentences' => ['___箱。', '___托运。', '___重量。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '纪念品',
                'pinyin' => 'jì niàn pǐn',
                'simplified' => '纪念品',
                'traditional' => '紀念品',
                'part_of_speech' => 'noun',
                'meaning' => 'Souvenir',
                'meaning_zh' => '纪念品',
                'example_sentence' => '买纪念品。',
                'example_translation' => 'Buy souvenirs.',
                'definition' => 'Souvenir, memento',
                'sentences' => ['___商店。', '___价格。', '___选择。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '拍照',
                'pinyin' => 'pāi zhào',
                'simplified' => '拍照',
                'traditional' => '拍照',
                'part_of_speech' => 'verb',
                'meaning' => 'To take a photo',
                'meaning_zh' => '拍照',
                'example_sentence' => '可以拍照吗？',
                'example_translation' => 'Can I take a photo?',
                'definition' => 'To take a photo, to photograph',
                'sentences' => ['___留念。', '___禁止。', '___地点。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 75,
                'word' => '地图',
                'pinyin' => 'dì tú',
                'simplified' => '地图',
                'traditional' => '地圖',
                'part_of_speech' => 'noun',
                'meaning' => 'Map',
                'meaning_zh' => '地图',
                'example_sentence' => '看地图。',
                'example_translation' => 'Look at the map.',
                'definition' => 'Map',
                'sentences' => ['___显示。', '___导航。', '___位置。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 76: At School (在学校) - 20 words
        $schoolVocab = [
            [
                'topic_id' => 76,
                'word' => '学校',
                'pinyin' => 'xué xiào',
                'simplified' => '学校',
                'traditional' => '學校',
                'part_of_speech' => 'noun',
                'meaning' => 'School',
                'meaning_zh' => '学校',
                'example_sentence' => '去学校。',
                'example_translation' => 'Go to school.',
                'definition' => 'School',
                'sentences' => ['___生活。', '___教育。', '___规定。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '教室',
                'pinyin' => 'jiào shì',
                'simplified' => '教室',
                'traditional' => '教室',
                'part_of_speech' => 'noun',
                'meaning' => 'Classroom',
                'meaning_zh' => '教室',
                'example_sentence' => '在教室学习。',
                'example_translation' => 'Study in the classroom.',
                'definition' => 'Classroom',
                'sentences' => ['___里。', '___干净。', '___设备。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '课堂',
                'pinyin' => 'kè táng',
                'simplified' => '课堂',
                'traditional' => '課堂',
                'part_of_speech' => 'noun',
                'meaning' => 'Class / Classroom',
                'meaning_zh' => '课堂',
                'example_sentence' => '在课堂上。',
                'example_translation' => 'In class.',
                'definition' => 'Class, classroom',
                'sentences' => ['___上。', '___纪律。', '___讨论。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '课程',
                'pinyin' => 'kè chéng',
                'simplified' => '课程',
                'traditional' => '課程',
                'part_of_speech' => 'noun',
                'meaning' => 'Course / Curriculum',
                'meaning_zh' => '课程',
                'example_sentence' => '选择课程。',
                'example_translation' => 'Choose courses.',
                'definition' => 'Course, curriculum',
                'sentences' => ['___表。', '___内容。', '___安排。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '科目',
                'pinyin' => 'kē mù',
                'simplified' => '科目',
                'traditional' => '科目',
                'part_of_speech' => 'noun',
                'meaning' => 'Subject / Course',
                'meaning_zh' => '科目',
                'example_sentence' => '学习科目。',
                'example_translation' => 'Study subjects.',
                'definition' => 'Subject, course',
                'sentences' => ['___考试。', '___成绩。', '___选择。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '教材',
                'pinyin' => 'jiào cái',
                'simplified' => '教材',
                'traditional' => '教材',
                'part_of_speech' => 'noun',
                'meaning' => 'Teaching material / Textbook',
                'meaning_zh' => '教材',
                'example_sentence' => '准备教材。',
                'example_translation' => 'Prepare teaching materials.',
                'definition' => 'Teaching material, textbook',
                'sentences' => ['___内容。', '___版本。', '___选择。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '作业',
                'pinyin' => 'zuò yè',
                'simplified' => '作业',
                'traditional' => '作業',
                'part_of_speech' => 'noun',
                'meaning' => 'Homework / Assignment',
                'meaning_zh' => '作业',
                'example_sentence' => '做作业。',
                'example_translation' => 'Do homework.',
                'definition' => 'Homework, assignment',
                'sentences' => ['___完成。', '___多。', '___检查。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '练习',
                'pinyin' => 'liàn xí',
                'simplified' => '练习',
                'traditional' => '練習',
                'part_of_speech' => 'verb',
                'meaning' => 'To practice / Exercise',
                'meaning_zh' => '练习',
                'example_sentence' => '多练习。',
                'example_translation' => 'Practice more.',
                'definition' => 'To practice, exercise',
                'sentences' => ['___题。', '___册。', '___方法。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '考试',
                'pinyin' => 'kǎo shì',
                'simplified' => '考试',
                'traditional' => '考試',
                'part_of_speech' => 'noun',
                'meaning' => 'Exam / Test',
                'meaning_zh' => '考试',
                'example_sentence' => '准备考试。',
                'example_translation' => 'Prepare for the exam.',
                'definition' => 'Exam, test',
                'sentences' => ['___时间。', '___成绩。', '___内容。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '成绩',
                'pinyin' => 'chéng jì',
                'simplified' => '成绩',
                'traditional' => '成績',
                'part_of_speech' => 'noun',
                'meaning' => 'Grade / Score / Achievement',
                'meaning_zh' => '成绩',
                'example_sentence' => '成绩很好。',
                'example_translation' => 'The grades are very good.',
                'definition' => 'Grade, score, achievement',
                'sentences' => ['___单。', '___优秀。', '___提高。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '分数',
                'pinyin' => 'fēn shù',
                'simplified' => '分数',
                'traditional' => '分數',
                'part_of_speech' => 'noun',
                'meaning' => 'Score / Mark',
                'meaning_zh' => '分数',
                'example_sentence' => '分数高。',
                'example_translation' => 'High score.',
                'definition' => 'Score, mark',
                'sentences' => ['___线。', '___统计。', '___排名。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '及格',
                'pinyin' => 'jí gé',
                'simplified' => '及格',
                'traditional' => '及格',
                'part_of_speech' => 'verb',
                'meaning' => 'To pass (an exam)',
                'meaning_zh' => '及格',
                'example_sentence' => '考试及格。',
                'example_translation' => 'Pass the exam.',
                'definition' => 'To pass, passing grade',
                'sentences' => ['___了。', '___线。', '___标准。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '不及格',
                'pinyin' => 'bù jí gé',
                'simplified' => '不及格',
                'traditional' => '不及格',
                'part_of_speech' => 'verb',
                'meaning' => 'To fail (an exam)',
                'meaning_zh' => '不及格',
                'example_sentence' => '考试不及格。',
                'example_translation' => 'Fail the exam.',
                'definition' => 'To fail, failing grade',
                'sentences' => ['___了。', '___补考。', '___原因。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '毕业',
                'pinyin' => 'bì yè',
                'simplified' => '毕业',
                'traditional' => '畢業',
                'part_of_speech' => 'verb',
                'meaning' => 'To graduate',
                'meaning_zh' => '毕业',
                'example_sentence' => '明年毕业。',
                'example_translation' => 'Graduate next year.',
                'definition' => 'To graduate, graduation',
                'sentences' => ['___了。', '___证书。', '___典礼。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '图书馆',
                'pinyin' => 'tú shū guǎn',
                'simplified' => '图书馆',
                'traditional' => '圖書館',
                'part_of_speech' => 'noun',
                'meaning' => 'Library',
                'meaning_zh' => '图书馆',
                'example_sentence' => '去图书馆。',
                'example_translation' => 'Go to the library.',
                'definition' => 'Library',
                'sentences' => ['___里。', '___借书。', '___学习。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '实验室',
                'pinyin' => 'shí yàn shì',
                'simplified' => '实验室',
                'traditional' => '實驗室',
                'part_of_speech' => 'noun',
                'meaning' => 'Laboratory',
                'meaning_zh' => '实验室',
                'example_sentence' => '在实验室做实验。',
                'example_translation' => 'Do experiments in the laboratory.',
                'definition' => 'Laboratory, lab',
                'sentences' => ['___设备。', '___实验。', '___安全。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '食堂',
                'pinyin' => 'shí táng',
                'simplified' => '食堂',
                'traditional' => '食堂',
                'part_of_speech' => 'noun',
                'meaning' => 'Cafeteria / Dining hall',
                'meaning_zh' => '食堂',
                'example_sentence' => '在食堂吃饭。',
                'example_translation' => 'Eat in the cafeteria.',
                'definition' => 'Cafeteria, dining hall, canteen',
                'sentences' => ['___里。', '___饭菜。', '___卡。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '操场',
                'pinyin' => 'cāo chǎng',
                'simplified' => '操场',
                'traditional' => '操場',
                'part_of_speech' => 'noun',
                'meaning' => 'Playground / Sports field',
                'meaning_zh' => '操场',
                'example_sentence' => '在操场运动。',
                'example_translation' => 'Exercise on the playground.',
                'definition' => 'Playground, sports field',
                'sentences' => ['___上。', '___跑步。', '___活动。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '宿舍',
                'pinyin' => 'sù shè',
                'simplified' => '宿舍',
                'traditional' => '宿舍',
                'part_of_speech' => 'noun',
                'meaning' => 'Dormitory',
                'meaning_zh' => '宿舍',
                'example_sentence' => '住宿舍。',
                'example_translation' => 'Live in the dormitory.',
                'definition' => 'Dormitory, dorm',
                'sentences' => ['___里。', '___楼。', '___管理。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 76,
                'word' => '奖学金',
                'pinyin' => 'jiǎng xué jīn',
                'simplified' => '奖学金',
                'traditional' => '獎學金',
                'part_of_speech' => 'noun',
                'meaning' => 'Scholarship',
                'meaning_zh' => '奖学金',
                'example_sentence' => '获得奖学金。',
                'example_translation' => 'Receive a scholarship.',
                'definition' => 'Scholarship',
                'sentences' => ['___申请。', '___金额。', '___条件。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 77: In the Office (在办公室) - 20 words
        $officeVocab = [
            [
                'topic_id' => 77,
                'word' => '办公室',
                'pinyin' => 'bàn gōng shì',
                'simplified' => '办公室',
                'traditional' => '辦公室',
                'part_of_speech' => 'noun',
                'meaning' => 'Office',
                'meaning_zh' => '办公室',
                'example_sentence' => '在办公室工作。',
                'example_translation' => 'Work in the office.',
                'definition' => 'Office',
                'sentences' => ['___里。', '___环境。', '___设备。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '公司',
                'pinyin' => 'gōng sī',
                'simplified' => '公司',
                'traditional' => '公司',
                'part_of_speech' => 'noun',
                'meaning' => 'Company',
                'meaning_zh' => '公司',
                'example_sentence' => '在公司上班。',
                'example_translation' => 'Work at the company.',
                'definition' => 'Company, corporation',
                'sentences' => ['___规模。', '___文化。', '___发展。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '工作',
                'pinyin' => 'gōng zuò',
                'simplified' => '工作',
                'traditional' => '工作',
                'part_of_speech' => 'verb',
                'meaning' => 'To work / Work / Job',
                'meaning_zh' => '工作',
                'example_sentence' => '努力工作。',
                'example_translation' => 'Work hard.',
                'definition' => 'To work, work, job',
                'sentences' => ['___时间。', '___内容。', '___环境。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '职位',
                'pinyin' => 'zhí wèi',
                'simplified' => '职位',
                'traditional' => '職位',
                'part_of_speech' => 'noun',
                'meaning' => 'Position / Post',
                'meaning_zh' => '职位',
                'example_sentence' => '申请职位。',
                'example_translation' => 'Apply for a position.',
                'definition' => 'Position, post, job',
                'sentences' => ['___空缺。', '___要求。', '___晋升。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '员工',
                'pinyin' => 'yuán gōng',
                'simplified' => '员工',
                'traditional' => '員工',
                'part_of_speech' => 'noun',
                'meaning' => 'Employee / Staff',
                'meaning_zh' => '员工',
                'example_sentence' => '公司员工。',
                'example_translation' => 'Company employees.',
                'definition' => 'Employee, staff, worker',
                'sentences' => ['___数量。', '___福利。', '___培训。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '老板',
                'pinyin' => 'lǎo bǎn',
                'simplified' => '老板',
                'traditional' => '老闆',
                'part_of_speech' => 'noun',
                'meaning' => 'Boss / Owner',
                'meaning_zh' => '老板',
                'example_sentence' => '见老板。',
                'example_translation' => 'Meet the boss.',
                'definition' => 'Boss, owner, proprietor',
                'sentences' => ['___要求。', '___决定。', '___批准。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '经理',
                'pinyin' => 'jīng lǐ',
                'simplified' => '经理',
                'traditional' => '經理',
                'part_of_speech' => 'noun',
                'meaning' => 'Manager',
                'meaning_zh' => '经理',
                'example_sentence' => '部门经理。',
                'example_translation' => 'Department manager.',
                'definition' => 'Manager',
                'sentences' => ['___职责。', '___会议。', '___决策。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '同事',
                'pinyin' => 'tóng shì',
                'simplified' => '同事',
                'traditional' => '同事',
                'part_of_speech' => 'noun',
                'meaning' => 'Colleague / Coworker',
                'meaning_zh' => '同事',
                'example_sentence' => '和同事合作。',
                'example_translation' => 'Cooperate with colleagues.',
                'definition' => 'Colleague, coworker',
                'sentences' => ['___关系。', '___帮助。', '___交流。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '会议',
                'pinyin' => 'huì yì',
                'simplified' => '会议',
                'traditional' => '會議',
                'part_of_speech' => 'noun',
                'meaning' => 'Meeting / Conference',
                'meaning_zh' => '会议',
                'example_sentence' => '参加会议。',
                'example_translation' => 'Attend a meeting.',
                'definition' => 'Meeting, conference',
                'sentences' => ['___室。', '___内容。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '报告',
                'pinyin' => 'bào gào',
                'simplified' => '报告',
                'traditional' => '報告',
                'part_of_speech' => 'noun',
                'meaning' => 'Report',
                'meaning_zh' => '报告',
                'example_sentence' => '写报告。',
                'example_translation' => 'Write a report.',
                'definition' => 'Report, to report',
                'sentences' => ['___内容。', '___提交。', '___分析。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '文件',
                'pinyin' => 'wén jiàn',
                'simplified' => '文件',
                'traditional' => '文件',
                'part_of_speech' => 'noun',
                'meaning' => 'Document / File',
                'meaning_zh' => '文件',
                'example_sentence' => '处理文件。',
                'example_translation' => 'Process documents.',
                'definition' => 'Document, file',
                'sentences' => ['___夹。', '___管理。', '___保存。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '资料',
                'pinyin' => 'zī liào',
                'simplified' => '资料',
                'traditional' => '資料',
                'part_of_speech' => 'noun',
                'meaning' => 'Material / Data / Information',
                'meaning_zh' => '资料',
                'example_sentence' => '收集资料。',
                'example_translation' => 'Collect information.',
                'definition' => 'Material, data, information',
                'sentences' => ['___齐全。', '___查询。', '___整理。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '电脑',
                'pinyin' => 'diàn nǎo',
                'simplified' => '电脑',
                'traditional' => '電腦',
                'part_of_speech' => 'noun',
                'meaning' => 'Computer',
                'meaning_zh' => '电脑',
                'example_sentence' => '用电脑工作。',
                'example_translation' => 'Work with a computer.',
                'definition' => 'Computer',
                'sentences' => ['___技术。', '___系统。', '___维修。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '打印',
                'pinyin' => 'dǎ yìn',
                'simplified' => '打印',
                'traditional' => '打印',
                'part_of_speech' => 'verb',
                'meaning' => 'To print',
                'meaning_zh' => '打印',
                'example_sentence' => '打印文件。',
                'example_translation' => 'Print documents.',
                'definition' => 'To print',
                'sentences' => ['___机。', '___纸张。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '复印',
                'pinyin' => 'fù yìn',
                'simplified' => '复印',
                'traditional' => '複印',
                'part_of_speech' => 'verb',
                'meaning' => 'To photocopy',
                'meaning_zh' => '复印',
                'example_sentence' => '复印资料。',
                'example_translation' => 'Photocopy materials.',
                'definition' => 'To photocopy, to duplicate',
                'sentences' => ['___机。', '___件。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '发邮件',
                'pinyin' => 'fā yóu jiàn',
                'simplified' => '发邮件',
                'traditional' => '發郵件',
                'part_of_speech' => 'verb',
                'meaning' => 'To send an email',
                'meaning_zh' => '发邮件',
                'example_sentence' => '发邮件给他。',
                'example_translation' => 'Send him an email.',
                'definition' => 'To send an email',
                'sentences' => ['___了。', '___内容。', '___地址。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '加班',
                'pinyin' => 'jiā bān',
                'simplified' => '加班',
                'traditional' => '加班',
                'part_of_speech' => 'verb',
                'meaning' => 'To work overtime',
                'meaning_zh' => '加班',
                'example_sentence' => '今天加班。',
                'example_translation' => 'Work overtime today.',
                'definition' => 'To work overtime',
                'sentences' => ['___了。', '___费。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '请假',
                'pinyin' => 'qǐng jià',
                'simplified' => '请假',
                'traditional' => '請假',
                'part_of_speech' => 'verb',
                'meaning' => 'To ask for leave',
                'meaning_zh' => '请假',
                'example_sentence' => '我要请假。',
                'example_translation' => 'I need to ask for leave.',
                'definition' => 'To ask for leave',
                'sentences' => ['___了。', '___条。', '___理由。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '工资',
                'pinyin' => 'gōng zī',
                'simplified' => '工资',
                'traditional' => '工資',
                'part_of_speech' => 'noun',
                'meaning' => 'Salary / Wages',
                'meaning_zh' => '工资',
                'example_sentence' => '领工资。',
                'example_translation' => 'Receive salary.',
                'definition' => 'Salary, wages, pay',
                'sentences' => ['___水平。', '___发放。', '___待遇。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 77,
                'word' => '效率',
                'pinyin' => 'xiào lǜ',
                'simplified' => '效率',
                'traditional' => '效率',
                'part_of_speech' => 'noun',
                'meaning' => 'Efficiency',
                'meaning_zh' => '效率',
                'example_sentence' => '提高效率。',
                'example_translation' => 'Improve efficiency.',
                'definition' => 'Efficiency',
                'sentences' => ['___高。', '___低。', '工作___。'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($transportationVocab, $travelVocab, $schoolVocab, $officeVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
