<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics16to20Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 78: Technology and Internet (科技和互联网) - 20 words
        $technologyVocab = [
            [
                'topic_id' => 78,
                'word' => '科技',
                'pinyin' => 'kē jì',
                'simplified' => '科技',
                'traditional' => '科技',
                'part_of_speech' => 'noun',
                'meaning' => 'Technology / Science and technology',
                'meaning_zh' => '科技',
                'example_sentence' => '科技发展很快。',
                'example_translation' => 'Technology develops very fast.',
                'definition' => 'Technology, science and technology',
                'sentences' => ['___发展。', '___产品。', '___创新。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '技术',
                'pinyin' => 'jì shù',
                'simplified' => '技术',
                'traditional' => '技術',
                'part_of_speech' => 'noun',
                'meaning' => 'Technology / Skill / Technique',
                'meaning_zh' => '技术',
                'example_sentence' => '学习新技术。',
                'example_translation' => 'Learn new technology.',
                'definition' => 'Technology, skill, technique',
                'sentences' => ['___先进。', '___水平。', '___培训。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '互联网',
                'pinyin' => 'hù lián wǎng',
                'simplified' => '互联网',
                'traditional' => '互聯網',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet',
                'meaning_zh' => '互联网',
                'example_sentence' => '使用互联网。',
                'example_translation' => 'Use the internet.',
                'definition' => 'Internet',
                'sentences' => ['___时代。', '___服务。', '___连接。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '网络',
                'pinyin' => 'wǎng luò',
                'simplified' => '网络',
                'traditional' => '網絡',
                'part_of_speech' => 'noun',
                'meaning' => 'Network / Internet',
                'meaning_zh' => '网络',
                'example_sentence' => '网络很快。',
                'example_translation' => 'The network is very fast.',
                'definition' => 'Network, internet',
                'sentences' => ['___速度。', '___安全。', '___连接。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '上网',
                'pinyin' => 'shàng wǎng',
                'simplified' => '上网',
                'traditional' => '上網',
                'part_of_speech' => 'verb',
                'meaning' => 'To go online / To surf the internet',
                'meaning_zh' => '上网',
                'example_sentence' => '每天上网。',
                'example_translation' => 'Go online every day.',
                'definition' => 'To go online, to surf the internet',
                'sentences' => ['___了。', '___时间。', '___查资料。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '网站',
                'pinyin' => 'wǎng zhàn',
                'simplified' => '网站',
                'traditional' => '網站',
                'part_of_speech' => 'noun',
                'meaning' => 'Website',
                'meaning_zh' => '网站',
                'example_sentence' => '浏览网站。',
                'example_translation' => 'Browse the website.',
                'definition' => 'Website',
                'sentences' => ['___链接。', '___内容。', '___访问。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '网页',
                'pinyin' => 'wǎng yè',
                'simplified' => '网页',
                'traditional' => '網頁',
                'part_of_speech' => 'noun',
                'meaning' => 'Web page',
                'meaning_zh' => '网页',
                'example_sentence' => '打开网页。',
                'example_translation' => 'Open the web page.',
                'definition' => 'Web page',
                'sentences' => ['___显示。', '___加载。', '___设计。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '软件',
                'pinyin' => 'ruǎn jiàn',
                'simplified' => '软件',
                'traditional' => '軟件',
                'part_of_speech' => 'noun',
                'meaning' => 'Software',
                'meaning_zh' => '软件',
                'example_sentence' => '下载软件。',
                'example_translation' => 'Download software.',
                'definition' => 'Software',
                'sentences' => ['___安装。', '___更新。', '___功能。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '应用',
                'pinyin' => 'yìng yòng',
                'simplified' => '应用',
                'traditional' => '應用',
                'part_of_speech' => 'noun',
                'meaning' => 'Application / App',
                'meaning_zh' => '应用',
                'example_sentence' => '下载应用。',
                'example_translation' => 'Download the app.',
                'definition' => 'Application, app, to apply',
                'sentences' => ['___程序。', '___商店。', '___广泛。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '下载',
                'pinyin' => 'xià zài',
                'simplified' => '下载',
                'traditional' => '下載',
                'part_of_speech' => 'verb',
                'meaning' => 'To download',
                'meaning_zh' => '下载',
                'example_sentence' => '下载文件。',
                'example_translation' => 'Download the file.',
                'definition' => 'To download',
                'sentences' => ['___了。', '___速度。', '___完成。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '上传',
                'pinyin' => 'shàng chuán',
                'simplified' => '上传',
                'traditional' => '上傳',
                'part_of_speech' => 'verb',
                'meaning' => 'To upload',
                'meaning_zh' => '上传',
                'example_sentence' => '上传照片。',
                'example_translation' => 'Upload photos.',
                'definition' => 'To upload',
                'sentences' => ['___了。', '___文件。', '___速度。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '搜索',
                'pinyin' => 'sōu suō',
                'simplified' => '搜索',
                'traditional' => '搜索',
                'part_of_speech' => 'verb',
                'meaning' => 'To search',
                'meaning_zh' => '搜索',
                'example_sentence' => '搜索信息。',
                'example_translation' => 'Search for information.',
                'definition' => 'To search',
                'sentences' => ['___引擎。', '___结果。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '浏览',
                'pinyin' => 'liú lǎn',
                'simplified' => '浏览',
                'traditional' => '瀏覽',
                'part_of_speech' => 'verb',
                'meaning' => 'To browse',
                'meaning_zh' => '浏览',
                'example_sentence' => '浏览网页。',
                'example_translation' => 'Browse web pages.',
                'definition' => 'To browse',
                'sentences' => ['___器。', '___了。', '___内容。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '聊天',
                'pinyin' => 'liáo tiān',
                'simplified' => '聊天',
                'traditional' => '聊天',
                'part_of_speech' => 'verb',
                'meaning' => 'To chat',
                'meaning_zh' => '聊天',
                'example_sentence' => '网上聊天。',
                'example_translation' => 'Chat online.',
                'definition' => 'To chat',
                'sentences' => ['___了。', '___软件。', '___记录。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '视频',
                'pinyin' => 'shì pín',
                'simplified' => '视频',
                'traditional' => '視頻',
                'part_of_speech' => 'noun',
                'meaning' => 'Video',
                'meaning_zh' => '视频',
                'example_sentence' => '看视频。',
                'example_translation' => 'Watch videos.',
                'definition' => 'Video',
                'sentences' => ['___会议。', '___播放。', '___内容。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '音频',
                'pinyin' => 'yīn pín',
                'simplified' => '音频',
                'traditional' => '音頻',
                'part_of_speech' => 'noun',
                'meaning' => 'Audio',
                'meaning_zh' => '音频',
                'example_sentence' => '播放音频。',
                'example_translation' => 'Play audio.',
                'definition' => 'Audio',
                'sentences' => ['___文件。', '___质量。', '___播放。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '密码',
                'pinyin' => 'mì mǎ',
                'simplified' => '密码',
                'traditional' => '密碼',
                'part_of_speech' => 'noun',
                'meaning' => 'Password',
                'meaning_zh' => '密码',
                'example_sentence' => '输入密码。',
                'example_translation' => 'Enter the password.',
                'definition' => 'Password',
                'sentences' => ['___错误。', '___设置。', '___保护。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '账号',
                'pinyin' => 'zhàng hào',
                'simplified' => '账号',
                'traditional' => '賬號',
                'part_of_speech' => 'noun',
                'meaning' => 'Account',
                'meaning_zh' => '账号',
                'example_sentence' => '注册账号。',
                'example_translation' => 'Register an account.',
                'definition' => 'Account',
                'sentences' => ['___密码。', '___登录。', '___注册。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '登录',
                'pinyin' => 'dēng lù',
                'simplified' => '登录',
                'traditional' => '登錄',
                'part_of_speech' => 'verb',
                'meaning' => 'To log in',
                'meaning_zh' => '登录',
                'example_sentence' => '登录账号。',
                'example_translation' => 'Log in to the account.',
                'definition' => 'To log in',
                'sentences' => ['___了。', '___失败。', '___成功。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 78,
                'word' => '退出',
                'pinyin' => 'tuì chū',
                'simplified' => '退出',
                'traditional' => '退出',
                'part_of_speech' => 'verb',
                'meaning' => 'To log out / To exit',
                'meaning_zh' => '退出',
                'example_sentence' => '退出账号。',
                'example_translation' => 'Log out of the account.',
                'definition' => 'To log out, to exit',
                'sentences' => ['___了。', '___系统。', '___登录。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 79: Verbs (动词) - 20 words
        $verbsVocab = [
            [
                'topic_id' => 79,
                'word' => '发生',
                'pinyin' => 'fā shēng',
                'simplified' => '发生',
                'traditional' => '發生',
                'part_of_speech' => 'verb',
                'meaning' => 'To happen / To occur',
                'meaning_zh' => '发生',
                'example_sentence' => '发生了什么？',
                'example_translation' => 'What happened?',
                'definition' => 'To happen, to occur',
                'sentences' => ['___了。', '___事故。', '___变化。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '发现',
                'pinyin' => 'fā xiàn',
                'simplified' => '发现',
                'traditional' => '發現',
                'part_of_speech' => 'verb',
                'meaning' => 'To discover / To find',
                'meaning_zh' => '发现',
                'example_sentence' => '发现问题。',
                'example_translation' => 'Discover a problem.',
                'definition' => 'To discover, to find',
                'sentences' => ['___了。', '___秘密。', '___新大陆。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '发展',
                'pinyin' => 'fā zhǎn',
                'simplified' => '发展',
                'traditional' => '發展',
                'part_of_speech' => 'verb',
                'meaning' => 'To develop',
                'meaning_zh' => '发展',
                'example_sentence' => '经济发展。',
                'example_translation' => 'Economic development.',
                'definition' => 'To develop, development',
                'sentences' => ['___快。', '___机会。', '___空间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '进行',
                'pinyin' => 'jìn xíng',
                'simplified' => '进行',
                'traditional' => '進行',
                'part_of_speech' => 'verb',
                'meaning' => 'To carry out / To proceed',
                'meaning_zh' => '进行',
                'example_sentence' => '进行讨论。',
                'example_translation' => 'Carry out a discussion.',
                'definition' => 'To carry out, to proceed',
                'sentences' => ['___中。', '___工作。', '___调查。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '继续',
                'pinyin' => 'jì xù',
                'simplified' => '继续',
                'traditional' => '繼續',
                'part_of_speech' => 'verb',
                'meaning' => 'To continue',
                'meaning_zh' => '继续',
                'example_sentence' => '继续学习。',
                'example_translation' => 'Continue studying.',
                'definition' => 'To continue',
                'sentences' => ['___了。', '___努力。', '___工作。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '停止',
                'pinyin' => 'tíng zhǐ',
                'simplified' => '停止',
                'traditional' => '停止',
                'part_of_speech' => 'verb',
                'meaning' => 'To stop / To cease',
                'meaning_zh' => '停止',
                'example_sentence' => '停止工作。',
                'example_translation' => 'Stop working.',
                'definition' => 'To stop, to cease',
                'sentences' => ['___了。', '___活动。', '___运行。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '开始',
                'pinyin' => 'kāi shǐ',
                'simplified' => '开始',
                'traditional' => '開始',
                'part_of_speech' => 'verb',
                'meaning' => 'To begin / To start',
                'meaning_zh' => '开始',
                'example_sentence' => '开始工作。',
                'example_translation' => 'Start working.',
                'definition' => 'To begin, to start',
                'sentences' => ['___了。', '___时间。', '___做。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '结束',
                'pinyin' => 'jié shù',
                'simplified' => '结束',
                'traditional' => '結束',
                'part_of_speech' => 'verb',
                'meaning' => 'To end / To finish',
                'meaning_zh' => '结束',
                'example_sentence' => '工作结束。',
                'example_translation' => 'The work is finished.',
                'definition' => 'To end, to finish',
                'sentences' => ['___了。', '___时间。', '___工作。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '完成',
                'pinyin' => 'wán chéng',
                'simplified' => '完成',
                'traditional' => '完成',
                'part_of_speech' => 'verb',
                'meaning' => 'To complete / To finish',
                'meaning_zh' => '完成',
                'example_sentence' => '完成任务。',
                'example_translation' => 'Complete the task.',
                'definition' => 'To complete, to finish',
                'sentences' => ['___了。', '___工作。', '___作业。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '实现',
                'pinyin' => 'shí xiàn',
                'simplified' => '实现',
                'traditional' => '實現',
                'part_of_speech' => 'verb',
                'meaning' => 'To realize / To achieve',
                'meaning_zh' => '实现',
                'example_sentence' => '实现梦想。',
                'example_translation' => 'Realize a dream.',
                'definition' => 'To realize, to achieve',
                'sentences' => ['___了。', '___目标。', '___愿望。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '增加',
                'pinyin' => 'zēng jiā',
                'simplified' => '增加',
                'traditional' => '增加',
                'part_of_speech' => 'verb',
                'meaning' => 'To increase / To add',
                'meaning_zh' => '增加',
                'example_sentence' => '增加数量。',
                'example_translation' => 'Increase the quantity.',
                'definition' => 'To increase, to add',
                'sentences' => ['___了。', '___收入。', '___投资。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '减少',
                'pinyin' => 'jiǎn shǎo',
                'simplified' => '减少',
                'traditional' => '減少',
                'part_of_speech' => 'verb',
                'meaning' => 'To decrease / To reduce',
                'meaning_zh' => '减少',
                'example_sentence' => '减少开支。',
                'example_translation' => 'Reduce expenses.',
                'definition' => 'To decrease, to reduce',
                'sentences' => ['___了。', '___污染。', '___浪费。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '提高',
                'pinyin' => 'tí gāo',
                'simplified' => '提高',
                'traditional' => '提高',
                'part_of_speech' => 'verb',
                'meaning' => 'To improve / To raise',
                'meaning_zh' => '提高',
                'example_sentence' => '提高水平。',
                'example_translation' => 'Improve the level.',
                'definition' => 'To improve, to raise',
                'sentences' => ['___了。', '___效率。', '___质量。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '降低',
                'pinyin' => 'jiàng dī',
                'simplified' => '降低',
                'traditional' => '降低',
                'part_of_speech' => 'verb',
                'meaning' => 'To lower / To reduce',
                'meaning_zh' => '降低',
                'example_sentence' => '降低价格。',
                'example_translation' => 'Lower the price.',
                'definition' => 'To lower, to reduce',
                'sentences' => ['___了。', '___成本。', '___标准。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '保护',
                'pinyin' => 'bǎo hù',
                'simplified' => '保护',
                'traditional' => '保護',
                'part_of_speech' => 'verb',
                'meaning' => 'To protect',
                'meaning_zh' => '保护',
                'example_sentence' => '保护环境。',
                'example_translation' => 'Protect the environment.',
                'definition' => 'To protect, protection',
                'sentences' => ['___自己。', '___措施。', '___野生动物。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '破坏',
                'pinyin' => 'pò huài',
                'simplified' => '破坏',
                'traditional' => '破壞',
                'part_of_speech' => 'verb',
                'meaning' => 'To destroy / To damage',
                'meaning_zh' => '破坏',
                'example_sentence' => '破坏环境。',
                'example_translation' => 'Damage the environment.',
                'definition' => 'To destroy, to damage',
                'sentences' => ['___了。', '___规则。', '___关系。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '影响',
                'pinyin' => 'yǐng xiǎng',
                'simplified' => '影响',
                'traditional' => '影響',
                'part_of_speech' => 'verb',
                'meaning' => 'To influence / To affect',
                'meaning_zh' => '影响',
                'example_sentence' => '影响健康。',
                'example_translation' => 'Affect health.',
                'definition' => 'To influence, to affect, influence',
                'sentences' => ['___很大。', '___他人。', '___力。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '允许',
                'pinyin' => 'yǔn xǔ',
                'simplified' => '允许',
                'traditional' => '允許',
                'part_of_speech' => 'verb',
                'meaning' => 'To permit / To allow',
                'meaning_zh' => '允许',
                'example_sentence' => '允许进入。',
                'example_translation' => 'Allow entry.',
                'definition' => 'To permit, to allow',
                'sentences' => ['___了。', '___吗？', '不___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '禁止',
                'pinyin' => 'jìn zhǐ',
                'simplified' => '禁止',
                'traditional' => '禁止',
                'part_of_speech' => 'verb',
                'meaning' => 'To prohibit / To forbid',
                'meaning_zh' => '禁止',
                'example_sentence' => '禁止吸烟。',
                'example_translation' => 'No smoking.',
                'definition' => 'To prohibit, to forbid',
                'sentences' => ['___停车。', '___入内。', '___使用。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 79,
                'word' => '取消',
                'pinyin' => 'qǔ xiāo',
                'simplified' => '取消',
                'traditional' => '取消',
                'part_of_speech' => 'verb',
                'meaning' => 'To cancel',
                'meaning_zh' => '取消',
                'example_sentence' => '取消会议。',
                'example_translation' => 'Cancel the meeting.',
                'definition' => 'To cancel',
                'sentences' => ['___了。', '___订单。', '___计划。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 80: Adjectives (形容词) - 20 words
        $adjectivesVocab = [
            [
                'topic_id' => 80,
                'word' => '正常',
                'pinyin' => 'zhèng cháng',
                'simplified' => '正常',
                'traditional' => '正常',
                'part_of_speech' => 'adjective',
                'meaning' => 'Normal',
                'meaning_zh' => '正常',
                'example_sentence' => '这很正常。',
                'example_translation' => 'This is normal.',
                'definition' => 'Normal',
                'sentences' => ['___现象。', '___情况。', '___工作。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '特别',
                'pinyin' => 'tè bié',
                'simplified' => '特别',
                'traditional' => '特別',
                'part_of_speech' => 'adjective',
                'meaning' => 'Special / Especially',
                'meaning_zh' => '特别',
                'example_sentence' => '特别好。',
                'example_translation' => 'Especially good.',
                'definition' => 'Special, especially, particular',
                'sentences' => ['___的。', '___喜欢。', '___关注。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '普通',
                'pinyin' => 'pǔ tōng',
                'simplified' => '普通',
                'traditional' => '普通',
                'part_of_speech' => 'adjective',
                'meaning' => 'Ordinary / Common',
                'meaning_zh' => '普通',
                'example_sentence' => '普通人。',
                'example_translation' => 'Ordinary person.',
                'definition' => 'Ordinary, common',
                'sentences' => ['___的。', '___话。', '___员工。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '简单',
                'pinyin' => 'jiǎn dān',
                'simplified' => '简单',
                'traditional' => '簡單',
                'part_of_speech' => 'adjective',
                'meaning' => 'Simple / Easy',
                'meaning_zh' => '简单',
                'example_sentence' => '很简单。',
                'example_translation' => 'Very simple.',
                'definition' => 'Simple, easy',
                'sentences' => ['___的题。', '___明了。', '___易懂。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '复杂',
                'pinyin' => 'fù zá',
                'simplified' => '复杂',
                'traditional' => '複雜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Complex / Complicated',
                'meaning_zh' => '复杂',
                'example_sentence' => '很复杂。',
                'example_translation' => 'Very complicated.',
                'definition' => 'Complex, complicated',
                'sentences' => ['___的问题。', '___情况。', '___关系。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '困难',
                'pinyin' => 'kùn nan',
                'simplified' => '困难',
                'traditional' => '困難',
                'part_of_speech' => 'adjective',
                'meaning' => 'Difficult / Difficulty',
                'meaning_zh' => '困难',
                'example_sentence' => '很困难。',
                'example_translation' => 'Very difficult.',
                'definition' => 'Difficult, difficulty',
                'sentences' => ['___的事。', '___时期。', '克服___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '容易',
                'pinyin' => 'róng yì',
                'simplified' => '容易',
                'traditional' => '容易',
                'part_of_speech' => 'adjective',
                'meaning' => 'Easy',
                'meaning_zh' => '容易',
                'example_sentence' => '很容易。',
                'example_translation' => 'Very easy.',
                'definition' => 'Easy',
                'sentences' => ['___学。', '___理解。', '___做。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '方便',
                'pinyin' => 'fāng biàn',
                'simplified' => '方便',
                'traditional' => '方便',
                'part_of_speech' => 'adjective',
                'meaning' => 'Convenient',
                'meaning_zh' => '方便',
                'example_sentence' => '很方便。',
                'example_translation' => 'Very convenient.',
                'definition' => 'Convenient',
                'sentences' => ['___的交通。', '___吗？', '___面。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '危险',
                'pinyin' => 'wēi xiǎn',
                'simplified' => '危险',
                'traditional' => '危險',
                'part_of_speech' => 'adjective',
                'meaning' => 'Dangerous / Danger',
                'meaning_zh' => '危险',
                'example_sentence' => '很危险。',
                'example_translation' => 'Very dangerous.',
                'definition' => 'Dangerous, danger',
                'sentences' => ['___的地方。', '___了。', '___性。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '安全',
                'pinyin' => 'ān quán',
                'simplified' => '安全',
                'traditional' => '安全',
                'part_of_speech' => 'adjective',
                'meaning' => 'Safe / Safety',
                'meaning_zh' => '安全',
                'example_sentence' => '很安全。',
                'example_translation' => 'Very safe.',
                'definition' => 'Safe, safety, secure',
                'sentences' => ['___的地方。', '___措施。', '___第一。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '严重',
                'pinyin' => 'yán zhòng',
                'simplified' => '严重',
                'traditional' => '嚴重',
                'part_of_speech' => 'adjective',
                'meaning' => 'Serious / Severe',
                'meaning_zh' => '严重',
                'example_sentence' => '问题很严重。',
                'example_translation' => 'The problem is serious.',
                'definition' => 'Serious, severe',
                'sentences' => ['___的问题。', '___性。', '___后果。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '严格',
                'pinyin' => 'yán gé',
                'simplified' => '严格',
                'traditional' => '嚴格',
                'part_of_speech' => 'adjective',
                'meaning' => 'Strict / Rigorous',
                'meaning_zh' => '严格',
                'example_sentence' => '要求严格。',
                'example_translation' => 'Strict requirements.',
                'definition' => 'Strict, rigorous',
                'sentences' => ['___的老师。', '___管理。', '___要求。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '重要',
                'pinyin' => 'zhòng yào',
                'simplified' => '重要',
                'traditional' => '重要',
                'part_of_speech' => 'adjective',
                'meaning' => 'Important',
                'meaning_zh' => '重要',
                'example_sentence' => '很重要。',
                'example_translation' => 'Very important.',
                'definition' => 'Important',
                'sentences' => ['___的事。', '___性。', '___人物。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '必要',
                'pinyin' => 'bì yào',
                'simplified' => '必要',
                'traditional' => '必要',
                'part_of_speech' => 'adjective',
                'meaning' => 'Necessary',
                'meaning_zh' => '必要',
                'example_sentence' => '很必要。',
                'example_translation' => 'Very necessary.',
                'definition' => 'Necessary',
                'sentences' => ['___的。', '___性。', '___措施。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '可能',
                'pinyin' => 'kě néng',
                'simplified' => '可能',
                'traditional' => '可能',
                'part_of_speech' => 'adjective',
                'meaning' => 'Possible / Possibly',
                'meaning_zh' => '可能',
                'example_sentence' => '有可能。',
                'example_translation' => 'It\'s possible.',
                'definition' => 'Possible, possibly, may',
                'sentences' => ['___性。', '___会。', '___的结果。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '不可能',
                'pinyin' => 'bù kě néng',
                'simplified' => '不可能',
                'traditional' => '不可能',
                'part_of_speech' => 'adjective',
                'meaning' => 'Impossible',
                'meaning_zh' => '不可能',
                'example_sentence' => '这不可能。',
                'example_translation' => 'This is impossible.',
                'definition' => 'Impossible',
                'sentences' => ['___的事。', '___做到。', '___实现。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '完全',
                'pinyin' => 'wán quán',
                'simplified' => '完全',
                'traditional' => '完全',
                'part_of_speech' => 'adjective',
                'meaning' => 'Complete / Completely',
                'meaning_zh' => '完全',
                'example_sentence' => '完全正确。',
                'example_translation' => 'Completely correct.',
                'definition' => 'Complete, completely, totally',
                'sentences' => ['___的。', '___不同。', '___理解。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '明显',
                'pinyin' => 'míng xiǎn',
                'simplified' => '明显',
                'traditional' => '明顯',
                'part_of_speech' => 'adjective',
                'meaning' => 'Obvious / Clear',
                'meaning_zh' => '明显',
                'example_sentence' => '很明显。',
                'example_translation' => 'Very obvious.',
                'definition' => 'Obvious, clear, evident',
                'sentences' => ['___的。', '___错误。', '___变化。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '清楚',
                'pinyin' => 'qīng chu',
                'simplified' => '清楚',
                'traditional' => '清楚',
                'part_of_speech' => 'adjective',
                'meaning' => 'Clear / Clearly',
                'meaning_zh' => '清楚',
                'example_sentence' => '说清楚。',
                'example_translation' => 'Speak clearly.',
                'definition' => 'Clear, clearly',
                'sentences' => ['___的。', '___了。', '不___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 80,
                'word' => '明白',
                'pinyin' => 'míng bai',
                'simplified' => '明白',
                'traditional' => '明白',
                'part_of_speech' => 'adjective',
                'meaning' => 'Clear / To understand',
                'meaning_zh' => '明白',
                'example_sentence' => '我明白了。',
                'example_translation' => 'I understand.',
                'definition' => 'Clear, to understand',
                'sentences' => ['___了。', '___吗？', '___道理。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 81: Adverbs (副词) - 20 words
        $adverbsVocab = [
            [
                'topic_id' => 81,
                'word' => '刚才',
                'pinyin' => 'gāng cái',
                'simplified' => '刚才',
                'traditional' => '剛才',
                'part_of_speech' => 'adverb',
                'meaning' => 'Just now / A moment ago',
                'meaning_zh' => '刚才',
                'example_sentence' => '刚才见过。',
                'example_translation' => 'Saw just now.',
                'definition' => 'Just now, a moment ago',
                'sentences' => ['___说的。', '___来了。', '___的事。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '刚刚',
                'pinyin' => 'gāng gang',
                'simplified' => '刚刚',
                'traditional' => '剛剛',
                'part_of_speech' => 'adverb',
                'meaning' => 'Just / Just now',
                'meaning_zh' => '刚刚',
                'example_sentence' => '刚刚到。',
                'example_translation' => 'Just arrived.',
                'definition' => 'Just, just now',
                'sentences' => ['___好。', '___开始。', '___发生。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '马上',
                'pinyin' => 'mǎ shàng',
                'simplified' => '马上',
                'traditional' => '馬上',
                'part_of_speech' => 'adverb',
                'meaning' => 'Immediately / Right away',
                'meaning_zh' => '马上',
                'example_sentence' => '马上来。',
                'example_translation' => 'Coming right away.',
                'definition' => 'Immediately, right away, at once',
                'sentences' => ['___去。', '___就好。', '___开始。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '立刻',
                'pinyin' => 'lì kè',
                'simplified' => '立刻',
                'traditional' => '立刻',
                'part_of_speech' => 'adverb',
                'meaning' => 'Immediately / At once',
                'meaning_zh' => '立刻',
                'example_sentence' => '立刻行动。',
                'example_translation' => 'Act immediately.',
                'definition' => 'Immediately, at once',
                'sentences' => ['___去。', '___停止。', '___出发。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '终于',
                'pinyin' => 'zhōng yú',
                'simplified' => '终于',
                'traditional' => '終於',
                'part_of_speech' => 'adverb',
                'meaning' => 'Finally / At last',
                'meaning_zh' => '终于',
                'example_sentence' => '终于到了。',
                'example_translation' => 'Finally arrived.',
                'definition' => 'Finally, at last',
                'sentences' => ['___成功了。', '___明白了。', '___来了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '仍然',
                'pinyin' => 'réng rán',
                'simplified' => '仍然',
                'traditional' => '仍然',
                'part_of_speech' => 'adverb',
                'meaning' => 'Still / Yet',
                'meaning_zh' => '仍然',
                'example_sentence' => '仍然在这里。',
                'example_translation' => 'Still here.',
                'definition' => 'Still, yet',
                'sentences' => ['___是。', '___坚持。', '___继续。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '依然',
                'pinyin' => 'yī rán',
                'simplified' => '依然',
                'traditional' => '依然',
                'part_of_speech' => 'adverb',
                'meaning' => 'Still / As before',
                'meaning_zh' => '依然',
                'example_sentence' => '依然如故。',
                'example_translation' => 'Still the same.',
                'definition' => 'Still, as before',
                'sentences' => ['___是。', '___记得。', '___美丽。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '已经',
                'pinyin' => 'yǐ jing',
                'simplified' => '已经',
                'traditional' => '已經',
                'part_of_speech' => 'adverb',
                'meaning' => 'Already',
                'meaning_zh' => '已经',
                'example_sentence' => '已经到了。',
                'example_translation' => 'Already arrived.',
                'definition' => 'Already',
                'sentences' => ['___晚了。', '___知道了。', '___完成了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '从来',
                'pinyin' => 'cóng lái',
                'simplified' => '从来',
                'traditional' => '從來',
                'part_of_speech' => 'adverb',
                'meaning' => 'Always / All along',
                'meaning_zh' => '从来',
                'example_sentence' => '从来没去过。',
                'example_translation' => 'Have never been.',
                'definition' => 'Always, all along, ever (in negatives)',
                'sentences' => ['___不。', '___没有。', '___如此。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '从不',
                'pinyin' => 'cóng bù',
                'simplified' => '从不',
                'traditional' => '從不',
                'part_of_speech' => 'adverb',
                'meaning' => 'Never',
                'meaning_zh' => '从不',
                'example_sentence' => '从不迟到。',
                'example_translation' => 'Never late.',
                'definition' => 'Never',
                'sentences' => ['___放弃。', '___说谎。', '___后悔。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '总是',
                'pinyin' => 'zǒng shì',
                'simplified' => '总是',
                'traditional' => '總是',
                'part_of_speech' => 'adverb',
                'meaning' => 'Always',
                'meaning_zh' => '总是',
                'example_sentence' => '总是迟到。',
                'example_translation' => 'Always late.',
                'definition' => 'Always',
                'sentences' => ['___这样。', '___忘记。', '___如此。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '经常',
                'pinyin' => 'jīng cháng',
                'simplified' => '经常',
                'traditional' => '經常',
                'part_of_speech' => 'adverb',
                'meaning' => 'Often / Frequently',
                'meaning_zh' => '经常',
                'example_sentence' => '经常去。',
                'example_translation' => 'Often go.',
                'definition' => 'Often, frequently',
                'sentences' => ['___做。', '___见面。', '___锻炼。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '偶尔',
                'pinyin' => 'ǒu ěr',
                'simplified' => '偶尔',
                'traditional' => '偶爾',
                'part_of_speech' => 'adverb',
                'meaning' => 'Occasionally / Once in a while',
                'meaning_zh' => '偶尔',
                'example_sentence' => '偶尔去。',
                'example_translation' => 'Occasionally go.',
                'definition' => 'Occasionally, once in a while',
                'sentences' => ['___做。', '___见面。', '___想起。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '几乎',
                'pinyin' => 'jī hū',
                'simplified' => '几乎',
                'traditional' => '幾乎',
                'part_of_speech' => 'adverb',
                'meaning' => 'Almost / Nearly',
                'meaning_zh' => '几乎',
                'example_sentence' => '几乎一样。',
                'example_translation' => 'Almost the same.',
                'definition' => 'Almost, nearly',
                'sentences' => ['___没有。', '___全部。', '___不可能。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '大约',
                'pinyin' => 'dà yuē',
                'simplified' => '大约',
                'traditional' => '大約',
                'part_of_speech' => 'adverb',
                'meaning' => 'Approximately / About',
                'meaning_zh' => '大约',
                'example_sentence' => '大约十点。',
                'example_translation' => 'About ten o\'clock.',
                'definition' => 'Approximately, about',
                'sentences' => ['___一百人。', '___三天。', '___多少？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '大概',
                'pinyin' => 'dà gài',
                'simplified' => '大概',
                'traditional' => '大概',
                'part_of_speech' => 'adverb',
                'meaning' => 'Probably / Approximately',
                'meaning_zh' => '大概',
                'example_sentence' => '大概明天。',
                'example_translation' => 'Probably tomorrow.',
                'definition' => 'Probably, approximately, roughly',
                'sentences' => ['___是。', '___十点。', '___如此。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '反而',
                'pinyin' => 'fǎn ér',
                'simplified' => '反而',
                'traditional' => '反而',
                'part_of_speech' => 'adverb',
                'meaning' => 'On the contrary / Instead',
                'meaning_zh' => '反而',
                'example_sentence' => '反而更好。',
                'example_translation' => 'On the contrary, it\'s better.',
                'definition' => 'On the contrary, instead',
                'sentences' => ['___不好。', '___更难。', '___高兴。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '究竟',
                'pinyin' => 'jiū jìng',
                'simplified' => '究竟',
                'traditional' => '究竟',
                'part_of_speech' => 'adverb',
                'meaning' => 'Actually / After all',
                'meaning_zh' => '究竟',
                'example_sentence' => '究竟是什么？',
                'example_translation' => 'What is it actually?',
                'definition' => 'Actually, after all, in the end',
                'sentences' => ['___怎么回事？', '___是谁？', '___为什么？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '根本',
                'pinyin' => 'gēn běn',
                'simplified' => '根本',
                'traditional' => '根本',
                'part_of_speech' => 'adverb',
                'meaning' => 'Simply / At all',
                'meaning_zh' => '根本',
                'example_sentence' => '根本不知道。',
                'example_translation' => 'Simply don\'t know.',
                'definition' => 'Simply, at all, fundamental',
                'sentences' => ['___不。', '___没有。', '___问题。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 81,
                'word' => '究竟',
                'pinyin' => 'jiū jìng',
                'simplified' => '究竟',
                'traditional' => '究竟',
                'part_of_speech' => 'adverb',
                'meaning' => 'Exactly / After all',
                'meaning_zh' => '究竟',
                'example_sentence' => '究竟发生了什么？',
                'example_translation' => 'What exactly happened?',
                'definition' => 'Exactly, after all',
                'sentences' => ['___是什么？', '___怎么了？', '___要干什么？'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($technologyVocab, $verbsVocab, $adjectivesVocab, $adverbsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
