<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics1to3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 63: Daily Life and Habits (日常生活和习惯) - 20 words
        $dailyLifeVocab = [
            [
                'topic_id' => 63,
                'word' => '习惯',
                'pinyin' => 'xí guàn',
                'simplified' => '习惯',
                'traditional' => '習慣',
                'part_of_speech' => 'noun',
                'meaning' => 'Habit / To be accustomed to',
                'meaning_zh' => '习惯',
                'example_sentence' => '我习惯早起。',
                'example_translation' => 'I am accustomed to getting up early.',
                'definition' => 'Habit, to be accustomed to',
                'sentences' => ['___很好。', '___了。', '养成___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '生活',
                'pinyin' => 'shēng huó',
                'simplified' => '生活',
                'traditional' => '生活',
                'part_of_speech' => 'noun',
                'meaning' => 'Life / To live',
                'meaning_zh' => '生活',
                'example_sentence' => '我的生活很简单。',
                'example_translation' => 'My life is very simple.',
                'definition' => 'Life, to live',
                'sentences' => ['___很好。', '日常___。', '___方式。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '起床',
                'pinyin' => 'qǐ chuáng',
                'simplified' => '起床',
                'traditional' => '起床',
                'part_of_speech' => 'verb',
                'meaning' => 'To get up / To get out of bed',
                'meaning_zh' => '起床',
                'example_sentence' => '我每天七点起床。',
                'example_translation' => 'I get up at 7 every day.',
                'definition' => 'To get up, to get out of bed',
                'sentences' => ['___了。', '早___。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '睡觉',
                'pinyin' => 'shuì jiào',
                'simplified' => '睡觉',
                'traditional' => '睡覺',
                'part_of_speech' => 'verb',
                'meaning' => 'To sleep / To go to bed',
                'meaning_zh' => '睡觉',
                'example_sentence' => '我晚上十点睡觉。',
                'example_translation' => 'I go to bed at 10 pm.',
                'definition' => 'To sleep, to go to bed',
                'sentences' => ['___了。', '早___。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '洗澡',
                'pinyin' => 'xǐ zǎo',
                'simplified' => '洗澡',
                'traditional' => '洗澡',
                'part_of_speech' => 'verb',
                'meaning' => 'To take a bath / To shower',
                'meaning_zh' => '洗澡',
                'example_sentence' => '我喜欢洗澡。',
                'example_translation' => 'I like taking a bath.',
                'definition' => 'To take a bath, to shower',
                'sentences' => ['___了。', '去___。', '___水。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '刷牙',
                'pinyin' => 'shuā yá',
                'simplified' => '刷牙',
                'traditional' => '刷牙',
                'part_of_speech' => 'verb',
                'meaning' => 'To brush teeth',
                'meaning_zh' => '刷牙',
                'example_sentence' => '早上刷牙。',
                'example_translation' => 'Brush teeth in the morning.',
                'definition' => 'To brush teeth',
                'sentences' => ['___了。', '___洗脸。', '___的习惯。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '洗脸',
                'pinyin' => 'xǐ liǎn',
                'simplified' => '洗脸',
                'traditional' => '洗臉',
                'part_of_speech' => 'verb',
                'meaning' => 'To wash face',
                'meaning_zh' => '洗脸',
                'example_sentence' => '我去洗脸。',
                'example_translation' => 'I\'m going to wash my face.',
                'definition' => 'To wash face',
                'sentences' => ['___了。', '___刷牙。', '___水。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '锻炼',
                'pinyin' => 'duàn liàn',
                'simplified' => '锻炼',
                'traditional' => '鍛煉',
                'part_of_speech' => 'verb',
                'meaning' => 'To exercise / To work out',
                'meaning_zh' => '锻炼',
                'example_sentence' => '我每天锻炼。',
                'example_translation' => 'I exercise every day.',
                'definition' => 'To exercise, to work out',
                'sentences' => ['___身体。', '___了。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '散步',
                'pinyin' => 'sàn bù',
                'simplified' => '散步',
                'traditional' => '散步',
                'part_of_speech' => 'verb',
                'meaning' => 'To take a walk / To stroll',
                'meaning_zh' => '散步',
                'example_sentence' => '晚上去散步。',
                'example_translation' => 'Go for a walk in the evening.',
                'definition' => 'To take a walk, to stroll',
                'sentences' => ['___了。', '去___。', '___公园。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '休息',
                'pinyin' => 'xiū xi',
                'simplified' => '休息',
                'traditional' => '休息',
                'part_of_speech' => 'verb',
                'meaning' => 'To rest / To take a break',
                'meaning_zh' => '休息',
                'example_sentence' => '我需要休息。',
                'example_translation' => 'I need to rest.',
                'definition' => 'To rest, to take a break',
                'sentences' => ['___一下。', '___时间。', '好好___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '准备',
                'pinyin' => 'zhǔn bèi',
                'simplified' => '准备',
                'traditional' => '準備',
                'part_of_speech' => 'verb',
                'meaning' => 'To prepare / To get ready',
                'meaning_zh' => '准备',
                'example_sentence' => '我在准备考试。',
                'example_translation' => 'I am preparing for the exam.',
                'definition' => 'To prepare, to get ready',
                'sentences' => ['___好了。', '___考试。', '___工作。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '安排',
                'pinyin' => 'ān pái',
                'simplified' => '安排',
                'traditional' => '安排',
                'part_of_speech' => 'verb',
                'meaning' => 'To arrange / To plan',
                'meaning_zh' => '安排',
                'example_sentence' => '我安排时间。',
                'example_translation' => 'I arrange the time.',
                'definition' => 'To arrange, to plan, arrangement',
                'sentences' => ['___好了。', '___时间。', '___工作。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '规律',
                'pinyin' => 'guī lǜ',
                'simplified' => '规律',
                'traditional' => '規律',
                'part_of_speech' => 'noun',
                'meaning' => 'Regular / Law / Pattern',
                'meaning_zh' => '规律',
                'example_sentence' => '生活很规律。',
                'example_translation' => 'Life is very regular.',
                'definition' => 'Regular, law, pattern',
                'sentences' => ['___的生活。', '有___。', '___作息。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '按时',
                'pinyin' => 'àn shí',
                'simplified' => '按时',
                'traditional' => '按時',
                'part_of_speech' => 'adverb',
                'meaning' => 'On time / Punctually',
                'meaning_zh' => '按时',
                'example_sentence' => '我按时起床。',
                'example_translation' => 'I get up on time.',
                'definition' => 'On time, punctually',
                'sentences' => ['___到达。', '___完成。', '___睡觉。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '准时',
                'pinyin' => 'zhǔn shí',
                'simplified' => '准时',
                'traditional' => '準時',
                'part_of_speech' => 'adjective',
                'meaning' => 'Punctual / On time',
                'meaning_zh' => '准时',
                'example_sentence' => '他很准时。',
                'example_translation' => 'He is very punctual.',
                'definition' => 'Punctual, on time',
                'sentences' => ['___到达。', '很___。', '___出发。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '改变',
                'pinyin' => 'gǎi biàn',
                'simplified' => '改变',
                'traditional' => '改變',
                'part_of_speech' => 'verb',
                'meaning' => 'To change',
                'meaning_zh' => '改变',
                'example_sentence' => '我想改变习惯。',
                'example_translation' => 'I want to change my habits.',
                'definition' => 'To change, change',
                'sentences' => ['___习惯。', '___了。', '___生活。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '坚持',
                'pinyin' => 'jiān chí',
                'simplified' => '坚持',
                'traditional' => '堅持',
                'part_of_speech' => 'verb',
                'meaning' => 'To persist / To insist',
                'meaning_zh' => '坚持',
                'example_sentence' => '坚持锻炼。',
                'example_translation' => 'Persist in exercising.',
                'definition' => 'To persist, to insist, to stick to',
                'sentences' => ['___下去。', '___学习。', '___运动。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '养成',
                'pinyin' => 'yǎng chéng',
                'simplified' => '养成',
                'traditional' => '養成',
                'part_of_speech' => 'verb',
                'meaning' => 'To form / To develop (habit)',
                'meaning_zh' => '养成',
                'example_sentence' => '养成好习惯。',
                'example_translation' => 'Develop good habits.',
                'definition' => 'To form, to develop (a habit)',
                'sentences' => ['___习惯。', '___了。', '___好习惯。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '保持',
                'pinyin' => 'bǎo chí',
                'simplified' => '保持',
                'traditional' => '保持',
                'part_of_speech' => 'verb',
                'meaning' => 'To keep / To maintain',
                'meaning_zh' => '保持',
                'example_sentence' => '保持健康。',
                'example_translation' => 'Keep healthy.',
                'definition' => 'To keep, to maintain',
                'sentences' => ['___习惯。', '___联系。', '___健康。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 63,
                'word' => '注意',
                'pinyin' => 'zhù yì',
                'simplified' => '注意',
                'traditional' => '注意',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay attention to / To be careful',
                'meaning_zh' => '注意',
                'example_sentence' => '注意安全。',
                'example_translation' => 'Pay attention to safety.',
                'definition' => 'To pay attention to, to be careful',
                'sentences' => ['___安全。', '___身体。', '___休息。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 64: Housework and Chores (家务活) - 20 words
        $houseworkVocab = [
            [
                'topic_id' => 64,
                'word' => '打扫',
                'pinyin' => 'dǎ sǎo',
                'simplified' => '打扫',
                'traditional' => '打掃',
                'part_of_speech' => 'verb',
                'meaning' => 'To clean / To sweep',
                'meaning_zh' => '打扫',
                'example_sentence' => '打扫房间。',
                'example_translation' => 'Clean the room.',
                'definition' => 'To clean, to sweep',
                'sentences' => ['___房间。', '___卫生。', '___干净。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '整理',
                'pinyin' => 'zhěng lǐ',
                'simplified' => '整理',
                'traditional' => '整理',
                'part_of_speech' => 'verb',
                'meaning' => 'To tidy up / To arrange',
                'meaning_zh' => '整理',
                'example_sentence' => '整理房间。',
                'example_translation' => 'Tidy up the room.',
                'definition' => 'To tidy up, to arrange, to put in order',
                'sentences' => ['___房间。', '___东西。', '___好了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '洗衣服',
                'pinyin' => 'xǐ yī fu',
                'simplified' => '洗衣服',
                'traditional' => '洗衣服',
                'part_of_speech' => 'verb',
                'meaning' => 'To wash clothes / To do laundry',
                'meaning_zh' => '洗衣服',
                'example_sentence' => '我要洗衣服。',
                'example_translation' => 'I need to wash clothes.',
                'definition' => 'To wash clothes, to do laundry',
                'sentences' => ['___了。', '去___。', '___机。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '晾衣服',
                'pinyin' => 'liàng yī fu',
                'simplified' => '晾衣服',
                'traditional' => '晾衣服',
                'part_of_speech' => 'verb',
                'meaning' => 'To hang clothes to dry',
                'meaning_zh' => '晾衣服',
                'example_sentence' => '晾衣服在阳台。',
                'example_translation' => 'Hang clothes to dry on the balcony.',
                'definition' => 'To hang clothes to dry',
                'sentences' => ['___了。', '___架。', '___晒干。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '叠衣服',
                'pinyin' => 'dié yī fu',
                'simplified' => '叠衣服',
                'traditional' => '疊衣服',
                'part_of_speech' => 'verb',
                'meaning' => 'To fold clothes',
                'meaning_zh' => '叠衣服',
                'example_sentence' => '叠衣服放进柜子。',
                'example_translation' => 'Fold clothes and put in the closet.',
                'definition' => 'To fold clothes',
                'sentences' => ['___了。', '___整齐。', '___放好。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '扫地',
                'pinyin' => 'sǎo dì',
                'simplified' => '扫地',
                'traditional' => '掃地',
                'part_of_speech' => 'verb',
                'meaning' => 'To sweep the floor',
                'meaning_zh' => '扫地',
                'example_sentence' => '我在扫地。',
                'example_translation' => 'I am sweeping the floor.',
                'definition' => 'To sweep the floor',
                'sentences' => ['___了。', '___拖地。', '___的工具。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '拖地',
                'pinyin' => 'tuō dì',
                'simplified' => '拖地',
                'traditional' => '拖地',
                'part_of_speech' => 'verb',
                'meaning' => 'To mop the floor',
                'meaning_zh' => '拖地',
                'example_sentence' => '拖地很累。',
                'example_translation' => 'Mopping the floor is tiring.',
                'definition' => 'To mop the floor',
                'sentences' => ['___了。', '___干净。', '___板。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '擦桌子',
                'pinyin' => 'cā zhuō zi',
                'simplified' => '擦桌子',
                'traditional' => '擦桌子',
                'part_of_speech' => 'verb',
                'meaning' => 'To wipe the table',
                'meaning_zh' => '擦桌子',
                'example_sentence' => '吃完饭擦桌子。',
                'example_translation' => 'Wipe the table after eating.',
                'definition' => 'To wipe the table',
                'sentences' => ['___了。', '___干净。', '___布。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '洗碗',
                'pinyin' => 'xǐ wǎn',
                'simplified' => '洗碗',
                'traditional' => '洗碗',
                'part_of_speech' => 'verb',
                'meaning' => 'To wash dishes',
                'meaning_zh' => '洗碗',
                'example_sentence' => '我去洗碗。',
                'example_translation' => 'I\'m going to wash dishes.',
                'definition' => 'To wash dishes',
                'sentences' => ['___了。', '___机。', '___的工具。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '倒垃圾',
                'pinyin' => 'dào lā jī',
                'simplified' => '倒垃圾',
                'traditional' => '倒垃圾',
                'part_of_speech' => 'verb',
                'meaning' => 'To take out the trash',
                'meaning_zh' => '倒垃圾',
                'example_sentence' => '我去倒垃圾。',
                'example_translation' => 'I\'m going to take out the trash.',
                'definition' => 'To take out the trash',
                'sentences' => ['___了。', '___桶。', '___分类。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '做饭',
                'pinyin' => 'zuò fàn',
                'simplified' => '做饭',
                'traditional' => '做飯',
                'part_of_speech' => 'verb',
                'meaning' => 'To cook / To prepare a meal',
                'meaning_zh' => '做饭',
                'example_sentence' => '我会做饭。',
                'example_translation' => 'I can cook.',
                'definition' => 'To cook, to prepare a meal',
                'sentences' => ['___了。', '___吃。', '___的技能。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '收拾',
                'pinyin' => 'shōu shi',
                'simplified' => '收拾',
                'traditional' => '收拾',
                'part_of_speech' => 'verb',
                'meaning' => 'To tidy up / To pack',
                'meaning_zh' => '收拾',
                'example_sentence' => '收拾房间。',
                'example_translation' => 'Tidy up the room.',
                'definition' => 'To tidy up, to pack, to put in order',
                'sentences' => ['___房间。', '___东西。', '___干净。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '擦窗户',
                'pinyin' => 'cā chuāng hu',
                'simplified' => '擦窗户',
                'traditional' => '擦窗戶',
                'part_of_speech' => 'verb',
                'meaning' => 'To wipe the windows',
                'meaning_zh' => '擦窗户',
                'example_sentence' => '周末擦窗户。',
                'example_translation' => 'Wipe the windows on weekends.',
                'definition' => 'To wipe the windows',
                'sentences' => ['___了。', '___干净。', '___玻璃。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '干净',
                'pinyin' => 'gān jìng',
                'simplified' => '干净',
                'traditional' => '乾淨',
                'part_of_speech' => 'adjective',
                'meaning' => 'Clean',
                'meaning_zh' => '干净',
                'example_sentence' => '房间很干净。',
                'example_translation' => 'The room is very clean.',
                'definition' => 'Clean',
                'sentences' => ['很___。', '___的房间。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '脏',
                'pinyin' => 'zāng',
                'simplified' => '脏',
                'traditional' => '髒',
                'part_of_speech' => 'adjective',
                'meaning' => 'Dirty',
                'meaning_zh' => '脏',
                'example_sentence' => '衣服很脏。',
                'example_translation' => 'The clothes are very dirty.',
                'definition' => 'Dirty',
                'sentences' => ['很___。', '___了。', '___衣服。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '整齐',
                'pinyin' => 'zhěng qí',
                'simplified' => '整齐',
                'traditional' => '整齊',
                'part_of_speech' => 'adjective',
                'meaning' => 'Neat / Tidy',
                'meaning_zh' => '整齐',
                'example_sentence' => '书放得很整齐。',
                'example_translation' => 'The books are arranged very neatly.',
                'definition' => 'Neat, tidy, in good order',
                'sentences' => ['很___。', '___的房间。', '___摆放。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '乱',
                'pinyin' => 'luàn',
                'simplified' => '乱',
                'traditional' => '亂',
                'part_of_speech' => 'adjective',
                'meaning' => 'Messy / Chaotic',
                'meaning_zh' => '乱',
                'example_sentence' => '房间很乱。',
                'example_translation' => 'The room is very messy.',
                'definition' => 'Messy, chaotic, disorderly',
                'sentences' => ['很___。', '___了。', '___放。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '忙碌',
                'pinyin' => 'máng lù',
                'simplified' => '忙碌',
                'traditional' => '忙碌',
                'part_of_speech' => 'adjective',
                'meaning' => 'Busy',
                'meaning_zh' => '忙碌',
                'example_sentence' => '他很忙碌。',
                'example_translation' => 'He is very busy.',
                'definition' => 'Busy, busily engaged',
                'sentences' => ['很___。', '___的生活。', '___工作。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '累',
                'pinyin' => 'lèi',
                'simplified' => '累',
                'traditional' => '累',
                'part_of_speech' => 'adjective',
                'meaning' => 'Tired',
                'meaning_zh' => '累',
                'example_sentence' => '我很累。',
                'example_translation' => 'I am very tired.',
                'definition' => 'Tired, exhausted',
                'sentences' => ['很___。', '___了。', '___坏了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 64,
                'word' => '辛苦',
                'pinyin' => 'xīn kǔ',
                'simplified' => '辛苦',
                'traditional' => '辛苦',
                'part_of_speech' => 'adjective',
                'meaning' => 'Hard / Toilsome',
                'meaning_zh' => '辛苦',
                'example_sentence' => '做家务很辛苦。',
                'example_translation' => 'Doing housework is hard.',
                'definition' => 'Hard, toilsome, to work hard',
                'sentences' => ['很___。', '___了。', '___工作。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 65: At the Supermarket (在超市) - 20 words
        $supermarketVocab = [
            [
                'topic_id' => 65,
                'word' => '超市',
                'pinyin' => 'chāo shì',
                'simplified' => '超市',
                'traditional' => '超市',
                'part_of_speech' => 'noun',
                'meaning' => 'Supermarket',
                'meaning_zh' => '超市',
                'example_sentence' => '我去超市买东西。',
                'example_translation' => 'I go to the supermarket to buy things.',
                'definition' => 'Supermarket',
                'sentences' => ['去___。', '___购物。', '___很大。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '购物',
                'pinyin' => 'gòu wù',
                'simplified' => '购物',
                'traditional' => '購物',
                'part_of_speech' => 'verb',
                'meaning' => 'To shop / Shopping',
                'meaning_zh' => '购物',
                'example_sentence' => '我喜欢购物。',
                'example_translation' => 'I like shopping.',
                'definition' => 'To shop, shopping',
                'sentences' => ['___了。', '___车。', '___中心。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '购物车',
                'pinyin' => 'gòu wù chē',
                'simplified' => '购物车',
                'traditional' => '購物車',
                'part_of_speech' => 'noun',
                'meaning' => 'Shopping cart',
                'meaning_zh' => '购物车',
                'example_sentence' => '推购物车。',
                'example_translation' => 'Push the shopping cart.',
                'definition' => 'Shopping cart',
                'sentences' => ['推___。', '___很满。', '___里有什么？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '价格',
                'pinyin' => 'jià gé',
                'simplified' => '价格',
                'traditional' => '價格',
                'part_of_speech' => 'noun',
                'meaning' => 'Price',
                'meaning_zh' => '价格',
                'example_sentence' => '价格很便宜。',
                'example_translation' => 'The price is very cheap.',
                'definition' => 'Price',
                'sentences' => ['___便宜。', '___贵。', '___多少？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '打折',
                'pinyin' => 'dǎ zhé',
                'simplified' => '打折',
                'traditional' => '打折',
                'part_of_speech' => 'verb',
                'meaning' => 'To discount / On sale',
                'meaning_zh' => '打折',
                'example_sentence' => '这个商品打折。',
                'example_translation' => 'This product is on sale.',
                'definition' => 'To discount, on sale',
                'sentences' => ['___了。', '___商品。', '___季。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '优惠',
                'pinyin' => 'yōu huì',
                'simplified' => '优惠',
                'traditional' => '優惠',
                'part_of_speech' => 'noun',
                'meaning' => 'Discount / Preferential',
                'meaning_zh' => '优惠',
                'example_sentence' => '有优惠吗？',
                'example_translation' => 'Is there a discount?',
                'definition' => 'Discount, preferential',
                'sentences' => ['___活动。', '___券。', '___价格。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '便宜',
                'pinyin' => 'pián yi',
                'simplified' => '便宜',
                'traditional' => '便宜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cheap / Inexpensive',
                'meaning_zh' => '便宜',
                'example_sentence' => '这个很便宜。',
                'example_translation' => 'This is very cheap.',
                'definition' => 'Cheap, inexpensive',
                'sentences' => ['很___。', '___货。', '___点。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '贵',
                'pinyin' => 'guì',
                'simplified' => '贵',
                'traditional' => '貴',
                'part_of_speech' => 'adjective',
                'meaning' => 'Expensive',
                'meaning_zh' => '贵',
                'example_sentence' => '这个太贵了。',
                'example_translation' => 'This is too expensive.',
                'definition' => 'Expensive',
                'sentences' => ['太___了。', '___的东西。', '___不___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '付款',
                'pinyin' => 'fù kuǎn',
                'simplified' => '付款',
                'traditional' => '付款',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay',
                'meaning_zh' => '付款',
                'example_sentence' => '我去付款。',
                'example_translation' => 'I\'m going to pay.',
                'definition' => 'To pay, payment',
                'sentences' => ['___了。', '___方式。', '___台。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '收银台',
                'pinyin' => 'shōu yín tái',
                'simplified' => '收银台',
                'traditional' => '收銀台',
                'part_of_speech' => 'noun',
                'meaning' => 'Cashier / Checkout counter',
                'meaning_zh' => '收银台',
                'example_sentence' => '在收银台付款。',
                'example_translation' => 'Pay at the cashier.',
                'definition' => 'Cashier, checkout counter',
                'sentences' => ['在___。', '___排队。', '___工作。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '现金',
                'pinyin' => 'xiàn jīn',
                'simplified' => '现金',
                'traditional' => '現金',
                'part_of_speech' => 'noun',
                'meaning' => 'Cash',
                'meaning_zh' => '现金',
                'example_sentence' => '用现金付款。',
                'example_translation' => 'Pay with cash.',
                'definition' => 'Cash',
                'sentences' => ['___付款。', '___不够。', '___支付。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '刷卡',
                'pinyin' => 'shuā kǎ',
                'simplified' => '刷卡',
                'traditional' => '刷卡',
                'part_of_speech' => 'verb',
                'meaning' => 'To swipe a card / To pay by card',
                'meaning_zh' => '刷卡',
                'example_sentence' => '我可以刷卡吗？',
                'example_translation' => 'Can I pay by card?',
                'definition' => 'To swipe a card, to pay by card',
                'sentences' => ['___付款。', '___机。', '___支付。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '找零',
                'pinyin' => 'zhǎo líng',
                'simplified' => '找零',
                'traditional' => '找零',
                'part_of_speech' => 'verb',
                'meaning' => 'To give change',
                'meaning_zh' => '找零',
                'example_sentence' => '找零五元。',
                'example_translation' => 'Give 5 yuan change.',
                'definition' => 'To give change',
                'sentences' => ['___了。', '___钱。', '不用___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '小票',
                'pinyin' => 'xiǎo piào',
                'simplified' => '小票',
                'traditional' => '小票',
                'part_of_speech' => 'noun',
                'meaning' => 'Receipt',
                'meaning_zh' => '小票',
                'example_sentence' => '请给我小票。',
                'example_translation' => 'Please give me the receipt.',
                'definition' => 'Receipt',
                'sentences' => ['___在这里。', '___丢了。', '保留___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '袋子',
                'pinyin' => 'dài zi',
                'simplified' => '袋子',
                'traditional' => '袋子',
                'part_of_speech' => 'noun',
                'meaning' => 'Bag',
                'meaning_zh' => '袋子',
                'example_sentence' => '需要袋子吗？',
                'example_translation' => 'Do you need a bag?',
                'definition' => 'Bag',
                'sentences' => ['___里。', '塑料___。', '___装满了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '挑选',
                'pinyin' => 'tiāo xuǎn',
                'simplified' => '挑选',
                'traditional' => '挑選',
                'part_of_speech' => 'verb',
                'meaning' => 'To select / To choose',
                'meaning_zh' => '挑选',
                'example_sentence' => '挑选商品。',
                'example_translation' => 'Select products.',
                'definition' => 'To select, to choose, to pick',
                'sentences' => ['___了。', '___商品。', '___礼物。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '新鲜',
                'pinyin' => 'xīn xiān',
                'simplified' => '新鲜',
                'traditional' => '新鮮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fresh',
                'meaning_zh' => '新鲜',
                'example_sentence' => '这个很新鲜。',
                'example_translation' => 'This is very fresh.',
                'definition' => 'Fresh',
                'sentences' => ['很___。', '___的水果。', '___食材。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '促销',
                'pinyin' => 'cù xiāo',
                'simplified' => '促销',
                'traditional' => '促銷',
                'part_of_speech' => 'verb',
                'meaning' => 'To promote sales / Promotion',
                'meaning_zh' => '促销',
                'example_sentence' => '现在促销活动。',
                'example_translation' => 'There\'s a promotion now.',
                'definition' => 'To promote sales, promotion',
                'sentences' => ['___活动。', '___商品。', '___价格。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '排队',
                'pinyin' => 'pái duì',
                'simplified' => '排队',
                'traditional' => '排隊',
                'part_of_speech' => 'verb',
                'meaning' => 'To queue / To line up',
                'meaning_zh' => '排队',
                'example_sentence' => '排队付款。',
                'example_translation' => 'Queue to pay.',
                'definition' => 'To queue, to line up',
                'sentences' => ['___了。', '___等候。', '___很长。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 65,
                'word' => '退换',
                'pinyin' => 'tuì huàn',
                'simplified' => '退换',
                'traditional' => '退換',
                'part_of_speech' => 'verb',
                'meaning' => 'To return or exchange',
                'meaning_zh' => '退换',
                'example_sentence' => '可以退换吗？',
                'example_translation' => 'Can I return or exchange it?',
                'definition' => 'To return or exchange',
                'sentences' => ['___商品。', '___货。', '___政策。'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($dailyLifeVocab, $houseworkVocab, $supermarketVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
