<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics25to27Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 86: Question Words (疑问词) - 20 words
        $questionWordsVocab = [
            [
                'topic_id' => 86,
                'word' => '什么',
                'pinyin' => 'shén me',
                'simplified' => '什么',
                'traditional' => '什麼',
                'part_of_speech' => 'question word',
                'meaning' => 'What',
                'meaning_zh' => '什么',
                'example_sentence' => '这是什么？',
                'example_translation' => 'What is this?',
                'definition' => 'What',
                'sentences' => ['___东西？', '___时候？', '为___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '什么的',
                'pinyin' => 'shén me de',
                'simplified' => '什么的',
                'traditional' => '什麼的',
                'part_of_speech' => 'phrase',
                'meaning' => 'And so on / Etc.',
                'meaning_zh' => '什么的',
                'example_sentence' => '买书、笔什么的。',
                'example_translation' => 'Buy books, pens and so on.',
                'definition' => 'And so on, etc.',
                'sentences' => ['吃饭___。', '学习___。', '工作___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '谁',
                'pinyin' => 'shéi',
                'simplified' => '谁',
                'traditional' => '誰',
                'part_of_speech' => 'question word',
                'meaning' => 'Who / Whom',
                'meaning_zh' => '谁',
                'example_sentence' => '他是谁？',
                'example_translation' => 'Who is he?',
                'definition' => 'Who, whom',
                'sentences' => ['___的？', '___来？', '___知道？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '哪',
                'pinyin' => 'nǎ',
                'simplified' => '哪',
                'traditional' => '哪',
                'part_of_speech' => 'question word',
                'meaning' => 'Which',
                'meaning_zh' => '哪',
                'example_sentence' => '哪一个？',
                'example_translation' => 'Which one?',
                'definition' => 'Which',
                'sentences' => ['___个？', '___里？', '___天？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '哪儿',
                'pinyin' => 'nǎr',
                'simplified' => '哪儿',
                'traditional' => '哪兒',
                'part_of_speech' => 'question word',
                'meaning' => 'Where',
                'meaning_zh' => '哪儿',
                'example_sentence' => '你在哪儿？',
                'example_translation' => 'Where are you?',
                'definition' => 'Where',
                'sentences' => ['在___？', '去___？', '从___来？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '哪里',
                'pinyin' => 'nǎ lǐ',
                'simplified' => '哪里',
                'traditional' => '哪裡',
                'part_of_speech' => 'question word',
                'meaning' => 'Where / Not at all',
                'meaning_zh' => '哪里',
                'example_sentence' => '你在哪里？',
                'example_translation' => 'Where are you?',
                'definition' => 'Where, not at all (modesty)',
                'sentences' => ['在___？', '___的话。', '___不对？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '怎么',
                'pinyin' => 'zěn me',
                'simplified' => '怎么',
                'traditional' => '怎麼',
                'part_of_speech' => 'question word',
                'meaning' => 'How / Why',
                'meaning_zh' => '怎么',
                'example_sentence' => '怎么去？',
                'example_translation' => 'How to get there?',
                'definition' => 'How, why, what',
                'sentences' => ['___做？', '___了？', '___回事？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '怎样',
                'pinyin' => 'zěn yàng',
                'simplified' => '怎样',
                'traditional' => '怎樣',
                'part_of_speech' => 'question word',
                'meaning' => 'How / In what way',
                'meaning_zh' => '怎样',
                'example_sentence' => '怎样学习？',
                'example_translation' => 'How to study?',
                'definition' => 'How, in what way',
                'sentences' => ['___做？', '___才好？', '___的？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '几',
                'pinyin' => 'jǐ',
                'simplified' => '几',
                'traditional' => '幾',
                'part_of_speech' => 'question word',
                'meaning' => 'How many / Several',
                'meaning_zh' => '几',
                'example_sentence' => '几点了？',
                'example_translation' => 'What time is it?',
                'definition' => 'How many, several, a few',
                'sentences' => ['___个？', '___点？', '___天？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '多',
                'pinyin' => 'duō',
                'simplified' => '多',
                'traditional' => '多',
                'part_of_speech' => 'question word',
                'meaning' => 'How / Many',
                'meaning_zh' => '多',
                'example_sentence' => '多大了？',
                'example_translation' => 'How old?',
                'definition' => 'How, many, much, more',
                'sentences' => ['___少？', '___大？', '___长时间？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '多久',
                'pinyin' => 'duō jiǔ',
                'simplified' => '多久',
                'traditional' => '多久',
                'part_of_speech' => 'question word',
                'meaning' => 'How long (time)',
                'meaning_zh' => '多久',
                'example_sentence' => '要多久？',
                'example_translation' => 'How long does it take?',
                'definition' => 'How long (time duration)',
                'sentences' => ['___以后？', '___一次？', '需要___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '多长',
                'pinyin' => 'duō cháng',
                'simplified' => '多长',
                'traditional' => '多長',
                'part_of_speech' => 'question word',
                'meaning' => 'How long (length)',
                'meaning_zh' => '多长',
                'example_sentence' => '多长时间？',
                'example_translation' => 'How much time?',
                'definition' => 'How long (length or duration)',
                'sentences' => ['___？', '___时间？', '有___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '多远',
                'pinyin' => 'duō yuǎn',
                'simplified' => '多远',
                'traditional' => '多遠',
                'part_of_speech' => 'question word',
                'meaning' => 'How far',
                'meaning_zh' => '多远',
                'example_sentence' => '有多远？',
                'example_translation' => 'How far is it?',
                'definition' => 'How far (distance)',
                'sentences' => ['___？', '离这___？', '距离___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '多大',
                'pinyin' => 'duō dà',
                'simplified' => '多大',
                'traditional' => '多大',
                'part_of_speech' => 'question word',
                'meaning' => 'How old / How big',
                'meaning_zh' => '多大',
                'example_sentence' => '你多大了？',
                'example_translation' => 'How old are you?',
                'definition' => 'How old, how big',
                'sentences' => ['___？', '___年纪？', '有___？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '哪怕',
                'pinyin' => 'nǎ pà',
                'simplified' => '哪怕',
                'traditional' => '哪怕',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Even if / Even though',
                'meaning_zh' => '哪怕',
                'example_sentence' => '哪怕很难。',
                'example_translation' => 'Even if it\'s difficult.',
                'definition' => 'Even if, even though',
                'sentences' => ['___下雨。', '___一点。', '___失败。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '难道',
                'pinyin' => 'nán dào',
                'simplified' => '难道',
                'traditional' => '難道',
                'part_of_speech' => 'adverb',
                'meaning' => 'Could it be that / Don\'t tell me',
                'meaning_zh' => '难道',
                'example_sentence' => '难道你不知道？',
                'example_translation' => 'Don\'t you know?',
                'definition' => 'Could it be that, don\'t tell me',
                'sentences' => ['___不是？', '___是？', '___你不？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '究竟',
                'pinyin' => 'jiū jìng',
                'simplified' => '究竟',
                'traditional' => '究竟',
                'part_of_speech' => 'adverb',
                'meaning' => 'Actually / After all / Exactly',
                'meaning_zh' => '究竟',
                'example_sentence' => '究竟是什么？',
                'example_translation' => 'What exactly is it?',
                'definition' => 'Actually, after all, exactly',
                'sentences' => ['___是谁？', '___怎么了？', '___要什么？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '万一',
                'pinyin' => 'wàn yī',
                'simplified' => '万一',
                'traditional' => '萬一',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Just in case / If by chance',
                'meaning_zh' => '万一',
                'example_sentence' => '万一下雨怎么办？',
                'example_translation' => 'What if it rains?',
                'definition' => 'Just in case, if by chance',
                'sentences' => ['___不行。', '___失败。', '___出事。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '是否',
                'pinyin' => 'shì fǒu',
                'simplified' => '是否',
                'traditional' => '是否',
                'part_of_speech' => 'adverb',
                'meaning' => 'Whether or not',
                'meaning_zh' => '是否',
                'example_sentence' => '是否同意？',
                'example_translation' => 'Whether agree or not?',
                'definition' => 'Whether or not, if or not',
                'sentences' => ['___可以？', '___正确？', '___需要？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 86,
                'word' => '何必',
                'pinyin' => 'hé bì',
                'simplified' => '何必',
                'traditional' => '何必',
                'part_of_speech' => 'adverb',
                'meaning' => 'Why / Why bother',
                'meaning_zh' => '何必',
                'example_sentence' => '何必这样？',
                'example_translation' => 'Why do this?',
                'definition' => 'Why, why bother, what\'s the point',
                'sentences' => ['___呢？', '___担心？', '___生气？'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 87: Time Expression (时间表达) - 20 words
        $timeExpressionVocab = [
            [
                'topic_id' => 87,
                'word' => '早晨',
                'pinyin' => 'zǎo chen',
                'simplified' => '早晨',
                'traditional' => '早晨',
                'part_of_speech' => 'noun',
                'meaning' => 'Morning / Early morning',
                'meaning_zh' => '早晨',
                'example_sentence' => '早晨起床。',
                'example_translation' => 'Get up in the morning.',
                'definition' => 'Morning, early morning',
                'sentences' => ['___好。', '___锻炼。', '___的空气。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '中午',
                'pinyin' => 'zhōng wǔ',
                'simplified' => '中午',
                'traditional' => '中午',
                'part_of_speech' => 'noun',
                'meaning' => 'Noon / Midday',
                'meaning_zh' => '中午',
                'example_sentence' => '中午吃饭。',
                'example_translation' => 'Eat lunch at noon.',
                'definition' => 'Noon, midday',
                'sentences' => ['___好。', '___休息。', '___十二点。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '傍晚',
                'pinyin' => 'bàng wǎn',
                'simplified' => '傍晚',
                'traditional' => '傍晚',
                'part_of_speech' => 'noun',
                'meaning' => 'Dusk / Evening',
                'meaning_zh' => '傍晚',
                'example_sentence' => '傍晚散步。',
                'example_translation' => 'Take a walk at dusk.',
                'definition' => 'Dusk, evening, twilight',
                'sentences' => ['___时分。', '___回家。', '___的天空。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '半夜',
                'pinyin' => 'bàn yè',
                'simplified' => '半夜',
                'traditional' => '半夜',
                'part_of_speech' => 'noun',
                'meaning' => 'Midnight / Middle of the night',
                'meaning_zh' => '半夜',
                'example_sentence' => '半夜醒了。',
                'example_translation' => 'Woke up at midnight.',
                'definition' => 'Midnight, middle of the night',
                'sentences' => ['___三点。', '___起来。', '___睡不着。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '昨天',
                'pinyin' => 'zuó tiān',
                'simplified' => '昨天',
                'traditional' => '昨天',
                'part_of_speech' => 'noun',
                'meaning' => 'Yesterday',
                'meaning_zh' => '昨天',
                'example_sentence' => '昨天去了。',
                'example_translation' => 'Went yesterday.',
                'definition' => 'Yesterday',
                'sentences' => ['___的事。', '___晚上。', '___见过。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '今天',
                'pinyin' => 'jīn tiān',
                'simplified' => '今天',
                'traditional' => '今天',
                'part_of_speech' => 'noun',
                'meaning' => 'Today',
                'meaning_zh' => '今天',
                'example_sentence' => '今天星期几？',
                'example_translation' => 'What day is today?',
                'definition' => 'Today',
                'sentences' => ['___的天气。', '___做什么？', '___很忙。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '明天',
                'pinyin' => 'míng tiān',
                'simplified' => '明天',
                'traditional' => '明天',
                'part_of_speech' => 'noun',
                'meaning' => 'Tomorrow',
                'meaning_zh' => '明天',
                'example_sentence' => '明天见。',
                'example_translation' => 'See you tomorrow.',
                'definition' => 'Tomorrow',
                'sentences' => ['___去。', '___的计划。', '___再说。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '前天',
                'pinyin' => 'qián tiān',
                'simplified' => '前天',
                'traditional' => '前天',
                'part_of_speech' => 'noun',
                'meaning' => 'The day before yesterday',
                'meaning_zh' => '前天',
                'example_sentence' => '前天来的。',
                'example_translation' => 'Came the day before yesterday.',
                'definition' => 'The day before yesterday',
                'sentences' => ['___见过。', '___买的。', '___晚上。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '后天',
                'pinyin' => 'hòu tiān',
                'simplified' => '后天',
                'traditional' => '後天',
                'part_of_speech' => 'noun',
                'meaning' => 'The day after tomorrow',
                'meaning_zh' => '后天',
                'example_sentence' => '后天再去。',
                'example_translation' => 'Go again the day after tomorrow.',
                'definition' => 'The day after tomorrow',
                'sentences' => ['___见。', '___的会议。', '___出发。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '上周',
                'pinyin' => 'shàng zhōu',
                'simplified' => '上周',
                'traditional' => '上週',
                'part_of_speech' => 'noun',
                'meaning' => 'Last week',
                'meaning_zh' => '上周',
                'example_sentence' => '上周去过。',
                'example_translation' => 'Went last week.',
                'definition' => 'Last week',
                'sentences' => ['___的事。', '___末。', '___开始的。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '本周',
                'pinyin' => 'běn zhōu',
                'simplified' => '本周',
                'traditional' => '本週',
                'part_of_speech' => 'noun',
                'meaning' => 'This week',
                'meaning_zh' => '本周',
                'example_sentence' => '本周很忙。',
                'example_translation' => 'Very busy this week.',
                'definition' => 'This week',
                'sentences' => ['___的计划。', '___末。', '___内。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '下周',
                'pinyin' => 'xià zhōu',
                'simplified' => '下周',
                'traditional' => '下週',
                'part_of_speech' => 'noun',
                'meaning' => 'Next week',
                'meaning_zh' => '下周',
                'example_sentence' => '下周见面。',
                'example_translation' => 'Meet next week.',
                'definition' => 'Next week',
                'sentences' => ['___一。', '___的活动。', '___再说。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '上个月',
                'pinyin' => 'shàng ge yuè',
                'simplified' => '上个月',
                'traditional' => '上個月',
                'part_of_speech' => 'noun',
                'meaning' => 'Last month',
                'meaning_zh' => '上个月',
                'example_sentence' => '上个月去的。',
                'example_translation' => 'Went last month.',
                'definition' => 'Last month',
                'sentences' => ['___的工资。', '___底。', '___来的。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '这个月',
                'pinyin' => 'zhè ge yuè',
                'simplified' => '这个月',
                'traditional' => '這個月',
                'part_of_speech' => 'noun',
                'meaning' => 'This month',
                'meaning_zh' => '这个月',
                'example_sentence' => '这个月很忙。',
                'example_translation' => 'Very busy this month.',
                'definition' => 'This month',
                'sentences' => ['___的目标。', '___底。', '___要完成。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '下个月',
                'pinyin' => 'xià ge yuè',
                'simplified' => '下个月',
                'traditional' => '下個月',
                'part_of_speech' => 'noun',
                'meaning' => 'Next month',
                'meaning_zh' => '下个月',
                'example_sentence' => '下个月见。',
                'example_translation' => 'See you next month.',
                'definition' => 'Next month',
                'sentences' => ['___初。', '___的计划。', '___开始。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '去年',
                'pinyin' => 'qù nián',
                'simplified' => '去年',
                'traditional' => '去年',
                'part_of_speech' => 'noun',
                'meaning' => 'Last year',
                'meaning_zh' => '去年',
                'example_sentence' => '去年夏天。',
                'example_translation' => 'Last summer.',
                'definition' => 'Last year',
                'sentences' => ['___的事。', '___冬天。', '___买的。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '今年',
                'pinyin' => 'jīn nián',
                'simplified' => '今年',
                'traditional' => '今年',
                'part_of_speech' => 'noun',
                'meaning' => 'This year',
                'meaning_zh' => '今年',
                'example_sentence' => '今年多大？',
                'example_translation' => 'How old this year?',
                'definition' => 'This year',
                'sentences' => ['___的目标。', '___春天。', '___开始。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '明年',
                'pinyin' => 'míng nián',
                'simplified' => '明年',
                'traditional' => '明年',
                'part_of_speech' => 'noun',
                'meaning' => 'Next year',
                'meaning_zh' => '明年',
                'example_sentence' => '明年见。',
                'example_translation' => 'See you next year.',
                'definition' => 'Next year',
                'sentences' => ['___的计划。', '___春节。', '___再说。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '平时',
                'pinyin' => 'píng shí',
                'simplified' => '平时',
                'traditional' => '平時',
                'part_of_speech' => 'noun',
                'meaning' => 'Usually / Ordinarily',
                'meaning_zh' => '平时',
                'example_sentence' => '平时很忙。',
                'example_translation' => 'Usually very busy.',
                'definition' => 'Usually, ordinarily, in normal times',
                'sentences' => ['___的习惯。', '___做什么？', '___不这样。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 87,
                'word' => '当时',
                'pinyin' => 'dāng shí',
                'simplified' => '当时',
                'traditional' => '當時',
                'part_of_speech' => 'noun',
                'meaning' => 'At that time / Then',
                'meaning_zh' => '当时',
                'example_sentence' => '当时不知道。',
                'example_translation' => 'Didn\'t know at that time.',
                'definition' => 'At that time, then',
                'sentences' => ['___的情况。', '___在哪？', '___就知道。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 88: Direction and Position (方向和位置) - 20 words
        $directionPositionVocab = [
            [
                'topic_id' => 88,
                'word' => '上面',
                'pinyin' => 'shàng mian',
                'simplified' => '上面',
                'traditional' => '上面',
                'part_of_speech' => 'noun',
                'meaning' => 'Above / On top / Upper side',
                'meaning_zh' => '上面',
                'example_sentence' => '桌子上面。',
                'example_translation' => 'On top of the table.',
                'definition' => 'Above, on top, upper side',
                'sentences' => ['在___。', '___有。', '___写着。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '下面',
                'pinyin' => 'xià mian',
                'simplified' => '下面',
                'traditional' => '下面',
                'part_of_speech' => 'noun',
                'meaning' => 'Below / Under / Lower side',
                'meaning_zh' => '下面',
                'example_sentence' => '桌子下面。',
                'example_translation' => 'Under the table.',
                'definition' => 'Below, under, lower side',
                'sentences' => ['在___。', '___有。', '往___看。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '前面',
                'pinyin' => 'qián mian',
                'simplified' => '前面',
                'traditional' => '前面',
                'part_of_speech' => 'noun',
                'meaning' => 'Front / In front / Ahead',
                'meaning_zh' => '前面',
                'example_sentence' => '房子前面。',
                'example_translation' => 'In front of the house.',
                'definition' => 'Front, in front, ahead',
                'sentences' => ['在___。', '___有。', '往___走。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '后面',
                'pinyin' => 'hòu mian',
                'simplified' => '后面',
                'traditional' => '後面',
                'part_of_speech' => 'noun',
                'meaning' => 'Behind / Back / Rear',
                'meaning_zh' => '后面',
                'example_sentence' => '房子后面。',
                'example_translation' => 'Behind the house.',
                'definition' => 'Behind, back, rear',
                'sentences' => ['在___。', '___有。', '往___看。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '左边',
                'pinyin' => 'zuǒ bian',
                'simplified' => '左边',
                'traditional' => '左邊',
                'part_of_speech' => 'noun',
                'meaning' => 'Left side',
                'meaning_zh' => '左边',
                'example_sentence' => '在左边。',
                'example_translation' => 'On the left side.',
                'definition' => 'Left side',
                'sentences' => ['在___。', '___第一个。', '往___转。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '右边',
                'pinyin' => 'yòu bian',
                'simplified' => '右边',
                'traditional' => '右邊',
                'part_of_speech' => 'noun',
                'meaning' => 'Right side',
                'meaning_zh' => '右边',
                'example_sentence' => '在右边。',
                'example_translation' => 'On the right side.',
                'definition' => 'Right side',
                'sentences' => ['在___。', '___第二个。', '往___转。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '旁边',
                'pinyin' => 'páng biān',
                'simplified' => '旁边',
                'traditional' => '旁邊',
                'part_of_speech' => 'noun',
                'meaning' => 'Side / Beside',
                'meaning_zh' => '旁边',
                'example_sentence' => '在旁边。',
                'example_translation' => 'At the side.',
                'definition' => 'Side, beside, next to',
                'sentences' => ['在___。', '___的人。', '___坐。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '中间',
                'pinyin' => 'zhōng jiān',
                'simplified' => '中间',
                'traditional' => '中間',
                'part_of_speech' => 'noun',
                'meaning' => 'Middle / Between / Center',
                'meaning_zh' => '中间',
                'example_sentence' => '在中间。',
                'example_translation' => 'In the middle.',
                'definition' => 'Middle, between, center',
                'sentences' => ['在___。', '___的位置。', '___隔着。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '里面',
                'pinyin' => 'lǐ mian',
                'simplified' => '里面',
                'traditional' => '裡面',
                'part_of_speech' => 'noun',
                'meaning' => 'Inside / Interior',
                'meaning_zh' => '里面',
                'example_sentence' => '房间里面。',
                'example_translation' => 'Inside the room.',
                'definition' => 'Inside, interior, within',
                'sentences' => ['在___。', '___有。', '进___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '外面',
                'pinyin' => 'wài mian',
                'simplified' => '外面',
                'traditional' => '外面',
                'part_of_speech' => 'noun',
                'meaning' => 'Outside / Exterior',
                'meaning_zh' => '外面',
                'example_sentence' => '房间外面。',
                'example_translation' => 'Outside the room.',
                'definition' => 'Outside, exterior',
                'sentences' => ['在___。', '___下雨。', '到___去。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '对面',
                'pinyin' => 'duì miàn',
                'simplified' => '对面',
                'traditional' => '對面',
                'part_of_speech' => 'noun',
                'meaning' => 'Opposite side / Across from',
                'meaning_zh' => '对面',
                'example_sentence' => '街道对面。',
                'example_translation' => 'Across the street.',
                'definition' => 'Opposite side, across from',
                'sentences' => ['在___。', '___的楼。', '___见。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '附近',
                'pinyin' => 'fù jìn',
                'simplified' => '附近',
                'traditional' => '附近',
                'part_of_speech' => 'noun',
                'meaning' => 'Nearby / Vicinity',
                'meaning_zh' => '附近',
                'example_sentence' => '学校附近。',
                'example_translation' => 'Near the school.',
                'definition' => 'Nearby, vicinity, surrounding area',
                'sentences' => ['在___。', '___的店。', '___有。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '周围',
                'pinyin' => 'zhōu wéi',
                'simplified' => '周围',
                'traditional' => '周圍',
                'part_of_speech' => 'noun',
                'meaning' => 'Surroundings / Around',
                'meaning_zh' => '周围',
                'example_sentence' => '看看周围。',
                'example_translation' => 'Look around.',
                'definition' => 'Surroundings, around, circumference',
                'sentences' => ['___的人。', '___环境。', '___都是。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '东',
                'pinyin' => 'dōng',
                'simplified' => '东',
                'traditional' => '東',
                'part_of_speech' => 'noun',
                'meaning' => 'East',
                'meaning_zh' => '东',
                'example_sentence' => '往东走。',
                'example_translation' => 'Go east.',
                'definition' => 'East',
                'sentences' => ['___方。', '___边。', '___南西北。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '南',
                'pinyin' => 'nán',
                'simplified' => '南',
                'traditional' => '南',
                'part_of_speech' => 'noun',
                'meaning' => 'South',
                'meaning_zh' => '南',
                'example_sentence' => '往南走。',
                'example_translation' => 'Go south.',
                'definition' => 'South',
                'sentences' => ['___方。', '___边。', '___北。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '西',
                'pinyin' => 'xī',
                'simplified' => '西',
                'traditional' => '西',
                'part_of_speech' => 'noun',
                'meaning' => 'West',
                'meaning_zh' => '西',
                'example_sentence' => '往西走。',
                'example_translation' => 'Go west.',
                'definition' => 'West',
                'sentences' => ['___方。', '___边。', '东___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '北',
                'pinyin' => 'běi',
                'simplified' => '北',
                'traditional' => '北',
                'part_of_speech' => 'noun',
                'meaning' => 'North',
                'meaning_zh' => '北',
                'example_sentence' => '往北走。',
                'example_translation' => 'Go north.',
                'definition' => 'North',
                'sentences' => ['___方。', '___边。', '___京。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '角落',
                'pinyin' => 'jiǎo luò',
                'simplified' => '角落',
                'traditional' => '角落',
                'part_of_speech' => 'noun',
                'meaning' => 'Corner',
                'meaning_zh' => '角落',
                'example_sentence' => '在角落里。',
                'example_translation' => 'In the corner.',
                'definition' => 'Corner',
                'sentences' => ['___里。', '房间的___。', '___处。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '边',
                'pinyin' => 'biān',
                'simplified' => '边',
                'traditional' => '邊',
                'part_of_speech' => 'noun',
                'meaning' => 'Side / Edge / Border',
                'meaning_zh' => '边',
                'example_sentence' => '这边来。',
                'example_translation' => 'Come this way.',
                'definition' => 'Side, edge, border',
                'sentences' => ['这___。', '那___。', '旁___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 88,
                'word' => '处',
                'pinyin' => 'chù',
                'simplified' => '处',
                'traditional' => '處',
                'part_of_speech' => 'noun',
                'meaning' => 'Place / Location',
                'meaning_zh' => '处',
                'example_sentence' => '各处都有。',
                'example_translation' => 'Available everywhere.',
                'definition' => 'Place, location, spot',
                'sentences' => ['到___。', '好___。', '各___。'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($questionWordsVocab, $timeExpressionVocab, $directionPositionVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
