<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk3Topics4to7Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 66: Eating Out (外出就餐) - 20 words
        $eatingOutVocab = [
            [
                'topic_id' => 66,
                'word' => '餐厅',
                'pinyin' => 'cān tīng',
                'simplified' => '餐厅',
                'traditional' => '餐廳',
                'part_of_speech' => 'noun',
                'meaning' => 'Restaurant',
                'meaning_zh' => '餐厅',
                'example_sentence' => '我们去餐厅吃饭。',
                'example_translation' => 'We go to the restaurant to eat.',
                'definition' => 'Restaurant, dining room',
                'sentences' => ['去___。', '___很大。', '___预订。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '服务员',
                'pinyin' => 'fú wù yuán',
                'simplified' => '服务员',
                'traditional' => '服務員',
                'part_of_speech' => 'noun',
                'meaning' => 'Waiter / Waitress',
                'meaning_zh' => '服务员',
                'example_sentence' => '服务员，买单！',
                'example_translation' => 'Waiter, the bill please!',
                'definition' => 'Waiter, waitress, attendant',
                'sentences' => ['___来了。', '叫___。', '___服务。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '点菜',
                'pinyin' => 'diǎn cài',
                'simplified' => '点菜',
                'traditional' => '點菜',
                'part_of_speech' => 'verb',
                'meaning' => 'To order dishes',
                'meaning_zh' => '点菜',
                'example_sentence' => '我来点菜。',
                'example_translation' => 'I will order the dishes.',
                'definition' => 'To order dishes, to order food',
                'sentences' => ['___了。', '___单。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '推荐',
                'pinyin' => 'tuī jiàn',
                'simplified' => '推荐',
                'traditional' => '推薦',
                'part_of_speech' => 'verb',
                'meaning' => 'To recommend',
                'meaning_zh' => '推荐',
                'example_sentence' => '你推荐什么菜？',
                'example_translation' => 'What dish do you recommend?',
                'definition' => 'To recommend, recommendation',
                'sentences' => ['___菜。', '___餐厅。', '___给你。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '特色',
                'pinyin' => 'tè sè',
                'simplified' => '特色',
                'traditional' => '特色',
                'part_of_speech' => 'noun',
                'meaning' => 'Special feature / Characteristic',
                'meaning_zh' => '特色',
                'example_sentence' => '这是特色菜。',
                'example_translation' => 'This is a specialty dish.',
                'definition' => 'Special feature, characteristic, specialty',
                'sentences' => ['___菜。', '___餐厅。', '___小吃。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '招牌菜',
                'pinyin' => 'zhāo pái cài',
                'simplified' => '招牌菜',
                'traditional' => '招牌菜',
                'part_of_speech' => 'noun',
                'meaning' => 'Signature dish',
                'meaning_zh' => '招牌菜',
                'example_sentence' => '这是我们的招牌菜。',
                'example_translation' => 'This is our signature dish.',
                'definition' => 'Signature dish, specialty',
                'sentences' => ['___很好吃。', '点___。', '___推荐。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '座位',
                'pinyin' => 'zuò wèi',
                'simplified' => '座位',
                'traditional' => '座位',
                'part_of_speech' => 'noun',
                'meaning' => 'Seat',
                'meaning_zh' => '座位',
                'example_sentence' => '请找座位。',
                'example_translation' => 'Please find a seat.',
                'definition' => 'Seat',
                'sentences' => ['___在哪？', '___满了。', '___预订。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '预订',
                'pinyin' => 'yù dìng',
                'simplified' => '预订',
                'traditional' => '預訂',
                'part_of_speech' => 'verb',
                'meaning' => 'To reserve / To book',
                'meaning_zh' => '预订',
                'example_sentence' => '我要预订座位。',
                'example_translation' => 'I want to reserve a seat.',
                'definition' => 'To reserve, to book',
                'sentences' => ['___座位。', '___了。', '___餐厅。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '上菜',
                'pinyin' => 'shàng cài',
                'simplified' => '上菜',
                'traditional' => '上菜',
                'part_of_speech' => 'verb',
                'meaning' => 'To serve dishes',
                'meaning_zh' => '上菜',
                'example_sentence' => '可以上菜了。',
                'example_translation' => 'You can serve the dishes now.',
                'definition' => 'To serve dishes',
                'sentences' => ['___了。', '___时间。', '___很慢。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '口味',
                'pinyin' => 'kǒu wèi',
                'simplified' => '口味',
                'traditional' => '口味',
                'part_of_speech' => 'noun',
                'meaning' => 'Taste / Flavor',
                'meaning_zh' => '口味',
                'example_sentence' => '口味怎么样？',
                'example_translation' => 'How is the taste?',
                'definition' => 'Taste, flavor, preference',
                'sentences' => ['___很好。', '___不错。', '___重。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '辣',
                'pinyin' => 'là',
                'simplified' => '辣',
                'traditional' => '辣',
                'part_of_speech' => 'adjective',
                'meaning' => 'Spicy / Hot',
                'meaning_zh' => '辣',
                'example_sentence' => '这个菜很辣。',
                'example_translation' => 'This dish is very spicy.',
                'definition' => 'Spicy, hot',
                'sentences' => ['很___。', '___的菜。', '不___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '咸',
                'pinyin' => 'xián',
                'simplified' => '咸',
                'traditional' => '鹹',
                'part_of_speech' => 'adjective',
                'meaning' => 'Salty',
                'meaning_zh' => '咸',
                'example_sentence' => '太咸了。',
                'example_translation' => 'Too salty.',
                'definition' => 'Salty',
                'sentences' => ['太___了。', '___的菜。', '不___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '淡',
                'pinyin' => 'dàn',
                'simplified' => '淡',
                'traditional' => '淡',
                'part_of_speech' => 'adjective',
                'meaning' => 'Bland / Light',
                'meaning_zh' => '淡',
                'example_sentence' => '有点淡。',
                'example_translation' => 'A bit bland.',
                'definition' => 'Bland, light, weak',
                'sentences' => ['___了。', '___的口味。', '___一点。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '酸',
                'pinyin' => 'suān',
                'simplified' => '酸',
                'traditional' => '酸',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sour',
                'meaning_zh' => '酸',
                'example_sentence' => '有点酸。',
                'example_translation' => 'A bit sour.',
                'definition' => 'Sour',
                'sentences' => ['___的味道。', '很___。', '___甜。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '结账',
                'pinyin' => 'jié zhàng',
                'simplified' => '结账',
                'traditional' => '結賬',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay the bill / To settle accounts',
                'meaning_zh' => '结账',
                'example_sentence' => '我要结账。',
                'example_translation' => 'I want to pay the bill.',
                'definition' => 'To pay the bill, to settle accounts',
                'sentences' => ['___了。', '___台。', '___单。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '买单',
                'pinyin' => 'mǎi dān',
                'simplified' => '买单',
                'traditional' => '買單',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay the bill',
                'meaning_zh' => '买单',
                'example_sentence' => '服务员，买单！',
                'example_translation' => 'Waiter, the bill please!',
                'definition' => 'To pay the bill',
                'sentences' => ['___了。', '___！', '___方式。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '账单',
                'pinyin' => 'zhàng dān',
                'simplified' => '账单',
                'traditional' => '賬單',
                'part_of_speech' => 'noun',
                'meaning' => 'Bill / Check',
                'meaning_zh' => '账单',
                'example_sentence' => '请给我账单。',
                'example_translation' => 'Please give me the bill.',
                'definition' => 'Bill, check, invoice',
                'sentences' => ['___在这里。', '___金额。', '___明细。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '小费',
                'pinyin' => 'xiǎo fèi',
                'simplified' => '小费',
                'traditional' => '小費',
                'part_of_speech' => 'noun',
                'meaning' => 'Tip / Gratuity',
                'meaning_zh' => '小费',
                'example_sentence' => '要给小费吗？',
                'example_translation' => 'Do we need to give a tip?',
                'definition' => 'Tip, gratuity',
                'sentences' => ['给___。', '___多少？', '___文化。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '满意',
                'pinyin' => 'mǎn yì',
                'simplified' => '满意',
                'traditional' => '滿意',
                'part_of_speech' => 'adjective',
                'meaning' => 'Satisfied',
                'meaning_zh' => '满意',
                'example_sentence' => '我很满意。',
                'example_translation' => 'I am very satisfied.',
                'definition' => 'Satisfied, pleased',
                'sentences' => ['很___。', '___吗？', '___服务。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 66,
                'word' => '美味',
                'pinyin' => 'měi wèi',
                'simplified' => '美味',
                'traditional' => '美味',
                'part_of_speech' => 'adjective',
                'meaning' => 'Delicious',
                'meaning_zh' => '美味',
                'example_sentence' => '这个菜很美味。',
                'example_translation' => 'This dish is very delicious.',
                'definition' => 'Delicious, tasty',
                'sentences' => ['很___。', '___的菜。', '___食物。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 67: Health and Illness (健康和疾病) - 20 words
        $healthVocab = [
            [
                'topic_id' => 67,
                'word' => '健康',
                'pinyin' => 'jiàn kāng',
                'simplified' => '健康',
                'traditional' => '健康',
                'part_of_speech' => 'noun',
                'meaning' => 'Health / Healthy',
                'meaning_zh' => '健康',
                'example_sentence' => '身体健康。',
                'example_translation' => 'Healthy body.',
                'definition' => 'Health, healthy',
                'sentences' => ['___很重要。', '___状况。', '保持___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '生病',
                'pinyin' => 'shēng bìng',
                'simplified' => '生病',
                'traditional' => '生病',
                'part_of_speech' => 'verb',
                'meaning' => 'To get sick / To be ill',
                'meaning_zh' => '生病',
                'example_sentence' => '我生病了。',
                'example_translation' => 'I am sick.',
                'definition' => 'To get sick, to be ill',
                'sentences' => ['___了。', '___请假。', '___住院。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '感冒',
                'pinyin' => 'gǎn mào',
                'simplified' => '感冒',
                'traditional' => '感冒',
                'part_of_speech' => 'verb',
                'meaning' => 'To catch a cold / Cold',
                'meaning_zh' => '感冒',
                'example_sentence' => '我感冒了。',
                'example_translation' => 'I caught a cold.',
                'definition' => 'To catch a cold, cold',
                'sentences' => ['___了。', '___药。', '___症状。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '发烧',
                'pinyin' => 'fā shāo',
                'simplified' => '发烧',
                'traditional' => '發燒',
                'part_of_speech' => 'verb',
                'meaning' => 'To have a fever',
                'meaning_zh' => '发烧',
                'example_sentence' => '我发烧了。',
                'example_translation' => 'I have a fever.',
                'definition' => 'To have a fever',
                'sentences' => ['___了。', '___度数。', '___退热。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '咳嗽',
                'pinyin' => 'ké sou',
                'simplified' => '咳嗽',
                'traditional' => '咳嗽',
                'part_of_speech' => 'verb',
                'meaning' => 'To cough',
                'meaning_zh' => '咳嗽',
                'example_sentence' => '我一直咳嗽。',
                'example_translation' => 'I keep coughing.',
                'definition' => 'To cough',
                'sentences' => ['___了。', '___药。', '___厉害。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '流鼻涕',
                'pinyin' => 'liú bí tì',
                'simplified' => '流鼻涕',
                'traditional' => '流鼻涕',
                'part_of_speech' => 'verb',
                'meaning' => 'To have a runny nose',
                'meaning_zh' => '流鼻涕',
                'example_sentence' => '我流鼻涕了。',
                'example_translation' => 'I have a runny nose.',
                'definition' => 'To have a runny nose',
                'sentences' => ['___了。', '___擦鼻子。', '___症状。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '疼',
                'pinyin' => 'téng',
                'simplified' => '疼',
                'traditional' => '疼',
                'part_of_speech' => 'verb',
                'meaning' => 'To hurt / To ache',
                'meaning_zh' => '疼',
                'example_sentence' => '头很疼。',
                'example_translation' => 'My head hurts.',
                'definition' => 'To hurt, to ache, painful',
                'sentences' => ['很___。', '___痛。', '___得厉害。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '疼痛',
                'pinyin' => 'téng tòng',
                'simplified' => '疼痛',
                'traditional' => '疼痛',
                'part_of_speech' => 'noun',
                'meaning' => 'Pain / Ache',
                'meaning_zh' => '疼痛',
                'example_sentence' => '感到疼痛。',
                'example_translation' => 'Feel pain.',
                'definition' => 'Pain, ache',
                'sentences' => ['___感。', '___部位。', '___缓解。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '看医生',
                'pinyin' => 'kàn yī shēng',
                'simplified' => '看医生',
                'traditional' => '看醫生',
                'part_of_speech' => 'verb',
                'meaning' => 'To see a doctor',
                'meaning_zh' => '看医生',
                'example_sentence' => '我要去看医生。',
                'example_translation' => 'I need to see a doctor.',
                'definition' => 'To see a doctor',
                'sentences' => ['___了。', '___预约。', '___检查。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '检查',
                'pinyin' => 'jiǎn chá',
                'simplified' => '检查',
                'traditional' => '檢查',
                'part_of_speech' => 'verb',
                'meaning' => 'To examine / To check',
                'meaning_zh' => '检查',
                'example_sentence' => '医生检查身体。',
                'example_translation' => 'The doctor examines the body.',
                'definition' => 'To examine, to check, to inspect',
                'sentences' => ['___身体。', '___结果。', '___报告。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '治疗',
                'pinyin' => 'zhì liáo',
                'simplified' => '治疗',
                'traditional' => '治療',
                'part_of_speech' => 'verb',
                'meaning' => 'To treat / Treatment',
                'meaning_zh' => '治疗',
                'example_sentence' => '接受治疗。',
                'example_translation' => 'Receive treatment.',
                'definition' => 'To treat, treatment',
                'sentences' => ['___疾病。', '___方法。', '___效果。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '吃药',
                'pinyin' => 'chī yào',
                'simplified' => '吃药',
                'traditional' => '吃藥',
                'part_of_speech' => 'verb',
                'meaning' => 'To take medicine',
                'meaning_zh' => '吃药',
                'example_sentence' => '按时吃药。',
                'example_translation' => 'Take medicine on time.',
                'definition' => 'To take medicine',
                'sentences' => ['___了。', '___时间。', '___剂量。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '打针',
                'pinyin' => 'dǎ zhēn',
                'simplified' => '打针',
                'traditional' => '打針',
                'part_of_speech' => 'verb',
                'meaning' => 'To give/get an injection',
                'meaning_zh' => '打针',
                'example_sentence' => '我要打针。',
                'example_translation' => 'I need to get an injection.',
                'definition' => 'To give/get an injection',
                'sentences' => ['___了。', '___疼吗？', '___治疗。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '输液',
                'pinyin' => 'shū yè',
                'simplified' => '输液',
                'traditional' => '輸液',
                'part_of_speech' => 'verb',
                'meaning' => 'To get an IV drip',
                'meaning_zh' => '输液',
                'example_sentence' => '在医院输液。',
                'example_translation' => 'Getting an IV drip at the hospital.',
                'definition' => 'To get an IV drip, intravenous injection',
                'sentences' => ['___治疗。', '___了。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '恢复',
                'pinyin' => 'huī fù',
                'simplified' => '恢复',
                'traditional' => '恢復',
                'part_of_speech' => 'verb',
                'meaning' => 'To recover / To restore',
                'meaning_zh' => '恢复',
                'example_sentence' => '身体恢复了。',
                'example_translation' => 'The body has recovered.',
                'definition' => 'To recover, to restore',
                'sentences' => ['___健康。', '___了。', '___快。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '康复',
                'pinyin' => 'kāng fù',
                'simplified' => '康复',
                'traditional' => '康復',
                'part_of_speech' => 'verb',
                'meaning' => 'To recuperate / To recover',
                'meaning_zh' => '康复',
                'example_sentence' => '祝你早日康复。',
                'example_translation' => 'Wish you a speedy recovery.',
                'definition' => 'To recuperate, to recover',
                'sentences' => ['___了。', '___训练。', '早日___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '住院',
                'pinyin' => 'zhù yuàn',
                'simplified' => '住院',
                'traditional' => '住院',
                'part_of_speech' => 'verb',
                'meaning' => 'To be hospitalized',
                'meaning_zh' => '住院',
                'example_sentence' => '他住院了。',
                'example_translation' => 'He is hospitalized.',
                'definition' => 'To be hospitalized, to be in hospital',
                'sentences' => ['___了。', '___治疗。', '___时间。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '出院',
                'pinyin' => 'chū yuàn',
                'simplified' => '出院',
                'traditional' => '出院',
                'part_of_speech' => 'verb',
                'meaning' => 'To be discharged from hospital',
                'meaning_zh' => '出院',
                'example_sentence' => '明天可以出院。',
                'example_translation' => 'Can be discharged tomorrow.',
                'definition' => 'To be discharged from hospital',
                'sentences' => ['___了。', '___时间。', '___手续。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '症状',
                'pinyin' => 'zhèng zhuàng',
                'simplified' => '症状',
                'traditional' => '症狀',
                'part_of_speech' => 'noun',
                'meaning' => 'Symptom',
                'meaning_zh' => '症状',
                'example_sentence' => '有什么症状？',
                'example_translation' => 'What symptoms do you have?',
                'definition' => 'Symptom',
                'sentences' => ['___明显。', '___减轻。', '___描述。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 67,
                'word' => '预防',
                'pinyin' => 'yù fáng',
                'simplified' => '预防',
                'traditional' => '預防',
                'part_of_speech' => 'verb',
                'meaning' => 'To prevent',
                'meaning_zh' => '预防',
                'example_sentence' => '预防疾病。',
                'example_translation' => 'Prevent disease.',
                'definition' => 'To prevent, prevention',
                'sentences' => ['___感冒。', '___措施。', '___接种。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 68: Feelings and Emotions (感受和情绪) - 20 words
        $emotionsVocab = [
            [
                'topic_id' => 68,
                'word' => '感受',
                'pinyin' => 'gǎn shòu',
                'simplified' => '感受',
                'traditional' => '感受',
                'part_of_speech' => 'noun',
                'meaning' => 'Feeling / To feel',
                'meaning_zh' => '感受',
                'example_sentence' => '我的感受很复杂。',
                'example_translation' => 'My feelings are complicated.',
                'definition' => 'Feeling, to feel',
                'sentences' => ['___很深。', '___到。', '___如何？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '情绪',
                'pinyin' => 'qíng xù',
                'simplified' => '情绪',
                'traditional' => '情緒',
                'part_of_speech' => 'noun',
                'meaning' => 'Emotion / Mood',
                'meaning_zh' => '情绪',
                'example_sentence' => '情绪不好。',
                'example_translation' => 'In a bad mood.',
                'definition' => 'Emotion, mood',
                'sentences' => ['___波动。', '___稳定。', '___管理。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '开心',
                'pinyin' => 'kāi xīn',
                'simplified' => '开心',
                'traditional' => '開心',
                'part_of_speech' => 'adjective',
                'meaning' => 'Happy / Joyful',
                'meaning_zh' => '开心',
                'example_sentence' => '我很开心。',
                'example_translation' => 'I am very happy.',
                'definition' => 'Happy, joyful',
                'sentences' => ['很___。', '___的事。', '___极了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '难过',
                'pinyin' => 'nán guò',
                'simplified' => '难过',
                'traditional' => '難過',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sad / Sorry',
                'meaning_zh' => '难过',
                'example_sentence' => '我很难过。',
                'example_translation' => 'I am very sad.',
                'definition' => 'Sad, sorry, grieved',
                'sentences' => ['很___。', '___的事。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '伤心',
                'pinyin' => 'shāng xīn',
                'simplified' => '伤心',
                'traditional' => '傷心',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sad / Grieved',
                'meaning_zh' => '伤心',
                'example_sentence' => '他很伤心。',
                'example_translation' => 'He is very sad.',
                'definition' => 'Sad, grieved, heartbroken',
                'sentences' => ['很___。', '___的事。', '___哭了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '失望',
                'pinyin' => 'shī wàng',
                'simplified' => '失望',
                'traditional' => '失望',
                'part_of_speech' => 'adjective',
                'meaning' => 'Disappointed',
                'meaning_zh' => '失望',
                'example_sentence' => '我很失望。',
                'example_translation' => 'I am very disappointed.',
                'definition' => 'Disappointed, to lose hope',
                'sentences' => ['很___。', '___了。', '___的结果。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '担心',
                'pinyin' => 'dān xīn',
                'simplified' => '担心',
                'traditional' => '擔心',
                'part_of_speech' => 'verb',
                'meaning' => 'To worry',
                'meaning_zh' => '担心',
                'example_sentence' => '我担心你。',
                'example_translation' => 'I worry about you.',
                'definition' => 'To worry, worried',
                'sentences' => ['___你。', '不用___。', '___的事。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '放心',
                'pinyin' => 'fàng xīn',
                'simplified' => '放心',
                'traditional' => '放心',
                'part_of_speech' => 'adjective',
                'meaning' => 'To rest assured / At ease',
                'meaning_zh' => '放心',
                'example_sentence' => '你放心吧。',
                'example_translation' => 'Don\'t worry.',
                'definition' => 'To rest assured, at ease',
                'sentences' => ['___吧。', '___了。', '___不下。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '紧张',
                'pinyin' => 'jǐn zhāng',
                'simplified' => '紧张',
                'traditional' => '緊張',
                'part_of_speech' => 'adjective',
                'meaning' => 'Nervous / Tense',
                'meaning_zh' => '紧张',
                'example_sentence' => '我很紧张。',
                'example_translation' => 'I am very nervous.',
                'definition' => 'Nervous, tense, tight',
                'sentences' => ['很___。', '___的气氛。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '轻松',
                'pinyin' => 'qīng sōng',
                'simplified' => '轻松',
                'traditional' => '輕鬆',
                'part_of_speech' => 'adjective',
                'meaning' => 'Relaxed / Easy',
                'meaning_zh' => '轻松',
                'example_sentence' => '我感到很轻松。',
                'example_translation' => 'I feel very relaxed.',
                'definition' => 'Relaxed, easy, light',
                'sentences' => ['很___。', '___的工作。', '___愉快。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '激动',
                'pinyin' => 'jī dòng',
                'simplified' => '激动',
                'traditional' => '激動',
                'part_of_speech' => 'adjective',
                'meaning' => 'Excited / Stirred',
                'meaning_zh' => '激动',
                'example_sentence' => '我很激动。',
                'example_translation' => 'I am very excited.',
                'definition' => 'Excited, stirred, agitated',
                'sentences' => ['很___。', '___的心情。', '___不已。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '兴奋',
                'pinyin' => 'xīng fèn',
                'simplified' => '兴奋',
                'traditional' => '興奮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Excited / Thrilled',
                'meaning_zh' => '兴奋',
                'example_sentence' => '他很兴奋。',
                'example_translation' => 'He is very excited.',
                'definition' => 'Excited, thrilled',
                'sentences' => ['很___。', '___的消息。', '___不已。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '生气',
                'pinyin' => 'shēng qì',
                'simplified' => '生气',
                'traditional' => '生氣',
                'part_of_speech' => 'verb',
                'meaning' => 'To be angry',
                'meaning_zh' => '生气',
                'example_sentence' => '他生气了。',
                'example_translation' => 'He is angry.',
                'definition' => 'To be angry',
                'sentences' => ['___了。', '___的原因。', '不要___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '愤怒',
                'pinyin' => 'fèn nù',
                'simplified' => '愤怒',
                'traditional' => '憤怒',
                'part_of_speech' => 'adjective',
                'meaning' => 'Angry / Furious',
                'meaning_zh' => '愤怒',
                'example_sentence' => '他很愤怒。',
                'example_translation' => 'He is very angry.',
                'definition' => 'Angry, furious, indignant',
                'sentences' => ['很___。', '___的情绪。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '害怕',
                'pinyin' => 'hài pà',
                'simplified' => '害怕',
                'traditional' => '害怕',
                'part_of_speech' => 'verb',
                'meaning' => 'To be afraid / To fear',
                'meaning_zh' => '害怕',
                'example_sentence' => '我害怕。',
                'example_translation' => 'I am afraid.',
                'definition' => 'To be afraid, to fear',
                'sentences' => ['___了。', '___的事。', '不___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '恐惧',
                'pinyin' => 'kǒng jù',
                'simplified' => '恐惧',
                'traditional' => '恐懼',
                'part_of_speech' => 'noun',
                'meaning' => 'Fear / Terror',
                'meaning_zh' => '恐惧',
                'example_sentence' => '感到恐惧。',
                'example_translation' => 'Feel fear.',
                'definition' => 'Fear, terror, dread',
                'sentences' => ['___感。', '___的心理。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '惊讶',
                'pinyin' => 'jīng yà',
                'simplified' => '惊讶',
                'traditional' => '驚訝',
                'part_of_speech' => 'adjective',
                'meaning' => 'Surprised / Amazed',
                'meaning_zh' => '惊讶',
                'example_sentence' => '我很惊讶。',
                'example_translation' => 'I am very surprised.',
                'definition' => 'Surprised, amazed, astonished',
                'sentences' => ['很___。', '___的消息。', '___了。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '感动',
                'pinyin' => 'gǎn dòng',
                'simplified' => '感动',
                'traditional' => '感動',
                'part_of_speech' => 'verb',
                'meaning' => 'To be moved / Touched',
                'meaning_zh' => '感动',
                'example_sentence' => '我很感动。',
                'example_translation' => 'I am very moved.',
                'definition' => 'To be moved, touched',
                'sentences' => ['___了。', '___的故事。', '___人心。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '后悔',
                'pinyin' => 'hòu huǐ',
                'simplified' => '后悔',
                'traditional' => '後悔',
                'part_of_speech' => 'verb',
                'meaning' => 'To regret',
                'meaning_zh' => '后悔',
                'example_sentence' => '我很后悔。',
                'example_translation' => 'I regret it very much.',
                'definition' => 'To regret',
                'sentences' => ['___了。', '___的事。', '___不已。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 68,
                'word' => '满足',
                'pinyin' => 'mǎn zú',
                'simplified' => '满足',
                'traditional' => '滿足',
                'part_of_speech' => 'adjective',
                'meaning' => 'Satisfied / Content',
                'meaning_zh' => '满足',
                'example_sentence' => '我很满足。',
                'example_translation' => 'I am very satisfied.',
                'definition' => 'Satisfied, content, to satisfy',
                'sentences' => ['很___。', '___需求。', '___了。'],
                'level' => 'HSK3',
            ],
        ];

        // Topic 69: Expressing Opinions (表达意见) - 20 words
        $opinionsVocab = [
            [
                'topic_id' => 69,
                'word' => '意见',
                'pinyin' => 'yì jiàn',
                'simplified' => '意见',
                'traditional' => '意見',
                'part_of_speech' => 'noun',
                'meaning' => 'Opinion / Suggestion',
                'meaning_zh' => '意见',
                'example_sentence' => '你有什么意见？',
                'example_translation' => 'What\'s your opinion?',
                'definition' => 'Opinion, suggestion, view',
                'sentences' => ['___不同。', '___一致。', '提___。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '看法',
                'pinyin' => 'kàn fǎ',
                'simplified' => '看法',
                'traditional' => '看法',
                'part_of_speech' => 'noun',
                'meaning' => 'View / Opinion',
                'meaning_zh' => '看法',
                'example_sentence' => '我的看法不同。',
                'example_translation' => 'My view is different.',
                'definition' => 'View, opinion',
                'sentences' => ['___不同。', '___一致。', '___如何？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '观点',
                'pinyin' => 'guān diǎn',
                'simplified' => '观点',
                'traditional' => '觀點',
                'part_of_speech' => 'noun',
                'meaning' => 'Viewpoint / Point of view',
                'meaning_zh' => '观点',
                'example_sentence' => '你的观点很好。',
                'example_translation' => 'Your viewpoint is very good.',
                'definition' => 'Viewpoint, point of view',
                'sentences' => ['___不同。', '___明确。', '___独特。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '觉得',
                'pinyin' => 'jué de',
                'simplified' => '觉得',
                'traditional' => '覺得',
                'part_of_speech' => 'verb',
                'meaning' => 'To feel / To think',
                'meaning_zh' => '觉得',
                'example_sentence' => '我觉得很好。',
                'example_translation' => 'I think it\'s very good.',
                'definition' => 'To feel, to think',
                'sentences' => ['___怎么样？', '___不错。', '___对。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '认为',
                'pinyin' => 'rèn wéi',
                'simplified' => '认为',
                'traditional' => '認為',
                'part_of_speech' => 'verb',
                'meaning' => 'To think / To believe',
                'meaning_zh' => '认为',
                'example_sentence' => '我认为是对的。',
                'example_translation' => 'I think it\'s right.',
                'definition' => 'To think, to believe, to consider',
                'sentences' => ['___正确。', '___不对。', '___如何？'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '同意',
                'pinyin' => 'tóng yì',
                'simplified' => '同意',
                'traditional' => '同意',
                'part_of_speech' => 'verb',
                'meaning' => 'To agree',
                'meaning_zh' => '同意',
                'example_sentence' => '我同意你的看法。',
                'example_translation' => 'I agree with your view.',
                'definition' => 'To agree, to consent',
                'sentences' => ['___了。', '___吗？', '___意见。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '不同意',
                'pinyin' => 'bù tóng yì',
                'simplified' => '不同意',
                'traditional' => '不同意',
                'part_of_speech' => 'verb',
                'meaning' => 'To disagree',
                'meaning_zh' => '不同意',
                'example_sentence' => '我不同意。',
                'example_translation' => 'I disagree.',
                'definition' => 'To disagree',
                'sentences' => ['___。', '___这个。', '___看法。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '反对',
                'pinyin' => 'fǎn duì',
                'simplified' => '反对',
                'traditional' => '反對',
                'part_of_speech' => 'verb',
                'meaning' => 'To oppose / To object',
                'meaning_zh' => '反对',
                'example_sentence' => '我反对这个决定。',
                'example_translation' => 'I oppose this decision.',
                'definition' => 'To oppose, to object to',
                'sentences' => ['___意见。', '___了。', '___态度。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '赞成',
                'pinyin' => 'zàn chéng',
                'simplified' => '赞成',
                'traditional' => '贊成',
                'part_of_speech' => 'verb',
                'meaning' => 'To approve / To agree with',
                'meaning_zh' => '赞成',
                'example_sentence' => '我赞成你的意见。',
                'example_translation' => 'I agree with your opinion.',
                'definition' => 'To approve, to agree with',
                'sentences' => ['___了。', '___吗？', '___意见。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '支持',
                'pinyin' => 'zhī chí',
                'simplified' => '支持',
                'traditional' => '支持',
                'part_of_speech' => 'verb',
                'meaning' => 'To support',
                'meaning_zh' => '支持',
                'example_sentence' => '我支持你。',
                'example_translation' => 'I support you.',
                'definition' => 'To support',
                'sentences' => ['___你。', '___决定。', '___意见。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb',
                'meaning' => 'To understand',
                'meaning_zh' => '理解',
                'example_sentence' => '我理解你。',
                'example_translation' => 'I understand you.',
                'definition' => 'To understand, understanding',
                'sentences' => ['___了。', '___意思。', '___错误。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '误解',
                'pinyin' => 'wù jiě',
                'simplified' => '误解',
                'traditional' => '誤解',
                'part_of_speech' => 'verb',
                'meaning' => 'To misunderstand',
                'meaning_zh' => '误解',
                'example_sentence' => '你误解了。',
                'example_translation' => 'You misunderstood.',
                'definition' => 'To misunderstand, misunderstanding',
                'sentences' => ['___了。', '___意思。', '___我。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '解释',
                'pinyin' => 'jiě shì',
                'simplified' => '解释',
                'traditional' => '解釋',
                'part_of_speech' => 'verb',
                'meaning' => 'To explain',
                'meaning_zh' => '解释',
                'example_sentence' => '请解释一下。',
                'example_translation' => 'Please explain.',
                'definition' => 'To explain, explanation',
                'sentences' => ['___清楚。', '___了。', '___原因。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '说明',
                'pinyin' => 'shuō míng',
                'simplified' => '说明',
                'traditional' => '說明',
                'part_of_speech' => 'verb',
                'meaning' => 'To explain / To illustrate',
                'meaning_zh' => '说明',
                'example_sentence' => '请说明情况。',
                'example_translation' => 'Please explain the situation.',
                'definition' => 'To explain, to illustrate, explanation',
                'sentences' => ['___问题。', '___书。', '___情况。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '证明',
                'pinyin' => 'zhèng míng',
                'simplified' => '证明',
                'traditional' => '證明',
                'part_of_speech' => 'verb',
                'meaning' => 'To prove / To certify',
                'meaning_zh' => '证明',
                'example_sentence' => '请证明你的身份。',
                'example_translation' => 'Please prove your identity.',
                'definition' => 'To prove, to certify, proof',
                'sentences' => ['___了。', '___材料。', '___身份。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '表达',
                'pinyin' => 'biǎo dá',
                'simplified' => '表达',
                'traditional' => '表達',
                'part_of_speech' => 'verb',
                'meaning' => 'To express',
                'meaning_zh' => '表达',
                'example_sentence' => '表达意见。',
                'example_translation' => 'Express opinion.',
                'definition' => 'To express, expression',
                'sentences' => ['___意见。', '___感谢。', '___清楚。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '讨论',
                'pinyin' => 'tǎo lùn',
                'simplified' => '讨论',
                'traditional' => '討論',
                'part_of_speech' => 'verb',
                'meaning' => 'To discuss',
                'meaning_zh' => '讨论',
                'example_sentence' => '我们讨论一下。',
                'example_translation' => 'Let\'s discuss it.',
                'definition' => 'To discuss, discussion',
                'sentences' => ['___问题。', '___了。', '___结果。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '争论',
                'pinyin' => 'zhēng lùn',
                'simplified' => '争论',
                'traditional' => '爭論',
                'part_of_speech' => 'verb',
                'meaning' => 'To argue / To debate',
                'meaning_zh' => '争论',
                'example_sentence' => '他们在争论。',
                'example_translation' => 'They are arguing.',
                'definition' => 'To argue, to debate, argument',
                'sentences' => ['___了。', '___问题。', '___很激烈。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '建议',
                'pinyin' => 'jiàn yì',
                'simplified' => '建议',
                'traditional' => '建議',
                'part_of_speech' => 'verb',
                'meaning' => 'To suggest / Suggestion',
                'meaning_zh' => '建议',
                'example_sentence' => '我建议明天去。',
                'example_translation' => 'I suggest going tomorrow.',
                'definition' => 'To suggest, suggestion',
                'sentences' => ['___你。', '___很好。', '___采纳。'],
                'level' => 'HSK3',
            ],
            [
                'topic_id' => 69,
                'word' => '劝告',
                'pinyin' => 'quàn gào',
                'simplified' => '劝告',
                'traditional' => '勸告',
                'part_of_speech' => 'verb',
                'meaning' => 'To advise / Advice',
                'meaning_zh' => '劝告',
                'example_sentence' => '我劝告你。',
                'example_translation' => 'I advise you.',
                'definition' => 'To advise, advice',
                'sentences' => ['___你。', '___了。', '___不听。'],
                'level' => 'HSK3',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($eatingOutVocab, $healthVocab, $emotionsVocab, $opinionsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
