<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics25to28Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 117: Health and Medical Care (健康和医疗) - 20 words
        $healthVocab = [
            [
                'topic_id' => 117,
                'word' => '健康',
                'pinyin' => 'jiàn kāng',
                'simplified' => '健康',
                'traditional' => '健康',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Health / Healthy',
                'meaning_zh' => '健康',
                'example_sentence' => '身体健康。',
                'example_translation' => 'Good health.',
                'definition' => 'Health, healthy',
                'sentences' => ['___状况。', '___生活。', '___检查。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '疾病',
                'pinyin' => 'jí bìng',
                'simplified' => '疾病',
                'traditional' => '疾病',
                'part_of_speech' => 'noun',
                'meaning' => 'Disease / Illness',
                'meaning_zh' => '疾病',
                'example_sentence' => '预防疾病。',
                'example_translation' => 'Prevent disease.',
                'definition' => 'Disease, illness',
                'sentences' => ['___控制。', '___传染。', '___治疗。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '症状',
                'pinyin' => 'zhèng zhuàng',
                'simplified' => '症状',
                'traditional' => '症狀',
                'part_of_speech' => 'noun',
                'meaning' => 'Symptom',
                'meaning_zh' => '症状',
                'example_sentence' => '有什么症状？',
                'example_translation' => 'What are the symptoms?',
                'definition' => 'Symptom',
                'sentences' => ['___明显。', '___消失。', '___表现。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '治疗',
                'pinyin' => 'zhì liáo',
                'simplified' => '治疗',
                'traditional' => '治療',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To treat / Treatment',
                'meaning_zh' => '治疗',
                'example_sentence' => '接受治疗。',
                'example_translation' => 'Receive treatment.',
                'definition' => 'To treat, treatment',
                'sentences' => ['___方法。', '___效果。', '___疾病。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '诊断',
                'pinyin' => 'zhěn duàn',
                'simplified' => '诊断',
                'traditional' => '診斷',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To diagnose / Diagnosis',
                'meaning_zh' => '诊断',
                'example_sentence' => '医生诊断。',
                'example_translation' => 'Doctor\'s diagnosis.',
                'definition' => 'To diagnose, diagnosis',
                'sentences' => ['___结果。', '___证明。', '___书。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '预防',
                'pinyin' => 'yù fáng',
                'simplified' => '预防',
                'traditional' => '預防',
                'part_of_speech' => 'verb',
                'meaning' => 'To prevent / To guard against',
                'meaning_zh' => '预防',
                'example_sentence' => '预防感冒。',
                'example_translation' => 'Prevent colds.',
                'definition' => 'To prevent, to guard against',
                'sentences' => ['___措施。', '___接种。', '___为主。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '康复',
                'pinyin' => 'kāng fù',
                'simplified' => '康复',
                'traditional' => '康復',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To recover / Recovery / Rehabilitation',
                'meaning_zh' => '康复',
                'example_sentence' => '早日康复。',
                'example_translation' => 'Get well soon.',
                'definition' => 'To recover, recovery, rehabilitation',
                'sentences' => ['___中心。', '___训练。', '___期。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '医院',
                'pinyin' => 'yī yuàn',
                'simplified' => '医院',
                'traditional' => '醫院',
                'part_of_speech' => 'noun',
                'meaning' => 'Hospital',
                'meaning_zh' => '医院',
                'example_sentence' => '去医院看病。',
                'example_translation' => 'Go to hospital.',
                'definition' => 'Hospital',
                'sentences' => ['___就诊。', '___住院。', '___检查。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '医生',
                'pinyin' => 'yī shēng',
                'simplified' => '医生',
                'traditional' => '醫生',
                'part_of_speech' => 'noun',
                'meaning' => 'Doctor / Physician',
                'meaning_zh' => '医生',
                'example_sentence' => '看医生。',
                'example_translation' => 'See a doctor.',
                'definition' => 'Doctor, physician',
                'sentences' => ['___建议。', '___说。', '___处方。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '护士',
                'pinyin' => 'hù shi',
                'simplified' => '护士',
                'traditional' => '護士',
                'part_of_speech' => 'noun',
                'meaning' => 'Nurse',
                'meaning_zh' => '护士',
                'example_sentence' => '护士照顾病人。',
                'example_translation' => 'Nurse takes care of patients.',
                'definition' => 'Nurse',
                'sentences' => ['___站。', '___长。', '___服。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '病人',
                'pinyin' => 'bìng rén',
                'simplified' => '病人',
                'traditional' => '病人',
                'part_of_speech' => 'noun',
                'meaning' => 'Patient / Sick person',
                'meaning_zh' => '病人',
                'example_sentence' => '照顾病人。',
                'example_translation' => 'Take care of patient.',
                'definition' => 'Patient, sick person',
                'sentences' => ['___家属。', '___住院。', '___康复。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '药',
                'pinyin' => 'yào',
                'simplified' => '药',
                'traditional' => '藥',
                'part_of_speech' => 'noun',
                'meaning' => 'Medicine / Drug',
                'meaning_zh' => '药',
                'example_sentence' => '吃药。',
                'example_translation' => 'Take medicine.',
                'definition' => 'Medicine, drug',
                'sentences' => ['___店。', '___方。', '___物。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '注射',
                'pinyin' => 'zhù shè',
                'simplified' => '注射',
                'traditional' => '注射',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To inject / Injection',
                'meaning_zh' => '注射',
                'example_sentence' => '打注射。',
                'example_translation' => 'Get an injection.',
                'definition' => 'To inject, injection',
                'sentences' => ['___器。', '___疫苗。', '___药物。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '手术',
                'pinyin' => 'shǒu shù',
                'simplified' => '手术',
                'traditional' => '手術',
                'part_of_speech' => 'noun',
                'meaning' => 'Surgery / Operation',
                'meaning_zh' => '手术',
                'example_sentence' => '做手术。',
                'example_translation' => 'Have surgery.',
                'definition' => 'Surgery, operation',
                'sentences' => ['___室。', '___成功。', '___台。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '检查',
                'pinyin' => 'jiǎn chá',
                'simplified' => '检查',
                'traditional' => '檢查',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To examine / To check / Examination',
                'meaning_zh' => '检查',
                'example_sentence' => '身体检查。',
                'example_translation' => 'Physical examination.',
                'definition' => 'To examine, to check, examination',
                'sentences' => ['___结果。', '___报告。', '___身体。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '体检',
                'pinyin' => 'tǐ jiǎn',
                'simplified' => '体检',
                'traditional' => '體檢',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Physical examination / Medical checkup',
                'meaning_zh' => '体检',
                'example_sentence' => '定期体检。',
                'example_translation' => 'Regular checkup.',
                'definition' => 'Physical examination, medical checkup',
                'sentences' => ['___中心。', '___报告。', '___表。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '血压',
                'pinyin' => 'xuè yā',
                'simplified' => '血压',
                'traditional' => '血壓',
                'part_of_speech' => 'noun',
                'meaning' => 'Blood pressure',
                'meaning_zh' => '血压',
                'example_sentence' => '测血压。',
                'example_translation' => 'Measure blood pressure.',
                'definition' => 'Blood pressure',
                'sentences' => ['___高。', '___计。', '___正常。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '体温',
                'pinyin' => 'tǐ wēn',
                'simplified' => '体温',
                'traditional' => '體溫',
                'part_of_speech' => 'noun',
                'meaning' => 'Body temperature',
                'meaning_zh' => '体温',
                'example_sentence' => '量体温。',
                'example_translation' => 'Take temperature.',
                'definition' => 'Body temperature',
                'sentences' => ['___升高。', '___计。', '___正常。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '疼痛',
                'pinyin' => 'téng tòng',
                'simplified' => '疼痛',
                'traditional' => '疼痛',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Pain / To ache',
                'meaning_zh' => '疼痛',
                'example_sentence' => '感到疼痛。',
                'example_translation' => 'Feel pain.',
                'definition' => 'Pain, to ache',
                'sentences' => ['___难忍。', '___减轻。', '___部位。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 117,
                'word' => '保健',
                'pinyin' => 'bǎo jiàn',
                'simplified' => '保健',
                'traditional' => '保健',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Health care / Health protection',
                'meaning_zh' => '保健',
                'example_sentence' => '注意保健。',
                'example_translation' => 'Pay attention to health.',
                'definition' => 'Health care, health protection',
                'sentences' => ['___品。', '___操。', '___医生。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 118: Economy and Finance (经济和金融) - 20 words
        $economyVocab = [
            [
                'topic_id' => 118,
                'word' => '经济',
                'pinyin' => 'jīng jì',
                'simplified' => '经济',
                'traditional' => '經濟',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Economy / Economic',
                'meaning_zh' => '经济',
                'example_sentence' => '经济发展。',
                'example_translation' => 'Economic development.',
                'definition' => 'Economy, economic',
                'sentences' => ['___增长。', '___学。', '___实惠。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '金融',
                'pinyin' => 'jīn róng',
                'simplified' => '金融',
                'traditional' => '金融',
                'part_of_speech' => 'noun',
                'meaning' => 'Finance / Financial',
                'meaning_zh' => '金融',
                'example_sentence' => '金融中心。',
                'example_translation' => 'Financial center.',
                'definition' => 'Finance, financial',
                'sentences' => ['___市场。', '___机构。', '___危机。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '银行',
                'pinyin' => 'yín háng',
                'simplified' => '银行',
                'traditional' => '銀行',
                'part_of_speech' => 'noun',
                'meaning' => 'Bank',
                'meaning_zh' => '银行',
                'example_sentence' => '去银行。',
                'example_translation' => 'Go to the bank.',
                'definition' => 'Bank',
                'sentences' => ['___卡。', '___存款。', '___账户。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '货币',
                'pinyin' => 'huò bì',
                'simplified' => '货币',
                'traditional' => '貨幣',
                'part_of_speech' => 'noun',
                'meaning' => 'Currency / Money',
                'meaning_zh' => '货币',
                'example_sentence' => '外国货币。',
                'example_translation' => 'Foreign currency.',
                'definition' => 'Currency, money',
                'sentences' => ['___政策。', '___兑换。', '___单位。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '投资',
                'pinyin' => 'tóu zī',
                'simplified' => '投资',
                'traditional' => '投資',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To invest / Investment',
                'meaning_zh' => '投资',
                'example_sentence' => '投资项目。',
                'example_translation' => 'Investment project.',
                'definition' => 'To invest, investment',
                'sentences' => ['___者。', '___回报。', '___风险。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '利润',
                'pinyin' => 'lì rùn',
                'simplified' => '利润',
                'traditional' => '利潤',
                'part_of_speech' => 'noun',
                'meaning' => 'Profit',
                'meaning_zh' => '利润',
                'example_sentence' => '获得利润。',
                'example_translation' => 'Gain profit.',
                'definition' => 'Profit',
                'sentences' => ['___率。', '___增长。', '净___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '成本',
                'pinyin' => 'chéng běn',
                'simplified' => '成本',
                'traditional' => '成本',
                'part_of_speech' => 'noun',
                'meaning' => 'Cost',
                'meaning_zh' => '成本',
                'example_sentence' => '降低成本。',
                'example_translation' => 'Reduce cost.',
                'definition' => 'Cost',
                'sentences' => ['___控制。', '___核算。', '生产___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '预算',
                'pinyin' => 'yù suàn',
                'simplified' => '预算',
                'traditional' => '預算',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Budget',
                'meaning_zh' => '预算',
                'example_sentence' => '做预算。',
                'example_translation' => 'Make a budget.',
                'definition' => 'Budget',
                'sentences' => ['___计划。', '___内。', '___超支。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '税',
                'pinyin' => 'shuì',
                'simplified' => '税',
                'traditional' => '稅',
                'part_of_speech' => 'noun',
                'meaning' => 'Tax',
                'meaning_zh' => '税',
                'example_sentence' => '交税。',
                'example_translation' => 'Pay tax.',
                'definition' => 'Tax',
                'sentences' => ['___收。', '___率。', '___务。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '收入',
                'pinyin' => 'shōu rù',
                'simplified' => '收入',
                'traditional' => '收入',
                'part_of_speech' => 'noun',
                'meaning' => 'Income / Revenue',
                'meaning_zh' => '收入',
                'example_sentence' => '增加收入。',
                'example_translation' => 'Increase income.',
                'definition' => 'Income, revenue',
                'sentences' => ['___水平。', '___来源。', '___证明。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '支出',
                'pinyin' => 'zhī chū',
                'simplified' => '支出',
                'traditional' => '支出',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Expenditure / To spend',
                'meaning_zh' => '支出',
                'example_sentence' => '减少支出。',
                'example_translation' => 'Reduce expenditure.',
                'definition' => 'Expenditure, to spend',
                'sentences' => ['___费用。', '___项目。', '___预算。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '存款',
                'pinyin' => 'cún kuǎn',
                'simplified' => '存款',
                'traditional' => '存款',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Deposit / Savings',
                'meaning_zh' => '存款',
                'example_sentence' => '银行存款。',
                'example_translation' => 'Bank deposit.',
                'definition' => 'Deposit, savings',
                'sentences' => ['___利率。', '___单。', '定期___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '贷款',
                'pinyin' => 'dài kuǎn',
                'simplified' => '贷款',
                'traditional' => '貸款',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Loan / To lend',
                'meaning_zh' => '贷款',
                'example_sentence' => '申请贷款。',
                'example_translation' => 'Apply for loan.',
                'definition' => 'Loan, to lend',
                'sentences' => ['___利率。', '___买房。', '___还款。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '债务',
                'pinyin' => 'zhài wù',
                'simplified' => '债务',
                'traditional' => '債務',
                'part_of_speech' => 'noun',
                'meaning' => 'Debt',
                'meaning_zh' => '债务',
                'example_sentence' => '偿还债务。',
                'example_translation' => 'Pay off debt.',
                'definition' => 'Debt',
                'sentences' => ['___危机。', '___人。', '___负担。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '股票',
                'pinyin' => 'gǔ piào',
                'simplified' => '股票',
                'traditional' => '股票',
                'part_of_speech' => 'noun',
                'meaning' => 'Stock / Share',
                'meaning_zh' => '股票',
                'example_sentence' => '买股票。',
                'example_translation' => 'Buy stocks.',
                'definition' => 'Stock, share',
                'sentences' => ['___市场。', '___交易。', '___价格。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '市场',
                'pinyin' => 'shì chǎng',
                'simplified' => '市场',
                'traditional' => '市場',
                'part_of_speech' => 'noun',
                'meaning' => 'Market',
                'meaning_zh' => '市场',
                'example_sentence' => '市场经济。',
                'example_translation' => 'Market economy.',
                'definition' => 'Market',
                'sentences' => ['___调查。', '___竞争。', '___份额。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '交易',
                'pinyin' => 'jiāo yì',
                'simplified' => '交易',
                'traditional' => '交易',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Transaction / Trade / To deal',
                'meaning_zh' => '交易',
                'example_sentence' => '完成交易。',
                'example_translation' => 'Complete transaction.',
                'definition' => 'Transaction, trade, to deal',
                'sentences' => ['___所。', '___平台。', '___量。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '竞争',
                'pinyin' => 'jìng zhēng',
                'simplified' => '竞争',
                'traditional' => '競爭',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To compete / Competition',
                'meaning_zh' => '竞争',
                'example_sentence' => '激烈竞争。',
                'example_translation' => 'Fierce competition.',
                'definition' => 'To compete, competition',
                'sentences' => ['___力。', '___对手。', '___优势。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '增长',
                'pinyin' => 'zēng zhǎng',
                'simplified' => '增长',
                'traditional' => '增長',
                'part_of_speech' => 'verb',
                'meaning' => 'To grow / To increase',
                'meaning_zh' => '增长',
                'example_sentence' => '经济增长。',
                'example_translation' => 'Economic growth.',
                'definition' => 'To grow, to increase',
                'sentences' => ['___率。', '快速___。', '___点。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 118,
                'word' => '财富',
                'pinyin' => 'cái fù',
                'simplified' => '财富',
                'traditional' => '財富',
                'part_of_speech' => 'noun',
                'meaning' => 'Wealth / Fortune',
                'meaning_zh' => '财富',
                'example_sentence' => '积累财富。',
                'example_translation' => 'Accumulate wealth.',
                'definition' => 'Wealth, fortune',
                'sentences' => ['___管理。', '___榜。', '精神___。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 119: Culture and Arts (文化和艺术) - 20 words
        $cultureVocab = [
            [
                'topic_id' => 119,
                'word' => '文化',
                'pinyin' => 'wén huà',
                'simplified' => '文化',
                'traditional' => '文化',
                'part_of_speech' => 'noun',
                'meaning' => 'Culture / Cultural',
                'meaning_zh' => '文化',
                'example_sentence' => '传统文化。',
                'example_translation' => 'Traditional culture.',
                'definition' => 'Culture, cultural',
                'sentences' => ['___交流。', '___差异。', '___遗产。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '艺术',
                'pinyin' => 'yì shù',
                'simplified' => '艺术',
                'traditional' => '藝術',
                'part_of_speech' => 'noun',
                'meaning' => 'Art / Artistic',
                'meaning_zh' => '艺术',
                'example_sentence' => '艺术作品。',
                'example_translation' => 'Artwork.',
                'definition' => 'Art, artistic',
                'sentences' => ['___家。', '___馆。', '___品。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '传统节日。',
                'example_translation' => 'Traditional festival.',
                'definition' => 'Tradition, traditional',
                'sentences' => ['___文化。', '___习俗。', '___美德。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '风俗',
                'pinyin' => 'fēng sú',
                'simplified' => '风俗',
                'traditional' => '風俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Convention',
                'meaning_zh' => '风俗',
                'example_sentence' => '地方风俗。',
                'example_translation' => 'Local customs.',
                'definition' => 'Custom, convention',
                'sentences' => ['___习惯。', '___文化。', '___差异。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '习俗',
                'pinyin' => 'xí sú',
                'simplified' => '习俗',
                'traditional' => '習俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Tradition',
                'meaning_zh' => '习俗',
                'example_sentence' => '传统习俗。',
                'example_translation' => 'Traditional custom.',
                'definition' => 'Custom, tradition',
                'sentences' => ['___文化。', '___活动。', '民间___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '节日',
                'pinyin' => 'jié rì',
                'simplified' => '节日',
                'traditional' => '節日',
                'part_of_speech' => 'noun',
                'meaning' => 'Festival / Holiday',
                'meaning_zh' => '节日',
                'example_sentence' => '庆祝节日。',
                'example_translation' => 'Celebrate festival.',
                'definition' => 'Festival, holiday',
                'sentences' => ['___快乐。', '___活动。', '传统___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '庆祝',
                'pinyin' => 'qìng zhù',
                'simplified' => '庆祝',
                'traditional' => '慶祝',
                'part_of_speech' => 'verb',
                'meaning' => 'To celebrate',
                'meaning_zh' => '庆祝',
                'example_sentence' => '庆祝生日。',
                'example_translation' => 'Celebrate birthday.',
                'definition' => 'To celebrate',
                'sentences' => ['___活动。', '___会。', '___胜利。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '仪式',
                'pinyin' => 'yí shì',
                'simplified' => '仪式',
                'traditional' => '儀式',
                'part_of_speech' => 'noun',
                'meaning' => 'Ceremony / Ritual',
                'meaning_zh' => '仪式',
                'example_sentence' => '举行仪式。',
                'example_translation' => 'Hold ceremony.',
                'definition' => 'Ceremony, ritual',
                'sentences' => ['开幕___。', '___感。', '婚礼___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '表演',
                'pinyin' => 'biǎo yǎn',
                'simplified' => '表演',
                'traditional' => '表演',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To perform / Performance',
                'meaning_zh' => '表演',
                'example_sentence' => '精彩表演。',
                'example_translation' => 'Wonderful performance.',
                'definition' => 'To perform, performance',
                'sentences' => ['___节目。', '___者。', '___艺术。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '展览',
                'pinyin' => 'zhǎn lǎn',
                'simplified' => '展览',
                'traditional' => '展覽',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To exhibit / Exhibition',
                'meaning_zh' => '展览',
                'example_sentence' => '参观展览。',
                'example_translation' => 'Visit exhibition.',
                'definition' => 'To exhibit, exhibition',
                'sentences' => ['___会。', '___馆。', '___品。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '博物馆',
                'pinyin' => 'bó wù guǎn',
                'simplified' => '博物馆',
                'traditional' => '博物館',
                'part_of_speech' => 'noun',
                'meaning' => 'Museum',
                'meaning_zh' => '博物馆',
                'example_sentence' => '参观博物馆。',
                'example_translation' => 'Visit museum.',
                'definition' => 'Museum',
                'sentences' => ['___藏品。', '___展览。', '国家___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '绘画',
                'pinyin' => 'huì huà',
                'simplified' => '绘画',
                'traditional' => '繪畫',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Painting / To paint',
                'meaning_zh' => '绘画',
                'example_sentence' => '学习绘画。',
                'example_translation' => 'Learn painting.',
                'definition' => 'Painting, to paint',
                'sentences' => ['___作品。', '___艺术。', '___技巧。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '雕塑',
                'pinyin' => 'diāo sù',
                'simplified' => '雕塑',
                'traditional' => '雕塑',
                'part_of_speech' => 'noun',
                'meaning' => 'Sculpture',
                'meaning_zh' => '雕塑',
                'example_sentence' => '雕塑艺术。',
                'example_translation' => 'Sculpture art.',
                'definition' => 'Sculpture',
                'sentences' => ['___作品。', '___家。', '石___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '音乐',
                'pinyin' => 'yīn yuè',
                'simplified' => '音乐',
                'traditional' => '音樂',
                'part_of_speech' => 'noun',
                'meaning' => 'Music',
                'meaning_zh' => '音乐',
                'example_sentence' => '听音乐。',
                'example_translation' => 'Listen to music.',
                'definition' => 'Music',
                'sentences' => ['___会。', '___家。', '___厅。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '舞蹈',
                'pinyin' => 'wǔ dǎo',
                'simplified' => '舞蹈',
                'traditional' => '舞蹈',
                'part_of_speech' => 'noun',
                'meaning' => 'Dance',
                'meaning_zh' => '舞蹈',
                'example_sentence' => '跳舞蹈。',
                'example_translation' => 'Dance.',
                'definition' => 'Dance',
                'sentences' => ['___表演。', '___家。', '民族___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '戏剧',
                'pinyin' => 'xì jù',
                'simplified' => '戏剧',
                'traditional' => '戲劇',
                'part_of_speech' => 'noun',
                'meaning' => 'Drama / Theater',
                'meaning_zh' => '戏剧',
                'example_sentence' => '戏剧表演。',
                'example_translation' => 'Drama performance.',
                'definition' => 'Drama, theater',
                'sentences' => ['___院。', '___家。', '___作品。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '电影',
                'pinyin' => 'diàn yǐng',
                'simplified' => '电影',
                'traditional' => '電影',
                'part_of_speech' => 'noun',
                'meaning' => 'Movie / Film',
                'meaning_zh' => '电影',
                'example_sentence' => '看电影。',
                'example_translation' => 'Watch a movie.',
                'definition' => 'Movie, film',
                'sentences' => ['___院。', '___节。', '___票。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '文学',
                'pinyin' => 'wén xué',
                'simplified' => '文学',
                'traditional' => '文學',
                'part_of_speech' => 'noun',
                'meaning' => 'Literature',
                'meaning_zh' => '文学',
                'example_sentence' => '文学作品。',
                'example_translation' => 'Literary works.',
                'definition' => 'Literature',
                'sentences' => ['___家。', '___史。', '___奖。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '诗歌',
                'pinyin' => 'shī gē',
                'simplified' => '诗歌',
                'traditional' => '詩歌',
                'part_of_speech' => 'noun',
                'meaning' => 'Poetry / Poem',
                'meaning_zh' => '诗歌',
                'example_sentence' => '朗诵诗歌。',
                'example_translation' => 'Recite poetry.',
                'definition' => 'Poetry, poem',
                'sentences' => ['___创作。', '___集。', '古代___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 119,
                'word' => '小说',
                'pinyin' => 'xiǎo shuō',
                'simplified' => '小说',
                'traditional' => '小說',
                'part_of_speech' => 'noun',
                'meaning' => 'Novel / Fiction',
                'meaning_zh' => '小说',
                'example_sentence' => '看小说。',
                'example_translation' => 'Read novel.',
                'definition' => 'Novel, fiction',
                'sentences' => ['___家。', '长篇___。', '___内容。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 120: Sports and Competition (体育和竞赛) - 20 words
        $sportsVocab = [
            [
                'topic_id' => 120,
                'word' => '体育',
                'pinyin' => 'tǐ yù',
                'simplified' => '体育',
                'traditional' => '體育',
                'part_of_speech' => 'noun',
                'meaning' => 'Sports / Physical education',
                'meaning_zh' => '体育',
                'example_sentence' => '体育运动。',
                'example_translation' => 'Sports.',
                'definition' => 'Sports, physical education',
                'sentences' => ['___馆。', '___课。', '___场。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '运动',
                'pinyin' => 'yùn dòng',
                'simplified' => '运动',
                'traditional' => '運動',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Sports / Exercise / Movement',
                'meaning_zh' => '运动',
                'example_sentence' => '参加运动。',
                'example_translation' => 'Participate in sports.',
                'definition' => 'Sports, exercise, movement',
                'sentences' => ['___会。', '___员。', '___鞋。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '锻炼',
                'pinyin' => 'duàn liàn',
                'simplified' => '锻炼',
                'traditional' => '鍛煉',
                'part_of_speech' => 'verb',
                'meaning' => 'To exercise / To work out',
                'meaning_zh' => '锻炼',
                'example_sentence' => '锻炼身体。',
                'example_translation' => 'Exercise.',
                'definition' => 'To exercise, to work out',
                'sentences' => ['___意志。', '___机会。', '坚持___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '比赛',
                'pinyin' => 'bǐ sài',
                'simplified' => '比赛',
                'traditional' => '比賽',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Competition / Match / To compete',
                'meaning_zh' => '比赛',
                'example_sentence' => '参加比赛。',
                'example_translation' => 'Join competition.',
                'definition' => 'Competition, match, to compete',
                'sentences' => ['___项目。', '___规则。', '___结果。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '竞赛',
                'pinyin' => 'jìng sài',
                'simplified' => '竞赛',
                'traditional' => '競賽',
                'part_of_speech' => 'noun',
                'meaning' => 'Competition / Contest',
                'meaning_zh' => '竞赛',
                'example_sentence' => '知识竞赛。',
                'example_translation' => 'Knowledge competition.',
                'definition' => 'Competition, contest',
                'sentences' => ['___活动。', '___规则。', '___项目。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '冠军',
                'pinyin' => 'guàn jūn',
                'simplified' => '冠军',
                'traditional' => '冠軍',
                'part_of_speech' => 'noun',
                'meaning' => 'Champion / Championship',
                'meaning_zh' => '冠军',
                'example_sentence' => '获得冠军。',
                'example_translation' => 'Win championship.',
                'definition' => 'Champion, championship',
                'sentences' => ['世界___。', '___赛。', '___奖杯。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '奖牌',
                'pinyin' => 'jiǎng pái',
                'simplified' => '奖牌',
                'traditional' => '獎牌',
                'part_of_speech' => 'noun',
                'meaning' => 'Medal',
                'meaning_zh' => '奖牌',
                'example_sentence' => '获得奖牌。',
                'example_translation' => 'Win a medal.',
                'definition' => 'Medal',
                'sentences' => ['金___。', '___榜。', '___得主。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '纪录',
                'pinyin' => 'jì lù',
                'simplified' => '纪录',
                'traditional' => '紀錄',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Record',
                'meaning_zh' => '纪录',
                'example_sentence' => '打破纪录。',
                'example_translation' => 'Break record.',
                'definition' => 'Record',
                'sentences' => ['世界___。', '___片。', '___保持者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '队',
                'pinyin' => 'duì',
                'simplified' => '队',
                'traditional' => '隊',
                'part_of_speech' => 'noun',
                'meaning' => 'Team / Troop',
                'meaning_zh' => '队',
                'example_sentence' => '球队。',
                'example_translation' => 'Ball team.',
                'definition' => 'Team, troop',
                'sentences' => ['___员。', '___长。', '___伍。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '教练',
                'pinyin' => 'jiào liàn',
                'simplified' => '教练',
                'traditional' => '教練',
                'part_of_speech' => 'noun',
                'meaning' => 'Coach / Instructor',
                'meaning_zh' => '教练',
                'example_sentence' => '请教练。',
                'example_translation' => 'Hire a coach.',
                'definition' => 'Coach, instructor',
                'sentences' => ['___员。', '___指导。', '健身___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '球',
                'pinyin' => 'qiú',
                'simplified' => '球',
                'traditional' => '球',
                'part_of_speech' => 'noun',
                'meaning' => 'Ball / Sphere',
                'meaning_zh' => '球',
                'example_sentence' => '打球。',
                'example_translation' => 'Play ball.',
                'definition' => 'Ball, sphere',
                'sentences' => ['足___。', '篮___。', '___类。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '足球',
                'pinyin' => 'zú qiú',
                'simplified' => '足球',
                'traditional' => '足球',
                'part_of_speech' => 'noun',
                'meaning' => 'Football / Soccer',
                'meaning_zh' => '足球',
                'example_sentence' => '踢足球。',
                'example_translation' => 'Play football.',
                'definition' => 'Football, soccer',
                'sentences' => ['___赛。', '___场。', '___队。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '篮球',
                'pinyin' => 'lán qiú',
                'simplified' => '篮球',
                'traditional' => '籃球',
                'part_of_speech' => 'noun',
                'meaning' => 'Basketball',
                'meaning_zh' => '篮球',
                'example_sentence' => '打篮球。',
                'example_translation' => 'Play basketball.',
                'definition' => 'Basketball',
                'sentences' => ['___赛。', '___场。', '___队。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '乒乓球',
                'pinyin' => 'pīng pāng qiú',
                'simplified' => '乒乓球',
                'traditional' => '乒乓球',
                'part_of_speech' => 'noun',
                'meaning' => 'Table tennis / Ping-pong',
                'meaning_zh' => '乒乓球',
                'example_sentence' => '打乒乓球。',
                'example_translation' => 'Play table tennis.',
                'definition' => 'Table tennis, ping-pong',
                'sentences' => ['___拍。', '___台。', '___赛。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '羽毛球',
                'pinyin' => 'yǔ máo qiú',
                'simplified' => '羽毛球',
                'traditional' => '羽毛球',
                'part_of_speech' => 'noun',
                'meaning' => 'Badminton',
                'meaning_zh' => '羽毛球',
                'example_sentence' => '打羽毛球。',
                'example_translation' => 'Play badminton.',
                'definition' => 'Badminton',
                'sentences' => ['___拍。', '___场。', '___赛。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '游泳',
                'pinyin' => 'yóu yǒng',
                'simplified' => '游泳',
                'traditional' => '游泳',
                'part_of_speech' => 'verb',
                'meaning' => 'To swim / Swimming',
                'meaning_zh' => '游泳',
                'example_sentence' => '去游泳。',
                'example_translation' => 'Go swimming.',
                'definition' => 'To swim, swimming',
                'sentences' => ['___池。', '___馆。', '___衣。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '跑步',
                'pinyin' => 'pǎo bù',
                'simplified' => '跑步',
                'traditional' => '跑步',
                'part_of_speech' => 'verb',
                'meaning' => 'To run / Running / To jog',
                'meaning_zh' => '跑步',
                'example_sentence' => '晨跑步。',
                'example_translation' => 'Morning run.',
                'definition' => 'To run, running, to jog',
                'sentences' => ['___机。', '长跑___。', '坚持___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '爬山',
                'pinyin' => 'pá shān',
                'simplified' => '爬山',
                'traditional' => '爬山',
                'part_of_speech' => 'verb',
                'meaning' => 'To climb mountains / Mountain climbing',
                'meaning_zh' => '爬山',
                'example_sentence' => '周末爬山。',
                'example_translation' => 'Climb mountains on weekend.',
                'definition' => 'To climb mountains, mountain climbing',
                'sentences' => ['___活动。', '___装备。', '喜欢___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '瑜伽',
                'pinyin' => 'yú jiā',
                'simplified' => '瑜伽',
                'traditional' => '瑜伽',
                'part_of_speech' => 'noun',
                'meaning' => 'Yoga',
                'meaning_zh' => '瑜伽',
                'example_sentence' => '练瑜伽。',
                'example_translation' => 'Practice yoga.',
                'definition' => 'Yoga',
                'sentences' => ['___课。', '___垫。', '___教练。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 120,
                'word' => '健身',
                'pinyin' => 'jiàn shēn',
                'simplified' => '健身',
                'traditional' => '健身',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To work out / Fitness / Bodybuilding',
                'meaning_zh' => '健身',
                'example_sentence' => '去健身房。',
                'example_translation' => 'Go to gym.',
                'definition' => 'To work out, fitness, bodybuilding',
                'sentences' => ['___房。', '___器材。', '___教练。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($healthVocab, $economyVocab, $cultureVocab, $sportsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
