<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics5to8Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 97: Study and Self-Improvement (学习和自我提升) - 20 words
        $studyVocab = [
            [
                'topic_id' => 97,
                'word' => '学习',
                'pinyin' => 'xué xí',
                'simplified' => '学习',
                'traditional' => '學習',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To study / To learn / Study',
                'meaning_zh' => '学习',
                'example_sentence' => '努力学习。',
                'example_translation' => 'Study hard.',
                'definition' => 'To study, to learn, study',
                'sentences' => ['___方法。', '___态度。', '___成绩。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '进步',
                'pinyin' => 'jìn bù',
                'simplified' => '进步',
                'traditional' => '進步',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To make progress / Progress',
                'meaning_zh' => '进步',
                'example_sentence' => '取得进步。',
                'example_translation' => 'Make progress.',
                'definition' => 'To make progress, progress, improvement',
                'sentences' => ['___很大。', '___快。', '___明显。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '提高',
                'pinyin' => 'tí gāo',
                'simplified' => '提高',
                'traditional' => '提高',
                'part_of_speech' => 'verb',
                'meaning' => 'To improve / To raise / To increase',
                'meaning_zh' => '提高',
                'example_sentence' => '提高水平。',
                'example_translation' => 'Improve level.',
                'definition' => 'To improve, to raise, to increase',
                'sentences' => ['___能力。', '___质量。', '___效率。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '努力',
                'pinyin' => 'nǔ lì',
                'simplified' => '努力',
                'traditional' => '努力',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'To make efforts / To try hard / Diligent',
                'meaning_zh' => '努力',
                'example_sentence' => '很努力工作。',
                'example_translation' => 'Work very hard.',
                'definition' => 'To make efforts, to try hard, diligent',
                'sentences' => ['___学习。', '___工作。', '___奋斗。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '坚持',
                'pinyin' => 'jiān chí',
                'simplified' => '坚持',
                'traditional' => '堅持',
                'part_of_speech' => 'verb',
                'meaning' => 'To persist / To insist / To persevere',
                'meaning_zh' => '坚持',
                'example_sentence' => '坚持学习。',
                'example_translation' => 'Persist in studying.',
                'definition' => 'To persist, to insist, to persevere',
                'sentences' => ['___下去。', '___原则。', '___不懈。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '克服',
                'pinyin' => 'kè fú',
                'simplified' => '克服',
                'traditional' => '克服',
                'part_of_speech' => 'verb',
                'meaning' => 'To overcome / To conquer',
                'meaning_zh' => '克服',
                'example_sentence' => '克服困难。',
                'example_translation' => 'Overcome difficulties.',
                'definition' => 'To overcome, to conquer',
                'sentences' => ['___障碍。', '___缺点。', '___恐惧。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '掌握',
                'pinyin' => 'zhǎng wò',
                'simplified' => '掌握',
                'traditional' => '掌握',
                'part_of_speech' => 'verb',
                'meaning' => 'To master / To grasp',
                'meaning_zh' => '掌握',
                'example_sentence' => '掌握技能。',
                'example_translation' => 'Master skills.',
                'definition' => 'To master, to grasp, to control',
                'sentences' => ['___知识。', '___方法。', '___技术。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '复习',
                'pinyin' => 'fù xí',
                'simplified' => '复习',
                'traditional' => '複習',
                'part_of_speech' => 'verb',
                'meaning' => 'To review / To revise',
                'meaning_zh' => '复习',
                'example_sentence' => '复习功课。',
                'example_translation' => 'Review lessons.',
                'definition' => 'To review, to revise',
                'sentences' => ['___考试。', '___内容。', '___资料。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '预习',
                'pinyin' => 'yù xí',
                'simplified' => '预习',
                'traditional' => '預習',
                'part_of_speech' => 'verb',
                'meaning' => 'To preview / To prepare lessons',
                'meaning_zh' => '预习',
                'example_sentence' => '预习新课。',
                'example_translation' => 'Preview new lessons.',
                'definition' => 'To preview, to prepare lessons',
                'sentences' => ['___课文。', '___材料。', '___明天的课。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To understand / Understanding',
                'meaning_zh' => '理解',
                'example_sentence' => '理解意思。',
                'example_translation' => 'Understand the meaning.',
                'definition' => 'To understand, understanding',
                'sentences' => ['___能力。', '___深刻。', '___错误。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '记忆',
                'pinyin' => 'jì yì',
                'simplified' => '记忆',
                'traditional' => '記憶',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To remember / Memory',
                'meaning_zh' => '记忆',
                'example_sentence' => '记忆力好。',
                'example_translation' => 'Good memory.',
                'definition' => 'To remember, memory',
                'sentences' => ['___深刻。', '___方法。', '___力。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '思考',
                'pinyin' => 'sī kǎo',
                'simplified' => '思考',
                'traditional' => '思考',
                'part_of_speech' => 'verb',
                'meaning' => 'To think / To ponder',
                'meaning_zh' => '思考',
                'example_sentence' => '认真思考。',
                'example_translation' => 'Think carefully.',
                'definition' => 'To think, to ponder, to reflect',
                'sentences' => ['___问题。', '___人生。', '___方式。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '分析',
                'pinyin' => 'fēn xī',
                'simplified' => '分析',
                'traditional' => '分析',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To analyze / Analysis',
                'meaning_zh' => '分析',
                'example_sentence' => '分析原因。',
                'example_translation' => 'Analyze reasons.',
                'definition' => 'To analyze, analysis',
                'sentences' => ['___问题。', '___结果。', '___报告。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '目标',
                'pinyin' => 'mù biāo',
                'simplified' => '目标',
                'traditional' => '目標',
                'part_of_speech' => 'noun',
                'meaning' => 'Goal / Target / Objective',
                'meaning_zh' => '目标',
                'example_sentence' => '实现目标。',
                'example_translation' => 'Achieve goals.',
                'definition' => 'Goal, target, objective',
                'sentences' => ['___明确。', '___计划。', '学习___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '动力',
                'pinyin' => 'dòng lì',
                'simplified' => '动力',
                'traditional' => '動力',
                'part_of_speech' => 'noun',
                'meaning' => 'Motivation / Drive / Power',
                'meaning_zh' => '动力',
                'example_sentence' => '学习动力。',
                'example_translation' => 'Learning motivation.',
                'definition' => 'Motivation, drive, power',
                'sentences' => ['___十足。', '___来源。', '___不足。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '兴趣',
                'pinyin' => 'xìng qù',
                'simplified' => '兴趣',
                'traditional' => '興趣',
                'part_of_speech' => 'noun',
                'meaning' => 'Interest / Hobby',
                'meaning_zh' => '兴趣',
                'example_sentence' => '有兴趣。',
                'example_translation' => 'Have interest.',
                'definition' => 'Interest, hobby',
                'sentences' => ['___爱好。', '___广泛。', '培养___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '态度',
                'pinyin' => 'tài du',
                'simplified' => '态度',
                'traditional' => '態度',
                'part_of_speech' => 'noun',
                'meaning' => 'Attitude / Manner',
                'meaning_zh' => '态度',
                'example_sentence' => '学习态度。',
                'example_translation' => 'Learning attitude.',
                'definition' => 'Attitude, manner',
                'sentences' => ['___认真。', '___好。', '___积极。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '习惯',
                'pinyin' => 'xí guàn',
                'simplified' => '习惯',
                'traditional' => '習慣',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Habit / To be used to',
                'meaning_zh' => '习惯',
                'example_sentence' => '好习惯。',
                'example_translation' => 'Good habit.',
                'definition' => 'Habit, to be used to, to be accustomed to',
                'sentences' => ['___了。', '养成___。', '___性。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '方法',
                'pinyin' => 'fāng fǎ',
                'simplified' => '方法',
                'traditional' => '方法',
                'part_of_speech' => 'noun',
                'meaning' => 'Method / Way / Approach',
                'meaning_zh' => '方法',
                'example_sentence' => '学习方法。',
                'example_translation' => 'Learning method.',
                'definition' => 'Method, way, approach',
                'sentences' => ['___有效。', '___正确。', '___论。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 97,
                'word' => '效果',
                'pinyin' => 'xiào guǒ',
                'simplified' => '效果',
                'traditional' => '效果',
                'part_of_speech' => 'noun',
                'meaning' => 'Effect / Result',
                'meaning_zh' => '效果',
                'example_sentence' => '学习效果好。',
                'example_translation' => 'Good learning effect.',
                'definition' => 'Effect, result, effectiveness',
                'sentences' => ['___显著。', '___不错。', '___评估。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 98: Personality and Character (个性和性格) - 20 words
        $personalityVocab = [
            [
                'topic_id' => 98,
                'word' => '性格',
                'pinyin' => 'xìng gé',
                'simplified' => '性格',
                'traditional' => '性格',
                'part_of_speech' => 'noun',
                'meaning' => 'Personality / Character / Temperament',
                'meaning_zh' => '性格',
                'example_sentence' => '性格开朗。',
                'example_translation' => 'Cheerful personality.',
                'definition' => 'Personality, character, temperament',
                'sentences' => ['___温和。', '___特点。', '___内向。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '个性',
                'pinyin' => 'gè xìng',
                'simplified' => '个性',
                'traditional' => '個性',
                'part_of_speech' => 'noun',
                'meaning' => 'Individuality / Personality',
                'meaning_zh' => '个性',
                'example_sentence' => '有个性。',
                'example_translation' => 'Have personality.',
                'definition' => 'Individuality, personality',
                'sentences' => ['___鲜明。', '___特点。', '___化。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '热情',
                'pinyin' => 'rè qíng',
                'simplified' => '热情',
                'traditional' => '熱情',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Enthusiastic / Warm / Enthusiasm',
                'meaning_zh' => '热情',
                'example_sentence' => '热情欢迎。',
                'example_translation' => 'Warmly welcome.',
                'definition' => 'Enthusiastic, warm, enthusiasm',
                'sentences' => ['___高涨。', '___待客。', '___洋溢。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '冷静',
                'pinyin' => 'lěng jìng',
                'simplified' => '冷静',
                'traditional' => '冷靜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Calm / Cool-headed / Composed',
                'meaning_zh' => '冷静',
                'example_sentence' => '保持冷静。',
                'example_translation' => 'Stay calm.',
                'definition' => 'Calm, cool-headed, composed',
                'sentences' => ['___下来。', '___分析。', '___思考。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '诚实',
                'pinyin' => 'chéng shí',
                'simplified' => '诚实',
                'traditional' => '誠實',
                'part_of_speech' => 'adjective',
                'meaning' => 'Honest / Truthful',
                'meaning_zh' => '诚实',
                'example_sentence' => '诚实的人。',
                'example_translation' => 'Honest person.',
                'definition' => 'Honest, truthful',
                'sentences' => ['___可靠。', '___守信。', '___做人。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '善良',
                'pinyin' => 'shàn liáng',
                'simplified' => '善良',
                'traditional' => '善良',
                'part_of_speech' => 'adjective',
                'meaning' => 'Kind / Kindhearted / Good-natured',
                'meaning_zh' => '善良',
                'example_sentence' => '善良的心。',
                'example_translation' => 'Kind heart.',
                'definition' => 'Kind, kindhearted, good-natured',
                'sentences' => ['___的人。', '___纯朴。', '心地___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '勇敢',
                'pinyin' => 'yǒng gǎn',
                'simplified' => '勇敢',
                'traditional' => '勇敢',
                'part_of_speech' => 'adjective',
                'meaning' => 'Brave / Courageous',
                'meaning_zh' => '勇敢',
                'example_sentence' => '勇敢面对。',
                'example_translation' => 'Bravely face.',
                'definition' => 'Brave, courageous',
                'sentences' => ['___的人。', '___前进。', '___精神。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '谦虚',
                'pinyin' => 'qiān xū',
                'simplified' => '谦虚',
                'traditional' => '謙虛',
                'part_of_speech' => 'adjective',
                'meaning' => 'Modest / Humble',
                'meaning_zh' => '谦虚',
                'example_sentence' => '谦虚的态度。',
                'example_translation' => 'Modest attitude.',
                'definition' => 'Modest, humble',
                'sentences' => ['___谨慎。', '___好学。', '为人___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '骄傲',
                'pinyin' => 'jiāo ào',
                'simplified' => '骄傲',
                'traditional' => '驕傲',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Proud / Arrogant / To be proud',
                'meaning_zh' => '骄傲',
                'example_sentence' => '感到骄傲。',
                'example_translation' => 'Feel proud.',
                'definition' => 'Proud, arrogant, to be proud of',
                'sentences' => ['___自满。', '___的成绩。', '为你___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '自私',
                'pinyin' => 'zì sī',
                'simplified' => '自私',
                'traditional' => '自私',
                'part_of_speech' => 'adjective',
                'meaning' => 'Selfish',
                'meaning_zh' => '自私',
                'example_sentence' => '不要自私。',
                'example_translation' => 'Don\'t be selfish.',
                'definition' => 'Selfish',
                'sentences' => ['___的人。', '___行为。', '太___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '大方',
                'pinyin' => 'dà fang',
                'simplified' => '大方',
                'traditional' => '大方',
                'part_of_speech' => 'adjective',
                'meaning' => 'Generous / Natural / Graceful',
                'meaning_zh' => '大方',
                'example_sentence' => '为人大方。',
                'example_translation' => 'Generous person.',
                'definition' => 'Generous, natural, graceful',
                'sentences' => ['___得体。', '举止___。', '___自然。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '开朗',
                'pinyin' => 'kāi lǎng',
                'simplified' => '开朗',
                'traditional' => '開朗',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cheerful / Outgoing / Open-minded',
                'meaning_zh' => '开朗',
                'example_sentence' => '性格开朗。',
                'example_translation' => 'Cheerful personality.',
                'definition' => 'Cheerful, outgoing, open-minded',
                'sentences' => ['___活泼。', '___乐观。', '___的人。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '内向',
                'pinyin' => 'nèi xiàng',
                'simplified' => '内向',
                'traditional' => '內向',
                'part_of_speech' => 'adjective',
                'meaning' => 'Introverted / Reserved',
                'meaning_zh' => '内向',
                'example_sentence' => '性格内向。',
                'example_translation' => 'Introverted personality.',
                'definition' => 'Introverted, reserved, shy',
                'sentences' => ['___的人。', '___安静。', '比较___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '外向',
                'pinyin' => 'wài xiàng',
                'simplified' => '外向',
                'traditional' => '外向',
                'part_of_speech' => 'adjective',
                'meaning' => 'Outgoing / Extroverted',
                'meaning_zh' => '外向',
                'example_sentence' => '性格外向。',
                'example_translation' => 'Outgoing personality.',
                'definition' => 'Outgoing, extroverted',
                'sentences' => ['___活泼。', '___开朗。', '___的性格。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '活泼',
                'pinyin' => 'huó po',
                'simplified' => '活泼',
                'traditional' => '活潑',
                'part_of_speech' => 'adjective',
                'meaning' => 'Lively / Vivacious / Active',
                'meaning_zh' => '活泼',
                'example_sentence' => '活泼可爱。',
                'example_translation' => 'Lively and cute.',
                'definition' => 'Lively, vivacious, active',
                'sentences' => ['___开朗。', '___的孩子。', '性格___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '温柔',
                'pinyin' => 'wēn róu',
                'simplified' => '温柔',
                'traditional' => '溫柔',
                'part_of_speech' => 'adjective',
                'meaning' => 'Gentle / Tender / Soft',
                'meaning_zh' => '温柔',
                'example_sentence' => '温柔的人。',
                'example_translation' => 'Gentle person.',
                'definition' => 'Gentle, tender, soft',
                'sentences' => ['___体贴。', '___的话。', '性格___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '严格',
                'pinyin' => 'yán gé',
                'simplified' => '严格',
                'traditional' => '嚴格',
                'part_of_speech' => 'adjective',
                'meaning' => 'Strict / Rigorous / Stringent',
                'meaning_zh' => '严格',
                'example_sentence' => '要求严格。',
                'example_translation' => 'Strict requirements.',
                'definition' => 'Strict, rigorous, stringent',
                'sentences' => ['___管理。', '___要求。', '___执行。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '幽默',
                'pinyin' => 'yōu mò',
                'simplified' => '幽默',
                'traditional' => '幽默',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Humorous / Humor',
                'meaning_zh' => '幽默',
                'example_sentence' => '很有幽默感。',
                'example_translation' => 'Very humorous.',
                'definition' => 'Humorous, humor',
                'sentences' => ['___的人。', '___风趣。', '___感。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '乐观',
                'pinyin' => 'lè guān',
                'simplified' => '乐观',
                'traditional' => '樂觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Optimistic / Positive',
                'meaning_zh' => '乐观',
                'example_sentence' => '保持乐观。',
                'example_translation' => 'Stay optimistic.',
                'definition' => 'Optimistic, positive',
                'sentences' => ['___向上。', '___态度。', '___的人。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 98,
                'word' => '悲观',
                'pinyin' => 'bēi guān',
                'simplified' => '悲观',
                'traditional' => '悲觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Pessimistic / Negative',
                'meaning_zh' => '悲观',
                'example_sentence' => '不要悲观。',
                'example_translation' => 'Don\'t be pessimistic.',
                'definition' => 'Pessimistic, negative',
                'sentences' => ['___情绪。', '___态度。', '___失望。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 99: Friendship and Trust (友谊和信任) - 20 words
        $friendshipVocab = [
            [
                'topic_id' => 99,
                'word' => '朋友',
                'pinyin' => 'péng you',
                'simplified' => '朋友',
                'traditional' => '朋友',
                'part_of_speech' => 'noun',
                'meaning' => 'Friend',
                'meaning_zh' => '朋友',
                'example_sentence' => '好朋友。',
                'example_translation' => 'Good friend.',
                'definition' => 'Friend',
                'sentences' => ['___关系。', '___圈。', '交___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '友谊',
                'pinyin' => 'yǒu yì',
                'simplified' => '友谊',
                'traditional' => '友誼',
                'part_of_speech' => 'noun',
                'meaning' => 'Friendship',
                'meaning_zh' => '友谊',
                'example_sentence' => '珍贵的友谊。',
                'example_translation' => 'Precious friendship.',
                'definition' => 'Friendship',
                'sentences' => ['___深厚。', '___长存。', '___赛。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '信任',
                'pinyin' => 'xìn rèn',
                'simplified' => '信任',
                'traditional' => '信任',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To trust / Trust',
                'meaning_zh' => '信任',
                'example_sentence' => '相互信任。',
                'example_translation' => 'Mutual trust.',
                'definition' => 'To trust, trust, confidence',
                'sentences' => ['___他。', '___关系。', '___危机。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '真诚',
                'pinyin' => 'zhēn chéng',
                'simplified' => '真诚',
                'traditional' => '真誠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sincere / Genuine / Honest',
                'meaning_zh' => '真诚',
                'example_sentence' => '真诚的朋友。',
                'example_translation' => 'Sincere friend.',
                'definition' => 'Sincere, genuine, honest',
                'sentences' => ['___待人。', '___的心。', '___相待。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '忠诚',
                'pinyin' => 'zhōng chéng',
                'simplified' => '忠诚',
                'traditional' => '忠誠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Loyal / Faithful / Devoted',
                'meaning_zh' => '忠诚',
                'example_sentence' => '忠诚的朋友。',
                'example_translation' => 'Loyal friend.',
                'definition' => 'Loyal, faithful, devoted',
                'sentences' => ['___可靠。', '___度。', '___于。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To understand / Understanding',
                'meaning_zh' => '理解',
                'example_sentence' => '相互理解。',
                'example_translation' => 'Mutual understanding.',
                'definition' => 'To understand, understanding',
                'sentences' => ['___对方。', '___支持。', '___包容。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '尊重',
                'pinyin' => 'zūn zhòng',
                'simplified' => '尊重',
                'traditional' => '尊重',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To respect / Respect',
                'meaning_zh' => '尊重',
                'example_sentence' => '尊重他人。',
                'example_translation' => 'Respect others.',
                'definition' => 'To respect, respect',
                'sentences' => ['___彼此。', '___意见。', '___选择。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '关心',
                'pinyin' => 'guān xīn',
                'simplified' => '关心',
                'traditional' => '關心',
                'part_of_speech' => 'verb',
                'meaning' => 'To care about / To be concerned',
                'meaning_zh' => '关心',
                'example_sentence' => '关心朋友。',
                'example_translation' => 'Care about friends.',
                'definition' => 'To care about, to be concerned',
                'sentences' => ['___他人。', '___健康。', '___情况。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '帮助',
                'pinyin' => 'bāng zhù',
                'simplified' => '帮助',
                'traditional' => '幫助',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To help / Help / Assistance',
                'meaning_zh' => '帮助',
                'example_sentence' => '互相帮助。',
                'example_translation' => 'Help each other.',
                'definition' => 'To help, help, assistance',
                'sentences' => ['___别人。', '___很大。', '需要___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '支持',
                'pinyin' => 'zhī chí',
                'simplified' => '支持',
                'traditional' => '支持',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To support / Support',
                'meaning_zh' => '支持',
                'example_sentence' => '支持朋友。',
                'example_translation' => 'Support friends.',
                'definition' => 'To support, support',
                'sentences' => ['___你。', '___意见。', '___率。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '陪伴',
                'pinyin' => 'péi bàn',
                'simplified' => '陪伴',
                'traditional' => '陪伴',
                'part_of_speech' => 'verb',
                'meaning' => 'To accompany / To keep company',
                'meaning_zh' => '陪伴',
                'example_sentence' => '陪伴家人。',
                'example_translation' => 'Accompany family.',
                'definition' => 'To accompany, to keep company',
                'sentences' => ['___左右。', '___成长。', '___者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '依靠',
                'pinyin' => 'yī kào',
                'simplified' => '依靠',
                'traditional' => '依靠',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To rely on / To depend on / Support',
                'meaning_zh' => '依靠',
                'example_sentence' => '可以依靠。',
                'example_translation' => 'Can rely on.',
                'definition' => 'To rely on, to depend on, support',
                'sentences' => ['___朋友。', '___自己。', '___对象。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '分享',
                'pinyin' => 'fēn xiǎng',
                'simplified' => '分享',
                'traditional' => '分享',
                'part_of_speech' => 'verb',
                'meaning' => 'To share',
                'meaning_zh' => '分享',
                'example_sentence' => '分享快乐。',
                'example_translation' => 'Share happiness.',
                'definition' => 'To share',
                'sentences' => ['___经验。', '___故事。', '___给。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '秘密',
                'pinyin' => 'mì mì',
                'simplified' => '秘密',
                'traditional' => '秘密',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Secret',
                'meaning_zh' => '秘密',
                'example_sentence' => '保守秘密。',
                'example_translation' => 'Keep a secret.',
                'definition' => 'Secret, confidential',
                'sentences' => ['___武器。', '___告诉。', '___文件。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '误会',
                'pinyin' => 'wù huì',
                'simplified' => '误会',
                'traditional' => '誤會',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Misunderstanding / To misunderstand',
                'meaning_zh' => '误会',
                'example_sentence' => '解释误会。',
                'example_translation' => 'Explain the misunderstanding.',
                'definition' => 'Misunderstanding, to misunderstand',
                'sentences' => ['___了。', '___消除。', '___他。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '矛盾',
                'pinyin' => 'máo dùn',
                'simplified' => '矛盾',
                'traditional' => '矛盾',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Contradiction / Conflict / Contradictory',
                'meaning_zh' => '矛盾',
                'example_sentence' => '解决矛盾。',
                'example_translation' => 'Resolve conflict.',
                'definition' => 'Contradiction, conflict, contradictory',
                'sentences' => ['___冲突。', '___心理。', '___的话。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '原谅',
                'pinyin' => 'yuán liàng',
                'simplified' => '原谅',
                'traditional' => '原諒',
                'part_of_speech' => 'verb',
                'meaning' => 'To forgive / To pardon',
                'meaning_zh' => '原谅',
                'example_sentence' => '请原谅我。',
                'example_translation' => 'Please forgive me.',
                'definition' => 'To forgive, to pardon',
                'sentences' => ['___他。', '___错误。', '___别人。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '道歉',
                'pinyin' => 'dào qiàn',
                'simplified' => '道歉',
                'traditional' => '道歉',
                'part_of_speech' => 'verb',
                'meaning' => 'To apologize',
                'meaning_zh' => '道歉',
                'example_sentence' => '向他道歉。',
                'example_translation' => 'Apologize to him.',
                'definition' => 'To apologize, to make an apology',
                'sentences' => ['___信。', '___声明。', '正式___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '珍惜',
                'pinyin' => 'zhēn xī',
                'simplified' => '珍惜',
                'traditional' => '珍惜',
                'part_of_speech' => 'verb',
                'meaning' => 'To treasure / To cherish',
                'meaning_zh' => '珍惜',
                'example_sentence' => '珍惜友谊。',
                'example_translation' => 'Cherish friendship.',
                'definition' => 'To treasure, to cherish, to value',
                'sentences' => ['___时间。', '___机会。', '___拥有。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 99,
                'word' => '感激',
                'pinyin' => 'gǎn jī',
                'simplified' => '感激',
                'traditional' => '感激',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To be grateful / Grateful',
                'meaning_zh' => '感激',
                'example_sentence' => '非常感激。',
                'example_translation' => 'Very grateful.',
                'definition' => 'To be grateful, grateful, to appreciate',
                'sentences' => ['___不尽。', '___之情。', '___你。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 100: Love and Family Life (爱情和家庭生活) - 20 words
        $loveVocab = [
            [
                'topic_id' => 100,
                'word' => '爱情',
                'pinyin' => 'ài qíng',
                'simplified' => '爱情',
                'traditional' => '愛情',
                'part_of_speech' => 'noun',
                'meaning' => 'Love / Romance',
                'meaning_zh' => '爱情',
                'example_sentence' => '真挚的爱情。',
                'example_translation' => 'Sincere love.',
                'definition' => 'Love, romance',
                'sentences' => ['___故事。', '___观。', '___电影。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '恋爱',
                'pinyin' => 'liàn ài',
                'simplified' => '恋爱',
                'traditional' => '戀愛',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To be in love / Love',
                'meaning_zh' => '恋爱',
                'example_sentence' => '谈恋爱。',
                'example_translation' => 'Be in a relationship.',
                'definition' => 'To be in love, love, romance',
                'sentences' => ['___中。', '___自由。', '___关系。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '结婚',
                'pinyin' => 'jié hūn',
                'simplified' => '结婚',
                'traditional' => '結婚',
                'part_of_speech' => 'verb',
                'meaning' => 'To get married / To marry',
                'meaning_zh' => '结婚',
                'example_sentence' => '他们结婚了。',
                'example_translation' => 'They got married.',
                'definition' => 'To get married, to marry',
                'sentences' => ['___证。', '___典礼。', '___照。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '婚姻',
                'pinyin' => 'hūn yīn',
                'simplified' => '婚姻',
                'traditional' => '婚姻',
                'part_of_speech' => 'noun',
                'meaning' => 'Marriage / Matrimony',
                'meaning_zh' => '婚姻',
                'example_sentence' => '幸福的婚姻。',
                'example_translation' => 'Happy marriage.',
                'definition' => 'Marriage, matrimony',
                'sentences' => ['___生活。', '___观。', '___法。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '夫妻',
                'pinyin' => 'fū qī',
                'simplified' => '夫妻',
                'traditional' => '夫妻',
                'part_of_speech' => 'noun',
                'meaning' => 'Husband and wife / Couple',
                'meaning_zh' => '夫妻',
                'example_sentence' => '夫妻和睦。',
                'example_translation' => 'Harmonious couple.',
                'definition' => 'Husband and wife, couple',
                'sentences' => ['___关系。', '___双方。', '___俩。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '丈夫',
                'pinyin' => 'zhàng fu',
                'simplified' => '丈夫',
                'traditional' => '丈夫',
                'part_of_speech' => 'noun',
                'meaning' => 'Husband',
                'meaning_zh' => '丈夫',
                'example_sentence' => '她的丈夫。',
                'example_translation' => 'Her husband.',
                'definition' => 'Husband',
                'sentences' => ['___工作。', '___很好。', '未来___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '妻子',
                'pinyin' => 'qī zi',
                'simplified' => '妻子',
                'traditional' => '妻子',
                'part_of_speech' => 'noun',
                'meaning' => 'Wife',
                'meaning_zh' => '妻子',
                'example_sentence' => '他的妻子。',
                'example_translation' => 'His wife.',
                'definition' => 'Wife',
                'sentences' => ['___贤惠。', '___孩子。', '前___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '家庭',
                'pinyin' => 'jiā tíng',
                'simplified' => '家庭',
                'traditional' => '家庭',
                'part_of_speech' => 'noun',
                'meaning' => 'Family / Household',
                'meaning_zh' => '家庭',
                'example_sentence' => '幸福的家庭。',
                'example_translation' => 'Happy family.',
                'definition' => 'Family, household',
                'sentences' => ['___成员。', '___教育。', '___生活。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '亲人',
                'pinyin' => 'qīn rén',
                'simplified' => '亲人',
                'traditional' => '親人',
                'part_of_speech' => 'noun',
                'meaning' => 'Family member / Relative / Loved one',
                'meaning_zh' => '亲人',
                'example_sentence' => '思念亲人。',
                'example_translation' => 'Miss loved ones.',
                'definition' => 'Family member, relative, loved one',
                'sentences' => ['___团聚。', '___朋友。', '___去世。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '亲戚',
                'pinyin' => 'qīn qi',
                'simplified' => '亲戚',
                'traditional' => '親戚',
                'part_of_speech' => 'noun',
                'meaning' => 'Relative / Kin',
                'meaning_zh' => '亲戚',
                'example_sentence' => '拜访亲戚。',
                'example_translation' => 'Visit relatives.',
                'definition' => 'Relative, kin',
                'sentences' => ['___朋友。', '___关系。', '远方___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '父母',
                'pinyin' => 'fù mǔ',
                'simplified' => '父母',
                'traditional' => '父母',
                'part_of_speech' => 'noun',
                'meaning' => 'Parents',
                'meaning_zh' => '父母',
                'example_sentence' => '孝顺父母。',
                'example_translation' => 'Be filial to parents.',
                'definition' => 'Parents',
                'sentences' => ['___爱。', '___之爱。', '___双亲。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '孩子',
                'pinyin' => 'hái zi',
                'simplified' => '孩子',
                'traditional' => '孩子',
                'part_of_speech' => 'noun',
                'meaning' => 'Child / Children',
                'meaning_zh' => '孩子',
                'example_sentence' => '照顾孩子。',
                'example_translation' => 'Take care of children.',
                'definition' => 'Child, children, kid',
                'sentences' => ['___教育。', '___成长。', '小___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '抚养',
                'pinyin' => 'fǔ yǎng',
                'simplified' => '抚养',
                'traditional' => '撫養',
                'part_of_speech' => 'verb',
                'meaning' => 'To raise / To bring up / To foster',
                'meaning_zh' => '抚养',
                'example_sentence' => '抚养孩子。',
                'example_translation' => 'Raise children.',
                'definition' => 'To raise, to bring up, to foster',
                'sentences' => ['___费。', '___成人。', '___权。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '教育',
                'pinyin' => 'jiào yù',
                'simplified' => '教育',
                'traditional' => '教育',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To educate / Education',
                'meaning_zh' => '教育',
                'example_sentence' => '教育孩子。',
                'example_translation' => 'Educate children.',
                'definition' => 'To educate, education',
                'sentences' => ['___制度。', '___事业。', '___水平。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '照顾',
                'pinyin' => 'zhào gu',
                'simplified' => '照顾',
                'traditional' => '照顧',
                'part_of_speech' => 'verb',
                'meaning' => 'To take care of / To look after',
                'meaning_zh' => '照顾',
                'example_sentence' => '照顾家人。',
                'example_translation' => 'Take care of family.',
                'definition' => 'To take care of, to look after',
                'sentences' => ['___好。', '___病人。', '___自己。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '幸福',
                'pinyin' => 'xìng fú',
                'simplified' => '幸福',
                'traditional' => '幸福',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Happy / Happiness',
                'meaning_zh' => '幸福',
                'example_sentence' => '幸福生活。',
                'example_translation' => 'Happy life.',
                'definition' => 'Happy, happiness, blessed',
                'sentences' => ['___的人。', '___感。', '___美满。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '和谐',
                'pinyin' => 'hé xié',
                'simplified' => '和谐',
                'traditional' => '和諧',
                'part_of_speech' => 'adjective',
                'meaning' => 'Harmonious / Harmony',
                'meaning_zh' => '和谐',
                'example_sentence' => '和谐家庭。',
                'example_translation' => 'Harmonious family.',
                'definition' => 'Harmonious, harmony',
                'sentences' => ['___社会。', '___相处。', '___统一。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '温暖',
                'pinyin' => 'wēn nuǎn',
                'simplified' => '温暖',
                'traditional' => '溫暖',
                'part_of_speech' => 'adjective',
                'meaning' => 'Warm / Warmth',
                'meaning_zh' => '温暖',
                'example_sentence' => '温暖的家。',
                'example_translation' => 'Warm home.',
                'definition' => 'Warm, warmth',
                'sentences' => ['___人心。', '___的阳光。', '___关怀。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '责任',
                'pinyin' => 'zé rèn',
                'simplified' => '责任',
                'traditional' => '責任',
                'part_of_speech' => 'noun',
                'meaning' => 'Responsibility / Duty',
                'meaning_zh' => '责任',
                'example_sentence' => '家庭责任。',
                'example_translation' => 'Family responsibility.',
                'definition' => 'Responsibility, duty',
                'sentences' => ['___感。', '承担___。', '___心。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 100,
                'word' => '牺牲',
                'pinyin' => 'xī shēng',
                'simplified' => '牺牲',
                'traditional' => '犧牲',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To sacrifice / Sacrifice',
                'meaning_zh' => '牺牲',
                'example_sentence' => '牺牲时间。',
                'example_translation' => 'Sacrifice time.',
                'definition' => 'To sacrifice, sacrifice',
                'sentences' => ['___精神。', '___自己。', '___品。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($studyVocab, $personalityVocab, $friendshipVocab, $loveVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
