<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics29to30Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 121: Time and Change (时间和变化) - 20 words
        $timeVocab = [
            [
                'topic_id' => 121,
                'word' => '时代',
                'pinyin' => 'shí dài',
                'simplified' => '时代',
                'traditional' => '時代',
                'part_of_speech' => 'noun',
                'meaning' => 'Era / Age / Period',
                'meaning_zh' => '时代',
                'example_sentence' => '新时代。',
                'example_translation' => 'New era.',
                'definition' => 'Era, age, period',
                'sentences' => ['___变化。', '___精神。', '___特征。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '时期',
                'pinyin' => 'shí qī',
                'simplified' => '时期',
                'traditional' => '時期',
                'part_of_speech' => 'noun',
                'meaning' => 'Period / Phase / Time',
                'meaning_zh' => '时期',
                'example_sentence' => '关键时期。',
                'example_translation' => 'Critical period.',
                'definition' => 'Period, phase, time',
                'sentences' => ['___内。', '特殊___。', '发展___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '阶段',
                'pinyin' => 'jiē duàn',
                'simplified' => '阶段',
                'traditional' => '階段',
                'part_of_speech' => 'noun',
                'meaning' => 'Stage / Phase',
                'meaning_zh' => '阶段',
                'example_sentence' => '不同阶段。',
                'example_translation' => 'Different stages.',
                'definition' => 'Stage, phase',
                'sentences' => ['___性。', '初级___。', '___目标。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '过程',
                'pinyin' => 'guò chéng',
                'simplified' => '过程',
                'traditional' => '過程',
                'part_of_speech' => 'noun',
                'meaning' => 'Process / Course',
                'meaning_zh' => '过程',
                'example_sentence' => '发展过程。',
                'example_translation' => 'Development process.',
                'definition' => 'Process, course',
                'sentences' => ['___中。', '___漫长。', '___管理。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '变化',
                'pinyin' => 'biàn huà',
                'simplified' => '变化',
                'traditional' => '變化',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Change / To change',
                'meaning_zh' => '变化',
                'example_sentence' => '巨大变化。',
                'example_translation' => 'Great changes.',
                'definition' => 'Change, to change',
                'sentences' => ['___很大。', '___过程。', '气候___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '改变',
                'pinyin' => 'gǎi biàn',
                'simplified' => '改变',
                'traditional' => '改變',
                'part_of_speech' => 'verb',
                'meaning' => 'To change / To alter / To transform',
                'meaning_zh' => '改变',
                'example_sentence' => '改变主意。',
                'example_translation' => 'Change one\'s mind.',
                'definition' => 'To change, to alter, to transform',
                'sentences' => ['___想法。', '___命运。', '___现状。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '转变',
                'pinyin' => 'zhuǎn biàn',
                'simplified' => '转变',
                'traditional' => '轉變',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To transform / Transformation',
                'meaning_zh' => '转变',
                'example_sentence' => '观念转变。',
                'example_translation' => 'Change of concept.',
                'definition' => 'To transform, transformation',
                'sentences' => ['___方式。', '___态度。', '___思想。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '演变',
                'pinyin' => 'yǎn biàn',
                'simplified' => '演变',
                'traditional' => '演變',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To evolve / Evolution',
                'meaning_zh' => '演变',
                'example_sentence' => '历史演变。',
                'example_translation' => 'Historical evolution.',
                'definition' => 'To evolve, evolution',
                'sentences' => ['___过程。', '___规律。', '___结果。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '发生',
                'pinyin' => 'fā shēng',
                'simplified' => '发生',
                'traditional' => '發生',
                'part_of_speech' => 'verb',
                'meaning' => 'To happen / To occur / To take place',
                'meaning_zh' => '发生',
                'example_sentence' => '发生变化。',
                'example_translation' => 'Changes occurred.',
                'definition' => 'To happen, to occur, to take place',
                'sentences' => ['___事故。', '___了。', '___什么。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '出现',
                'pinyin' => 'chū xiàn',
                'simplified' => '出现',
                'traditional' => '出現',
                'part_of_speech' => 'verb',
                'meaning' => 'To appear / To emerge',
                'meaning_zh' => '出现',
                'example_sentence' => '出现问题。',
                'example_translation' => 'Problems appeared.',
                'definition' => 'To appear, to emerge',
                'sentences' => ['___了。', '___新情况。', '___机会。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '产生',
                'pinyin' => 'chǎn shēng',
                'simplified' => '产生',
                'traditional' => '產生',
                'part_of_speech' => 'verb',
                'meaning' => 'To produce / To generate / To arise',
                'meaning_zh' => '产生',
                'example_sentence' => '产生影响。',
                'example_translation' => 'Generate influence.',
                'definition' => 'To produce, to generate, to arise',
                'sentences' => ['___作用。', '___效果。', '___兴趣。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '形成',
                'pinyin' => 'xíng chéng',
                'simplified' => '形成',
                'traditional' => '形成',
                'part_of_speech' => 'verb',
                'meaning' => 'To form / To take shape',
                'meaning_zh' => '形成',
                'example_sentence' => '形成习惯。',
                'example_translation' => 'Form a habit.',
                'definition' => 'To form, to take shape',
                'sentences' => ['___对比。', '___共识。', '___规模。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '造成',
                'pinyin' => 'zào chéng',
                'simplified' => '造成',
                'traditional' => '造成',
                'part_of_speech' => 'verb',
                'meaning' => 'To cause / To bring about',
                'meaning_zh' => '造成',
                'example_sentence' => '造成损失。',
                'example_translation' => 'Cause losses.',
                'definition' => 'To cause, to bring about',
                'sentences' => ['___影响。', '___后果。', '___危害。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '导致',
                'pinyin' => 'dǎo zhì',
                'simplified' => '导致',
                'traditional' => '導致',
                'part_of_speech' => 'verb',
                'meaning' => 'To lead to / To result in / To cause',
                'meaning_zh' => '导致',
                'example_sentence' => '导致失败。',
                'example_translation' => 'Lead to failure.',
                'definition' => 'To lead to, to result in, to cause',
                'sentences' => ['___结果。', '___问题。', '___事故。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '促进',
                'pinyin' => 'cù jìn',
                'simplified' => '促进',
                'traditional' => '促進',
                'part_of_speech' => 'verb',
                'meaning' => 'To promote / To advance / To facilitate',
                'meaning_zh' => '促进',
                'example_sentence' => '促进发展。',
                'example_translation' => 'Promote development.',
                'definition' => 'To promote, to advance, to facilitate',
                'sentences' => ['___交流。', '___合作。', '___作用。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '推动',
                'pinyin' => 'tuī dòng',
                'simplified' => '推动',
                'traditional' => '推動',
                'part_of_speech' => 'verb',
                'meaning' => 'To push forward / To promote',
                'meaning_zh' => '推动',
                'example_sentence' => '推动进步。',
                'example_translation' => 'Push forward progress.',
                'definition' => 'To push forward, to promote',
                'sentences' => ['___发展。', '___改革。', '___力。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '加速',
                'pinyin' => 'jiā sù',
                'simplified' => '加速',
                'traditional' => '加速',
                'part_of_speech' => 'verb',
                'meaning' => 'To accelerate / To speed up',
                'meaning_zh' => '加速',
                'example_sentence' => '加速发展。',
                'example_translation' => 'Accelerate development.',
                'definition' => 'To accelerate, to speed up',
                'sentences' => ['___度。', '___器。', '___进程。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '延长',
                'pinyin' => 'yán cháng',
                'simplified' => '延长',
                'traditional' => '延長',
                'part_of_speech' => 'verb',
                'meaning' => 'To extend / To prolong / To lengthen',
                'meaning_zh' => '延长',
                'example_sentence' => '延长时间。',
                'example_translation' => 'Extend time.',
                'definition' => 'To extend, to prolong, to lengthen',
                'sentences' => ['___寿命。', '___期限。', '___线。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '缩短',
                'pinyin' => 'suō duǎn',
                'simplified' => '缩短',
                'traditional' => '縮短',
                'part_of_speech' => 'verb',
                'meaning' => 'To shorten / To cut down',
                'meaning_zh' => '缩短',
                'example_sentence' => '缩短距离。',
                'example_translation' => 'Shorten distance.',
                'definition' => 'To shorten, to cut down',
                'sentences' => ['___时间。', '___差距。', '___工期。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 121,
                'word' => '持续',
                'pinyin' => 'chí xù',
                'simplified' => '持续',
                'traditional' => '持續',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To continue / To last / Continuous',
                'meaning_zh' => '持续',
                'example_sentence' => '持续发展。',
                'example_translation' => 'Sustainable development.',
                'definition' => 'To continue, to last, continuous',
                'sentences' => ['___时间。', '___增长。', '___性。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 122: Future and Goals (未来和目标) - 20 words
        $futureVocab = [
            [
                'topic_id' => 122,
                'word' => '未来',
                'pinyin' => 'wèi lái',
                'simplified' => '未来',
                'traditional' => '未來',
                'part_of_speech' => 'noun',
                'meaning' => 'Future',
                'meaning_zh' => '未来',
                'example_sentence' => '未来计划。',
                'example_translation' => 'Future plans.',
                'definition' => 'Future',
                'sentences' => ['___发展。', '___世界。', '___展望。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '将来',
                'pinyin' => 'jiāng lái',
                'simplified' => '将来',
                'traditional' => '將來',
                'part_of_speech' => 'noun',
                'meaning' => 'Future / In the future',
                'meaning_zh' => '将来',
                'example_sentence' => '将来的事。',
                'example_translation' => 'Future matters.',
                'definition' => 'Future, in the future',
                'sentences' => ['___有一天。', '___打算。', '___会。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '目标',
                'pinyin' => 'mù biāo',
                'simplified' => '目标',
                'traditional' => '目標',
                'part_of_speech' => 'noun',
                'meaning' => 'Goal / Target / Objective',
                'meaning_zh' => '目标',
                'example_sentence' => '实现目标。',
                'example_translation' => 'Achieve goals.',
                'definition' => 'Goal, target, objective',
                'sentences' => ['___明确。', '___市场。', '___客户。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '目的',
                'pinyin' => 'mù dì',
                'simplified' => '目的',
                'traditional' => '目的',
                'part_of_speech' => 'noun',
                'meaning' => 'Purpose / Aim / Objective',
                'meaning_zh' => '目的',
                'example_sentence' => '达到目的。',
                'example_translation' => 'Achieve the purpose.',
                'definition' => 'Purpose, aim, objective',
                'sentences' => ['___是。', '___地。', '___性。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '理想',
                'pinyin' => 'lǐ xiǎng',
                'simplified' => '理想',
                'traditional' => '理想',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Ideal / Dream / Perfect',
                'meaning_zh' => '理想',
                'example_sentence' => '实现理想。',
                'example_translation' => 'Realize ideals.',
                'definition' => 'Ideal, dream, perfect',
                'sentences' => ['___主义。', '___化。', '___状态。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '梦想',
                'pinyin' => 'mèng xiǎng',
                'simplified' => '梦想',
                'traditional' => '夢想',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Dream / To dream of',
                'meaning_zh' => '梦想',
                'example_sentence' => '追求梦想。',
                'example_translation' => 'Pursue dreams.',
                'definition' => 'Dream, to dream of',
                'sentences' => ['___成真。', '___实现。', '___家。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '希望',
                'pinyin' => 'xī wàng',
                'simplified' => '希望',
                'traditional' => '希望',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To hope / Hope',
                'meaning_zh' => '希望',
                'example_sentence' => '充满希望。',
                'example_translation' => 'Full of hope.',
                'definition' => 'To hope, hope',
                'sentences' => ['___你。', '___工程。', '___渺茫。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '期望',
                'pinyin' => 'qī wàng',
                'simplified' => '期望',
                'traditional' => '期望',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To expect / Expectation',
                'meaning_zh' => '期望',
                'example_sentence' => '不负期望。',
                'example_translation' => 'Live up to expectations.',
                'definition' => 'To expect, expectation',
                'sentences' => ['___值。', '___你。', '___高。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '愿望',
                'pinyin' => 'yuàn wàng',
                'simplified' => '愿望',
                'traditional' => '願望',
                'part_of_speech' => 'noun',
                'meaning' => 'Wish / Desire / Aspiration',
                'meaning_zh' => '愿望',
                'example_sentence' => '美好愿望。',
                'example_translation' => 'Good wishes.',
                'definition' => 'Wish, desire, aspiration',
                'sentences' => ['___实现。', '___强烈。', '___清单。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '打算',
                'pinyin' => 'dǎ suàn',
                'simplified' => '打算',
                'traditional' => '打算',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To plan / To intend / Plan',
                'meaning_zh' => '打算',
                'example_sentence' => '有什么打算？',
                'example_translation' => 'What are your plans?',
                'definition' => 'To plan, to intend, plan',
                'sentences' => ['___做。', '___去。', '___买。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '计划',
                'pinyin' => 'jì huà',
                'simplified' => '计划',
                'traditional' => '計劃',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Plan / To plan',
                'meaning_zh' => '计划',
                'example_sentence' => '制定计划。',
                'example_translation' => 'Make a plan.',
                'definition' => 'Plan, to plan',
                'sentences' => ['___书。', '___生育。', '___经济。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '规划',
                'pinyin' => 'guī huà',
                'simplified' => '规划',
                'traditional' => '規劃',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Plan / Planning / To plan',
                'meaning_zh' => '规划',
                'example_sentence' => '城市规划。',
                'example_translation' => 'Urban planning.',
                'definition' => 'Plan, planning, to plan',
                'sentences' => ['___设计。', '___局。', '___方案。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '准备',
                'pinyin' => 'zhǔn bèi',
                'simplified' => '准备',
                'traditional' => '準備',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To prepare / Preparation',
                'meaning_zh' => '准备',
                'example_sentence' => '准备好了。',
                'example_translation' => 'Ready.',
                'definition' => 'To prepare, preparation',
                'sentences' => ['___工作。', '___考试。', '___充分。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '努力',
                'pinyin' => 'nǔ lì',
                'simplified' => '努力',
                'traditional' => '努力',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To make efforts / To strive / Hardworking',
                'meaning_zh' => '努力',
                'example_sentence' => '努力工作。',
                'example_translation' => 'Work hard.',
                'definition' => 'To make efforts, to strive, hardworking',
                'sentences' => ['___学习。', '___奋斗。', '___方向。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '奋斗',
                'pinyin' => 'fèn dòu',
                'simplified' => '奋斗',
                'traditional' => '奮鬥',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To struggle / To strive / Struggle',
                'meaning_zh' => '奋斗',
                'example_sentence' => '为理想奋斗。',
                'example_translation' => 'Struggle for ideals.',
                'definition' => 'To struggle, to strive, struggle',
                'sentences' => ['___目标。', '___精神。', '___者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '坚持',
                'pinyin' => 'jiān chí',
                'simplified' => '坚持',
                'traditional' => '堅持',
                'part_of_speech' => 'verb',
                'meaning' => 'To persist / To insist / To stick to',
                'meaning_zh' => '坚持',
                'example_sentence' => '坚持不懈。',
                'example_translation' => 'Persist unremittingly.',
                'definition' => 'To persist, to insist, to stick to',
                'sentences' => ['___原则。', '___下去。', '___到底。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '追求',
                'pinyin' => 'zhuī qiú',
                'simplified' => '追求',
                'traditional' => '追求',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To pursue / To seek / Pursuit',
                'meaning_zh' => '追求',
                'example_sentence' => '追求梦想。',
                'example_translation' => 'Pursue dreams.',
                'definition' => 'To pursue, to seek, pursuit',
                'sentences' => ['___真理。', '___完美。', '___者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '挑战',
                'pinyin' => 'tiǎo zhàn',
                'simplified' => '挑战',
                'traditional' => '挑戰',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To challenge / Challenge',
                'meaning_zh' => '挑战',
                'example_sentence' => '面对挑战。',
                'example_translation' => 'Face challenges.',
                'definition' => 'To challenge, challenge',
                'sentences' => ['___性。', '___者。', '___自我。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '机会',
                'pinyin' => 'jī huì',
                'simplified' => '机会',
                'traditional' => '機會',
                'part_of_speech' => 'noun',
                'meaning' => 'Opportunity / Chance',
                'meaning_zh' => '机会',
                'example_sentence' => '抓住机会。',
                'example_translation' => 'Seize the opportunity.',
                'definition' => 'Opportunity, chance',
                'sentences' => ['___难得。', '___成本。', '___主义。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 122,
                'word' => '可能',
                'pinyin' => 'kě néng',
                'simplified' => '可能',
                'traditional' => '可能',
                'part_of_speech' => 'adjective/noun/adverb',
                'meaning' => 'Possible / Possibility / Maybe',
                'meaning_zh' => '可能',
                'example_sentence' => '一切皆有可能。',
                'example_translation' => 'Everything is possible.',
                'definition' => 'Possible, possibility, maybe',
                'sentences' => ['___性。', '___会。', '有___。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($timeVocab, $futureVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
