<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics17to20Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 109: Dining and Food Culture (餐饮和饮食文化) - 20 words
        $diningVocab = [
            [
                'topic_id' => 109,
                'word' => '餐厅',
                'pinyin' => 'cān tīng',
                'simplified' => '餐厅',
                'traditional' => '餐廳',
                'part_of_speech' => 'noun',
                'meaning' => 'Restaurant / Dining room',
                'meaning_zh' => '餐厅',
                'example_sentence' => '去餐厅吃饭。',
                'example_translation' => 'Go to the restaurant to eat.',
                'definition' => 'Restaurant, dining room',
                'sentences' => ['___预订。', '___菜单。', '___服务。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '菜单',
                'pinyin' => 'cài dān',
                'simplified' => '菜单',
                'traditional' => '菜單',
                'part_of_speech' => 'noun',
                'meaning' => 'Menu',
                'meaning_zh' => '菜单',
                'example_sentence' => '看菜单。',
                'example_translation' => 'Look at the menu.',
                'definition' => 'Menu',
                'sentences' => ['___推荐。', '___价格。', '___内容。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '点菜',
                'pinyin' => 'diǎn cài',
                'simplified' => '点菜',
                'traditional' => '點菜',
                'part_of_speech' => 'verb',
                'meaning' => 'To order dishes',
                'meaning_zh' => '点菜',
                'example_sentence' => '开始点菜。',
                'example_translation' => 'Start ordering.',
                'definition' => 'To order dishes, to order food',
                'sentences' => ['___了。', '___系统。', '___单。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '特色',
                'pinyin' => 'tè sè',
                'simplified' => '特色',
                'traditional' => '特色',
                'part_of_speech' => 'noun',
                'meaning' => 'Characteristic / Special feature',
                'meaning_zh' => '特色',
                'example_sentence' => '特色菜。',
                'example_translation' => 'Specialty dish.',
                'definition' => 'Characteristic, special feature',
                'sentences' => ['___小吃。', '___餐厅。', '地方___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '口味',
                'pinyin' => 'kǒu wèi',
                'simplified' => '口味',
                'traditional' => '口味',
                'part_of_speech' => 'noun',
                'meaning' => 'Taste / Flavor / Preference',
                'meaning_zh' => '口味',
                'example_sentence' => '口味很好。',
                'example_translation' => 'Good taste.',
                'definition' => 'Taste, flavor, preference',
                'sentences' => ['___独特。', '___清淡。', '___重。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '味道',
                'pinyin' => 'wèi dao',
                'simplified' => '味道',
                'traditional' => '味道',
                'part_of_speech' => 'noun',
                'meaning' => 'Taste / Flavor / Smell',
                'meaning_zh' => '味道',
                'example_sentence' => '味道不错。',
                'example_translation' => 'Tastes good.',
                'definition' => 'Taste, flavor, smell',
                'sentences' => ['___好。', '___鲜美。', '___怪。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '辣',
                'pinyin' => 'là',
                'simplified' => '辣',
                'traditional' => '辣',
                'part_of_speech' => 'adjective',
                'meaning' => 'Spicy / Hot',
                'meaning_zh' => '辣',
                'example_sentence' => '很辣。',
                'example_translation' => 'Very spicy.',
                'definition' => 'Spicy, hot, pungent',
                'sentences' => ['___椒。', '___的菜。', '不___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '咸',
                'pinyin' => 'xián',
                'simplified' => '咸',
                'traditional' => '鹹',
                'part_of_speech' => 'adjective',
                'meaning' => 'Salty',
                'meaning_zh' => '咸',
                'example_sentence' => '太咸了。',
                'example_translation' => 'Too salty.',
                'definition' => 'Salty',
                'sentences' => ['___味。', '___的菜。', '不___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '酸',
                'pinyin' => 'suān',
                'simplified' => '酸',
                'traditional' => '酸',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sour / Tart',
                'meaning_zh' => '酸',
                'example_sentence' => '酸甜可口。',
                'example_translation' => 'Sweet and sour.',
                'definition' => 'Sour, tart, acid',
                'sentences' => ['___辣汤。', '___味。', '___的。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '苦',
                'pinyin' => 'kǔ',
                'simplified' => '苦',
                'traditional' => '苦',
                'part_of_speech' => 'adjective',
                'meaning' => 'Bitter',
                'meaning_zh' => '苦',
                'example_sentence' => '药很苦。',
                'example_translation' => 'Medicine is bitter.',
                'definition' => 'Bitter',
                'sentences' => ['___味。', '___瓜。', '良药___口。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '营养',
                'pinyin' => 'yíng yǎng',
                'simplified' => '营养',
                'traditional' => '營養',
                'part_of_speech' => 'noun',
                'meaning' => 'Nutrition / Nourishment',
                'meaning_zh' => '营养',
                'example_sentence' => '营养丰富。',
                'example_translation' => 'Rich in nutrition.',
                'definition' => 'Nutrition, nourishment',
                'sentences' => ['___价值。', '___均衡。', '___不良。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '卫生',
                'pinyin' => 'wèi shēng',
                'simplified' => '卫生',
                'traditional' => '衛生',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Hygiene / Sanitary',
                'meaning_zh' => '卫生',
                'example_sentence' => '注意卫生。',
                'example_translation' => 'Pay attention to hygiene.',
                'definition' => 'Hygiene, sanitary, health',
                'sentences' => ['___间。', '___条件。', '___标准。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '筷子',
                'pinyin' => 'kuài zi',
                'simplified' => '筷子',
                'traditional' => '筷子',
                'part_of_speech' => 'noun',
                'meaning' => 'Chopsticks',
                'meaning_zh' => '筷子',
                'example_sentence' => '用筷子吃饭。',
                'example_translation' => 'Eat with chopsticks.',
                'definition' => 'Chopsticks',
                'sentences' => ['一双___。', '___用法。', '___文化。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '餐具',
                'pinyin' => 'cān jù',
                'simplified' => '餐具',
                'traditional' => '餐具',
                'part_of_speech' => 'noun',
                'meaning' => 'Tableware / Cutlery',
                'meaning_zh' => '餐具',
                'example_sentence' => '摆放餐具。',
                'example_translation' => 'Set the tableware.',
                'definition' => 'Tableware, cutlery, dinnerware',
                'sentences' => ['___消毒。', '___齐全。', '___柜。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '招待',
                'pinyin' => 'zhāo dài',
                'simplified' => '招待',
                'traditional' => '招待',
                'part_of_speech' => 'verb',
                'meaning' => 'To entertain / To treat / To receive',
                'meaning_zh' => '招待',
                'example_sentence' => '招待客人。',
                'example_translation' => 'Entertain guests.',
                'definition' => 'To entertain, to treat, to receive',
                'sentences' => ['___会。', '___所。', '热情___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '请客',
                'pinyin' => 'qǐng kè',
                'simplified' => '请客',
                'traditional' => '請客',
                'part_of_speech' => 'verb',
                'meaning' => 'To treat someone / To stand treat',
                'meaning_zh' => '请客',
                'example_sentence' => '我请客。',
                'example_translation' => 'It\'s my treat.',
                'definition' => 'To treat someone, to stand treat',
                'sentences' => ['___吃饭。', '今天我___。', '___送礼。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '干杯',
                'pinyin' => 'gān bēi',
                'simplified' => '干杯',
                'traditional' => '乾杯',
                'part_of_speech' => 'verb',
                'meaning' => 'To toast / Cheers / Bottoms up',
                'meaning_zh' => '干杯',
                'example_sentence' => '为友谊干杯。',
                'example_translation' => 'Toast to friendship.',
                'definition' => 'To toast, cheers, bottoms up',
                'sentences' => ['___！', '___祝酒。', '一起___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '结账',
                'pinyin' => 'jié zhàng',
                'simplified' => '结账',
                'traditional' => '結賬',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay the bill / To settle accounts',
                'meaning_zh' => '结账',
                'example_sentence' => '请结账。',
                'example_translation' => 'Check, please.',
                'definition' => 'To pay the bill, to settle accounts',
                'sentences' => ['___买单。', '___台。', '___了。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '小费',
                'pinyin' => 'xiǎo fèi',
                'simplified' => '小费',
                'traditional' => '小費',
                'part_of_speech' => 'noun',
                'meaning' => 'Tip / Gratuity',
                'meaning_zh' => '小费',
                'example_sentence' => '给小费。',
                'example_translation' => 'Give a tip.',
                'definition' => 'Tip, gratuity',
                'sentences' => ['___制度。', '___多少。', '___文化。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 109,
                'word' => '饮食',
                'pinyin' => 'yǐn shí',
                'simplified' => '饮食',
                'traditional' => '飲食',
                'part_of_speech' => 'noun',
                'meaning' => 'Food and drink / Diet',
                'meaning_zh' => '饮食',
                'example_sentence' => '饮食习惯。',
                'example_translation' => 'Eating habits.',
                'definition' => 'Food and drink, diet',
                'sentences' => ['___健康。', '___文化。', '___均衡。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 110: Opinion Expression (观点表达) - 20 words
        $opinionVocab = [
            [
                'topic_id' => 110,
                'word' => '认为',
                'pinyin' => 'rèn wéi',
                'simplified' => '认为',
                'traditional' => '認為',
                'part_of_speech' => 'verb',
                'meaning' => 'To think / To consider / To believe',
                'meaning_zh' => '认为',
                'example_sentence' => '我认为他对。',
                'example_translation' => 'I think he is right.',
                'definition' => 'To think, to consider, to believe',
                'sentences' => ['___正确。', '___重要。', '___不对。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '觉得',
                'pinyin' => 'jué de',
                'simplified' => '觉得',
                'traditional' => '覺得',
                'part_of_speech' => 'verb',
                'meaning' => 'To feel / To think',
                'meaning_zh' => '觉得',
                'example_sentence' => '我觉得很好。',
                'example_translation' => 'I think it\'s good.',
                'definition' => 'To feel, to think',
                'sentences' => ['___怎么样。', '___不错。', '___对吗。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '看法',
                'pinyin' => 'kàn fǎ',
                'simplified' => '看法',
                'traditional' => '看法',
                'part_of_speech' => 'noun',
                'meaning' => 'View / Opinion',
                'meaning_zh' => '看法',
                'example_sentence' => '你的看法呢？',
                'example_translation' => 'What\'s your opinion?',
                'definition' => 'View, opinion',
                'sentences' => ['___不同。', '___一致。', '___正确。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '想法',
                'pinyin' => 'xiǎng fǎ',
                'simplified' => '想法',
                'traditional' => '想法',
                'part_of_speech' => 'noun',
                'meaning' => 'Idea / Thought / Opinion',
                'meaning_zh' => '想法',
                'example_sentence' => '好想法。',
                'example_translation' => 'Good idea.',
                'definition' => 'Idea, thought, opinion',
                'sentences' => ['___独特。', '___很多。', '___改变。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '主张',
                'pinyin' => 'zhǔ zhāng',
                'simplified' => '主张',
                'traditional' => '主張',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To advocate / To stand for / View',
                'meaning_zh' => '主张',
                'example_sentence' => '我主张和平。',
                'example_translation' => 'I advocate peace.',
                'definition' => 'To advocate, to stand for, view',
                'sentences' => ['___自由。', '___正义。', '___明确。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '赞成',
                'pinyin' => 'zàn chéng',
                'simplified' => '赞成',
                'traditional' => '贊成',
                'part_of_speech' => 'verb',
                'meaning' => 'To approve / To agree / To support',
                'meaning_zh' => '赞成',
                'example_sentence' => '我赞成你的意见。',
                'example_translation' => 'I agree with your opinion.',
                'definition' => 'To approve, to agree, to support',
                'sentences' => ['___提议。', '___决定。', '___率。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '反对',
                'pinyin' => 'fǎn duì',
                'simplified' => '反对',
                'traditional' => '反對',
                'part_of_speech' => 'verb',
                'meaning' => 'To oppose / To be against',
                'meaning_zh' => '反对',
                'example_sentence' => '我反对这个计划。',
                'example_translation' => 'I oppose this plan.',
                'definition' => 'To oppose, to be against',
                'sentences' => ['___意见。', '___党。', '___声。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '同意',
                'pinyin' => 'tóng yì',
                'simplified' => '同意',
                'traditional' => '同意',
                'part_of_speech' => 'verb',
                'meaning' => 'To agree / To consent',
                'meaning_zh' => '同意',
                'example_sentence' => '我同意你的看法。',
                'example_translation' => 'I agree with your view.',
                'definition' => 'To agree, to consent, to approve',
                'sentences' => ['___书。', '___了。', '不___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '否定',
                'pinyin' => 'fǒu dìng',
                'simplified' => '否定',
                'traditional' => '否定',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To negate / Negative',
                'meaning_zh' => '否定',
                'example_sentence' => '否定观点。',
                'example_translation' => 'Negate the viewpoint.',
                'definition' => 'To negate, negative, to deny',
                'sentences' => ['___回答。', '___态度。', '___了。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '肯定',
                'pinyin' => 'kěn dìng',
                'simplified' => '肯定',
                'traditional' => '肯定',
                'part_of_speech' => 'verb/adjective/adverb',
                'meaning' => 'To affirm / Positive / Definitely',
                'meaning_zh' => '肯定',
                'example_sentence' => '肯定会成功。',
                'example_translation' => 'Will definitely succeed.',
                'definition' => 'To affirm, positive, definitely, certain',
                'sentences' => ['___回答。', '___的。', '___态度。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '强调',
                'pinyin' => 'qiáng diào',
                'simplified' => '强调',
                'traditional' => '強調',
                'part_of_speech' => 'verb',
                'meaning' => 'To emphasize / To stress',
                'meaning_zh' => '强调',
                'example_sentence' => '强调重要性。',
                'example_translation' => 'Emphasize the importance.',
                'definition' => 'To emphasize, to stress, to underline',
                'sentences' => ['___一下。', '___指出。', '___了。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '批评',
                'pinyin' => 'pī píng',
                'simplified' => '批评',
                'traditional' => '批評',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To criticize / Criticism',
                'meaning_zh' => '批评',
                'example_sentence' => '接受批评。',
                'example_translation' => 'Accept criticism.',
                'definition' => 'To criticize, criticism',
                'sentences' => ['___教育。', '___他。', '___意见。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '表扬',
                'pinyin' => 'biǎo yáng',
                'simplified' => '表扬',
                'traditional' => '表揚',
                'part_of_speech' => 'verb',
                'meaning' => 'To praise / To commend',
                'meaning_zh' => '表扬',
                'example_sentence' => '受到表扬。',
                'example_translation' => 'Receive praise.',
                'definition' => 'To praise, to commend',
                'sentences' => ['___他。', '___信。', '___大会。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '怀疑',
                'pinyin' => 'huái yí',
                'simplified' => '怀疑',
                'traditional' => '懷疑',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To doubt / To suspect / Doubt',
                'meaning_zh' => '怀疑',
                'example_sentence' => '我怀疑他。',
                'example_translation' => 'I doubt him.',
                'definition' => 'To doubt, to suspect, doubt, suspicion',
                'sentences' => ['___态度。', '___对象。', '___了。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '相信',
                'pinyin' => 'xiāng xìn',
                'simplified' => '相信',
                'traditional' => '相信',
                'part_of_speech' => 'verb',
                'meaning' => 'To believe / To trust',
                'meaning_zh' => '相信',
                'example_sentence' => '我相信你。',
                'example_translation' => 'I believe you.',
                'definition' => 'To believe, to trust, to have faith in',
                'sentences' => ['___自己。', '___他。', '___不疑。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '证明',
                'pinyin' => 'zhèng míng',
                'simplified' => '证明',
                'traditional' => '證明',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To prove / Proof / Certificate',
                'meaning_zh' => '证明',
                'example_sentence' => '证明清白。',
                'example_translation' => 'Prove innocence.',
                'definition' => 'To prove, proof, certificate',
                'sentences' => ['___书。', '___了。', '___材料。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '判断',
                'pinyin' => 'pàn duàn',
                'simplified' => '判断',
                'traditional' => '判斷',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To judge / To determine / Judgment',
                'meaning_zh' => '判断',
                'example_sentence' => '做出判断。',
                'example_translation' => 'Make a judgment.',
                'definition' => 'To judge, to determine, judgment',
                'sentences' => ['___力。', '___标准。', '___正确。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '估计',
                'pinyin' => 'gū jì',
                'simplified' => '估计',
                'traditional' => '估計',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To estimate / To reckon / Estimate',
                'meaning_zh' => '估计',
                'example_sentence' => '估计时间。',
                'example_translation' => 'Estimate time.',
                'definition' => 'To estimate, to reckon, estimate',
                'sentences' => ['___价值。', '___数量。', '___不足。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '预测',
                'pinyin' => 'yù cè',
                'simplified' => '预测',
                'traditional' => '預測',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To predict / To forecast / Prediction',
                'meaning_zh' => '预测',
                'example_sentence' => '天气预测。',
                'example_translation' => 'Weather forecast.',
                'definition' => 'To predict, to forecast, prediction',
                'sentences' => ['___结果。', '___准确。', '___未来。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 110,
                'word' => '假设',
                'pinyin' => 'jiǎ shè',
                'simplified' => '假设',
                'traditional' => '假設',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To suppose / To assume / Hypothesis',
                'meaning_zh' => '假设',
                'example_sentence' => '假设条件。',
                'example_translation' => 'Suppose conditions.',
                'definition' => 'To suppose, to assume, hypothesis',
                'sentences' => ['___如果。', '___情况。', '___理论。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 111: Reasoning and Logic (推理和逻辑) - 20 words
        $reasoningVocab = [
            [
                'topic_id' => 111,
                'word' => '因此',
                'pinyin' => 'yīn cǐ',
                'simplified' => '因此',
                'traditional' => '因此',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Therefore / Thus / Consequently',
                'meaning_zh' => '因此',
                'example_sentence' => '因此我们要努力。',
                'example_translation' => 'Therefore we must work hard.',
                'definition' => 'Therefore, thus, consequently',
                'sentences' => ['___得出。', '___结论。', '___推断。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '所以',
                'pinyin' => 'suǒ yǐ',
                'simplified' => '所以',
                'traditional' => '所以',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Therefore / So',
                'meaning_zh' => '所以',
                'example_sentence' => '所以要小心。',
                'example_translation' => 'So be careful.',
                'definition' => 'Therefore, so, as a result',
                'sentences' => ['___说。', '___我。', '___才。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '因为',
                'pinyin' => 'yīn wèi',
                'simplified' => '因为',
                'traditional' => '因為',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Because / Since',
                'meaning_zh' => '因为',
                'example_sentence' => '因为下雨。',
                'example_translation' => 'Because it\'s raining.',
                'definition' => 'Because, since, as',
                'sentences' => ['___所以。', '___原因。', '___这个。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '原因',
                'pinyin' => 'yuán yīn',
                'simplified' => '原因',
                'traditional' => '原因',
                'part_of_speech' => 'noun',
                'meaning' => 'Reason / Cause',
                'meaning_zh' => '原因',
                'example_sentence' => '主要原因。',
                'example_translation' => 'Main reason.',
                'definition' => 'Reason, cause',
                'sentences' => ['___分析。', '___很多。', '___是。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '结果',
                'pinyin' => 'jié guǒ',
                'simplified' => '结果',
                'traditional' => '結果',
                'part_of_speech' => 'noun/conjunction',
                'meaning' => 'Result / Outcome / As a result',
                'meaning_zh' => '结果',
                'example_sentence' => '好结果。',
                'example_translation' => 'Good result.',
                'definition' => 'Result, outcome, as a result',
                'sentences' => ['___显示。', '___如何。', '___是。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '结论',
                'pinyin' => 'jié lùn',
                'simplified' => '结论',
                'traditional' => '結論',
                'part_of_speech' => 'noun',
                'meaning' => 'Conclusion',
                'meaning_zh' => '结论',
                'example_sentence' => '得出结论。',
                'example_translation' => 'Draw a conclusion.',
                'definition' => 'Conclusion',
                'sentences' => ['___是。', '___正确。', '下___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '如果',
                'pinyin' => 'rú guǒ',
                'simplified' => '如果',
                'traditional' => '如果',
                'part_of_speech' => 'conjunction',
                'meaning' => 'If',
                'meaning_zh' => '如果',
                'example_sentence' => '如果下雨。',
                'example_translation' => 'If it rains.',
                'definition' => 'If, in case, supposing',
                'sentences' => ['___的话。', '___可以。', '___不。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '否则',
                'pinyin' => 'fǒu zé',
                'simplified' => '否则',
                'traditional' => '否則',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Otherwise / Or else',
                'meaning_zh' => '否则',
                'example_sentence' => '快走，否则迟到。',
                'example_translation' => 'Hurry, or else we\'ll be late.',
                'definition' => 'Otherwise, or else, if not',
                'sentences' => ['___就。', '___的话。', '___会。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '虽然',
                'pinyin' => 'suī rán',
                'simplified' => '虽然',
                'traditional' => '雖然',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Although / Though',
                'meaning_zh' => '虽然',
                'example_sentence' => '虽然累但高兴。',
                'example_translation' => 'Although tired but happy.',
                'definition' => 'Although, though, even though',
                'sentences' => ['___但是。', '___可是。', '___如此。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '但是',
                'pinyin' => 'dàn shì',
                'simplified' => '但是',
                'traditional' => '但是',
                'part_of_speech' => 'conjunction',
                'meaning' => 'But / However',
                'meaning_zh' => '但是',
                'example_sentence' => '很难但是可能。',
                'example_translation' => 'Difficult but possible.',
                'definition' => 'But, however, yet',
                'sentences' => ['___我。', '___还是。', '___不。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '然而',
                'pinyin' => 'rán ér',
                'simplified' => '然而',
                'traditional' => '然而',
                'part_of_speech' => 'conjunction',
                'meaning' => 'However / Yet / Nevertheless',
                'meaning_zh' => '然而',
                'example_sentence' => '然而事实并非如此。',
                'example_translation' => 'However, the fact is not so.',
                'definition' => 'However, yet, nevertheless',
                'sentences' => ['___并非。', '___事实。', '___结果。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '无论',
                'pinyin' => 'wú lùn',
                'simplified' => '无论',
                'traditional' => '無論',
                'part_of_speech' => 'conjunction',
                'meaning' => 'No matter / Regardless of',
                'meaning_zh' => '无论',
                'example_sentence' => '无论如何。',
                'example_translation' => 'No matter what.',
                'definition' => 'No matter, regardless of',
                'sentences' => ['___怎样。', '___是。', '___都。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '除非',
                'pinyin' => 'chú fēi',
                'simplified' => '除非',
                'traditional' => '除非',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Unless / Only if',
                'meaning_zh' => '除非',
                'example_sentence' => '除非你同意。',
                'example_translation' => 'Unless you agree.',
                'definition' => 'Unless, only if',
                'sentences' => ['___否则。', '___才。', '___不然。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '尽管',
                'pinyin' => 'jǐn guǎn',
                'simplified' => '尽管',
                'traditional' => '儘管',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Despite / Although / Even though',
                'meaning_zh' => '尽管',
                'example_sentence' => '尽管困难还是坚持。',
                'example_translation' => 'Despite difficulties still persist.',
                'definition' => 'Despite, although, even though',
                'sentences' => ['___如此。', '___但是。', '___这样。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '既然',
                'pinyin' => 'jì rán',
                'simplified' => '既然',
                'traditional' => '既然',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Since / Now that',
                'meaning_zh' => '既然',
                'example_sentence' => '既然来了就坐吧。',
                'example_translation' => 'Since you\'re here, sit down.',
                'definition' => 'Since, now that, as',
                'sentences' => ['___那么。', '___就。', '___如此。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '由于',
                'pinyin' => 'yóu yú',
                'simplified' => '由于',
                'traditional' => '由於',
                'part_of_speech' => 'preposition',
                'meaning' => 'Due to / Owing to / Because of',
                'meaning_zh' => '由于',
                'example_sentence' => '由于下雨取消。',
                'example_translation' => 'Canceled due to rain.',
                'definition' => 'Due to, owing to, because of',
                'sentences' => ['___原因。', '___这个。', '___缺乏。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '根据',
                'pinyin' => 'gēn jù',
                'simplified' => '根据',
                'traditional' => '根據',
                'part_of_speech' => 'preposition/noun',
                'meaning' => 'According to / Based on / Basis',
                'meaning_zh' => '根据',
                'example_sentence' => '根据事实。',
                'example_translation' => 'According to facts.',
                'definition' => 'According to, based on, basis',
                'sentences' => ['___资料。', '___分析。', '___地。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '于是',
                'pinyin' => 'yú shì',
                'simplified' => '于是',
                'traditional' => '於是',
                'part_of_speech' => 'conjunction',
                'meaning' => 'Thereupon / Hence / Then',
                'meaning_zh' => '于是',
                'example_sentence' => '于是决定去。',
                'example_translation' => 'Thereupon decided to go.',
                'definition' => 'Thereupon, hence, then, consequently',
                'sentences' => ['___他。', '___我们。', '___就。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '可见',
                'pinyin' => 'kě jiàn',
                'simplified' => '可见',
                'traditional' => '可見',
                'part_of_speech' => 'adverb',
                'meaning' => 'It\'s obvious / Clearly',
                'meaning_zh' => '可见',
                'example_sentence' => '可见其重要性。',
                'example_translation' => 'Obviously important.',
                'definition' => 'It\'s obvious, clearly, evidently',
                'sentences' => ['___一斑。', '由此___。', '___得。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 111,
                'word' => '显然',
                'pinyin' => 'xiǎn rán',
                'simplified' => '显然',
                'traditional' => '顯然',
                'part_of_speech' => 'adverb',
                'meaning' => 'Obviously / Evidently / Clearly',
                'meaning_zh' => '显然',
                'example_sentence' => '显然不对。',
                'example_translation' => 'Obviously wrong.',
                'definition' => 'Obviously, evidently, clearly',
                'sentences' => ['___是。', '___的。', '___错误。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 112: Description and Comparison (描述和比较) - 20 words
        $descriptionVocab = [
            [
                'topic_id' => 112,
                'word' => '描述',
                'pinyin' => 'miáo shù',
                'simplified' => '描述',
                'traditional' => '描述',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To describe / Description',
                'meaning_zh' => '描述',
                'example_sentence' => '详细描述。',
                'example_translation' => 'Describe in detail.',
                'definition' => 'To describe, description',
                'sentences' => ['___情况。', '___过程。', '___准确。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '形容',
                'pinyin' => 'xíng róng',
                'simplified' => '形容',
                'traditional' => '形容',
                'part_of_speech' => 'verb',
                'meaning' => 'To describe / To depict',
                'meaning_zh' => '形容',
                'example_sentence' => '形容美丽。',
                'example_translation' => 'Describe as beautiful.',
                'definition' => 'To describe, to depict',
                'sentences' => ['___词。', '___不出。', '___生动。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '比较',
                'pinyin' => 'bǐ jiào',
                'simplified' => '比较',
                'traditional' => '比較',
                'part_of_speech' => 'verb/adverb',
                'meaning' => 'To compare / Comparatively / Rather',
                'meaning_zh' => '比较',
                'example_sentence' => '比较一下。',
                'example_translation' => 'Compare.',
                'definition' => 'To compare, comparatively, rather',
                'sentences' => ['___好。', '___大。', '___分析。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '对比',
                'pinyin' => 'duì bǐ',
                'simplified' => '对比',
                'traditional' => '對比',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To contrast / Contrast / Comparison',
                'meaning_zh' => '对比',
                'example_sentence' => '形成对比。',
                'example_translation' => 'Form a contrast.',
                'definition' => 'To contrast, contrast, comparison',
                'sentences' => ['___鲜明。', '___分析。', '___度。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '相似',
                'pinyin' => 'xiāng sì',
                'simplified' => '相似',
                'traditional' => '相似',
                'part_of_speech' => 'adjective',
                'meaning' => 'Similar / Alike',
                'meaning_zh' => '相似',
                'example_sentence' => '非常相似。',
                'example_translation' => 'Very similar.',
                'definition' => 'Similar, alike, resembling',
                'sentences' => ['___度。', '___之处。', '___性。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '差异',
                'pinyin' => 'chā yì',
                'simplified' => '差异',
                'traditional' => '差異',
                'part_of_speech' => 'noun',
                'meaning' => 'Difference / Discrepancy',
                'meaning_zh' => '差异',
                'example_sentence' => '文化差异。',
                'example_translation' => 'Cultural difference.',
                'definition' => 'Difference, discrepancy, diversity',
                'sentences' => ['___很大。', '___性。', '___分析。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '不同',
                'pinyin' => 'bù tóng',
                'simplified' => '不同',
                'traditional' => '不同',
                'part_of_speech' => 'adjective',
                'meaning' => 'Different / Not the same',
                'meaning_zh' => '不同',
                'example_sentence' => '完全不同。',
                'example_translation' => 'Completely different.',
                'definition' => 'Different, not the same, distinct',
                'sentences' => ['___点。', '___的。', '___之处。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '相同',
                'pinyin' => 'xiāng tóng',
                'simplified' => '相同',
                'traditional' => '相同',
                'part_of_speech' => 'adjective',
                'meaning' => 'Same / Identical',
                'meaning_zh' => '相同',
                'example_sentence' => '完全相同。',
                'example_translation' => 'Exactly the same.',
                'definition' => 'Same, identical',
                'sentences' => ['___点。', '___的。', '___之处。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '特点',
                'pinyin' => 'tè diǎn',
                'simplified' => '特点',
                'traditional' => '特點',
                'part_of_speech' => 'noun',
                'meaning' => 'Characteristic / Feature',
                'meaning_zh' => '特点',
                'example_sentence' => '主要特点。',
                'example_translation' => 'Main characteristics.',
                'definition' => 'Characteristic, feature, trait',
                'sentences' => ['___鲜明。', '___是。', '___分析。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '特征',
                'pinyin' => 'tè zhēng',
                'simplified' => '特征',
                'traditional' => '特徵',
                'part_of_speech' => 'noun',
                'meaning' => 'Feature / Characteristic / Trait',
                'meaning_zh' => '特征',
                'example_sentence' => '明显特征。',
                'example_translation' => 'Obvious features.',
                'definition' => 'Feature, characteristic, trait',
                'sentences' => ['___值。', '___识别。', '___明显。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '性质',
                'pinyin' => 'xìng zhì',
                'simplified' => '性质',
                'traditional' => '性質',
                'part_of_speech' => 'noun',
                'meaning' => 'Nature / Character / Property',
                'meaning_zh' => '性质',
                'example_sentence' => '问题性质。',
                'example_translation' => 'Nature of problem.',
                'definition' => 'Nature, character, property',
                'sentences' => ['___不同。', '___严重。', '___恶劣。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '程度',
                'pinyin' => 'chéng dù',
                'simplified' => '程度',
                'traditional' => '程度',
                'part_of_speech' => 'noun',
                'meaning' => 'Degree / Level / Extent',
                'meaning_zh' => '程度',
                'example_sentence' => '严重程度。',
                'example_translation' => 'Degree of severity.',
                'definition' => 'Degree, level, extent',
                'sentences' => ['___高。', '___深。', '___不同。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '范围',
                'pinyin' => 'fàn wéi',
                'simplified' => '范围',
                'traditional' => '範圍',
                'part_of_speech' => 'noun',
                'meaning' => 'Range / Scope / Extent',
                'meaning_zh' => '范围',
                'example_sentence' => '广泛范围。',
                'example_translation' => 'Wide range.',
                'definition' => 'Range, scope, extent',
                'sentences' => ['___内。', '___广。', '___限制。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '规模',
                'pinyin' => 'guī mó',
                'simplified' => '规模',
                'traditional' => '規模',
                'part_of_speech' => 'noun',
                'meaning' => 'Scale / Scope / Dimensions',
                'meaning_zh' => '规模',
                'example_sentence' => '大规模。',
                'example_translation' => 'Large scale.',
                'definition' => 'Scale, scope, dimensions',
                'sentences' => ['___宏大。', '___不断扩大。', '___经济。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '优点',
                'pinyin' => 'yōu diǎn',
                'simplified' => '优点',
                'traditional' => '優點',
                'part_of_speech' => 'noun',
                'meaning' => 'Advantage / Merit / Strong point',
                'meaning_zh' => '优点',
                'example_sentence' => '很多优点。',
                'example_translation' => 'Many advantages.',
                'definition' => 'Advantage, merit, strong point',
                'sentences' => ['___和缺点。', '___是。', '___明显。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '趋势',
                'pinyin' => 'qū shì',
                'simplified' => '趋势',
                'traditional' => '趨勢',
                'part_of_speech' => 'noun',
                'meaning' => 'Trend / Tendency',
                'meaning_zh' => '趋势',
                'example_sentence' => '发展趋势。',
                'example_translation' => 'Development trend.',
                'definition' => 'Trend, tendency',
                'sentences' => ['___明显。', '___分析。', '___图。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '现象',
                'pinyin' => 'xiàn xiàng',
                'simplified' => '现象',
                'traditional' => '現象',
                'part_of_speech' => 'noun',
                'meaning' => 'Phenomenon / Appearance',
                'meaning_zh' => '现象',
                'example_sentence' => '普遍现象。',
                'example_translation' => 'Common phenomenon.',
                'definition' => 'Phenomenon, appearance',
                'sentences' => ['___产生。', '___分析。', '___级。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '情况',
                'pinyin' => 'qíng kuàng',
                'simplified' => '情况',
                'traditional' => '情況',
                'part_of_speech' => 'noun',
                'meaning' => 'Situation / Condition / Circumstances',
                'meaning_zh' => '情况',
                'example_sentence' => '了解情况。',
                'example_translation' => 'Understand the situation.',
                'definition' => 'Situation, condition, circumstances',
                'sentences' => ['___说明。', '___介绍。', '___下。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '状态',
                'pinyin' => 'zhuàng tài',
                'simplified' => '状态',
                'traditional' => '狀態',
                'part_of_speech' => 'noun',
                'meaning' => 'State / Condition / Status',
                'meaning_zh' => '状态',
                'example_sentence' => '良好状态。',
                'example_translation' => 'Good condition.',
                'definition' => 'State, condition, status',
                'sentences' => ['___栏。', '___好。', '___不佳。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 112,
                'word' => '例子',
                'pinyin' => 'lì zi',
                'simplified' => '例子',
                'traditional' => '例子',
                'part_of_speech' => 'noun',
                'meaning' => 'Example / Case / Instance',
                'meaning_zh' => '例子',
                'example_sentence' => '举个例子。',
                'example_translation' => 'Give an example.',
                'definition' => 'Example, case, instance',
                'sentences' => ['___说明。', '典型___。', '___很多。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($diningVocab, $opinionVocab, $reasoningVocab, $descriptionVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
