<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics13to16Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 105: Environment and Nature (环境和自然) - 20 words
        $environmentVocab = [
            [
                'topic_id' => 105,
                'word' => '环境',
                'pinyin' => 'huán jìng',
                'simplified' => '环境',
                'traditional' => '環境',
                'part_of_speech' => 'noun',
                'meaning' => 'Environment / Surroundings',
                'meaning_zh' => '环境',
                'example_sentence' => '保护环境。',
                'example_translation' => 'Protect the environment.',
                'definition' => 'Environment, surroundings',
                'sentences' => ['___污染。', '___优美。', '___保护。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '自然',
                'pinyin' => 'zì rán',
                'simplified' => '自然',
                'traditional' => '自然',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Nature / Natural',
                'meaning_zh' => '自然',
                'example_sentence' => '自然环境。',
                'example_translation' => 'Natural environment.',
                'definition' => 'Nature, natural',
                'sentences' => ['___景观。', '___灾害。', '___科学。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '污染',
                'pinyin' => 'wū rǎn',
                'simplified' => '污染',
                'traditional' => '污染',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To pollute / Pollution',
                'meaning_zh' => '污染',
                'example_sentence' => '空气污染。',
                'example_translation' => 'Air pollution.',
                'definition' => 'To pollute, pollution',
                'sentences' => ['___严重。', '___源。', '___物。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '资源',
                'pinyin' => 'zī yuán',
                'simplified' => '资源',
                'traditional' => '資源',
                'part_of_speech' => 'noun',
                'meaning' => 'Resource',
                'meaning_zh' => '资源',
                'example_sentence' => '自然资源。',
                'example_translation' => 'Natural resources.',
                'definition' => 'Resource',
                'sentences' => ['___丰富。', '___利用。', '___共享。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '节约',
                'pinyin' => 'jié yuē',
                'simplified' => '节约',
                'traditional' => '節約',
                'part_of_speech' => 'verb',
                'meaning' => 'To save / To economize',
                'meaning_zh' => '节约',
                'example_sentence' => '节约用水。',
                'example_translation' => 'Save water.',
                'definition' => 'To save, to economize, thrifty',
                'sentences' => ['___能源。', '___资源。', '___型。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '浪费',
                'pinyin' => 'làng fèi',
                'simplified' => '浪费',
                'traditional' => '浪費',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To waste / Waste',
                'meaning_zh' => '浪费',
                'example_sentence' => '不要浪费。',
                'example_translation' => 'Don\'t waste.',
                'definition' => 'To waste, waste, wasteful',
                'sentences' => ['___时间。', '___食物。', '___现象。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '森林',
                'pinyin' => 'sēn lín',
                'simplified' => '森林',
                'traditional' => '森林',
                'part_of_speech' => 'noun',
                'meaning' => 'Forest',
                'meaning_zh' => '森林',
                'example_sentence' => '热带森林。',
                'example_translation' => 'Tropical forest.',
                'definition' => 'Forest',
                'sentences' => ['___公园。', '___资源。', '___保护。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '海洋',
                'pinyin' => 'hǎi yáng',
                'simplified' => '海洋',
                'traditional' => '海洋',
                'part_of_speech' => 'noun',
                'meaning' => 'Ocean / Sea',
                'meaning_zh' => '海洋',
                'example_sentence' => '海洋生物。',
                'example_translation' => 'Marine life.',
                'definition' => 'Ocean, sea',
                'sentences' => ['___污染。', '___资源。', '___保护。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '河流',
                'pinyin' => 'hé liú',
                'simplified' => '河流',
                'traditional' => '河流',
                'part_of_speech' => 'noun',
                'meaning' => 'River',
                'meaning_zh' => '河流',
                'example_sentence' => '长江是大河流。',
                'example_translation' => 'Yangtze is a big river.',
                'definition' => 'River',
                'sentences' => ['___湖泊。', '___污染。', '___治理。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '湖泊',
                'pinyin' => 'hú pō',
                'simplified' => '湖泊',
                'traditional' => '湖泊',
                'part_of_speech' => 'noun',
                'meaning' => 'Lake',
                'meaning_zh' => '湖泊',
                'example_sentence' => '美丽的湖泊。',
                'example_translation' => 'Beautiful lake.',
                'definition' => 'Lake',
                'sentences' => ['___风光。', '___资源。', '___保护。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '山脉',
                'pinyin' => 'shān mài',
                'simplified' => '山脉',
                'traditional' => '山脈',
                'part_of_speech' => 'noun',
                'meaning' => 'Mountain range',
                'meaning_zh' => '山脉',
                'example_sentence' => '喜马拉雅山脉。',
                'example_translation' => 'Himalayan mountain range.',
                'definition' => 'Mountain range, mountains',
                'sentences' => ['___绵延。', '___地区。', '___风景。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '土地',
                'pinyin' => 'tǔ dì',
                'simplified' => '土地',
                'traditional' => '土地',
                'part_of_speech' => 'noun',
                'meaning' => 'Land / Soil',
                'meaning_zh' => '土地',
                'example_sentence' => '耕种土地。',
                'example_translation' => 'Cultivate land.',
                'definition' => 'Land, soil, territory',
                'sentences' => ['___资源。', '___利用。', '___肥沃。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '气候',
                'pinyin' => 'qì hòu',
                'simplified' => '气候',
                'traditional' => '氣候',
                'part_of_speech' => 'noun',
                'meaning' => 'Climate',
                'meaning_zh' => '气候',
                'example_sentence' => '温暖的气候。',
                'example_translation' => 'Warm climate.',
                'definition' => 'Climate',
                'sentences' => ['___变化。', '___条件。', '___温暖。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '灾害',
                'pinyin' => 'zāi hài',
                'simplified' => '灾害',
                'traditional' => '災害',
                'part_of_speech' => 'noun',
                'meaning' => 'Disaster / Calamity',
                'meaning_zh' => '灾害',
                'example_sentence' => '自然灾害。',
                'example_translation' => 'Natural disaster.',
                'definition' => 'Disaster, calamity',
                'sentences' => ['___预防。', '___损失。', '___救援。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '地震',
                'pinyin' => 'dì zhèn',
                'simplified' => '地震',
                'traditional' => '地震',
                'part_of_speech' => 'noun',
                'meaning' => 'Earthquake',
                'meaning_zh' => '地震',
                'example_sentence' => '发生地震。',
                'example_translation' => 'Earthquake occurred.',
                'definition' => 'Earthquake',
                'sentences' => ['___预警。', '___灾区。', '___救援。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '洪水',
                'pinyin' => 'hóng shuǐ',
                'simplified' => '洪水',
                'traditional' => '洪水',
                'part_of_speech' => 'noun',
                'meaning' => 'Flood',
                'meaning_zh' => '洪水',
                'example_sentence' => '洪水来了。',
                'example_translation' => 'The flood came.',
                'definition' => 'Flood, floodwater',
                'sentences' => ['___灾害。', '___防治。', '___泛滥。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '植物',
                'pinyin' => 'zhí wù',
                'simplified' => '植物',
                'traditional' => '植物',
                'part_of_speech' => 'noun',
                'meaning' => 'Plant',
                'meaning_zh' => '植物',
                'example_sentence' => '种植物。',
                'example_translation' => 'Plant plants.',
                'definition' => 'Plant, vegetation',
                'sentences' => ['___园。', '___保护。', '___种类。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '动物',
                'pinyin' => 'dòng wù',
                'simplified' => '动物',
                'traditional' => '動物',
                'part_of_speech' => 'noun',
                'meaning' => 'Animal',
                'meaning_zh' => '动物',
                'example_sentence' => '野生动物。',
                'example_translation' => 'Wild animals.',
                'definition' => 'Animal',
                'sentences' => ['___园。', '___保护。', '___世界。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '野生',
                'pinyin' => 'yě shēng',
                'simplified' => '野生',
                'traditional' => '野生',
                'part_of_speech' => 'adjective',
                'meaning' => 'Wild / Uncultivated',
                'meaning_zh' => '野生',
                'example_sentence' => '野生动物。',
                'example_translation' => 'Wild animals.',
                'definition' => 'Wild, uncultivated',
                'sentences' => ['___植物。', '___资源。', '___保护。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 105,
                'word' => '生态',
                'pinyin' => 'shēng tài',
                'simplified' => '生态',
                'traditional' => '生態',
                'part_of_speech' => 'noun',
                'meaning' => 'Ecology / Ecological',
                'meaning_zh' => '生态',
                'example_sentence' => '生态环境。',
                'example_translation' => 'Ecological environment.',
                'definition' => 'Ecology, ecological',
                'sentences' => ['___平衡。', '___系统。', '___保护。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 106: Transportation and Travel (交通和旅行) - 20 words
        $transportVocab = [
            [
                'topic_id' => 106,
                'word' => '交通',
                'pinyin' => 'jiāo tōng',
                'simplified' => '交通',
                'traditional' => '交通',
                'part_of_speech' => 'noun',
                'meaning' => 'Transportation / Traffic',
                'meaning_zh' => '交通',
                'example_sentence' => '交通便利。',
                'example_translation' => 'Convenient transportation.',
                'definition' => 'Transportation, traffic',
                'sentences' => ['___工具。', '___拥堵。', '___规则。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '旅行',
                'pinyin' => 'lǚ xíng',
                'simplified' => '旅行',
                'traditional' => '旅行',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To travel / Travel / Trip',
                'meaning_zh' => '旅行',
                'example_sentence' => '去旅行。',
                'example_translation' => 'Go traveling.',
                'definition' => 'To travel, travel, trip',
                'sentences' => ['___社。', '___计划。', '___经历。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '旅游',
                'pinyin' => 'lǚ yóu',
                'simplified' => '旅游',
                'traditional' => '旅遊',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To tour / Tourism / Travel',
                'meaning_zh' => '旅游',
                'example_sentence' => '去旅游。',
                'example_translation' => 'Go traveling.',
                'definition' => 'To tour, tourism, travel',
                'sentences' => ['___业。', '___景点。', '___胜地。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '飞机',
                'pinyin' => 'fēi jī',
                'simplified' => '飞机',
                'traditional' => '飛機',
                'part_of_speech' => 'noun',
                'meaning' => 'Airplane / Aircraft',
                'meaning_zh' => '飞机',
                'example_sentence' => '坐飞机。',
                'example_translation' => 'Take a plane.',
                'definition' => 'Airplane, aircraft',
                'sentences' => ['___票。', '___场。', '___起飞。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '火车',
                'pinyin' => 'huǒ chē',
                'simplified' => '火车',
                'traditional' => '火車',
                'part_of_speech' => 'noun',
                'meaning' => 'Train',
                'meaning_zh' => '火车',
                'example_sentence' => '坐火车。',
                'example_translation' => 'Take a train.',
                'definition' => 'Train',
                'sentences' => ['___站。', '___票。', '___时刻表。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '地铁',
                'pinyin' => 'dì tiě',
                'simplified' => '地铁',
                'traditional' => '地鐵',
                'part_of_speech' => 'noun',
                'meaning' => 'Subway / Metro',
                'meaning_zh' => '地铁',
                'example_sentence' => '坐地铁。',
                'example_translation' => 'Take the subway.',
                'definition' => 'Subway, metro, underground',
                'sentences' => ['___站。', '___线。', '___票。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '公交',
                'pinyin' => 'gōng jiāo',
                'simplified' => '公交',
                'traditional' => '公交',
                'part_of_speech' => 'noun',
                'meaning' => 'Public transportation / Bus',
                'meaning_zh' => '公交',
                'example_sentence' => '坐公交车。',
                'example_translation' => 'Take the bus.',
                'definition' => 'Public transportation, bus',
                'sentences' => ['___车。', '___站。', '___卡。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '出租车',
                'pinyin' => 'chū zū chē',
                'simplified' => '出租车',
                'traditional' => '出租車',
                'part_of_speech' => 'noun',
                'meaning' => 'Taxi / Cab',
                'meaning_zh' => '出租车',
                'example_sentence' => '打出租车。',
                'example_translation' => 'Take a taxi.',
                'definition' => 'Taxi, cab',
                'sentences' => ['___司机。', '___费用。', '___站。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '航班',
                'pinyin' => 'háng bān',
                'simplified' => '航班',
                'traditional' => '航班',
                'part_of_speech' => 'noun',
                'meaning' => 'Flight / Scheduled flight',
                'meaning_zh' => '航班',
                'example_sentence' => '航班延误。',
                'example_translation' => 'Flight delayed.',
                'definition' => 'Flight, scheduled flight',
                'sentences' => ['___号。', '___信息。', '___取消。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '机场',
                'pinyin' => 'jī chǎng',
                'simplified' => '机场',
                'traditional' => '機場',
                'part_of_speech' => 'noun',
                'meaning' => 'Airport',
                'meaning_zh' => '机场',
                'example_sentence' => '去机场。',
                'example_translation' => 'Go to airport.',
                'definition' => 'Airport',
                'sentences' => ['___大巴。', '___安检。', '国际___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '车站',
                'pinyin' => 'chē zhàn',
                'simplified' => '车站',
                'traditional' => '車站',
                'part_of_speech' => 'noun',
                'meaning' => 'Station / Bus stop / Train station',
                'meaning_zh' => '车站',
                'example_sentence' => '在车站等。',
                'example_translation' => 'Wait at the station.',
                'definition' => 'Station, bus stop, train station',
                'sentences' => ['___台。', '___大厅。', '___候车。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '售票',
                'pinyin' => 'shòu piào',
                'simplified' => '售票',
                'traditional' => '售票',
                'part_of_speech' => 'verb',
                'meaning' => 'To sell tickets',
                'meaning_zh' => '售票',
                'example_sentence' => '售票处。',
                'example_translation' => 'Ticket office.',
                'definition' => 'To sell tickets',
                'sentences' => ['___窗口。', '___员。', '___时间。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '订票',
                'pinyin' => 'dìng piào',
                'simplified' => '订票',
                'traditional' => '訂票',
                'part_of_speech' => 'verb',
                'meaning' => 'To book a ticket',
                'meaning_zh' => '订票',
                'example_sentence' => '网上订票。',
                'example_translation' => 'Book tickets online.',
                'definition' => 'To book a ticket, to reserve a ticket',
                'sentences' => ['___电话。', '___系统。', '___成功。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '检票',
                'pinyin' => 'jiǎn piào',
                'simplified' => '检票',
                'traditional' => '檢票',
                'part_of_speech' => 'verb',
                'meaning' => 'To check tickets',
                'meaning_zh' => '检票',
                'example_sentence' => '检票进站。',
                'example_translation' => 'Check tickets to enter.',
                'definition' => 'To check tickets, to inspect tickets',
                'sentences' => ['___口。', '___员。', '___时间。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '行李',
                'pinyin' => 'xíng li',
                'simplified' => '行李',
                'traditional' => '行李',
                'part_of_speech' => 'noun',
                'meaning' => 'Luggage / Baggage',
                'meaning_zh' => '行李',
                'example_sentence' => '托运行李。',
                'example_translation' => 'Check luggage.',
                'definition' => 'Luggage, baggage',
                'sentences' => ['___箱。', '___架。', '___托运。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '路线',
                'pinyin' => 'lù xiàn',
                'simplified' => '路线',
                'traditional' => '路線',
                'part_of_speech' => 'noun',
                'meaning' => 'Route / Line',
                'meaning_zh' => '路线',
                'example_sentence' => '旅游路线。',
                'example_translation' => 'Tourist route.',
                'definition' => 'Route, line, itinerary',
                'sentences' => ['___图。', '___规划。', '___选择。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '导游',
                'pinyin' => 'dǎo yóu',
                'simplified' => '导游',
                'traditional' => '導遊',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Tour guide / To guide',
                'meaning_zh' => '导游',
                'example_sentence' => '请导游。',
                'example_translation' => 'Hire a tour guide.',
                'definition' => 'Tour guide, to guide',
                'sentences' => ['___服务。', '___讲解。', '___带团。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '景点',
                'pinyin' => 'jǐng diǎn',
                'simplified' => '景点',
                'traditional' => '景點',
                'part_of_speech' => 'noun',
                'meaning' => 'Scenic spot / Tourist attraction',
                'meaning_zh' => '景点',
                'example_sentence' => '著名景点。',
                'example_translation' => 'Famous scenic spot.',
                'definition' => 'Scenic spot, tourist attraction',
                'sentences' => ['___门票。', '___介绍。', '___游览。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '风景',
                'pinyin' => 'fēng jǐng',
                'simplified' => '风景',
                'traditional' => '風景',
                'part_of_speech' => 'noun',
                'meaning' => 'Scenery / Landscape',
                'meaning_zh' => '风景',
                'example_sentence' => '美丽的风景。',
                'example_translation' => 'Beautiful scenery.',
                'definition' => 'Scenery, landscape, view',
                'sentences' => ['___优美。', '___区。', '___如画。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 106,
                'word' => '纪念',
                'pinyin' => 'jì niàn',
                'simplified' => '纪念',
                'traditional' => '紀念',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To commemorate / Memorial',
                'meaning_zh' => '纪念',
                'example_sentence' => '纪念品。',
                'example_translation' => 'Souvenir.',
                'definition' => 'To commemorate, memorial, souvenir',
                'sentences' => ['___馆。', '___日。', '___意义。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 107: Accommodation and Hotels (住宿和酒店) - 20 words
        $accommodationVocab = [
            [
                'topic_id' => 107,
                'word' => '酒店',
                'pinyin' => 'jiǔ diàn',
                'simplified' => '酒店',
                'traditional' => '酒店',
                'part_of_speech' => 'noun',
                'meaning' => 'Hotel',
                'meaning_zh' => '酒店',
                'example_sentence' => '住酒店。',
                'example_translation' => 'Stay at a hotel.',
                'definition' => 'Hotel',
                'sentences' => ['___管理。', '___预订。', '___服务。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '宾馆',
                'pinyin' => 'bīn guǎn',
                'simplified' => '宾馆',
                'traditional' => '賓館',
                'part_of_speech' => 'noun',
                'meaning' => 'Hotel / Guesthouse',
                'meaning_zh' => '宾馆',
                'example_sentence' => '住宾馆。',
                'example_translation' => 'Stay at a hotel.',
                'definition' => 'Hotel, guesthouse',
                'sentences' => ['___房间。', '___前台。', '___服务。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '旅馆',
                'pinyin' => 'lǚ guǎn',
                'simplified' => '旅馆',
                'traditional' => '旅館',
                'part_of_speech' => 'noun',
                'meaning' => 'Hotel / Inn',
                'meaning_zh' => '旅馆',
                'example_sentence' => '小旅馆。',
                'example_translation' => 'Small inn.',
                'definition' => 'Hotel, inn, lodging house',
                'sentences' => ['___老板。', '___住宿。', '___价格。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '预订',
                'pinyin' => 'yù dìng',
                'simplified' => '预订',
                'traditional' => '預訂',
                'part_of_speech' => 'verb',
                'meaning' => 'To reserve / To book',
                'meaning_zh' => '预订',
                'example_sentence' => '预订房间。',
                'example_translation' => 'Reserve a room.',
                'definition' => 'To reserve, to book',
                'sentences' => ['___酒店。', '___系统。', '___成功。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '登记',
                'pinyin' => 'dēng jì',
                'simplified' => '登记',
                'traditional' => '登記',
                'part_of_speech' => 'verb',
                'meaning' => 'To register / To check in',
                'meaning_zh' => '登记',
                'example_sentence' => '办理登记。',
                'example_translation' => 'Complete registration.',
                'definition' => 'To register, to check in',
                'sentences' => ['___手续。', '___表。', '___信息。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '入住',
                'pinyin' => 'rù zhù',
                'simplified' => '入住',
                'traditional' => '入住',
                'part_of_speech' => 'verb',
                'meaning' => 'To check in / To move in',
                'meaning_zh' => '入住',
                'example_sentence' => '办理入住。',
                'example_translation' => 'Check in.',
                'definition' => 'To check in, to move in',
                'sentences' => ['___时间。', '___手续。', '___酒店。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '退房',
                'pinyin' => 'tuì fáng',
                'simplified' => '退房',
                'traditional' => '退房',
                'part_of_speech' => 'verb',
                'meaning' => 'To check out',
                'meaning_zh' => '退房',
                'example_sentence' => '办理退房。',
                'example_translation' => 'Check out.',
                'definition' => 'To check out',
                'sentences' => ['___时间。', '___手续。', '___前。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '房间',
                'pinyin' => 'fáng jiān',
                'simplified' => '房间',
                'traditional' => '房間',
                'part_of_speech' => 'noun',
                'meaning' => 'Room',
                'meaning_zh' => '房间',
                'example_sentence' => '打扫房间。',
                'example_translation' => 'Clean the room.',
                'definition' => 'Room',
                'sentences' => ['___号。', '___钥匙。', '___服务。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '单人间',
                'pinyin' => 'dān rén jiān',
                'simplified' => '单人间',
                'traditional' => '單人間',
                'part_of_speech' => 'noun',
                'meaning' => 'Single room',
                'meaning_zh' => '单人间',
                'example_sentence' => '订单人间。',
                'example_translation' => 'Book a single room.',
                'definition' => 'Single room',
                'sentences' => ['___价格。', '___预订。', '一个___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '双人间',
                'pinyin' => 'shuāng rén jiān',
                'simplified' => '双人间',
                'traditional' => '雙人間',
                'part_of_speech' => 'noun',
                'meaning' => 'Double room',
                'meaning_zh' => '双人间',
                'example_sentence' => '订双人间。',
                'example_translation' => 'Book a double room.',
                'definition' => 'Double room',
                'sentences' => ['___标准间。', '___预订。', '一个___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '套间',
                'pinyin' => 'tào jiān',
                'simplified' => '套间',
                'traditional' => '套間',
                'part_of_speech' => 'noun',
                'meaning' => 'Suite',
                'meaning_zh' => '套间',
                'example_sentence' => '豪华套间。',
                'example_translation' => 'Luxury suite.',
                'definition' => 'Suite',
                'sentences' => ['总统___。', '___房。', '___价格。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '前台',
                'pinyin' => 'qián tái',
                'simplified' => '前台',
                'traditional' => '前台',
                'part_of_speech' => 'noun',
                'meaning' => 'Front desk / Reception',
                'meaning_zh' => '前台',
                'example_sentence' => '去前台。',
                'example_translation' => 'Go to the front desk.',
                'definition' => 'Front desk, reception',
                'sentences' => ['___服务。', '___咨询。', '___接待。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '服务员',
                'pinyin' => 'fú wù yuán',
                'simplified' => '服务员',
                'traditional' => '服務員',
                'part_of_speech' => 'noun',
                'meaning' => 'Waiter / Waitress / Attendant',
                'meaning_zh' => '服务员',
                'example_sentence' => '叫服务员。',
                'example_translation' => 'Call the attendant.',
                'definition' => 'Waiter, waitress, attendant',
                'sentences' => ['___态度。', '___服务。', '___小费。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '设施',
                'pinyin' => 'shè shī',
                'simplified' => '设施',
                'traditional' => '設施',
                'part_of_speech' => 'noun',
                'meaning' => 'Facility / Installation',
                'meaning_zh' => '设施',
                'example_sentence' => '完善的设施。',
                'example_translation' => 'Complete facilities.',
                'definition' => 'Facility, installation, equipment',
                'sentences' => ['___齐全。', '___建设。', '___完备。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '空调',
                'pinyin' => 'kōng tiáo',
                'simplified' => '空调',
                'traditional' => '空調',
                'part_of_speech' => 'noun',
                'meaning' => 'Air conditioner / Air conditioning',
                'meaning_zh' => '空调',
                'example_sentence' => '开空调。',
                'example_translation' => 'Turn on air conditioning.',
                'definition' => 'Air conditioner, air conditioning',
                'sentences' => ['___房间。', '___温度。', '___系统。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '电梯',
                'pinyin' => 'diàn tī',
                'simplified' => '电梯',
                'traditional' => '電梯',
                'part_of_speech' => 'noun',
                'meaning' => 'Elevator / Lift',
                'meaning_zh' => '电梯',
                'example_sentence' => '坐电梯。',
                'example_translation' => 'Take the elevator.',
                'definition' => 'Elevator, lift',
                'sentences' => ['___口。', '___按钮。', '___上楼。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '早餐',
                'pinyin' => 'zǎo cān',
                'simplified' => '早餐',
                'traditional' => '早餐',
                'part_of_speech' => 'noun',
                'meaning' => 'Breakfast',
                'meaning_zh' => '早餐',
                'example_sentence' => '吃早餐。',
                'example_translation' => 'Eat breakfast.',
                'definition' => 'Breakfast',
                'sentences' => ['___时间。', '___券。', '___自助餐。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '押金',
                'pinyin' => 'yā jīn',
                'simplified' => '押金',
                'traditional' => '押金',
                'part_of_speech' => 'noun',
                'meaning' => 'Deposit',
                'meaning_zh' => '押金',
                'example_sentence' => '交押金。',
                'example_translation' => 'Pay deposit.',
                'definition' => 'Deposit',
                'sentences' => ['___退还。', '___收据。', '___金额。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '钥匙',
                'pinyin' => 'yào shi',
                'simplified' => '钥匙',
                'traditional' => '鑰匙',
                'part_of_speech' => 'noun',
                'meaning' => 'Key',
                'meaning_zh' => '钥匙',
                'example_sentence' => '房间钥匙。',
                'example_translation' => 'Room key.',
                'definition' => 'Key',
                'sentences' => ['___卡。', '___丢了。', '___归还。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 107,
                'word' => '舒适',
                'pinyin' => 'shū shì',
                'simplified' => '舒适',
                'traditional' => '舒適',
                'part_of_speech' => 'adjective',
                'meaning' => 'Comfortable / Cozy',
                'meaning_zh' => '舒适',
                'example_sentence' => '舒适的房间。',
                'example_translation' => 'Comfortable room.',
                'definition' => 'Comfortable, cozy',
                'sentences' => ['___度。', '___环境。', '___感。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 108: Shopping and Consumption (购物和消费) - 20 words
        $shoppingVocab = [
            [
                'topic_id' => 108,
                'word' => '购物',
                'pinyin' => 'gòu wù',
                'simplified' => '购物',
                'traditional' => '購物',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To shop / Shopping',
                'meaning_zh' => '购物',
                'example_sentence' => '去购物。',
                'example_translation' => 'Go shopping.',
                'definition' => 'To shop, shopping',
                'sentences' => ['___中心。', '___车。', '___袋。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '消费',
                'pinyin' => 'xiāo fèi',
                'simplified' => '消费',
                'traditional' => '消費',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To consume / Consumption',
                'meaning_zh' => '消费',
                'example_sentence' => '消费水平。',
                'example_translation' => 'Consumption level.',
                'definition' => 'To consume, consumption, spending',
                'sentences' => ['___者。', '___观念。', '___能力。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '商场',
                'pinyin' => 'shāng chǎng',
                'simplified' => '商场',
                'traditional' => '商場',
                'part_of_speech' => 'noun',
                'meaning' => 'Shopping mall / Market',
                'meaning_zh' => '商场',
                'example_sentence' => '逛商场。',
                'example_translation' => 'Go to the mall.',
                'definition' => 'Shopping mall, market',
                'sentences' => ['___购物。', '___打折。', '大型___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '超市',
                'pinyin' => 'chāo shì',
                'simplified' => '超市',
                'traditional' => '超市',
                'part_of_speech' => 'noun',
                'meaning' => 'Supermarket',
                'meaning_zh' => '超市',
                'example_sentence' => '去超市。',
                'example_translation' => 'Go to the supermarket.',
                'definition' => 'Supermarket',
                'sentences' => ['___购物。', '___促销。', '___收银。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '商品',
                'pinyin' => 'shāng pǐn',
                'simplified' => '商品',
                'traditional' => '商品',
                'part_of_speech' => 'noun',
                'meaning' => 'Commodity / Goods / Merchandise',
                'meaning_zh' => '商品',
                'example_sentence' => '商品种类。',
                'example_translation' => 'Variety of goods.',
                'definition' => 'Commodity, goods, merchandise',
                'sentences' => ['___质量。', '___价格。', '___丰富。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '价格',
                'pinyin' => 'jià gé',
                'simplified' => '价格',
                'traditional' => '價格',
                'part_of_speech' => 'noun',
                'meaning' => 'Price',
                'meaning_zh' => '价格',
                'example_sentence' => '价格合理。',
                'example_translation' => 'Reasonable price.',
                'definition' => 'Price',
                'sentences' => ['___便宜。', '___昂贵。', '___标签。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '打折',
                'pinyin' => 'dǎ zhé',
                'simplified' => '打折',
                'traditional' => '打折',
                'part_of_speech' => 'verb',
                'meaning' => 'To give a discount / On sale',
                'meaning_zh' => '打折',
                'example_sentence' => '商品打折。',
                'example_translation' => 'Goods on sale.',
                'definition' => 'To give a discount, on sale',
                'sentences' => ['___促销。', '___季。', '___商品。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '优惠',
                'pinyin' => 'yōu huì',
                'simplified' => '优惠',
                'traditional' => '優惠',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Preferential / Discount / Favorable',
                'meaning_zh' => '优惠',
                'example_sentence' => '优惠活动。',
                'example_translation' => 'Promotional activity.',
                'definition' => 'Preferential, discount, favorable',
                'sentences' => ['___券。', '___价。', '___政策。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '促销',
                'pinyin' => 'cù xiāo',
                'simplified' => '促销',
                'traditional' => '促銷',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To promote sales / Promotion',
                'meaning_zh' => '促销',
                'example_sentence' => '促销活动。',
                'example_translation' => 'Promotion activity.',
                'definition' => 'To promote sales, promotion',
                'sentences' => ['___期。', '___方案。', '___力度。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '品牌',
                'pinyin' => 'pǐn pái',
                'simplified' => '品牌',
                'traditional' => '品牌',
                'part_of_speech' => 'noun',
                'meaning' => 'Brand',
                'meaning_zh' => '品牌',
                'example_sentence' => '名牌商品。',
                'example_translation' => 'Brand-name goods.',
                'definition' => 'Brand',
                'sentences' => ['___效应。', '___知名度。', '___产品。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '质量',
                'pinyin' => 'zhì liàng',
                'simplified' => '质量',
                'traditional' => '質量',
                'part_of_speech' => 'noun',
                'meaning' => 'Quality',
                'meaning_zh' => '质量',
                'example_sentence' => '质量好。',
                'example_translation' => 'Good quality.',
                'definition' => 'Quality',
                'sentences' => ['___保证。', '___检查。', '___问题。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '退货',
                'pinyin' => 'tuì huò',
                'simplified' => '退货',
                'traditional' => '退貨',
                'part_of_speech' => 'verb',
                'meaning' => 'To return goods / To refund',
                'meaning_zh' => '退货',
                'example_sentence' => '申请退货。',
                'example_translation' => 'Apply for refund.',
                'definition' => 'To return goods, to refund',
                'sentences' => ['___政策。', '___换货。', '___手续。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '换货',
                'pinyin' => 'huàn huò',
                'simplified' => '换货',
                'traditional' => '換貨',
                'part_of_speech' => 'verb',
                'meaning' => 'To exchange goods',
                'meaning_zh' => '换货',
                'example_sentence' => '要求换货。',
                'example_translation' => 'Request to exchange.',
                'definition' => 'To exchange goods',
                'sentences' => ['___服务。', '___流程。', '___凭证。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '发票',
                'pinyin' => 'fā piào',
                'simplified' => '发票',
                'traditional' => '發票',
                'part_of_speech' => 'noun',
                'meaning' => 'Invoice / Receipt',
                'meaning_zh' => '发票',
                'example_sentence' => '开发票。',
                'example_translation' => 'Issue an invoice.',
                'definition' => 'Invoice, receipt',
                'sentences' => ['___抬头。', '___保存。', '___内容。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '收银',
                'pinyin' => 'shōu yín',
                'simplified' => '收银',
                'traditional' => '收銀',
                'part_of_speech' => 'verb',
                'meaning' => 'To collect payment / Cashier',
                'meaning_zh' => '收银',
                'example_sentence' => '收银台。',
                'example_translation' => 'Cashier counter.',
                'definition' => 'To collect payment, cashier',
                'sentences' => ['___员。', '___处。', '___系统。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '现金',
                'pinyin' => 'xiàn jīn',
                'simplified' => '现金',
                'traditional' => '現金',
                'part_of_speech' => 'noun',
                'meaning' => 'Cash',
                'meaning_zh' => '现金',
                'example_sentence' => '付现金。',
                'example_translation' => 'Pay cash.',
                'definition' => 'Cash, ready money',
                'sentences' => ['___支付。', '___流。', '___交易。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '刷卡',
                'pinyin' => 'shuā kǎ',
                'simplified' => '刷卡',
                'traditional' => '刷卡',
                'part_of_speech' => 'verb',
                'meaning' => 'To swipe a card / To pay by card',
                'meaning_zh' => '刷卡',
                'example_sentence' => '可以刷卡吗？',
                'example_translation' => 'Can I pay by card?',
                'definition' => 'To swipe a card, to pay by card',
                'sentences' => ['___支付。', '___消费。', '___机。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '包装',
                'pinyin' => 'bāo zhuāng',
                'simplified' => '包装',
                'traditional' => '包裝',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To pack / Packaging',
                'meaning_zh' => '包装',
                'example_sentence' => '精美包装。',
                'example_translation' => 'Exquisite packaging.',
                'definition' => 'To pack, packaging, to wrap',
                'sentences' => ['___盒。', '___袋。', '___设计。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '售后',
                'pinyin' => 'shòu hòu',
                'simplified' => '售后',
                'traditional' => '售後',
                'part_of_speech' => 'noun',
                'meaning' => 'After-sales / Post-sale',
                'meaning_zh' => '售后',
                'example_sentence' => '售后服务。',
                'example_translation' => 'After-sales service.',
                'definition' => 'After-sales, post-sale',
                'sentences' => ['___保障。', '___电话。', '___维修。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 108,
                'word' => '顾客',
                'pinyin' => 'gù kè',
                'simplified' => '顾客',
                'traditional' => '顧客',
                'part_of_speech' => 'noun',
                'meaning' => 'Customer / Client',
                'meaning_zh' => '顾客',
                'example_sentence' => '顾客满意。',
                'example_translation' => 'Customer satisfaction.',
                'definition' => 'Customer, client, patron',
                'sentences' => ['___服务。', '___至上。', '___需求。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($environmentVocab, $transportVocab, $accommodationVocab, $shoppingVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
