<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics1to4Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 93: Workplace and Careers (工作和职业) - 20 words
        $workplaceVocab = [
            [
                'topic_id' => 93,
                'word' => '工作',
                'pinyin' => 'gōng zuò',
                'simplified' => '工作',
                'traditional' => '工作',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Work / Job / To work',
                'meaning_zh' => '工作',
                'example_sentence' => '我在一家公司工作。',
                'example_translation' => 'I work at a company.',
                'definition' => 'Work, job, to work',
                'sentences' => ['找___。', '___很忙。', '___经验。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '职业',
                'pinyin' => 'zhí yè',
                'simplified' => '职业',
                'traditional' => '職業',
                'part_of_speech' => 'noun',
                'meaning' => 'Occupation / Profession / Career',
                'meaning_zh' => '职业',
                'example_sentence' => '你的职业是什么？',
                'example_translation' => 'What is your occupation?',
                'definition' => 'Occupation, profession, career',
                'sentences' => ['___规划。', '___选择。', '___发展。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '职位',
                'pinyin' => 'zhí wèi',
                'simplified' => '职位',
                'traditional' => '職位',
                'part_of_speech' => 'noun',
                'meaning' => 'Position / Post',
                'meaning_zh' => '职位',
                'example_sentence' => '申请这个职位。',
                'example_translation' => 'Apply for this position.',
                'definition' => 'Position, post, job title',
                'sentences' => ['___空缺。', '___要求。', '重要___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '薪水',
                'pinyin' => 'xīn shuǐ',
                'simplified' => '薪水',
                'traditional' => '薪水',
                'part_of_speech' => 'noun',
                'meaning' => 'Salary / Pay',
                'meaning_zh' => '薪水',
                'example_sentence' => '薪水不错。',
                'example_translation' => 'The salary is good.',
                'definition' => 'Salary, pay, wages',
                'sentences' => ['___高。', '___待遇。', '发___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '工资',
                'pinyin' => 'gōng zī',
                'simplified' => '工资',
                'traditional' => '工資',
                'part_of_speech' => 'noun',
                'meaning' => 'Wages / Salary',
                'meaning_zh' => '工资',
                'example_sentence' => '每月发工资。',
                'example_translation' => 'Salary is paid monthly.',
                'definition' => 'Wages, salary',
                'sentences' => ['___收入。', '涨___。', '___单。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '经验',
                'pinyin' => 'jīng yàn',
                'simplified' => '经验',
                'traditional' => '經驗',
                'part_of_speech' => 'noun',
                'meaning' => 'Experience',
                'meaning_zh' => '经验',
                'example_sentence' => '需要工作经验。',
                'example_translation' => 'Work experience is required.',
                'definition' => 'Experience',
                'sentences' => ['丰富___。', '___不足。', '学习___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '经理',
                'pinyin' => 'jīng lǐ',
                'simplified' => '经理',
                'traditional' => '經理',
                'part_of_speech' => 'noun',
                'meaning' => 'Manager',
                'meaning_zh' => '经理',
                'example_sentence' => '他是部门经理。',
                'example_translation' => 'He is the department manager.',
                'definition' => 'Manager',
                'sentences' => ['总___。', '___办公室。', '___批准。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '老板',
                'pinyin' => 'lǎo bǎn',
                'simplified' => '老板',
                'traditional' => '老闆',
                'part_of_speech' => 'noun',
                'meaning' => 'Boss / Owner',
                'meaning_zh' => '老板',
                'example_sentence' => '老板很严格。',
                'example_translation' => 'The boss is very strict.',
                'definition' => 'Boss, owner, proprietor',
                'sentences' => ['___好。', '___要求。', '见___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '员工',
                'pinyin' => 'yuán gōng',
                'simplified' => '员工',
                'traditional' => '員工',
                'part_of_speech' => 'noun',
                'meaning' => 'Employee / Staff',
                'meaning_zh' => '员工',
                'example_sentence' => '公司员工很多。',
                'example_translation' => 'The company has many employees.',
                'definition' => 'Employee, staff',
                'sentences' => ['___福利。', '___培训。', '___人数。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '同事',
                'pinyin' => 'tóng shì',
                'simplified' => '同事',
                'traditional' => '同事',
                'part_of_speech' => 'noun',
                'meaning' => 'Colleague / Coworker',
                'meaning_zh' => '同事',
                'example_sentence' => '和同事相处很好。',
                'example_translation' => 'Get along well with colleagues.',
                'definition' => 'Colleague, coworker',
                'sentences' => ['___关系。', '___帮助。', '___之间。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '部门',
                'pinyin' => 'bù mén',
                'simplified' => '部门',
                'traditional' => '部門',
                'part_of_speech' => 'noun',
                'meaning' => 'Department / Division',
                'meaning_zh' => '部门',
                'example_sentence' => '财务部门。',
                'example_translation' => 'Finance department.',
                'definition' => 'Department, division, section',
                'sentences' => ['各___。', '___负责人。', '___会议。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '公司',
                'pinyin' => 'gōng sī',
                'simplified' => '公司',
                'traditional' => '公司',
                'part_of_speech' => 'noun',
                'meaning' => 'Company / Corporation',
                'meaning_zh' => '公司',
                'example_sentence' => '在公司上班。',
                'example_translation' => 'Work at a company.',
                'definition' => 'Company, corporation',
                'sentences' => ['___规模。', '___文化。', '___发展。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '企业',
                'pinyin' => 'qǐ yè',
                'simplified' => '企业',
                'traditional' => '企業',
                'part_of_speech' => 'noun',
                'meaning' => 'Enterprise / Business',
                'meaning_zh' => '企业',
                'example_sentence' => '大型企业。',
                'example_translation' => 'Large enterprise.',
                'definition' => 'Enterprise, business, company',
                'sentences' => ['___管理。', '___家。', '___竞争。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '成功',
                'pinyin' => 'chéng gōng',
                'simplified' => '成功',
                'traditional' => '成功',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To succeed / Successful / Success',
                'meaning_zh' => '成功',
                'example_sentence' => '项目成功了。',
                'example_translation' => 'The project succeeded.',
                'definition' => 'To succeed, successful, success',
                'sentences' => ['___人士。', '___经验。', '___了！'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '失败',
                'pinyin' => 'shī bài',
                'simplified' => '失败',
                'traditional' => '失敗',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To fail / Failure',
                'meaning_zh' => '失败',
                'example_sentence' => '不怕失败。',
                'example_translation' => 'Not afraid of failure.',
                'definition' => 'To fail, failure',
                'sentences' => ['___的原因。', '___教训。', '___了。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '负责',
                'pinyin' => 'fù zé',
                'simplified' => '负责',
                'traditional' => '負責',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To be responsible / Responsible',
                'meaning_zh' => '负责',
                'example_sentence' => '他负责这个项目。',
                'example_translation' => 'He is responsible for this project.',
                'definition' => 'To be responsible, responsible',
                'sentences' => ['___人。', '___任。', '___态度。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '任务',
                'pinyin' => 'rèn wu',
                'simplified' => '任务',
                'traditional' => '任務',
                'part_of_speech' => 'noun',
                'meaning' => 'Task / Mission / Assignment',
                'meaning_zh' => '任务',
                'example_sentence' => '完成任务。',
                'example_translation' => 'Complete the task.',
                'definition' => 'Task, mission, assignment',
                'sentences' => ['___艰巨。', '___分配。', '重要___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '项目',
                'pinyin' => 'xiàng mù',
                'simplified' => '项目',
                'traditional' => '項目',
                'part_of_speech' => 'noun',
                'meaning' => 'Project / Item',
                'meaning_zh' => '项目',
                'example_sentence' => '新项目启动。',
                'example_translation' => 'New project starts.',
                'definition' => 'Project, item, program',
                'sentences' => ['___管理。', '___进展。', '___团队。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '效率',
                'pinyin' => 'xiào lǜ',
                'simplified' => '效率',
                'traditional' => '效率',
                'part_of_speech' => 'noun',
                'meaning' => 'Efficiency',
                'meaning_zh' => '效率',
                'example_sentence' => '提高工作效率。',
                'example_translation' => 'Improve work efficiency.',
                'definition' => 'Efficiency',
                'sentences' => ['___高。', '___低。', '工作___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 93,
                'word' => '压力',
                'pinyin' => 'yā lì',
                'simplified' => '压力',
                'traditional' => '壓力',
                'part_of_speech' => 'noun',
                'meaning' => 'Pressure / Stress',
                'meaning_zh' => '压力',
                'example_sentence' => '工作压力很大。',
                'example_translation' => 'Work pressure is great.',
                'definition' => 'Pressure, stress',
                'sentences' => ['___大。', '___山大。', '缓解___。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 94: Job Hunting and Interviews (求职和面试) - 20 words
        $jobHuntingVocab = [
            [
                'topic_id' => 94,
                'word' => '求职',
                'pinyin' => 'qiú zhí',
                'simplified' => '求职',
                'traditional' => '求職',
                'part_of_speech' => 'verb',
                'meaning' => 'To seek employment / Job hunting',
                'meaning_zh' => '求职',
                'example_sentence' => '正在求职。',
                'example_translation' => 'Currently job hunting.',
                'definition' => 'To seek employment, job hunting',
                'sentences' => ['___网站。', '___信。', '___者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '招聘',
                'pinyin' => 'zhāo pìn',
                'simplified' => '招聘',
                'traditional' => '招聘',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To recruit / Recruitment',
                'meaning_zh' => '招聘',
                'example_sentence' => '公司正在招聘。',
                'example_translation' => 'The company is recruiting.',
                'definition' => 'To recruit, recruitment',
                'sentences' => ['___会。', '___广告。', '___信息。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '简历',
                'pinyin' => 'jiǎn lì',
                'simplified' => '简历',
                'traditional' => '簡歷',
                'part_of_speech' => 'noun',
                'meaning' => 'Resume / CV',
                'meaning_zh' => '简历',
                'example_sentence' => '投简历。',
                'example_translation' => 'Submit a resume.',
                'definition' => 'Resume, CV, curriculum vitae',
                'sentences' => ['___表。', '___内容。', '准备___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '申请',
                'pinyin' => 'shēn qǐng',
                'simplified' => '申请',
                'traditional' => '申請',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To apply / Application',
                'meaning_zh' => '申请',
                'example_sentence' => '申请工作。',
                'example_translation' => 'Apply for a job.',
                'definition' => 'To apply, application',
                'sentences' => ['___表。', '___材料。', '___人。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '面试',
                'pinyin' => 'miàn shì',
                'simplified' => '面试',
                'traditional' => '面試',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Interview / To interview',
                'meaning_zh' => '面试',
                'example_sentence' => '明天去面试。',
                'example_translation' => 'Go for an interview tomorrow.',
                'definition' => 'Interview, to interview',
                'sentences' => ['___官。', '___题。', '___通过。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '录取',
                'pinyin' => 'lù qǔ',
                'simplified' => '录取',
                'traditional' => '錄取',
                'part_of_speech' => 'verb',
                'meaning' => 'To admit / To enroll / To hire',
                'meaning_zh' => '录取',
                'example_sentence' => '被公司录取了。',
                'example_translation' => 'Was hired by the company.',
                'definition' => 'To admit, to enroll, to hire',
                'sentences' => ['___通知。', '___名单。', '___标准。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '能力',
                'pinyin' => 'néng lì',
                'simplified' => '能力',
                'traditional' => '能力',
                'part_of_speech' => 'noun',
                'meaning' => 'Ability / Capability',
                'meaning_zh' => '能力',
                'example_sentence' => '工作能力强。',
                'example_translation' => 'Strong work ability.',
                'definition' => 'Ability, capability, competence',
                'sentences' => ['___强。', '___不足。', '提高___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '技能',
                'pinyin' => 'jì néng',
                'simplified' => '技能',
                'traditional' => '技能',
                'part_of_speech' => 'noun',
                'meaning' => 'Skill / Technique',
                'meaning_zh' => '技能',
                'example_sentence' => '专业技能。',
                'example_translation' => 'Professional skills.',
                'definition' => 'Skill, technique',
                'sentences' => ['___培训。', '___水平。', '掌握___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '要求',
                'pinyin' => 'yāo qiú',
                'simplified' => '要求',
                'traditional' => '要求',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To require / Requirement',
                'meaning_zh' => '要求',
                'example_sentence' => '工作要求很高。',
                'example_translation' => 'Job requirements are high.',
                'definition' => 'To require, requirement, demand',
                'sentences' => ['___严格。', '___条件。', '满足___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '条件',
                'pinyin' => 'tiáo jiàn',
                'simplified' => '条件',
                'traditional' => '條件',
                'part_of_speech' => 'noun',
                'meaning' => 'Condition / Qualification',
                'meaning_zh' => '条件',
                'example_sentence' => '符合条件。',
                'example_translation' => 'Meet the conditions.',
                'definition' => 'Condition, qualification, term',
                'sentences' => ['___好。', '___限制。', '基本___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '机会',
                'pinyin' => 'jī huì',
                'simplified' => '机会',
                'traditional' => '機會',
                'part_of_speech' => 'noun',
                'meaning' => 'Opportunity / Chance',
                'meaning_zh' => '机会',
                'example_sentence' => '好机会。',
                'example_translation' => 'Good opportunity.',
                'definition' => 'Opportunity, chance',
                'sentences' => ['___难得。', '___来了。', '抓住___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '优势',
                'pinyin' => 'yōu shì',
                'simplified' => '优势',
                'traditional' => '優勢',
                'part_of_speech' => 'noun',
                'meaning' => 'Advantage / Strength',
                'meaning_zh' => '优势',
                'example_sentence' => '自己的优势。',
                'example_translation' => 'One\'s own advantages.',
                'definition' => 'Advantage, strength, superiority',
                'sentences' => ['___明显。', '竞争___。', '发挥___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '缺点',
                'pinyin' => 'quē diǎn',
                'simplified' => '缺点',
                'traditional' => '缺點',
                'part_of_speech' => 'noun',
                'meaning' => 'Shortcoming / Weakness / Disadvantage',
                'meaning_zh' => '缺点',
                'example_sentence' => '每个人都有缺点。',
                'example_translation' => 'Everyone has shortcomings.',
                'definition' => 'Shortcoming, weakness, disadvantage',
                'sentences' => ['___和优点。', '改正___。', '___很多。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '表现',
                'pinyin' => 'biǎo xiàn',
                'simplified' => '表现',
                'traditional' => '表現',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To show / To display / Performance',
                'meaning_zh' => '表现',
                'example_sentence' => '面试表现很好。',
                'example_translation' => 'Interview performance was good.',
                'definition' => 'To show, to display, performance',
                'sentences' => ['___出色。', '___不错。', '___机会。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '准备',
                'pinyin' => 'zhǔn bèi',
                'simplified' => '准备',
                'traditional' => '準備',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To prepare / Preparation',
                'meaning_zh' => '准备',
                'example_sentence' => '准备面试。',
                'example_translation' => 'Prepare for interview.',
                'definition' => 'To prepare, preparation',
                'sentences' => ['___材料。', '___充分。', '___工作。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '介绍',
                'pinyin' => 'jiè shào',
                'simplified' => '介绍',
                'traditional' => '介紹',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To introduce / Introduction',
                'meaning_zh' => '介绍',
                'example_sentence' => '自我介绍。',
                'example_translation' => 'Self-introduction.',
                'definition' => 'To introduce, introduction',
                'sentences' => ['___信。', '___一下。', '___材料。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '沟通',
                'pinyin' => 'gōu tōng',
                'simplified' => '沟通',
                'traditional' => '溝通',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To communicate / Communication',
                'meaning_zh' => '沟通',
                'example_sentence' => '良好的沟通能力。',
                'example_translation' => 'Good communication skills.',
                'definition' => 'To communicate, communication',
                'sentences' => ['___能力。', '___交流。', '___问题。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '自信',
                'pinyin' => 'zì xìn',
                'simplified' => '自信',
                'traditional' => '自信',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Confident / Self-confident / Confidence',
                'meaning_zh' => '自信',
                'example_sentence' => '表现自信。',
                'example_translation' => 'Show confidence.',
                'definition' => 'Confident, self-confident, confidence',
                'sentences' => ['___心。', '___的态度。', '充满___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '紧张',
                'pinyin' => 'jǐn zhāng',
                'simplified' => '紧张',
                'traditional' => '緊張',
                'part_of_speech' => 'adjective',
                'meaning' => 'Nervous / Tense',
                'meaning_zh' => '紧张',
                'example_sentence' => '面试很紧张。',
                'example_translation' => 'Very nervous in the interview.',
                'definition' => 'Nervous, tense, stressful',
                'sentences' => ['不要___。', '___的气氛。', '___起来。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 94,
                'word' => '竞争',
                'pinyin' => 'jìng zhēng',
                'simplified' => '竞争',
                'traditional' => '競爭',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To compete / Competition',
                'meaning_zh' => '竞争',
                'example_sentence' => '竞争激烈。',
                'example_translation' => 'Competition is fierce.',
                'definition' => 'To compete, competition',
                'sentences' => ['___力。', '___对手。', '___优势。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 95: University and Education (大学和教育) - 20 words
        $universityVocab = [
            [
                'topic_id' => 95,
                'word' => '大学',
                'pinyin' => 'dà xué',
                'simplified' => '大学',
                'traditional' => '大學',
                'part_of_speech' => 'noun',
                'meaning' => 'University / College',
                'meaning_zh' => '大学',
                'example_sentence' => '上大学。',
                'example_translation' => 'Go to university.',
                'definition' => 'University, college',
                'sentences' => ['___生活。', '___校园。', '考___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '专业',
                'pinyin' => 'zhuān yè',
                'simplified' => '专业',
                'traditional' => '專業',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Major / Specialty / Professional',
                'meaning_zh' => '专业',
                'example_sentence' => '我的专业是中文。',
                'example_translation' => 'My major is Chinese.',
                'definition' => 'Major, specialty, professional',
                'sentences' => ['选___。', '___知识。', '___课程。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '学位',
                'pinyin' => 'xué wèi',
                'simplified' => '学位',
                'traditional' => '學位',
                'part_of_speech' => 'noun',
                'meaning' => 'Degree / Academic degree',
                'meaning_zh' => '学位',
                'example_sentence' => '获得学位。',
                'example_translation' => 'Obtain a degree.',
                'definition' => 'Degree, academic degree',
                'sentences' => ['___证书。', '硕士___。', '___论文。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '毕业',
                'pinyin' => 'bì yè',
                'simplified' => '毕业',
                'traditional' => '畢業',
                'part_of_speech' => 'verb',
                'meaning' => 'To graduate',
                'meaning_zh' => '毕业',
                'example_sentence' => '明年毕业。',
                'example_translation' => 'Graduate next year.',
                'definition' => 'To graduate, graduation',
                'sentences' => ['___典礼。', '___证书。', '___生。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '教授',
                'pinyin' => 'jiào shòu',
                'simplified' => '教授',
                'traditional' => '教授',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Professor / To teach',
                'meaning_zh' => '教授',
                'example_sentence' => '李教授。',
                'example_translation' => 'Professor Li.',
                'definition' => 'Professor, to teach',
                'sentences' => ['___课。', '___办公室。', '___讲座。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '讲座',
                'pinyin' => 'jiǎng zuò',
                'simplified' => '讲座',
                'traditional' => '講座',
                'part_of_speech' => 'noun',
                'meaning' => 'Lecture / Seminar',
                'meaning_zh' => '讲座',
                'example_sentence' => '参加讲座。',
                'example_translation' => 'Attend a lecture.',
                'definition' => 'Lecture, seminar',
                'sentences' => ['___主题。', '___内容。', '举办___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '课程',
                'pinyin' => 'kè chéng',
                'simplified' => '课程',
                'traditional' => '課程',
                'part_of_speech' => 'noun',
                'meaning' => 'Course / Curriculum',
                'meaning_zh' => '课程',
                'example_sentence' => '选修课程。',
                'example_translation' => 'Elective courses.',
                'definition' => 'Course, curriculum',
                'sentences' => ['___表。', '___安排。', '必修___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '学期',
                'pinyin' => 'xué qī',
                'simplified' => '学期',
                'traditional' => '學期',
                'part_of_speech' => 'noun',
                'meaning' => 'Semester / Term',
                'meaning_zh' => '学期',
                'example_sentence' => '这个学期。',
                'example_translation' => 'This semester.',
                'definition' => 'Semester, term',
                'sentences' => ['新___。', '___末。', '___开始。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '学费',
                'pinyin' => 'xué fèi',
                'simplified' => '学费',
                'traditional' => '學費',
                'part_of_speech' => 'noun',
                'meaning' => 'Tuition / Tuition fee',
                'meaning_zh' => '学费',
                'example_sentence' => '交学费。',
                'example_translation' => 'Pay tuition.',
                'definition' => 'Tuition, tuition fee',
                'sentences' => ['___贵。', '___减免。', '___标准。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '奖学金',
                'pinyin' => 'jiǎng xué jīn',
                'simplified' => '奖学金',
                'traditional' => '獎學金',
                'part_of_speech' => 'noun',
                'meaning' => 'Scholarship',
                'meaning_zh' => '奖学金',
                'example_sentence' => '获得奖学金。',
                'example_translation' => 'Receive a scholarship.',
                'definition' => 'Scholarship',
                'sentences' => ['申请___。', '___金额。', '___获得者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '研究',
                'pinyin' => 'yán jiū',
                'simplified' => '研究',
                'traditional' => '研究',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To research / Research',
                'meaning_zh' => '研究',
                'example_sentence' => '研究问题。',
                'example_translation' => 'Research problems.',
                'definition' => 'To research, research, study',
                'sentences' => ['___生。', '___成果。', '___课题。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '论文',
                'pinyin' => 'lùn wén',
                'simplified' => '论文',
                'traditional' => '論文',
                'part_of_speech' => 'noun',
                'meaning' => 'Thesis / Paper / Dissertation',
                'meaning_zh' => '论文',
                'example_sentence' => '写论文。',
                'example_translation' => 'Write a thesis.',
                'definition' => 'Thesis, paper, dissertation',
                'sentences' => ['___题目。', '___答辩。', '毕业___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '实验',
                'pinyin' => 'shí yàn',
                'simplified' => '实验',
                'traditional' => '實驗',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Experiment / To experiment',
                'meaning_zh' => '实验',
                'example_sentence' => '做实验。',
                'example_translation' => 'Do an experiment.',
                'definition' => 'Experiment, to experiment',
                'sentences' => ['___室。', '___结果。', '___报告。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '图书馆',
                'pinyin' => 'tú shū guǎn',
                'simplified' => '图书馆',
                'traditional' => '圖書館',
                'part_of_speech' => 'noun',
                'meaning' => 'Library',
                'meaning_zh' => '图书馆',
                'example_sentence' => '去图书馆学习。',
                'example_translation' => 'Go to the library to study.',
                'definition' => 'Library',
                'sentences' => ['___借书。', '___开放。', '___资源。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '宿舍',
                'pinyin' => 'sù shè',
                'simplified' => '宿舍',
                'traditional' => '宿舍',
                'part_of_speech' => 'noun',
                'meaning' => 'Dormitory',
                'meaning_zh' => '宿舍',
                'example_sentence' => '学生宿舍。',
                'example_translation' => 'Student dormitory.',
                'definition' => 'Dormitory, dorm',
                'sentences' => ['___楼。', '___室友。', '___生活。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '食堂',
                'pinyin' => 'shí táng',
                'simplified' => '食堂',
                'traditional' => '食堂',
                'part_of_speech' => 'noun',
                'meaning' => 'Dining hall / Cafeteria',
                'meaning_zh' => '食堂',
                'example_sentence' => '在食堂吃饭。',
                'example_translation' => 'Eat at the cafeteria.',
                'definition' => 'Dining hall, cafeteria',
                'sentences' => ['学校___。', '___饭菜。', '___卡。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '社团',
                'pinyin' => 'shè tuán',
                'simplified' => '社团',
                'traditional' => '社團',
                'part_of_speech' => 'noun',
                'meaning' => 'Club / Society / Association',
                'meaning_zh' => '社团',
                'example_sentence' => '参加社团活动。',
                'example_translation' => 'Join club activities.',
                'definition' => 'Club, society, association',
                'sentences' => ['___活动。', '___成员。', '学生___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '实践',
                'pinyin' => 'shí jiàn',
                'simplified' => '实践',
                'traditional' => '實踐',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Practice / To practice',
                'meaning_zh' => '实践',
                'example_sentence' => '理论和实践。',
                'example_translation' => 'Theory and practice.',
                'definition' => 'Practice, to practice',
                'sentences' => ['___经验。', '___活动。', '___能力。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '培养',
                'pinyin' => 'péi yǎng',
                'simplified' => '培养',
                'traditional' => '培養',
                'part_of_speech' => 'verb',
                'meaning' => 'To cultivate / To develop / To train',
                'meaning_zh' => '培养',
                'example_sentence' => '培养能力。',
                'example_translation' => 'Cultivate abilities.',
                'definition' => 'To cultivate, to develop, to train',
                'sentences' => ['___人才。', '___兴趣。', '___目标。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 95,
                'word' => '知识',
                'pinyin' => 'zhī shi',
                'simplified' => '知识',
                'traditional' => '知識',
                'part_of_speech' => 'noun',
                'meaning' => 'Knowledge',
                'meaning_zh' => '知识',
                'example_sentence' => '学习知识。',
                'example_translation' => 'Learn knowledge.',
                'definition' => 'Knowledge',
                'sentences' => ['___面广。', '___丰富。', '___点。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 96: Office Communication (办公室交流) - 20 words
        $officeCommunicationVocab = [
            [
                'topic_id' => 96,
                'word' => '会议',
                'pinyin' => 'huì yì',
                'simplified' => '会议',
                'traditional' => '會議',
                'part_of_speech' => 'noun',
                'meaning' => 'Meeting / Conference',
                'meaning_zh' => '会议',
                'example_sentence' => '参加会议。',
                'example_translation' => 'Attend a meeting.',
                'definition' => 'Meeting, conference',
                'sentences' => ['___室。', '___内容。', '开___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '讨论',
                'pinyin' => 'tǎo lùn',
                'simplified' => '讨论',
                'traditional' => '討論',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To discuss / Discussion',
                'meaning_zh' => '讨论',
                'example_sentence' => '讨论问题。',
                'example_translation' => 'Discuss problems.',
                'definition' => 'To discuss, discussion',
                'sentences' => ['___会。', '___结果。', '热烈___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '报告',
                'pinyin' => 'bào gào',
                'simplified' => '报告',
                'traditional' => '報告',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Report / To report',
                'meaning_zh' => '报告',
                'example_sentence' => '工作报告。',
                'example_translation' => 'Work report.',
                'definition' => 'Report, to report',
                'sentences' => ['___内容。', '___会。', '写___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '通知',
                'pinyin' => 'tōng zhī',
                'simplified' => '通知',
                'traditional' => '通知',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To notify / Notice',
                'meaning_zh' => '通知',
                'example_sentence' => '收到通知。',
                'example_translation' => 'Receive notice.',
                'definition' => 'To notify, notice, notification',
                'sentences' => ['___书。', '___大家。', '___内容。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '安排',
                'pinyin' => 'ān pái',
                'simplified' => '安排',
                'traditional' => '安排',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To arrange / Arrangement',
                'meaning_zh' => '安排',
                'example_sentence' => '安排工作。',
                'example_translation' => 'Arrange work.',
                'definition' => 'To arrange, arrangement',
                'sentences' => ['___时间。', '___计划。', '___好。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '计划',
                'pinyin' => 'jì huà',
                'simplified' => '计划',
                'traditional' => '計劃',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Plan / To plan',
                'meaning_zh' => '计划',
                'example_sentence' => '制定计划。',
                'example_translation' => 'Make a plan.',
                'definition' => 'Plan, to plan',
                'sentences' => ['___表。', '___执行。', '工作___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '建议',
                'pinyin' => 'jiàn yì',
                'simplified' => '建议',
                'traditional' => '建議',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Suggestion / To suggest',
                'meaning_zh' => '建议',
                'example_sentence' => '提出建议。',
                'example_translation' => 'Make a suggestion.',
                'definition' => 'Suggestion, to suggest',
                'sentences' => ['___书。', '___很好。', '___采纳。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '意见',
                'pinyin' => 'yì jiàn',
                'simplified' => '意见',
                'traditional' => '意見',
                'part_of_speech' => 'noun',
                'meaning' => 'Opinion / Suggestion',
                'meaning_zh' => '意见',
                'example_sentence' => '听取意见。',
                'example_translation' => 'Listen to opinions.',
                'definition' => 'Opinion, suggestion, view',
                'sentences' => ['___反馈。', '___分歧。', '提___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '合作',
                'pinyin' => 'hé zuò',
                'simplified' => '合作',
                'traditional' => '合作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To cooperate / Cooperation',
                'meaning_zh' => '合作',
                'example_sentence' => '团队合作。',
                'example_translation' => 'Team cooperation.',
                'definition' => 'To cooperate, cooperation',
                'sentences' => ['___伙伴。', '___项目。', '___精神。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '交流',
                'pinyin' => 'jiāo liú',
                'simplified' => '交流',
                'traditional' => '交流',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To exchange / Communication',
                'meaning_zh' => '交流',
                'example_sentence' => '工作交流。',
                'example_translation' => 'Work exchange.',
                'definition' => 'To exchange, communication',
                'sentences' => ['___经验。', '___会。', '___想法。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '联系',
                'pinyin' => 'lián xì',
                'simplified' => '联系',
                'traditional' => '聯繫',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To contact / Contact / Connection',
                'meaning_zh' => '联系',
                'example_sentence' => '保持联系。',
                'example_translation' => 'Keep in contact.',
                'definition' => 'To contact, contact, connection',
                'sentences' => ['___方式。', '___电话。', '___人。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '文件',
                'pinyin' => 'wén jiàn',
                'simplified' => '文件',
                'traditional' => '文件',
                'part_of_speech' => 'noun',
                'meaning' => 'Document / File',
                'meaning_zh' => '文件',
                'example_sentence' => '发送文件。',
                'example_translation' => 'Send a document.',
                'definition' => 'Document, file',
                'sentences' => ['___夹。', '___处理。', '重要___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '材料',
                'pinyin' => 'cái liào',
                'simplified' => '材料',
                'traditional' => '材料',
                'part_of_speech' => 'noun',
                'meaning' => 'Material / Data',
                'meaning_zh' => '材料',
                'example_sentence' => '准备材料。',
                'example_translation' => 'Prepare materials.',
                'definition' => 'Material, data, information',
                'sentences' => ['___齐全。', '___收集。', '参考___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '资料',
                'pinyin' => 'zī liào',
                'simplified' => '资料',
                'traditional' => '資料',
                'part_of_speech' => 'noun',
                'meaning' => 'Data / Information / Material',
                'meaning_zh' => '资料',
                'example_sentence' => '查找资料。',
                'example_translation' => 'Search for information.',
                'definition' => 'Data, information, material',
                'sentences' => ['___库。', '___完整。', '___分析。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '邮件',
                'pinyin' => 'yóu jiàn',
                'simplified' => '邮件',
                'traditional' => '郵件',
                'part_of_speech' => 'noun',
                'meaning' => 'Email / Mail',
                'meaning_zh' => '邮件',
                'example_sentence' => '发邮件。',
                'example_translation' => 'Send an email.',
                'definition' => 'Email, mail',
                'sentences' => ['___地址。', '___回复。', '收___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '确认',
                'pinyin' => 'què rèn',
                'simplified' => '确认',
                'traditional' => '確認',
                'part_of_speech' => 'verb',
                'meaning' => 'To confirm / To verify',
                'meaning_zh' => '确认',
                'example_sentence' => '请确认信息。',
                'example_translation' => 'Please confirm the information.',
                'definition' => 'To confirm, to verify',
                'sentences' => ['___无误。', '___一下。', '___函。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '解决',
                'pinyin' => 'jiě jué',
                'simplified' => '解决',
                'traditional' => '解決',
                'part_of_speech' => 'verb',
                'meaning' => 'To solve / To resolve',
                'meaning_zh' => '解决',
                'example_sentence' => '解决问题。',
                'example_translation' => 'Solve problems.',
                'definition' => 'To solve, to resolve',
                'sentences' => ['___方案。', '___办法。', '___困难。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '处理',
                'pinyin' => 'chǔ lǐ',
                'simplified' => '处理',
                'traditional' => '處理',
                'part_of_speech' => 'verb',
                'meaning' => 'To handle / To deal with',
                'meaning_zh' => '处理',
                'example_sentence' => '处理事情。',
                'example_translation' => 'Handle matters.',
                'definition' => 'To handle, to deal with, to process',
                'sentences' => ['___问题。', '___方式。', '___好。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '完成',
                'pinyin' => 'wán chéng',
                'simplified' => '完成',
                'traditional' => '完成',
                'part_of_speech' => 'verb',
                'meaning' => 'To complete / To finish',
                'meaning_zh' => '完成',
                'example_sentence' => '完成工作。',
                'example_translation' => 'Complete work.',
                'definition' => 'To complete, to finish',
                'sentences' => ['___任务。', '___了。', '___情况。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 96,
                'word' => '总结',
                'pinyin' => 'zǒng jié',
                'simplified' => '总结',
                'traditional' => '總結',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To summarize / Summary',
                'meaning_zh' => '总结',
                'example_sentence' => '工作总结。',
                'example_translation' => 'Work summary.',
                'definition' => 'To summarize, summary',
                'sentences' => ['___经验。', '___报告。', '___会。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($workplaceVocab, $jobHuntingVocab, $universityVocab, $officeCommunicationVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
