<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics9to12Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 101: Emotions and Attitudes (情绪和态度) - 20 words
        $emotionsVocab = [
            [
                'topic_id' => 101,
                'word' => '情绪',
                'pinyin' => 'qíng xù',
                'simplified' => '情绪',
                'traditional' => '情緒',
                'part_of_speech' => 'noun',
                'meaning' => 'Emotion / Mood',
                'meaning_zh' => '情绪',
                'example_sentence' => '控制情绪。',
                'example_translation' => 'Control emotions.',
                'definition' => 'Emotion, mood, feeling',
                'sentences' => ['___稳定。', '___波动。', '___管理。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '心情',
                'pinyin' => 'xīn qíng',
                'simplified' => '心情',
                'traditional' => '心情',
                'part_of_speech' => 'noun',
                'meaning' => 'Mood / Frame of mind',
                'meaning_zh' => '心情',
                'example_sentence' => '心情很好。',
                'example_translation' => 'In a good mood.',
                'definition' => 'Mood, frame of mind',
                'sentences' => ['___愉快。', '___不好。', '___舒畅。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '兴奋',
                'pinyin' => 'xīng fèn',
                'simplified' => '兴奋',
                'traditional' => '興奮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Excited / Excitement',
                'meaning_zh' => '兴奋',
                'example_sentence' => '非常兴奋。',
                'example_translation' => 'Very excited.',
                'definition' => 'Excited, excitement, thrilled',
                'sentences' => ['___不已。', '___剂。', '___起来。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '激动',
                'pinyin' => 'jī dòng',
                'simplified' => '激动',
                'traditional' => '激動',
                'part_of_speech' => 'adjective',
                'meaning' => 'Excited / Emotional / Agitated',
                'meaning_zh' => '激动',
                'example_sentence' => '心情激动。',
                'example_translation' => 'Feel excited.',
                'definition' => 'Excited, emotional, agitated',
                'sentences' => ['___地说。', '___人心。', '___不已。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '焦虑',
                'pinyin' => 'jiāo lǜ',
                'simplified' => '焦虑',
                'traditional' => '焦慮',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Anxious / Anxiety',
                'meaning_zh' => '焦虑',
                'example_sentence' => '感到焦虑。',
                'example_translation' => 'Feel anxious.',
                'definition' => 'Anxious, anxiety, worried',
                'sentences' => ['___不安。', '___症。', '___情绪。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '烦恼',
                'pinyin' => 'fán nǎo',
                'simplified' => '烦恼',
                'traditional' => '煩惱',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Worry / Vexation / Worried',
                'meaning_zh' => '烦恼',
                'example_sentence' => '没有烦恼。',
                'example_translation' => 'No worries.',
                'definition' => 'Worry, vexation, worried, annoyed',
                'sentences' => ['___的事。', '___丝。', '___多。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '沮丧',
                'pinyin' => 'jǔ sàng',
                'simplified' => '沮丧',
                'traditional' => '沮喪',
                'part_of_speech' => 'adjective',
                'meaning' => 'Depressed / Dejected / Discouraged',
                'meaning_zh' => '沮丧',
                'example_sentence' => '感到沮丧。',
                'example_translation' => 'Feel depressed.',
                'definition' => 'Depressed, dejected, discouraged',
                'sentences' => ['___的心情。', '___不已。', '___失望。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '失望',
                'pinyin' => 'shī wàng',
                'simplified' => '失望',
                'traditional' => '失望',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Disappointed / Disappointment',
                'meaning_zh' => '失望',
                'example_sentence' => '很失望。',
                'example_translation' => 'Very disappointed.',
                'definition' => 'Disappointed, disappointment',
                'sentences' => ['___透顶。', '___的眼神。', '让人___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '满意',
                'pinyin' => 'mǎn yì',
                'simplified' => '满意',
                'traditional' => '滿意',
                'part_of_speech' => 'adjective',
                'meaning' => 'Satisfied / Satisfactory',
                'meaning_zh' => '满意',
                'example_sentence' => '非常满意。',
                'example_translation' => 'Very satisfied.',
                'definition' => 'Satisfied, satisfactory, pleased',
                'sentences' => ['___度。', '___的结果。', '___了。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '后悔',
                'pinyin' => 'hòu huǐ',
                'simplified' => '后悔',
                'traditional' => '後悔',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To regret / Regretful',
                'meaning_zh' => '后悔',
                'example_sentence' => '很后悔。',
                'example_translation' => 'Very regretful.',
                'definition' => 'To regret, regretful',
                'sentences' => ['___莫及。', '___不已。', '___的事。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '羡慕',
                'pinyin' => 'xiàn mù',
                'simplified' => '羡慕',
                'traditional' => '羨慕',
                'part_of_speech' => 'verb',
                'meaning' => 'To envy / To admire',
                'meaning_zh' => '羡慕',
                'example_sentence' => '羡慕他。',
                'example_translation' => 'Envy him.',
                'definition' => 'To envy, to admire',
                'sentences' => ['___嫉妒。', '___的眼光。', '___别人。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '嫉妒',
                'pinyin' => 'jí dù',
                'simplified' => '嫉妒',
                'traditional' => '嫉妒',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To be jealous / Jealous',
                'meaning_zh' => '嫉妒',
                'example_sentence' => '不要嫉妒。',
                'example_translation' => 'Don\'t be jealous.',
                'definition' => 'To be jealous, jealous, envy',
                'sentences' => ['___心。', '___别人。', '___的目光。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '愤怒',
                'pinyin' => 'fèn nù',
                'simplified' => '愤怒',
                'traditional' => '憤怒',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Angry / Anger / Fury',
                'meaning_zh' => '愤怒',
                'example_sentence' => '十分愤怒。',
                'example_translation' => 'Very angry.',
                'definition' => 'Angry, anger, fury',
                'sentences' => ['___地。', '___情绪。', '___的眼神。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '恐惧',
                'pinyin' => 'kǒng jù',
                'simplified' => '恐惧',
                'traditional' => '恐懼',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Fear / Terror / To fear',
                'meaning_zh' => '恐惧',
                'example_sentence' => '感到恐惧。',
                'example_translation' => 'Feel fear.',
                'definition' => 'Fear, terror, to fear',
                'sentences' => ['___感。', '___症。', '___心理。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '感动',
                'pinyin' => 'gǎn dòng',
                'simplified' => '感动',
                'traditional' => '感動',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To be moved / Touched',
                'meaning_zh' => '感动',
                'example_sentence' => '很感动。',
                'example_translation' => 'Very touched.',
                'definition' => 'To be moved, touched, moved',
                'sentences' => ['___得哭了。', '___人心。', '___不已。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '同情',
                'pinyin' => 'tóng qíng',
                'simplified' => '同情',
                'traditional' => '同情',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To sympathize / Sympathy',
                'meaning_zh' => '同情',
                'example_sentence' => '同情他。',
                'example_translation' => 'Sympathize with him.',
                'definition' => 'To sympathize, sympathy, compassion',
                'sentences' => ['___心。', '___的目光。', '___弱者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '积极',
                'pinyin' => 'jī jí',
                'simplified' => '积极',
                'traditional' => '積極',
                'part_of_speech' => 'adjective',
                'meaning' => 'Active / Positive / Enthusiastic',
                'meaning_zh' => '积极',
                'example_sentence' => '积极参与。',
                'example_translation' => 'Actively participate.',
                'definition' => 'Active, positive, enthusiastic',
                'sentences' => ['___性。', '___态度。', '___向上。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '消极',
                'pinyin' => 'xiāo jí',
                'simplified' => '消极',
                'traditional' => '消極',
                'part_of_speech' => 'adjective',
                'meaning' => 'Negative / Passive',
                'meaning_zh' => '消极',
                'example_sentence' => '态度消极。',
                'example_translation' => 'Negative attitude.',
                'definition' => 'Negative, passive',
                'sentences' => ['___情绪。', '___态度。', '___影响。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '放松',
                'pinyin' => 'fàng sōng',
                'simplified' => '放松',
                'traditional' => '放鬆',
                'part_of_speech' => 'verb',
                'meaning' => 'To relax / To loosen',
                'meaning_zh' => '放松',
                'example_sentence' => '放松心情。',
                'example_translation' => 'Relax mood.',
                'definition' => 'To relax, to loosen',
                'sentences' => ['___一下。', '___身心。', '___自己。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 101,
                'word' => '安慰',
                'pinyin' => 'ān wèi',
                'simplified' => '安慰',
                'traditional' => '安慰',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To comfort / To console / Comfort',
                'meaning_zh' => '安慰',
                'example_sentence' => '安慰朋友。',
                'example_translation' => 'Comfort friends.',
                'definition' => 'To comfort, to console, comfort',
                'sentences' => ['___人。', '___话。', '___自己。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 102: Manners and Social Behavior (礼貌和社交行为) - 20 words
        $mannersVocab = [
            [
                'topic_id' => 102,
                'word' => '礼貌',
                'pinyin' => 'lǐ mào',
                'simplified' => '礼貌',
                'traditional' => '禮貌',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Polite / Courtesy / Manners',
                'meaning_zh' => '礼貌',
                'example_sentence' => '很有礼貌。',
                'example_translation' => 'Very polite.',
                'definition' => 'Polite, courtesy, manners',
                'sentences' => ['___用语。', '___待人。', '___地。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '尊敬',
                'pinyin' => 'zūn jìng',
                'simplified' => '尊敬',
                'traditional' => '尊敬',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To respect / Respectful',
                'meaning_zh' => '尊敬',
                'example_sentence' => '尊敬长辈。',
                'example_translation' => 'Respect elders.',
                'definition' => 'To respect, respectful, to esteem',
                'sentences' => ['___的老师。', '___他人。', '___地。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '感谢',
                'pinyin' => 'gǎn xiè',
                'simplified' => '感谢',
                'traditional' => '感謝',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To thank / Thanks / Gratitude',
                'meaning_zh' => '感谢',
                'example_sentence' => '感谢帮助。',
                'example_translation' => 'Thank for help.',
                'definition' => 'To thank, thanks, gratitude',
                'sentences' => ['___信。', '___您。', '___的话。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '祝贺',
                'pinyin' => 'zhù hè',
                'simplified' => '祝贺',
                'traditional' => '祝賀',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To congratulate / Congratulations',
                'meaning_zh' => '祝贺',
                'example_sentence' => '祝贺成功。',
                'example_translation' => 'Congratulate on success.',
                'definition' => 'To congratulate, congratulations',
                'sentences' => ['___你！', '___信。', '___词。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '祝福',
                'pinyin' => 'zhù fú',
                'simplified' => '祝福',
                'traditional' => '祝福',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To bless / Blessing',
                'meaning_zh' => '祝福',
                'example_sentence' => '祝福你们。',
                'example_translation' => 'Bless you.',
                'definition' => 'To bless, blessing, wish well',
                'sentences' => ['___语。', '___的话。', '送上___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '问候',
                'pinyin' => 'wèn hòu',
                'simplified' => '问候',
                'traditional' => '問候',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To greet / Greeting / To send regards',
                'meaning_zh' => '问候',
                'example_sentence' => '问候家人。',
                'example_translation' => 'Send regards to family.',
                'definition' => 'To greet, greeting, to send regards',
                'sentences' => ['___语。', '___一声。', '___亲友。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '邀请',
                'pinyin' => 'yāo qǐng',
                'simplified' => '邀请',
                'traditional' => '邀請',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To invite / Invitation',
                'meaning_zh' => '邀请',
                'example_sentence' => '邀请朋友。',
                'example_translation' => 'Invite friends.',
                'definition' => 'To invite, invitation',
                'sentences' => ['___函。', '___参加。', '___嘉宾。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '接待',
                'pinyin' => 'jiē dài',
                'simplified' => '接待',
                'traditional' => '接待',
                'part_of_speech' => 'verb',
                'meaning' => 'To receive / To entertain / To host',
                'meaning_zh' => '接待',
                'example_sentence' => '接待客人。',
                'example_translation' => 'Receive guests.',
                'definition' => 'To receive, to entertain, to host',
                'sentences' => ['___室。', '___工作。', '___员。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '拜访',
                'pinyin' => 'bài fǎng',
                'simplified' => '拜访',
                'traditional' => '拜訪',
                'part_of_speech' => 'verb',
                'meaning' => 'To visit / To call on',
                'meaning_zh' => '拜访',
                'example_sentence' => '拜访老师。',
                'example_translation' => 'Visit teacher.',
                'definition' => 'To visit, to call on',
                'sentences' => ['___亲友。', '___客户。', '___长辈。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '打扰',
                'pinyin' => 'dǎ rǎo',
                'simplified' => '打扰',
                'traditional' => '打擾',
                'part_of_speech' => 'verb',
                'meaning' => 'To disturb / To bother',
                'meaning_zh' => '打扰',
                'example_sentence' => '不好意思打扰。',
                'example_translation' => 'Sorry to disturb.',
                'definition' => 'To disturb, to bother, to trouble',
                'sentences' => ['___了。', '___一下。', '不要___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '谦虚',
                'pinyin' => 'qiān xū',
                'simplified' => '谦虚',
                'traditional' => '謙虛',
                'part_of_speech' => 'adjective',
                'meaning' => 'Modest / Humble',
                'meaning_zh' => '谦虚',
                'example_sentence' => '为人谦虚。',
                'example_translation' => 'Modest person.',
                'definition' => 'Modest, humble',
                'sentences' => ['___好学。', '___的态度。', '___谨慎。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '客气',
                'pinyin' => 'kè qi',
                'simplified' => '客气',
                'traditional' => '客氣',
                'part_of_speech' => 'adjective',
                'meaning' => 'Polite / Courteous',
                'meaning_zh' => '客气',
                'example_sentence' => '不用客气。',
                'example_translation' => 'You\'re welcome.',
                'definition' => 'Polite, courteous, formal',
                'sentences' => ['___的话。', '太___了。', '___地说。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '礼物',
                'pinyin' => 'lǐ wù',
                'simplified' => '礼物',
                'traditional' => '禮物',
                'part_of_speech' => 'noun',
                'meaning' => 'Gift / Present',
                'meaning_zh' => '礼物',
                'example_sentence' => '送礼物。',
                'example_translation' => 'Give a gift.',
                'definition' => 'Gift, present',
                'sentences' => ['___盒。', '___准备。', '___交换。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '赠送',
                'pinyin' => 'zèng sòng',
                'simplified' => '赠送',
                'traditional' => '贈送',
                'part_of_speech' => 'verb',
                'meaning' => 'To give as a gift / To present',
                'meaning_zh' => '赠送',
                'example_sentence' => '赠送礼品。',
                'example_translation' => 'Give gifts.',
                'definition' => 'To give as a gift, to present',
                'sentences' => ['___品。', '免费___。', '___给。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '款待',
                'pinyin' => 'kuǎn dài',
                'simplified' => '款待',
                'traditional' => '款待',
                'part_of_speech' => 'verb',
                'meaning' => 'To entertain / To treat hospitably',
                'meaning_zh' => '款待',
                'example_sentence' => '热情款待。',
                'example_translation' => 'Warmly entertain.',
                'definition' => 'To entertain, to treat hospitably',
                'sentences' => ['___客人。', '___朋友。', '___得很好。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '场合',
                'pinyin' => 'chǎng hé',
                'simplified' => '场合',
                'traditional' => '場合',
                'part_of_speech' => 'noun',
                'meaning' => 'Occasion / Situation',
                'meaning_zh' => '场合',
                'example_sentence' => '正式场合。',
                'example_translation' => 'Formal occasion.',
                'definition' => 'Occasion, situation, context',
                'sentences' => ['___适当。', '___不同。', '公开___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '举止',
                'pinyin' => 'jǔ zhǐ',
                'simplified' => '举止',
                'traditional' => '舉止',
                'part_of_speech' => 'noun',
                'meaning' => 'Manner / Behavior / Bearing',
                'meaning_zh' => '举止',
                'example_sentence' => '举止优雅。',
                'example_translation' => 'Elegant manner.',
                'definition' => 'Manner, behavior, bearing',
                'sentences' => ['___得体。', '___大方。', '___言行。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '仪式',
                'pinyin' => 'yí shì',
                'simplified' => '仪式',
                'traditional' => '儀式',
                'part_of_speech' => 'noun',
                'meaning' => 'Ceremony / Ritual',
                'meaning_zh' => '仪式',
                'example_sentence' => '婚礼仪式。',
                'example_translation' => 'Wedding ceremony.',
                'definition' => 'Ceremony, ritual',
                'sentences' => ['___举行。', '___感。', '开幕___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '传统文化。',
                'example_translation' => 'Traditional culture.',
                'definition' => 'Tradition, traditional',
                'sentences' => ['___节日。', '___习俗。', '___观念。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 102,
                'word' => '风俗',
                'pinyin' => 'fēng sú',
                'simplified' => '风俗',
                'traditional' => '風俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Convention',
                'meaning_zh' => '风俗',
                'example_sentence' => '当地风俗。',
                'example_translation' => 'Local customs.',
                'definition' => 'Custom, convention, folkway',
                'sentences' => ['___习惯。', '___文化。', '___人情。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 103: Law and Order (法律和秩序) - 20 words
        $lawVocab = [
            [
                'topic_id' => 103,
                'word' => '法律',
                'pinyin' => 'fǎ lǜ',
                'simplified' => '法律',
                'traditional' => '法律',
                'part_of_speech' => 'noun',
                'meaning' => 'Law',
                'meaning_zh' => '法律',
                'example_sentence' => '遵守法律。',
                'example_translation' => 'Obey the law.',
                'definition' => 'Law, legal',
                'sentences' => ['___规定。', '___制度。', '___责任。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '规则',
                'pinyin' => 'guī zé',
                'simplified' => '规则',
                'traditional' => '規則',
                'part_of_speech' => 'noun',
                'meaning' => 'Rule / Regulation',
                'meaning_zh' => '规则',
                'example_sentence' => '遵守规则。',
                'example_translation' => 'Follow rules.',
                'definition' => 'Rule, regulation',
                'sentences' => ['___制定。', '游戏___。', '___意识。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '规定',
                'pinyin' => 'guī dìng',
                'simplified' => '规定',
                'traditional' => '規定',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Regulation / To stipulate',
                'meaning_zh' => '规定',
                'example_sentence' => '按照规定。',
                'example_translation' => 'According to regulations.',
                'definition' => 'Regulation, to stipulate, to provide',
                'sentences' => ['___时间。', '___明确。', '___执行。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '制度',
                'pinyin' => 'zhì dù',
                'simplified' => '制度',
                'traditional' => '制度',
                'part_of_speech' => 'noun',
                'meaning' => 'System / Institution',
                'meaning_zh' => '制度',
                'example_sentence' => '管理制度。',
                'example_translation' => 'Management system.',
                'definition' => 'System, institution, regime',
                'sentences' => ['___建设。', '___改革。', '___完善。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '权利',
                'pinyin' => 'quán lì',
                'simplified' => '权利',
                'traditional' => '權利',
                'part_of_speech' => 'noun',
                'meaning' => 'Right / Privilege',
                'meaning_zh' => '权利',
                'example_sentence' => '维护权利。',
                'example_translation' => 'Protect rights.',
                'definition' => 'Right, privilege',
                'sentences' => ['___义务。', '___要求。', '合法___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '义务',
                'pinyin' => 'yì wù',
                'simplified' => '义务',
                'traditional' => '義務',
                'part_of_speech' => 'noun',
                'meaning' => 'Duty / Obligation',
                'meaning_zh' => '义务',
                'example_sentence' => '履行义务。',
                'example_translation' => 'Fulfill obligations.',
                'definition' => 'Duty, obligation',
                'sentences' => ['___教育。', '___劳动。', '___和权利。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '公民',
                'pinyin' => 'gōng mín',
                'simplified' => '公民',
                'traditional' => '公民',
                'part_of_speech' => 'noun',
                'meaning' => 'Citizen',
                'meaning_zh' => '公民',
                'example_sentence' => '守法公民。',
                'example_translation' => 'Law-abiding citizen.',
                'definition' => 'Citizen',
                'sentences' => ['___权利。', '___意识。', '___素质。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '警察',
                'pinyin' => 'jǐng chá',
                'simplified' => '警察',
                'traditional' => '警察',
                'part_of_speech' => 'noun',
                'meaning' => 'Police / Police officer',
                'meaning_zh' => '警察',
                'example_sentence' => '报警察。',
                'example_translation' => 'Call the police.',
                'definition' => 'Police, police officer',
                'sentences' => ['___局。', '___叔叔。', '___执法。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '法院',
                'pinyin' => 'fǎ yuàn',
                'simplified' => '法院',
                'traditional' => '法院',
                'part_of_speech' => 'noun',
                'meaning' => 'Court / Law court',
                'meaning_zh' => '法院',
                'example_sentence' => '上法院。',
                'example_translation' => 'Go to court.',
                'definition' => 'Court, law court',
                'sentences' => ['___判决。', '___审理。', '___起诉。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '律师',
                'pinyin' => 'lǜ shī',
                'simplified' => '律师',
                'traditional' => '律師',
                'part_of_speech' => 'noun',
                'meaning' => 'Lawyer / Attorney',
                'meaning_zh' => '律师',
                'example_sentence' => '请律师。',
                'example_translation' => 'Hire a lawyer.',
                'definition' => 'Lawyer, attorney',
                'sentences' => ['___事务所。', '___咨询。', '___辩护。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '犯罪',
                'pinyin' => 'fàn zuì',
                'simplified' => '犯罪',
                'traditional' => '犯罪',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To commit a crime / Crime',
                'meaning_zh' => '犯罪',
                'example_sentence' => '预防犯罪。',
                'example_translation' => 'Prevent crime.',
                'definition' => 'To commit a crime, crime',
                'sentences' => ['___行为。', '___分子。', '___率。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '违反',
                'pinyin' => 'wéi fǎn',
                'simplified' => '违反',
                'traditional' => '違反',
                'part_of_speech' => 'verb',
                'meaning' => 'To violate / To break',
                'meaning_zh' => '违反',
                'example_sentence' => '违反规定。',
                'example_translation' => 'Violate regulations.',
                'definition' => 'To violate, to break, to go against',
                'sentences' => ['___法律。', '___纪律。', '___规则。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '惩罚',
                'pinyin' => 'chéng fá',
                'simplified' => '惩罚',
                'traditional' => '懲罰',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To punish / Punishment',
                'meaning_zh' => '惩罚',
                'example_sentence' => '受到惩罚。',
                'example_translation' => 'Receive punishment.',
                'definition' => 'To punish, punishment',
                'sentences' => ['___措施。', '___制度。', '___他。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '罚款',
                'pinyin' => 'fá kuǎn',
                'simplified' => '罚款',
                'traditional' => '罰款',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To fine / Fine / Penalty',
                'meaning_zh' => '罚款',
                'example_sentence' => '罚款200元。',
                'example_translation' => 'Fine of 200 yuan.',
                'definition' => 'To fine, fine, penalty',
                'sentences' => ['___单。', '___通知。', '___处罚。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '监狱',
                'pinyin' => 'jiān yù',
                'simplified' => '监狱',
                'traditional' => '監獄',
                'part_of_speech' => 'noun',
                'meaning' => 'Prison / Jail',
                'meaning_zh' => '监狱',
                'example_sentence' => '在监狱。',
                'example_translation' => 'In prison.',
                'definition' => 'Prison, jail',
                'sentences' => ['___生活。', '___服刑。', '___管理。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '安全',
                'pinyin' => 'ān quán',
                'simplified' => '安全',
                'traditional' => '安全',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Safe / Safety / Security',
                'meaning_zh' => '安全',
                'example_sentence' => '注意安全。',
                'example_translation' => 'Pay attention to safety.',
                'definition' => 'Safe, safety, security',
                'sentences' => ['___措施。', '___检查。', '___第一。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '保护',
                'pinyin' => 'bǎo hù',
                'simplified' => '保护',
                'traditional' => '保護',
                'part_of_speech' => 'verb',
                'meaning' => 'To protect',
                'meaning_zh' => '保护',
                'example_sentence' => '保护环境。',
                'example_translation' => 'Protect environment.',
                'definition' => 'To protect, to safeguard',
                'sentences' => ['___措施。', '___自己。', '___权利。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '公平',
                'pinyin' => 'gōng píng',
                'simplified' => '公平',
                'traditional' => '公平',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fair / Just / Impartial',
                'meaning_zh' => '公平',
                'example_sentence' => '公平对待。',
                'example_translation' => 'Treat fairly.',
                'definition' => 'Fair, just, impartial',
                'sentences' => ['___竞争。', '___公正。', '___合理。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '正义',
                'pinyin' => 'zhèng yì',
                'simplified' => '正义',
                'traditional' => '正義',
                'part_of_speech' => 'noun',
                'meaning' => 'Justice / Righteousness',
                'meaning_zh' => '正义',
                'example_sentence' => '维护正义。',
                'example_translation' => 'Uphold justice.',
                'definition' => 'Justice, righteousness',
                'sentences' => ['___感。', '___之士。', '___事业。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 103,
                'word' => '秩序',
                'pinyin' => 'zhì xù',
                'simplified' => '秩序',
                'traditional' => '秩序',
                'part_of_speech' => 'noun',
                'meaning' => 'Order / Sequence',
                'meaning_zh' => '秩序',
                'example_sentence' => '维持秩序。',
                'example_translation' => 'Maintain order.',
                'definition' => 'Order, sequence',
                'sentences' => ['___井然。', '___混乱。', '公共___。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 104: News and Media (新闻和媒体) - 20 words
        $mediaVocab = [
            [
                'topic_id' => 104,
                'word' => '新闻',
                'pinyin' => 'xīn wén',
                'simplified' => '新闻',
                'traditional' => '新聞',
                'part_of_speech' => 'noun',
                'meaning' => 'News',
                'meaning_zh' => '新闻',
                'example_sentence' => '看新闻。',
                'example_translation' => 'Watch news.',
                'definition' => 'News',
                'sentences' => ['___报道。', '___联播。', '___媒体。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '媒体',
                'pinyin' => 'méi tǐ',
                'simplified' => '媒体',
                'traditional' => '媒體',
                'part_of_speech' => 'noun',
                'meaning' => 'Media',
                'meaning_zh' => '媒体',
                'example_sentence' => '社交媒体。',
                'example_translation' => 'Social media.',
                'definition' => 'Media',
                'sentences' => ['___报道。', '___平台。', '___传播。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '报纸',
                'pinyin' => 'bào zhǐ',
                'simplified' => '报纸',
                'traditional' => '報紙',
                'part_of_speech' => 'noun',
                'meaning' => 'Newspaper',
                'meaning_zh' => '报纸',
                'example_sentence' => '读报纸。',
                'example_translation' => 'Read newspaper.',
                'definition' => 'Newspaper',
                'sentences' => ['___新闻。', '___杂志。', '订___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '杂志',
                'pinyin' => 'zá zhì',
                'simplified' => '杂志',
                'traditional' => '雜誌',
                'part_of_speech' => 'noun',
                'meaning' => 'Magazine',
                'meaning_zh' => '杂志',
                'example_sentence' => '时尚杂志。',
                'example_translation' => 'Fashion magazine.',
                'definition' => 'Magazine, journal',
                'sentences' => ['___社。', '___期刊。', '___文章。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '广播',
                'pinyin' => 'guǎng bō',
                'simplified' => '广播',
                'traditional' => '廣播',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Broadcast / To broadcast / Radio',
                'meaning_zh' => '广播',
                'example_sentence' => '听广播。',
                'example_translation' => 'Listen to radio.',
                'definition' => 'Broadcast, to broadcast, radio',
                'sentences' => ['___电台。', '___节目。', '___通知。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '电视',
                'pinyin' => 'diàn shì',
                'simplified' => '电视',
                'traditional' => '電視',
                'part_of_speech' => 'noun',
                'meaning' => 'Television / TV',
                'meaning_zh' => '电视',
                'example_sentence' => '看电视。',
                'example_translation' => 'Watch TV.',
                'definition' => 'Television, TV',
                'sentences' => ['___台。', '___节目。', '___剧。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '网络',
                'pinyin' => 'wǎng luò',
                'simplified' => '网络',
                'traditional' => '網絡',
                'part_of_speech' => 'noun',
                'meaning' => 'Network / Internet',
                'meaning_zh' => '网络',
                'example_sentence' => '上网络。',
                'example_translation' => 'Go online.',
                'definition' => 'Network, internet',
                'sentences' => ['___时代。', '___媒体。', '___安全。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '互联网',
                'pinyin' => 'hù lián wǎng',
                'simplified' => '互联网',
                'traditional' => '互聯網',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet',
                'meaning_zh' => '互联网',
                'example_sentence' => '互联网时代。',
                'example_translation' => 'Internet era.',
                'definition' => 'Internet',
                'sentences' => ['___公司。', '___技术。', '___发展。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '记者',
                'pinyin' => 'jì zhě',
                'simplified' => '记者',
                'traditional' => '記者',
                'part_of_speech' => 'noun',
                'meaning' => 'Reporter / Journalist',
                'meaning_zh' => '记者',
                'example_sentence' => '新闻记者。',
                'example_translation' => 'News reporter.',
                'definition' => 'Reporter, journalist',
                'sentences' => ['___采访。', '___会。', '___招待会。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '采访',
                'pinyin' => 'cǎi fǎng',
                'simplified' => '采访',
                'traditional' => '採訪',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To interview / Interview',
                'meaning_zh' => '采访',
                'example_sentence' => '接受采访。',
                'example_translation' => 'Accept interview.',
                'definition' => 'To interview, interview, to cover',
                'sentences' => ['___记者。', '___对象。', '___报道。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '报道',
                'pinyin' => 'bào dào',
                'simplified' => '报道',
                'traditional' => '報導',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To report / Report / News coverage',
                'meaning_zh' => '报道',
                'example_sentence' => '新闻报道。',
                'example_translation' => 'News report.',
                'definition' => 'To report, report, news coverage',
                'sentences' => ['___事件。', '___内容。', '___真实。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '发布',
                'pinyin' => 'fā bù',
                'simplified' => '发布',
                'traditional' => '發布',
                'part_of_speech' => 'verb',
                'meaning' => 'To release / To issue / To publish',
                'meaning_zh' => '发布',
                'example_sentence' => '发布消息。',
                'example_translation' => 'Release news.',
                'definition' => 'To release, to issue, to publish',
                'sentences' => ['___会。', '___信息。', '___公告。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '传播',
                'pinyin' => 'chuán bō',
                'simplified' => '传播',
                'traditional' => '傳播',
                'part_of_speech' => 'verb',
                'meaning' => 'To spread / To disseminate',
                'meaning_zh' => '传播',
                'example_sentence' => '传播知识。',
                'example_translation' => 'Spread knowledge.',
                'definition' => 'To spread, to disseminate, to propagate',
                'sentences' => ['___途径。', '___速度。', '___文化。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '消息',
                'pinyin' => 'xiāo xi',
                'simplified' => '消息',
                'traditional' => '消息',
                'part_of_speech' => 'noun',
                'meaning' => 'News / Information / Message',
                'meaning_zh' => '消息',
                'example_sentence' => '收到消息。',
                'example_translation' => 'Receive news.',
                'definition' => 'News, information, message',
                'sentences' => ['___来源。', '___真假。', '___灵通。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '信息',
                'pinyin' => 'xìn xī',
                'simplified' => '信息',
                'traditional' => '信息',
                'part_of_speech' => 'noun',
                'meaning' => 'Information',
                'meaning_zh' => '信息',
                'example_sentence' => '获取信息。',
                'example_translation' => 'Obtain information.',
                'definition' => 'Information',
                'sentences' => ['___时代。', '___技术。', '___量。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '内容',
                'pinyin' => 'nèi róng',
                'simplified' => '内容',
                'traditional' => '內容',
                'part_of_speech' => 'noun',
                'meaning' => 'Content / Substance',
                'meaning_zh' => '内容',
                'example_sentence' => '主要内容。',
                'example_translation' => 'Main content.',
                'definition' => 'Content, substance',
                'sentences' => ['___丰富。', '___简介。', '___摘要。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '标题',
                'pinyin' => 'biāo tí',
                'simplified' => '标题',
                'traditional' => '標題',
                'part_of_speech' => 'noun',
                'meaning' => 'Title / Headline',
                'meaning_zh' => '标题',
                'example_sentence' => '文章标题。',
                'example_translation' => 'Article title.',
                'definition' => 'Title, headline',
                'sentences' => ['___吸引人。', '___栏。', '___党。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '观点',
                'pinyin' => 'guān diǎn',
                'simplified' => '观点',
                'traditional' => '觀點',
                'part_of_speech' => 'noun',
                'meaning' => 'Viewpoint / Opinion',
                'meaning_zh' => '观点',
                'example_sentence' => '不同观点。',
                'example_translation' => 'Different viewpoints.',
                'definition' => 'Viewpoint, opinion, perspective',
                'sentences' => ['___鲜明。', '___一致。', '___表达。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '评论',
                'pinyin' => 'píng lùn',
                'simplified' => '评论',
                'traditional' => '評論',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To comment / Comment / Review',
                'meaning_zh' => '评论',
                'example_sentence' => '发表评论。',
                'example_translation' => 'Make comments.',
                'definition' => 'To comment, comment, review',
                'sentences' => ['___员。', '___区。', '___文章。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 104,
                'word' => '影响',
                'pinyin' => 'yǐng xiǎng',
                'simplified' => '影响',
                'traditional' => '影響',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To influence / Influence / Impact',
                'meaning_zh' => '影响',
                'example_sentence' => '有影响。',
                'example_translation' => 'Have influence.',
                'definition' => 'To influence, influence, impact',
                'sentences' => ['___力。', '___深远。', '___很大。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($emotionsVocab, $mannersVocab, $lawVocab, $mediaVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
