<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class Hsk4Topics21to24Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 113: Learning and Education (学习和教育) - 20 words
        $learningVocab = [
            [
                'topic_id' => 113,
                'word' => '学习',
                'pinyin' => 'xué xí',
                'simplified' => '学习',
                'traditional' => '學習',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To study / To learn / Learning',
                'meaning_zh' => '学习',
                'example_sentence' => '努力学习。',
                'example_translation' => 'Study hard.',
                'definition' => 'To study, to learn, learning',
                'sentences' => ['___知识。', '___方法。', '___成绩。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '教育',
                'pinyin' => 'jiào yù',
                'simplified' => '教育',
                'traditional' => '教育',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Education / To educate',
                'meaning_zh' => '教育',
                'example_sentence' => '教育事业。',
                'example_translation' => 'Educational cause.',
                'definition' => 'Education, to educate',
                'sentences' => ['___部。', '___工作者。', '___孩子。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '培养',
                'pinyin' => 'péi yǎng',
                'simplified' => '培养',
                'traditional' => '培養',
                'part_of_speech' => 'verb',
                'meaning' => 'To cultivate / To train / To foster',
                'meaning_zh' => '培养',
                'example_sentence' => '培养人才。',
                'example_translation' => 'Cultivate talent.',
                'definition' => 'To cultivate, to train, to foster',
                'sentences' => ['___兴趣。', '___能力。', '___习惯。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '训练',
                'pinyin' => 'xùn liàn',
                'simplified' => '训练',
                'traditional' => '訓練',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To train / Training',
                'meaning_zh' => '训练',
                'example_sentence' => '加强训练。',
                'example_translation' => 'Strengthen training.',
                'definition' => 'To train, training',
                'sentences' => ['___基地。', '___有素。', '___方法。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '掌握',
                'pinyin' => 'zhǎng wò',
                'simplified' => '掌握',
                'traditional' => '掌握',
                'part_of_speech' => 'verb',
                'meaning' => 'To master / To grasp / To control',
                'meaning_zh' => '掌握',
                'example_sentence' => '掌握技能。',
                'example_translation' => 'Master skills.',
                'definition' => 'To master, to grasp, to control',
                'sentences' => ['___知识。', '___方法。', '___主动权。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '熟悉',
                'pinyin' => 'shú xī',
                'simplified' => '熟悉',
                'traditional' => '熟悉',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Familiar / To be familiar with',
                'meaning_zh' => '熟悉',
                'example_sentence' => '很熟悉。',
                'example_translation' => 'Very familiar.',
                'definition' => 'Familiar, to be familiar with',
                'sentences' => ['___环境。', '___业务。', '___的地方。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '复习',
                'pinyin' => 'fù xí',
                'simplified' => '复习',
                'traditional' => '復習',
                'part_of_speech' => 'verb',
                'meaning' => 'To review / To revise',
                'meaning_zh' => '复习',
                'example_sentence' => '复习功课。',
                'example_translation' => 'Review lessons.',
                'definition' => 'To review, to revise',
                'sentences' => ['___考试。', '___资料。', '___一下。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '预习',
                'pinyin' => 'yù xí',
                'simplified' => '预习',
                'traditional' => '預習',
                'part_of_speech' => 'verb',
                'meaning' => 'To preview / To prepare lessons',
                'meaning_zh' => '预习',
                'example_sentence' => '预习课文。',
                'example_translation' => 'Preview the text.',
                'definition' => 'To preview, to prepare lessons',
                'sentences' => ['___新课。', '___内容。', '___作业。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '背',
                'pinyin' => 'bèi',
                'simplified' => '背',
                'traditional' => '背',
                'part_of_speech' => 'verb',
                'meaning' => 'To recite / To memorize / To carry on back',
                'meaning_zh' => '背',
                'example_sentence' => '背单词。',
                'example_translation' => 'Memorize words.',
                'definition' => 'To recite, to memorize, to learn by heart',
                'sentences' => ['___课文。', '___诵。', '___包。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '记忆',
                'pinyin' => 'jì yì',
                'simplified' => '记忆',
                'traditional' => '記憶',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To remember / Memory',
                'meaning_zh' => '记忆',
                'example_sentence' => '深刻记忆。',
                'example_translation' => 'Deep memory.',
                'definition' => 'To remember, memory',
                'sentences' => ['___力。', '___犹新。', '___方法。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To understand / Understanding',
                'meaning_zh' => '理解',
                'example_sentence' => '理解意思。',
                'example_translation' => 'Understand the meaning.',
                'definition' => 'To understand, understanding',
                'sentences' => ['___能力。', '___错误。', '___力。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '领会',
                'pinyin' => 'lǐng huì',
                'simplified' => '领会',
                'traditional' => '領會',
                'part_of_speech' => 'verb',
                'meaning' => 'To understand / To comprehend / To grasp',
                'meaning_zh' => '领会',
                'example_sentence' => '领会精神。',
                'example_translation' => 'Grasp the essence.',
                'definition' => 'To understand, to comprehend, to grasp',
                'sentences' => ['___意图。', '___深刻。', '___内容。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '研究',
                'pinyin' => 'yán jiū',
                'simplified' => '研究',
                'traditional' => '研究',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To research / To study / Research',
                'meaning_zh' => '研究',
                'example_sentence' => '研究问题。',
                'example_translation' => 'Research problems.',
                'definition' => 'To research, to study, research',
                'sentences' => ['___生。', '___所。', '___成果。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '探索',
                'pinyin' => 'tàn suǒ',
                'simplified' => '探索',
                'traditional' => '探索',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To explore / To probe / Exploration',
                'meaning_zh' => '探索',
                'example_sentence' => '探索真理。',
                'example_translation' => 'Explore truth.',
                'definition' => 'To explore, to probe, exploration',
                'sentences' => ['___之路。', '___精神。', '___研究。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '实践',
                'pinyin' => 'shí jiàn',
                'simplified' => '实践',
                'traditional' => '實踐',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Practice / To practice / To put into practice',
                'meaning_zh' => '实践',
                'example_sentence' => '理论与实践。',
                'example_translation' => 'Theory and practice.',
                'definition' => 'Practice, to practice, to put into practice',
                'sentences' => ['___经验。', '___活动。', '___证明。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '积累',
                'pinyin' => 'jī lěi',
                'simplified' => '积累',
                'traditional' => '積累',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To accumulate / To amass / Accumulation',
                'meaning_zh' => '积累',
                'example_sentence' => '积累经验。',
                'example_translation' => 'Accumulate experience.',
                'definition' => 'To accumulate, to amass, accumulation',
                'sentences' => ['___知识。', '___财富。', '___资金。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '总结',
                'pinyin' => 'zǒng jié',
                'simplified' => '总结',
                'traditional' => '總結',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To summarize / Summary',
                'meaning_zh' => '总结',
                'example_sentence' => '总结经验。',
                'example_translation' => 'Summarize experience.',
                'definition' => 'To summarize, summary',
                'sentences' => ['___工作。', '___会。', '___报告。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '成绩',
                'pinyin' => 'chéng jì',
                'simplified' => '成绩',
                'traditional' => '成績',
                'part_of_speech' => 'noun',
                'meaning' => 'Achievement / Grade / Result',
                'meaning_zh' => '成绩',
                'example_sentence' => '优秀成绩。',
                'example_translation' => 'Excellent grades.',
                'definition' => 'Achievement, grade, result',
                'sentences' => ['___单。', '___好。', '考试___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '水平',
                'pinyin' => 'shuǐ píng',
                'simplified' => '水平',
                'traditional' => '水平',
                'part_of_speech' => 'noun',
                'meaning' => 'Level / Standard',
                'meaning_zh' => '水平',
                'example_sentence' => '提高水平。',
                'example_translation' => 'Improve level.',
                'definition' => 'Level, standard',
                'sentences' => ['___高。', '___测试。', '___线。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 113,
                'word' => '能力',
                'pinyin' => 'néng lì',
                'simplified' => '能力',
                'traditional' => '能力',
                'part_of_speech' => 'noun',
                'meaning' => 'Ability / Capability / Capacity',
                'meaning_zh' => '能力',
                'example_sentence' => '工作能力。',
                'example_translation' => 'Work ability.',
                'definition' => 'Ability, capability, capacity',
                'sentences' => ['___强。', '___培养。', '___范围。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 114: Innovation and Creativity (创新和创造) - 20 words
        $innovationVocab = [
            [
                'topic_id' => 114,
                'word' => '创新',
                'pinyin' => 'chuàng xīn',
                'simplified' => '创新',
                'traditional' => '創新',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To innovate / Innovation',
                'meaning_zh' => '创新',
                'example_sentence' => '鼓励创新。',
                'example_translation' => 'Encourage innovation.',
                'definition' => 'To innovate, innovation',
                'sentences' => ['___精神。', '___能力。', '___思维。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '创造',
                'pinyin' => 'chuàng zào',
                'simplified' => '创造',
                'traditional' => '創造',
                'part_of_speech' => 'verb',
                'meaning' => 'To create / To produce',
                'meaning_zh' => '创造',
                'example_sentence' => '创造价值。',
                'example_translation' => 'Create value.',
                'definition' => 'To create, to produce',
                'sentences' => ['___力。', '___条件。', '___奇迹。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '发明',
                'pinyin' => 'fā míng',
                'simplified' => '发明',
                'traditional' => '發明',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To invent / Invention',
                'meaning_zh' => '发明',
                'example_sentence' => '发明家。',
                'example_translation' => 'Inventor.',
                'definition' => 'To invent, invention',
                'sentences' => ['___专利。', '___者。', '伟大___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '发现',
                'pinyin' => 'fā xiàn',
                'simplified' => '发现',
                'traditional' => '發現',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To discover / To find / Discovery',
                'meaning_zh' => '发现',
                'example_sentence' => '重大发现。',
                'example_translation' => 'Major discovery.',
                'definition' => 'To discover, to find, discovery',
                'sentences' => ['___问题。', '___了。', '___者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '设计',
                'pinyin' => 'shè jì',
                'simplified' => '设计',
                'traditional' => '設計',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To design / Design',
                'meaning_zh' => '设计',
                'example_sentence' => '设计方案。',
                'example_translation' => 'Design plan.',
                'definition' => 'To design, design',
                'sentences' => ['___师。', '___理念。', '___图。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '改进',
                'pinyin' => 'gǎi jìn',
                'simplified' => '改进',
                'traditional' => '改進',
                'part_of_speech' => 'verb',
                'meaning' => 'To improve / To make better',
                'meaning_zh' => '改进',
                'example_sentence' => '改进方法。',
                'example_translation' => 'Improve methods.',
                'definition' => 'To improve, to make better',
                'sentences' => ['___工作。', '___技术。', '___措施。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '改善',
                'pinyin' => 'gǎi shàn',
                'simplified' => '改善',
                'traditional' => '改善',
                'part_of_speech' => 'verb',
                'meaning' => 'To improve / To ameliorate',
                'meaning_zh' => '改善',
                'example_sentence' => '改善生活。',
                'example_translation' => 'Improve life.',
                'definition' => 'To improve, to ameliorate',
                'sentences' => ['___关系。', '___条件。', '___环境。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '改革',
                'pinyin' => 'gǎi gé',
                'simplified' => '改革',
                'traditional' => '改革',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To reform / Reform',
                'meaning_zh' => '改革',
                'example_sentence' => '教育改革。',
                'example_translation' => 'Educational reform.',
                'definition' => 'To reform, reform',
                'sentences' => ['___开放。', '___方案。', '___措施。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '革命',
                'pinyin' => 'gé mìng',
                'simplified' => '革命',
                'traditional' => '革命',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Revolution / Revolutionary',
                'meaning_zh' => '革命',
                'example_sentence' => '工业革命。',
                'example_translation' => 'Industrial revolution.',
                'definition' => 'Revolution, revolutionary',
                'sentences' => ['___性。', '___历史。', '___者。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '突破',
                'pinyin' => 'tū pò',
                'simplified' => '突破',
                'traditional' => '突破',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To break through / Breakthrough',
                'meaning_zh' => '突破',
                'example_sentence' => '重大突破。',
                'example_translation' => 'Major breakthrough.',
                'definition' => 'To break through, breakthrough',
                'sentences' => ['___口。', '___自我。', '___点。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '进步',
                'pinyin' => 'jìn bù',
                'simplified' => '进步',
                'traditional' => '進步',
                'part_of_speech' => 'verb/noun/adjective',
                'meaning' => 'Progress / To progress / Progressive',
                'meaning_zh' => '进步',
                'example_sentence' => '取得进步。',
                'example_translation' => 'Make progress.',
                'definition' => 'Progress, to progress, progressive',
                'sentences' => ['___很大。', '___性。', '___奖。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '提高',
                'pinyin' => 'tí gāo',
                'simplified' => '提高',
                'traditional' => '提高',
                'part_of_speech' => 'verb',
                'meaning' => 'To improve / To raise / To increase',
                'meaning_zh' => '提高',
                'example_sentence' => '提高质量。',
                'example_translation' => 'Improve quality.',
                'definition' => 'To improve, to raise, to increase',
                'sentences' => ['___水平。', '___效率。', '___认识。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '发展',
                'pinyin' => 'fā zhǎn',
                'simplified' => '发展',
                'traditional' => '發展',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To develop / Development',
                'meaning_zh' => '发展',
                'example_sentence' => '快速发展。',
                'example_translation' => 'Rapid development.',
                'definition' => 'To develop, development',
                'sentences' => ['___中国家。', '___战略。', '___趋势。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '成功',
                'pinyin' => 'chéng gōng',
                'simplified' => '成功',
                'traditional' => '成功',
                'part_of_speech' => 'verb/noun/adjective',
                'meaning' => 'Success / To succeed / Successful',
                'meaning_zh' => '成功',
                'example_sentence' => '获得成功。',
                'example_translation' => 'Achieve success.',
                'definition' => 'Success, to succeed, successful',
                'sentences' => ['___了。', '___经验。', '___人士。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '失败',
                'pinyin' => 'shī bài',
                'simplified' => '失败',
                'traditional' => '失敗',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To fail / Failure',
                'meaning_zh' => '失败',
                'example_sentence' => '遭受失败。',
                'example_translation' => 'Suffer failure.',
                'definition' => 'To fail, failure',
                'sentences' => ['___了。', '___原因。', '___是成功之母。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '成就',
                'pinyin' => 'chéng jiù',
                'simplified' => '成就',
                'traditional' => '成就',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Achievement / Accomplishment / To achieve',
                'meaning_zh' => '成就',
                'example_sentence' => '巨大成就。',
                'example_translation' => 'Great achievement.',
                'definition' => 'Achievement, accomplishment, to achieve',
                'sentences' => ['___感。', '___奖。', '___事业。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '完成',
                'pinyin' => 'wán chéng',
                'simplified' => '完成',
                'traditional' => '完成',
                'part_of_speech' => 'verb',
                'meaning' => 'To complete / To finish / To accomplish',
                'meaning_zh' => '完成',
                'example_sentence' => '完成任务。',
                'example_translation' => 'Complete the task.',
                'definition' => 'To complete, to finish, to accomplish',
                'sentences' => ['___了。', '___工作。', '___目标。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '实现',
                'pinyin' => 'shí xiàn',
                'simplified' => '实现',
                'traditional' => '實現',
                'part_of_speech' => 'verb',
                'meaning' => 'To realize / To achieve / To bring about',
                'meaning_zh' => '实现',
                'example_sentence' => '实现梦想。',
                'example_translation' => 'Realize dreams.',
                'definition' => 'To realize, to achieve, to bring about',
                'sentences' => ['___目标。', '___了。', '___价值。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '达到',
                'pinyin' => 'dá dào',
                'simplified' => '达到',
                'traditional' => '達到',
                'part_of_speech' => 'verb',
                'meaning' => 'To reach / To achieve / To attain',
                'meaning_zh' => '达到',
                'example_sentence' => '达到目的。',
                'example_translation' => 'Achieve the goal.',
                'definition' => 'To reach, to achieve, to attain',
                'sentences' => ['___标准。', '___水平。', '___要求。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 114,
                'word' => '获得',
                'pinyin' => 'huò dé',
                'simplified' => '获得',
                'traditional' => '獲得',
                'part_of_speech' => 'verb',
                'meaning' => 'To obtain / To gain / To acquire',
                'meaning_zh' => '获得',
                'example_sentence' => '获得成功。',
                'example_translation' => 'Gain success.',
                'definition' => 'To obtain, to gain, to acquire',
                'sentences' => ['___奖。', '___认可。', '___批准。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 115: Technology and Modern Life (科技和现代生活) - 20 words
        $technologyVocab = [
            [
                'topic_id' => 115,
                'word' => '科技',
                'pinyin' => 'kē jì',
                'simplified' => '科技',
                'traditional' => '科技',
                'part_of_speech' => 'noun',
                'meaning' => 'Science and technology',
                'meaning_zh' => '科技',
                'example_sentence' => '科技发展。',
                'example_translation' => 'Technology development.',
                'definition' => 'Science and technology',
                'sentences' => ['___创新。', '___进步。', '高___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '技术',
                'pinyin' => 'jì shù',
                'simplified' => '技术',
                'traditional' => '技術',
                'part_of_speech' => 'noun',
                'meaning' => 'Technology / Technique / Skill',
                'meaning_zh' => '技术',
                'example_sentence' => '先进技术。',
                'example_translation' => 'Advanced technology.',
                'definition' => 'Technology, technique, skill',
                'sentences' => ['___人员。', '___水平。', '___革新。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '电脑',
                'pinyin' => 'diàn nǎo',
                'simplified' => '电脑',
                'traditional' => '電腦',
                'part_of_speech' => 'noun',
                'meaning' => 'Computer',
                'meaning_zh' => '电脑',
                'example_sentence' => '用电脑工作。',
                'example_translation' => 'Work with computer.',
                'definition' => 'Computer',
                'sentences' => ['___游戏。', '___病毒。', '笔记本___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '网络',
                'pinyin' => 'wǎng luò',
                'simplified' => '网络',
                'traditional' => '網絡',
                'part_of_speech' => 'noun',
                'meaning' => 'Network / Internet',
                'meaning_zh' => '网络',
                'example_sentence' => '上网络。',
                'example_translation' => 'Go online.',
                'definition' => 'Network, internet',
                'sentences' => ['___时代。', '___安全。', '___游戏。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '软件',
                'pinyin' => 'ruǎn jiàn',
                'simplified' => '软件',
                'traditional' => '軟件',
                'part_of_speech' => 'noun',
                'meaning' => 'Software',
                'meaning_zh' => '软件',
                'example_sentence' => '安装软件。',
                'example_translation' => 'Install software.',
                'definition' => 'Software',
                'sentences' => ['___开发。', '___工程师。', '___公司。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '系统',
                'pinyin' => 'xì tǒng',
                'simplified' => '系统',
                'traditional' => '系統',
                'part_of_speech' => 'noun',
                'meaning' => 'System',
                'meaning_zh' => '系统',
                'example_sentence' => '操作系统。',
                'example_translation' => 'Operating system.',
                'definition' => 'System',
                'sentences' => ['___工程。', '___分析。', '___化。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '数据',
                'pinyin' => 'shù jù',
                'simplified' => '数据',
                'traditional' => '數據',
                'part_of_speech' => 'noun',
                'meaning' => 'Data',
                'meaning_zh' => '数据',
                'example_sentence' => '收集数据。',
                'example_translation' => 'Collect data.',
                'definition' => 'Data',
                'sentences' => ['___库。', '___分析。', '___统计。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '信息',
                'pinyin' => 'xìn xī',
                'simplified' => '信息',
                'traditional' => '信息',
                'part_of_speech' => 'noun',
                'meaning' => 'Information',
                'meaning_zh' => '信息',
                'example_sentence' => '获取信息。',
                'example_translation' => 'Get information.',
                'definition' => 'Information',
                'sentences' => ['___时代。', '___技术。', '___化。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '智能',
                'pinyin' => 'zhì néng',
                'simplified' => '智能',
                'traditional' => '智能',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Intelligence / Smart / Intelligent',
                'meaning_zh' => '智能',
                'example_sentence' => '人工智能。',
                'example_translation' => 'Artificial intelligence.',
                'definition' => 'Intelligence, smart, intelligent',
                'sentences' => ['___手机。', '___化。', '___家居。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '自动',
                'pinyin' => 'zì dòng',
                'simplified' => '自动',
                'traditional' => '自動',
                'part_of_speech' => 'adjective/adverb',
                'meaning' => 'Automatic / Automatically',
                'meaning_zh' => '自动',
                'example_sentence' => '自动化。',
                'example_translation' => 'Automation.',
                'definition' => 'Automatic, automatically',
                'sentences' => ['___门。', '___化。', '___回复。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '功能',
                'pinyin' => 'gōng néng',
                'simplified' => '功能',
                'traditional' => '功能',
                'part_of_speech' => 'noun',
                'meaning' => 'Function / Feature',
                'meaning_zh' => '功能',
                'example_sentence' => '强大功能。',
                'example_translation' => 'Powerful function.',
                'definition' => 'Function, feature',
                'sentences' => ['___齐全。', '___键。', '___室。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '设备',
                'pinyin' => 'shè bèi',
                'simplified' => '设备',
                'traditional' => '設備',
                'part_of_speech' => 'noun',
                'meaning' => 'Equipment / Facility / Device',
                'meaning_zh' => '设备',
                'example_sentence' => '先进设备。',
                'example_translation' => 'Advanced equipment.',
                'definition' => 'Equipment, facility, device',
                'sentences' => ['___齐全。', '___维修。', '___更新。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '装置',
                'pinyin' => 'zhuāng zhì',
                'simplified' => '装置',
                'traditional' => '裝置',
                'part_of_speech' => 'noun',
                'meaning' => 'Device / Installation / Apparatus',
                'meaning_zh' => '装置',
                'example_sentence' => '安全装置。',
                'example_translation' => 'Safety device.',
                'definition' => 'Device, installation, apparatus',
                'sentences' => ['___艺术。', '___完善。', '自动___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '工具',
                'pinyin' => 'gōng jù',
                'simplified' => '工具',
                'traditional' => '工具',
                'part_of_speech' => 'noun',
                'meaning' => 'Tool / Instrument',
                'meaning_zh' => '工具',
                'example_sentence' => '使用工具。',
                'example_translation' => 'Use tools.',
                'definition' => 'Tool, instrument',
                'sentences' => ['___箱。', '___软件。', '___书。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '操作',
                'pinyin' => 'cāo zuò',
                'simplified' => '操作',
                'traditional' => '操作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To operate / Operation',
                'meaning_zh' => '操作',
                'example_sentence' => '简单操作。',
                'example_translation' => 'Simple operation.',
                'definition' => 'To operate, operation',
                'sentences' => ['___系统。', '___方法。', '___员。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '使用',
                'pinyin' => 'shǐ yòng',
                'simplified' => '使用',
                'traditional' => '使用',
                'part_of_speech' => 'verb',
                'meaning' => 'To use / To employ',
                'meaning_zh' => '使用',
                'example_sentence' => '正确使用。',
                'example_translation' => 'Use correctly.',
                'definition' => 'To use, to employ',
                'sentences' => ['___方法。', '___说明。', '___寿命。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '应用',
                'pinyin' => 'yìng yòng',
                'simplified' => '应用',
                'traditional' => '應用',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To apply / Application',
                'meaning_zh' => '应用',
                'example_sentence' => '广泛应用。',
                'example_translation' => 'Wide application.',
                'definition' => 'To apply, application',
                'sentences' => ['___程序。', '___科学。', '___技术。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '效率',
                'pinyin' => 'xiào lǜ',
                'simplified' => '效率',
                'traditional' => '效率',
                'part_of_speech' => 'noun',
                'meaning' => 'Efficiency',
                'meaning_zh' => '效率',
                'example_sentence' => '提高效率。',
                'example_translation' => 'Improve efficiency.',
                'definition' => 'Efficiency',
                'sentences' => ['工作___。', '___高。', '___低。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '方便',
                'pinyin' => 'fāng biàn',
                'simplified' => '方便',
                'traditional' => '方便',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Convenient / Convenience / To make convenient',
                'meaning_zh' => '方便',
                'example_sentence' => '很方便。',
                'example_translation' => 'Very convenient.',
                'definition' => 'Convenient, convenience, to make convenient',
                'sentences' => ['___面。', '___快捷。', '___店。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 115,
                'word' => '现代',
                'pinyin' => 'xiàn dài',
                'simplified' => '现代',
                'traditional' => '現代',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Modern / Contemporary',
                'meaning_zh' => '现代',
                'example_sentence' => '现代化。',
                'example_translation' => 'Modernization.',
                'definition' => 'Modern, contemporary',
                'sentences' => ['___社会。', '___生活。', '___艺术。'],
                'level' => 'HSK4',
            ],
        ];

        // Topic 116: Social Issues and Values (社会问题和价值观) - 20 words
        $socialVocab = [
            [
                'topic_id' => 116,
                'word' => '社会',
                'pinyin' => 'shè huì',
                'simplified' => '社会',
                'traditional' => '社會',
                'part_of_speech' => 'noun',
                'meaning' => 'Society / Social',
                'meaning_zh' => '社会',
                'example_sentence' => '社会发展。',
                'example_translation' => 'Social development.',
                'definition' => 'Society, social',
                'sentences' => ['___主义。', '___问题。', '___科学。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '公平',
                'pinyin' => 'gōng píng',
                'simplified' => '公平',
                'traditional' => '公平',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Fair / Just / Fairness',
                'meaning_zh' => '公平',
                'example_sentence' => '公平竞争。',
                'example_translation' => 'Fair competition.',
                'definition' => 'Fair, just, fairness',
                'sentences' => ['___合理。', '___正义。', '___交易。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '正义',
                'pinyin' => 'zhèng yì',
                'simplified' => '正义',
                'traditional' => '正義',
                'part_of_speech' => 'noun',
                'meaning' => 'Justice / Righteousness',
                'meaning_zh' => '正义',
                'example_sentence' => '维护正义。',
                'example_translation' => 'Uphold justice.',
                'definition' => 'Justice, righteousness',
                'sentences' => ['___感。', '___之士。', '___事业。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '平等',
                'pinyin' => 'píng děng',
                'simplified' => '平等',
                'traditional' => '平等',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Equal / Equality',
                'meaning_zh' => '平等',
                'example_sentence' => '人人平等。',
                'example_translation' => 'Everyone is equal.',
                'definition' => 'Equal, equality',
                'sentences' => ['___权利。', '男女___。', '___对待。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '自由',
                'pinyin' => 'zì yóu',
                'simplified' => '自由',
                'traditional' => '自由',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Freedom / Free / Liberty',
                'meaning_zh' => '自由',
                'example_sentence' => '言论自由。',
                'example_translation' => 'Freedom of speech.',
                'definition' => 'Freedom, free, liberty',
                'sentences' => ['___民主。', '___职业。', '___泳。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '民主',
                'pinyin' => 'mín zhǔ',
                'simplified' => '民主',
                'traditional' => '民主',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Democracy / Democratic',
                'meaning_zh' => '民主',
                'example_sentence' => '民主制度。',
                'example_translation' => 'Democratic system.',
                'definition' => 'Democracy, democratic',
                'sentences' => ['___党。', '___权利。', '___集中。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '责任',
                'pinyin' => 'zé rèn',
                'simplified' => '责任',
                'traditional' => '責任',
                'part_of_speech' => 'noun',
                'meaning' => 'Responsibility / Duty',
                'meaning_zh' => '责任',
                'example_sentence' => '承担责任。',
                'example_translation' => 'Take responsibility.',
                'definition' => 'Responsibility, duty',
                'sentences' => ['___心。', '___感。', '___重大。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '义务',
                'pinyin' => 'yì wù',
                'simplified' => '义务',
                'traditional' => '義務',
                'part_of_speech' => 'noun',
                'meaning' => 'Duty / Obligation',
                'meaning_zh' => '义务',
                'example_sentence' => '尽义务。',
                'example_translation' => 'Fulfill duty.',
                'definition' => 'Duty, obligation',
                'sentences' => ['___教育。', '___劳动。', '___兵。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '道德',
                'pinyin' => 'dào dé',
                'simplified' => '道德',
                'traditional' => '道德',
                'part_of_speech' => 'noun',
                'meaning' => 'Morality / Ethics / Moral',
                'meaning_zh' => '道德',
                'example_sentence' => '社会道德。',
                'example_translation' => 'Social morality.',
                'definition' => 'Morality, ethics, moral',
                'sentences' => ['___标准。', '___品质。', '___教育。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '良心',
                'pinyin' => 'liáng xīn',
                'simplified' => '良心',
                'traditional' => '良心',
                'part_of_speech' => 'noun',
                'meaning' => 'Conscience',
                'meaning_zh' => '良心',
                'example_sentence' => '凭良心说。',
                'example_translation' => 'In conscience.',
                'definition' => 'Conscience',
                'sentences' => ['___话。', '___发现。', '___不安。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '诚实',
                'pinyin' => 'chéng shí',
                'simplified' => '诚实',
                'traditional' => '誠實',
                'part_of_speech' => 'adjective',
                'meaning' => 'Honest / Truthful',
                'meaning_zh' => '诚实',
                'example_sentence' => '诚实可靠。',
                'example_translation' => 'Honest and reliable.',
                'definition' => 'Honest, truthful',
                'sentences' => ['___守信。', '___的人。', '___回答。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '诚信',
                'pinyin' => 'chéng xìn',
                'simplified' => '诚信',
                'traditional' => '誠信',
                'part_of_speech' => 'noun',
                'meaning' => 'Integrity / Good faith / Honesty',
                'meaning_zh' => '诚信',
                'example_sentence' => '讲诚信。',
                'example_translation' => 'Have integrity.',
                'definition' => 'Integrity, good faith, honesty',
                'sentences' => ['___经营。', '___原则。', '___体系。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '贡献',
                'pinyin' => 'gòng xiàn',
                'simplified' => '贡献',
                'traditional' => '貢獻',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To contribute / Contribution',
                'meaning_zh' => '贡献',
                'example_sentence' => '做出贡献。',
                'example_translation' => 'Make contributions.',
                'definition' => 'To contribute, contribution',
                'sentences' => ['___力量。', '___奖。', '巨大___。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '奉献',
                'pinyin' => 'fèng xiàn',
                'simplified' => '奉献',
                'traditional' => '奉獻',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To dedicate / Dedication / To devote',
                'meaning_zh' => '奉献',
                'example_sentence' => '无私奉献。',
                'example_translation' => 'Selfless dedication.',
                'definition' => 'To dedicate, dedication, to devote',
                'sentences' => ['___精神。', '___爱心。', '___一生。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '牺牲',
                'pinyin' => 'xī shēng',
                'simplified' => '牺牲',
                'traditional' => '犧牲',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To sacrifice / Sacrifice',
                'meaning_zh' => '牺牲',
                'example_sentence' => '做出牺牲。',
                'example_translation' => 'Make sacrifices.',
                'definition' => 'To sacrifice, sacrifice',
                'sentences' => ['___精神。', '___自己。', '___品。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '互相',
                'pinyin' => 'hù xiāng',
                'simplified' => '互相',
                'traditional' => '互相',
                'part_of_speech' => 'adverb',
                'meaning' => 'Mutually / Each other',
                'meaning_zh' => '互相',
                'example_sentence' => '互相帮助。',
                'example_translation' => 'Help each other.',
                'definition' => 'Mutually, each other',
                'sentences' => ['___尊重。', '___理解。', '___学习。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '和谐',
                'pinyin' => 'hé xié',
                'simplified' => '和谐',
                'traditional' => '和諧',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Harmonious / Harmony',
                'meaning_zh' => '和谐',
                'example_sentence' => '和谐社会。',
                'example_translation' => 'Harmonious society.',
                'definition' => 'Harmonious, harmony',
                'sentences' => ['___发展。', '___相处。', '___统一。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '团结',
                'pinyin' => 'tuán jié',
                'simplified' => '团结',
                'traditional' => '團結',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To unite / Unity / United',
                'meaning_zh' => '团结',
                'example_sentence' => '团结一致。',
                'example_translation' => 'United as one.',
                'definition' => 'To unite, unity, united',
                'sentences' => ['___合作。', '___友爱。', '___起来。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '合作',
                'pinyin' => 'hé zuò',
                'simplified' => '合作',
                'traditional' => '合作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To cooperate / Cooperation',
                'meaning_zh' => '合作',
                'example_sentence' => '友好合作。',
                'example_translation' => 'Friendly cooperation.',
                'definition' => 'To cooperate, cooperation',
                'sentences' => ['___伙伴。', '___精神。', '___项目。'],
                'level' => 'HSK4',
            ],
            [
                'topic_id' => 116,
                'word' => '矛盾',
                'pinyin' => 'máo dùn',
                'simplified' => '矛盾',
                'traditional' => '矛盾',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Contradiction / Conflicting',
                'meaning_zh' => '矛盾',
                'example_sentence' => '解决矛盾。',
                'example_translation' => 'Resolve contradictions.',
                'definition' => 'Contradiction, conflicting',
                'sentences' => ['___冲突。', '___的话。', '___心理。'],
                'level' => 'HSK4',
            ],
        ];

        // Insert all vocabularies
        foreach (array_merge($learningVocab, $innovationVocab, $technologyVocab, $socialVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
