<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic126to129Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [126, 129])->delete();

        // Topic 126: Customs and Traditions - 习俗与传统
        $customsVocab = [
            [
                'topic_id' => 126,
                'word' => '习俗',
                'pinyin' => 'xí sú',
                'simplified' => '习俗',
                'traditional' => '習俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Convention',
                'meaning_zh' => '习俗',
                'example_sentence' => '每个地方都有不同的习俗。',
                'example_translation' => 'Every place has different customs.',
                'definition' => 'Custom, convention, traditional practice',
                'sentences' => ['传统___。', '民间___。', '___文化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '我们要继承优秀传统。',
                'example_translation' => 'We should inherit excellent traditions.',
                'definition' => 'Tradition, traditional, conventional',
                'sentences' => ['___文化。', '___节日。', '___观念。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '风俗',
                'pinyin' => 'fēng sú',
                'simplified' => '风俗',
                'traditional' => '風俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Social custom',
                'meaning_zh' => '风俗',
                'example_sentence' => '了解当地风俗很重要。',
                'example_translation' => 'Understanding local customs is important.',
                'definition' => 'Custom, social custom, folkway',
                'sentences' => ['民间___。', '___习惯。', '___人情。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '节日',
                'pinyin' => 'jié rì',
                'simplified' => '节日',
                'traditional' => '節日',
                'part_of_speech' => 'noun',
                'meaning' => 'Festival / Holiday',
                'meaning_zh' => '节日',
                'example_sentence' => '春节是中国最重要的节日。',
                'example_translation' => 'Spring Festival is China\'s most important holiday.',
                'definition' => 'Festival, holiday, feast day',
                'sentences' => ['传统___。', '___庆祝。', '___气氛。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '礼节',
                'pinyin' => 'lǐ jié',
                'simplified' => '礼节',
                'traditional' => '禮節',
                'part_of_speech' => 'noun',
                'meaning' => 'Etiquette / Protocol',
                'meaning_zh' => '礼节',
                'example_sentence' => '要注意礼节。',
                'example_translation' => 'Pay attention to etiquette.',
                'definition' => 'Etiquette, protocol, courtesy',
                'sentences' => ['讲究___。', '___规矩。', '社交___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '仪式',
                'pinyin' => 'yí shì',
                'simplified' => '仪式',
                'traditional' => '儀式',
                'part_of_speech' => 'noun',
                'meaning' => 'Ceremony / Ritual',
                'meaning_zh' => '仪式',
                'example_sentence' => '婚礼仪式很隆重。',
                'example_translation' => 'The wedding ceremony was very grand.',
                'definition' => 'Ceremony, ritual, rite',
                'sentences' => ['举行___。', '___感。', '开幕___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '庆祝',
                'pinyin' => 'qìng zhù',
                'simplified' => '庆祝',
                'traditional' => '慶祝',
                'part_of_speech' => 'verb',
                'meaning' => 'To celebrate',
                'meaning_zh' => '庆祝',
                'example_sentence' => '我们庆祝新年的到来。',
                'example_translation' => 'We celebrate the arrival of the new year.',
                'definition' => 'To celebrate, to observe',
                'sentences' => ['___节日。', '___胜利。', '___活动。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '祭祀',
                'pinyin' => 'jì sì',
                'simplified' => '祭祀',
                'traditional' => '祭祀',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To offer sacrifices / Sacrifice ceremony',
                'meaning_zh' => '祭祀',
                'example_sentence' => '清明节要祭祀祖先。',
                'example_translation' => 'We offer sacrifices to ancestors during Qingming Festival.',
                'definition' => 'To offer sacrifices, sacrifice ceremony',
                'sentences' => ['___祖先。', '___活动。', '___仪式。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '拜年',
                'pinyin' => 'bài nián',
                'simplified' => '拜年',
                'traditional' => '拜年',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay a New Year call',
                'meaning_zh' => '拜年',
                'example_sentence' => '春节期间要去拜年。',
                'example_translation' => 'We visit relatives to pay New Year calls during Spring Festival.',
                'definition' => 'To pay a New Year call, New Year visit',
                'sentences' => ['去___。', '___拜访。', '___礼物。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '红包',
                'pinyin' => 'hóng bāo',
                'simplified' => '红包',
                'traditional' => '紅包',
                'part_of_speech' => 'noun',
                'meaning' => 'Red envelope / Money gift',
                'meaning_zh' => '红包',
                'example_sentence' => '过年长辈会给孩子红包。',
                'example_translation' => 'Elders give children red envelopes during New Year.',
                'definition' => 'Red envelope containing money as gift',
                'sentences' => ['发___。', '___钱。', '收___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '鞭炮',
                'pinyin' => 'biān pào',
                'simplified' => '鞭炮',
                'traditional' => '鞭炮',
                'part_of_speech' => 'noun',
                'meaning' => 'Firecrackers',
                'meaning_zh' => '鞭炮',
                'example_sentence' => '过年要放鞭炮。',
                'example_translation' => 'We set off firecrackers during New Year.',
                'definition' => 'Firecrackers, fireworks',
                'sentences' => ['放___。', '___声。', '___烟花。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '灯笼',
                'pinyin' => 'dēng long',
                'simplified' => '灯笼',
                'traditional' => '燈籠',
                'part_of_speech' => 'noun',
                'meaning' => 'Lantern',
                'meaning_zh' => '灯笼',
                'example_sentence' => '元宵节挂红灯笼。',
                'example_translation' => 'We hang red lanterns during Lantern Festival.',
                'definition' => 'Lantern, lamp',
                'sentences' => ['红___。', '挂___。', '___节。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '舞龙',
                'pinyin' => 'wǔ lóng',
                'simplified' => '舞龙',
                'traditional' => '舞龍',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Dragon dance',
                'meaning_zh' => '舞龙',
                'example_sentence' => '节日里有舞龙表演。',
                'example_translation' => 'There are dragon dance performances during festivals.',
                'definition' => 'Dragon dance, to perform dragon dance',
                'sentences' => ['___舞狮。', '___表演。', '___队。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '祖先',
                'pinyin' => 'zǔ xiān',
                'simplified' => '祖先',
                'traditional' => '祖先',
                'part_of_speech' => 'noun',
                'meaning' => 'Ancestor / Forefather',
                'meaning_zh' => '祖先',
                'example_sentence' => '我们要尊敬祖先。',
                'example_translation' => 'We should respect our ancestors.',
                'definition' => 'Ancestor, forefather, forebear',
                'sentences' => ['___崇拜。', '___遗产。', '纪念___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '禁忌',
                'pinyin' => 'jìn jì',
                'simplified' => '禁忌',
                'traditional' => '禁忌',
                'part_of_speech' => 'noun',
                'meaning' => 'Taboo / Prohibition',
                'meaning_zh' => '禁忌',
                'example_sentence' => '每个文化都有自己的禁忌。',
                'example_translation' => 'Every culture has its own taboos.',
                'definition' => 'Taboo, prohibition, something forbidden',
                'sentences' => ['触犯___。', '___话题。', '文化___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '迷信',
                'pinyin' => 'mí xìn',
                'simplified' => '迷信',
                'traditional' => '迷信',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Superstition / To be superstitious',
                'meaning_zh' => '迷信',
                'example_sentence' => '不要太迷信。',
                'example_translation' => 'Don\'t be too superstitious.',
                'definition' => 'Superstition, to be superstitious',
                'sentences' => ['破除___。', '___思想。', '___活动。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '吉祥',
                'pinyin' => 'jí xiáng',
                'simplified' => '吉祥',
                'traditional' => '吉祥',
                'part_of_speech' => 'adjective',
                'meaning' => 'Auspicious / Lucky',
                'meaning_zh' => '吉祥',
                'example_sentence' => '红色在中国是吉祥的颜色。',
                'example_translation' => 'Red is an auspicious color in China.',
                'definition' => 'Auspicious, lucky, propitious',
                'sentences' => ['___如意。', '___物。', '___话。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '祝福',
                'pinyin' => 'zhù fú',
                'simplified' => '祝福',
                'traditional' => '祝福',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To bless / Blessing',
                'meaning_zh' => '祝福',
                'example_sentence' => '我祝福你幸福快乐。',
                'example_translation' => 'I wish you happiness.',
                'definition' => 'To bless, blessing, benediction',
                'sentences' => ['送上___。', '___语。', '___你。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '民俗',
                'pinyin' => 'mín sú',
                'simplified' => '民俗',
                'traditional' => '民俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Folk custom',
                'meaning_zh' => '民俗',
                'example_sentence' => '民俗文化很丰富。',
                'example_translation' => 'Folk culture is very rich.',
                'definition' => 'Folk custom, folklore',
                'sentences' => ['___文化。', '___活动。', '___研究。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 126,
                'word' => '传承',
                'pinyin' => 'chuán chéng',
                'simplified' => '传承',
                'traditional' => '傳承',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To pass on / Inheritance',
                'meaning_zh' => '传承',
                'example_sentence' => '文化需要传承。',
                'example_translation' => 'Culture needs to be passed on.',
                'definition' => 'To pass on, to inherit, inheritance',
                'sentences' => ['___文化。', '___人。', '___发展。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 127: Housing and Living Environment - 住房与居住环境
        $housingVocab = [
            [
                'topic_id' => 127,
                'word' => '住房',
                'pinyin' => 'zhù fáng',
                'simplified' => '住房',
                'traditional' => '住房',
                'part_of_speech' => 'noun',
                'meaning' => 'Housing / Residence',
                'meaning_zh' => '住房',
                'example_sentence' => '住房问题很重要。',
                'example_translation' => 'Housing issues are very important.',
                'definition' => 'Housing, residence, dwelling',
                'sentences' => ['___条件。', '___问题。', '___价格。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '公寓',
                'pinyin' => 'gōng yù',
                'simplified' => '公寓',
                'traditional' => '公寓',
                'part_of_speech' => 'noun',
                'meaning' => 'Apartment',
                'meaning_zh' => '公寓',
                'example_sentence' => '我住在一套公寓里。',
                'example_translation' => 'I live in an apartment.',
                'definition' => 'Apartment, flat',
                'sentences' => ['___楼。', '租___。', '___大厦。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '别墅',
                'pinyin' => 'bié shù',
                'simplified' => '别墅',
                'traditional' => '別墅',
                'part_of_speech' => 'noun',
                'meaning' => 'Villa',
                'meaning_zh' => '别墅',
                'example_sentence' => '他住在海边别墅。',
                'example_translation' => 'He lives in a seaside villa.',
                'definition' => 'Villa, detached house',
                'sentences' => ['豪华___。', '___区。', '___花园。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '小区',
                'pinyin' => 'xiǎo qū',
                'simplified' => '小区',
                'traditional' => '小區',
                'part_of_speech' => 'noun',
                'meaning' => 'Residential area / Community',
                'meaning_zh' => '小区',
                'example_sentence' => '这个小区环境很好。',
                'example_translation' => 'This residential area has a good environment.',
                'definition' => 'Residential area, housing complex, community',
                'sentences' => ['住宅___。', '___物业。', '___管理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '房租',
                'pinyin' => 'fáng zū',
                'simplified' => '房租',
                'traditional' => '房租',
                'part_of_speech' => 'noun',
                'meaning' => 'Rent',
                'meaning_zh' => '房租',
                'example_sentence' => '这里的房租很贵。',
                'example_translation' => 'The rent here is very expensive.',
                'definition' => 'Rent, rental fee',
                'sentences' => ['交___。', '___上涨。', '___便宜。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '房东',
                'pinyin' => 'fáng dōng',
                'simplified' => '房东',
                'traditional' => '房東',
                'part_of_speech' => 'noun',
                'meaning' => 'Landlord',
                'meaning_zh' => '房东',
                'example_sentence' => '房东很友好。',
                'example_translation' => 'The landlord is very friendly.',
                'definition' => 'Landlord, house owner',
                'sentences' => ['找___。', '___租客。', '___关系。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '租客',
                'pinyin' => 'zū kè',
                'simplified' => '租客',
                'traditional' => '租客',
                'part_of_speech' => 'noun',
                'meaning' => 'Tenant / Renter',
                'meaning_zh' => '租客',
                'example_sentence' => '租客要按时交房租。',
                'example_translation' => 'Tenants must pay rent on time.',
                'definition' => 'Tenant, renter, lodger',
                'sentences' => ['___权利。', '___义务。', '寻找___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '装修',
                'pinyin' => 'zhuāng xiū',
                'simplified' => '装修',
                'traditional' => '裝修',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To decorate / Decoration',
                'meaning_zh' => '装修',
                'example_sentence' => '房子正在装修。',
                'example_translation' => 'The house is being decorated.',
                'definition' => 'To decorate, to renovate, decoration',
                'sentences' => ['___房子。', '___风格。', '___材料。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '家具',
                'pinyin' => 'jiā jù',
                'simplified' => '家具',
                'traditional' => '家具',
                'part_of_speech' => 'noun',
                'meaning' => 'Furniture',
                'meaning_zh' => '家具',
                'example_sentence' => '需要买一些家具。',
                'example_translation' => 'Need to buy some furniture.',
                'definition' => 'Furniture, furnishings',
                'sentences' => ['___店。', '买___。', '___摆设。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '家电',
                'pinyin' => 'jiā diàn',
                'simplified' => '家电',
                'traditional' => '家電',
                'part_of_speech' => 'noun',
                'meaning' => 'Home appliances',
                'meaning_zh' => '家电',
                'example_sentence' => '家电都很齐全。',
                'example_translation' => 'All home appliances are complete.',
                'definition' => 'Home appliances, household electrical appliances',
                'sentences' => ['___产品。', '___维修。', '___商场。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '物业',
                'pinyin' => 'wù yè',
                'simplified' => '物业',
                'traditional' => '物業',
                'part_of_speech' => 'noun',
                'meaning' => 'Property management',
                'meaning_zh' => '物业',
                'example_sentence' => '物业管理很好。',
                'example_translation' => 'The property management is very good.',
                'definition' => 'Property management, property',
                'sentences' => ['___公司。', '___费。', '___服务。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '邻居',
                'pinyin' => 'lín jū',
                'simplified' => '邻居',
                'traditional' => '鄰居',
                'part_of_speech' => 'noun',
                'meaning' => 'Neighbor',
                'meaning_zh' => '邻居',
                'example_sentence' => '邻居很友好。',
                'example_translation' => 'The neighbors are very friendly.',
                'definition' => 'Neighbor, next-door neighbor',
                'sentences' => ['___关系。', '___之间。', '好___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '采光',
                'pinyin' => 'cǎi guāng',
                'simplified' => '采光',
                'traditional' => '採光',
                'part_of_speech' => 'noun',
                'meaning' => 'Lighting / Natural light',
                'meaning_zh' => '采光',
                'example_sentence' => '这个房子采光很好。',
                'example_translation' => 'This house has good natural lighting.',
                'definition' => 'Lighting, natural light, daylighting',
                'sentences' => ['___好。', '___条件。', '___效果。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '通风',
                'pinyin' => 'tōng fēng',
                'simplified' => '通风',
                'traditional' => '通風',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Ventilation / To ventilate',
                'meaning_zh' => '通风',
                'example_sentence' => '要注意通风。',
                'example_translation' => 'Pay attention to ventilation.',
                'definition' => 'Ventilation, to ventilate, to air',
                'sentences' => ['___良好。', '___条件。', '___设备。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '户型',
                'pinyin' => 'hù xíng',
                'simplified' => '户型',
                'traditional' => '戶型',
                'part_of_speech' => 'noun',
                'meaning' => 'Floor plan / Layout',
                'meaning_zh' => '户型',
                'example_sentence' => '这个户型很合理。',
                'example_translation' => 'This floor plan is very reasonable.',
                'definition' => 'Floor plan, apartment layout',
                'sentences' => ['___设计。', '___图。', '___合理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '面积',
                'pinyin' => 'miàn jī',
                'simplified' => '面积',
                'traditional' => '面積',
                'part_of_speech' => 'noun',
                'meaning' => 'Area / Floor space',
                'meaning_zh' => '面积',
                'example_sentence' => '房子面积有多大？',
                'example_translation' => 'How big is the floor area of the house?',
                'definition' => 'Area, floor space, surface area',
                'sentences' => ['建筑___。', '___大小。', '___计算。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '楼层',
                'pinyin' => 'lóu céng',
                'simplified' => '楼层',
                'traditional' => '樓層',
                'part_of_speech' => 'noun',
                'meaning' => 'Floor / Story',
                'meaning_zh' => '楼层',
                'example_sentence' => '我住在五楼层。',
                'example_translation' => 'I live on the fifth floor.',
                'definition' => 'Floor, story, storey',
                'sentences' => ['___高。', '___电梯。', '低___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '地段',
                'pinyin' => 'dì duàn',
                'simplified' => '地段',
                'traditional' => '地段',
                'part_of_speech' => 'noun',
                'meaning' => 'Location / District',
                'meaning_zh' => '地段',
                'example_sentence' => '这个地段很好。',
                'example_translation' => 'This location is very good.',
                'definition' => 'Location, district, lot',
                'sentences' => ['黄金___。', '___优势。', '___价值。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '配套',
                'pinyin' => 'pèi tào',
                'simplified' => '配套',
                'traditional' => '配套',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Supporting / Complementary',
                'meaning_zh' => '配套',
                'example_sentence' => '小区配套设施齐全。',
                'example_translation' => 'The community has complete supporting facilities.',
                'definition' => 'Supporting, complementary, matching facilities',
                'sentences' => ['___设施。', '___齐全。', '___服务。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 127,
                'word' => '房价',
                'pinyin' => 'fáng jià',
                'simplified' => '房价',
                'traditional' => '房價',
                'part_of_speech' => 'noun',
                'meaning' => 'House price',
                'meaning_zh' => '房价',
                'example_sentence' => '房价一直在上涨。',
                'example_translation' => 'House prices keep rising.',
                'definition' => 'House price, property price',
                'sentences' => ['___高。', '___上涨。', '___走势。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 128: Career and Employment - 职业与就业
        $careerVocab = [
            [
                'topic_id' => 128,
                'word' => '职业',
                'pinyin' => 'zhí yè',
                'simplified' => '职业',
                'traditional' => '職業',
                'part_of_speech' => 'noun',
                'meaning' => 'Occupation / Profession',
                'meaning_zh' => '职业',
                'example_sentence' => '你的职业是什么？',
                'example_translation' => 'What is your occupation?',
                'definition' => 'Occupation, profession, career',
                'sentences' => ['___选择。', '___发展。', '___规划。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '就业',
                'pinyin' => 'jiù yè',
                'simplified' => '就业',
                'traditional' => '就業',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Employment / To get a job',
                'meaning_zh' => '就业',
                'example_sentence' => '大学生就业压力大。',
                'example_translation' => 'College students face great employment pressure.',
                'definition' => 'Employment, to get a job',
                'sentences' => ['___机会。', '___率。', '___问题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '失业',
                'pinyin' => 'shī yè',
                'simplified' => '失业',
                'traditional' => '失業',
                'part_of_speech' => 'verb',
                'meaning' => 'To be unemployed',
                'meaning_zh' => '失业',
                'example_sentence' => '他失业已经半年了。',
                'example_translation' => 'He has been unemployed for half a year.',
                'definition' => 'To be unemployed, to lose one\'s job',
                'sentences' => ['___率。', '___人员。', '___保险。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '招聘',
                'pinyin' => 'zhāo pìn',
                'simplified' => '招聘',
                'traditional' => '招聘',
                'part_of_speech' => 'verb',
                'meaning' => 'To recruit / To hire',
                'meaning_zh' => '招聘',
                'example_sentence' => '公司正在招聘新员工。',
                'example_translation' => 'The company is recruiting new employees.',
                'definition' => 'To recruit, to hire, recruitment',
                'sentences' => ['___会。', '___信息。', '___要求。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '求职',
                'pinyin' => 'qiú zhí',
                'simplified' => '求职',
                'traditional' => '求職',
                'part_of_speech' => 'verb',
                'meaning' => 'To seek employment / Job hunting',
                'meaning_zh' => '求职',
                'example_sentence' => '我正在求职。',
                'example_translation' => 'I am job hunting.',
                'definition' => 'To seek employment, job hunting',
                'sentences' => ['___者。', '___信。', '___简历。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '简历',
                'pinyin' => 'jiǎn lì',
                'simplified' => '简历',
                'traditional' => '簡歷',
                'part_of_speech' => 'noun',
                'meaning' => 'Resume / CV',
                'meaning_zh' => '简历',
                'example_sentence' => '请投递你的简历。',
                'example_translation' => 'Please submit your resume.',
                'definition' => 'Resume, curriculum vitae, CV',
                'sentences' => ['投___。', '___表。', '个人___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '面试',
                'pinyin' => 'miàn shì',
                'simplified' => '面试',
                'traditional' => '面試',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Interview / To interview',
                'meaning_zh' => '面试',
                'example_sentence' => '明天有一个面试。',
                'example_translation' => 'I have an interview tomorrow.',
                'definition' => 'Interview, to interview',
                'sentences' => ['参加___。', '___通过。', '___技巧。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '录用',
                'pinyin' => 'lù yòng',
                'simplified' => '录用',
                'traditional' => '錄用',
                'part_of_speech' => 'verb',
                'meaning' => 'To employ / To hire',
                'meaning_zh' => '录用',
                'example_sentence' => '公司决定录用我。',
                'example_translation' => 'The company decided to hire me.',
                'definition' => 'To employ, to hire, to recruit',
                'sentences' => ['被___。', '___通知。', '___标准。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '薪水',
                'pinyin' => 'xīn shuǐ',
                'simplified' => '薪水',
                'traditional' => '薪水',
                'part_of_speech' => 'noun',
                'meaning' => 'Salary / Pay',
                'meaning_zh' => '薪水',
                'example_sentence' => '薪水还不错。',
                'example_translation' => 'The salary is pretty good.',
                'definition' => 'Salary, pay, wages',
                'sentences' => ['___待遇。', '___高。', '涨___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '待遇',
                'pinyin' => 'dài yù',
                'simplified' => '待遇',
                'traditional' => '待遇',
                'part_of_speech' => 'noun',
                'meaning' => 'Treatment / Pay and benefits',
                'meaning_zh' => '待遇',
                'example_sentence' => '公司待遇很好。',
                'example_translation' => 'The company offers good benefits.',
                'definition' => 'Treatment, pay and benefits, remuneration',
                'sentences' => ['工资___。', '___优厚。', '___问题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '晋升',
                'pinyin' => 'jìn shēng',
                'simplified' => '晋升',
                'traditional' => '晉升',
                'part_of_speech' => 'verb',
                'meaning' => 'To promote / Promotion',
                'meaning_zh' => '晋升',
                'example_sentence' => '他晋升为经理。',
                'example_translation' => 'He was promoted to manager.',
                'definition' => 'To promote, promotion, to advance',
                'sentences' => ['___机会。', '___空间。', '___制度。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '辞职',
                'pinyin' => 'cí zhí',
                'simplified' => '辞职',
                'traditional' => '辭職',
                'part_of_speech' => 'verb',
                'meaning' => 'To resign / To quit',
                'meaning_zh' => '辞职',
                'example_sentence' => '我打算辞职。',
                'example_translation' => 'I plan to resign.',
                'definition' => 'To resign, to quit one\'s job',
                'sentences' => ['___信。', '___原因。', '提出___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '解雇',
                'pinyin' => 'jiě gù',
                'simplified' => '解雇',
                'traditional' => '解僱',
                'part_of_speech' => 'verb',
                'meaning' => 'To fire / To dismiss',
                'meaning_zh' => '解雇',
                'example_sentence' => '他被公司解雇了。',
                'example_translation' => 'He was fired by the company.',
                'definition' => 'To fire, to dismiss, to discharge',
                'sentences' => ['被___。', '___员工。', '___理由。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '资格',
                'pinyin' => 'zī gé',
                'simplified' => '资格',
                'traditional' => '資格',
                'part_of_speech' => 'noun',
                'meaning' => 'Qualification',
                'meaning_zh' => '资格',
                'example_sentence' => '他有资格申请这个职位。',
                'example_translation' => 'He is qualified to apply for this position.',
                'definition' => 'Qualification, credentials',
                'sentences' => ['___证书。', '___审查。', '___要求。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '经验',
                'pinyin' => 'jīng yàn',
                'simplified' => '经验',
                'traditional' => '經驗',
                'part_of_speech' => 'noun',
                'meaning' => 'Experience',
                'meaning_zh' => '经验',
                'example_sentence' => '我有三年工作经验。',
                'example_translation' => 'I have three years of work experience.',
                'definition' => 'Experience, expertise',
                'sentences' => ['工作___。', '___丰富。', '积累___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '能力',
                'pinyin' => 'néng lì',
                'simplified' => '能力',
                'traditional' => '能力',
                'part_of_speech' => 'noun',
                'meaning' => 'Ability / Capability',
                'meaning_zh' => '能力',
                'example_sentence' => '他能力很强。',
                'example_translation' => 'He is very capable.',
                'definition' => 'Ability, capability, capacity',
                'sentences' => ['工作___。', '___强。', '___提升。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '竞争',
                'pinyin' => 'jìng zhēng',
                'simplified' => '竞争',
                'traditional' => '競爭',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Competition / To compete',
                'meaning_zh' => '竞争',
                'example_sentence' => '就业竞争很激烈。',
                'example_translation' => 'Job competition is very fierce.',
                'definition' => 'Competition, to compete, rivalry',
                'sentences' => ['___力。', '___激烈。', '___对手。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '培训',
                'pinyin' => 'péi xùn',
                'simplified' => '培训',
                'traditional' => '培訓',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Training / To train',
                'meaning_zh' => '培训',
                'example_sentence' => '公司提供培训机会。',
                'example_translation' => 'The company provides training opportunities.',
                'definition' => 'Training, to train',
                'sentences' => ['___课程。', '参加___。', '___计划。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '职称',
                'pinyin' => 'zhí chēng',
                'simplified' => '职称',
                'traditional' => '職稱',
                'part_of_speech' => 'noun',
                'meaning' => 'Professional title',
                'meaning_zh' => '职称',
                'example_sentence' => '他评上了高级职称。',
                'example_translation' => 'He was awarded a senior professional title.',
                'definition' => 'Professional title, job title',
                'sentences' => ['___评定。', '___晋升。', '高级___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 128,
                'word' => '实习',
                'pinyin' => 'shí xí',
                'simplified' => '实习',
                'traditional' => '實習',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Internship / To intern',
                'meaning_zh' => '实习',
                'example_sentence' => '我在公司实习。',
                'example_translation' => 'I am interning at the company.',
                'definition' => 'Internship, to intern, to practice',
                'sentences' => ['___生。', '___期。', '___机会。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 129: Business and Economy - 商业与经济
        $businessVocab = [
            [
                'topic_id' => 129,
                'word' => '商业',
                'pinyin' => 'shāng yè',
                'simplified' => '商业',
                'traditional' => '商業',
                'part_of_speech' => 'noun',
                'meaning' => 'Business / Commerce',
                'meaning_zh' => '商业',
                'example_sentence' => '这里是商业中心。',
                'example_translation' => 'This is a business center.',
                'definition' => 'Business, commerce, trade',
                'sentences' => ['___活动。', '___区。', '___模式。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '经济',
                'pinyin' => 'jīng jì',
                'simplified' => '经济',
                'traditional' => '經濟',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Economy / Economic',
                'meaning_zh' => '经济',
                'example_sentence' => '经济发展很快。',
                'example_translation' => 'Economic development is very fast.',
                'definition' => 'Economy, economic, financial',
                'sentences' => ['___增长。', '___发展。', '___效益。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '贸易',
                'pinyin' => 'mào yì',
                'simplified' => '贸易',
                'traditional' => '貿易',
                'part_of_speech' => 'noun',
                'meaning' => 'Trade',
                'meaning_zh' => '贸易',
                'example_sentence' => '国际贸易很重要。',
                'example_translation' => 'International trade is very important.',
                'definition' => 'Trade, commerce',
                'sentences' => ['___公司。', '___合作。', '___伙伴。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '市场',
                'pinyin' => 'shì chǎng',
                'simplified' => '市场',
                'traditional' => '市場',
                'part_of_speech' => 'noun',
                'meaning' => 'Market',
                'meaning_zh' => '市场',
                'example_sentence' => '市场需求很大。',
                'example_translation' => 'Market demand is very high.',
                'definition' => 'Market, marketplace',
                'sentences' => ['___经济。', '___竞争。', '___份额。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '企业',
                'pinyin' => 'qǐ yè',
                'simplified' => '企业',
                'traditional' => '企業',
                'part_of_speech' => 'noun',
                'meaning' => 'Enterprise / Company',
                'meaning_zh' => '企业',
                'example_sentence' => '他在一家企业工作。',
                'example_translation' => 'He works at an enterprise.',
                'definition' => 'Enterprise, company, business',
                'sentences' => ['___管理。', '___文化。', '___发展。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '公司',
                'pinyin' => 'gōng sī',
                'simplified' => '公司',
                'traditional' => '公司',
                'part_of_speech' => 'noun',
                'meaning' => 'Company',
                'meaning_zh' => '公司',
                'example_sentence' => '我在一家公司上班。',
                'example_translation' => 'I work at a company.',
                'definition' => 'Company, corporation, firm',
                'sentences' => ['___员工。', '___业务。', '___规模。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '投资',
                'pinyin' => 'tóu zī',
                'simplified' => '投资',
                'traditional' => '投資',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Investment / To invest',
                'meaning_zh' => '投资',
                'example_sentence' => '他投资了一家公司。',
                'example_translation' => 'He invested in a company.',
                'definition' => 'Investment, to invest',
                'sentences' => ['___者。', '___回报。', '___项目。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '利润',
                'pinyin' => 'lì rùn',
                'simplified' => '利润',
                'traditional' => '利潤',
                'part_of_speech' => 'noun',
                'meaning' => 'Profit',
                'meaning_zh' => '利润',
                'example_sentence' => '公司利润增加了。',
                'example_translation' => 'The company\'s profit increased.',
                'definition' => 'Profit, gain',
                'sentences' => ['___增长。', '___空间。', '___率。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '成本',
                'pinyin' => 'chéng běn',
                'simplified' => '成本',
                'traditional' => '成本',
                'part_of_speech' => 'noun',
                'meaning' => 'Cost',
                'meaning_zh' => '成本',
                'example_sentence' => '生产成本很高。',
                'example_translation' => 'Production costs are very high.',
                'definition' => 'Cost, production cost',
                'sentences' => ['降低___。', '___控制。', '___核算。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '收入',
                'pinyin' => 'shōu rù',
                'simplified' => '收入',
                'traditional' => '收入',
                'part_of_speech' => 'noun',
                'meaning' => 'Income / Revenue',
                'meaning_zh' => '收入',
                'example_sentence' => '我的收入不高。',
                'example_translation' => 'My income is not high.',
                'definition' => 'Income, revenue, earnings',
                'sentences' => ['___水平。', '___增加。', '___来源。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '支出',
                'pinyin' => 'zhī chū',
                'simplified' => '支出',
                'traditional' => '支出',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Expenditure / To spend',
                'meaning_zh' => '支出',
                'example_sentence' => '要控制支出。',
                'example_translation' => 'Need to control expenditures.',
                'definition' => 'Expenditure, to spend, outlay',
                'sentences' => ['___预算。', '___项目。', '减少___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '债务',
                'pinyin' => 'zhài wù',
                'simplified' => '债务',
                'traditional' => '債務',
                'part_of_speech' => 'noun',
                'meaning' => 'Debt',
                'meaning_zh' => '债务',
                'example_sentence' => '要还清债务。',
                'example_translation' => 'Need to pay off the debt.',
                'definition' => 'Debt, liabilities',
                'sentences' => ['___危机。', '___负担。', '___偿还。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '股票',
                'pinyin' => 'gǔ piào',
                'simplified' => '股票',
                'traditional' => '股票',
                'part_of_speech' => 'noun',
                'meaning' => 'Stock / Share',
                'meaning_zh' => '股票',
                'example_sentence' => '他买了一些股票。',
                'example_translation' => 'He bought some stocks.',
                'definition' => 'Stock, share, equity',
                'sentences' => ['___市场。', '___价格。', '买___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '银行',
                'pinyin' => 'yín háng',
                'simplified' => '银行',
                'traditional' => '銀行',
                'part_of_speech' => 'noun',
                'meaning' => 'Bank',
                'meaning_zh' => '银行',
                'example_sentence' => '我去银行取钱。',
                'example_translation' => 'I go to the bank to withdraw money.',
                'definition' => 'Bank, banking institution',
                'sentences' => ['___卡。', '___存款。', '___贷款。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '贷款',
                'pinyin' => 'dài kuǎn',
                'simplified' => '贷款',
                'traditional' => '貸款',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Loan / To lend',
                'meaning_zh' => '贷款',
                'example_sentence' => '我向银行贷款。',
                'example_translation' => 'I took out a bank loan.',
                'definition' => 'Loan, to lend, to borrow',
                'sentences' => ['___利率。', '申请___。', '___还款。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '税收',
                'pinyin' => 'shuì shōu',
                'simplified' => '税收',
                'traditional' => '稅收',
                'part_of_speech' => 'noun',
                'meaning' => 'Tax / Taxation',
                'meaning_zh' => '税收',
                'example_sentence' => '税收政策很重要。',
                'example_translation' => 'Tax policy is very important.',
                'definition' => 'Tax, taxation, revenue',
                'sentences' => ['___制度。', '___政策。', '___负担。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '消费',
                'pinyin' => 'xiāo fèi',
                'simplified' => '消费',
                'traditional' => '消費',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Consumption / To consume',
                'meaning_zh' => '消费',
                'example_sentence' => '消费水平提高了。',
                'example_translation' => 'Consumption levels have increased.',
                'definition' => 'Consumption, to consume, spending',
                'sentences' => ['___者。', '___能力。', '___市场。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '供需',
                'pinyin' => 'gōng xū',
                'simplified' => '供需',
                'traditional' => '供需',
                'part_of_speech' => 'noun',
                'meaning' => 'Supply and demand',
                'meaning_zh' => '供需',
                'example_sentence' => '供需平衡很重要。',
                'example_translation' => 'Supply and demand balance is very important.',
                'definition' => 'Supply and demand',
                'sentences' => ['___关系。', '___平衡。', '___矛盾。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '通货膨胀',
                'pinyin' => 'tōng huò péng zhàng',
                'simplified' => '通货膨胀',
                'traditional' => '通貨膨脹',
                'part_of_speech' => 'noun',
                'meaning' => 'Inflation',
                'meaning_zh' => '通货膨胀',
                'example_sentence' => '通货膨胀影响生活。',
                'example_translation' => 'Inflation affects life.',
                'definition' => 'Inflation, currency inflation',
                'sentences' => ['___率。', '控制___。', '___压力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 129,
                'word' => '经营',
                'pinyin' => 'jīng yíng',
                'simplified' => '经营',
                'traditional' => '經營',
                'part_of_speech' => 'verb',
                'meaning' => 'To operate / To manage',
                'meaning_zh' => '经营',
                'example_sentence' => '他经营一家餐厅。',
                'example_translation' => 'He operates a restaurant.',
                'definition' => 'To operate, to manage, to run a business',
                'sentences' => ['___管理。', '___策略。', '___状况。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($customsVocab, $housingVocab, $careerVocab, $businessVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
