<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic146to149Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [146, 149])->delete();

        // Topic 146: Good and Bad Habits - 好习惯与坏习惯
        $habitsVocab = [
            [
                'topic_id' => 146,
                'word' => '习惯',
                'pinyin' => 'xí guàn',
                'simplified' => '习惯',
                'traditional' => '習慣',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Habit / To be used to',
                'meaning_zh' => '习惯',
                'example_sentence' => '养成好习惯很重要。',
                'example_translation' => 'Developing good habits is very important.',
                'definition' => 'Habit, to be used to, custom',
                'sentences' => ['___培养。', '___养成。', '___改变。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '养成',
                'pinyin' => 'yǎng chéng',
                'simplified' => '养成',
                'traditional' => '養成',
                'part_of_speech' => 'verb',
                'meaning' => 'To develop / To form',
                'meaning_zh' => '养成',
                'example_sentence' => '要养成好习惯。',
                'example_translation' => 'Need to develop good habits.',
                'definition' => 'To develop, to form, to cultivate',
                'sentences' => ['___习惯。', '___意识。', '___性格。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '勤奋',
                'pinyin' => 'qín fèn',
                'simplified' => '勤奋',
                'traditional' => '勤奮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Diligent / Hard-working',
                'meaning_zh' => '勤奋',
                'example_sentence' => '他很勤奋。',
                'example_translation' => 'He is very diligent.',
                'definition' => 'Diligent, hard-working, industrious',
                'sentences' => ['___学习。', '___工作。', '___努力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '懒惰',
                'pinyin' => 'lǎn duò',
                'simplified' => '懒惰',
                'traditional' => '懶惰',
                'part_of_speech' => 'adjective',
                'meaning' => 'Lazy',
                'meaning_zh' => '懒惰',
                'example_sentence' => '不要懒惰。',
                'example_translation' => 'Don\'t be lazy.',
                'definition' => 'Lazy, indolent, slothful',
                'sentences' => ['___的人。', '___成性。', '___习气。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '节俭',
                'pinyin' => 'jié jiǎn',
                'simplified' => '节俭',
                'traditional' => '節儉',
                'part_of_speech' => 'adjective',
                'meaning' => 'Frugal / Thrifty',
                'meaning_zh' => '节俭',
                'example_sentence' => '要节俭生活。',
                'example_translation' => 'Need to live frugally.',
                'definition' => 'Frugal, thrifty, economical',
                'sentences' => ['___美德。', '___持家。', '___朴素。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '浪费',
                'pinyin' => 'làng fèi',
                'simplified' => '浪费',
                'traditional' => '浪費',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To waste / Waste',
                'meaning_zh' => '浪费',
                'example_sentence' => '不要浪费时间。',
                'example_translation' => 'Don\'t waste time.',
                'definition' => 'To waste, waste, wasteful',
                'sentences' => ['___资源。', '___粮食。', '___金钱。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '守时',
                'pinyin' => 'shǒu shí',
                'simplified' => '守时',
                'traditional' => '守時',
                'part_of_speech' => 'adjective',
                'meaning' => 'Punctual',
                'meaning_zh' => '守时',
                'example_sentence' => '他很守时。',
                'example_translation' => 'He is very punctual.',
                'definition' => 'Punctual, on time',
                'sentences' => ['___的人。', '___守信。', '___观念。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '拖延',
                'pinyin' => 'tuō yán',
                'simplified' => '拖延',
                'traditional' => '拖延',
                'part_of_speech' => 'verb',
                'meaning' => 'To procrastinate / To delay',
                'meaning_zh' => '拖延',
                'example_sentence' => '不要拖延工作。',
                'example_translation' => 'Don\'t procrastinate on work.',
                'definition' => 'To procrastinate, to delay, to postpone',
                'sentences' => ['___症。', '___时间。', '___问题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '整洁',
                'pinyin' => 'zhěng jié',
                'simplified' => '整洁',
                'traditional' => '整潔',
                'part_of_speech' => 'adjective',
                'meaning' => 'Neat / Tidy',
                'meaning_zh' => '整洁',
                'example_sentence' => '房间很整洁。',
                'example_translation' => 'The room is very neat.',
                'definition' => 'Neat, tidy, clean and orderly',
                'sentences' => ['___干净。', '___有序。', '___卫生。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '邋遢',
                'pinyin' => 'lā ta',
                'simplified' => '邋遢',
                'traditional' => '邋遢',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sloppy / Slovenly',
                'meaning_zh' => '邋遢',
                'example_sentence' => '不要太邋遢。',
                'example_translation' => 'Don\'t be too sloppy.',
                'definition' => 'Sloppy, slovenly, untidy',
                'sentences' => ['___的样子。', '___不堪。', '___形象。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '自律',
                'pinyin' => 'zì lǜ',
                'simplified' => '自律',
                'traditional' => '自律',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Self-discipline',
                'meaning_zh' => '自律',
                'example_sentence' => '要有自律性。',
                'example_translation' => 'Need to have self-discipline.',
                'definition' => 'Self-discipline, self-control',
                'sentences' => ['___性。', '___能力。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '放纵',
                'pinyin' => 'fàng zòng',
                'simplified' => '放纵',
                'traditional' => '放縱',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To indulge / Indulgent',
                'meaning_zh' => '放纵',
                'example_sentence' => '不要放纵自己。',
                'example_translation' => 'Don\'t indulge yourself.',
                'definition' => 'To indulge, indulgent, unrestrained',
                'sentences' => ['___欲望。', '___行为。', '___生活。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '坚持',
                'pinyin' => 'jiān chí',
                'simplified' => '坚持',
                'traditional' => '堅持',
                'part_of_speech' => 'verb',
                'meaning' => 'To persist / To insist',
                'meaning_zh' => '坚持',
                'example_sentence' => '要坚持锻炼。',
                'example_translation' => 'Need to persist in exercising.',
                'definition' => 'To persist, to insist, to stick to',
                'sentences' => ['___不懈。', '___原则。', '___努力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '放弃',
                'pinyin' => 'fàng qì',
                'simplified' => '放弃',
                'traditional' => '放棄',
                'part_of_speech' => 'verb',
                'meaning' => 'To give up / To abandon',
                'meaning_zh' => '放弃',
                'example_sentence' => '不要轻易放弃。',
                'example_translation' => 'Don\'t give up easily.',
                'definition' => 'To give up, to abandon, to renounce',
                'sentences' => ['___梦想。', '___努力。', '___机会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '专注',
                'pinyin' => 'zhuān zhù',
                'simplified' => '专注',
                'traditional' => '專注',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To concentrate / Focused',
                'meaning_zh' => '专注',
                'example_sentence' => '要专注学习。',
                'example_translation' => 'Need to concentrate on studying.',
                'definition' => 'To concentrate, focused, attentive',
                'sentences' => ['___力。', '___投入。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '分心',
                'pinyin' => 'fēn xīn',
                'simplified' => '分心',
                'traditional' => '分心',
                'part_of_speech' => 'verb',
                'meaning' => 'To be distracted',
                'meaning_zh' => '分心',
                'example_sentence' => '不要分心。',
                'example_translation' => 'Don\'t be distracted.',
                'definition' => 'To be distracted, to divert attention',
                'sentences' => ['___走神。', '___注意。', '___学习。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '礼貌',
                'pinyin' => 'lǐ mào',
                'simplified' => '礼貌',
                'traditional' => '禮貌',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Polite / Courtesy',
                'meaning_zh' => '礼貌',
                'example_sentence' => '要有礼貌。',
                'example_translation' => 'Need to be polite.',
                'definition' => 'Polite, courtesy, manners',
                'sentences' => ['___待人。', '___用语。', '___教养。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '粗鲁',
                'pinyin' => 'cū lǔ',
                'simplified' => '粗鲁',
                'traditional' => '粗魯',
                'part_of_speech' => 'adjective',
                'meaning' => 'Rude / Crude',
                'meaning_zh' => '粗鲁',
                'example_sentence' => '说话不要粗鲁。',
                'example_translation' => 'Don\'t speak rudely.',
                'definition' => 'Rude, crude, rough',
                'sentences' => ['___无礼。', '___的话。', '___行为。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '诚实',
                'pinyin' => 'chéng shí',
                'simplified' => '诚实',
                'traditional' => '誠實',
                'part_of_speech' => 'adjective',
                'meaning' => 'Honest / Truthful',
                'meaning_zh' => '诚实',
                'example_sentence' => '要诚实守信。',
                'example_translation' => 'Need to be honest and trustworthy.',
                'definition' => 'Honest, truthful, sincere',
                'sentences' => ['___的人。', '___守信。', '___可靠。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 146,
                'word' => '撒谎',
                'pinyin' => 'sā huǎng',
                'simplified' => '撒谎',
                'traditional' => '撒謊',
                'part_of_speech' => 'verb',
                'meaning' => 'To lie / To tell lies',
                'meaning_zh' => '撒谎',
                'example_sentence' => '不要撒谎。',
                'example_translation' => 'Don\'t lie.',
                'definition' => 'To lie, to tell lies, to fib',
                'sentences' => ['___欺骗。', '___说谎。', '___行为。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 147: Traditional and Modern Medicine - 传统与现代医学
        $medicineVocab = [
            [
                'topic_id' => 147,
                'word' => '医学',
                'pinyin' => 'yī xué',
                'simplified' => '医学',
                'traditional' => '醫學',
                'part_of_speech' => 'noun',
                'meaning' => 'Medicine / Medical science',
                'meaning_zh' => '医学',
                'example_sentence' => '他学习医学。',
                'example_translation' => 'He studies medicine.',
                'definition' => 'Medicine, medical science',
                'sentences' => ['___研究。', '___发展。', '___知识。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '中医',
                'pinyin' => 'zhōng yī',
                'simplified' => '中医',
                'traditional' => '中醫',
                'part_of_speech' => 'noun',
                'meaning' => 'Traditional Chinese medicine',
                'meaning_zh' => '中医',
                'example_sentence' => '中医治疗很有效。',
                'example_translation' => 'Traditional Chinese medicine treatment is very effective.',
                'definition' => 'Traditional Chinese medicine, TCM',
                'sentences' => ['___理论。', '___药。', '___诊所。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '西医',
                'pinyin' => 'xī yī',
                'simplified' => '西医',
                'traditional' => '西醫',
                'part_of_speech' => 'noun',
                'meaning' => 'Western medicine',
                'meaning_zh' => '西医',
                'example_sentence' => '西医见效快。',
                'example_translation' => 'Western medicine takes effect quickly.',
                'definition' => 'Western medicine, modern medicine',
                'sentences' => ['___治疗。', '___医院。', '___手术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '中药',
                'pinyin' => 'zhōng yào',
                'simplified' => '中药',
                'traditional' => '中藥',
                'part_of_speech' => 'noun',
                'meaning' => 'Chinese medicine / Herbal medicine',
                'meaning_zh' => '中药',
                'example_sentence' => '喝中药很苦。',
                'example_translation' => 'Chinese herbal medicine is very bitter.',
                'definition' => 'Chinese medicine, herbal medicine',
                'sentences' => ['___材。', '___处方。', '___调理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '西药',
                'pinyin' => 'xī yào',
                'simplified' => '西药',
                'traditional' => '西藥',
                'part_of_speech' => 'noun',
                'meaning' => 'Western medicine / Pharmaceutical drugs',
                'meaning_zh' => '西药',
                'example_sentence' => '西药见效快。',
                'example_translation' => 'Western medicine takes effect quickly.',
                'definition' => 'Western medicine, pharmaceutical drugs',
                'sentences' => ['___片。', '___副作用。', '___处方。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '针灸',
                'pinyin' => 'zhēn jiǔ',
                'simplified' => '针灸',
                'traditional' => '針灸',
                'part_of_speech' => 'noun',
                'meaning' => 'Acupuncture',
                'meaning_zh' => '针灸',
                'example_sentence' => '针灸可以止痛。',
                'example_translation' => 'Acupuncture can relieve pain.',
                'definition' => 'Acupuncture and moxibustion',
                'sentences' => ['___治疗。', '___疗法。', '___穴位。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '推拿',
                'pinyin' => 'tuī ná',
                'simplified' => '推拿',
                'traditional' => '推拿',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Massage / Chinese therapeutic massage',
                'meaning_zh' => '推拿',
                'example_sentence' => '推拿可以缓解疲劳。',
                'example_translation' => 'Massage can relieve fatigue.',
                'definition' => 'Massage, Chinese therapeutic massage',
                'sentences' => ['___按摩。', '___师。', '___治疗。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '拔罐',
                'pinyin' => 'bá guàn',
                'simplified' => '拔罐',
                'traditional' => '拔罐',
                'part_of_speech' => 'verb',
                'meaning' => 'Cupping therapy',
                'meaning_zh' => '拔罐',
                'example_sentence' => '拔罐可以去湿气。',
                'example_translation' => 'Cupping can remove dampness.',
                'definition' => 'Cupping therapy',
                'sentences' => ['___疗法。', '___治疗。', '___印子。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '手术',
                'pinyin' => 'shǒu shù',
                'simplified' => '手术',
                'traditional' => '手術',
                'part_of_speech' => 'noun',
                'meaning' => 'Surgery / Operation',
                'meaning_zh' => '手术',
                'example_sentence' => '需要做手术。',
                'example_translation' => 'Need to have surgery.',
                'definition' => 'Surgery, operation, surgical procedure',
                'sentences' => ['___台。', '___室。', '___成功。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '诊断',
                'pinyin' => 'zhěn duàn',
                'simplified' => '诊断',
                'traditional' => '診斷',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To diagnose / Diagnosis',
                'meaning_zh' => '诊断',
                'example_sentence' => '医生诊断病情。',
                'example_translation' => 'The doctor diagnoses the condition.',
                'definition' => 'To diagnose, diagnosis',
                'sentences' => ['___结果。', '___报告。', '___准确。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '治疗',
                'pinyin' => 'zhì liáo',
                'simplified' => '治疗',
                'traditional' => '治療',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To treat / Treatment',
                'meaning_zh' => '治疗',
                'example_sentence' => '正在接受治疗。',
                'example_translation' => 'Currently receiving treatment.',
                'definition' => 'To treat, treatment, therapy',
                'sentences' => ['___方案。', '___效果。', '___方法。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '康复',
                'pinyin' => 'kāng fù',
                'simplified' => '康复',
                'traditional' => '康復',
                'part_of_speech' => 'verb',
                'meaning' => 'To recover / Rehabilitation',
                'meaning_zh' => '康复',
                'example_sentence' => '祝你早日康复。',
                'example_translation' => 'Wish you a speedy recovery.',
                'definition' => 'To recover, rehabilitation, recuperation',
                'sentences' => ['___训练。', '___中心。', '___治疗。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '预防',
                'pinyin' => 'yù fáng',
                'simplified' => '预防',
                'traditional' => '預防',
                'part_of_speech' => 'verb',
                'meaning' => 'To prevent / Prevention',
                'meaning_zh' => '预防',
                'example_sentence' => '预防胜于治疗。',
                'example_translation' => 'Prevention is better than cure.',
                'definition' => 'To prevent, prevention, prophylaxis',
                'sentences' => ['___措施。', '___接种。', '___疾病。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '体检',
                'pinyin' => 'tǐ jiǎn',
                'simplified' => '体检',
                'traditional' => '體檢',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Physical examination / Checkup',
                'meaning_zh' => '体检',
                'example_sentence' => '每年要体检。',
                'example_translation' => 'Need to have a physical exam every year.',
                'definition' => 'Physical examination, checkup',
                'sentences' => ['___报告。', '___中心。', '___项目。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '症状',
                'pinyin' => 'zhèng zhuàng',
                'simplified' => '症状',
                'traditional' => '症狀',
                'part_of_speech' => 'noun',
                'meaning' => 'Symptom',
                'meaning_zh' => '症状',
                'example_sentence' => '有什么症状？',
                'example_translation' => 'What symptoms do you have?',
                'definition' => 'Symptom, sign',
                'sentences' => ['___明显。', '___描述。', '___减轻。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '疼痛',
                'pinyin' => 'téng tòng',
                'simplified' => '疼痛',
                'traditional' => '疼痛',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Pain / To ache',
                'meaning_zh' => '疼痛',
                'example_sentence' => '感到疼痛。',
                'example_translation' => 'Feel pain.',
                'definition' => 'Pain, ache, soreness',
                'sentences' => ['___感。', '___缓解。', '___难忍。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '发炎',
                'pinyin' => 'fā yán',
                'simplified' => '发炎',
                'traditional' => '發炎',
                'part_of_speech' => 'verb',
                'meaning' => 'To become inflamed / Inflammation',
                'meaning_zh' => '发炎',
                'example_sentence' => '伤口发炎了。',
                'example_translation' => 'The wound became inflamed.',
                'definition' => 'To become inflamed, inflammation',
                'sentences' => ['___感染。', '___红肿。', '___消炎。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '过敏',
                'pinyin' => 'guò mǐn',
                'simplified' => '过敏',
                'traditional' => '過敏',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'Allergy / Allergic',
                'meaning_zh' => '过敏',
                'example_sentence' => '我对花粉过敏。',
                'example_translation' => 'I\'m allergic to pollen.',
                'definition' => 'Allergy, allergic, hypersensitive',
                'sentences' => ['___反应。', '___源。', '___体质。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '免疫',
                'pinyin' => 'miǎn yì',
                'simplified' => '免疫',
                'traditional' => '免疫',
                'part_of_speech' => 'noun',
                'meaning' => 'Immunity / Immune',
                'meaning_zh' => '免疫',
                'example_sentence' => '增强免疫力。',
                'example_translation' => 'Strengthen immunity.',
                'definition' => 'Immunity, immune system',
                'sentences' => ['___力。', '___系统。', '___功能。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 147,
                'word' => '疫苗',
                'pinyin' => 'yì miáo',
                'simplified' => '疫苗',
                'traditional' => '疫苗',
                'part_of_speech' => 'noun',
                'meaning' => 'Vaccine',
                'meaning_zh' => '疫苗',
                'example_sentence' => '要接种疫苗。',
                'example_translation' => 'Need to get vaccinated.',
                'definition' => 'Vaccine, vaccination',
                'sentences' => ['___接种。', '___研发。', '___注射。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 148: Domestic and International Travel - 国内与国际旅行
        $travelVocab = [
            [
                'topic_id' => 148,
                'word' => '旅行',
                'pinyin' => 'lǚ xíng',
                'simplified' => '旅行',
                'traditional' => '旅行',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To travel / Travel',
                'meaning_zh' => '旅行',
                'example_sentence' => '喜欢旅行。',
                'example_translation' => 'Like to travel.',
                'definition' => 'To travel, travel, journey',
                'sentences' => ['___计划。', '___社。', '___箱。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '旅游',
                'pinyin' => 'lǚ yóu',
                'simplified' => '旅游',
                'traditional' => '旅遊',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To tour / Tourism',
                'meaning_zh' => '旅游',
                'example_sentence' => '去旅游。',
                'example_translation' => 'Go traveling.',
                'definition' => 'To tour, tourism, sightseeing',
                'sentences' => ['___景点。', '___业。', '___旺季。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '出国',
                'pinyin' => 'chū guó',
                'simplified' => '出国',
                'traditional' => '出國',
                'part_of_speech' => 'verb',
                'meaning' => 'To go abroad',
                'meaning_zh' => '出国',
                'example_sentence' => '他出国留学。',
                'example_translation' => 'He went abroad to study.',
                'definition' => 'To go abroad, to leave the country',
                'sentences' => ['___留学。', '___旅游。', '___签证。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '签证',
                'pinyin' => 'qiān zhèng',
                'simplified' => '签证',
                'traditional' => '簽證',
                'part_of_speech' => 'noun',
                'meaning' => 'Visa',
                'meaning_zh' => '签证',
                'example_sentence' => '需要办签证。',
                'example_translation' => 'Need to apply for a visa.',
                'definition' => 'Visa',
                'sentences' => ['___申请。', '___办理。', '___材料。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '护照',
                'pinyin' => 'hù zhào',
                'simplified' => '护照',
                'traditional' => '護照',
                'part_of_speech' => 'noun',
                'meaning' => 'Passport',
                'meaning_zh' => '护照',
                'example_sentence' => '带好护照。',
                'example_translation' => 'Bring your passport.',
                'definition' => 'Passport',
                'sentences' => ['___号码。', '___有效期。', '___办理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '海关',
                'pinyin' => 'hǎi guān',
                'simplified' => '海关',
                'traditional' => '海關',
                'part_of_speech' => 'noun',
                'meaning' => 'Customs',
                'meaning_zh' => '海关',
                'example_sentence' => '通过海关。',
                'example_translation' => 'Go through customs.',
                'definition' => 'Customs, customs office',
                'sentences' => ['___检查。', '___申报。', '___入境。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '行李',
                'pinyin' => 'xíng li',
                'simplified' => '行李',
                'traditional' => '行李',
                'part_of_speech' => 'noun',
                'meaning' => 'Luggage / Baggage',
                'meaning_zh' => '行李',
                'example_sentence' => '托运行李。',
                'example_translation' => 'Check in luggage.',
                'definition' => 'Luggage, baggage',
                'sentences' => ['___箱。', '___托运。', '___限额。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '航班',
                'pinyin' => 'háng bān',
                'simplified' => '航班',
                'traditional' => '航班',
                'part_of_speech' => 'noun',
                'meaning' => 'Flight / Scheduled flight',
                'meaning_zh' => '航班',
                'example_sentence' => '航班延误了。',
                'example_translation' => 'The flight was delayed.',
                'definition' => 'Flight, scheduled flight',
                'sentences' => ['___号。', '___信息。', '___时刻表。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '登机',
                'pinyin' => 'dēng jī',
                'simplified' => '登机',
                'traditional' => '登機',
                'part_of_speech' => 'verb',
                'meaning' => 'To board a plane',
                'meaning_zh' => '登机',
                'example_sentence' => '准备登机。',
                'example_translation' => 'Prepare to board.',
                'definition' => 'To board a plane, boarding',
                'sentences' => ['___口。', '___牌。', '___时间。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '转机',
                'pinyin' => 'zhuǎn jī',
                'simplified' => '转机',
                'traditional' => '轉機',
                'part_of_speech' => 'verb',
                'meaning' => 'To transfer (flights)',
                'meaning_zh' => '转机',
                'example_sentence' => '需要转机。',
                'example_translation' => 'Need to transfer flights.',
                'definition' => 'To transfer flights, connecting flight',
                'sentences' => ['___时间。', '___航班。', '___手续。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '景点',
                'pinyin' => 'jǐng diǎn',
                'simplified' => '景点',
                'traditional' => '景點',
                'part_of_speech' => 'noun',
                'meaning' => 'Scenic spot / Tourist attraction',
                'meaning_zh' => '景点',
                'example_sentence' => '参观景点。',
                'example_translation' => 'Visit scenic spots.',
                'definition' => 'Scenic spot, tourist attraction',
                'sentences' => ['___门票。', '___推荐。', '___介绍。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '导游',
                'pinyin' => 'dǎo yóu',
                'simplified' => '导游',
                'traditional' => '導遊',
                'part_of_speech' => 'noun',
                'meaning' => 'Tour guide',
                'meaning_zh' => '导游',
                'example_sentence' => '导游很专业。',
                'example_translation' => 'The tour guide is very professional.',
                'definition' => 'Tour guide, tourist guide',
                'sentences' => ['___服务。', '___讲解。', '___带队。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '纪念品',
                'pinyin' => 'jì niàn pǐn',
                'simplified' => '纪念品',
                'traditional' => '紀念品',
                'part_of_speech' => 'noun',
                'meaning' => 'Souvenir',
                'meaning_zh' => '纪念品',
                'example_sentence' => '买了纪念品。',
                'example_translation' => 'Bought souvenirs.',
                'definition' => 'Souvenir, memento, keepsake',
                'sentences' => ['___商店。', '___收藏。', '___礼物。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '特产',
                'pinyin' => 'tè chǎn',
                'simplified' => '特产',
                'traditional' => '特產',
                'part_of_speech' => 'noun',
                'meaning' => 'Local specialty',
                'meaning_zh' => '特产',
                'example_sentence' => '这是当地特产。',
                'example_translation' => 'This is a local specialty.',
                'definition' => 'Local specialty, special local product',
                'sentences' => ['___美食。', '___商店。', '___推荐。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '预订',
                'pinyin' => 'yù dìng',
                'simplified' => '预订',
                'traditional' => '預訂',
                'part_of_speech' => 'verb',
                'meaning' => 'To book / To reserve',
                'meaning_zh' => '预订',
                'example_sentence' => '预订酒店。',
                'example_translation' => 'Book a hotel.',
                'definition' => 'To book, to reserve, to make a reservation',
                'sentences' => ['___房间。', '___机票。', '___确认。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '攻略',
                'pinyin' => 'gōng lüè',
                'simplified' => '攻略',
                'traditional' => '攻略',
                'part_of_speech' => 'noun',
                'meaning' => 'Strategy / Travel guide',
                'meaning_zh' => '攻略',
                'example_sentence' => '看旅游攻略。',
                'example_translation' => 'Read travel guides.',
                'definition' => 'Strategy, guide, tips',
                'sentences' => ['___分享。', '___参考。', '___制定。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '背包客',
                'pinyin' => 'bēi bāo kè',
                'simplified' => '背包客',
                'traditional' => '背包客',
                'part_of_speech' => 'noun',
                'meaning' => 'Backpacker',
                'meaning_zh' => '背包客',
                'example_sentence' => '他是个背包客。',
                'example_translation' => 'He is a backpacker.',
                'definition' => 'Backpacker, budget traveler',
                'sentences' => ['___旅行。', '___住宿。', '___路线。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '自由行',
                'pinyin' => 'zì yóu xíng',
                'simplified' => '自由行',
                'traditional' => '自由行',
                'part_of_speech' => 'noun',
                'meaning' => 'Independent travel / FIT',
                'meaning_zh' => '自由行',
                'example_sentence' => '喜欢自由行。',
                'example_translation' => 'Like independent travel.',
                'definition' => 'Independent travel, free and easy tour',
                'sentences' => ['___游客。', '___安排。', '___路线。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '跟团游',
                'pinyin' => 'gēn tuán yóu',
                'simplified' => '跟团游',
                'traditional' => '跟團遊',
                'part_of_speech' => 'noun',
                'meaning' => 'Group tour / Package tour',
                'meaning_zh' => '跟团游',
                'example_sentence' => '选择跟团游。',
                'example_translation' => 'Choose a group tour.',
                'definition' => 'Group tour, package tour',
                'sentences' => ['___安排。', '___行程。', '___导游。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 148,
                'word' => '风景',
                'pinyin' => 'fēng jǐng',
                'simplified' => '风景',
                'traditional' => '風景',
                'part_of_speech' => 'noun',
                'meaning' => 'Scenery / Landscape',
                'meaning_zh' => '风景',
                'example_sentence' => '风景很美。',
                'example_translation' => 'The scenery is very beautiful.',
                'definition' => 'Scenery, landscape, view',
                'sentences' => ['___优美。', '___如画。', '___名胜。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 149: Cultural Experiences - 文化体验
        $cultureVocab = [
            [
                'topic_id' => 149,
                'word' => '体验',
                'pinyin' => 'tǐ yàn',
                'simplified' => '体验',
                'traditional' => '體驗',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To experience / Experience',
                'meaning_zh' => '体验',
                'example_sentence' => '体验不同文化。',
                'example_translation' => 'Experience different cultures.',
                'definition' => 'To experience, experience',
                'sentences' => ['___生活。', '___活动。', '___感受。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '文化',
                'pinyin' => 'wén huà',
                'simplified' => '文化',
                'traditional' => '文化',
                'part_of_speech' => 'noun',
                'meaning' => 'Culture',
                'meaning_zh' => '文化',
                'example_sentence' => '学习中国文化。',
                'example_translation' => 'Learn Chinese culture.',
                'definition' => 'Culture, civilization',
                'sentences' => ['___传统。', '___交流。', '___差异。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '传统文化很重要。',
                'example_translation' => 'Traditional culture is very important.',
                'definition' => 'Tradition, traditional, convention',
                'sentences' => ['___节日。', '___习俗。', '___艺术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '民俗',
                'pinyin' => 'mín sú',
                'simplified' => '民俗',
                'traditional' => '民俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Folk custom',
                'meaning_zh' => '民俗',
                'example_sentence' => '了解民俗文化。',
                'example_translation' => 'Learn about folk customs.',
                'definition' => 'Folk custom, folklore',
                'sentences' => ['___活动。', '___文化。', '___村。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '手工艺',
                'pinyin' => 'shǒu gōng yì',
                'simplified' => '手工艺',
                'traditional' => '手工藝',
                'part_of_speech' => 'noun',
                'meaning' => 'Handicraft',
                'meaning_zh' => '手工艺',
                'example_sentence' => '学习手工艺。',
                'example_translation' => 'Learn handicrafts.',
                'definition' => 'Handicraft, handiwork',
                'sentences' => ['___品。', '___制作。', '___传承。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '书法',
                'pinyin' => 'shū fǎ',
                'simplified' => '书法',
                'traditional' => '書法',
                'part_of_speech' => 'noun',
                'meaning' => 'Calligraphy',
                'meaning_zh' => '书法',
                'example_sentence' => '练习书法。',
                'example_translation' => 'Practice calligraphy.',
                'definition' => 'Calligraphy, penmanship',
                'sentences' => ['___艺术。', '___作品。', '___大师。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '武术',
                'pinyin' => 'wǔ shù',
                'simplified' => '武术',
                'traditional' => '武術',
                'part_of_speech' => 'noun',
                'meaning' => 'Martial arts / Wushu',
                'meaning_zh' => '武术',
                'example_sentence' => '学习武术。',
                'example_translation' => 'Learn martial arts.',
                'definition' => 'Martial arts, wushu, kung fu',
                'sentences' => ['___表演。', '___比赛。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '茶道',
                'pinyin' => 'chá dào',
                'simplified' => '茶道',
                'traditional' => '茶道',
                'part_of_speech' => 'noun',
                'meaning' => 'Tea ceremony / Tea culture',
                'meaning_zh' => '茶道',
                'example_sentence' => '学习茶道。',
                'example_translation' => 'Learn tea ceremony.',
                'definition' => 'Tea ceremony, tea culture',
                'sentences' => ['___文化。', '___表演。', '___艺术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '戏曲',
                'pinyin' => 'xì qǔ',
                'simplified' => '戏曲',
                'traditional' => '戲曲',
                'part_of_speech' => 'noun',
                'meaning' => 'Traditional opera',
                'meaning_zh' => '戏曲',
                'example_sentence' => '欣赏戏曲。',
                'example_translation' => 'Appreciate traditional opera.',
                'definition' => 'Traditional opera, Chinese opera',
                'sentences' => ['___表演。', '___艺术。', '___文化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '京剧',
                'pinyin' => 'jīng jù',
                'simplified' => '京剧',
                'traditional' => '京劇',
                'part_of_speech' => 'noun',
                'meaning' => 'Peking opera',
                'meaning_zh' => '京剧',
                'example_sentence' => '看京剧表演。',
                'example_translation' => 'Watch Peking opera performance.',
                'definition' => 'Peking opera, Beijing opera',
                'sentences' => ['___脸谱。', '___表演。', '___艺术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '剪纸',
                'pinyin' => 'jiǎn zhǐ',
                'simplified' => '剪纸',
                'traditional' => '剪紙',
                'part_of_speech' => 'noun',
                'meaning' => 'Paper cutting',
                'meaning_zh' => '剪纸',
                'example_sentence' => '学习剪纸。',
                'example_translation' => 'Learn paper cutting.',
                'definition' => 'Paper cutting, paper-cut',
                'sentences' => ['___艺术。', '___作品。', '___技巧。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '陶瓷',
                'pinyin' => 'táo cí',
                'simplified' => '陶瓷',
                'traditional' => '陶瓷',
                'part_of_speech' => 'noun',
                'meaning' => 'Pottery and porcelain / Ceramics',
                'meaning_zh' => '陶瓷',
                'example_sentence' => '制作陶瓷。',
                'example_translation' => 'Make pottery.',
                'definition' => 'Pottery and porcelain, ceramics',
                'sentences' => ['___艺术。', '___制品。', '___工艺。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '刺绣',
                'pinyin' => 'cì xiù',
                'simplified' => '刺绣',
                'traditional' => '刺繡',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Embroidery / To embroider',
                'meaning_zh' => '刺绣',
                'example_sentence' => '学习刺绣。',
                'example_translation' => 'Learn embroidery.',
                'definition' => 'Embroidery, to embroider',
                'sentences' => ['___作品。', '___工艺。', '___技术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '民族',
                'pinyin' => 'mín zú',
                'simplified' => '民族',
                'traditional' => '民族',
                'part_of_speech' => 'noun',
                'meaning' => 'Ethnic group / Nationality',
                'meaning_zh' => '民族',
                'example_sentence' => '尊重民族文化。',
                'example_translation' => 'Respect ethnic culture.',
                'definition' => 'Ethnic group, nationality, nation',
                'sentences' => ['___文化。', '___服装。', '___团结。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '融入',
                'pinyin' => 'róng rù',
                'simplified' => '融入',
                'traditional' => '融入',
                'part_of_speech' => 'verb',
                'meaning' => 'To integrate / To blend in',
                'meaning_zh' => '融入',
                'example_sentence' => '融入当地文化。',
                'example_translation' => 'Integrate into local culture.',
                'definition' => 'To integrate, to blend in, to merge',
                'sentences' => ['___社会。', '___环境。', '___生活。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '适应',
                'pinyin' => 'shì yìng',
                'simplified' => '适应',
                'traditional' => '適應',
                'part_of_speech' => 'verb',
                'meaning' => 'To adapt / To adjust',
                'meaning_zh' => '适应',
                'example_sentence' => '适应新环境。',
                'example_translation' => 'Adapt to the new environment.',
                'definition' => 'To adapt, to adjust, to get used to',
                'sentences' => ['___能力。', '___过程。', '___变化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '差异',
                'pinyin' => 'chā yì',
                'simplified' => '差异',
                'traditional' => '差異',
                'part_of_speech' => 'noun',
                'meaning' => 'Difference / Disparity',
                'meaning_zh' => '差异',
                'example_sentence' => '文化差异很大。',
                'example_translation' => 'Cultural differences are significant.',
                'definition' => 'Difference, disparity, distinction',
                'sentences' => ['___性。', '___明显。', '___缩小。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '包容',
                'pinyin' => 'bāo róng',
                'simplified' => '包容',
                'traditional' => '包容',
                'part_of_speech' => 'verb',
                'meaning' => 'To tolerate / Tolerance',
                'meaning_zh' => '包容',
                'example_sentence' => '要包容不同文化。',
                'example_translation' => 'Need to tolerate different cultures.',
                'definition' => 'To tolerate, tolerance, inclusive',
                'sentences' => ['___性。', '___理解。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '尊重',
                'pinyin' => 'zūn zhòng',
                'simplified' => '尊重',
                'traditional' => '尊重',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To respect / Respect',
                'meaning_zh' => '尊重',
                'example_sentence' => '要尊重他人。',
                'example_translation' => 'Need to respect others.',
                'definition' => 'To respect, respect, esteem',
                'sentences' => ['___文化。', '___习俗。', '___差异。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 149,
                'word' => '传承',
                'pinyin' => 'chuán chéng',
                'simplified' => '传承',
                'traditional' => '傳承',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To inherit / Inheritance',
                'meaning_zh' => '传承',
                'example_sentence' => '传承文化遗产。',
                'example_translation' => 'Inherit cultural heritage.',
                'definition' => 'To inherit, inheritance, to pass on',
                'sentences' => ['___文化。', '___技艺。', '___精神。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($habitsVocab, $medicineVocab, $travelVocab, $cultureVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
