<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic134to137Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [134, 137])->delete();

        // Topic 134: Foreign Language Learning - 外语学习
        $languageVocab = [
            [
                'topic_id' => 134,
                'word' => '外语',
                'pinyin' => 'wài yǔ',
                'simplified' => '外语',
                'traditional' => '外語',
                'part_of_speech' => 'noun',
                'meaning' => 'Foreign language',
                'meaning_zh' => '外语',
                'example_sentence' => '学习外语很有用。',
                'example_translation' => 'Learning a foreign language is very useful.',
                'definition' => 'Foreign language, non-native language',
                'sentences' => ['___学习。', '___水平。', '___能力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '母语',
                'pinyin' => 'mǔ yǔ',
                'simplified' => '母语',
                'traditional' => '母語',
                'part_of_speech' => 'noun',
                'meaning' => 'Mother tongue / Native language',
                'meaning_zh' => '母语',
                'example_sentence' => '中文是我的母语。',
                'example_translation' => 'Chinese is my mother tongue.',
                'definition' => 'Mother tongue, native language',
                'sentences' => ['___是中文。', '___环境。', '___思维。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '发音',
                'pinyin' => 'fā yīn',
                'simplified' => '发音',
                'traditional' => '發音',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Pronunciation / To pronounce',
                'meaning_zh' => '发音',
                'example_sentence' => '他的发音很标准。',
                'example_translation' => 'His pronunciation is very standard.',
                'definition' => 'Pronunciation, to pronounce',
                'sentences' => ['___准确。', '___练习。', '___标准。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '语音',
                'pinyin' => 'yǔ yīn',
                'simplified' => '语音',
                'traditional' => '語音',
                'part_of_speech' => 'noun',
                'meaning' => 'Speech sound / Phonetics',
                'meaning_zh' => '语音',
                'example_sentence' => '语音语调很重要。',
                'example_translation' => 'Speech sound and intonation are very important.',
                'definition' => 'Speech sound, phonetics, voice',
                'sentences' => ['___识别。', '___输入。', '___助手。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '语法',
                'pinyin' => 'yǔ fǎ',
                'simplified' => '语法',
                'traditional' => '語法',
                'part_of_speech' => 'noun',
                'meaning' => 'Grammar',
                'meaning_zh' => '语法',
                'example_sentence' => '要注意语法规则。',
                'example_translation' => 'Need to pay attention to grammar rules.',
                'definition' => 'Grammar, grammatical rules',
                'sentences' => ['___规则。', '___错误。', '___结构。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '词汇',
                'pinyin' => 'cí huì',
                'simplified' => '词汇',
                'traditional' => '詞彙',
                'part_of_speech' => 'noun',
                'meaning' => 'Vocabulary',
                'meaning_zh' => '词汇',
                'example_sentence' => '要扩大词汇量。',
                'example_translation' => 'Need to expand vocabulary.',
                'definition' => 'Vocabulary, lexicon',
                'sentences' => ['___量。', '___学习。', '___积累。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '口语',
                'pinyin' => 'kǒu yǔ',
                'simplified' => '口语',
                'traditional' => '口語',
                'part_of_speech' => 'noun',
                'meaning' => 'Spoken language / Oral',
                'meaning_zh' => '口语',
                'example_sentence' => '他的口语很流利。',
                'example_translation' => 'His spoken language is very fluent.',
                'definition' => 'Spoken language, oral, colloquial',
                'sentences' => ['___练习。', '___考试。', '___表达。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '书面语',
                'pinyin' => 'shū miàn yǔ',
                'simplified' => '书面语',
                'traditional' => '書面語',
                'part_of_speech' => 'noun',
                'meaning' => 'Written language',
                'meaning_zh' => '书面语',
                'example_sentence' => '书面语和口语不同。',
                'example_translation' => 'Written language is different from spoken language.',
                'definition' => 'Written language, formal written form',
                'sentences' => ['___表达。', '___文章。', '___规范。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '听力',
                'pinyin' => 'tīng lì',
                'simplified' => '听力',
                'traditional' => '聽力',
                'part_of_speech' => 'noun',
                'meaning' => 'Listening comprehension / Hearing',
                'meaning_zh' => '听力',
                'example_sentence' => '听力练习很重要。',
                'example_translation' => 'Listening practice is very important.',
                'definition' => 'Listening comprehension, hearing ability',
                'sentences' => ['___训练。', '___测试。', '___材料。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '阅读',
                'pinyin' => 'yuè dú',
                'simplified' => '阅读',
                'traditional' => '閱讀',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Reading / To read',
                'meaning_zh' => '阅读',
                'example_sentence' => '多阅读可以提高语言水平。',
                'example_translation' => 'Reading more can improve language proficiency.',
                'definition' => 'Reading, to read',
                'sentences' => ['___理解。', '___速度。', '___能力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '写作',
                'pinyin' => 'xiě zuò',
                'simplified' => '写作',
                'traditional' => '寫作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Writing / To write',
                'meaning_zh' => '写作',
                'example_sentence' => '写作需要多练习。',
                'example_translation' => 'Writing requires lots of practice.',
                'definition' => 'Writing, to write, composition',
                'sentences' => ['___能力。', '___技巧。', '___训练。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '翻译',
                'pinyin' => 'fān yì',
                'simplified' => '翻译',
                'traditional' => '翻譯',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Translation / To translate',
                'meaning_zh' => '翻译',
                'example_sentence' => '我需要翻译这篇文章。',
                'example_translation' => 'I need to translate this article.',
                'definition' => 'Translation, to translate, interpreter',
                'sentences' => ['___软件。', '___工作。', '___准确。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '口音',
                'pinyin' => 'kǒu yīn',
                'simplified' => '口音',
                'traditional' => '口音',
                'part_of_speech' => 'noun',
                'meaning' => 'Accent',
                'meaning_zh' => '口音',
                'example_sentence' => '他有一点口音。',
                'example_translation' => 'He has a bit of an accent.',
                'definition' => 'Accent, pronunciation characteristics',
                'sentences' => ['地方___。', '___重。', '___纯正。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '方言',
                'pinyin' => 'fāng yán',
                'simplified' => '方言',
                'traditional' => '方言',
                'part_of_speech' => 'noun',
                'meaning' => 'Dialect',
                'meaning_zh' => '方言',
                'example_sentence' => '中国有很多方言。',
                'example_translation' => 'China has many dialects.',
                'definition' => 'Dialect, regional language',
                'sentences' => ['地方___。', '___差异。', '___保护。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '交流',
                'pinyin' => 'jiāo liú',
                'simplified' => '交流',
                'traditional' => '交流',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Communication / To communicate',
                'meaning_zh' => '交流',
                'example_sentence' => '语言是交流的工具。',
                'example_translation' => 'Language is a tool for communication.',
                'definition' => 'Communication, exchange, to communicate',
                'sentences' => ['___经验。', '___活动。', '___障碍。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '表达',
                'pinyin' => 'biǎo dá',
                'simplified' => '表达',
                'traditional' => '表達',
                'part_of_speech' => 'verb',
                'meaning' => 'To express',
                'meaning_zh' => '表达',
                'example_sentence' => '他善于表达自己的想法。',
                'example_translation' => 'He is good at expressing his thoughts.',
                'definition' => 'To express, to convey',
                'sentences' => ['___能力。', '___方式。', '___清楚。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '流利',
                'pinyin' => 'liú lì',
                'simplified' => '流利',
                'traditional' => '流利',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fluent',
                'meaning_zh' => '流利',
                'example_sentence' => '她说英语很流利。',
                'example_translation' => 'She speaks English very fluently.',
                'definition' => 'Fluent, smooth',
                'sentences' => ['说得___。', '___程度。', '___表达。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '熟练',
                'pinyin' => 'shú liàn',
                'simplified' => '熟练',
                'traditional' => '熟練',
                'part_of_speech' => 'adjective',
                'meaning' => 'Skilled / Proficient',
                'meaning_zh' => '熟练',
                'example_sentence' => '他汉语很熟练。',
                'example_translation' => 'He is very proficient in Chinese.',
                'definition' => 'Skilled, proficient, practiced',
                'sentences' => ['___掌握。', '___运用。', '___程度。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '语言环境',
                'pinyin' => 'yǔ yán huán jìng',
                'simplified' => '语言环境',
                'traditional' => '語言環境',
                'part_of_speech' => 'noun',
                'meaning' => 'Language environment',
                'meaning_zh' => '语言环境',
                'example_sentence' => '好的语言环境很重要。',
                'example_translation' => 'A good language environment is very important.',
                'definition' => 'Language environment, linguistic atmosphere',
                'sentences' => ['___营造。', '___缺乏。', '___影响。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 134,
                'word' => '文化差异',
                'pinyin' => 'wén huà chā yì',
                'simplified' => '文化差异',
                'traditional' => '文化差異',
                'part_of_speech' => 'noun',
                'meaning' => 'Cultural difference',
                'meaning_zh' => '文化差异',
                'example_sentence' => '要了解文化差异。',
                'example_translation' => 'Need to understand cultural differences.',
                'definition' => 'Cultural difference, cultural gap',
                'sentences' => ['___很大。', '___理解。', '___尊重。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 135: Exams and Achievement - 考试与成绩
        $examVocab = [
            [
                'topic_id' => 135,
                'word' => '考试',
                'pinyin' => 'kǎo shì',
                'simplified' => '考试',
                'traditional' => '考試',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Exam / To take an exam',
                'meaning_zh' => '考试',
                'example_sentence' => '明天有个重要考试。',
                'example_translation' => 'There is an important exam tomorrow.',
                'definition' => 'Exam, examination, test',
                'sentences' => ['___准备。', '___通过。', '___成绩。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '测验',
                'pinyin' => 'cè yàn',
                'simplified' => '测验',
                'traditional' => '測驗',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Test / Quiz',
                'meaning_zh' => '测验',
                'example_sentence' => '今天有个小测验。',
                'example_translation' => 'There is a small quiz today.',
                'definition' => 'Test, quiz, to test',
                'sentences' => ['___成绩。', '___题目。', '___结果。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '试卷',
                'pinyin' => 'shì juàn',
                'simplified' => '试卷',
                'traditional' => '試卷',
                'part_of_speech' => 'noun',
                'meaning' => 'Exam paper / Test paper',
                'meaning_zh' => '试卷',
                'example_sentence' => '请交上试卷。',
                'example_translation' => 'Please hand in the exam paper.',
                'definition' => 'Exam paper, test paper',
                'sentences' => ['___难度。', '___批改。', '___分析。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '题目',
                'pinyin' => 'tí mù',
                'simplified' => '题目',
                'traditional' => '題目',
                'part_of_speech' => 'noun',
                'meaning' => 'Question / Problem / Topic',
                'meaning_zh' => '题目',
                'example_sentence' => '这道题目很难。',
                'example_translation' => 'This question is very difficult.',
                'definition' => 'Question, problem, topic, title',
                'sentences' => ['___要求。', '___类型。', '___难度。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '答案',
                'pinyin' => 'dá àn',
                'simplified' => '答案',
                'traditional' => '答案',
                'part_of_speech' => 'noun',
                'meaning' => 'Answer / Solution',
                'meaning_zh' => '答案',
                'example_sentence' => '答案是什么？',
                'example_translation' => 'What is the answer?',
                'definition' => 'Answer, solution, key',
                'sentences' => ['正确___。', '___解析。', '___公布。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '及格',
                'pinyin' => 'jí gé',
                'simplified' => '及格',
                'traditional' => '及格',
                'part_of_speech' => 'verb',
                'meaning' => 'To pass (an exam)',
                'meaning_zh' => '及格',
                'example_sentence' => '他考试及格了。',
                'example_translation' => 'He passed the exam.',
                'definition' => 'To pass, to meet the standard',
                'sentences' => ['___线。', '___分数。', '勉强___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '不及格',
                'pinyin' => 'bù jí gé',
                'simplified' => '不及格',
                'traditional' => '不及格',
                'part_of_speech' => 'verb',
                'meaning' => 'To fail (an exam)',
                'meaning_zh' => '不及格',
                'example_sentence' => '他这次考试不及格。',
                'example_translation' => 'He failed the exam this time.',
                'definition' => 'To fail, below passing grade',
                'sentences' => ['___了。', '___原因。', '___科目。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '优秀',
                'pinyin' => 'yōu xiù',
                'simplified' => '优秀',
                'traditional' => '優秀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Excellent / Outstanding',
                'meaning_zh' => '优秀',
                'example_sentence' => '她是优秀学生。',
                'example_translation' => 'She is an excellent student.',
                'definition' => 'Excellent, outstanding, superior',
                'sentences' => ['___成绩。', '___表现。', '___人才。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '成绩单',
                'pinyin' => 'chéng jì dān',
                'simplified' => '成绩单',
                'traditional' => '成績單',
                'part_of_speech' => 'noun',
                'meaning' => 'Transcript / Report card',
                'meaning_zh' => '成绩单',
                'example_sentence' => '我收到了成绩单。',
                'example_translation' => 'I received the transcript.',
                'definition' => 'Transcript, report card, grade sheet',
                'sentences' => ['查看___。', '___公布。', '___分析。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '复习',
                'pinyin' => 'fù xí',
                'simplified' => '复习',
                'traditional' => '複習',
                'part_of_speech' => 'verb',
                'meaning' => 'To review / To revise',
                'meaning_zh' => '复习',
                'example_sentence' => '考前要认真复习。',
                'example_translation' => 'Need to review carefully before the exam.',
                'definition' => 'To review, to revise, revision',
                'sentences' => ['___功课。', '___资料。', '___计划。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '预习',
                'pinyin' => 'yù xí',
                'simplified' => '预习',
                'traditional' => '預習',
                'part_of_speech' => 'verb',
                'meaning' => 'To preview / To prepare lessons',
                'meaning_zh' => '预习',
                'example_sentence' => '要提前预习新课。',
                'example_translation' => 'Need to preview new lessons in advance.',
                'definition' => 'To preview, to prepare lessons',
                'sentences' => ['___课文。', '___内容。', '___作业。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '练习',
                'pinyin' => 'liàn xí',
                'simplified' => '练习',
                'traditional' => '練習',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To practice / Exercise',
                'meaning_zh' => '练习',
                'example_sentence' => '多做练习题。',
                'example_translation' => 'Do more practice exercises.',
                'definition' => 'To practice, exercise, drill',
                'sentences' => ['___题。', '___册。', '___机会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '错误',
                'pinyin' => 'cuò wù',
                'simplified' => '错误',
                'traditional' => '錯誤',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Mistake / Error / Wrong',
                'meaning_zh' => '错误',
                'example_sentence' => '要改正错误。',
                'example_translation' => 'Need to correct mistakes.',
                'definition' => 'Mistake, error, wrong',
                'sentences' => ['___很多。', '___分析。', '___改正。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '进步',
                'pinyin' => 'jìn bù',
                'simplified' => '进步',
                'traditional' => '進步',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Progress / To make progress',
                'meaning_zh' => '进步',
                'example_sentence' => '他进步很快。',
                'example_translation' => 'He is making rapid progress.',
                'definition' => 'Progress, to make progress, improvement',
                'sentences' => ['___很大。', '___显著。', '___空间。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '退步',
                'pinyin' => 'tuì bù',
                'simplified' => '退步',
                'traditional' => '退步',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To regress / Deterioration',
                'meaning_zh' => '退步',
                'example_sentence' => '成绩退步了。',
                'example_translation' => 'The grades have deteriorated.',
                'definition' => 'To regress, deterioration, to fall behind',
                'sentences' => ['___明显。', '___原因。', '___了。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '目标',
                'pinyin' => 'mù biāo',
                'simplified' => '目标',
                'traditional' => '目標',
                'part_of_speech' => 'noun',
                'meaning' => 'Goal / Target / Objective',
                'meaning_zh' => '目标',
                'example_sentence' => '要设定学习目标。',
                'example_translation' => 'Need to set learning goals.',
                'definition' => 'Goal, target, objective',
                'sentences' => ['___明确。', '___实现。', '___定位。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '努力',
                'pinyin' => 'nǔ lì',
                'simplified' => '努力',
                'traditional' => '努力',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To make an effort / Hardworking',
                'meaning_zh' => '努力',
                'example_sentence' => '要努力学习。',
                'example_translation' => 'Need to study hard.',
                'definition' => 'To make an effort, hardworking, diligent',
                'sentences' => ['___工作。', '___奋斗。', '___方向。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '刻苦',
                'pinyin' => 'kè kǔ',
                'simplified' => '刻苦',
                'traditional' => '刻苦',
                'part_of_speech' => 'adjective',
                'meaning' => 'Hardworking / Assiduous',
                'meaning_zh' => '刻苦',
                'example_sentence' => '他学习很刻苦。',
                'example_translation' => 'He studies very hard.',
                'definition' => 'Hardworking, assiduous, painstaking',
                'sentences' => ['___学习。', '___训练。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '竞争',
                'pinyin' => 'jìng zhēng',
                'simplified' => '竞争',
                'traditional' => '競爭',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Competition / To compete',
                'meaning_zh' => '竞争',
                'example_sentence' => '考试竞争很激烈。',
                'example_translation' => 'Exam competition is very fierce.',
                'definition' => 'Competition, to compete, rivalry',
                'sentences' => ['___激烈。', '___对手。', '___优势。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 135,
                'word' => '排名',
                'pinyin' => 'pái míng',
                'simplified' => '排名',
                'traditional' => '排名',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Ranking / To rank',
                'meaning_zh' => '排名',
                'example_sentence' => '他的排名很靠前。',
                'example_translation' => 'His ranking is very high.',
                'definition' => 'Ranking, to rank, position',
                'sentences' => ['___第一。', '___上升。', '___下降。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 136: Chinese Literature - 中国文学
        $literatureVocab = [
            [
                'topic_id' => 136,
                'word' => '文学',
                'pinyin' => 'wén xué',
                'simplified' => '文学',
                'traditional' => '文學',
                'part_of_speech' => 'noun',
                'meaning' => 'Literature',
                'meaning_zh' => '文学',
                'example_sentence' => '我喜欢中国文学。',
                'example_translation' => 'I like Chinese literature.',
                'definition' => 'Literature, literary',
                'sentences' => ['___作品。', '___创作。', '___研究。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '诗歌',
                'pinyin' => 'shī gē',
                'simplified' => '诗歌',
                'traditional' => '詩歌',
                'part_of_speech' => 'noun',
                'meaning' => 'Poetry / Poem',
                'meaning_zh' => '诗歌',
                'example_sentence' => '唐代诗歌很有名。',
                'example_translation' => 'Tang Dynasty poetry is very famous.',
                'definition' => 'Poetry, poem, verse',
                'sentences' => ['___创作。', '___朗诵。', '___欣赏。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '小说',
                'pinyin' => 'xiǎo shuō',
                'simplified' => '小说',
                'traditional' => '小說',
                'part_of_speech' => 'noun',
                'meaning' => 'Novel / Fiction',
                'meaning_zh' => '小说',
                'example_sentence' => '这是一部长篇小说。',
                'example_translation' => 'This is a full-length novel.',
                'definition' => 'Novel, fiction',
                'sentences' => ['___家。', '___人物。', '___情节。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '散文',
                'pinyin' => 'sǎn wén',
                'simplified' => '散文',
                'traditional' => '散文',
                'part_of_speech' => 'noun',
                'meaning' => 'Prose / Essay',
                'meaning_zh' => '散文',
                'example_sentence' => '他写散文很好。',
                'example_translation' => 'He writes prose very well.',
                'definition' => 'Prose, essay',
                'sentences' => ['___集。', '___写作。', '___风格。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '戏剧',
                'pinyin' => 'xì jù',
                'simplified' => '戏剧',
                'traditional' => '戲劇',
                'part_of_speech' => 'noun',
                'meaning' => 'Drama / Theatre',
                'meaning_zh' => '戏剧',
                'example_sentence' => '我喜欢看戏剧表演。',
                'example_translation' => 'I like watching drama performances.',
                'definition' => 'Drama, theatre, play',
                'sentences' => ['___演出。', '___艺术。', '___作品。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '作家',
                'pinyin' => 'zuò jiā',
                'simplified' => '作家',
                'traditional' => '作家',
                'part_of_speech' => 'noun',
                'meaning' => 'Writer / Author',
                'meaning_zh' => '作家',
                'example_sentence' => '他是著名作家。',
                'example_translation' => 'He is a famous writer.',
                'definition' => 'Writer, author',
                'sentences' => ['___协会。', '___创作。', '___风格。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '诗人',
                'pinyin' => 'shī rén',
                'simplified' => '诗人',
                'traditional' => '詩人',
                'part_of_speech' => 'noun',
                'meaning' => 'Poet',
                'meaning_zh' => '诗人',
                'example_sentence' => '李白是唐代著名诗人。',
                'example_translation' => 'Li Bai is a famous Tang Dynasty poet.',
                'definition' => 'Poet',
                'sentences' => ['___作品。', '___风格。', '___情怀。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '作品',
                'pinyin' => 'zuò pǐn',
                'simplified' => '作品',
                'traditional' => '作品',
                'part_of_speech' => 'noun',
                'meaning' => 'Work / Creation',
                'meaning_zh' => '作品',
                'example_sentence' => '这是他的代表作品。',
                'example_translation' => 'This is his representative work.',
                'definition' => 'Work, creation, opus',
                'sentences' => ['___展览。', '___欣赏。', '___分析。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '著作',
                'pinyin' => 'zhù zuò',
                'simplified' => '著作',
                'traditional' => '著作',
                'part_of_speech' => 'noun',
                'meaning' => 'Work / Writing / Book',
                'meaning_zh' => '著作',
                'example_sentence' => '他有很多著作。',
                'example_translation' => 'He has many works.',
                'definition' => 'Work, writing, book, treatise',
                'sentences' => ['___等身。', '___权。', '___出版。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '情节',
                'pinyin' => 'qíng jié',
                'simplified' => '情节',
                'traditional' => '情節',
                'part_of_speech' => 'noun',
                'meaning' => 'Plot / Storyline',
                'meaning_zh' => '情节',
                'example_sentence' => '小说情节很精彩。',
                'example_translation' => 'The novel\'s plot is very exciting.',
                'definition' => 'Plot, storyline, scenario',
                'sentences' => ['___发展。', '___曲折。', '___紧凑。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '人物',
                'pinyin' => 'rén wù',
                'simplified' => '人物',
                'traditional' => '人物',
                'part_of_speech' => 'noun',
                'meaning' => 'Character / Figure / Personage',
                'meaning_zh' => '人物',
                'example_sentence' => '小说人物很生动。',
                'example_translation' => 'The novel\'s characters are very vivid.',
                'definition' => 'Character, figure, personage',
                'sentences' => ['___形象。', '___性格。', '___刻画。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '主题',
                'pinyin' => 'zhǔ tí',
                'simplified' => '主题',
                'traditional' => '主題',
                'part_of_speech' => 'noun',
                'meaning' => 'Theme / Subject',
                'meaning_zh' => '主题',
                'example_sentence' => '作品主题深刻。',
                'example_translation' => 'The theme of the work is profound.',
                'definition' => 'Theme, subject, topic',
                'sentences' => ['___思想。', '___鲜明。', '___曲。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '风格',
                'pinyin' => 'fēng gé',
                'simplified' => '风格',
                'traditional' => '風格',
                'part_of_speech' => 'noun',
                'meaning' => 'Style',
                'meaning_zh' => '风格',
                'example_sentence' => '每个作家都有自己的风格。',
                'example_translation' => 'Every writer has their own style.',
                'definition' => 'Style, manner',
                'sentences' => ['艺术___。', '___独特。', '___多样。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '描写',
                'pinyin' => 'miáo xiě',
                'simplified' => '描写',
                'traditional' => '描寫',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To describe / Description',
                'meaning_zh' => '描写',
                'example_sentence' => '作者描写得很生动。',
                'example_translation' => 'The author describes it very vividly.',
                'definition' => 'To describe, description, depiction',
                'sentences' => ['___细节。', '___手法。', '___景物。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '表现',
                'pinyin' => 'biǎo xiàn',
                'simplified' => '表现',
                'traditional' => '表現',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To show / To express / Performance',
                'meaning_zh' => '表现',
                'example_sentence' => '作品表现了人物性格。',
                'example_translation' => 'The work expresses the character\'s personality.',
                'definition' => 'To show, to express, performance',
                'sentences' => ['___手法。', '___形式。', '___力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '经典',
                'pinyin' => 'jīng diǎn',
                'simplified' => '经典',
                'traditional' => '經典',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Classic / Classical',
                'meaning_zh' => '经典',
                'example_sentence' => '这是一部经典作品。',
                'example_translation' => 'This is a classic work.',
                'definition' => 'Classic, classical, scripture',
                'sentences' => ['___名著。', '___之作。', '___文学。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '中国传统文学很丰富。',
                'example_translation' => 'Chinese traditional literature is very rich.',
                'definition' => 'Tradition, traditional, convention',
                'sentences' => ['___文化。', '___节日。', '___习俗。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '现代',
                'pinyin' => 'xiàn dài',
                'simplified' => '现代',
                'traditional' => '現代',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Modern / Contemporary',
                'meaning_zh' => '现代',
                'example_sentence' => '现代文学也很有特色。',
                'example_translation' => 'Modern literature also has unique characteristics.',
                'definition' => 'Modern, contemporary',
                'sentences' => ['___社会。', '___化。', '___技术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '鲁迅',
                'pinyin' => 'Lǔ Xùn',
                'simplified' => '鲁迅',
                'traditional' => '魯迅',
                'part_of_speech' => 'proper noun',
                'meaning' => 'Lu Xun (famous Chinese writer)',
                'meaning_zh' => '鲁迅',
                'example_sentence' => '鲁迅是中国现代文学的代表。',
                'example_translation' => 'Lu Xun is a representative of Chinese modern literature.',
                'definition' => 'Lu Xun, famous Chinese writer and thinker',
                'sentences' => ['___作品。', '___精神。', '___研究。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 136,
                'word' => '红楼梦',
                'pinyin' => 'Hóng Lóu Mèng',
                'simplified' => '红楼梦',
                'traditional' => '紅樓夢',
                'part_of_speech' => 'proper noun',
                'meaning' => 'Dream of the Red Chamber (classic novel)',
                'meaning_zh' => '红楼梦',
                'example_sentence' => '《红楼梦》是中国四大名著之一。',
                'example_translation' => '"Dream of the Red Chamber" is one of China\'s Four Great Classical Novels.',
                'definition' => 'Dream of the Red Chamber, classic Chinese novel',
                'sentences' => ['___研究。', '___人物。', '___艺术。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 137: Film, Music, and Painting - 影视音乐美术
        $artsVocab = [
            [
                'topic_id' => 137,
                'word' => '电影',
                'pinyin' => 'diàn yǐng',
                'simplified' => '电影',
                'traditional' => '電影',
                'part_of_speech' => 'noun',
                'meaning' => 'Movie / Film',
                'meaning_zh' => '电影',
                'example_sentence' => '我喜欢看电影。',
                'example_translation' => 'I like watching movies.',
                'definition' => 'Movie, film, cinema',
                'sentences' => ['___院。', '___票。', '___明星。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '电视剧',
                'pinyin' => 'diàn shì jù',
                'simplified' => '电视剧',
                'traditional' => '電視劇',
                'part_of_speech' => 'noun',
                'meaning' => 'TV series / TV drama',
                'meaning_zh' => '电视剧',
                'example_sentence' => '这部电视剧很受欢迎。',
                'example_translation' => 'This TV series is very popular.',
                'definition' => 'TV series, TV drama',
                'sentences' => ['___集。', '___演员。', '___收视率。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '导演',
                'pinyin' => 'dǎo yǎn',
                'simplified' => '导演',
                'traditional' => '導演',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Director / To direct',
                'meaning_zh' => '导演',
                'example_sentence' => '这位导演很有名。',
                'example_translation' => 'This director is very famous.',
                'definition' => 'Director, to direct',
                'sentences' => ['___作品。', '___风格。', '___技巧。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '演员',
                'pinyin' => 'yǎn yuán',
                'simplified' => '演员',
                'traditional' => '演員',
                'part_of_speech' => 'noun',
                'meaning' => 'Actor / Actress / Performer',
                'meaning_zh' => '演员',
                'example_sentence' => '他是专业演员。',
                'example_translation' => 'He is a professional actor.',
                'definition' => 'Actor, actress, performer',
                'sentences' => ['___表演。', '___阵容。', '___演技。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '表演',
                'pinyin' => 'biǎo yǎn',
                'simplified' => '表演',
                'traditional' => '表演',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To perform / Performance',
                'meaning_zh' => '表演',
                'example_sentence' => '表演很精彩。',
                'example_translation' => 'The performance is very exciting.',
                'definition' => 'To perform, performance, to act',
                'sentences' => ['___节目。', '___艺术。', '___技巧。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '剧本',
                'pinyin' => 'jù běn',
                'simplified' => '剧本',
                'traditional' => '劇本',
                'part_of_speech' => 'noun',
                'meaning' => 'Script / Screenplay',
                'meaning_zh' => '剧本',
                'example_sentence' => '这个剧本很好。',
                'example_translation' => 'This script is very good.',
                'definition' => 'Script, screenplay, play',
                'sentences' => ['___创作。', '___改编。', '___台词。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '音乐',
                'pinyin' => 'yīn yuè',
                'simplified' => '音乐',
                'traditional' => '音樂',
                'part_of_speech' => 'noun',
                'meaning' => 'Music',
                'meaning_zh' => '音乐',
                'example_sentence' => '我喜欢听音乐。',
                'example_translation' => 'I like listening to music.',
                'definition' => 'Music',
                'sentences' => ['___会。', '___家。', '___欣赏。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '歌曲',
                'pinyin' => 'gē qǔ',
                'simplified' => '歌曲',
                'traditional' => '歌曲',
                'part_of_speech' => 'noun',
                'meaning' => 'Song',
                'meaning_zh' => '歌曲',
                'example_sentence' => '这首歌曲很好听。',
                'example_translation' => 'This song sounds very good.',
                'definition' => 'Song, vocal music',
                'sentences' => ['___创作。', '___演唱。', '___流行。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '歌手',
                'pinyin' => 'gē shǒu',
                'simplified' => '歌手',
                'traditional' => '歌手',
                'part_of_speech' => 'noun',
                'meaning' => 'Singer',
                'meaning_zh' => '歌手',
                'example_sentence' => '她是著名歌手。',
                'example_translation' => 'She is a famous singer.',
                'definition' => 'Singer, vocalist',
                'sentences' => ['___演唱会。', '___专辑。', '___歌迷。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '乐器',
                'pinyin' => 'yuè qì',
                'simplified' => '乐器',
                'traditional' => '樂器',
                'part_of_speech' => 'noun',
                'meaning' => 'Musical instrument',
                'meaning_zh' => '乐器',
                'example_sentence' => '他会演奏多种乐器。',
                'example_translation' => 'He can play many musical instruments.',
                'definition' => 'Musical instrument',
                'sentences' => ['___演奏。', '___学习。', '___种类。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '钢琴',
                'pinyin' => 'gāng qín',
                'simplified' => '钢琴',
                'traditional' => '鋼琴',
                'part_of_speech' => 'noun',
                'meaning' => 'Piano',
                'meaning_zh' => '钢琴',
                'example_sentence' => '她在弹钢琴。',
                'example_translation' => 'She is playing the piano.',
                'definition' => 'Piano',
                'sentences' => ['弹___。', '___演奏。', '___曲。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '绘画',
                'pinyin' => 'huì huà',
                'simplified' => '绘画',
                'traditional' => '繪畫',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Painting / To paint',
                'meaning_zh' => '绘画',
                'example_sentence' => '他喜欢绘画。',
                'example_translation' => 'He likes painting.',
                'definition' => 'Painting, to paint, drawing',
                'sentences' => ['___艺术。', '___作品。', '___技巧。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '美术',
                'pinyin' => 'měi shù',
                'simplified' => '美术',
                'traditional' => '美術',
                'part_of_speech' => 'noun',
                'meaning' => 'Fine arts',
                'meaning_zh' => '美术',
                'example_sentence' => '美术馆有很多作品。',
                'example_translation' => 'The art gallery has many works.',
                'definition' => 'Fine arts, art',
                'sentences' => ['___作品。', '___馆。', '___教育。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '画家',
                'pinyin' => 'huà jiā',
                'simplified' => '画家',
                'traditional' => '畫家',
                'part_of_speech' => 'noun',
                'meaning' => 'Painter / Artist',
                'meaning_zh' => '画家',
                'example_sentence' => '他是著名画家。',
                'example_translation' => 'He is a famous painter.',
                'definition' => 'Painter, artist',
                'sentences' => ['___作品。', '___风格。', '___创作。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '作品',
                'pinyin' => 'zuò pǐn',
                'simplified' => '作品',
                'traditional' => '作品',
                'part_of_speech' => 'noun',
                'meaning' => 'Work / Creation',
                'meaning_zh' => '作品',
                'example_sentence' => '这幅作品很有价值。',
                'example_translation' => 'This work is very valuable.',
                'definition' => 'Work, creation, production',
                'sentences' => ['艺术___。', '___展览。', '___欣赏。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '艺术',
                'pinyin' => 'yì shù',
                'simplified' => '艺术',
                'traditional' => '藝術',
                'part_of_speech' => 'noun',
                'meaning' => 'Art',
                'meaning_zh' => '艺术',
                'example_sentence' => '艺术来源于生活。',
                'example_translation' => 'Art comes from life.',
                'definition' => 'Art, artistic',
                'sentences' => ['___品。', '___家。', '___价值。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '展览',
                'pinyin' => 'zhǎn lǎn',
                'simplified' => '展览',
                'traditional' => '展覽',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Exhibition / To exhibit',
                'meaning_zh' => '展览',
                'example_sentence' => '今天有艺术展览。',
                'example_translation' => 'There is an art exhibition today.',
                'definition' => 'Exhibition, to exhibit, to display',
                'sentences' => ['___会。', '___馆。', '___作品。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '欣赏',
                'pinyin' => 'xīn shǎng',
                'simplified' => '欣赏',
                'traditional' => '欣賞',
                'part_of_speech' => 'verb',
                'meaning' => 'To appreciate / To admire',
                'meaning_zh' => '欣赏',
                'example_sentence' => '我很欣赏这部作品。',
                'example_translation' => 'I really appreciate this work.',
                'definition' => 'To appreciate, to admire, to enjoy',
                'sentences' => ['___艺术。', '___音乐。', '___能力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '创作',
                'pinyin' => 'chuàng zuò',
                'simplified' => '创作',
                'traditional' => '創作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To create / Creation',
                'meaning_zh' => '创作',
                'example_sentence' => '他正在创作新作品。',
                'example_translation' => 'He is creating a new work.',
                'definition' => 'To create, creation, creative work',
                'sentences' => ['___灵感。', '___过程。', '___热情。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 137,
                'word' => '灵感',
                'pinyin' => 'líng gǎn',
                'simplified' => '灵感',
                'traditional' => '靈感',
                'part_of_speech' => 'noun',
                'meaning' => 'Inspiration',
                'meaning_zh' => '灵感',
                'example_sentence' => '他突然有了灵感。',
                'example_translation' => 'He suddenly got inspiration.',
                'definition' => 'Inspiration, flash of insight',
                'sentences' => ['___来源。', '___迸发。', '___枯竭。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($languageVocab, $examVocab, $literatureVocab, $artsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
