<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic142to145Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [142, 145])->delete();

        // Topic 142: Media and Social Networks - 传媒与社交媒体
        $mediaVocab = [
            [
                'topic_id' => 142,
                'word' => '媒体',
                'pinyin' => 'méi tǐ',
                'simplified' => '媒体',
                'traditional' => '媒體',
                'part_of_speech' => 'noun',
                'meaning' => 'Media',
                'meaning_zh' => '媒体',
                'example_sentence' => '媒体报道很重要。',
                'example_translation' => 'Media coverage is very important.',
                'definition' => 'Media, mass media',
                'sentences' => ['___报道。', '___平台。', '___影响。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '新闻',
                'pinyin' => 'xīn wén',
                'simplified' => '新闻',
                'traditional' => '新聞',
                'part_of_speech' => 'noun',
                'meaning' => 'News',
                'meaning_zh' => '新闻',
                'example_sentence' => '我每天看新闻。',
                'example_translation' => 'I watch the news every day.',
                'definition' => 'News, journalism',
                'sentences' => ['___联播。', '___记者。', '___发布会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '报道',
                'pinyin' => 'bào dào',
                'simplified' => '报道',
                'traditional' => '報道',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To report / News report',
                'meaning_zh' => '报道',
                'example_sentence' => '媒体报道了这件事。',
                'example_translation' => 'The media reported this matter.',
                'definition' => 'To report, news report, coverage',
                'sentences' => ['___新闻。', '___内容。', '___真实。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '记者',
                'pinyin' => 'jì zhě',
                'simplified' => '记者',
                'traditional' => '記者',
                'part_of_speech' => 'noun',
                'meaning' => 'Reporter / Journalist',
                'meaning_zh' => '记者',
                'example_sentence' => '他是一名记者。',
                'example_translation' => 'He is a reporter.',
                'definition' => 'Reporter, journalist, correspondent',
                'sentences' => ['___采访。', '___招待会。', '___报道。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '采访',
                'pinyin' => 'cǎi fǎng',
                'simplified' => '采访',
                'traditional' => '採訪',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To interview / Interview',
                'meaning_zh' => '采访',
                'example_sentence' => '记者采访了专家。',
                'example_translation' => 'The reporter interviewed the expert.',
                'definition' => 'To interview, interview, to cover',
                'sentences' => ['___对象。', '___内容。', '___报道。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '发布',
                'pinyin' => 'fā bù',
                'simplified' => '发布',
                'traditional' => '發布',
                'part_of_speech' => 'verb',
                'meaning' => 'To release / To publish',
                'meaning_zh' => '发布',
                'example_sentence' => '公司发布了新产品。',
                'example_translation' => 'The company released a new product.',
                'definition' => 'To release, to publish, to announce',
                'sentences' => ['___消息。', '___会。', '___信息。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '社交媒体',
                'pinyin' => 'shè jiāo méi tǐ',
                'simplified' => '社交媒体',
                'traditional' => '社交媒體',
                'part_of_speech' => 'noun',
                'meaning' => 'Social media',
                'meaning_zh' => '社交媒体',
                'example_sentence' => '社交媒体很流行。',
                'example_translation' => 'Social media is very popular.',
                'definition' => 'Social media, social networking',
                'sentences' => ['___平台。', '___传播。', '___营销。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '微博',
                'pinyin' => 'wēi bó',
                'simplified' => '微博',
                'traditional' => '微博',
                'part_of_speech' => 'noun',
                'meaning' => 'Microblog / Weibo',
                'meaning_zh' => '微博',
                'example_sentence' => '我在微博上发了消息。',
                'example_translation' => 'I posted a message on Weibo.',
                'definition' => 'Microblog, Weibo (Chinese social media)',
                'sentences' => ['___热搜。', '发___。', '___粉丝。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '微信',
                'pinyin' => 'wēi xìn',
                'simplified' => '微信',
                'traditional' => '微信',
                'part_of_speech' => 'noun',
                'meaning' => 'WeChat',
                'meaning_zh' => '微信',
                'example_sentence' => '我用微信联系朋友。',
                'example_translation' => 'I use WeChat to contact friends.',
                'definition' => 'WeChat (Chinese messaging app)',
                'sentences' => ['___群。', '___支付。', '___朋友圈。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '平台',
                'pinyin' => 'píng tái',
                'simplified' => '平台',
                'traditional' => '平台',
                'part_of_speech' => 'noun',
                'meaning' => 'Platform',
                'meaning_zh' => '平台',
                'example_sentence' => '这是一个很好的平台。',
                'example_translation' => 'This is a very good platform.',
                'definition' => 'Platform, stage',
                'sentences' => ['___建设。', '___服务。', '___经济。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '传播',
                'pinyin' => 'chuán bō',
                'simplified' => '传播',
                'traditional' => '傳播',
                'part_of_speech' => 'verb',
                'meaning' => 'To spread / To disseminate',
                'meaning_zh' => '传播',
                'example_sentence' => '信息传播很快。',
                'example_translation' => 'Information spreads very quickly.',
                'definition' => 'To spread, to disseminate, to propagate',
                'sentences' => ['___速度。', '___文化。', '___知识。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '影响力',
                'pinyin' => 'yǐng xiǎng lì',
                'simplified' => '影响力',
                'traditional' => '影響力',
                'part_of_speech' => 'noun',
                'meaning' => 'Influence / Impact',
                'meaning_zh' => '影响力',
                'example_sentence' => '他很有影响力。',
                'example_translation' => 'He has great influence.',
                'definition' => 'Influence, impact, clout',
                'sentences' => ['___大。', '___提升。', '___扩大。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '关注',
                'pinyin' => 'guān zhù',
                'simplified' => '关注',
                'traditional' => '關注',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To follow / To pay attention to',
                'meaning_zh' => '关注',
                'example_sentence' => '请关注我的账号。',
                'example_translation' => 'Please follow my account.',
                'definition' => 'To follow, to pay attention to, attention',
                'sentences' => ['___度。', '___焦点。', '___热点。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '评论',
                'pinyin' => 'píng lùn',
                'simplified' => '评论',
                'traditional' => '評論',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Comment / To comment',
                'meaning_zh' => '评论',
                'example_sentence' => '大家都在评论这件事。',
                'example_translation' => 'Everyone is commenting on this matter.',
                'definition' => 'Comment, to comment, review',
                'sentences' => ['___区。', '___文章。', '___家。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '互动',
                'pinyin' => 'hù dòng',
                'simplified' => '互动',
                'traditional' => '互動',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Interaction / To interact',
                'meaning_zh' => '互动',
                'example_sentence' => '要加强互动交流。',
                'example_translation' => 'Need to strengthen interactive communication.',
                'definition' => 'Interaction, to interact',
                'sentences' => ['___交流。', '___性。', '___环节。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '热搜',
                'pinyin' => 'rè sōu',
                'simplified' => '热搜',
                'traditional' => '熱搜',
                'part_of_speech' => 'noun',
                'meaning' => 'Trending / Hot search',
                'meaning_zh' => '热搜',
                'example_sentence' => '这个话题上了热搜。',
                'example_translation' => 'This topic is trending.',
                'definition' => 'Trending topic, hot search',
                'sentences' => ['___榜。', '上___。', '___第一。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '舆论',
                'pinyin' => 'yú lùn',
                'simplified' => '舆论',
                'traditional' => '輿論',
                'part_of_speech' => 'noun',
                'meaning' => 'Public opinion',
                'meaning_zh' => '舆论',
                'example_sentence' => '要关注舆论导向。',
                'example_translation' => 'Need to pay attention to public opinion guidance.',
                'definition' => 'Public opinion, public sentiment',
                'sentences' => ['___压力。', '___导向。', '___监督。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '隐私',
                'pinyin' => 'yǐn sī',
                'simplified' => '隐私',
                'traditional' => '隱私',
                'part_of_speech' => 'noun',
                'meaning' => 'Privacy',
                'meaning_zh' => '隐私',
                'example_sentence' => '要保护个人隐私。',
                'example_translation' => 'Need to protect personal privacy.',
                'definition' => 'Privacy, private matters',
                'sentences' => ['___保护。', '___权。', '___泄露。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '谣言',
                'pinyin' => 'yáo yán',
                'simplified' => '谣言',
                'traditional' => '謠言',
                'part_of_speech' => 'noun',
                'meaning' => 'Rumor',
                'meaning_zh' => '谣言',
                'example_sentence' => '不要相信谣言。',
                'example_translation' => 'Don\'t believe rumors.',
                'definition' => 'Rumor, hearsay',
                'sentences' => ['___传播。', '___止于智者。', '___澄清。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 142,
                'word' => '真相',
                'pinyin' => 'zhēn xiàng',
                'simplified' => '真相',
                'traditional' => '真相',
                'part_of_speech' => 'noun',
                'meaning' => 'Truth / The facts',
                'meaning_zh' => '真相',
                'example_sentence' => '要查明真相。',
                'example_translation' => 'Need to find out the truth.',
                'definition' => 'Truth, the facts, reality',
                'sentences' => ['___大白。', '___调查。', '___公布。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 143: Policy and Law - 政策与法律
        $lawVocab = [
            [
                'topic_id' => 143,
                'word' => '政策',
                'pinyin' => 'zhèng cè',
                'simplified' => '政策',
                'traditional' => '政策',
                'part_of_speech' => 'noun',
                'meaning' => 'Policy',
                'meaning_zh' => '政策',
                'example_sentence' => '国家出台了新政策。',
                'example_translation' => 'The country introduced new policies.',
                'definition' => 'Policy, guideline',
                'sentences' => ['___制定。', '___实施。', '___调整。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '法律',
                'pinyin' => 'fǎ lǜ',
                'simplified' => '法律',
                'traditional' => '法律',
                'part_of_speech' => 'noun',
                'meaning' => 'Law',
                'meaning_zh' => '法律',
                'example_sentence' => '要遵守法律。',
                'example_translation' => 'Need to abide by the law.',
                'definition' => 'Law, legislation',
                'sentences' => ['___规定。', '___制度。', '___意识。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '法规',
                'pinyin' => 'fǎ guī',
                'simplified' => '法规',
                'traditional' => '法規',
                'part_of_speech' => 'noun',
                'meaning' => 'Laws and regulations',
                'meaning_zh' => '法规',
                'example_sentence' => '要遵守法规。',
                'example_translation' => 'Need to comply with laws and regulations.',
                'definition' => 'Laws and regulations, statutes',
                'sentences' => ['___制度。', '___执行。', '___完善。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '规定',
                'pinyin' => 'guī dìng',
                'simplified' => '规定',
                'traditional' => '規定',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Regulation / To stipulate',
                'meaning_zh' => '规定',
                'example_sentence' => '按照规定办事。',
                'example_translation' => 'Act according to regulations.',
                'definition' => 'Regulation, to stipulate, to specify',
                'sentences' => ['___明确。', '___执行。', '___要求。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '制度',
                'pinyin' => 'zhì dù',
                'simplified' => '制度',
                'traditional' => '制度',
                'part_of_speech' => 'noun',
                'meaning' => 'System / Institution',
                'meaning_zh' => '制度',
                'example_sentence' => '要完善制度。',
                'example_translation' => 'Need to improve the system.',
                'definition' => 'System, institution, regime',
                'sentences' => ['___建设。', '___改革。', '___完善。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '权利',
                'pinyin' => 'quán lì',
                'simplified' => '权利',
                'traditional' => '權利',
                'part_of_speech' => 'noun',
                'meaning' => 'Right / Privilege',
                'meaning_zh' => '权利',
                'example_sentence' => '每个人都有权利。',
                'example_translation' => 'Everyone has rights.',
                'definition' => 'Right, privilege, entitlement',
                'sentences' => ['___义务。', '___保护。', '___平等。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '义务',
                'pinyin' => 'yì wù',
                'simplified' => '义务',
                'traditional' => '義務',
                'part_of_speech' => 'noun',
                'meaning' => 'Duty / Obligation',
                'meaning_zh' => '义务',
                'example_sentence' => '公民有义务纳税。',
                'example_translation' => 'Citizens have the obligation to pay taxes.',
                'definition' => 'Duty, obligation, compulsory',
                'sentences' => ['___教育。', '___履行。', '___责任。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '合法',
                'pinyin' => 'hé fǎ',
                'simplified' => '合法',
                'traditional' => '合法',
                'part_of_speech' => 'adjective',
                'meaning' => 'Legal / Lawful',
                'meaning_zh' => '合法',
                'example_sentence' => '这是合法的。',
                'example_translation' => 'This is legal.',
                'definition' => 'Legal, lawful, legitimate',
                'sentences' => ['___权益。', '___性。', '___经营。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '违法',
                'pinyin' => 'wéi fǎ',
                'simplified' => '违法',
                'traditional' => '違法',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'Illegal / To break the law',
                'meaning_zh' => '违法',
                'example_sentence' => '违法行为要受到惩罚。',
                'example_translation' => 'Illegal acts must be punished.',
                'definition' => 'Illegal, to break the law, unlawful',
                'sentences' => ['___行为。', '___犯罪。', '___活动。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '遵守',
                'pinyin' => 'zūn shǒu',
                'simplified' => '遵守',
                'traditional' => '遵守',
                'part_of_speech' => 'verb',
                'meaning' => 'To abide by / To comply with',
                'meaning_zh' => '遵守',
                'example_sentence' => '要遵守规则。',
                'example_translation' => 'Need to abide by the rules.',
                'definition' => 'To abide by, to comply with, to observe',
                'sentences' => ['___法律。', '___纪律。', '___承诺。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '执行',
                'pinyin' => 'zhí xíng',
                'simplified' => '执行',
                'traditional' => '執行',
                'part_of_speech' => 'verb',
                'meaning' => 'To execute / To implement',
                'meaning_zh' => '执行',
                'example_sentence' => '要认真执行政策。',
                'example_translation' => 'Need to implement policies seriously.',
                'definition' => 'To execute, to implement, to carry out',
                'sentences' => ['___任务。', '___命令。', '___力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '监督',
                'pinyin' => 'jiān dū',
                'simplified' => '监督',
                'traditional' => '監督',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To supervise / Supervision',
                'meaning_zh' => '监督',
                'example_sentence' => '需要加强监督。',
                'example_translation' => 'Need to strengthen supervision.',
                'definition' => 'To supervise, supervision, to oversee',
                'sentences' => ['___管理。', '___机制。', '___检查。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '惩罚',
                'pinyin' => 'chéng fá',
                'simplified' => '惩罚',
                'traditional' => '懲罰',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Punishment / To punish',
                'meaning_zh' => '惩罚',
                'example_sentence' => '违法要受到惩罚。',
                'example_translation' => 'Breaking the law must be punished.',
                'definition' => 'Punishment, to punish, penalty',
                'sentences' => ['___措施。', '___制度。', '___严厉。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '罚款',
                'pinyin' => 'fá kuǎn',
                'simplified' => '罚款',
                'traditional' => '罰款',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Fine / To fine',
                'meaning_zh' => '罚款',
                'example_sentence' => '违章停车要罚款。',
                'example_translation' => 'Illegal parking will be fined.',
                'definition' => 'Fine, to fine, penalty',
                'sentences' => ['___处罚。', '___金额。', '___通知。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '诉讼',
                'pinyin' => 'sù sòng',
                'simplified' => '诉讼',
                'traditional' => '訴訟',
                'part_of_speech' => 'noun',
                'meaning' => 'Lawsuit / Litigation',
                'meaning_zh' => '诉讼',
                'example_sentence' => '他提起了诉讼。',
                'example_translation' => 'He filed a lawsuit.',
                'definition' => 'Lawsuit, litigation, legal proceedings',
                'sentences' => ['___程序。', '___案件。', '___费用。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '律师',
                'pinyin' => 'lǜ shī',
                'simplified' => '律师',
                'traditional' => '律師',
                'part_of_speech' => 'noun',
                'meaning' => 'Lawyer / Attorney',
                'meaning_zh' => '律师',
                'example_sentence' => '我需要咨询律师。',
                'example_translation' => 'I need to consult a lawyer.',
                'definition' => 'Lawyer, attorney, solicitor',
                'sentences' => ['___事务所。', '___咨询。', '___费。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '法院',
                'pinyin' => 'fǎ yuàn',
                'simplified' => '法院',
                'traditional' => '法院',
                'part_of_speech' => 'noun',
                'meaning' => 'Court / Courthouse',
                'meaning_zh' => '法院',
                'example_sentence' => '案件在法院审理。',
                'example_translation' => 'The case is being tried in court.',
                'definition' => 'Court, courthouse, tribunal',
                'sentences' => ['___判决。', '___审理。', '___起诉。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '判决',
                'pinyin' => 'pàn jué',
                'simplified' => '判决',
                'traditional' => '判決',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Judgment / To judge',
                'meaning_zh' => '判决',
                'example_sentence' => '法院做出了判决。',
                'example_translation' => 'The court made a judgment.',
                'definition' => 'Judgment, verdict, to judge',
                'sentences' => ['___结果。', '___书。', '___公正。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '公正',
                'pinyin' => 'gōng zhèng',
                'simplified' => '公正',
                'traditional' => '公正',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fair / Just',
                'meaning_zh' => '公正',
                'example_sentence' => '要公正对待每个人。',
                'example_translation' => 'Need to treat everyone fairly.',
                'definition' => 'Fair, just, impartial',
                'sentences' => ['___公平。', '___处理。', '___执法。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 143,
                'word' => '维权',
                'pinyin' => 'wéi quán',
                'simplified' => '维权',
                'traditional' => '維權',
                'part_of_speech' => 'verb',
                'meaning' => 'To defend one\'s rights',
                'meaning_zh' => '维权',
                'example_sentence' => '消费者要学会维权。',
                'example_translation' => 'Consumers need to learn to defend their rights.',
                'definition' => 'To defend rights, to safeguard rights',
                'sentences' => ['___意识。', '___行动。', '___渠道。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 144: Nutrition, Exercise, and Rest - 营养运动休息
        $healthVocab = [
            [
                'topic_id' => 144,
                'word' => '营养',
                'pinyin' => 'yíng yǎng',
                'simplified' => '营养',
                'traditional' => '營養',
                'part_of_speech' => 'noun',
                'meaning' => 'Nutrition / Nourishment',
                'meaning_zh' => '营养',
                'example_sentence' => '要注意营养均衡。',
                'example_translation' => 'Need to pay attention to balanced nutrition.',
                'definition' => 'Nutrition, nourishment, nutrients',
                'sentences' => ['___丰富。', '___价值。', '___补充。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '饮食',
                'pinyin' => 'yǐn shí',
                'simplified' => '饮食',
                'traditional' => '飲食',
                'part_of_speech' => 'noun',
                'meaning' => 'Diet / Food and drink',
                'meaning_zh' => '饮食',
                'example_sentence' => '要注意饮食健康。',
                'example_translation' => 'Need to pay attention to dietary health.',
                'definition' => 'Diet, food and drink, eating habits',
                'sentences' => ['___习惯。', '___结构。', '___调理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '均衡',
                'pinyin' => 'jūn héng',
                'simplified' => '均衡',
                'traditional' => '均衡',
                'part_of_speech' => 'adjective',
                'meaning' => 'Balanced / Equilibrium',
                'meaning_zh' => '均衡',
                'example_sentence' => '营养要均衡。',
                'example_translation' => 'Nutrition should be balanced.',
                'definition' => 'Balanced, equilibrium, well-proportioned',
                'sentences' => ['___发展。', '___膳食。', '___配置。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '维生素',
                'pinyin' => 'wéi shēng sù',
                'simplified' => '维生素',
                'traditional' => '維生素',
                'part_of_speech' => 'noun',
                'meaning' => 'Vitamin',
                'meaning_zh' => '维生素',
                'example_sentence' => '要补充维生素。',
                'example_translation' => 'Need to supplement vitamins.',
                'definition' => 'Vitamin',
                'sentences' => ['___C。', '___补充。', '___缺乏。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '蛋白质',
                'pinyin' => 'dàn bái zhì',
                'simplified' => '蛋白质',
                'traditional' => '蛋白質',
                'part_of_speech' => 'noun',
                'meaning' => 'Protein',
                'meaning_zh' => '蛋白质',
                'example_sentence' => '蛋白质很重要。',
                'example_translation' => 'Protein is very important.',
                'definition' => 'Protein',
                'sentences' => ['___摄入。', '___含量。', '___补充。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '锻炼',
                'pinyin' => 'duàn liàn',
                'simplified' => '锻炼',
                'traditional' => '鍛煉',
                'part_of_speech' => 'verb',
                'meaning' => 'To exercise / To work out',
                'meaning_zh' => '锻炼',
                'example_sentence' => '每天要锻炼身体。',
                'example_translation' => 'Need to exercise every day.',
                'definition' => 'To exercise, to work out, to train',
                'sentences' => ['___身体。', '___时间。', '___方式。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '运动',
                'pinyin' => 'yùn dòng',
                'simplified' => '运动',
                'traditional' => '運動',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Exercise / Sport / To exercise',
                'meaning_zh' => '运动',
                'example_sentence' => '运动有益健康。',
                'example_translation' => 'Exercise is beneficial to health.',
                'definition' => 'Exercise, sport, to exercise, movement',
                'sentences' => ['___量。', '___项目。', '___鞋。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '跑步',
                'pinyin' => 'pǎo bù',
                'simplified' => '跑步',
                'traditional' => '跑步',
                'part_of_speech' => 'verb',
                'meaning' => 'To run / Running',
                'meaning_zh' => '跑步',
                'example_sentence' => '我每天早上跑步。',
                'example_translation' => 'I run every morning.',
                'definition' => 'To run, running, jogging',
                'sentences' => ['___锻炼。', '___机。', '___爱好者。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '健身',
                'pinyin' => 'jiàn shēn',
                'simplified' => '健身',
                'traditional' => '健身',
                'part_of_speech' => 'verb',
                'meaning' => 'To work out / Fitness',
                'meaning_zh' => '健身',
                'example_sentence' => '我经常去健身房。',
                'example_translation' => 'I often go to the gym.',
                'definition' => 'To work out, fitness, bodybuilding',
                'sentences' => ['___房。', '___器材。', '___教练。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '瑜伽',
                'pinyin' => 'yú jiā',
                'simplified' => '瑜伽',
                'traditional' => '瑜伽',
                'part_of_speech' => 'noun',
                'meaning' => 'Yoga',
                'meaning_zh' => '瑜伽',
                'example_sentence' => '她每天练瑜伽。',
                'example_translation' => 'She practices yoga every day.',
                'definition' => 'Yoga',
                'sentences' => ['练___。', '___课。', '___垫。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '休息',
                'pinyin' => 'xiū xi',
                'simplified' => '休息',
                'traditional' => '休息',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To rest / Rest',
                'meaning_zh' => '休息',
                'example_sentence' => '累了要休息。',
                'example_translation' => 'Need to rest when tired.',
                'definition' => 'To rest, rest, break',
                'sentences' => ['___时间。', '___一下。', '___日。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '睡眠',
                'pinyin' => 'shuì mián',
                'simplified' => '睡眠',
                'traditional' => '睡眠',
                'part_of_speech' => 'noun',
                'meaning' => 'Sleep',
                'meaning_zh' => '睡眠',
                'example_sentence' => '睡眠很重要。',
                'example_translation' => 'Sleep is very important.',
                'definition' => 'Sleep, slumber',
                'sentences' => ['___质量。', '___时间。', '___不足。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '作息',
                'pinyin' => 'zuò xī',
                'simplified' => '作息',
                'traditional' => '作息',
                'part_of_speech' => 'noun',
                'meaning' => 'Work and rest schedule',
                'meaning_zh' => '作息',
                'example_sentence' => '要规律作息。',
                'example_translation' => 'Need to have a regular schedule.',
                'definition' => 'Work and rest schedule, daily routine',
                'sentences' => ['___时间。', '___规律。', '___表。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '熬夜',
                'pinyin' => 'áo yè',
                'simplified' => '熬夜',
                'traditional' => '熬夜',
                'part_of_speech' => 'verb',
                'meaning' => 'To stay up late',
                'meaning_zh' => '熬夜',
                'example_sentence' => '不要经常熬夜。',
                'example_translation' => 'Don\'t stay up late often.',
                'definition' => 'To stay up late, to burn the midnight oil',
                'sentences' => ['___工作。', '___伤身。', '___加班。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '疲劳',
                'pinyin' => 'pí láo',
                'simplified' => '疲劳',
                'traditional' => '疲勞',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Tired / Fatigue',
                'meaning_zh' => '疲劳',
                'example_sentence' => '感到很疲劳。',
                'example_translation' => 'Feel very tired.',
                'definition' => 'Tired, fatigue, exhaustion',
                'sentences' => ['___驾驶。', '___过度。', '___感。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '精力',
                'pinyin' => 'jīng lì',
                'simplified' => '精力',
                'traditional' => '精力',
                'part_of_speech' => 'noun',
                'meaning' => 'Energy / Vigor',
                'meaning_zh' => '精力',
                'example_sentence' => '他精力充沛。',
                'example_translation' => 'He is full of energy.',
                'definition' => 'Energy, vigor, vitality',
                'sentences' => ['___充沛。', '___旺盛。', '___集中。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '体力',
                'pinyin' => 'tǐ lì',
                'simplified' => '体力',
                'traditional' => '體力',
                'part_of_speech' => 'noun',
                'meaning' => 'Physical strength / Stamina',
                'meaning_zh' => '体力',
                'example_sentence' => '体力劳动很累。',
                'example_translation' => 'Physical labor is very tiring.',
                'definition' => 'Physical strength, stamina, physical power',
                'sentences' => ['___劳动。', '___消耗。', '___恢复。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '体重',
                'pinyin' => 'tǐ zhòng',
                'simplified' => '体重',
                'traditional' => '體重',
                'part_of_speech' => 'noun',
                'meaning' => 'Body weight',
                'meaning_zh' => '体重',
                'example_sentence' => '要控制体重。',
                'example_translation' => 'Need to control body weight.',
                'definition' => 'Body weight, weight',
                'sentences' => ['___增加。', '___下降。', '___管理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '减肥',
                'pinyin' => 'jiǎn féi',
                'simplified' => '减肥',
                'traditional' => '減肥',
                'part_of_speech' => 'verb',
                'meaning' => 'To lose weight',
                'meaning_zh' => '减肥',
                'example_sentence' => '她正在减肥。',
                'example_translation' => 'She is losing weight.',
                'definition' => 'To lose weight, to slim down',
                'sentences' => ['___方法。', '___计划。', '___成功。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 144,
                'word' => '保健',
                'pinyin' => 'bǎo jiàn',
                'simplified' => '保健',
                'traditional' => '保健',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Health care / To maintain health',
                'meaning_zh' => '保健',
                'example_sentence' => '要注意保健。',
                'example_translation' => 'Need to pay attention to health care.',
                'definition' => 'Health care, to maintain health',
                'sentences' => ['___品。', '___知识。', '___养生。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 145: Mental Health - 心理健康
        $mentalHealthVocab = [
            [
                'topic_id' => 145,
                'word' => '心理',
                'pinyin' => 'xīn lǐ',
                'simplified' => '心理',
                'traditional' => '心理',
                'part_of_speech' => 'noun',
                'meaning' => 'Psychology / Mental',
                'meaning_zh' => '心理',
                'example_sentence' => '要注意心理健康。',
                'example_translation' => 'Need to pay attention to mental health.',
                'definition' => 'Psychology, mental, psychological',
                'sentences' => ['___健康。', '___压力。', '___咨询。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '情绪',
                'pinyin' => 'qíng xù',
                'simplified' => '情绪',
                'traditional' => '情緒',
                'part_of_speech' => 'noun',
                'meaning' => 'Emotion / Mood',
                'meaning_zh' => '情绪',
                'example_sentence' => '要控制情绪。',
                'example_translation' => 'Need to control emotions.',
                'definition' => 'Emotion, mood, feeling',
                'sentences' => ['___管理。', '___波动。', '___稳定。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '心情',
                'pinyin' => 'xīn qíng',
                'simplified' => '心情',
                'traditional' => '心情',
                'part_of_speech' => 'noun',
                'meaning' => 'Mood / Frame of mind',
                'meaning_zh' => '心情',
                'example_sentence' => '今天心情很好。',
                'example_translation' => 'I\'m in a good mood today.',
                'definition' => 'Mood, frame of mind, state of mind',
                'sentences' => ['___愉快。', '___不好。', '___放松。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '焦虑',
                'pinyin' => 'jiāo lǜ',
                'simplified' => '焦虑',
                'traditional' => '焦慮',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Anxious / Anxiety',
                'meaning_zh' => '焦虑',
                'example_sentence' => '不要太焦虑。',
                'example_translation' => 'Don\'t be too anxious.',
                'definition' => 'Anxious, anxiety, worried',
                'sentences' => ['___情绪。', '___症。', '___不安。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '抑郁',
                'pinyin' => 'yì yù',
                'simplified' => '抑郁',
                'traditional' => '抑鬱',
                'part_of_speech' => 'adjective',
                'meaning' => 'Depressed / Depression',
                'meaning_zh' => '抑郁',
                'example_sentence' => '他有点抑郁。',
                'example_translation' => 'He is a bit depressed.',
                'definition' => 'Depressed, depression, melancholy',
                'sentences' => ['___症。', '___情绪。', '___状态。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '乐观',
                'pinyin' => 'lè guān',
                'simplified' => '乐观',
                'traditional' => '樂觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Optimistic',
                'meaning_zh' => '乐观',
                'example_sentence' => '要保持乐观态度。',
                'example_translation' => 'Need to maintain an optimistic attitude.',
                'definition' => 'Optimistic, positive',
                'sentences' => ['___向上。', '___心态。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '悲观',
                'pinyin' => 'bēi guān',
                'simplified' => '悲观',
                'traditional' => '悲觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Pessimistic',
                'meaning_zh' => '悲观',
                'example_sentence' => '不要太悲观。',
                'example_translation' => 'Don\'t be too pessimistic.',
                'definition' => 'Pessimistic, negative',
                'sentences' => ['___情绪。', '___态度。', '___主义。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '心态',
                'pinyin' => 'xīn tài',
                'simplified' => '心态',
                'traditional' => '心態',
                'part_of_speech' => 'noun',
                'meaning' => 'Mentality / State of mind',
                'meaning_zh' => '心态',
                'example_sentence' => '要调整心态。',
                'example_translation' => 'Need to adjust one\'s mentality.',
                'definition' => 'Mentality, state of mind, mindset',
                'sentences' => ['___平和。', '___积极。', '___调整。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '幸福感',
                'pinyin' => 'xìng fú gǎn',
                'simplified' => '幸福感',
                'traditional' => '幸福感',
                'part_of_speech' => 'noun',
                'meaning' => 'Sense of happiness',
                'meaning_zh' => '幸福感',
                'example_sentence' => '要提高幸福感。',
                'example_translation' => 'Need to increase the sense of happiness.',
                'definition' => 'Sense of happiness, feeling of well-being',
                'sentences' => ['___提升。', '___强。', '___指数。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '满足感',
                'pinyin' => 'mǎn zú gǎn',
                'simplified' => '满足感',
                'traditional' => '滿足感',
                'part_of_speech' => 'noun',
                'meaning' => 'Sense of satisfaction',
                'meaning_zh' => '满足感',
                'example_sentence' => '工作给我满足感。',
                'example_translation' => 'Work gives me a sense of satisfaction.',
                'definition' => 'Sense of satisfaction, fulfillment',
                'sentences' => ['___强。', '___获得。', '___缺乏。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '自信',
                'pinyin' => 'zì xìn',
                'simplified' => '自信',
                'traditional' => '自信',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Self-confident / Confidence',
                'meaning_zh' => '自信',
                'example_sentence' => '要有自信。',
                'example_translation' => 'Need to have confidence.',
                'definition' => 'Self-confident, confidence, self-assurance',
                'sentences' => ['___心。', '___满满。', '___建立。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '自卑',
                'pinyin' => 'zì bēi',
                'simplified' => '自卑',
                'traditional' => '自卑',
                'part_of_speech' => 'adjective',
                'meaning' => 'Inferior / Inferiority',
                'meaning_zh' => '自卑',
                'example_sentence' => '不要自卑。',
                'example_translation' => 'Don\'t feel inferior.',
                'definition' => 'Inferior, inferiority complex',
                'sentences' => ['___感。', '___心理。', '___情绪。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '孤独',
                'pinyin' => 'gū dú',
                'simplified' => '孤独',
                'traditional' => '孤獨',
                'part_of_speech' => 'adjective',
                'meaning' => 'Lonely / Loneliness',
                'meaning_zh' => '孤独',
                'example_sentence' => '他感到很孤独。',
                'example_translation' => 'He feels very lonely.',
                'definition' => 'Lonely, loneliness, solitary',
                'sentences' => ['___感。', '___寂寞。', '___的人。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '放松',
                'pinyin' => 'fàng sōng',
                'simplified' => '放松',
                'traditional' => '放鬆',
                'part_of_speech' => 'verb',
                'meaning' => 'To relax',
                'meaning_zh' => '放松',
                'example_sentence' => '要学会放松。',
                'example_translation' => 'Need to learn to relax.',
                'definition' => 'To relax, to loosen up',
                'sentences' => ['___心情。', '___一下。', '___身心。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '缓解',
                'pinyin' => 'huǎn jiě',
                'simplified' => '缓解',
                'traditional' => '緩解',
                'part_of_speech' => 'verb',
                'meaning' => 'To relieve / To ease',
                'meaning_zh' => '缓解',
                'example_sentence' => '要缓解压力。',
                'example_translation' => 'Need to relieve stress.',
                'definition' => 'To relieve, to ease, to alleviate',
                'sentences' => ['___压力。', '___症状。', '___矛盾。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '调节',
                'pinyin' => 'tiáo jié',
                'simplified' => '调节',
                'traditional' => '調節',
                'part_of_speech' => 'verb',
                'meaning' => 'To regulate / To adjust',
                'meaning_zh' => '调节',
                'example_sentence' => '要调节情绪。',
                'example_translation' => 'Need to regulate emotions.',
                'definition' => 'To regulate, to adjust, to moderate',
                'sentences' => ['___心理。', '___能力。', '___作用。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '倾诉',
                'pinyin' => 'qīng sù',
                'simplified' => '倾诉',
                'traditional' => '傾訴',
                'part_of_speech' => 'verb',
                'meaning' => 'To pour out / To confide',
                'meaning_zh' => '倾诉',
                'example_sentence' => '需要有人倾诉。',
                'example_translation' => 'Need someone to confide in.',
                'definition' => 'To pour out, to confide, to unburden',
                'sentences' => ['___烦恼。', '___对象。', '___心声。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '沟通',
                'pinyin' => 'gōu tōng',
                'simplified' => '沟通',
                'traditional' => '溝通',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To communicate / Communication',
                'meaning_zh' => '沟通',
                'example_sentence' => '要多沟通交流。',
                'example_translation' => 'Need to communicate more.',
                'definition' => 'To communicate, communication',
                'sentences' => ['___技巧。', '___能力。', '___障碍。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To understand / Understanding',
                'meaning_zh' => '理解',
                'example_sentence' => '需要相互理解。',
                'example_translation' => 'Need mutual understanding.',
                'definition' => 'To understand, understanding, comprehension',
                'sentences' => ['___能力。', '___支持。', '___包容。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 145,
                'word' => '陪伴',
                'pinyin' => 'péi bàn',
                'simplified' => '陪伴',
                'traditional' => '陪伴',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To accompany / Companionship',
                'meaning_zh' => '陪伴',
                'example_sentence' => '家人的陪伴很重要。',
                'example_translation' => 'Family companionship is very important.',
                'definition' => 'To accompany, companionship, to keep company',
                'sentences' => ['___成长。', '___家人。', '___关爱。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($mediaVocab, $lawVocab, $healthVocab, $mentalHealthVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
