<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic153to154Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [153, 154])->delete();

        // Topic 153: Failure and Learning - 失败与学习
        $failureVocab = [
            [
                'topic_id' => 153,
                'word' => '失败',
                'pinyin' => 'shī bài',
                'simplified' => '失败',
                'traditional' => '失敗',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To fail / Failure',
                'meaning_zh' => '失败',
                'example_sentence' => '不怕失败。',
                'example_translation' => 'Not afraid of failure.',
                'definition' => 'To fail, failure, to be defeated',
                'sentences' => ['___经历。', '___原因。', '___教训。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '挫折',
                'pinyin' => 'cuò zhé',
                'simplified' => '挫折',
                'traditional' => '挫折',
                'part_of_speech' => 'noun',
                'meaning' => 'Setback / Frustration',
                'meaning_zh' => '挫折',
                'example_sentence' => '遇到挫折。',
                'example_translation' => 'Encounter setbacks.',
                'definition' => 'Setback, frustration, defeat',
                'sentences' => ['___教育。', '___面对。', '___克服。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '困难',
                'pinyin' => 'kùn nan',
                'simplified' => '困难',
                'traditional' => '困難',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Difficulty / Difficult',
                'meaning_zh' => '困难',
                'example_sentence' => '克服困难。',
                'example_translation' => 'Overcome difficulties.',
                'definition' => 'Difficulty, difficult, hardship',
                'sentences' => ['___重重。', '___解决。', '___时期。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '挑战',
                'pinyin' => 'tiǎo zhàn',
                'simplified' => '挑战',
                'traditional' => '挑戰',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Challenge / To challenge',
                'meaning_zh' => '挑战',
                'example_sentence' => '接受挑战。',
                'example_translation' => 'Accept the challenge.',
                'definition' => 'Challenge, to challenge',
                'sentences' => ['___自我。', '___性。', '___面对。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '错误',
                'pinyin' => 'cuò wù',
                'simplified' => '错误',
                'traditional' => '錯誤',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Mistake / Wrong',
                'meaning_zh' => '错误',
                'example_sentence' => '犯了错误。',
                'example_translation' => 'Made a mistake.',
                'definition' => 'Mistake, error, wrong',
                'sentences' => ['___纠正。', '___认识。', '___承认。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '教训',
                'pinyin' => 'jiào xun',
                'simplified' => '教训',
                'traditional' => '教訓',
                'part_of_speech' => 'noun',
                'meaning' => 'Lesson / Moral',
                'meaning_zh' => '教训',
                'example_sentence' => '吸取教训。',
                'example_translation' => 'Learn a lesson.',
                'definition' => 'Lesson, moral, to teach someone a lesson',
                'sentences' => ['___深刻。', '___总结。', '___记住。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '经验',
                'pinyin' => 'jīng yàn',
                'simplified' => '经验',
                'traditional' => '經驗',
                'part_of_speech' => 'noun',
                'meaning' => 'Experience',
                'meaning_zh' => '经验',
                'example_sentence' => '积累经验。',
                'example_translation' => 'Accumulate experience.',
                'definition' => 'Experience, to experience',
                'sentences' => ['___丰富。', '___分享。', '___总结。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '反思',
                'pinyin' => 'fǎn sī',
                'simplified' => '反思',
                'traditional' => '反思',
                'part_of_speech' => 'verb',
                'meaning' => 'To reflect / To introspect',
                'meaning_zh' => '反思',
                'example_sentence' => '需要反思。',
                'example_translation' => 'Need to reflect.',
                'definition' => 'To reflect, to introspect, reflection',
                'sentences' => ['___自己。', '___总结。', '___深刻。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '总结',
                'pinyin' => 'zǒng jié',
                'simplified' => '总结',
                'traditional' => '總結',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To summarize / Summary',
                'meaning_zh' => '总结',
                'example_sentence' => '总结经验。',
                'example_translation' => 'Summarize experience.',
                'definition' => 'To summarize, summary, to sum up',
                'sentences' => ['___工作。', '___报告。', '___反思。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '改进',
                'pinyin' => 'gǎi jìn',
                'simplified' => '改进',
                'traditional' => '改進',
                'part_of_speech' => 'verb',
                'meaning' => 'To improve / To better',
                'meaning_zh' => '改进',
                'example_sentence' => '不断改进。',
                'example_translation' => 'Continuously improve.',
                'definition' => 'To improve, to better, improvement',
                'sentences' => ['___方法。', '___措施。', '___工作。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '完善',
                'pinyin' => 'wán shàn',
                'simplified' => '完善',
                'traditional' => '完善',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To perfect / Perfect',
                'meaning_zh' => '完善',
                'example_sentence' => '不断完善。',
                'example_translation' => 'Continuously perfect.',
                'definition' => 'To perfect, perfect, to improve',
                'sentences' => ['___制度。', '___自己。', '___体系。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '重新开始',
                'pinyin' => 'chóng xīn kāi shǐ',
                'simplified' => '重新开始',
                'traditional' => '重新開始',
                'part_of_speech' => 'verb phrase',
                'meaning' => 'To start over / To begin again',
                'meaning_zh' => '重新开始',
                'example_sentence' => '可以重新开始。',
                'example_translation' => 'Can start over.',
                'definition' => 'To start over, to begin again',
                'sentences' => ['___生活。', '___努力。', '___机会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '克服',
                'pinyin' => 'kè fú',
                'simplified' => '克服',
                'traditional' => '克服',
                'part_of_speech' => 'verb',
                'meaning' => 'To overcome / To conquer',
                'meaning_zh' => '克服',
                'example_sentence' => '克服困难。',
                'example_translation' => 'Overcome difficulties.',
                'definition' => 'To overcome, to conquer, to surmount',
                'sentences' => ['___障碍。', '___恐惧。', '___弱点。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '坚强',
                'pinyin' => 'jiān qiáng',
                'simplified' => '坚强',
                'traditional' => '堅強',
                'part_of_speech' => 'adjective',
                'meaning' => 'Strong / Firm',
                'meaning_zh' => '坚强',
                'example_sentence' => '要坚强。',
                'example_translation' => 'Need to be strong.',
                'definition' => 'Strong, firm, resilient',
                'sentences' => ['___意志。', '___勇敢。', '___面对。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '韧性',
                'pinyin' => 'rèn xìng',
                'simplified' => '韧性',
                'traditional' => '韌性',
                'part_of_speech' => 'noun',
                'meaning' => 'Resilience / Toughness',
                'meaning_zh' => '韧性',
                'example_sentence' => '培养韧性。',
                'example_translation' => 'Cultivate resilience.',
                'definition' => 'Resilience, toughness, tenacity',
                'sentences' => ['___强。', '___不足。', '___锻炼。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '承受',
                'pinyin' => 'chéng shòu',
                'simplified' => '承受',
                'traditional' => '承受',
                'part_of_speech' => 'verb',
                'meaning' => 'To bear / To endure',
                'meaning_zh' => '承受',
                'example_sentence' => '承受压力。',
                'example_translation' => 'Bear pressure.',
                'definition' => 'To bear, to endure, to withstand',
                'sentences' => ['___能力。', '___痛苦。', '___打击。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '磨练',
                'pinyin' => 'mó liàn',
                'simplified' => '磨练',
                'traditional' => '磨練',
                'part_of_speech' => 'verb',
                'meaning' => 'To temper / To toughen',
                'meaning_zh' => '磨练',
                'example_sentence' => '磨练意志。',
                'example_translation' => 'Temper one\'s will.',
                'definition' => 'To temper, to toughen, to steel',
                'sentences' => ['___自己。', '___机会。', '___过程。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '积累',
                'pinyin' => 'jī lěi',
                'simplified' => '积累',
                'traditional' => '積累',
                'part_of_speech' => 'verb',
                'meaning' => 'To accumulate / To amass',
                'meaning_zh' => '积累',
                'example_sentence' => '积累经验。',
                'example_translation' => 'Accumulate experience.',
                'definition' => 'To accumulate, to amass, accumulation',
                'sentences' => ['___知识。', '___财富。', '___过程。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '启发',
                'pinyin' => 'qǐ fā',
                'simplified' => '启发',
                'traditional' => '啟發',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To inspire / Inspiration',
                'meaning_zh' => '启发',
                'example_sentence' => '得到启发。',
                'example_translation' => 'Get inspiration.',
                'definition' => 'To inspire, inspiration, enlightenment',
                'sentences' => ['___思考。', '___意义。', '___教育。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 153,
                'word' => '成熟',
                'pinyin' => 'chéng shú',
                'simplified' => '成熟',
                'traditional' => '成熟',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Mature / To mature',
                'meaning_zh' => '成熟',
                'example_sentence' => '变得成熟。',
                'example_translation' => 'Become mature.',
                'definition' => 'Mature, to mature, ripe',
                'sentences' => ['___稳重。', '___思考。', '___表现。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 154: Life Outlook and Values - 人生观与价值观
        $valuesVocab = [
            [
                'topic_id' => 154,
                'word' => '人生',
                'pinyin' => 'rén shēng',
                'simplified' => '人生',
                'traditional' => '人生',
                'part_of_speech' => 'noun',
                'meaning' => 'Life / Human life',
                'meaning_zh' => '人生',
                'example_sentence' => '人生很精彩。',
                'example_translation' => 'Life is wonderful.',
                'definition' => 'Life, human life, lifetime',
                'sentences' => ['___道路。', '___经历。', '___哲理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '价值',
                'pinyin' => 'jià zhí',
                'simplified' => '价值',
                'traditional' => '價值',
                'part_of_speech' => 'noun',
                'meaning' => 'Value / Worth',
                'meaning_zh' => '价值',
                'example_sentence' => '实现价值。',
                'example_translation' => 'Realize one\'s value.',
                'definition' => 'Value, worth',
                'sentences' => ['___观。', '___体现。', '___意义。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '价值观',
                'pinyin' => 'jià zhí guān',
                'simplified' => '价值观',
                'traditional' => '價值觀',
                'part_of_speech' => 'noun',
                'meaning' => 'Values / Value system',
                'meaning_zh' => '价值观',
                'example_sentence' => '树立正确的价值观。',
                'example_translation' => 'Establish correct values.',
                'definition' => 'Values, value system, worldview',
                'sentences' => ['___培养。', '___形成。', '___差异。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '人生观',
                'pinyin' => 'rén shēng guān',
                'simplified' => '人生观',
                'traditional' => '人生觀',
                'part_of_speech' => 'noun',
                'meaning' => 'Outlook on life / Life philosophy',
                'meaning_zh' => '人生观',
                'example_sentence' => '积极的人生观。',
                'example_translation' => 'Positive outlook on life.',
                'definition' => 'Outlook on life, life philosophy',
                'sentences' => ['___世界观。', '___形成。', '___树立。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '意义',
                'pinyin' => 'yì yì',
                'simplified' => '意义',
                'traditional' => '意義',
                'part_of_speech' => 'noun',
                'meaning' => 'Meaning / Significance',
                'meaning_zh' => '意义',
                'example_sentence' => '有意义的事。',
                'example_translation' => 'Meaningful thing.',
                'definition' => 'Meaning, significance, sense',
                'sentences' => ['___重大。', '___深刻。', '___何在。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '幸福',
                'pinyin' => 'xìng fú',
                'simplified' => '幸福',
                'traditional' => '幸福',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Happiness / Happy',
                'meaning_zh' => '幸福',
                'example_sentence' => '追求幸福。',
                'example_translation' => 'Pursue happiness.',
                'definition' => 'Happiness, happy, well-being',
                'sentences' => ['___生活。', '___家庭。', '___美满。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '快乐',
                'pinyin' => 'kuài lè',
                'simplified' => '快乐',
                'traditional' => '快樂',
                'part_of_speech' => 'adjective',
                'meaning' => 'Happy / Joyful',
                'meaning_zh' => '快乐',
                'example_sentence' => '保持快乐。',
                'example_translation' => 'Stay happy.',
                'definition' => 'Happy, joyful, cheerful',
                'sentences' => ['___成长。', '___生活。', '___心情。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '满足',
                'pinyin' => 'mǎn zú',
                'simplified' => '满足',
                'traditional' => '滿足',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To satisfy / Satisfied',
                'meaning_zh' => '满足',
                'example_sentence' => '感到满足。',
                'example_translation' => 'Feel satisfied.',
                'definition' => 'To satisfy, satisfied, content',
                'sentences' => ['___需求。', '___现状。', '___条件。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '感恩',
                'pinyin' => 'gǎn ēn',
                'simplified' => '感恩',
                'traditional' => '感恩',
                'part_of_speech' => 'verb',
                'meaning' => 'To be grateful / Gratitude',
                'meaning_zh' => '感恩',
                'example_sentence' => '学会感恩。',
                'example_translation' => 'Learn to be grateful.',
                'definition' => 'To be grateful, gratitude, to give thanks',
                'sentences' => ['___之心。', '___父母。', '___生活。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '善良',
                'pinyin' => 'shàn liáng',
                'simplified' => '善良',
                'traditional' => '善良',
                'part_of_speech' => 'adjective',
                'meaning' => 'Kind / Kind-hearted',
                'meaning_zh' => '善良',
                'example_sentence' => '保持善良。',
                'example_translation' => 'Stay kind.',
                'definition' => 'Kind, kind-hearted, good-natured',
                'sentences' => ['___的人。', '___纯真。', '___品质。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '正直',
                'pinyin' => 'zhèng zhí',
                'simplified' => '正直',
                'traditional' => '正直',
                'part_of_speech' => 'adjective',
                'meaning' => 'Upright / Honest',
                'meaning_zh' => '正直',
                'example_sentence' => '为人正直。',
                'example_translation' => 'Be an upright person.',
                'definition' => 'Upright, honest, righteous',
                'sentences' => ['___善良。', '___品格。', '___做人。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '诚信',
                'pinyin' => 'chéng xìn',
                'simplified' => '诚信',
                'traditional' => '誠信',
                'part_of_speech' => 'noun',
                'meaning' => 'Integrity / Honesty',
                'meaning_zh' => '诚信',
                'example_sentence' => '讲诚信。',
                'example_translation' => 'Have integrity.',
                'definition' => 'Integrity, honesty, credibility',
                'sentences' => ['___经营。', '___为本。', '___社会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '责任',
                'pinyin' => 'zé rèn',
                'simplified' => '责任',
                'traditional' => '責任',
                'part_of_speech' => 'noun',
                'meaning' => 'Responsibility / Duty',
                'meaning_zh' => '责任',
                'example_sentence' => '承担责任。',
                'example_translation' => 'Take responsibility.',
                'definition' => 'Responsibility, duty, obligation',
                'sentences' => ['___感。', '___心。', '___重大。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '奉献',
                'pinyin' => 'fèng xiàn',
                'simplified' => '奉献',
                'traditional' => '奉獻',
                'part_of_speech' => 'verb',
                'meaning' => 'To dedicate / To contribute',
                'meaning_zh' => '奉献',
                'example_sentence' => '无私奉献。',
                'example_translation' => 'Selfless dedication.',
                'definition' => 'To dedicate, to contribute, dedication',
                'sentences' => ['___精神。', '___社会。', '___爱心。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '贡献',
                'pinyin' => 'gòng xiàn',
                'simplified' => '贡献',
                'traditional' => '貢獻',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To contribute / Contribution',
                'meaning_zh' => '贡献',
                'example_sentence' => '做出贡献。',
                'example_translation' => 'Make a contribution.',
                'definition' => 'To contribute, contribution',
                'sentences' => ['___力量。', '___社会。', '___巨大。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '珍惜',
                'pinyin' => 'zhēn xī',
                'simplified' => '珍惜',
                'traditional' => '珍惜',
                'part_of_speech' => 'verb',
                'meaning' => 'To cherish / To treasure',
                'meaning_zh' => '珍惜',
                'example_sentence' => '珍惜时间。',
                'example_translation' => 'Cherish time.',
                'definition' => 'To cherish, to treasure, to value',
                'sentences' => ['___机会。', '___拥有。', '___当下。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '热爱',
                'pinyin' => 'rè ài',
                'simplified' => '热爱',
                'traditional' => '熱愛',
                'part_of_speech' => 'verb',
                'meaning' => 'To love / To adore',
                'meaning_zh' => '热爱',
                'example_sentence' => '热爱生活。',
                'example_translation' => 'Love life.',
                'definition' => 'To love, to adore, to be enthusiastic about',
                'sentences' => ['___工作。', '___祖国。', '___事业。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '平衡',
                'pinyin' => 'píng héng',
                'simplified' => '平衡',
                'traditional' => '平衡',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Balance / To balance',
                'meaning_zh' => '平衡',
                'example_sentence' => '保持平衡。',
                'example_translation' => 'Maintain balance.',
                'definition' => 'Balance, to balance, equilibrium',
                'sentences' => ['___工作。', '___生活。', '___发展。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '简单',
                'pinyin' => 'jiǎn dān',
                'simplified' => '简单',
                'traditional' => '簡單',
                'part_of_speech' => 'adjective',
                'meaning' => 'Simple / Easy',
                'meaning_zh' => '简单',
                'example_sentence' => '简单生活。',
                'example_translation' => 'Live simply.',
                'definition' => 'Simple, easy, uncomplicated',
                'sentences' => ['___朴素。', '___明了。', '___快乐。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 154,
                'word' => '充实',
                'pinyin' => 'chōng shí',
                'simplified' => '充实',
                'traditional' => '充實',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Enriching / To enrich',
                'meaning_zh' => '充实',
                'example_sentence' => '生活很充实。',
                'example_translation' => 'Life is very fulfilling.',
                'definition' => 'Enriching, to enrich, substantial',
                'sentences' => ['___自己。', '___生活。', '___内容。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($failureVocab, $valuesVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
