<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic130to133Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [130, 133])->delete();

        // Topic 130: Work Environment and Communication - 工作环境与沟通
        $workEnvVocab = [
            [
                'topic_id' => 130,
                'word' => '同事',
                'pinyin' => 'tóng shì',
                'simplified' => '同事',
                'traditional' => '同事',
                'part_of_speech' => 'noun',
                'meaning' => 'Colleague / Coworker',
                'meaning_zh' => '同事',
                'example_sentence' => '我和同事关系很好。',
                'example_translation' => 'I have a good relationship with my colleagues.',
                'definition' => 'Colleague, coworker, fellow worker',
                'sentences' => ['___关系。', '___之间。', '___合作。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '上司',
                'pinyin' => 'shàng si',
                'simplified' => '上司',
                'traditional' => '上司',
                'part_of_speech' => 'noun',
                'meaning' => 'Boss / Superior',
                'meaning_zh' => '上司',
                'example_sentence' => '上司对我很信任。',
                'example_translation' => 'My boss trusts me a lot.',
                'definition' => 'Boss, superior, supervisor',
                'sentences' => ['___领导。', '___关系。', '___要求。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '下属',
                'pinyin' => 'xià shǔ',
                'simplified' => '下属',
                'traditional' => '下屬',
                'part_of_speech' => 'noun',
                'meaning' => 'Subordinate',
                'meaning_zh' => '下属',
                'example_sentence' => '他有很多下属。',
                'example_translation' => 'He has many subordinates.',
                'definition' => 'Subordinate, staff under one\'s supervision',
                'sentences' => ['___管理。', '___工作。', '___关系。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '团队',
                'pinyin' => 'tuán duì',
                'simplified' => '团队',
                'traditional' => '團隊',
                'part_of_speech' => 'noun',
                'meaning' => 'Team',
                'meaning_zh' => '团队',
                'example_sentence' => '团队合作很重要。',
                'example_translation' => 'Teamwork is very important.',
                'definition' => 'Team, group',
                'sentences' => ['___精神。', '___合作。', '___建设。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '协作',
                'pinyin' => 'xié zuò',
                'simplified' => '协作',
                'traditional' => '協作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Cooperation / To cooperate',
                'meaning_zh' => '协作',
                'example_sentence' => '需要大家协作完成。',
                'example_translation' => 'Everyone needs to cooperate to complete it.',
                'definition' => 'Cooperation, to cooperate, collaboration',
                'sentences' => ['___精神。', '___能力。', '___完成。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '沟通',
                'pinyin' => 'gōu tōng',
                'simplified' => '沟通',
                'traditional' => '溝通',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Communication / To communicate',
                'meaning_zh' => '沟通',
                'example_sentence' => '沟通很重要。',
                'example_translation' => 'Communication is very important.',
                'definition' => 'Communication, to communicate',
                'sentences' => ['___能力。', '___交流。', '___方式。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '汇报',
                'pinyin' => 'huì bào',
                'simplified' => '汇报',
                'traditional' => '匯報',
                'part_of_speech' => 'verb',
                'meaning' => 'To report / To brief',
                'meaning_zh' => '汇报',
                'example_sentence' => '向领导汇报工作。',
                'example_translation' => 'Report work to the leader.',
                'definition' => 'To report, to brief, to give an account',
                'sentences' => ['___工作。', '___情况。', '___进展。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '会议',
                'pinyin' => 'huì yì',
                'simplified' => '会议',
                'traditional' => '會議',
                'part_of_speech' => 'noun',
                'meaning' => 'Meeting / Conference',
                'meaning_zh' => '会议',
                'example_sentence' => '今天有个重要会议。',
                'example_translation' => 'There is an important meeting today.',
                'definition' => 'Meeting, conference, session',
                'sentences' => ['开___。', '___室。', '___内容。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '讨论',
                'pinyin' => 'tǎo lùn',
                'simplified' => '讨论',
                'traditional' => '討論',
                'part_of_speech' => 'verb',
                'meaning' => 'To discuss',
                'meaning_zh' => '讨论',
                'example_sentence' => '我们讨论了这个问题。',
                'example_translation' => 'We discussed this issue.',
                'definition' => 'To discuss, discussion',
                'sentences' => ['___问题。', '___方案。', '___会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '办公室',
                'pinyin' => 'bàn gōng shì',
                'simplified' => '办公室',
                'traditional' => '辦公室',
                'part_of_speech' => 'noun',
                'meaning' => 'Office',
                'meaning_zh' => '办公室',
                'example_sentence' => '我在办公室工作。',
                'example_translation' => 'I work in the office.',
                'definition' => 'Office, workspace',
                'sentences' => ['___环境。', '___文化。', '___政治。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '效率',
                'pinyin' => 'xiào lǜ',
                'simplified' => '效率',
                'traditional' => '效率',
                'part_of_speech' => 'noun',
                'meaning' => 'Efficiency',
                'meaning_zh' => '效率',
                'example_sentence' => '要提高工作效率。',
                'example_translation' => 'Need to improve work efficiency.',
                'definition' => 'Efficiency, productivity',
                'sentences' => ['工作___。', '___提高。', '___低。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '加班',
                'pinyin' => 'jiā bān',
                'simplified' => '加班',
                'traditional' => '加班',
                'part_of_speech' => 'verb',
                'meaning' => 'To work overtime',
                'meaning_zh' => '加班',
                'example_sentence' => '今天需要加班。',
                'example_translation' => 'Need to work overtime today.',
                'definition' => 'To work overtime, overtime work',
                'sentences' => ['___费。', '经常___。', '___工作。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '出差',
                'pinyin' => 'chū chāi',
                'simplified' => '出差',
                'traditional' => '出差',
                'part_of_speech' => 'verb',
                'meaning' => 'To go on a business trip',
                'meaning_zh' => '出差',
                'example_sentence' => '他去北京出差了。',
                'example_translation' => 'He went to Beijing on a business trip.',
                'definition' => 'To go on a business trip, business travel',
                'sentences' => ['___旅行。', '___补助。', '经常___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '任务',
                'pinyin' => 'rèn wu',
                'simplified' => '任务',
                'traditional' => '任務',
                'part_of_speech' => 'noun',
                'meaning' => 'Task / Mission',
                'meaning_zh' => '任务',
                'example_sentence' => '完成任务。',
                'example_translation' => 'Complete the task.',
                'definition' => 'Task, mission, assignment',
                'sentences' => ['___完成。', '___分配。', '___重。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '项目',
                'pinyin' => 'xiàng mù',
                'simplified' => '项目',
                'traditional' => '項目',
                'part_of_speech' => 'noun',
                'meaning' => 'Project',
                'meaning_zh' => '项目',
                'example_sentence' => '这个项目很重要。',
                'example_translation' => 'This project is very important.',
                'definition' => 'Project, program, item',
                'sentences' => ['___管理。', '___负责。', '___进度。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '截止',
                'pinyin' => 'jié zhǐ',
                'simplified' => '截止',
                'traditional' => '截止',
                'part_of_speech' => 'verb',
                'meaning' => 'Deadline / To close',
                'meaning_zh' => '截止',
                'example_sentence' => '截止日期是明天。',
                'example_translation' => 'The deadline is tomorrow.',
                'definition' => 'Deadline, to close, to stop',
                'sentences' => ['___时间。', '___日期。', '___报名。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '文件',
                'pinyin' => 'wén jiàn',
                'simplified' => '文件',
                'traditional' => '文件',
                'part_of_speech' => 'noun',
                'meaning' => 'Document / File',
                'meaning_zh' => '文件',
                'example_sentence' => '请签署这个文件。',
                'example_translation' => 'Please sign this document.',
                'definition' => 'Document, file, papers',
                'sentences' => ['___处理。', '___管理。', '___夹。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '责任',
                'pinyin' => 'zé rèn',
                'simplified' => '责任',
                'traditional' => '責任',
                'part_of_speech' => 'noun',
                'meaning' => 'Responsibility',
                'meaning_zh' => '责任',
                'example_sentence' => '这是我的责任。',
                'example_translation' => 'This is my responsibility.',
                'definition' => 'Responsibility, duty',
                'sentences' => ['___心。', '___感。', '承担___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '压力',
                'pinyin' => 'yā lì',
                'simplified' => '压力',
                'traditional' => '壓力',
                'part_of_speech' => 'noun',
                'meaning' => 'Pressure / Stress',
                'meaning_zh' => '压力',
                'example_sentence' => '工作压力很大。',
                'example_translation' => 'Work pressure is very high.',
                'definition' => 'Pressure, stress, strain',
                'sentences' => ['___大。', '___管理。', '缓解___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 130,
                'word' => '氛围',
                'pinyin' => 'fēn wéi',
                'simplified' => '氛围',
                'traditional' => '氛圍',
                'part_of_speech' => 'noun',
                'meaning' => 'Atmosphere / Ambience',
                'meaning_zh' => '氛围',
                'example_sentence' => '办公室氛围很好。',
                'example_translation' => 'The office atmosphere is very good.',
                'definition' => 'Atmosphere, ambience, mood',
                'sentences' => ['工作___。', '___轻松。', '___融洽。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 131: Finance and Investment - 财务与投资
        $financeVocab = [
            [
                'topic_id' => 131,
                'word' => '财务',
                'pinyin' => 'cái wù',
                'simplified' => '财务',
                'traditional' => '財務',
                'part_of_speech' => 'noun',
                'meaning' => 'Finance / Financial affairs',
                'meaning_zh' => '财务',
                'example_sentence' => '财务管理很重要。',
                'example_translation' => 'Financial management is very important.',
                'definition' => 'Finance, financial affairs',
                'sentences' => ['___管理。', '___报表。', '___状况。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '理财',
                'pinyin' => 'lǐ cái',
                'simplified' => '理财',
                'traditional' => '理財',
                'part_of_speech' => 'verb',
                'meaning' => 'To manage finances',
                'meaning_zh' => '理财',
                'example_sentence' => '要学会理财。',
                'example_translation' => 'Need to learn to manage finances.',
                'definition' => 'To manage finances, financial planning',
                'sentences' => ['___产品。', '___知识。', '___规划。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '储蓄',
                'pinyin' => 'chǔ xù',
                'simplified' => '储蓄',
                'traditional' => '儲蓄',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Savings / To save',
                'meaning_zh' => '储蓄',
                'example_sentence' => '要有储蓄的习惯。',
                'example_translation' => 'Need to have the habit of saving.',
                'definition' => 'Savings, to save money, deposits',
                'sentences' => ['___存款。', '___率。', '___账户。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '存款',
                'pinyin' => 'cún kuǎn',
                'simplified' => '存款',
                'traditional' => '存款',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Deposit / To deposit',
                'meaning_zh' => '存款',
                'example_sentence' => '我在银行有存款。',
                'example_translation' => 'I have deposits in the bank.',
                'definition' => 'Deposit, to deposit money',
                'sentences' => ['___利率。', '定期___。', '___账户。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '取款',
                'pinyin' => 'qǔ kuǎn',
                'simplified' => '取款',
                'traditional' => '取款',
                'part_of_speech' => 'verb',
                'meaning' => 'To withdraw money',
                'meaning_zh' => '取款',
                'example_sentence' => '我去银行取款。',
                'example_translation' => 'I went to the bank to withdraw money.',
                'definition' => 'To withdraw money, withdrawal',
                'sentences' => ['___机。', '___密码。', '___手续。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '转账',
                'pinyin' => 'zhuǎn zhàng',
                'simplified' => '转账',
                'traditional' => '轉賬',
                'part_of_speech' => 'verb',
                'meaning' => 'To transfer money',
                'meaning_zh' => '转账',
                'example_sentence' => '我给你转账。',
                'example_translation' => 'I will transfer money to you.',
                'definition' => 'To transfer money, bank transfer',
                'sentences' => ['___手续费。', '网上___。', '___记录。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '利息',
                'pinyin' => 'lì xī',
                'simplified' => '利息',
                'traditional' => '利息',
                'part_of_speech' => 'noun',
                'meaning' => 'Interest',
                'meaning_zh' => '利息',
                'example_sentence' => '存款有利息。',
                'example_translation' => 'Deposits earn interest.',
                'definition' => 'Interest, interest rate',
                'sentences' => ['___率。', '___收入。', '支付___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '汇率',
                'pinyin' => 'huì lǜ',
                'simplified' => '汇率',
                'traditional' => '匯率',
                'part_of_speech' => 'noun',
                'meaning' => 'Exchange rate',
                'meaning_zh' => '汇率',
                'example_sentence' => '今天的汇率是多少？',
                'example_translation' => 'What is today\'s exchange rate?',
                'definition' => 'Exchange rate, currency rate',
                'sentences' => ['___变化。', '___波动。', '___换算。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '基金',
                'pinyin' => 'jī jīn',
                'simplified' => '基金',
                'traditional' => '基金',
                'part_of_speech' => 'noun',
                'meaning' => 'Fund',
                'meaning_zh' => '基金',
                'example_sentence' => '我买了一些基金。',
                'example_translation' => 'I bought some funds.',
                'definition' => 'Fund, investment fund',
                'sentences' => ['___投资。', '___收益。', '___经理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '债券',
                'pinyin' => 'zhài quàn',
                'simplified' => '债券',
                'traditional' => '債券',
                'part_of_speech' => 'noun',
                'meaning' => 'Bond',
                'meaning_zh' => '债券',
                'example_sentence' => '国债券很安全。',
                'example_translation' => 'Government bonds are very safe.',
                'definition' => 'Bond, debenture',
                'sentences' => ['___市场。', '___投资。', '___收益。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '风险',
                'pinyin' => 'fēng xiǎn',
                'simplified' => '风险',
                'traditional' => '風險',
                'part_of_speech' => 'noun',
                'meaning' => 'Risk',
                'meaning_zh' => '风险',
                'example_sentence' => '投资有风险。',
                'example_translation' => 'Investment has risks.',
                'definition' => 'Risk, hazard',
                'sentences' => ['___管理。', '___评估。', '___控制。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '收益',
                'pinyin' => 'shōu yì',
                'simplified' => '收益',
                'traditional' => '收益',
                'part_of_speech' => 'noun',
                'meaning' => 'Return / Profit',
                'meaning_zh' => '收益',
                'example_sentence' => '投资收益不错。',
                'example_translation' => 'Investment returns are good.',
                'definition' => 'Return, profit, earnings',
                'sentences' => ['___率。', '___高。', '___稳定。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '亏损',
                'pinyin' => 'kuī sǔn',
                'simplified' => '亏损',
                'traditional' => '虧損',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Loss / To lose money',
                'meaning_zh' => '亏损',
                'example_sentence' => '公司出现了亏损。',
                'example_translation' => 'The company suffered losses.',
                'definition' => 'Loss, to lose money, deficit',
                'sentences' => ['___严重。', '___额。', '___状态。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '分红',
                'pinyin' => 'fēn hóng',
                'simplified' => '分红',
                'traditional' => '分紅',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Dividend / To distribute dividends',
                'meaning_zh' => '分红',
                'example_sentence' => '公司每年分红。',
                'example_translation' => 'The company distributes dividends every year.',
                'definition' => 'Dividend, to distribute dividends',
                'sentences' => ['___方案。', '___比例。', '___收入。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '资产',
                'pinyin' => 'zī chǎn',
                'simplified' => '资产',
                'traditional' => '資產',
                'part_of_speech' => 'noun',
                'meaning' => 'Asset / Property',
                'meaning_zh' => '资产',
                'example_sentence' => '他有很多资产。',
                'example_translation' => 'He has many assets.',
                'definition' => 'Asset, property, wealth',
                'sentences' => ['___配置。', '___管理。', '固定___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '负债',
                'pinyin' => 'fù zhài',
                'simplified' => '负债',
                'traditional' => '負債',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Debt / Liability',
                'meaning_zh' => '负债',
                'example_sentence' => '要减少负债。',
                'example_translation' => 'Need to reduce debt.',
                'definition' => 'Debt, liability, to be in debt',
                'sentences' => ['___率。', '___累累。', '___压力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '预算',
                'pinyin' => 'yù suàn',
                'simplified' => '预算',
                'traditional' => '預算',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Budget',
                'meaning_zh' => '预算',
                'example_sentence' => '要做好预算。',
                'example_translation' => 'Need to make a good budget.',
                'definition' => 'Budget, to budget',
                'sentences' => ['___计划。', '___控制。', '___超支。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '账单',
                'pinyin' => 'zhàng dān',
                'simplified' => '账单',
                'traditional' => '賬單',
                'part_of_speech' => 'noun',
                'meaning' => 'Bill / Statement',
                'meaning_zh' => '账单',
                'example_sentence' => '我收到了账单。',
                'example_translation' => 'I received the bill.',
                'definition' => 'Bill, statement, invoice',
                'sentences' => ['___支付。', '信用卡___。', '___明细。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '保险',
                'pinyin' => 'bǎo xiǎn',
                'simplified' => '保险',
                'traditional' => '保險',
                'part_of_speech' => 'noun',
                'meaning' => 'Insurance',
                'meaning_zh' => '保险',
                'example_sentence' => '要买保险。',
                'example_translation' => 'Need to buy insurance.',
                'definition' => 'Insurance, to insure',
                'sentences' => ['___公司。', '___费。', '___理赔。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 131,
                'word' => '养老金',
                'pinyin' => 'yǎng lǎo jīn',
                'simplified' => '养老金',
                'traditional' => '養老金',
                'part_of_speech' => 'noun',
                'meaning' => 'Pension',
                'meaning_zh' => '养老金',
                'example_sentence' => '他每月领取养老金。',
                'example_translation' => 'He receives a pension every month.',
                'definition' => 'Pension, retirement fund',
                'sentences' => ['___制度。', '领取___。', '___保险。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 132: Lifelong Learning - 终身学习
        $learningVocab = [
            [
                'topic_id' => 132,
                'word' => '学习',
                'pinyin' => 'xué xí',
                'simplified' => '学习',
                'traditional' => '學習',
                'part_of_speech' => 'verb',
                'meaning' => 'To learn / To study',
                'meaning_zh' => '学习',
                'example_sentence' => '我们要不断学习。',
                'example_translation' => 'We need to keep learning.',
                'definition' => 'To learn, to study',
                'sentences' => ['___知识。', '___方法。', '___能力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '进修',
                'pinyin' => 'jìn xiū',
                'simplified' => '进修',
                'traditional' => '進修',
                'part_of_speech' => 'verb',
                'meaning' => 'Further study / To take advanced studies',
                'meaning_zh' => '进修',
                'example_sentence' => '他去国外进修。',
                'example_translation' => 'He went abroad for further study.',
                'definition' => 'Further study, to take advanced studies',
                'sentences' => ['___课程。', '___机会。', '___学习。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '自学',
                'pinyin' => 'zì xué',
                'simplified' => '自学',
                'traditional' => '自學',
                'part_of_speech' => 'verb',
                'meaning' => 'Self-study / To teach oneself',
                'meaning_zh' => '自学',
                'example_sentence' => '我通过自学学会了编程。',
                'example_translation' => 'I learned programming through self-study.',
                'definition' => 'Self-study, to teach oneself',
                'sentences' => ['___成才。', '___能力。', '___考试。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '充电',
                'pinyin' => 'chōng diàn',
                'simplified' => '充电',
                'traditional' => '充電',
                'part_of_speech' => 'verb',
                'meaning' => 'To recharge / To update one\'s knowledge',
                'meaning_zh' => '充电',
                'example_sentence' => '要给自己充电。',
                'example_translation' => 'Need to update one\'s knowledge.',
                'definition' => 'To recharge, to update knowledge (metaphor)',
                'sentences' => ['___学习。', '___培训。', '___提升。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '技能',
                'pinyin' => 'jì néng',
                'simplified' => '技能',
                'traditional' => '技能',
                'part_of_speech' => 'noun',
                'meaning' => 'Skill',
                'meaning_zh' => '技能',
                'example_sentence' => '要掌握新技能。',
                'example_translation' => 'Need to master new skills.',
                'definition' => 'Skill, technique',
                'sentences' => ['___培训。', '___提升。', '专业___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '知识',
                'pinyin' => 'zhī shi',
                'simplified' => '知识',
                'traditional' => '知識',
                'part_of_speech' => 'noun',
                'meaning' => 'Knowledge',
                'meaning_zh' => '知识',
                'example_sentence' => '知识就是力量。',
                'example_translation' => 'Knowledge is power.',
                'definition' => 'Knowledge, information',
                'sentences' => ['___储备。', '___更新。', '___产权。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '掌握',
                'pinyin' => 'zhǎng wò',
                'simplified' => '掌握',
                'traditional' => '掌握',
                'part_of_speech' => 'verb',
                'meaning' => 'To master / To grasp',
                'meaning_zh' => '掌握',
                'example_sentence' => '要掌握这门技术。',
                'example_translation' => 'Need to master this technology.',
                'definition' => 'To master, to grasp, to command',
                'sentences' => ['___知识。', '___技能。', '___方法。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '熟练',
                'pinyin' => 'shú liàn',
                'simplified' => '熟练',
                'traditional' => '熟練',
                'part_of_speech' => 'adjective',
                'meaning' => 'Skilled / Proficient',
                'meaning_zh' => '熟练',
                'example_sentence' => '他的技术很熟练。',
                'example_translation' => 'His skills are very proficient.',
                'definition' => 'Skilled, proficient, practiced',
                'sentences' => ['___工人。', '___掌握。', '___程度。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '证书',
                'pinyin' => 'zhèng shū',
                'simplified' => '证书',
                'traditional' => '證書',
                'part_of_speech' => 'noun',
                'meaning' => 'Certificate',
                'meaning_zh' => '证书',
                'example_sentence' => '我获得了证书。',
                'example_translation' => 'I obtained a certificate.',
                'definition' => 'Certificate, credential',
                'sentences' => ['___考试。', '获得___。', '___认证。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '课程',
                'pinyin' => 'kè chéng',
                'simplified' => '课程',
                'traditional' => '課程',
                'part_of_speech' => 'noun',
                'meaning' => 'Course / Curriculum',
                'meaning_zh' => '课程',
                'example_sentence' => '这个课程很有用。',
                'example_translation' => 'This course is very useful.',
                'definition' => 'Course, curriculum, class',
                'sentences' => ['___安排。', '___内容。', '___学习。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '讲座',
                'pinyin' => 'jiǎng zuò',
                'simplified' => '讲座',
                'traditional' => '講座',
                'part_of_speech' => 'noun',
                'meaning' => 'Lecture / Seminar',
                'meaning_zh' => '讲座',
                'example_sentence' => '今天有个讲座。',
                'example_translation' => 'There is a lecture today.',
                'definition' => 'Lecture, seminar, talk',
                'sentences' => ['参加___。', '___主题。', '___嘉宾。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '研讨会',
                'pinyin' => 'yán tǎo huì',
                'simplified' => '研讨会',
                'traditional' => '研討會',
                'part_of_speech' => 'noun',
                'meaning' => 'Seminar / Workshop',
                'meaning_zh' => '研讨会',
                'example_sentence' => '我参加了研讨会。',
                'example_translation' => 'I attended the seminar.',
                'definition' => 'Seminar, workshop, symposium',
                'sentences' => ['学术___。', '___交流。', '___议题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '在线',
                'pinyin' => 'zài xiàn',
                'simplified' => '在线',
                'traditional' => '在線',
                'part_of_speech' => 'adjective',
                'meaning' => 'Online',
                'meaning_zh' => '在线',
                'example_sentence' => '在线学习很方便。',
                'example_translation' => 'Online learning is very convenient.',
                'definition' => 'Online, on the internet',
                'sentences' => ['___教育。', '___课程。', '___咨询。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '网课',
                'pinyin' => 'wǎng kè',
                'simplified' => '网课',
                'traditional' => '網課',
                'part_of_speech' => 'noun',
                'meaning' => 'Online course',
                'meaning_zh' => '网课',
                'example_sentence' => '我在上网课。',
                'example_translation' => 'I am taking online courses.',
                'definition' => 'Online course, web-based course',
                'sentences' => ['上___。', '___平台。', '___教学。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '阅读',
                'pinyin' => 'yuè dú',
                'simplified' => '阅读',
                'traditional' => '閱讀',
                'part_of_speech' => 'verb',
                'meaning' => 'To read',
                'meaning_zh' => '阅读',
                'example_sentence' => '我喜欢阅读。',
                'example_translation' => 'I like reading.',
                'definition' => 'To read, reading',
                'sentences' => ['___理解。', '___习惯。', '___量。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '笔记',
                'pinyin' => 'bǐ jì',
                'simplified' => '笔记',
                'traditional' => '筆記',
                'part_of_speech' => 'noun',
                'meaning' => 'Notes',
                'meaning_zh' => '笔记',
                'example_sentence' => '我做了笔记。',
                'example_translation' => 'I took notes.',
                'definition' => 'Notes, to take notes',
                'sentences' => ['做___。', '___本。', '___整理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '复习',
                'pinyin' => 'fù xí',
                'simplified' => '复习',
                'traditional' => '複習',
                'part_of_speech' => 'verb',
                'meaning' => 'To review / To revise',
                'meaning_zh' => '复习',
                'example_sentence' => '考前要好好复习。',
                'example_translation' => 'Need to review well before the exam.',
                'definition' => 'To review, to revise, revision',
                'sentences' => ['___功课。', '___资料。', '___计划。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '总结',
                'pinyin' => 'zǒng jié',
                'simplified' => '总结',
                'traditional' => '總結',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To summarize / Summary',
                'meaning_zh' => '总结',
                'example_sentence' => '要及时总结经验。',
                'example_translation' => 'Need to summarize experience in time.',
                'definition' => 'To summarize, summary, to sum up',
                'sentences' => ['___经验。', '___报告。', '___会议。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '反思',
                'pinyin' => 'fǎn sī',
                'simplified' => '反思',
                'traditional' => '反思',
                'part_of_speech' => 'verb',
                'meaning' => 'To reflect / To introspect',
                'meaning_zh' => '反思',
                'example_sentence' => '要经常反思。',
                'example_translation' => 'Need to reflect often.',
                'definition' => 'To reflect, to introspect, reflection',
                'sentences' => ['___自己。', '___总结。', '___能力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 132,
                'word' => '成长',
                'pinyin' => 'chéng zhǎng',
                'simplified' => '成长',
                'traditional' => '成長',
                'part_of_speech' => 'verb',
                'meaning' => 'To grow / Growth',
                'meaning_zh' => '成长',
                'example_sentence' => '学习让我们成长。',
                'example_translation' => 'Learning helps us grow.',
                'definition' => 'To grow, growth, to develop',
                'sentences' => ['___过程。', '___经历。', '快速___。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 133: Modern and Traditional Education - 现代与传统教育
        $educationVocab = [
            [
                'topic_id' => 133,
                'word' => '教育',
                'pinyin' => 'jiào yù',
                'simplified' => '教育',
                'traditional' => '教育',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Education / To educate',
                'meaning_zh' => '教育',
                'example_sentence' => '教育很重要。',
                'example_translation' => 'Education is very important.',
                'definition' => 'Education, to educate',
                'sentences' => ['___体系。', '___改革。', '___理念。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '教学',
                'pinyin' => 'jiào xué',
                'simplified' => '教学',
                'traditional' => '教學',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Teaching / To teach',
                'meaning_zh' => '教学',
                'example_sentence' => '教学方法很重要。',
                'example_translation' => 'Teaching methods are very important.',
                'definition' => 'Teaching, to teach, instruction',
                'sentences' => ['___方法。', '___质量。', '___内容。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '师资',
                'pinyin' => 'shī zī',
                'simplified' => '师资',
                'traditional' => '師資',
                'part_of_speech' => 'noun',
                'meaning' => 'Teaching staff / Faculty',
                'meaning_zh' => '师资',
                'example_sentence' => '学校师资力量雄厚。',
                'example_translation' => 'The school has strong teaching staff.',
                'definition' => 'Teaching staff, faculty, teachers',
                'sentences' => ['___力量。', '___队伍。', '___培训。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '教材',
                'pinyin' => 'jiào cái',
                'simplified' => '教材',
                'traditional' => '教材',
                'part_of_speech' => 'noun',
                'meaning' => 'Teaching material / Textbook',
                'meaning_zh' => '教材',
                'example_sentence' => '这套教材很好。',
                'example_translation' => 'This set of teaching materials is very good.',
                'definition' => 'Teaching material, textbook',
                'sentences' => ['___编写。', '___内容。', '___选择。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '课堂',
                'pinyin' => 'kè táng',
                'simplified' => '课堂',
                'traditional' => '課堂',
                'part_of_speech' => 'noun',
                'meaning' => 'Classroom',
                'meaning_zh' => '课堂',
                'example_sentence' => '课堂气氛很好。',
                'example_translation' => 'The classroom atmosphere is very good.',
                'definition' => 'Classroom, class',
                'sentences' => ['___教学。', '___纪律。', '___互动。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '作业',
                'pinyin' => 'zuò yè',
                'simplified' => '作业',
                'traditional' => '作業',
                'part_of_speech' => 'noun',
                'meaning' => 'Homework / Assignment',
                'meaning_zh' => '作业',
                'example_sentence' => '今天作业很多。',
                'example_translation' => 'There is a lot of homework today.',
                'definition' => 'Homework, assignment, schoolwork',
                'sentences' => ['做___。', '___量。', '___批改。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '考试',
                'pinyin' => 'kǎo shì',
                'simplified' => '考试',
                'traditional' => '考試',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Exam / To take an exam',
                'meaning_zh' => '考试',
                'example_sentence' => '明天有考试。',
                'example_translation' => 'There is an exam tomorrow.',
                'definition' => 'Exam, examination, test',
                'sentences' => ['___成绩。', '___制度。', '___压力。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '成绩',
                'pinyin' => 'chéng jì',
                'simplified' => '成绩',
                'traditional' => '成績',
                'part_of_speech' => 'noun',
                'meaning' => 'Grade / Result / Achievement',
                'meaning_zh' => '成绩',
                'example_sentence' => '他成绩很好。',
                'example_translation' => 'His grades are very good.',
                'definition' => 'Grade, result, achievement, performance',
                'sentences' => ['___单。', '___优秀。', '___提高。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '分数',
                'pinyin' => 'fēn shù',
                'simplified' => '分数',
                'traditional' => '分數',
                'part_of_speech' => 'noun',
                'meaning' => 'Score / Mark',
                'meaning_zh' => '分数',
                'example_sentence' => '这次考试分数不错。',
                'example_translation' => 'The score on this exam is pretty good.',
                'definition' => 'Score, mark, points',
                'sentences' => ['___高。', '___线。', '___评定。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '升学',
                'pinyin' => 'shēng xué',
                'simplified' => '升学',
                'traditional' => '升學',
                'part_of_speech' => 'verb',
                'meaning' => 'To enter a higher school',
                'meaning_zh' => '升学',
                'example_sentence' => '升学压力很大。',
                'example_translation' => 'Entrance exam pressure is very high.',
                'definition' => 'To enter a higher school, enrollment',
                'sentences' => ['___率。', '___考试。', '___竞争。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '素质',
                'pinyin' => 'sù zhì',
                'simplified' => '素质',
                'traditional' => '素質',
                'part_of_speech' => 'noun',
                'meaning' => 'Quality / Caliber',
                'meaning_zh' => '素质',
                'example_sentence' => '要提高素质教育。',
                'example_translation' => 'Need to improve quality education.',
                'definition' => 'Quality, caliber, character',
                'sentences' => ['___教育。', '___高。', '综合___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '德育',
                'pinyin' => 'dé yù',
                'simplified' => '德育',
                'traditional' => '德育',
                'part_of_speech' => 'noun',
                'meaning' => 'Moral education',
                'meaning_zh' => '德育',
                'example_sentence' => '德育很重要。',
                'example_translation' => 'Moral education is very important.',
                'definition' => 'Moral education, character education',
                'sentences' => ['___工作。', '___课程。', '___教育。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '体育',
                'pinyin' => 'tǐ yù',
                'simplified' => '体育',
                'traditional' => '體育',
                'part_of_speech' => 'noun',
                'meaning' => 'Physical education / Sports',
                'meaning_zh' => '体育',
                'example_sentence' => '体育锻炼很重要。',
                'example_translation' => 'Physical exercise is very important.',
                'definition' => 'Physical education, sports, PE',
                'sentences' => ['___课。', '___运动。', '___锻炼。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '美育',
                'pinyin' => 'měi yù',
                'simplified' => '美育',
                'traditional' => '美育',
                'part_of_speech' => 'noun',
                'meaning' => 'Aesthetic education',
                'meaning_zh' => '美育',
                'example_sentence' => '美育培养审美能力。',
                'example_translation' => 'Aesthetic education cultivates aesthetic ability.',
                'definition' => 'Aesthetic education, arts education',
                'sentences' => ['___教育。', '___课程。', '___培养。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '启蒙',
                'pinyin' => 'qǐ méng',
                'simplified' => '启蒙',
                'traditional' => '啟蒙',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Enlightenment / To enlighten',
                'meaning_zh' => '启蒙',
                'example_sentence' => '幼儿启蒙教育。',
                'example_translation' => 'Early childhood enlightenment education.',
                'definition' => 'Enlightenment, to enlighten, initiation',
                'sentences' => ['___教育。', '___老师。', '___读物。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '应试',
                'pinyin' => 'yìng shì',
                'simplified' => '应试',
                'traditional' => '應試',
                'part_of_speech' => 'verb',
                'meaning' => 'To take an exam',
                'meaning_zh' => '应试',
                'example_sentence' => '应试教育有弊端。',
                'example_translation' => 'Exam-oriented education has drawbacks.',
                'definition' => 'To take an exam, exam-oriented',
                'sentences' => ['___教育。', '___能力。', '___技巧。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '创新',
                'pinyin' => 'chuàng xīn',
                'simplified' => '创新',
                'traditional' => '創新',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Innovation / To innovate',
                'meaning_zh' => '创新',
                'example_sentence' => '要培养创新能力。',
                'example_translation' => 'Need to cultivate innovation ability.',
                'definition' => 'Innovation, to innovate, creativity',
                'sentences' => ['___思维。', '___能力。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '实践',
                'pinyin' => 'shí jiàn',
                'simplified' => '实践',
                'traditional' => '實踐',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Practice / To practice',
                'meaning_zh' => '实践',
                'example_sentence' => '理论要结合实践。',
                'example_translation' => 'Theory must be combined with practice.',
                'definition' => 'Practice, to practice, to put into practice',
                'sentences' => ['___活动。', '___能力。', '___经验。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '兴趣',
                'pinyin' => 'xìng qù',
                'simplified' => '兴趣',
                'traditional' => '興趣',
                'part_of_speech' => 'noun',
                'meaning' => 'Interest / Hobby',
                'meaning_zh' => '兴趣',
                'example_sentence' => '培养学习兴趣。',
                'example_translation' => 'Cultivate learning interest.',
                'definition' => 'Interest, hobby, enthusiasm',
                'sentences' => ['___爱好。', '___班。', '___培养。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 133,
                'word' => '因材施教',
                'pinyin' => 'yīn cái shī jiào',
                'simplified' => '因材施教',
                'traditional' => '因材施教',
                'part_of_speech' => 'idiom',
                'meaning' => 'To teach according to students\' abilities',
                'meaning_zh' => '因材施教',
                'example_sentence' => '教育要因材施教。',
                'example_translation' => 'Education should be tailored to individual students.',
                'definition' => 'To teach according to students\' abilities, individualized teaching',
                'sentences' => ['___理念。', '___方法。', '___原则。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($workEnvVocab, $financeVocab, $learningVocab, $educationVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
