<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic138to141Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [138, 141])->delete();

        // Topic 138: Pop Culture - 流行文化
        $popCultureVocab = [
            [
                'topic_id' => 138,
                'word' => '流行',
                'pinyin' => 'liú xíng',
                'simplified' => '流行',
                'traditional' => '流行',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'Popular / To be in fashion',
                'meaning_zh' => '流行',
                'example_sentence' => '这首歌很流行。',
                'example_translation' => 'This song is very popular.',
                'definition' => 'Popular, fashionable, to be in vogue',
                'sentences' => ['___歌曲。', '___趋势。', '___文化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '时尚',
                'pinyin' => 'shí shàng',
                'simplified' => '时尚',
                'traditional' => '時尚',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Fashion / Fashionable',
                'meaning_zh' => '时尚',
                'example_sentence' => '她很喜欢时尚。',
                'example_translation' => 'She likes fashion very much.',
                'definition' => 'Fashion, fashionable, stylish',
                'sentences' => ['___界。', '___潮流。', '___品牌。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '潮流',
                'pinyin' => 'cháo liú',
                'simplified' => '潮流',
                'traditional' => '潮流',
                'part_of_speech' => 'noun',
                'meaning' => 'Trend / Current',
                'meaning_zh' => '潮流',
                'example_sentence' => '要跟上时代潮流。',
                'example_translation' => 'Need to keep up with the trends of the times.',
                'definition' => 'Trend, current, tide',
                'sentences' => ['___趋势。', '___引领。', '___文化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '明星',
                'pinyin' => 'míng xīng',
                'simplified' => '明星',
                'traditional' => '明星',
                'part_of_speech' => 'noun',
                'meaning' => 'Star / Celebrity',
                'meaning_zh' => '明星',
                'example_sentence' => '他是一位明星。',
                'example_translation' => 'He is a star.',
                'definition' => 'Star, celebrity, famous person',
                'sentences' => ['电影___。', '___效应。', '___粉丝。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '偶像',
                'pinyin' => 'ǒu xiàng',
                'simplified' => '偶像',
                'traditional' => '偶像',
                'part_of_speech' => 'noun',
                'meaning' => 'Idol',
                'meaning_zh' => '偶像',
                'example_sentence' => '她是我的偶像。',
                'example_translation' => 'She is my idol.',
                'definition' => 'Idol, icon',
                'sentences' => ['___崇拜。', '___明星。', '___剧。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '粉丝',
                'pinyin' => 'fěn sī',
                'simplified' => '粉丝',
                'traditional' => '粉絲',
                'part_of_speech' => 'noun',
                'meaning' => 'Fan / Follower',
                'meaning_zh' => '粉丝',
                'example_sentence' => '他有很多粉丝。',
                'example_translation' => 'He has many fans.',
                'definition' => 'Fan, follower, supporter',
                'sentences' => ['___数量。', '___见面会。', '___经济。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '网红',
                'pinyin' => 'wǎng hóng',
                'simplified' => '网红',
                'traditional' => '網紅',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet celebrity',
                'meaning_zh' => '网红',
                'example_sentence' => '她是一个网红。',
                'example_translation' => 'She is an internet celebrity.',
                'definition' => 'Internet celebrity, online influencer',
                'sentences' => ['___经济。', '___主播。', '___产品。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '直播',
                'pinyin' => 'zhí bō',
                'simplified' => '直播',
                'traditional' => '直播',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Live broadcast / To livestream',
                'meaning_zh' => '直播',
                'example_sentence' => '我在看直播。',
                'example_translation' => 'I am watching a live broadcast.',
                'definition' => 'Live broadcast, to livestream',
                'sentences' => ['___平台。', '___带货。', '___间。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '热门',
                'pinyin' => 'rè mén',
                'simplified' => '热门',
                'traditional' => '熱門',
                'part_of_speech' => 'adjective',
                'meaning' => 'Popular / Hot',
                'meaning_zh' => '热门',
                'example_sentence' => '这是热门话题。',
                'example_translation' => 'This is a popular topic.',
                'definition' => 'Popular, hot, in demand',
                'sentences' => ['___话题。', '___搜索。', '___专业。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '话题',
                'pinyin' => 'huà tí',
                'simplified' => '话题',
                'traditional' => '話題',
                'part_of_speech' => 'noun',
                'meaning' => 'Topic / Subject',
                'meaning_zh' => '话题',
                'example_sentence' => '这是一个热门话题。',
                'example_translation' => 'This is a hot topic.',
                'definition' => 'Topic, subject of conversation',
                'sentences' => ['___讨论。', '___人物。', '___性。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '追星',
                'pinyin' => 'zhuī xīng',
                'simplified' => '追星',
                'traditional' => '追星',
                'part_of_speech' => 'verb',
                'meaning' => 'To be a fan / To follow celebrities',
                'meaning_zh' => '追星',
                'example_sentence' => '她很喜欢追星。',
                'example_translation' => 'She really likes following celebrities.',
                'definition' => 'To be a fan, to follow celebrities',
                'sentences' => ['___族。', '___文化。', '理性___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '娱乐',
                'pinyin' => 'yú lè',
                'simplified' => '娱乐',
                'traditional' => '娛樂',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Entertainment / To entertain',
                'meaning_zh' => '娱乐',
                'example_sentence' => '娱乐活动很多。',
                'example_translation' => 'There are many entertainment activities.',
                'definition' => 'Entertainment, to entertain, recreation',
                'sentences' => ['___圈。', '___节目。', '___新闻。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '综艺',
                'pinyin' => 'zōng yì',
                'simplified' => '综艺',
                'traditional' => '綜藝',
                'part_of_speech' => 'noun',
                'meaning' => 'Variety show',
                'meaning_zh' => '综艺',
                'example_sentence' => '这个综艺节目很有趣。',
                'example_translation' => 'This variety show is very interesting.',
                'definition' => 'Variety show, entertainment program',
                'sentences' => ['___节目。', '___明星。', '___效果。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '弹幕',
                'pinyin' => 'dàn mù',
                'simplified' => '弹幕',
                'traditional' => '彈幕',
                'part_of_speech' => 'noun',
                'meaning' => 'Bullet screen / Live comments',
                'meaning_zh' => '弹幕',
                'example_sentence' => '看视频的时候可以发弹幕。',
                'example_translation' => 'You can send bullet comments while watching videos.',
                'definition' => 'Bullet screen, scrolling comments on videos',
                'sentences' => ['___评论。', '___互动。', '___文化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '打卡',
                'pinyin' => 'dǎ kǎ',
                'simplified' => '打卡',
                'traditional' => '打卡',
                'part_of_speech' => 'verb',
                'meaning' => 'To check in / To clock in',
                'meaning_zh' => '打卡',
                'example_sentence' => '去景点打卡拍照。',
                'example_translation' => 'Check in and take photos at scenic spots.',
                'definition' => 'To check in, to clock in, to mark attendance',
                'sentences' => ['___上班。', '___地点。', '___文化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '吐槽',
                'pinyin' => 'tǔ cáo',
                'simplified' => '吐槽',
                'traditional' => '吐槽',
                'part_of_speech' => 'verb',
                'meaning' => 'To complain / To roast',
                'meaning_zh' => '吐槽',
                'example_sentence' => '大家都在吐槽这个节目。',
                'example_translation' => 'Everyone is complaining about this program.',
                'definition' => 'To complain, to roast, to criticize humorously',
                'sentences' => ['___大会。', '___文化。', '___对象。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '点赞',
                'pinyin' => 'diǎn zàn',
                'simplified' => '点赞',
                'traditional' => '點贊',
                'part_of_speech' => 'verb',
                'meaning' => 'To like / To give a thumbs up',
                'meaning_zh' => '点赞',
                'example_sentence' => '请给我点赞。',
                'example_translation' => 'Please give me a like.',
                'definition' => 'To like, to give a thumbs up',
                'sentences' => ['___评论。', '___数量。', '___转发。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '转发',
                'pinyin' => 'zhuǎn fā',
                'simplified' => '转发',
                'traditional' => '轉發',
                'part_of_speech' => 'verb',
                'meaning' => 'To forward / To share',
                'meaning_zh' => '转发',
                'example_sentence' => '帮我转发一下。',
                'example_translation' => 'Please help me share it.',
                'definition' => 'To forward, to share, to repost',
                'sentences' => ['___微博。', '___信息。', '___链接。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '表情包',
                'pinyin' => 'biǎo qíng bāo',
                'simplified' => '表情包',
                'traditional' => '表情包',
                'part_of_speech' => 'noun',
                'meaning' => 'Emoji / Sticker pack',
                'meaning_zh' => '表情包',
                'example_sentence' => '我收藏了很多表情包。',
                'example_translation' => 'I have collected many emoji stickers.',
                'definition' => 'Emoji, sticker pack, meme',
                'sentences' => ['___文化。', '发___。', '___大全。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 138,
                'word' => '网络用语',
                'pinyin' => 'wǎng luò yòng yǔ',
                'simplified' => '网络用语',
                'traditional' => '網絡用語',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet slang',
                'meaning_zh' => '网络用语',
                'example_sentence' => '年轻人喜欢用网络用语。',
                'example_translation' => 'Young people like to use internet slang.',
                'definition' => 'Internet slang, online terminology',
                'sentences' => ['___流行。', '___解释。', '___文化。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 139: Thought and Philosophy - 思想与哲学
        $philosophyVocab = [
            [
                'topic_id' => 139,
                'word' => '思想',
                'pinyin' => 'sī xiǎng',
                'simplified' => '思想',
                'traditional' => '思想',
                'part_of_speech' => 'noun',
                'meaning' => 'Thought / Ideology',
                'meaning_zh' => '思想',
                'example_sentence' => '他的思想很先进。',
                'example_translation' => 'His thoughts are very advanced.',
                'definition' => 'Thought, ideology, thinking',
                'sentences' => ['___观念。', '___交流。', '___解放。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '哲学',
                'pinyin' => 'zhé xué',
                'simplified' => '哲学',
                'traditional' => '哲學',
                'part_of_speech' => 'noun',
                'meaning' => 'Philosophy',
                'meaning_zh' => '哲学',
                'example_sentence' => '我对哲学很感兴趣。',
                'example_translation' => 'I am very interested in philosophy.',
                'definition' => 'Philosophy',
                'sentences' => ['___家。', '___思想。', '___研究。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '儒家',
                'pinyin' => 'Rú jiā',
                'simplified' => '儒家',
                'traditional' => '儒家',
                'part_of_speech' => 'noun',
                'meaning' => 'Confucianism / Confucian',
                'meaning_zh' => '儒家',
                'example_sentence' => '儒家思想影响深远。',
                'example_translation' => 'Confucianism has far-reaching influence.',
                'definition' => 'Confucianism, Confucian school',
                'sentences' => ['___思想。', '___文化。', '___经典。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '道家',
                'pinyin' => 'Dào jiā',
                'simplified' => '道家',
                'traditional' => '道家',
                'part_of_speech' => 'noun',
                'meaning' => 'Taoism / Daoist',
                'meaning_zh' => '道家',
                'example_sentence' => '道家讲究自然和谐。',
                'example_translation' => 'Taoism emphasizes natural harmony.',
                'definition' => 'Taoism, Daoist school',
                'sentences' => ['___思想。', '___哲学。', '___文化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '智慧',
                'pinyin' => 'zhì huì',
                'simplified' => '智慧',
                'traditional' => '智慧',
                'part_of_speech' => 'noun',
                'meaning' => 'Wisdom / Intelligence',
                'meaning_zh' => '智慧',
                'example_sentence' => '他是一个有智慧的人。',
                'example_translation' => 'He is a wise person.',
                'definition' => 'Wisdom, intelligence, sagacity',
                'sentences' => ['___结晶。', '___城市。', '___人生。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '理想',
                'pinyin' => 'lǐ xiǎng',
                'simplified' => '理想',
                'traditional' => '理想',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Ideal / Dream',
                'meaning_zh' => '理想',
                'example_sentence' => '要有理想和目标。',
                'example_translation' => 'Need to have ideals and goals.',
                'definition' => 'Ideal, dream, perfect',
                'sentences' => ['___主义。', '___状态。', '___实现。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '信念',
                'pinyin' => 'xìn niàn',
                'simplified' => '信念',
                'traditional' => '信念',
                'part_of_speech' => 'noun',
                'meaning' => 'Belief / Faith / Conviction',
                'meaning_zh' => '信念',
                'example_sentence' => '要坚定信念。',
                'example_translation' => 'Need to maintain firm beliefs.',
                'definition' => 'Belief, faith, conviction',
                'sentences' => ['___坚定。', '___支撑。', '___力量。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '道德',
                'pinyin' => 'dào dé',
                'simplified' => '道德',
                'traditional' => '道德',
                'part_of_speech' => 'noun',
                'meaning' => 'Morality / Ethics',
                'meaning_zh' => '道德',
                'example_sentence' => '要有道德观念。',
                'example_translation' => 'Need to have moral concepts.',
                'definition' => 'Morality, ethics, virtue',
                'sentences' => ['___标准。', '___品质。', '___底线。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '品德',
                'pinyin' => 'pǐn dé',
                'simplified' => '品德',
                'traditional' => '品德',
                'part_of_speech' => 'noun',
                'meaning' => 'Moral character / Virtue',
                'meaning_zh' => '品德',
                'example_sentence' => '他品德高尚。',
                'example_translation' => 'His moral character is noble.',
                'definition' => 'Moral character, virtue, integrity',
                'sentences' => ['___教育。', '___修养。', '___良好。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '修养',
                'pinyin' => 'xiū yǎng',
                'simplified' => '修养',
                'traditional' => '修養',
                'part_of_speech' => 'noun',
                'meaning' => 'Cultivation / Refinement',
                'meaning_zh' => '修养',
                'example_sentence' => '他很有修养。',
                'example_translation' => 'He is very refined.',
                'definition' => 'Cultivation, refinement, self-cultivation',
                'sentences' => ['个人___。', '___提高。', '___素质。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '境界',
                'pinyin' => 'jìng jiè',
                'simplified' => '境界',
                'traditional' => '境界',
                'part_of_speech' => 'noun',
                'meaning' => 'Realm / State / Level',
                'meaning_zh' => '境界',
                'example_sentence' => '他达到了很高的境界。',
                'example_translation' => 'He has reached a very high level.',
                'definition' => 'Realm, state, level of attainment',
                'sentences' => ['___高。', '___提升。', '___不同。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '觉悟',
                'pinyin' => 'jué wù',
                'simplified' => '觉悟',
                'traditional' => '覺悟',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Consciousness / Awareness / To become aware',
                'meaning_zh' => '觉悟',
                'example_sentence' => '他的觉悟很高。',
                'example_translation' => 'His consciousness is very high.',
                'definition' => 'Consciousness, awareness, to become aware',
                'sentences' => ['___提高。', '___性。', '___水平。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '感悟',
                'pinyin' => 'gǎn wù',
                'simplified' => '感悟',
                'traditional' => '感悟',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To comprehend / Insight',
                'meaning_zh' => '感悟',
                'example_sentence' => '我有很多感悟。',
                'example_translation' => 'I have many insights.',
                'definition' => 'To comprehend, insight, realization',
                'sentences' => ['人生___。', '___深刻。', '___分享。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '领悟',
                'pinyin' => 'lǐng wù',
                'simplified' => '领悟',
                'traditional' => '領悟',
                'part_of_speech' => 'verb',
                'meaning' => 'To comprehend / To grasp',
                'meaning_zh' => '领悟',
                'example_sentence' => '我终于领悟了这个道理。',
                'example_translation' => 'I finally comprehended this truth.',
                'definition' => 'To comprehend, to grasp, to understand',
                'sentences' => ['___能力。', '___道理。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '启发',
                'pinyin' => 'qǐ fā',
                'simplified' => '启发',
                'traditional' => '啟發',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To inspire / Inspiration',
                'meaning_zh' => '启发',
                'example_sentence' => '这本书给了我很大启发。',
                'example_translation' => 'This book gave me great inspiration.',
                'definition' => 'To inspire, inspiration, enlightenment',
                'sentences' => ['___思维。', '___教育。', '___作用。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '观念',
                'pinyin' => 'guān niàn',
                'simplified' => '观念',
                'traditional' => '觀念',
                'part_of_speech' => 'noun',
                'meaning' => 'Concept / Idea / View',
                'meaning_zh' => '观念',
                'example_sentence' => '观念要更新。',
                'example_translation' => 'Concepts need to be updated.',
                'definition' => 'Concept, idea, view, notion',
                'sentences' => ['___转变。', '___更新。', '___差异。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '态度',
                'pinyin' => 'tài du',
                'simplified' => '态度',
                'traditional' => '態度',
                'part_of_speech' => 'noun',
                'meaning' => 'Attitude',
                'meaning_zh' => '态度',
                'example_sentence' => '态度决定一切。',
                'example_translation' => 'Attitude determines everything.',
                'definition' => 'Attitude, manner, approach',
                'sentences' => ['___端正。', '___认真。', '___积极。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '精神',
                'pinyin' => 'jīng shén',
                'simplified' => '精神',
                'traditional' => '精神',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Spirit / Mental / Energetic',
                'meaning_zh' => '精神',
                'example_sentence' => '要有奉献精神。',
                'example_translation' => 'Need to have a spirit of dedication.',
                'definition' => 'Spirit, mental, mind, energetic',
                'sentences' => ['___状态。', '___面貌。', '___文明。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '意志',
                'pinyin' => 'yì zhì',
                'simplified' => '意志',
                'traditional' => '意志',
                'part_of_speech' => 'noun',
                'meaning' => 'Will / Willpower',
                'meaning_zh' => '意志',
                'example_sentence' => '他意志坚强。',
                'example_translation' => 'He has strong willpower.',
                'definition' => 'Will, willpower, determination',
                'sentences' => ['___力。', '___坚定。', '___品质。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 139,
                'word' => '自律',
                'pinyin' => 'zì lǜ',
                'simplified' => '自律',
                'traditional' => '自律',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Self-discipline',
                'meaning_zh' => '自律',
                'example_sentence' => '要学会自律。',
                'example_translation' => 'Need to learn self-discipline.',
                'definition' => 'Self-discipline, self-control',
                'sentences' => ['___能力。', '___精神。', '___严格。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 140: Social Issues - 社会问题
        $socialVocab = [
            [
                'topic_id' => 140,
                'word' => '社会',
                'pinyin' => 'shè huì',
                'simplified' => '社会',
                'traditional' => '社會',
                'part_of_speech' => 'noun',
                'meaning' => 'Society / Social',
                'meaning_zh' => '社会',
                'example_sentence' => '社会问题很复杂。',
                'example_translation' => 'Social issues are very complex.',
                'definition' => 'Society, social',
                'sentences' => ['___发展。', '___责任。', '___现象。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '问题',
                'pinyin' => 'wèn tí',
                'simplified' => '问题',
                'traditional' => '問題',
                'part_of_speech' => 'noun',
                'meaning' => 'Problem / Issue / Question',
                'meaning_zh' => '问题',
                'example_sentence' => '这是一个严重的问题。',
                'example_translation' => 'This is a serious problem.',
                'definition' => 'Problem, issue, question',
                'sentences' => ['___解决。', '___分析。', '___关键。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '环境污染',
                'pinyin' => 'huán jìng wū rǎn',
                'simplified' => '环境污染',
                'traditional' => '環境污染',
                'part_of_speech' => 'noun',
                'meaning' => 'Environmental pollution',
                'meaning_zh' => '环境污染',
                'example_sentence' => '环境污染很严重。',
                'example_translation' => 'Environmental pollution is very serious.',
                'definition' => 'Environmental pollution',
                'sentences' => ['___治理。', '___防治。', '___问题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '老龄化',
                'pinyin' => 'lǎo líng huà',
                'simplified' => '老龄化',
                'traditional' => '老齡化',
                'part_of_speech' => 'noun',
                'meaning' => 'Aging / Ageing',
                'meaning_zh' => '老龄化',
                'example_sentence' => '人口老龄化是个问题。',
                'example_translation' => 'Population aging is a problem.',
                'definition' => 'Aging, demographic aging',
                'sentences' => ['___社会。', '___问题。', '___趋势。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '贫富差距',
                'pinyin' => 'pín fù chā jù',
                'simplified' => '贫富差距',
                'traditional' => '貧富差距',
                'part_of_speech' => 'noun',
                'meaning' => 'Wealth gap / Income inequality',
                'meaning_zh' => '贫富差距',
                'example_sentence' => '贫富差距越来越大。',
                'example_translation' => 'The wealth gap is getting bigger.',
                'definition' => 'Wealth gap, income inequality',
                'sentences' => ['___扩大。', '___缩小。', '___问题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '就业',
                'pinyin' => 'jiù yè',
                'simplified' => '就业',
                'traditional' => '就業',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Employment / To get employed',
                'meaning_zh' => '就业',
                'example_sentence' => '就业压力很大。',
                'example_translation' => 'Employment pressure is very high.',
                'definition' => 'Employment, to get employed',
                'sentences' => ['___机会。', '___率。', '___难。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '公平',
                'pinyin' => 'gōng píng',
                'simplified' => '公平',
                'traditional' => '公平',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Fair / Fairness',
                'meaning_zh' => '公平',
                'example_sentence' => '要保证公平。',
                'example_translation' => 'Need to ensure fairness.',
                'definition' => 'Fair, fairness, impartial',
                'sentences' => ['___竞争。', '___正义。', '___对待。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '平等',
                'pinyin' => 'píng děng',
                'simplified' => '平等',
                'traditional' => '平等',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Equal / Equality',
                'meaning_zh' => '平等',
                'example_sentence' => '人人都应该平等。',
                'example_translation' => 'Everyone should be equal.',
                'definition' => 'Equal, equality',
                'sentences' => ['___权利。', '___对待。', '___机会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '歧视',
                'pinyin' => 'qí shì',
                'simplified' => '歧视',
                'traditional' => '歧視',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Discrimination / To discriminate',
                'meaning_zh' => '歧视',
                'example_sentence' => '不应该歧视别人。',
                'example_translation' => 'Should not discriminate against others.',
                'definition' => 'Discrimination, to discriminate',
                'sentences' => ['___现象。', '___行为。', '反对___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '腐败',
                'pinyin' => 'fǔ bài',
                'simplified' => '腐败',
                'traditional' => '腐敗',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Corruption / Corrupt',
                'meaning_zh' => '腐败',
                'example_sentence' => '要打击腐败。',
                'example_translation' => 'Need to combat corruption.',
                'definition' => 'Corruption, corrupt, rotten',
                'sentences' => ['___现象。', '反___。', '___问题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '犯罪',
                'pinyin' => 'fàn zuì',
                'simplified' => '犯罪',
                'traditional' => '犯罪',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Crime / To commit a crime',
                'meaning_zh' => '犯罪',
                'example_sentence' => '要预防犯罪。',
                'example_translation' => 'Need to prevent crime.',
                'definition' => 'Crime, to commit a crime',
                'sentences' => ['___率。', '___行为。', '___分子。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '安全',
                'pinyin' => 'ān quán',
                'simplified' => '安全',
                'traditional' => '安全',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Safety / Safe / Security',
                'meaning_zh' => '安全',
                'example_sentence' => '安全第一。',
                'example_translation' => 'Safety first.',
                'definition' => 'Safety, safe, security',
                'sentences' => ['___问题。', '___措施。', '___保障。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '福利',
                'pinyin' => 'fú lì',
                'simplified' => '福利',
                'traditional' => '福利',
                'part_of_speech' => 'noun',
                'meaning' => 'Welfare / Benefits',
                'meaning_zh' => '福利',
                'example_sentence' => '公司福利很好。',
                'example_translation' => 'The company benefits are very good.',
                'definition' => 'Welfare, benefits, well-being',
                'sentences' => ['___制度。', '___待遇。', '___保障。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '医疗',
                'pinyin' => 'yī liáo',
                'simplified' => '医疗',
                'traditional' => '醫療',
                'part_of_speech' => 'noun',
                'meaning' => 'Medical treatment / Healthcare',
                'meaning_zh' => '医疗',
                'example_sentence' => '医疗费用很高。',
                'example_translation' => 'Medical costs are very high.',
                'definition' => 'Medical treatment, healthcare',
                'sentences' => ['___保险。', '___服务。', '___资源。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '养老',
                'pinyin' => 'yǎng lǎo',
                'simplified' => '养老',
                'traditional' => '養老',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Elderly care / Pension',
                'meaning_zh' => '养老',
                'example_sentence' => '养老问题很重要。',
                'example_translation' => 'Elderly care issues are very important.',
                'definition' => 'Elderly care, pension, to support the elderly',
                'sentences' => ['___院。', '___保险。', '___金。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '慈善',
                'pinyin' => 'cí shàn',
                'simplified' => '慈善',
                'traditional' => '慈善',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Charity / Charitable',
                'meaning_zh' => '慈善',
                'example_sentence' => '他经常做慈善。',
                'example_translation' => 'He often does charity work.',
                'definition' => 'Charity, charitable, philanthropy',
                'sentences' => ['___活动。', '___机构。', '___捐款。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '志愿者',
                'pinyin' => 'zhì yuàn zhě',
                'simplified' => '志愿者',
                'traditional' => '志願者',
                'part_of_speech' => 'noun',
                'meaning' => 'Volunteer',
                'meaning_zh' => '志愿者',
                'example_sentence' => '他是一名志愿者。',
                'example_translation' => 'He is a volunteer.',
                'definition' => 'Volunteer',
                'sentences' => ['___服务。', '___活动。', '___精神。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '和谐',
                'pinyin' => 'hé xié',
                'simplified' => '和谐',
                'traditional' => '和諧',
                'part_of_speech' => 'adjective',
                'meaning' => 'Harmonious',
                'meaning_zh' => '和谐',
                'example_sentence' => '社会要和谐发展。',
                'example_translation' => 'Society should develop harmoniously.',
                'definition' => 'Harmonious, harmony',
                'sentences' => ['___社会。', '___相处。', '___发展。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '矛盾',
                'pinyin' => 'máo dùn',
                'simplified' => '矛盾',
                'traditional' => '矛盾',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Contradiction / Contradictory',
                'meaning_zh' => '矛盾',
                'example_sentence' => '要解决矛盾。',
                'example_translation' => 'Need to resolve contradictions.',
                'definition' => 'Contradiction, conflict, contradictory',
                'sentences' => ['___冲突。', '___化解。', '___心理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 140,
                'word' => '改革',
                'pinyin' => 'gǎi gé',
                'simplified' => '改革',
                'traditional' => '改革',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Reform / To reform',
                'meaning_zh' => '改革',
                'example_sentence' => '需要深化改革。',
                'example_translation' => 'Need to deepen reforms.',
                'definition' => 'Reform, to reform',
                'sentences' => ['___开放。', '___措施。', '___创新。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 141: Science and Technology - 科学与技术
        $technologyVocab = [
            [
                'topic_id' => 141,
                'word' => '科学',
                'pinyin' => 'kē xué',
                'simplified' => '科学',
                'traditional' => '科學',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Science / Scientific',
                'meaning_zh' => '科学',
                'example_sentence' => '科学技术很发达。',
                'example_translation' => 'Science and technology are very advanced.',
                'definition' => 'Science, scientific',
                'sentences' => ['___研究。', '___家。', '___发展。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '技术',
                'pinyin' => 'jì shù',
                'simplified' => '技术',
                'traditional' => '技術',
                'part_of_speech' => 'noun',
                'meaning' => 'Technology / Technique',
                'meaning_zh' => '技术',
                'example_sentence' => '这项技术很先进。',
                'example_translation' => 'This technology is very advanced.',
                'definition' => 'Technology, technique, skill',
                'sentences' => ['___创新。', '___发展。', '___人员。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '人工智能',
                'pinyin' => 'rén gōng zhì néng',
                'simplified' => '人工智能',
                'traditional' => '人工智能',
                'part_of_speech' => 'noun',
                'meaning' => 'Artificial intelligence / AI',
                'meaning_zh' => '人工智能',
                'example_sentence' => '人工智能发展很快。',
                'example_translation' => 'Artificial intelligence is developing rapidly.',
                'definition' => 'Artificial intelligence, AI',
                'sentences' => ['___技术。', '___应用。', '___时代。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '互联网',
                'pinyin' => 'hù lián wǎng',
                'simplified' => '互联网',
                'traditional' => '互聯網',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet',
                'meaning_zh' => '互联网',
                'example_sentence' => '互联网改变了生活。',
                'example_translation' => 'The Internet has changed life.',
                'definition' => 'Internet, web',
                'sentences' => ['___时代。', '___技术。', '___公司。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '网络',
                'pinyin' => 'wǎng luò',
                'simplified' => '网络',
                'traditional' => '網絡',
                'part_of_speech' => 'noun',
                'meaning' => 'Network / Internet',
                'meaning_zh' => '网络',
                'example_sentence' => '网络很方便。',
                'example_translation' => 'The internet is very convenient.',
                'definition' => 'Network, internet, web',
                'sentences' => ['___安全。', '___平台。', '___技术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '机器人',
                'pinyin' => 'jī qì rén',
                'simplified' => '机器人',
                'traditional' => '機器人',
                'part_of_speech' => 'noun',
                'meaning' => 'Robot',
                'meaning_zh' => '机器人',
                'example_sentence' => '机器人可以做很多事。',
                'example_translation' => 'Robots can do many things.',
                'definition' => 'Robot, android',
                'sentences' => ['___技术。', '___服务。', '___时代。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '芯片',
                'pinyin' => 'xīn piàn',
                'simplified' => '芯片',
                'traditional' => '芯片',
                'part_of_speech' => 'noun',
                'meaning' => 'Chip / Microchip',
                'meaning_zh' => '芯片',
                'example_sentence' => '芯片技术很重要。',
                'example_translation' => 'Chip technology is very important.',
                'definition' => 'Chip, microchip, integrated circuit',
                'sentences' => ['___制造。', '___技术。', '___产业。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '数据',
                'pinyin' => 'shù jù',
                'simplified' => '数据',
                'traditional' => '數據',
                'part_of_speech' => 'noun',
                'meaning' => 'Data',
                'meaning_zh' => '数据',
                'example_sentence' => '数据很重要。',
                'example_translation' => 'Data is very important.',
                'definition' => 'Data, statistics',
                'sentences' => ['___分析。', '___库。', '___安全。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '软件',
                'pinyin' => 'ruǎn jiàn',
                'simplified' => '软件',
                'traditional' => '軟件',
                'part_of_speech' => 'noun',
                'meaning' => 'Software',
                'meaning_zh' => '软件',
                'example_sentence' => '这个软件很好用。',
                'example_translation' => 'This software is very easy to use.',
                'definition' => 'Software, program',
                'sentences' => ['___开发。', '___工程师。', '___系统。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '硬件',
                'pinyin' => 'yìng jiàn',
                'simplified' => '硬件',
                'traditional' => '硬件',
                'part_of_speech' => 'noun',
                'meaning' => 'Hardware',
                'meaning_zh' => '硬件',
                'example_sentence' => '硬件设备很先进。',
                'example_translation' => 'The hardware equipment is very advanced.',
                'definition' => 'Hardware, physical equipment',
                'sentences' => ['___设施。', '___设备。', '___条件。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '编程',
                'pinyin' => 'biān chéng',
                'simplified' => '编程',
                'traditional' => '編程',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Programming / To program',
                'meaning_zh' => '编程',
                'example_sentence' => '我在学编程。',
                'example_translation' => 'I am learning programming.',
                'definition' => 'Programming, to program, coding',
                'sentences' => ['___语言。', '___技术。', '___学习。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '创新',
                'pinyin' => 'chuàng xīn',
                'simplified' => '创新',
                'traditional' => '創新',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Innovation / To innovate',
                'meaning_zh' => '创新',
                'example_sentence' => '科技需要创新。',
                'example_translation' => 'Technology needs innovation.',
                'definition' => 'Innovation, to innovate',
                'sentences' => ['___能力。', '___精神。', '___发展。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '发明',
                'pinyin' => 'fā míng',
                'simplified' => '发明',
                'traditional' => '發明',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Invention / To invent',
                'meaning_zh' => '发明',
                'example_sentence' => '这是一项伟大的发明。',
                'example_translation' => 'This is a great invention.',
                'definition' => 'Invention, to invent',
                'sentences' => ['___家。', '___创造。', '___专利。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '研发',
                'pinyin' => 'yán fā',
                'simplified' => '研发',
                'traditional' => '研發',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Research and development / R&D',
                'meaning_zh' => '研发',
                'example_sentence' => '公司注重研发。',
                'example_translation' => 'The company emphasizes R&D.',
                'definition' => 'Research and development, R&D',
                'sentences' => ['___中心。', '___团队。', '___投入。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '突破',
                'pinyin' => 'tū pò',
                'simplified' => '突破',
                'traditional' => '突破',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Breakthrough / To break through',
                'meaning_zh' => '突破',
                'example_sentence' => '技术有了新突破。',
                'example_translation' => 'There has been a new technological breakthrough.',
                'definition' => 'Breakthrough, to break through',
                'sentences' => ['___性。', '___口。', '___创新。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '应用',
                'pinyin' => 'yìng yòng',
                'simplified' => '应用',
                'traditional' => '應用',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Application / To apply',
                'meaning_zh' => '应用',
                'example_sentence' => '技术应用很广泛。',
                'example_translation' => 'Technology applications are very extensive.',
                'definition' => 'Application, to apply, to use',
                'sentences' => ['___程序。', '___广泛。', '___技术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '智能',
                'pinyin' => 'zhì néng',
                'simplified' => '智能',
                'traditional' => '智能',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Intelligence / Intelligent',
                'meaning_zh' => '智能',
                'example_sentence' => '智能手机很普及。',
                'example_translation' => 'Smartphones are very popular.',
                'definition' => 'Intelligence, intelligent, smart',
                'sentences' => ['___化。', '___设备。', '___系统。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '电子',
                'pinyin' => 'diàn zǐ',
                'simplified' => '电子',
                'traditional' => '電子',
                'part_of_speech' => 'noun',
                'meaning' => 'Electronic / Electronics',
                'meaning_zh' => '电子',
                'example_sentence' => '电子产品很多。',
                'example_translation' => 'There are many electronic products.',
                'definition' => 'Electronic, electronics, electron',
                'sentences' => ['___产品。', '___商务。', '___邮件。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '虚拟',
                'pinyin' => 'xū nǐ',
                'simplified' => '虚拟',
                'traditional' => '虛擬',
                'part_of_speech' => 'adjective',
                'meaning' => 'Virtual',
                'meaning_zh' => '虚拟',
                'example_sentence' => '虚拟现实技术很先进。',
                'example_translation' => 'Virtual reality technology is very advanced.',
                'definition' => 'Virtual, simulated',
                'sentences' => ['___世界。', '___现实。', '___技术。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 141,
                'word' => '数字化',
                'pinyin' => 'shù zì huà',
                'simplified' => '数字化',
                'traditional' => '數字化',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Digitalization / Digital',
                'meaning_zh' => '数字化',
                'example_sentence' => '社会正在数字化。',
                'example_translation' => 'Society is being digitalized.',
                'definition' => 'Digitalization, digital transformation',
                'sentences' => ['___时代。', '___转型。', '___管理。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($popCultureVocab, $philosophyVocab, $socialVocab, $technologyVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
