<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic123to125Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [123, 125])->delete();

        // Topic 123: Family and Relationships - 家庭与关系
        $familyVocab = [
            [
                'topic_id' => 123,
                'word' => '父母',
                'pinyin' => 'fù mǔ',
                'simplified' => '父母',
                'traditional' => '父母',
                'part_of_speech' => 'noun',
                'meaning' => 'Parents',
                'meaning_zh' => '父母',
                'example_sentence' => '父母很关心我的学习。',
                'example_translation' => 'My parents care a lot about my studies.',
                'definition' => 'Parents, father and mother',
                'sentences' => ['___很关心我。', '孝敬___。', '___的爱。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '亲戚',
                'pinyin' => 'qīn qi',
                'simplified' => '亲戚',
                'traditional' => '親戚',
                'part_of_speech' => 'noun',
                'meaning' => 'Relatives',
                'meaning_zh' => '亲戚',
                'example_sentence' => '春节我要去看望亲戚。',
                'example_translation' => 'I will visit relatives during Spring Festival.',
                'definition' => 'Relatives, family members',
                'sentences' => ['远房___。', '看望___。', '___关系。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '夫妻',
                'pinyin' => 'fū qī',
                'simplified' => '夫妻',
                'traditional' => '夫妻',
                'part_of_speech' => 'noun',
                'meaning' => 'Husband and wife / Couple',
                'meaning_zh' => '夫妻',
                'example_sentence' => '他们是一对恩爱的夫妻。',
                'example_translation' => 'They are a loving couple.',
                'definition' => 'Husband and wife, married couple',
                'sentences' => ['___关系。', '___生活。', '___和睦。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '婆婆',
                'pinyin' => 'pó po',
                'simplified' => '婆婆',
                'traditional' => '婆婆',
                'part_of_speech' => 'noun',
                'meaning' => 'Mother-in-law (husband\'s mother)',
                'meaning_zh' => '婆婆',
                'example_sentence' => '我婆婆对我很好。',
                'example_translation' => 'My mother-in-law is very good to me.',
                'definition' => 'Mother-in-law (husband\'s mother)',
                'sentences' => ['___很疼我。', '孝顺___。', '___家。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '岳父',
                'pinyin' => 'yuè fù',
                'simplified' => '岳父',
                'traditional' => '岳父',
                'part_of_speech' => 'noun',
                'meaning' => 'Father-in-law (wife\'s father)',
                'meaning_zh' => '岳父',
                'example_sentence' => '岳父是一位教授。',
                'example_translation' => 'My father-in-law is a professor.',
                'definition' => 'Father-in-law (wife\'s father)',
                'sentences' => ['拜访___。', '___大人。', '___岳母。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '儿媳',
                'pinyin' => 'ér xí',
                'simplified' => '儿媳',
                'traditional' => '兒媳',
                'part_of_speech' => 'noun',
                'meaning' => 'Daughter-in-law',
                'meaning_zh' => '儿媳',
                'example_sentence' => '她是个孝顺的儿媳。',
                'example_translation' => 'She is a filial daughter-in-law.',
                'definition' => 'Daughter-in-law',
                'sentences' => ['___妇。', '孝顺的___。', '___关系。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '女婿',
                'pinyin' => 'nǚ xu',
                'simplified' => '女婿',
                'traditional' => '女婿',
                'part_of_speech' => 'noun',
                'meaning' => 'Son-in-law',
                'meaning_zh' => '女婿',
                'example_sentence' => '我们的女婿很能干。',
                'example_translation' => 'Our son-in-law is very capable.',
                'definition' => 'Son-in-law',
                'sentences' => ['好___。', '___很优秀。', '招___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '亲情',
                'pinyin' => 'qīn qíng',
                'simplified' => '亲情',
                'traditional' => '親情',
                'part_of_speech' => 'noun',
                'meaning' => 'Family affection',
                'meaning_zh' => '亲情',
                'example_sentence' => '亲情是最珍贵的。',
                'example_translation' => 'Family affection is the most precious.',
                'definition' => 'Family affection, kinship',
                'sentences' => ['___无价。', '珍惜___。', '___纽带。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '代沟',
                'pinyin' => 'dài gōu',
                'simplified' => '代沟',
                'traditional' => '代溝',
                'part_of_speech' => 'noun',
                'meaning' => 'Generation gap',
                'meaning_zh' => '代沟',
                'example_sentence' => '父母和孩子之间有代沟。',
                'example_translation' => 'There is a generation gap between parents and children.',
                'definition' => 'Generation gap',
                'sentences' => ['存在___。', '消除___。', '___问题。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '抚养',
                'pinyin' => 'fǔ yǎng',
                'simplified' => '抚养',
                'traditional' => '撫養',
                'part_of_speech' => 'verb',
                'meaning' => 'To raise / To bring up',
                'meaning_zh' => '抚养',
                'example_sentence' => '父母抚养孩子长大。',
                'example_translation' => 'Parents raise their children to adulthood.',
                'definition' => 'To raise, to bring up, to nurture',
                'sentences' => ['___子女。', '___成人。', '___费。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '赡养',
                'pinyin' => 'shàn yǎng',
                'simplified' => '赡养',
                'traditional' => '贍養',
                'part_of_speech' => 'verb',
                'meaning' => 'To support (elderly parents)',
                'meaning_zh' => '赡养',
                'example_sentence' => '子女应该赡养父母。',
                'example_translation' => 'Children should support their elderly parents.',
                'definition' => 'To support elderly parents financially',
                'sentences' => ['___老人。', '___义务。', '___费。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '和睦',
                'pinyin' => 'hé mù',
                'simplified' => '和睦',
                'traditional' => '和睦',
                'part_of_speech' => 'adjective',
                'meaning' => 'Harmonious / Peaceful',
                'meaning_zh' => '和睦',
                'example_sentence' => '他们一家人相处得很和睦。',
                'example_translation' => 'Their family gets along very harmoniously.',
                'definition' => 'Harmonious, peaceful, amicable',
                'sentences' => ['___相处。', '家庭___。', '___气氛。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '矛盾',
                'pinyin' => 'máo dùn',
                'simplified' => '矛盾',
                'traditional' => '矛盾',
                'part_of_speech' => 'noun',
                'meaning' => 'Contradiction / Conflict',
                'meaning_zh' => '矛盾',
                'example_sentence' => '家庭矛盾需要沟通解决。',
                'example_translation' => 'Family conflicts need communication to resolve.',
                'definition' => 'Contradiction, conflict, inconsistency',
                'sentences' => ['___冲突。', '解决___。', '___重重。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '孝顺',
                'pinyin' => 'xiào shùn',
                'simplified' => '孝顺',
                'traditional' => '孝順',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Filial / Dutiful / To show filial piety',
                'meaning_zh' => '孝顺',
                'example_sentence' => '他是个孝顺的儿子。',
                'example_translation' => 'He is a filial son.',
                'definition' => 'Filial, dutiful, showing respect to parents',
                'sentences' => ['___父母。', '___的孩子。', '___之道。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '独生子女',
                'pinyin' => 'dú shēng zǐ nǚ',
                'simplified' => '独生子女',
                'traditional' => '獨生子女',
                'part_of_speech' => 'noun',
                'meaning' => 'Only child',
                'meaning_zh' => '独生子女',
                'example_sentence' => '独生子女的压力比较大。',
                'example_translation' => 'Only children face relatively greater pressure.',
                'definition' => 'Only child, single child',
                'sentences' => ['___政策。', '___家庭。', '___一代。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '隔代',
                'pinyin' => 'gé dài',
                'simplified' => '隔代',
                'traditional' => '隔代',
                'part_of_speech' => 'adjective',
                'meaning' => 'Of different generations',
                'meaning_zh' => '隔代',
                'example_sentence' => '隔代教育有优点也有缺点。',
                'example_translation' => 'Grandparent education has both advantages and disadvantages.',
                'definition' => 'Across generations, intergenerational',
                'sentences' => ['___抚养。', '___教育。', '___亲。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '血缘',
                'pinyin' => 'xuè yuán',
                'simplified' => '血缘',
                'traditional' => '血緣',
                'part_of_speech' => 'noun',
                'meaning' => 'Blood relationship',
                'meaning_zh' => '血缘',
                'example_sentence' => '他们之间有血缘关系。',
                'example_translation' => 'They have a blood relationship.',
                'definition' => 'Blood relationship, kinship by blood',
                'sentences' => ['___关系。', '___亲情。', '___纽带。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '团聚',
                'pinyin' => 'tuán jù',
                'simplified' => '团聚',
                'traditional' => '團聚',
                'part_of_speech' => 'verb',
                'meaning' => 'To reunite / To gather',
                'meaning_zh' => '团聚',
                'example_sentence' => '春节是家人团聚的时候。',
                'example_translation' => 'Spring Festival is a time for family reunions.',
                'definition' => 'To reunite, to gather together',
                'sentences' => ['全家___。', '___时刻。', '___饭。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '家庭教育',
                'pinyin' => 'jiā tíng jiào yù',
                'simplified' => '家庭教育',
                'traditional' => '家庭教育',
                'part_of_speech' => 'noun',
                'meaning' => 'Family education',
                'meaning_zh' => '家庭教育',
                'example_sentence' => '家庭教育非常重要。',
                'example_translation' => 'Family education is very important.',
                'definition' => 'Family education, home education',
                'sentences' => ['重视___。', '___方法。', '___理念。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 123,
                'word' => '继承',
                'pinyin' => 'jì chéng',
                'simplified' => '继承',
                'traditional' => '繼承',
                'part_of_speech' => 'verb',
                'meaning' => 'To inherit / To carry on',
                'meaning_zh' => '继承',
                'example_sentence' => '他继承了父亲的事业。',
                'example_translation' => 'He inherited his father\'s business.',
                'definition' => 'To inherit, to carry on, to succeed',
                'sentences' => ['___遗产。', '___传统。', '___人。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 124: Marriage and Love - 婚姻与爱情
        $marriageVocab = [
            [
                'topic_id' => 124,
                'word' => '恋爱',
                'pinyin' => 'liàn ài',
                'simplified' => '恋爱',
                'traditional' => '戀愛',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To be in love / Romance',
                'meaning_zh' => '恋爱',
                'example_sentence' => '他们正在恋爱。',
                'example_translation' => 'They are in a relationship.',
                'definition' => 'To be in love, romance, dating',
                'sentences' => ['自由___。', '___关系。', '谈___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '爱情',
                'pinyin' => 'ài qíng',
                'simplified' => '爱情',
                'traditional' => '愛情',
                'part_of_speech' => 'noun',
                'meaning' => 'Love / Romance',
                'meaning_zh' => '爱情',
                'example_sentence' => '爱情需要经营。',
                'example_translation' => 'Love needs to be nurtured.',
                'definition' => 'Love, romantic love',
                'sentences' => ['真挚的___。', '___故事。', '___观。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '婚姻',
                'pinyin' => 'hūn yīn',
                'simplified' => '婚姻',
                'traditional' => '婚姻',
                'part_of_speech' => 'noun',
                'meaning' => 'Marriage',
                'meaning_zh' => '婚姻',
                'example_sentence' => '婚姻是人生大事。',
                'example_translation' => 'Marriage is a major life event.',
                'definition' => 'Marriage, matrimony',
                'sentences' => ['___生活。', '___法。', '___状况。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '结婚',
                'pinyin' => 'jié hūn',
                'simplified' => '结婚',
                'traditional' => '結婚',
                'part_of_speech' => 'verb',
                'meaning' => 'To get married / To marry',
                'meaning_zh' => '结婚',
                'example_sentence' => '他们打算明年结婚。',
                'example_translation' => 'They plan to get married next year.',
                'definition' => 'To get married, to marry',
                'sentences' => ['___证。', '___了。', '___典礼。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '离婚',
                'pinyin' => 'lí hūn',
                'simplified' => '离婚',
                'traditional' => '離婚',
                'part_of_speech' => 'verb',
                'meaning' => 'To divorce / To get divorced',
                'meaning_zh' => '离婚',
                'example_sentence' => '他们去年离婚了。',
                'example_translation' => 'They got divorced last year.',
                'definition' => 'To divorce, to get divorced',
                'sentences' => ['___率。', '协议___。', '___证。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '求婚',
                'pinyin' => 'qiú hūn',
                'simplified' => '求婚',
                'traditional' => '求婚',
                'part_of_speech' => 'verb',
                'meaning' => 'To propose marriage',
                'meaning_zh' => '求婚',
                'example_sentence' => '他昨天向她求婚了。',
                'example_translation' => 'He proposed to her yesterday.',
                'definition' => 'To propose marriage, to propose',
                'sentences' => ['___戒指。', '___仪式。', '___成功。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '订婚',
                'pinyin' => 'dìng hūn',
                'simplified' => '订婚',
                'traditional' => '訂婚',
                'part_of_speech' => 'verb',
                'meaning' => 'To get engaged',
                'meaning_zh' => '订婚',
                'example_sentence' => '他们已经订婚了。',
                'example_translation' => 'They are already engaged.',
                'definition' => 'To get engaged, engagement',
                'sentences' => ['___仪式。', '___戒指。', '___宴。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '婚礼',
                'pinyin' => 'hūn lǐ',
                'simplified' => '婚礼',
                'traditional' => '婚禮',
                'part_of_speech' => 'noun',
                'meaning' => 'Wedding ceremony',
                'meaning_zh' => '婚礼',
                'example_sentence' => '婚礼将在酒店举行。',
                'example_translation' => 'The wedding will be held at a hotel.',
                'definition' => 'Wedding ceremony, wedding',
                'sentences' => ['举办___。', '___现场。', '___策划。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '新郎',
                'pinyin' => 'xīn láng',
                'simplified' => '新郎',
                'traditional' => '新郎',
                'part_of_speech' => 'noun',
                'meaning' => 'Bridegroom / Groom',
                'meaning_zh' => '新郎',
                'example_sentence' => '新郎穿着黑色西装。',
                'example_translation' => 'The groom is wearing a black suit.',
                'definition' => 'Bridegroom, groom',
                'sentences' => ['___官。', '___新娘。', '___致辞。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '新娘',
                'pinyin' => 'xīn niáng',
                'simplified' => '新娘',
                'traditional' => '新娘',
                'part_of_speech' => 'noun',
                'meaning' => 'Bride',
                'meaning_zh' => '新娘',
                'example_sentence' => '新娘穿着白色婚纱。',
                'example_translation' => 'The bride is wearing a white wedding dress.',
                'definition' => 'Bride',
                'sentences' => ['美丽的___。', '___妆。', '___捧花。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '蜜月',
                'pinyin' => 'mì yuè',
                'simplified' => '蜜月',
                'traditional' => '蜜月',
                'part_of_speech' => 'noun',
                'meaning' => 'Honeymoon',
                'meaning_zh' => '蜜月',
                'example_sentence' => '他们去巴黎度蜜月。',
                'example_translation' => 'They went to Paris for their honeymoon.',
                'definition' => 'Honeymoon',
                'sentences' => ['度___。', '___旅行。', '___期。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '单身',
                'pinyin' => 'dān shēn',
                'simplified' => '单身',
                'traditional' => '單身',
                'part_of_speech' => 'adjective',
                'meaning' => 'Single / Unmarried',
                'meaning_zh' => '单身',
                'example_sentence' => '他还是单身。',
                'example_translation' => 'He is still single.',
                'definition' => 'Single, unmarried, unattached',
                'sentences' => ['___汉。', '___贵族。', '___公寓。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '恋人',
                'pinyin' => 'liàn rén',
                'simplified' => '恋人',
                'traditional' => '戀人',
                'part_of_speech' => 'noun',
                'meaning' => 'Lover / Sweetheart',
                'meaning_zh' => '恋人',
                'example_sentence' => '他们是一对恋人。',
                'example_translation' => 'They are lovers.',
                'definition' => 'Lover, sweetheart, romantic partner',
                'sentences' => ['___关系。', '___节。', '一对___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '初恋',
                'pinyin' => 'chū liàn',
                'simplified' => '初恋',
                'traditional' => '初戀',
                'part_of_speech' => 'noun',
                'meaning' => 'First love',
                'meaning_zh' => '初恋',
                'example_sentence' => '初恋是最难忘的。',
                'example_translation' => 'First love is the most unforgettable.',
                'definition' => 'First love',
                'sentences' => ['___情人。', '___记忆。', '___故事。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '情侣',
                'pinyin' => 'qíng lǚ',
                'simplified' => '情侣',
                'traditional' => '情侶',
                'part_of_speech' => 'noun',
                'meaning' => 'Couple / Lovers',
                'meaning_zh' => '情侣',
                'example_sentence' => '公园里有很多情侣。',
                'example_translation' => 'There are many couples in the park.',
                'definition' => 'Couple, lovers, romantic partners',
                'sentences' => ['___装。', '___头像。', '___套装。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '浪漫',
                'pinyin' => 'làng màn',
                'simplified' => '浪漫',
                'traditional' => '浪漫',
                'part_of_speech' => 'adjective',
                'meaning' => 'Romantic',
                'meaning_zh' => '浪漫',
                'example_sentence' => '他为她准备了浪漫的晚餐。',
                'example_translation' => 'He prepared a romantic dinner for her.',
                'definition' => 'Romantic',
                'sentences' => ['___主义。', '___的约会。', '___氛围。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '忠诚',
                'pinyin' => 'zhōng chéng',
                'simplified' => '忠诚',
                'traditional' => '忠誠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Loyal / Faithful',
                'meaning_zh' => '忠诚',
                'example_sentence' => '婚姻需要忠诚。',
                'example_translation' => 'Marriage requires loyalty.',
                'definition' => 'Loyal, faithful, devoted',
                'sentences' => ['___可靠。', '___度。', '___的伙伴。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '背叛',
                'pinyin' => 'bèi pàn',
                'simplified' => '背叛',
                'traditional' => '背叛',
                'part_of_speech' => 'verb',
                'meaning' => 'To betray',
                'meaning_zh' => '背叛',
                'example_sentence' => '背叛会伤害感情。',
                'example_translation' => 'Betrayal hurts relationships.',
                'definition' => 'To betray, betrayal',
                'sentences' => ['___者。', '___信任。', '遭到___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '分手',
                'pinyin' => 'fēn shǒu',
                'simplified' => '分手',
                'traditional' => '分手',
                'part_of_speech' => 'verb',
                'meaning' => 'To break up',
                'meaning_zh' => '分手',
                'example_sentence' => '他们已经分手了。',
                'example_translation' => 'They have already broken up.',
                'definition' => 'To break up, to split up',
                'sentences' => ['和平___。', '___了。', '___费。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 124,
                'word' => '婚姻观',
                'pinyin' => 'hūn yīn guān',
                'simplified' => '婚姻观',
                'traditional' => '婚姻觀',
                'part_of_speech' => 'noun',
                'meaning' => 'Views on marriage',
                'meaning_zh' => '婚姻观',
                'example_sentence' => '每个人的婚姻观都不同。',
                'example_translation' => 'Everyone has different views on marriage.',
                'definition' => 'Views on marriage, marriage values',
                'sentences' => ['传统___。', '___念。', '现代___。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 125: Urban and Rural Life - 城市与农村生活
        $urbanRuralVocab = [
            [
                'topic_id' => 125,
                'word' => '城市',
                'pinyin' => 'chéng shì',
                'simplified' => '城市',
                'traditional' => '城市',
                'part_of_speech' => 'noun',
                'meaning' => 'City',
                'meaning_zh' => '城市',
                'example_sentence' => '我在城市工作。',
                'example_translation' => 'I work in the city.',
                'definition' => 'City, urban area',
                'sentences' => ['___生活。', '大___。', '___化。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '农村',
                'pinyin' => 'nóng cūn',
                'simplified' => '农村',
                'traditional' => '農村',
                'part_of_speech' => 'noun',
                'meaning' => 'Rural area / Countryside',
                'meaning_zh' => '农村',
                'example_sentence' => '我从农村来到城市。',
                'example_translation' => 'I came to the city from the countryside.',
                'definition' => 'Rural area, countryside, village',
                'sentences' => ['___地区。', '___户口。', '___建设。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '乡村',
                'pinyin' => 'xiāng cūn',
                'simplified' => '乡村',
                'traditional' => '鄉村',
                'part_of_speech' => 'noun',
                'meaning' => 'Village / Countryside',
                'meaning_zh' => '乡村',
                'example_sentence' => '乡村生活很安静。',
                'example_translation' => 'Village life is very quiet.',
                'definition' => 'Village, countryside, rural area',
                'sentences' => ['___振兴。', '___旅游。', '___风光。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '都市',
                'pinyin' => 'dū shì',
                'simplified' => '都市',
                'traditional' => '都市',
                'part_of_speech' => 'noun',
                'meaning' => 'Metropolis / Big city',
                'meaning_zh' => '都市',
                'example_sentence' => '都市生活节奏很快。',
                'example_translation' => 'Metropolitan life has a fast pace.',
                'definition' => 'Metropolis, big city, urban',
                'sentences' => ['___人。', '___圈。', '现代___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '郊区',
                'pinyin' => 'jiāo qū',
                'simplified' => '郊区',
                'traditional' => '郊區',
                'part_of_speech' => 'noun',
                'meaning' => 'Suburb / Outskirts',
                'meaning_zh' => '郊区',
                'example_sentence' => '他住在郊区。',
                'example_translation' => 'He lives in the suburbs.',
                'definition' => 'Suburb, outskirts, suburban area',
                'sentences' => ['城市___。', '___房子。', '___生活。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '城镇',
                'pinyin' => 'chéng zhèn',
                'simplified' => '城镇',
                'traditional' => '城鎮',
                'part_of_speech' => 'noun',
                'meaning' => 'Town / Township',
                'meaning_zh' => '城镇',
                'example_sentence' => '这是一个小城镇。',
                'example_translation' => 'This is a small town.',
                'definition' => 'Town, township, small city',
                'sentences' => ['___化。', '___居民。', '___建设。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '城乡',
                'pinyin' => 'chéng xiāng',
                'simplified' => '城乡',
                'traditional' => '城鄉',
                'part_of_speech' => 'noun',
                'meaning' => 'Urban and rural',
                'meaning_zh' => '城乡',
                'example_sentence' => '城乡差距正在缩小。',
                'example_translation' => 'The urban-rural gap is narrowing.',
                'definition' => 'Urban and rural, city and countryside',
                'sentences' => ['___差距。', '___结合。', '___发展。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '繁华',
                'pinyin' => 'fán huá',
                'simplified' => '繁华',
                'traditional' => '繁華',
                'part_of_speech' => 'adjective',
                'meaning' => 'Bustling / Prosperous',
                'meaning_zh' => '繁华',
                'example_sentence' => '这是一条繁华的街道。',
                'example_translation' => 'This is a bustling street.',
                'definition' => 'Bustling, prosperous, flourishing',
                'sentences' => ['___地段。', '___商业区。', '___都市。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '拥挤',
                'pinyin' => 'yōng jǐ',
                'simplified' => '拥挤',
                'traditional' => '擁擠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Crowded / Congested',
                'meaning_zh' => '拥挤',
                'example_sentence' => '早上地铁很拥挤。',
                'example_translation' => 'The subway is very crowded in the morning.',
                'definition' => 'Crowded, congested, packed',
                'sentences' => ['___不堪。', '人群___。', '交通___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '偏僻',
                'pinyin' => 'piān pì',
                'simplified' => '偏僻',
                'traditional' => '偏僻',
                'part_of_speech' => 'adjective',
                'meaning' => 'Remote / Out-of-the-way',
                'meaning_zh' => '偏僻',
                'example_sentence' => '那个村子很偏僻。',
                'example_translation' => 'That village is very remote.',
                'definition' => 'Remote, out-of-the-way, secluded',
                'sentences' => ['___地区。', '___的山村。', '位置___。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '宁静',
                'pinyin' => 'níng jìng',
                'simplified' => '宁静',
                'traditional' => '寧靜',
                'part_of_speech' => 'adjective',
                'meaning' => 'Peaceful / Tranquil',
                'meaning_zh' => '宁静',
                'example_sentence' => '乡村的夜晚很宁静。',
                'example_translation' => 'Rural nights are very peaceful.',
                'definition' => 'Peaceful, tranquil, quiet',
                'sentences' => ['___的环境。', '___安详。', '___的生活。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '喧闹',
                'pinyin' => 'xuān nào',
                'simplified' => '喧闹',
                'traditional' => '喧鬧',
                'part_of_speech' => 'adjective',
                'meaning' => 'Noisy / Bustling',
                'meaning_zh' => '喧闹',
                'example_sentence' => '城市很喧闹。',
                'example_translation' => 'The city is very noisy.',
                'definition' => 'Noisy, bustling, clamorous',
                'sentences' => ['___的街道。', '___声。', '___不堪。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '便利',
                'pinyin' => 'biàn lì',
                'simplified' => '便利',
                'traditional' => '便利',
                'part_of_speech' => 'adjective',
                'meaning' => 'Convenient / Handy',
                'meaning_zh' => '便利',
                'example_sentence' => '城市生活很便利。',
                'example_translation' => 'City life is very convenient.',
                'definition' => 'Convenient, handy, easy',
                'sentences' => ['交通___。', '___店。', '___条件。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '落后',
                'pinyin' => 'luò hòu',
                'simplified' => '落后',
                'traditional' => '落後',
                'part_of_speech' => 'adjective',
                'meaning' => 'Backward / Underdeveloped',
                'meaning_zh' => '落后',
                'example_sentence' => '一些农村地区还比较落后。',
                'example_translation' => 'Some rural areas are still relatively underdeveloped.',
                'definition' => 'Backward, underdeveloped, lagging behind',
                'sentences' => ['___地区。', '经济___。', '___面貌。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '发达',
                'pinyin' => 'fā dá',
                'simplified' => '发达',
                'traditional' => '發達',
                'part_of_speech' => 'adjective',
                'meaning' => 'Developed / Advanced',
                'meaning_zh' => '发达',
                'example_sentence' => '这是一个发达的城市。',
                'example_translation' => 'This is a developed city.',
                'definition' => 'Developed, advanced, prosperous',
                'sentences' => ['___国家。', '经济___。', '___地区。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '节奏',
                'pinyin' => 'jié zòu',
                'simplified' => '节奏',
                'traditional' => '節奏',
                'part_of_speech' => 'noun',
                'meaning' => 'Rhythm / Pace / Tempo',
                'meaning_zh' => '节奏',
                'example_sentence' => '城市的生活节奏很快。',
                'example_translation' => 'The pace of city life is very fast.',
                'definition' => 'Rhythm, pace, tempo',
                'sentences' => ['生活___。', '___感。', '___快。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '压力',
                'pinyin' => 'yā lì',
                'simplified' => '压力',
                'traditional' => '壓力',
                'part_of_speech' => 'noun',
                'meaning' => 'Pressure / Stress',
                'meaning_zh' => '压力',
                'example_sentence' => '城市人的压力很大。',
                'example_translation' => 'City people face a lot of pressure.',
                'definition' => 'Pressure, stress, strain',
                'sentences' => ['工作___。', '___大。', '___山大。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '污染',
                'pinyin' => 'wū rǎn',
                'simplified' => '污染',
                'traditional' => '污染',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Pollution / To pollute',
                'meaning_zh' => '污染',
                'example_sentence' => '城市的空气污染比较严重。',
                'example_translation' => 'Air pollution in the city is quite serious.',
                'definition' => 'Pollution, to pollute, contamination',
                'sentences' => ['环境___。', '___源。', '___物。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '基础设施',
                'pinyin' => 'jī chǔ shè shī',
                'simplified' => '基础设施',
                'traditional' => '基礎設施',
                'part_of_speech' => 'noun',
                'meaning' => 'Infrastructure',
                'meaning_zh' => '基础设施',
                'example_sentence' => '农村的基础设施需要改善。',
                'example_translation' => 'Rural infrastructure needs improvement.',
                'definition' => 'Infrastructure, basic facilities',
                'sentences' => ['完善___。', '___建设。', '___投资。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 125,
                'word' => '城市化',
                'pinyin' => 'chéng shì huà',
                'simplified' => '城市化',
                'traditional' => '城市化',
                'part_of_speech' => 'noun',
                'meaning' => 'Urbanization',
                'meaning_zh' => '城市化',
                'example_sentence' => '中国的城市化进程很快。',
                'example_translation' => 'China\'s urbanization process is very fast.',
                'definition' => 'Urbanization, urban development',
                'sentences' => ['___进程。', '___率。', '___发展。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($familyVocab, $marriageVocab, $urbanRuralVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
