<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK5Topic150to152Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [150, 152])->delete();

        // Topic 150: International Exchange and Study Abroad - 国际交流与留学
        $studyAbroadVocab = [
            [
                'topic_id' => 150,
                'word' => '留学',
                'pinyin' => 'liú xué',
                'simplified' => '留学',
                'traditional' => '留學',
                'part_of_speech' => 'verb',
                'meaning' => 'To study abroad',
                'meaning_zh' => '留学',
                'example_sentence' => '他去美国留学。',
                'example_translation' => 'He went to study in America.',
                'definition' => 'To study abroad, to study overseas',
                'sentences' => ['___生活。', '___申请。', '___经历。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '留学生',
                'pinyin' => 'liú xué shēng',
                'simplified' => '留学生',
                'traditional' => '留學生',
                'part_of_speech' => 'noun',
                'meaning' => 'International student',
                'meaning_zh' => '留学生',
                'example_sentence' => '他是留学生。',
                'example_translation' => 'He is an international student.',
                'definition' => 'International student, overseas student',
                'sentences' => ['___公寓。', '___活动。', '___联谊。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '交流',
                'pinyin' => 'jiāo liú',
                'simplified' => '交流',
                'traditional' => '交流',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To exchange / Communication',
                'meaning_zh' => '交流',
                'example_sentence' => '文化交流很重要。',
                'example_translation' => 'Cultural exchange is very important.',
                'definition' => 'To exchange, communication, interaction',
                'sentences' => ['___经验。', '___学习。', '___活动。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '交换',
                'pinyin' => 'jiāo huàn',
                'simplified' => '交换',
                'traditional' => '交換',
                'part_of_speech' => 'verb',
                'meaning' => 'To exchange / To swap',
                'meaning_zh' => '交换',
                'example_sentence' => '交换生项目。',
                'example_translation' => 'Exchange student program.',
                'definition' => 'To exchange, to swap, to interchange',
                'sentences' => ['___生。', '___意见。', '___礼物。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '申请',
                'pinyin' => 'shēn qǐng',
                'simplified' => '申请',
                'traditional' => '申請',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To apply / Application',
                'meaning_zh' => '申请',
                'example_sentence' => '申请奖学金。',
                'example_translation' => 'Apply for scholarship.',
                'definition' => 'To apply, application',
                'sentences' => ['___材料。', '___表格。', '___流程。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '录取',
                'pinyin' => 'lù qǔ',
                'simplified' => '录取',
                'traditional' => '錄取',
                'part_of_speech' => 'verb',
                'meaning' => 'To admit / To enroll',
                'meaning_zh' => '录取',
                'example_sentence' => '被大学录取了。',
                'example_translation' => 'Was admitted to university.',
                'definition' => 'To admit, to enroll, admission',
                'sentences' => ['___通知。', '___分数线。', '___名单。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '奖学金',
                'pinyin' => 'jiǎng xué jīn',
                'simplified' => '奖学金',
                'traditional' => '獎學金',
                'part_of_speech' => 'noun',
                'meaning' => 'Scholarship',
                'meaning_zh' => '奖学金',
                'example_sentence' => '获得奖学金。',
                'example_translation' => 'Received a scholarship.',
                'definition' => 'Scholarship, fellowship',
                'sentences' => ['___申请。', '___金额。', '___获得者。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '学费',
                'pinyin' => 'xué fèi',
                'simplified' => '学费',
                'traditional' => '學費',
                'part_of_speech' => 'noun',
                'meaning' => 'Tuition / Tuition fee',
                'meaning_zh' => '学费',
                'example_sentence' => '学费很贵。',
                'example_translation' => 'Tuition is very expensive.',
                'definition' => 'Tuition, tuition fee',
                'sentences' => ['___支付。', '___标准。', '___减免。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '宿舍',
                'pinyin' => 'sù shè',
                'simplified' => '宿舍',
                'traditional' => '宿舍',
                'part_of_speech' => 'noun',
                'meaning' => 'Dormitory',
                'meaning_zh' => '宿舍',
                'example_sentence' => '住在宿舍。',
                'example_translation' => 'Live in the dormitory.',
                'definition' => 'Dormitory, dorm',
                'sentences' => ['___楼。', '___生活。', '___管理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '室友',
                'pinyin' => 'shì yǒu',
                'simplified' => '室友',
                'traditional' => '室友',
                'part_of_speech' => 'noun',
                'meaning' => 'Roommate',
                'meaning_zh' => '室友',
                'example_sentence' => '我的室友很友好。',
                'example_translation' => 'My roommate is very friendly.',
                'definition' => 'Roommate',
                'sentences' => ['___关系。', '___相处。', '___聚会。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '语言障碍',
                'pinyin' => 'yǔ yán zhàng ài',
                'simplified' => '语言障碍',
                'traditional' => '語言障礙',
                'part_of_speech' => 'noun',
                'meaning' => 'Language barrier',
                'meaning_zh' => '语言障碍',
                'example_sentence' => '克服语言障碍。',
                'example_translation' => 'Overcome language barriers.',
                'definition' => 'Language barrier, language difficulty',
                'sentences' => ['___问题。', '___克服。', '___困难。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '文化冲击',
                'pinyin' => 'wén huà chōng jī',
                'simplified' => '文化冲击',
                'traditional' => '文化衝擊',
                'part_of_speech' => 'noun',
                'meaning' => 'Culture shock',
                'meaning_zh' => '文化冲击',
                'example_sentence' => '经历文化冲击。',
                'example_translation' => 'Experience culture shock.',
                'definition' => 'Culture shock, cultural impact',
                'sentences' => ['___适应。', '___过程。', '___感受。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '思乡',
                'pinyin' => 'sī xiāng',
                'simplified' => '思乡',
                'traditional' => '思鄉',
                'part_of_speech' => 'verb',
                'meaning' => 'To be homesick / Homesickness',
                'meaning_zh' => '思乡',
                'example_sentence' => '有点思乡。',
                'example_translation' => 'Feel a bit homesick.',
                'definition' => 'To be homesick, homesickness',
                'sentences' => ['___之情。', '___情绪。', '___想家。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '独立',
                'pinyin' => 'dú lì',
                'simplified' => '独立',
                'traditional' => '獨立',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Independent / To be independent',
                'meaning_zh' => '独立',
                'example_sentence' => '学会独立生活。',
                'example_translation' => 'Learn to live independently.',
                'definition' => 'Independent, to be independent',
                'sentences' => ['___自主。', '___能力。', '___思考。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '成长',
                'pinyin' => 'chéng zhǎng',
                'simplified' => '成长',
                'traditional' => '成長',
                'part_of_speech' => 'verb',
                'meaning' => 'To grow up / Growth',
                'meaning_zh' => '成长',
                'example_sentence' => '在经历中成长。',
                'example_translation' => 'Grow through experiences.',
                'definition' => 'To grow up, growth, to mature',
                'sentences' => ['___过程。', '___经历。', '___环境。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '开阔眼界',
                'pinyin' => 'kāi kuò yǎn jiè',
                'simplified' => '开阔眼界',
                'traditional' => '開闊眼界',
                'part_of_speech' => 'verb phrase',
                'meaning' => 'To broaden one\'s horizons',
                'meaning_zh' => '开阔眼界',
                'example_sentence' => '留学能开阔眼界。',
                'example_translation' => 'Studying abroad can broaden horizons.',
                'definition' => 'To broaden horizons, to expand one\'s view',
                'sentences' => ['___机会。', '___视野。', '___见识。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '国际化',
                'pinyin' => 'guó jì huà',
                'simplified' => '国际化',
                'traditional' => '國際化',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Internationalization',
                'meaning_zh' => '国际化',
                'example_sentence' => '教育国际化。',
                'example_translation' => 'Internationalization of education.',
                'definition' => 'Internationalization, to internationalize',
                'sentences' => ['___发展。', '___视野。', '___人才。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '合作',
                'pinyin' => 'hé zuò',
                'simplified' => '合作',
                'traditional' => '合作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To cooperate / Cooperation',
                'meaning_zh' => '合作',
                'example_sentence' => '国际合作项目。',
                'example_translation' => 'International cooperation project.',
                'definition' => 'To cooperate, cooperation, collaboration',
                'sentences' => ['___伙伴。', '___精神。', '___项目。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '归国',
                'pinyin' => 'guī guó',
                'simplified' => '归国',
                'traditional' => '歸國',
                'part_of_speech' => 'verb',
                'meaning' => 'To return to one\'s country',
                'meaning_zh' => '归国',
                'example_sentence' => '学成归国。',
                'example_translation' => 'Return home after completing studies.',
                'definition' => 'To return to one\'s country, to repatriate',
                'sentences' => ['___发展。', '___人才。', '___就业。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 150,
                'word' => '海归',
                'pinyin' => 'hǎi guī',
                'simplified' => '海归',
                'traditional' => '海歸',
                'part_of_speech' => 'noun',
                'meaning' => 'Returnee / Someone who studied abroad',
                'meaning_zh' => '海归',
                'example_sentence' => '他是海归。',
                'example_translation' => 'He is a returnee.',
                'definition' => 'Returnee, overseas returnee',
                'sentences' => ['___人才。', '___就业。', '___优势。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 151: Travel Situations - 旅行情境
        $travelSituationsVocab = [
            [
                'topic_id' => 151,
                'word' => '迷路',
                'pinyin' => 'mí lù',
                'simplified' => '迷路',
                'traditional' => '迷路',
                'part_of_speech' => 'verb',
                'meaning' => 'To get lost',
                'meaning_zh' => '迷路',
                'example_sentence' => '我迷路了。',
                'example_translation' => 'I got lost.',
                'definition' => 'To get lost, to lose one\'s way',
                'sentences' => ['___了。', '___找不到。', '___问路。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '问路',
                'pinyin' => 'wèn lù',
                'simplified' => '问路',
                'traditional' => '問路',
                'part_of_speech' => 'verb',
                'meaning' => 'To ask for directions',
                'meaning_zh' => '问路',
                'example_sentence' => '向人问路。',
                'example_translation' => 'Ask someone for directions.',
                'definition' => 'To ask for directions, to ask the way',
                'sentences' => ['___方式。', '___技巧。', '___礼貌。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '指路',
                'pinyin' => 'zhǐ lù',
                'simplified' => '指路',
                'traditional' => '指路',
                'part_of_speech' => 'verb',
                'meaning' => 'To give directions',
                'meaning_zh' => '指路',
                'example_sentence' => '给他指路。',
                'example_translation' => 'Give him directions.',
                'definition' => 'To give directions, to show the way',
                'sentences' => ['___热心。', '___帮助。', '___清楚。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '排队',
                'pinyin' => 'pái duì',
                'simplified' => '排队',
                'traditional' => '排隊',
                'part_of_speech' => 'verb',
                'meaning' => 'To queue / To line up',
                'meaning_zh' => '排队',
                'example_sentence' => '排队等候。',
                'example_translation' => 'Queue and wait.',
                'definition' => 'To queue, to line up, to stand in line',
                'sentences' => ['___购票。', '___秩序。', '___时间。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '拥挤',
                'pinyin' => 'yōng jǐ',
                'simplified' => '拥挤',
                'traditional' => '擁擠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Crowded / Congested',
                'meaning_zh' => '拥挤',
                'example_sentence' => '人很拥挤。',
                'example_translation' => 'It\'s very crowded.',
                'definition' => 'Crowded, congested, packed',
                'sentences' => ['___不堪。', '___场面。', '___避免。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '延误',
                'pinyin' => 'yán wù',
                'simplified' => '延误',
                'traditional' => '延誤',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To delay / Delay',
                'meaning_zh' => '延误',
                'example_sentence' => '航班延误了。',
                'example_translation' => 'The flight was delayed.',
                'definition' => 'To delay, delay, to postpone',
                'sentences' => ['___时间。', '___通知。', '___原因。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '取消',
                'pinyin' => 'qǔ xiāo',
                'simplified' => '取消',
                'traditional' => '取消',
                'part_of_speech' => 'verb',
                'meaning' => 'To cancel',
                'meaning_zh' => '取消',
                'example_sentence' => '航班被取消了。',
                'example_translation' => 'The flight was cancelled.',
                'definition' => 'To cancel, to call off, to abolish',
                'sentences' => ['___订单。', '___计划。', '___预订。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '更改',
                'pinyin' => 'gēng gǎi',
                'simplified' => '更改',
                'traditional' => '更改',
                'part_of_speech' => 'verb',
                'meaning' => 'To change / To alter',
                'meaning_zh' => '更改',
                'example_sentence' => '更改行程。',
                'example_translation' => 'Change the itinerary.',
                'definition' => 'To change, to alter, to modify',
                'sentences' => ['___计划。', '___时间。', '___安排。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '投诉',
                'pinyin' => 'tóu sù',
                'simplified' => '投诉',
                'traditional' => '投訴',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To complain / Complaint',
                'meaning_zh' => '投诉',
                'example_sentence' => '向酒店投诉。',
                'example_translation' => 'Complain to the hotel.',
                'definition' => 'To complain, complaint',
                'sentences' => ['___电话。', '___处理。', '___渠道。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '退款',
                'pinyin' => 'tuì kuǎn',
                'simplified' => '退款',
                'traditional' => '退款',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To refund / Refund',
                'meaning_zh' => '退款',
                'example_sentence' => '申请退款。',
                'example_translation' => 'Apply for a refund.',
                'definition' => 'To refund, refund, to return money',
                'sentences' => ['___申请。', '___流程。', '___金额。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '遗失',
                'pinyin' => 'yí shī',
                'simplified' => '遗失',
                'traditional' => '遺失',
                'part_of_speech' => 'verb',
                'meaning' => 'To lose / To misplace',
                'meaning_zh' => '遗失',
                'example_sentence' => '护照遗失了。',
                'example_translation' => 'Lost the passport.',
                'definition' => 'To lose, to misplace, to be lost',
                'sentences' => ['___物品。', '___证件。', '___报失。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '寻找',
                'pinyin' => 'xún zhǎo',
                'simplified' => '寻找',
                'traditional' => '尋找',
                'part_of_speech' => 'verb',
                'meaning' => 'To search for / To look for',
                'meaning_zh' => '寻找',
                'example_sentence' => '寻找失物。',
                'example_translation' => 'Search for lost items.',
                'definition' => 'To search for, to look for, to seek',
                'sentences' => ['___帮助。', '___机会。', '___答案。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '紧急',
                'pinyin' => 'jǐn jí',
                'simplified' => '紧急',
                'traditional' => '緊急',
                'part_of_speech' => 'adjective',
                'meaning' => 'Urgent / Emergency',
                'meaning_zh' => '紧急',
                'example_sentence' => '紧急情况。',
                'example_translation' => 'Emergency situation.',
                'definition' => 'Urgent, emergency, critical',
                'sentences' => ['___情况。', '___联系。', '___处理。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '求助',
                'pinyin' => 'qiú zhù',
                'simplified' => '求助',
                'traditional' => '求助',
                'part_of_speech' => 'verb',
                'meaning' => 'To ask for help / To seek help',
                'meaning_zh' => '求助',
                'example_sentence' => '向警察求助。',
                'example_translation' => 'Ask the police for help.',
                'definition' => 'To ask for help, to seek help',
                'sentences' => ['___电话。', '___他人。', '___及时。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '安全',
                'pinyin' => 'ān quán',
                'simplified' => '安全',
                'traditional' => '安全',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Safe / Safety',
                'meaning_zh' => '安全',
                'example_sentence' => '注意安全。',
                'example_translation' => 'Pay attention to safety.',
                'definition' => 'Safe, safety, secure',
                'sentences' => ['___第一。', '___措施。', '___意识。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '危险',
                'pinyin' => 'wēi xiǎn',
                'simplified' => '危险',
                'traditional' => '危險',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Dangerous / Danger',
                'meaning_zh' => '危险',
                'example_sentence' => '很危险。',
                'example_translation' => 'It\'s very dangerous.',
                'definition' => 'Dangerous, danger, hazardous',
                'sentences' => ['___情况。', '___地带。', '___警告。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '小心',
                'pinyin' => 'xiǎo xīn',
                'simplified' => '小心',
                'traditional' => '小心',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Careful / To be careful',
                'meaning_zh' => '小心',
                'example_sentence' => '小心一点。',
                'example_translation' => 'Be careful.',
                'definition' => 'Careful, to be careful, cautious',
                'sentences' => ['___谨慎。', '___注意。', '___提醒。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '保管',
                'pinyin' => 'bǎo guǎn',
                'simplified' => '保管',
                'traditional' => '保管',
                'part_of_speech' => 'verb',
                'meaning' => 'To keep / To take care of',
                'meaning_zh' => '保管',
                'example_sentence' => '保管好财物。',
                'example_translation' => 'Keep valuables safe.',
                'definition' => 'To keep, to take care of, to safeguard',
                'sentences' => ['___物品。', '___妥善。', '___责任。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '提防',
                'pinyin' => 'dī fang',
                'simplified' => '提防',
                'traditional' => '提防',
                'part_of_speech' => 'verb',
                'meaning' => 'To guard against / To be on guard',
                'meaning_zh' => '提防',
                'example_sentence' => '提防小偷。',
                'example_translation' => 'Guard against thieves.',
                'definition' => 'To guard against, to be on guard, to watch out',
                'sentences' => ['___骗子。', '___危险。', '___意识。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 151,
                'word' => '应对',
                'pinyin' => 'yìng duì',
                'simplified' => '应对',
                'traditional' => '應對',
                'part_of_speech' => 'verb',
                'meaning' => 'To deal with / To respond to',
                'meaning_zh' => '应对',
                'example_sentence' => '应对突发情况。',
                'example_translation' => 'Deal with emergencies.',
                'definition' => 'To deal with, to respond to, to cope with',
                'sentences' => ['___措施。', '___能力。', '___策略。'],
                'level' => 'HSK5',
            ],
        ];

        // Topic 152: Goals, Dreams, and Success - 目标梦想与成功
        $successVocab = [
            [
                'topic_id' => 152,
                'word' => '目标',
                'pinyin' => 'mù biāo',
                'simplified' => '目标',
                'traditional' => '目標',
                'part_of_speech' => 'noun',
                'meaning' => 'Goal / Target',
                'meaning_zh' => '目标',
                'example_sentence' => '设定目标。',
                'example_translation' => 'Set goals.',
                'definition' => 'Goal, target, objective',
                'sentences' => ['___明确。', '___实现。', '___达成。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '梦想',
                'pinyin' => 'mèng xiǎng',
                'simplified' => '梦想',
                'traditional' => '夢想',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Dream / To dream',
                'meaning_zh' => '梦想',
                'example_sentence' => '追逐梦想。',
                'example_translation' => 'Chase dreams.',
                'definition' => 'Dream, to dream, aspiration',
                'sentences' => ['___成真。', '___实现。', '___追求。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '理想',
                'pinyin' => 'lǐ xiǎng',
                'simplified' => '理想',
                'traditional' => '理想',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Ideal / Perfect',
                'meaning_zh' => '理想',
                'example_sentence' => '实现理想。',
                'example_translation' => 'Realize one\'s ideals.',
                'definition' => 'Ideal, perfect, aspiration',
                'sentences' => ['___主义。', '___状态。', '___人生。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '抱负',
                'pinyin' => 'bào fù',
                'simplified' => '抱负',
                'traditional' => '抱負',
                'part_of_speech' => 'noun',
                'meaning' => 'Aspiration / Ambition',
                'meaning_zh' => '抱负',
                'example_sentence' => '有远大抱负。',
                'example_translation' => 'Have great aspirations.',
                'definition' => 'Aspiration, ambition, lofty ideal',
                'sentences' => ['___远大。', '___实现。', '___志向。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '志向',
                'pinyin' => 'zhì xiàng',
                'simplified' => '志向',
                'traditional' => '志向',
                'part_of_speech' => 'noun',
                'meaning' => 'Aspiration / Ambition',
                'meaning_zh' => '志向',
                'example_sentence' => '树立志向。',
                'example_translation' => 'Establish aspirations.',
                'definition' => 'Aspiration, ambition, will',
                'sentences' => ['___明确。', '___远大。', '___坚定。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '追求',
                'pinyin' => 'zhuī qiú',
                'simplified' => '追求',
                'traditional' => '追求',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To pursue / Pursuit',
                'meaning_zh' => '追求',
                'example_sentence' => '追求卓越。',
                'example_translation' => 'Pursue excellence.',
                'definition' => 'To pursue, pursuit, to seek',
                'sentences' => ['___梦想。', '___目标。', '___完美。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '奋斗',
                'pinyin' => 'fèn dòu',
                'simplified' => '奋斗',
                'traditional' => '奮鬥',
                'part_of_speech' => 'verb',
                'meaning' => 'To strive / To struggle',
                'meaning_zh' => '奋斗',
                'example_sentence' => '为梦想奋斗。',
                'example_translation' => 'Strive for dreams.',
                'definition' => 'To strive, to struggle, to fight',
                'sentences' => ['___目标。', '___精神。', '___不息。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '拼搏',
                'pinyin' => 'pīn bó',
                'simplified' => '拼搏',
                'traditional' => '拼搏',
                'part_of_speech' => 'verb',
                'meaning' => 'To struggle / To work hard',
                'meaning_zh' => '拼搏',
                'example_sentence' => '努力拼搏。',
                'example_translation' => 'Work hard and struggle.',
                'definition' => 'To struggle, to work hard, to fight',
                'sentences' => ['___精神。', '___进取。', '___向前。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '成功',
                'pinyin' => 'chéng gōng',
                'simplified' => '成功',
                'traditional' => '成功',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To succeed / Success',
                'meaning_zh' => '成功',
                'example_sentence' => '获得成功。',
                'example_translation' => 'Achieve success.',
                'definition' => 'To succeed, success',
                'sentences' => ['___人士。', '___经验。', '___之路。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '成就',
                'pinyin' => 'chéng jiù',
                'simplified' => '成就',
                'traditional' => '成就',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Achievement / To achieve',
                'meaning_zh' => '成就',
                'example_sentence' => '取得成就。',
                'example_translation' => 'Achieve accomplishments.',
                'definition' => 'Achievement, to achieve, accomplishment',
                'sentences' => ['___感。', '___辉煌。', '___卓越。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '收获',
                'pinyin' => 'shōu huò',
                'simplified' => '收获',
                'traditional' => '收穫',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To harvest / Gain',
                'meaning_zh' => '收获',
                'example_sentence' => '收获很多。',
                'example_translation' => 'Gained a lot.',
                'definition' => 'To harvest, gain, achievement',
                'sentences' => ['___经验。', '___成果。', '___满满。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '突破',
                'pinyin' => 'tū pò',
                'simplified' => '突破',
                'traditional' => '突破',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To break through / Breakthrough',
                'meaning_zh' => '突破',
                'example_sentence' => '实现突破。',
                'example_translation' => 'Achieve a breakthrough.',
                'definition' => 'To break through, breakthrough',
                'sentences' => ['___困难。', '___自我。', '___创新。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '超越',
                'pinyin' => 'chāo yuè',
                'simplified' => '超越',
                'traditional' => '超越',
                'part_of_speech' => 'verb',
                'meaning' => 'To surpass / To transcend',
                'meaning_zh' => '超越',
                'example_sentence' => '超越自己。',
                'example_translation' => 'Surpass oneself.',
                'definition' => 'To surpass, to transcend, to exceed',
                'sentences' => ['___极限。', '___对手。', '___梦想。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '进步',
                'pinyin' => 'jìn bù',
                'simplified' => '进步',
                'traditional' => '進步',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To progress / Progress',
                'meaning_zh' => '进步',
                'example_sentence' => '取得进步。',
                'example_translation' => 'Make progress.',
                'definition' => 'To progress, progress, improvement',
                'sentences' => ['___很大。', '___空间。', '___显著。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '提升',
                'pinyin' => 'tí shēng',
                'simplified' => '提升',
                'traditional' => '提升',
                'part_of_speech' => 'verb',
                'meaning' => 'To promote / To enhance',
                'meaning_zh' => '提升',
                'example_sentence' => '提升能力。',
                'example_translation' => 'Enhance abilities.',
                'definition' => 'To promote, to enhance, to improve',
                'sentences' => ['___水平。', '___质量。', '___自己。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '毅力',
                'pinyin' => 'yì lì',
                'simplified' => '毅力',
                'traditional' => '毅力',
                'part_of_speech' => 'noun',
                'meaning' => 'Perseverance / Willpower',
                'meaning_zh' => '毅力',
                'example_sentence' => '需要毅力。',
                'example_translation' => 'Need perseverance.',
                'definition' => 'Perseverance, willpower, determination',
                'sentences' => ['___坚强。', '___培养。', '___考验。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '决心',
                'pinyin' => 'jué xīn',
                'simplified' => '决心',
                'traditional' => '決心',
                'part_of_speech' => 'noun',
                'meaning' => 'Determination / Resolution',
                'meaning_zh' => '决心',
                'example_sentence' => '下定决心。',
                'example_translation' => 'Make up one\'s mind.',
                'definition' => 'Determination, resolution, resolve',
                'sentences' => ['___坚定。', '___很大。', '___改变。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '勇气',
                'pinyin' => 'yǒng qì',
                'simplified' => '勇气',
                'traditional' => '勇氣',
                'part_of_speech' => 'noun',
                'meaning' => 'Courage / Bravery',
                'meaning_zh' => '勇气',
                'example_sentence' => '需要勇气。',
                'example_translation' => 'Need courage.',
                'definition' => 'Courage, bravery, guts',
                'sentences' => ['___面对。', '___挑战。', '___尝试。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '信心',
                'pinyin' => 'xìn xīn',
                'simplified' => '信心',
                'traditional' => '信心',
                'part_of_speech' => 'noun',
                'meaning' => 'Confidence / Faith',
                'meaning_zh' => '信心',
                'example_sentence' => '充满信心。',
                'example_translation' => 'Full of confidence.',
                'definition' => 'Confidence, faith, trust',
                'sentences' => ['___十足。', '___建立。', '___增强。'],
                'level' => 'HSK5',
            ],
            [
                'topic_id' => 152,
                'word' => '潜力',
                'pinyin' => 'qián lì',
                'simplified' => '潜力',
                'traditional' => '潛力',
                'part_of_speech' => 'noun',
                'meaning' => 'Potential',
                'meaning_zh' => '潜力',
                'example_sentence' => '发挥潜力。',
                'example_translation' => 'Unleash potential.',
                'definition' => 'Potential, latent capacity',
                'sentences' => ['___巨大。', '___挖掘。', '___无限。'],
                'level' => 'HSK5',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($studyAbroadVocab, $travelSituationsVocab, $successVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
