<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic155to157Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [155, 157])->delete();

        // Topic 155: Social Issues and Public Life - 社会问题与公共生活
        $socialIssuesVocab = [
            [
                'topic_id' => 155,
                'word' => '贫富差距',
                'pinyin' => 'pín fù chā jù',
                'simplified' => '贫富差距',
                'traditional' => '貧富差距',
                'part_of_speech' => 'noun',
                'meaning' => 'Wealth gap / Income inequality',
                'meaning_zh' => '贫富差距',
                'example_sentence' => '贫富差距越来越大。',
                'example_translation' => 'The wealth gap is getting bigger.',
                'definition' => 'Gap between rich and poor, income inequality',
                'sentences' => ['___问题。', '___扩大。', '___缩小。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '志愿者',
                'pinyin' => 'zhì yuàn zhě',
                'simplified' => '志愿者',
                'traditional' => '志願者',
                'part_of_speech' => 'noun',
                'meaning' => 'Volunteer',
                'meaning_zh' => '志愿者',
                'example_sentence' => '他是一名志愿者。',
                'example_translation' => 'He is a volunteer.',
                'definition' => 'Volunteer, voluntary worker',
                'sentences' => ['___服务。', '___活动。', '___招募。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '公益',
                'pinyin' => 'gōng yì',
                'simplified' => '公益',
                'traditional' => '公益',
                'part_of_speech' => 'noun',
                'meaning' => 'Public welfare / Public good',
                'meaning_zh' => '公益',
                'example_sentence' => '参与公益活动。',
                'example_translation' => 'Participate in public welfare activities.',
                'definition' => 'Public welfare, public interest, charity',
                'sentences' => ['___事业。', '___组织。', '___广告。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '弱势群体',
                'pinyin' => 'ruò shì qún tǐ',
                'simplified' => '弱势群体',
                'traditional' => '弱勢群體',
                'part_of_speech' => 'noun',
                'meaning' => 'Vulnerable groups / Disadvantaged groups',
                'meaning_zh' => '弱势群体',
                'example_sentence' => '关注弱势群体。',
                'example_translation' => 'Pay attention to vulnerable groups.',
                'definition' => 'Vulnerable/disadvantaged groups in society',
                'sentences' => ['___保护。', '___关怀。', '___权益。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '老龄化',
                'pinyin' => 'lǎo líng huà',
                'simplified' => '老龄化',
                'traditional' => '老齡化',
                'part_of_speech' => 'noun',
                'meaning' => 'Aging / Population aging',
                'meaning_zh' => '老龄化',
                'example_sentence' => '人口老龄化严重。',
                'example_translation' => 'Population aging is serious.',
                'definition' => 'Aging, population aging, demographic aging',
                'sentences' => ['___社会。', '___问题。', '___趋势。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '就业',
                'pinyin' => 'jiù yè',
                'simplified' => '就业',
                'traditional' => '就業',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Employment / To get employed',
                'meaning_zh' => '就业',
                'example_sentence' => '解决就业问题。',
                'example_translation' => 'Solve employment problems.',
                'definition' => 'Employment, to get employed, to find work',
                'sentences' => ['___机会。', '___压力。', '___率。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '失业',
                'pinyin' => 'shī yè',
                'simplified' => '失业',
                'traditional' => '失業',
                'part_of_speech' => 'verb',
                'meaning' => 'Unemployment / To be unemployed',
                'meaning_zh' => '失业',
                'example_sentence' => '失业率上升。',
                'example_translation' => 'Unemployment rate is rising.',
                'definition' => 'Unemployment, to be unemployed, jobless',
                'sentences' => ['___人口。', '___保险。', '___率。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '歧视',
                'pinyin' => 'qí shì',
                'simplified' => '歧视',
                'traditional' => '歧視',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To discriminate / Discrimination',
                'meaning_zh' => '歧视',
                'example_sentence' => '反对歧视。',
                'example_translation' => 'Oppose discrimination.',
                'definition' => 'To discriminate, discrimination, prejudice',
                'sentences' => ['___现象。', '___行为。', '___消除。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '腐败',
                'pinyin' => 'fǔ bài',
                'simplified' => '腐败',
                'traditional' => '腐敗',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Corruption / Corrupt',
                'meaning_zh' => '腐败',
                'example_sentence' => '反腐败斗争。',
                'example_translation' => 'Anti-corruption campaign.',
                'definition' => 'Corruption, corrupt, rotten',
                'sentences' => ['___现象。', '___分子。', '___治理。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '和谐',
                'pinyin' => 'hé xié',
                'simplified' => '和谐',
                'traditional' => '和諧',
                'part_of_speech' => 'adjective',
                'meaning' => 'Harmonious / Harmony',
                'meaning_zh' => '和谐',
                'example_sentence' => '构建和谐社会。',
                'example_translation' => 'Build a harmonious society.',
                'definition' => 'Harmonious, harmony, concordant',
                'sentences' => ['___社会。', '___相处。', '___发展。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '矛盾',
                'pinyin' => 'máo dùn',
                'simplified' => '矛盾',
                'traditional' => '矛盾',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Contradiction / Contradictory',
                'meaning_zh' => '矛盾',
                'example_sentence' => '解决矛盾。',
                'example_translation' => 'Resolve contradictions.',
                'definition' => 'Contradiction, conflict, inconsistency',
                'sentences' => ['___冲突。', '___化解。', '___尖锐。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '福利',
                'pinyin' => 'fú lì',
                'simplified' => '福利',
                'traditional' => '福利',
                'part_of_speech' => 'noun',
                'meaning' => 'Welfare / Benefits',
                'meaning_zh' => '福利',
                'example_sentence' => '员工福利很好。',
                'example_translation' => 'Employee benefits are good.',
                'definition' => 'Welfare, benefits, well-being',
                'sentences' => ['___制度。', '___待遇。', '___保障。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '医疗保障',
                'pinyin' => 'yī liáo bǎo zhàng',
                'simplified' => '医疗保障',
                'traditional' => '醫療保障',
                'part_of_speech' => 'noun',
                'meaning' => 'Medical insurance / Healthcare coverage',
                'meaning_zh' => '医疗保障',
                'example_sentence' => '完善医疗保障体系。',
                'example_translation' => 'Improve the healthcare coverage system.',
                'definition' => 'Medical insurance, healthcare coverage',
                'sentences' => ['___体系。', '___制度。', '___覆盖。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '养老',
                'pinyin' => 'yǎng lǎo',
                'simplified' => '养老',
                'traditional' => '養老',
                'part_of_speech' => 'verb',
                'meaning' => 'Elderly care / Pension',
                'meaning_zh' => '养老',
                'example_sentence' => '养老问题很重要。',
                'example_translation' => 'Elderly care is very important.',
                'definition' => 'Elderly care, pension, retirement support',
                'sentences' => ['___保险。', '___金。', '___院。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '住房',
                'pinyin' => 'zhù fáng',
                'simplified' => '住房',
                'traditional' => '住房',
                'part_of_speech' => 'noun',
                'meaning' => 'Housing / Residence',
                'meaning_zh' => '住房',
                'example_sentence' => '住房问题突出。',
                'example_translation' => 'Housing problems are prominent.',
                'definition' => 'Housing, residence, dwelling',
                'sentences' => ['___困难。', '___条件。', '___保障。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '房价',
                'pinyin' => 'fáng jià',
                'simplified' => '房价',
                'traditional' => '房價',
                'part_of_speech' => 'noun',
                'meaning' => 'Housing price / Property price',
                'meaning_zh' => '房价',
                'example_sentence' => '房价太高了。',
                'example_translation' => 'Housing prices are too high.',
                'definition' => 'Housing price, property price, real estate price',
                'sentences' => ['___上涨。', '___下跌。', '___调控。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '犯罪',
                'pinyin' => 'fàn zuì',
                'simplified' => '犯罪',
                'traditional' => '犯罪',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Crime / To commit a crime',
                'meaning_zh' => '犯罪',
                'example_sentence' => '打击犯罪行为。',
                'example_translation' => 'Combat criminal behavior.',
                'definition' => 'Crime, to commit a crime, criminal act',
                'sentences' => ['___率。', '___分子。', '___行为。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '治安',
                'pinyin' => 'zhì ān',
                'simplified' => '治安',
                'traditional' => '治安',
                'part_of_speech' => 'noun',
                'meaning' => 'Public security / Public order',
                'meaning_zh' => '治安',
                'example_sentence' => '维护治安。',
                'example_translation' => 'Maintain public security.',
                'definition' => 'Public security, public order, law and order',
                'sentences' => ['___管理。', '___良好。', '___问题。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '慈善',
                'pinyin' => 'cí shàn',
                'simplified' => '慈善',
                'traditional' => '慈善',
                'part_of_speech' => 'noun',
                'meaning' => 'Charity / Philanthropy',
                'meaning_zh' => '慈善',
                'example_sentence' => '做慈善事业。',
                'example_translation' => 'Do charity work.',
                'definition' => 'Charity, philanthropy, charitable',
                'sentences' => ['___机构。', '___捐款。', '___活动。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 155,
                'word' => '捐赠',
                'pinyin' => 'juān zèng',
                'simplified' => '捐赠',
                'traditional' => '捐贈',
                'part_of_speech' => 'verb',
                'meaning' => 'To donate / Donation',
                'meaning_zh' => '捐赠',
                'example_sentence' => '向灾区捐赠物资。',
                'example_translation' => 'Donate supplies to disaster areas.',
                'definition' => 'To donate, donation, to contribute',
                'sentences' => ['___资金。', '___物品。', '___仪式。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 156: Government and Politics - 政府与政治
        $governmentVocab = [
            [
                'topic_id' => 156,
                'word' => '政府',
                'pinyin' => 'zhèng fǔ',
                'simplified' => '政府',
                'traditional' => '政府',
                'part_of_speech' => 'noun',
                'meaning' => 'Government',
                'meaning_zh' => '政府',
                'example_sentence' => '地方政府。',
                'example_translation' => 'Local government.',
                'definition' => 'Government, administration',
                'sentences' => ['___机构。', '___官员。', '___政策。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '政治',
                'pinyin' => 'zhèng zhì',
                'simplified' => '政治',
                'traditional' => '政治',
                'part_of_speech' => 'noun',
                'meaning' => 'Politics / Political',
                'meaning_zh' => '政治',
                'example_sentence' => '政治制度。',
                'example_translation' => 'Political system.',
                'definition' => 'Politics, political affairs',
                'sentences' => ['___体制。', '___改革。', '___稳定。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '改革',
                'pinyin' => 'gǎi gé',
                'simplified' => '改革',
                'traditional' => '改革',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Reform / To reform',
                'meaning_zh' => '改革',
                'example_sentence' => '深化改革。',
                'example_translation' => 'Deepen reforms.',
                'definition' => 'Reform, to reform, transformation',
                'sentences' => ['___开放。', '___措施。', '___创新。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '领导',
                'pinyin' => 'lǐng dǎo',
                'simplified' => '领导',
                'traditional' => '領導',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Leader / To lead',
                'meaning_zh' => '领导',
                'example_sentence' => '各级领导。',
                'example_translation' => 'Leaders at all levels.',
                'definition' => 'Leader, leadership, to lead',
                'sentences' => ['___干部。', '___班子。', '___能力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '干部',
                'pinyin' => 'gàn bù',
                'simplified' => '干部',
                'traditional' => '幹部',
                'part_of_speech' => 'noun',
                'meaning' => 'Cadre / Official',
                'meaning_zh' => '干部',
                'example_sentence' => '领导干部。',
                'example_translation' => 'Leading cadres.',
                'definition' => 'Cadre, official, staff member',
                'sentences' => ['___培训。', '___队伍。', '___管理。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '官员',
                'pinyin' => 'guān yuán',
                'simplified' => '官员',
                'traditional' => '官員',
                'part_of_speech' => 'noun',
                'meaning' => 'Official / Government official',
                'meaning_zh' => '官员',
                'example_sentence' => '政府官员。',
                'example_translation' => 'Government officials.',
                'definition' => 'Official, government official, functionary',
                'sentences' => ['___腐败。', '___职责。', '___任免。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '权力',
                'pinyin' => 'quán lì',
                'simplified' => '权力',
                'traditional' => '權力',
                'part_of_speech' => 'noun',
                'meaning' => 'Power / Authority',
                'meaning_zh' => '权力',
                'example_sentence' => '行使权力。',
                'example_translation' => 'Exercise power.',
                'definition' => 'Power, authority, right',
                'sentences' => ['___机关。', '___滥用。', '___制约。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '权威',
                'pinyin' => 'quán wēi',
                'simplified' => '权威',
                'traditional' => '權威',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Authority / Authoritative',
                'meaning_zh' => '权威',
                'example_sentence' => '权威专家。',
                'example_translation' => 'Authoritative expert.',
                'definition' => 'Authority, authoritative, prestige',
                'sentences' => ['___性。', '___机构。', '___人士。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '民主',
                'pinyin' => 'mín zhǔ',
                'simplified' => '民主',
                'traditional' => '民主',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Democracy / Democratic',
                'meaning_zh' => '民主',
                'example_sentence' => '发扬民主。',
                'example_translation' => 'Promote democracy.',
                'definition' => 'Democracy, democratic',
                'sentences' => ['___制度。', '___选举。', '___权利。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '选举',
                'pinyin' => 'xuǎn jǔ',
                'simplified' => '选举',
                'traditional' => '選舉',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Election / To elect',
                'meaning_zh' => '选举',
                'example_sentence' => '民主选举。',
                'example_translation' => 'Democratic election.',
                'definition' => 'Election, to elect, to vote',
                'sentences' => ['___权。', '___投票。', '___结果。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '体制',
                'pinyin' => 'tǐ zhì',
                'simplified' => '体制',
                'traditional' => '體制',
                'part_of_speech' => 'noun',
                'meaning' => 'System / Structure',
                'meaning_zh' => '体制',
                'example_sentence' => '政治体制。',
                'example_translation' => 'Political system.',
                'definition' => 'System, structure, organizational system',
                'sentences' => ['___改革。', '___机制。', '___创新。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '机制',
                'pinyin' => 'jī zhì',
                'simplified' => '机制',
                'traditional' => '機制',
                'part_of_speech' => 'noun',
                'meaning' => 'Mechanism / System',
                'meaning_zh' => '机制',
                'example_sentence' => '建立机制。',
                'example_translation' => 'Establish a mechanism.',
                'definition' => 'Mechanism, system, structure',
                'sentences' => ['___完善。', '___创新。', '___运行。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '决策',
                'pinyin' => 'jué cè',
                'simplified' => '决策',
                'traditional' => '決策',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Decision-making / To make decisions',
                'meaning_zh' => '决策',
                'example_sentence' => '科学决策。',
                'example_translation' => 'Scientific decision-making.',
                'definition' => 'Decision-making, to make decisions, policy',
                'sentences' => ['___过程。', '___者。', '___机制。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '实施',
                'pinyin' => 'shí shī',
                'simplified' => '实施',
                'traditional' => '實施',
                'part_of_speech' => 'verb',
                'meaning' => 'To implement / To carry out',
                'meaning_zh' => '实施',
                'example_sentence' => '实施政策。',
                'example_translation' => 'Implement policies.',
                'definition' => 'To implement, to carry out, to execute',
                'sentences' => ['___方案。', '___细则。', '___措施。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '落实',
                'pinyin' => 'luò shí',
                'simplified' => '落实',
                'traditional' => '落實',
                'part_of_speech' => 'verb',
                'meaning' => 'To implement / To put into practice',
                'meaning_zh' => '落实',
                'example_sentence' => '狠抓落实。',
                'example_translation' => 'Firmly implement.',
                'definition' => 'To implement, to put into practice, to fulfill',
                'sentences' => ['___政策。', '___责任。', '___到位。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '透明',
                'pinyin' => 'tòu míng',
                'simplified' => '透明',
                'traditional' => '透明',
                'part_of_speech' => 'adjective',
                'meaning' => 'Transparent / Transparency',
                'meaning_zh' => '透明',
                'example_sentence' => '政务透明。',
                'example_translation' => 'Government transparency.',
                'definition' => 'Transparent, transparency, clear',
                'sentences' => ['___度。', '___公开。', '___化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '参与',
                'pinyin' => 'cān yù',
                'simplified' => '参与',
                'traditional' => '參與',
                'part_of_speech' => 'verb',
                'meaning' => 'To participate / Participation',
                'meaning_zh' => '参与',
                'example_sentence' => '全民参与。',
                'example_translation' => 'Universal participation.',
                'definition' => 'To participate, participation, to take part',
                'sentences' => ['___度。', '___管理。', '___决策。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '治理',
                'pinyin' => 'zhì lǐ',
                'simplified' => '治理',
                'traditional' => '治理',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To govern / Governance',
                'meaning_zh' => '治理',
                'example_sentence' => '社会治理。',
                'example_translation' => 'Social governance.',
                'definition' => 'To govern, governance, to manage',
                'sentences' => ['___能力。', '___体系。', '___现代化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '稳定',
                'pinyin' => 'wěn dìng',
                'simplified' => '稳定',
                'traditional' => '穩定',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Stable / To stabilize',
                'meaning_zh' => '稳定',
                'example_sentence' => '保持稳定。',
                'example_translation' => 'Maintain stability.',
                'definition' => 'Stable, to stabilize, stability',
                'sentences' => ['___局面。', '___发展。', '___性。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 156,
                'word' => '繁荣',
                'pinyin' => 'fán róng',
                'simplified' => '繁荣',
                'traditional' => '繁榮',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Prosperous / To prosper',
                'meaning_zh' => '繁荣',
                'example_sentence' => '经济繁荣。',
                'example_translation' => 'Economic prosperity.',
                'definition' => 'Prosperous, to prosper, prosperity',
                'sentences' => ['___昌盛。', '___发展。', '___富强。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 157: Law and Justice - 法律与公正
        $lawVocab = [
            [
                'topic_id' => 157,
                'word' => '法治',
                'pinyin' => 'fǎ zhì',
                'simplified' => '法治',
                'traditional' => '法治',
                'part_of_speech' => 'noun',
                'meaning' => 'Rule of law / Legal system',
                'meaning_zh' => '法治',
                'example_sentence' => '依法治国。',
                'example_translation' => 'Govern the country by law.',
                'definition' => 'Rule of law, legal system',
                'sentences' => ['___社会。', '___建设。', '___精神。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '宪法',
                'pinyin' => 'xiàn fǎ',
                'simplified' => '宪法',
                'traditional' => '憲法',
                'part_of_speech' => 'noun',
                'meaning' => 'Constitution',
                'meaning_zh' => '宪法',
                'example_sentence' => '遵守宪法。',
                'example_translation' => 'Abide by the constitution.',
                'definition' => 'Constitution, constitutional law',
                'sentences' => ['___规定。', '___精神。', '___修正案。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '立法',
                'pinyin' => 'lì fǎ',
                'simplified' => '立法',
                'traditional' => '立法',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Legislation / To legislate',
                'meaning_zh' => '立法',
                'example_sentence' => '完善立法。',
                'example_translation' => 'Improve legislation.',
                'definition' => 'Legislation, to legislate, lawmaking',
                'sentences' => ['___机关。', '___程序。', '___权。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '司法',
                'pinyin' => 'sī fǎ',
                'simplified' => '司法',
                'traditional' => '司法',
                'part_of_speech' => 'noun',
                'meaning' => 'Judiciary / Justice',
                'meaning_zh' => '司法',
                'example_sentence' => '司法公正。',
                'example_translation' => 'Judicial justice.',
                'definition' => 'Judiciary, justice, judicial',
                'sentences' => ['___机关。', '___改革。', '___独立。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '执法',
                'pinyin' => 'zhí fǎ',
                'simplified' => '执法',
                'traditional' => '執法',
                'part_of_speech' => 'verb',
                'meaning' => 'Law enforcement / To enforce law',
                'meaning_zh' => '执法',
                'example_sentence' => '严格执法。',
                'example_translation' => 'Strict law enforcement.',
                'definition' => 'Law enforcement, to enforce law',
                'sentences' => ['___部门。', '___人员。', '___监督。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '法官',
                'pinyin' => 'fǎ guān',
                'simplified' => '法官',
                'traditional' => '法官',
                'part_of_speech' => 'noun',
                'meaning' => 'Judge',
                'meaning_zh' => '法官',
                'example_sentence' => '公正的法官。',
                'example_translation' => 'Fair judge.',
                'definition' => 'Judge, magistrate',
                'sentences' => ['___审判。', '___宣判。', '___职业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '检察官',
                'pinyin' => 'jiǎn chá guān',
                'simplified' => '检察官',
                'traditional' => '檢察官',
                'part_of_speech' => 'noun',
                'meaning' => 'Prosecutor',
                'meaning_zh' => '检察官',
                'example_sentence' => '检察官提起公诉。',
                'example_translation' => 'The prosecutor filed charges.',
                'definition' => 'Prosecutor, procurator',
                'sentences' => ['___起诉。', '___调查。', '___职责。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '审判',
                'pinyin' => 'shěn pàn',
                'simplified' => '审判',
                'traditional' => '審判',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Trial / To try (in court)',
                'meaning_zh' => '审判',
                'example_sentence' => '公开审判。',
                'example_translation' => 'Public trial.',
                'definition' => 'Trial, to try, to judge',
                'sentences' => ['___程序。', '___公正。', '___结果。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '起诉',
                'pinyin' => 'qǐ sù',
                'simplified' => '起诉',
                'traditional' => '起訴',
                'part_of_speech' => 'verb',
                'meaning' => 'To sue / To prosecute',
                'meaning_zh' => '起诉',
                'example_sentence' => '向法院起诉。',
                'example_translation' => 'Sue in court.',
                'definition' => 'To sue, to prosecute, to indict',
                'sentences' => ['___书。', '___权。', '___程序。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '辩护',
                'pinyin' => 'biàn hù',
                'simplified' => '辩护',
                'traditional' => '辯護',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Defense / To defend',
                'meaning_zh' => '辩护',
                'example_sentence' => '律师辩护。',
                'example_translation' => 'Lawyer\'s defense.',
                'definition' => 'Defense, to defend, to plead',
                'sentences' => ['___律师。', '___权。', '___意见。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '证据',
                'pinyin' => 'zhèng jù',
                'simplified' => '证据',
                'traditional' => '證據',
                'part_of_speech' => 'noun',
                'meaning' => 'Evidence / Proof',
                'meaning_zh' => '证据',
                'example_sentence' => '提供证据。',
                'example_translation' => 'Provide evidence.',
                'definition' => 'Evidence, proof, testimony',
                'sentences' => ['___确凿。', '___链。', '___不足。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '案件',
                'pinyin' => 'àn jiàn',
                'simplified' => '案件',
                'traditional' => '案件',
                'part_of_speech' => 'noun',
                'meaning' => 'Case / Legal case',
                'meaning_zh' => '案件',
                'example_sentence' => '审理案件。',
                'example_translation' => 'Hear a case.',
                'definition' => 'Case, legal case',
                'sentences' => ['___调查。', '___侦破。', '___审理。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '罪行',
                'pinyin' => 'zuì xíng',
                'simplified' => '罪行',
                'traditional' => '罪行',
                'part_of_speech' => 'noun',
                'meaning' => 'Crime / Criminal act',
                'meaning_zh' => '罪行',
                'example_sentence' => '严重罪行。',
                'example_translation' => 'Serious crime.',
                'definition' => 'Crime, criminal act, offense',
                'sentences' => ['___严重。', '___揭露。', '___认定。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '刑罚',
                'pinyin' => 'xíng fá',
                'simplified' => '刑罚',
                'traditional' => '刑罰',
                'part_of_speech' => 'noun',
                'meaning' => 'Punishment / Penalty',
                'meaning_zh' => '刑罚',
                'example_sentence' => '受到刑罚。',
                'example_translation' => 'Receive punishment.',
                'definition' => 'Punishment, penalty, sentence',
                'sentences' => ['___执行。', '___轻重。', '___制度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '宣判',
                'pinyin' => 'xuān pàn',
                'simplified' => '宣判',
                'traditional' => '宣判',
                'part_of_speech' => 'verb',
                'meaning' => 'To pronounce judgment / To sentence',
                'meaning_zh' => '宣判',
                'example_sentence' => '法院宣判。',
                'example_translation' => 'The court pronounces judgment.',
                'definition' => 'To pronounce judgment, to sentence',
                'sentences' => ['___结果。', '___无罪。', '___有罪。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '无罪',
                'pinyin' => 'wú zuì',
                'simplified' => '无罪',
                'traditional' => '無罪',
                'part_of_speech' => 'adjective',
                'meaning' => 'Innocent / Not guilty',
                'meaning_zh' => '无罪',
                'example_sentence' => '宣告无罪。',
                'example_translation' => 'Declare innocent.',
                'definition' => 'Innocent, not guilty, guiltless',
                'sentences' => ['___释放。', '___推定。', '___辩护。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '公平',
                'pinyin' => 'gōng píng',
                'simplified' => '公平',
                'traditional' => '公平',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fair / Just',
                'meaning_zh' => '公平',
                'example_sentence' => '公平对待。',
                'example_translation' => 'Treat fairly.',
                'definition' => 'Fair, just, impartial',
                'sentences' => ['___公正。', '___竞争。', '___原则。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '合法权益',
                'pinyin' => 'hé fǎ quán yì',
                'simplified' => '合法权益',
                'traditional' => '合法權益',
                'part_of_speech' => 'noun',
                'meaning' => 'Legal rights and interests',
                'meaning_zh' => '合法权益',
                'example_sentence' => '保护合法权益。',
                'example_translation' => 'Protect legal rights and interests.',
                'definition' => 'Legal rights and interests, legitimate rights',
                'sentences' => ['___维护。', '___受损。', '___保障。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '仲裁',
                'pinyin' => 'zhòng cái',
                'simplified' => '仲裁',
                'traditional' => '仲裁',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Arbitration / To arbitrate',
                'meaning_zh' => '仲裁',
                'example_sentence' => '申请仲裁。',
                'example_translation' => 'Apply for arbitration.',
                'definition' => 'Arbitration, to arbitrate',
                'sentences' => ['___机构。', '___裁决。', '___程序。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 157,
                'word' => '赔偿',
                'pinyin' => 'péi cháng',
                'simplified' => '赔偿',
                'traditional' => '賠償',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Compensation / To compensate',
                'meaning_zh' => '赔偿',
                'example_sentence' => '要求赔偿。',
                'example_translation' => 'Demand compensation.',
                'definition' => 'Compensation, to compensate, to indemnify',
                'sentences' => ['___损失。', '___金额。', '___责任。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($socialIssuesVocab, $governmentVocab, $lawVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
