<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic158to160Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [158, 160])->delete();

        // Topic 158: Economy and Business - 经济与商业
        $economyVocab = [
            [
                'topic_id' => 158,
                'word' => '经济',
                'pinyin' => 'jīng jì',
                'simplified' => '经济',
                'traditional' => '經濟',
                'part_of_speech' => 'noun',
                'meaning' => 'Economy / Economic',
                'meaning_zh' => '经济',
                'example_sentence' => '发展经济。',
                'example_translation' => 'Develop the economy.',
                'definition' => 'Economy, economic, economical',
                'sentences' => ['___发展。', '___增长。', '___政策。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '商业',
                'pinyin' => 'shāng yè',
                'simplified' => '商业',
                'traditional' => '商業',
                'part_of_speech' => 'noun',
                'meaning' => 'Commerce / Business',
                'meaning_zh' => '商业',
                'example_sentence' => '商业中心。',
                'example_translation' => 'Business center.',
                'definition' => 'Commerce, business, commercial',
                'sentences' => ['___活动。', '___合作。', '___价值。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '贸易',
                'pinyin' => 'mào yì',
                'simplified' => '贸易',
                'traditional' => '貿易',
                'part_of_speech' => 'noun',
                'meaning' => 'Trade',
                'meaning_zh' => '贸易',
                'example_sentence' => '国际贸易。',
                'example_translation' => 'International trade.',
                'definition' => 'Trade, commerce',
                'sentences' => ['___往来。', '___协定。', '___顺差。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '投资',
                'pinyin' => 'tóu zī',
                'simplified' => '投资',
                'traditional' => '投資',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Investment / To invest',
                'meaning_zh' => '投资',
                'example_sentence' => '吸引投资。',
                'example_translation' => 'Attract investment.',
                'definition' => 'Investment, to invest',
                'sentences' => ['___项目。', '___回报。', '___风险。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '融资',
                'pinyin' => 'róng zī',
                'simplified' => '融资',
                'traditional' => '融資',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Financing / To finance',
                'meaning_zh' => '融资',
                'example_sentence' => '企业融资。',
                'example_translation' => 'Corporate financing.',
                'definition' => 'Financing, to finance, to raise funds',
                'sentences' => ['___渠道。', '___困难。', '___成本。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '资本',
                'pinyin' => 'zī běn',
                'simplified' => '资本',
                'traditional' => '資本',
                'part_of_speech' => 'noun',
                'meaning' => 'Capital',
                'meaning_zh' => '资本',
                'example_sentence' => '资本市场。',
                'example_translation' => 'Capital market.',
                'definition' => 'Capital, fund',
                'sentences' => ['___运作。', '___积累。', '___主义。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '股票',
                'pinyin' => 'gǔ piào',
                'simplified' => '股票',
                'traditional' => '股票',
                'part_of_speech' => 'noun',
                'meaning' => 'Stock / Share',
                'meaning_zh' => '股票',
                'example_sentence' => '买股票。',
                'example_translation' => 'Buy stocks.',
                'definition' => 'Stock, share, equity',
                'sentences' => ['___市场。', '___交易。', '___价格。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '债券',
                'pinyin' => 'zhài quàn',
                'simplified' => '债券',
                'traditional' => '債券',
                'part_of_speech' => 'noun',
                'meaning' => 'Bond / Debenture',
                'meaning_zh' => '债券',
                'example_sentence' => '发行债券。',
                'example_translation' => 'Issue bonds.',
                'definition' => 'Bond, debenture',
                'sentences' => ['___市场。', '___利率。', '___到期。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '利润',
                'pinyin' => 'lì rùn',
                'simplified' => '利润',
                'traditional' => '利潤',
                'part_of_speech' => 'noun',
                'meaning' => 'Profit',
                'meaning_zh' => '利润',
                'example_sentence' => '增加利润。',
                'example_translation' => 'Increase profit.',
                'definition' => 'Profit, gain',
                'sentences' => ['___率。', '___最大化。', '___下降。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '亏损',
                'pinyin' => 'kuī sǔn',
                'simplified' => '亏损',
                'traditional' => '虧損',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Loss / To lose money',
                'meaning_zh' => '亏损',
                'example_sentence' => '企业亏损。',
                'example_translation' => 'Company losses.',
                'definition' => 'Loss, to lose money, deficit',
                'sentences' => ['___严重。', '___减少。', '___状态。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '竞争',
                'pinyin' => 'jìng zhēng',
                'simplified' => '竞争',
                'traditional' => '競爭',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Competition / To compete',
                'meaning_zh' => '竞争',
                'example_sentence' => '激烈竞争。',
                'example_translation' => 'Fierce competition.',
                'definition' => 'Competition, to compete, rivalry',
                'sentences' => ['___对手。', '___优势。', '___力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '垄断',
                'pinyin' => 'lǒng duàn',
                'simplified' => '垄断',
                'traditional' => '壟斷',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Monopoly / To monopolize',
                'meaning_zh' => '垄断',
                'example_sentence' => '反垄断法。',
                'example_translation' => 'Anti-monopoly law.',
                'definition' => 'Monopoly, to monopolize',
                'sentences' => ['___市场。', '___地位。', '___行为。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '供需',
                'pinyin' => 'gōng xū',
                'simplified' => '供需',
                'traditional' => '供需',
                'part_of_speech' => 'noun',
                'meaning' => 'Supply and demand',
                'meaning_zh' => '供需',
                'example_sentence' => '供需平衡。',
                'example_translation' => 'Supply and demand balance.',
                'definition' => 'Supply and demand',
                'sentences' => ['___关系。', '___矛盾。', '___变化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '通货膨胀',
                'pinyin' => 'tōng huò péng zhàng',
                'simplified' => '通货膨胀',
                'traditional' => '通貨膨脹',
                'part_of_speech' => 'noun',
                'meaning' => 'Inflation',
                'meaning_zh' => '通货膨胀',
                'example_sentence' => '控制通货膨胀。',
                'example_translation' => 'Control inflation.',
                'definition' => 'Inflation, price rise',
                'sentences' => ['___率。', '___压力。', '___预期。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '汇率',
                'pinyin' => 'huì lǜ',
                'simplified' => '汇率',
                'traditional' => '匯率',
                'part_of_speech' => 'noun',
                'meaning' => 'Exchange rate',
                'meaning_zh' => '汇率',
                'example_sentence' => '汇率波动。',
                'example_translation' => 'Exchange rate fluctuation.',
                'definition' => 'Exchange rate, foreign exchange rate',
                'sentences' => ['___变动。', '___稳定。', '___市场。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '税收',
                'pinyin' => 'shuì shōu',
                'simplified' => '税收',
                'traditional' => '稅收',
                'part_of_speech' => 'noun',
                'meaning' => 'Tax revenue / Taxation',
                'meaning_zh' => '税收',
                'example_sentence' => '增加税收。',
                'example_translation' => 'Increase tax revenue.',
                'definition' => 'Tax revenue, taxation, tax',
                'sentences' => ['___政策。', '___优惠。', '___制度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '财政',
                'pinyin' => 'cái zhèng',
                'simplified' => '财政',
                'traditional' => '財政',
                'part_of_speech' => 'noun',
                'meaning' => 'Public finance / Financial',
                'meaning_zh' => '财政',
                'example_sentence' => '财政收入。',
                'example_translation' => 'Fiscal revenue.',
                'definition' => 'Public finance, financial, fiscal',
                'sentences' => ['___预算。', '___政策。', '___赤字。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '预算',
                'pinyin' => 'yù suàn',
                'simplified' => '预算',
                'traditional' => '預算',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Budget / To budget',
                'meaning_zh' => '预算',
                'example_sentence' => '编制预算。',
                'example_translation' => 'Prepare a budget.',
                'definition' => 'Budget, to budget',
                'sentences' => ['___控制。', '___执行。', '___超支。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '破产',
                'pinyin' => 'pò chǎn',
                'simplified' => '破产',
                'traditional' => '破產',
                'part_of_speech' => 'verb',
                'meaning' => 'Bankruptcy / To go bankrupt',
                'meaning_zh' => '破产',
                'example_sentence' => '公司破产。',
                'example_translation' => 'Company went bankrupt.',
                'definition' => 'Bankruptcy, to go bankrupt, insolvency',
                'sentences' => ['___保护。', '___清算。', '___边缘。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 158,
                'word' => '并购',
                'pinyin' => 'bìng gòu',
                'simplified' => '并购',
                'traditional' => '併購',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Merger and acquisition / M&A',
                'meaning_zh' => '并购',
                'example_sentence' => '企业并购。',
                'example_translation' => 'Corporate merger and acquisition.',
                'definition' => 'Merger and acquisition, M&A',
                'sentences' => ['___重组。', '___交易。', '___整合。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 159: Globalization and International Relations - 全球化与国际关系
        $globalizationVocab = [
            [
                'topic_id' => 159,
                'word' => '全球化',
                'pinyin' => 'quán qiú huà',
                'simplified' => '全球化',
                'traditional' => '全球化',
                'part_of_speech' => 'noun',
                'meaning' => 'Globalization',
                'meaning_zh' => '全球化',
                'example_sentence' => '经济全球化。',
                'example_translation' => 'Economic globalization.',
                'definition' => 'Globalization, global integration',
                'sentences' => ['___趋势。', '___进程。', '___时代。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '国际',
                'pinyin' => 'guó jì',
                'simplified' => '国际',
                'traditional' => '國際',
                'part_of_speech' => 'adjective',
                'meaning' => 'International',
                'meaning_zh' => '国际',
                'example_sentence' => '国际关系。',
                'example_translation' => 'International relations.',
                'definition' => 'International, world',
                'sentences' => ['___社会。', '___合作。', '___组织。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '外交',
                'pinyin' => 'wài jiāo',
                'simplified' => '外交',
                'traditional' => '外交',
                'part_of_speech' => 'noun',
                'meaning' => 'Diplomacy / Foreign affairs',
                'meaning_zh' => '外交',
                'example_sentence' => '外交政策。',
                'example_translation' => 'Foreign policy.',
                'definition' => 'Diplomacy, foreign affairs',
                'sentences' => ['___关系。', '___部。', '___手段。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '主权',
                'pinyin' => 'zhǔ quán',
                'simplified' => '主权',
                'traditional' => '主權',
                'part_of_speech' => 'noun',
                'meaning' => 'Sovereignty',
                'meaning_zh' => '主权',
                'example_sentence' => '国家主权。',
                'example_translation' => 'National sovereignty.',
                'definition' => 'Sovereignty, sovereign rights',
                'sentences' => ['___独立。', '___完整。', '___尊重。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '领土',
                'pinyin' => 'lǐng tǔ',
                'simplified' => '领土',
                'traditional' => '領土',
                'part_of_speech' => 'noun',
                'meaning' => 'Territory',
                'meaning_zh' => '领土',
                'example_sentence' => '领土争议。',
                'example_translation' => 'Territorial dispute.',
                'definition' => 'Territory, territorial',
                'sentences' => ['___完整。', '___主权。', '___边界。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '联盟',
                'pinyin' => 'lián méng',
                'simplified' => '联盟',
                'traditional' => '聯盟',
                'part_of_speech' => 'noun',
                'meaning' => 'Alliance / Coalition',
                'meaning_zh' => '联盟',
                'example_sentence' => '建立联盟。',
                'example_translation' => 'Establish an alliance.',
                'definition' => 'Alliance, coalition, league',
                'sentences' => ['___国家。', '___关系。', '___伙伴。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '条约',
                'pinyin' => 'tiáo yuē',
                'simplified' => '条约',
                'traditional' => '條約',
                'part_of_speech' => 'noun',
                'meaning' => 'Treaty / Pact',
                'meaning_zh' => '条约',
                'example_sentence' => '签署条约。',
                'example_translation' => 'Sign a treaty.',
                'definition' => 'Treaty, pact, agreement',
                'sentences' => ['___内容。', '___生效。', '___缔约。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '协议',
                'pinyin' => 'xié yì',
                'simplified' => '协议',
                'traditional' => '協議',
                'part_of_speech' => 'noun',
                'meaning' => 'Agreement / Protocol',
                'meaning_zh' => '协议',
                'example_sentence' => '达成协议。',
                'example_translation' => 'Reach an agreement.',
                'definition' => 'Agreement, protocol, accord',
                'sentences' => ['___签订。', '___履行。', '___框架。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '冲突',
                'pinyin' => 'chōng tū',
                'simplified' => '冲突',
                'traditional' => '衝突',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Conflict / To clash',
                'meaning_zh' => '冲突',
                'example_sentence' => '武装冲突。',
                'example_translation' => 'Armed conflict.',
                'definition' => 'Conflict, to clash, confrontation',
                'sentences' => ['___解决。', '___爆发。', '___升级。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '制裁',
                'pinyin' => 'zhì cái',
                'simplified' => '制裁',
                'traditional' => '制裁',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Sanction / To sanction',
                'meaning_zh' => '制裁',
                'example_sentence' => '经济制裁。',
                'example_translation' => 'Economic sanctions.',
                'definition' => 'Sanction, to sanction, penalty',
                'sentences' => ['___措施。', '___解除。', '___实施。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '援助',
                'pinyin' => 'yuán zhù',
                'simplified' => '援助',
                'traditional' => '援助',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Aid / To aid',
                'meaning_zh' => '援助',
                'example_sentence' => '人道主义援助。',
                'example_translation' => 'Humanitarian aid.',
                'definition' => 'Aid, to aid, assistance',
                'sentences' => ['___项目。', '___物资。', '___资金。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '移民',
                'pinyin' => 'yí mín',
                'simplified' => '移民',
                'traditional' => '移民',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Immigrant / To immigrate',
                'meaning_zh' => '移民',
                'example_sentence' => '移民政策。',
                'example_translation' => 'Immigration policy.',
                'definition' => 'Immigrant, to immigrate, migration',
                'sentences' => ['___潮。', '___国家。', '___申请。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '难民',
                'pinyin' => 'nàn mín',
                'simplified' => '难民',
                'traditional' => '難民',
                'part_of_speech' => 'noun',
                'meaning' => 'Refugee',
                'meaning_zh' => '难民',
                'example_sentence' => '难民危机。',
                'example_translation' => 'Refugee crisis.',
                'definition' => 'Refugee, displaced person',
                'sentences' => ['___营。', '___安置。', '___问题。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '恐怖主义',
                'pinyin' => 'kǒng bù zhǔ yì',
                'simplified' => '恐怖主义',
                'traditional' => '恐怖主義',
                'part_of_speech' => 'noun',
                'meaning' => 'Terrorism',
                'meaning_zh' => '恐怖主义',
                'example_sentence' => '反对恐怖主义。',
                'example_translation' => 'Oppose terrorism.',
                'definition' => 'Terrorism, terrorist activities',
                'sentences' => ['___威胁。', '___袭击。', '___组织。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '和平',
                'pinyin' => 'hé píng',
                'simplified' => '和平',
                'traditional' => '和平',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Peace / Peaceful',
                'meaning_zh' => '和平',
                'example_sentence' => '维护和平。',
                'example_translation' => 'Maintain peace.',
                'definition' => 'Peace, peaceful',
                'sentences' => ['___谈判。', '___共处。', '___发展。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '战争',
                'pinyin' => 'zhàn zhēng',
                'simplified' => '战争',
                'traditional' => '戰爭',
                'part_of_speech' => 'noun',
                'meaning' => 'War',
                'meaning_zh' => '战争',
                'example_sentence' => '反对战争。',
                'example_translation' => 'Oppose war.',
                'definition' => 'War, warfare',
                'sentences' => ['___爆发。', '___结束。', '___威胁。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '裁军',
                'pinyin' => 'cái jūn',
                'simplified' => '裁军',
                'traditional' => '裁軍',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Disarmament / To disarm',
                'meaning_zh' => '裁军',
                'example_sentence' => '核裁军。',
                'example_translation' => 'Nuclear disarmament.',
                'definition' => 'Disarmament, to disarm',
                'sentences' => ['___谈判。', '___协议。', '___进程。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '合作',
                'pinyin' => 'hé zuò',
                'simplified' => '合作',
                'traditional' => '合作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Cooperation / To cooperate',
                'meaning_zh' => '合作',
                'example_sentence' => '国际合作。',
                'example_translation' => 'International cooperation.',
                'definition' => 'Cooperation, to cooperate, collaboration',
                'sentences' => ['___伙伴。', '___关系。', '___共赢。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '多边',
                'pinyin' => 'duō biān',
                'simplified' => '多边',
                'traditional' => '多邊',
                'part_of_speech' => 'adjective',
                'meaning' => 'Multilateral',
                'meaning_zh' => '多边',
                'example_sentence' => '多边合作。',
                'example_translation' => 'Multilateral cooperation.',
                'definition' => 'Multilateral, multi-party',
                'sentences' => ['___主义。', '___机制。', '___谈判。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 159,
                'word' => '双边',
                'pinyin' => 'shuāng biān',
                'simplified' => '双边',
                'traditional' => '雙邊',
                'part_of_speech' => 'adjective',
                'meaning' => 'Bilateral',
                'meaning_zh' => '双边',
                'example_sentence' => '双边关系。',
                'example_translation' => 'Bilateral relations.',
                'definition' => 'Bilateral, two-sided',
                'sentences' => ['___协议。', '___贸易。', '___会谈。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 160: Culture and Heritage - 文化与遗产
        $cultureVocab = [
            [
                'topic_id' => 160,
                'word' => '遗产',
                'pinyin' => 'yí chǎn',
                'simplified' => '遗产',
                'traditional' => '遺產',
                'part_of_speech' => 'noun',
                'meaning' => 'Heritage / Legacy',
                'meaning_zh' => '遗产',
                'example_sentence' => '文化遗产。',
                'example_translation' => 'Cultural heritage.',
                'definition' => 'Heritage, legacy, inheritance',
                'sentences' => ['___保护。', '___继承。', '___世界。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '传承',
                'pinyin' => 'chuán chéng',
                'simplified' => '传承',
                'traditional' => '傳承',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Inheritance / To inherit',
                'meaning_zh' => '传承',
                'example_sentence' => '文化传承。',
                'example_translation' => 'Cultural inheritance.',
                'definition' => 'Inheritance, to inherit, to pass on',
                'sentences' => ['___发展。', '___创新。', '___保护。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '文明',
                'pinyin' => 'wén míng',
                'simplified' => '文明',
                'traditional' => '文明',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Civilization / Civilized',
                'meaning_zh' => '文明',
                'example_sentence' => '古代文明。',
                'example_translation' => 'Ancient civilization.',
                'definition' => 'Civilization, civilized, culture',
                'sentences' => ['___发展。', '___进步。', '___社会。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '传统',
                'pinyin' => 'chuán tǒng',
                'simplified' => '传统',
                'traditional' => '傳統',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Tradition / Traditional',
                'meaning_zh' => '传统',
                'example_sentence' => '传统文化。',
                'example_translation' => 'Traditional culture.',
                'definition' => 'Tradition, traditional, conventional',
                'sentences' => ['___习俗。', '___观念。', '___节日。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '习俗',
                'pinyin' => 'xí sú',
                'simplified' => '习俗',
                'traditional' => '習俗',
                'part_of_speech' => 'noun',
                'meaning' => 'Custom / Convention',
                'meaning_zh' => '习俗',
                'example_sentence' => '民间习俗。',
                'example_translation' => 'Folk customs.',
                'definition' => 'Custom, convention, tradition',
                'sentences' => ['___风俗。', '___保留。', '___文化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '民族',
                'pinyin' => 'mín zú',
                'simplified' => '民族',
                'traditional' => '民族',
                'part_of_speech' => 'noun',
                'meaning' => 'Nation / Ethnic group',
                'meaning_zh' => '民族',
                'example_sentence' => '少数民族。',
                'example_translation' => 'Ethnic minority.',
                'definition' => 'Nation, ethnic group, nationality',
                'sentences' => ['___文化。', '___特色。', '___团结。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '仪式',
                'pinyin' => 'yí shì',
                'simplified' => '仪式',
                'traditional' => '儀式',
                'part_of_speech' => 'noun',
                'meaning' => 'Ceremony / Ritual',
                'meaning_zh' => '仪式',
                'example_sentence' => '举行仪式。',
                'example_translation' => 'Hold a ceremony.',
                'definition' => 'Ceremony, ritual, rite',
                'sentences' => ['___感。', '___隆重。', '___传统。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '祭祀',
                'pinyin' => 'jì sì',
                'simplified' => '祭祀',
                'traditional' => '祭祀',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Sacrifice / To offer sacrifice',
                'meaning_zh' => '祭祀',
                'example_sentence' => '祭祀祖先。',
                'example_translation' => 'Offer sacrifice to ancestors.',
                'definition' => 'Sacrifice, to offer sacrifice, worship',
                'sentences' => ['___活动。', '___仪式。', '___文化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '古迹',
                'pinyin' => 'gǔ jì',
                'simplified' => '古迹',
                'traditional' => '古蹟',
                'part_of_speech' => 'noun',
                'meaning' => 'Historic site / Ancient relic',
                'meaning_zh' => '古迹',
                'example_sentence' => '参观古迹。',
                'example_translation' => 'Visit historic sites.',
                'definition' => 'Historic site, ancient relic, monument',
                'sentences' => ['___保护。', '___名胜。', '___文物。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '文物',
                'pinyin' => 'wén wù',
                'simplified' => '文物',
                'traditional' => '文物',
                'part_of_speech' => 'noun',
                'meaning' => 'Cultural relic / Artifact',
                'meaning_zh' => '文物',
                'example_sentence' => '保护文物。',
                'example_translation' => 'Protect cultural relics.',
                'definition' => 'Cultural relic, artifact, historical object',
                'sentences' => ['___古迹。', '___修复。', '___价值。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '手工艺',
                'pinyin' => 'shǒu gōng yì',
                'simplified' => '手工艺',
                'traditional' => '手工藝',
                'part_of_speech' => 'noun',
                'meaning' => 'Handicraft / Handiwork',
                'meaning_zh' => '手工艺',
                'example_sentence' => '传统手工艺。',
                'example_translation' => 'Traditional handicraft.',
                'definition' => 'Handicraft, handiwork, craft',
                'sentences' => ['___品。', '___传承。', '___技艺。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '非物质',
                'pinyin' => 'fēi wù zhì',
                'simplified' => '非物质',
                'traditional' => '非物質',
                'part_of_speech' => 'adjective',
                'meaning' => 'Intangible / Non-material',
                'meaning_zh' => '非物质',
                'example_sentence' => '非物质文化遗产。',
                'example_translation' => 'Intangible cultural heritage.',
                'definition' => 'Intangible, non-material, immaterial',
                'sentences' => ['___遗产。', '___文化。', '___保护。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '戏曲',
                'pinyin' => 'xì qǔ',
                'simplified' => '戏曲',
                'traditional' => '戲曲',
                'part_of_speech' => 'noun',
                'meaning' => 'Traditional opera / Drama',
                'meaning_zh' => '戏曲',
                'example_sentence' => '中国戏曲。',
                'example_translation' => 'Chinese opera.',
                'definition' => 'Traditional opera, drama',
                'sentences' => ['___艺术。', '___表演。', '___传统。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '书法',
                'pinyin' => 'shū fǎ',
                'simplified' => '书法',
                'traditional' => '書法',
                'part_of_speech' => 'noun',
                'meaning' => 'Calligraphy',
                'meaning_zh' => '书法',
                'example_sentence' => '练习书法。',
                'example_translation' => 'Practice calligraphy.',
                'definition' => 'Calligraphy, penmanship',
                'sentences' => ['___艺术。', '___作品。', '___家。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '国画',
                'pinyin' => 'guó huà',
                'simplified' => '国画',
                'traditional' => '國畫',
                'part_of_speech' => 'noun',
                'meaning' => 'Chinese painting / Traditional Chinese painting',
                'meaning_zh' => '国画',
                'example_sentence' => '学习国画。',
                'example_translation' => 'Learn Chinese painting.',
                'definition' => 'Chinese painting, traditional Chinese painting',
                'sentences' => ['___艺术。', '___大师。', '___展览。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '武术',
                'pinyin' => 'wǔ shù',
                'simplified' => '武术',
                'traditional' => '武術',
                'part_of_speech' => 'noun',
                'meaning' => 'Martial arts / Wushu',
                'meaning_zh' => '武术',
                'example_sentence' => '练习武术。',
                'example_translation' => 'Practice martial arts.',
                'definition' => 'Martial arts, wushu, kung fu',
                'sentences' => ['___表演。', '___功夫。', '___传统。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '茶道',
                'pinyin' => 'chá dào',
                'simplified' => '茶道',
                'traditional' => '茶道',
                'part_of_speech' => 'noun',
                'meaning' => 'Tea ceremony / Tea culture',
                'meaning_zh' => '茶道',
                'example_sentence' => '学习茶道。',
                'example_translation' => 'Learn tea ceremony.',
                'definition' => 'Tea ceremony, tea culture, way of tea',
                'sentences' => ['___文化。', '___精神。', '___表演。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '建筑',
                'pinyin' => 'jiàn zhù',
                'simplified' => '建筑',
                'traditional' => '建築',
                'part_of_speech' => 'noun',
                'meaning' => 'Architecture / Building',
                'meaning_zh' => '建筑',
                'example_sentence' => '古代建筑。',
                'example_translation' => 'Ancient architecture.',
                'definition' => 'Architecture, building, construction',
                'sentences' => ['___风格。', '___艺术。', '___物。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '园林',
                'pinyin' => 'yuán lín',
                'simplified' => '园林',
                'traditional' => '園林',
                'part_of_speech' => 'noun',
                'meaning' => 'Garden / Landscape garden',
                'meaning_zh' => '园林',
                'example_sentence' => '中国园林。',
                'example_translation' => 'Chinese garden.',
                'definition' => 'Garden, landscape garden, park',
                'sentences' => ['___艺术。', '___设计。', '___景观。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 160,
                'word' => '雕刻',
                'pinyin' => 'diāo kè',
                'simplified' => '雕刻',
                'traditional' => '雕刻',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To carve / Carving',
                'meaning_zh' => '雕刻',
                'example_sentence' => '木雕刻。',
                'example_translation' => 'Wood carving.',
                'definition' => 'To carve, carving, sculpture',
                'sentences' => ['___艺术。', '___技术。', '___作品。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($economyVocab, $globalizationVocab, $cultureVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
