<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic164to166Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [164, 166])->delete();

        // Topic 164: Media and Information - 媒体与信息
        $mediaVocab = [
            [
                'topic_id' => 164,
                'word' => '媒体',
                'pinyin' => 'méi tǐ',
                'simplified' => '媒体',
                'traditional' => '媒體',
                'part_of_speech' => 'noun',
                'meaning' => 'Media',
                'meaning_zh' => '媒体',
                'example_sentence' => '新闻媒体。',
                'example_translation' => 'News media.',
                'definition' => 'Media, mass media',
                'sentences' => ['___报道。', '___传播。', '___平台。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '新闻',
                'pinyin' => 'xīn wén',
                'simplified' => '新闻',
                'traditional' => '新聞',
                'part_of_speech' => 'noun',
                'meaning' => 'News',
                'meaning_zh' => '新闻',
                'example_sentence' => '看新闻。',
                'example_translation' => 'Watch the news.',
                'definition' => 'News, journalism',
                'sentences' => ['___报道。', '___发布。', '___媒体。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '报道',
                'pinyin' => 'bào dào',
                'simplified' => '报道',
                'traditional' => '報導',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To report / Report',
                'meaning_zh' => '报道',
                'example_sentence' => '新闻报道。',
                'example_translation' => 'News report.',
                'definition' => 'To report, report, coverage',
                'sentences' => ['___事件。', '___真实。', '___客观。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '采访',
                'pinyin' => 'cǎi fǎng',
                'simplified' => '采访',
                'traditional' => '採訪',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To interview / Interview',
                'meaning_zh' => '采访',
                'example_sentence' => '记者采访。',
                'example_translation' => 'Reporter interview.',
                'definition' => 'To interview, interview, to cover',
                'sentences' => ['___对象。', '___问题。', '___报道。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '记者',
                'pinyin' => 'jì zhě',
                'simplified' => '记者',
                'traditional' => '記者',
                'part_of_speech' => 'noun',
                'meaning' => 'Reporter / Journalist',
                'meaning_zh' => '记者',
                'example_sentence' => '新闻记者。',
                'example_translation' => 'News reporter.',
                'definition' => 'Reporter, journalist, correspondent',
                'sentences' => ['___采访。', '___会。', '___职业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '编辑',
                'pinyin' => 'biān jí',
                'simplified' => '编辑',
                'traditional' => '編輯',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To edit / Editor',
                'meaning_zh' => '编辑',
                'example_sentence' => '编辑文章。',
                'example_translation' => 'Edit articles.',
                'definition' => 'To edit, editor, to compile',
                'sentences' => ['___工作。', '___部。', '___修改。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '出版',
                'pinyin' => 'chū bǎn',
                'simplified' => '出版',
                'traditional' => '出版',
                'part_of_speech' => 'verb',
                'meaning' => 'To publish / Publication',
                'meaning_zh' => '出版',
                'example_sentence' => '出版书籍。',
                'example_translation' => 'Publish books.',
                'definition' => 'To publish, publication',
                'sentences' => ['___社。', '___物。', '___发行。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '刊登',
                'pinyin' => 'kān dēng',
                'simplified' => '刊登',
                'traditional' => '刊登',
                'part_of_speech' => 'verb',
                'meaning' => 'To publish / To carry (in publication)',
                'meaning_zh' => '刊登',
                'example_sentence' => '刊登广告。',
                'example_translation' => 'Publish advertisements.',
                'definition' => 'To publish, to carry, to print',
                'sentences' => ['___文章。', '___报纸。', '___消息。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '传播',
                'pinyin' => 'chuán bō',
                'simplified' => '传播',
                'traditional' => '傳播',
                'part_of_speech' => 'verb',
                'meaning' => 'To spread / To disseminate',
                'meaning_zh' => '传播',
                'example_sentence' => '信息传播。',
                'example_translation' => 'Information dissemination.',
                'definition' => 'To spread, to disseminate, propagation',
                'sentences' => ['___速度。', '___渠道。', '___广泛。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '舆论',
                'pinyin' => 'yú lùn',
                'simplified' => '舆论',
                'traditional' => '輿論',
                'part_of_speech' => 'noun',
                'meaning' => 'Public opinion',
                'meaning_zh' => '舆论',
                'example_sentence' => '舆论关注。',
                'example_translation' => 'Public opinion attention.',
                'definition' => 'Public opinion, public sentiment',
                'sentences' => ['___导向。', '___压力。', '___影响。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '宣传',
                'pinyin' => 'xuān chuán',
                'simplified' => '宣传',
                'traditional' => '宣傳',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To publicize / Publicity',
                'meaning_zh' => '宣传',
                'example_sentence' => '宣传活动。',
                'example_translation' => 'Publicity activity.',
                'definition' => 'To publicize, publicity, propaganda',
                'sentences' => ['___推广。', '___效果。', '___材料。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '广告',
                'pinyin' => 'guǎng gào',
                'simplified' => '广告',
                'traditional' => '廣告',
                'part_of_speech' => 'noun',
                'meaning' => 'Advertisement / Ad',
                'meaning_zh' => '广告',
                'example_sentence' => '做广告。',
                'example_translation' => 'Make advertisements.',
                'definition' => 'Advertisement, ad, commercial',
                'sentences' => ['___宣传。', '___投放。', '___效果。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '直播',
                'pinyin' => 'zhí bō',
                'simplified' => '直播',
                'traditional' => '直播',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Live broadcast / To broadcast live',
                'meaning_zh' => '直播',
                'example_sentence' => '现场直播。',
                'example_translation' => 'Live broadcast.',
                'definition' => 'Live broadcast, to broadcast live',
                'sentences' => ['___节目。', '___平台。', '___观看。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '转播',
                'pinyin' => 'zhuǎn bō',
                'simplified' => '转播',
                'traditional' => '轉播',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To relay / Relay broadcast',
                'meaning_zh' => '转播',
                'example_sentence' => '卫星转播。',
                'example_translation' => 'Satellite relay.',
                'definition' => 'To relay, relay broadcast, to rebroadcast',
                'sentences' => ['___信号。', '___比赛。', '___权。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '频道',
                'pinyin' => 'pín dào',
                'simplified' => '频道',
                'traditional' => '頻道',
                'part_of_speech' => 'noun',
                'meaning' => 'Channel (TV/radio)',
                'meaning_zh' => '频道',
                'example_sentence' => '电视频道。',
                'example_translation' => 'TV channel.',
                'definition' => 'Channel, frequency',
                'sentences' => ['___切换。', '___节目。', '___收看。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '标题',
                'pinyin' => 'biāo tí',
                'simplified' => '标题',
                'traditional' => '標題',
                'part_of_speech' => 'noun',
                'meaning' => 'Title / Headline',
                'meaning_zh' => '标题',
                'example_sentence' => '文章标题。',
                'example_translation' => 'Article title.',
                'definition' => 'Title, headline, heading',
                'sentences' => ['___醒目。', '___新闻。', '___党。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '版面',
                'pinyin' => 'bǎn miàn',
                'simplified' => '版面',
                'traditional' => '版面',
                'part_of_speech' => 'noun',
                'meaning' => 'Page layout / Edition',
                'meaning_zh' => '版面',
                'example_sentence' => '版面设计。',
                'example_translation' => 'Page layout design.',
                'definition' => 'Page layout, edition, format',
                'sentences' => ['___头条。', '___安排。', '___整洁。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '头条',
                'pinyin' => 'tóu tiáo',
                'simplified' => '头条',
                'traditional' => '頭條',
                'part_of_speech' => 'noun',
                'meaning' => 'Headline / Top news',
                'meaning_zh' => '头条',
                'example_sentence' => '头条新闻。',
                'example_translation' => 'Headline news.',
                'definition' => 'Headline, top news, front page',
                'sentences' => ['___报道。', '___位置。', '___关注。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '虚假',
                'pinyin' => 'xū jiǎ',
                'simplified' => '虚假',
                'traditional' => '虛假',
                'part_of_speech' => 'adjective',
                'meaning' => 'False / Fake',
                'meaning_zh' => '虚假',
                'example_sentence' => '虚假信息。',
                'example_translation' => 'False information.',
                'definition' => 'False, fake, untrue',
                'sentences' => ['___新闻。', '___广告。', '___宣传。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 164,
                'word' => '客观',
                'pinyin' => 'kè guān',
                'simplified' => '客观',
                'traditional' => '客觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Objective / Impartial',
                'meaning_zh' => '客观',
                'example_sentence' => '客观报道。',
                'example_translation' => 'Objective reporting.',
                'definition' => 'Objective, impartial, unbiased',
                'sentences' => ['___公正。', '___事实。', '___评价。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 165: Psychology and Emotions - 心理学与情绪
        $psychologyVocab = [
            [
                'topic_id' => 165,
                'word' => '心理',
                'pinyin' => 'xīn lǐ',
                'simplified' => '心理',
                'traditional' => '心理',
                'part_of_speech' => 'noun',
                'meaning' => 'Psychology / Mental',
                'meaning_zh' => '心理',
                'example_sentence' => '心理健康。',
                'example_translation' => 'Mental health.',
                'definition' => 'Psychology, mental, psychological',
                'sentences' => ['___状态。', '___压力。', '___学。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '情绪',
                'pinyin' => 'qíng xù',
                'simplified' => '情绪',
                'traditional' => '情緒',
                'part_of_speech' => 'noun',
                'meaning' => 'Emotion / Mood',
                'meaning_zh' => '情绪',
                'example_sentence' => '控制情绪。',
                'example_translation' => 'Control emotions.',
                'definition' => 'Emotion, mood, feeling',
                'sentences' => ['___波动。', '___稳定。', '___管理。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '情感',
                'pinyin' => 'qíng gǎn',
                'simplified' => '情感',
                'traditional' => '情感',
                'part_of_speech' => 'noun',
                'meaning' => 'Emotion / Feeling',
                'meaning_zh' => '情感',
                'example_sentence' => '表达情感。',
                'example_translation' => 'Express emotions.',
                'definition' => 'Emotion, feeling, sentiment',
                'sentences' => ['___交流。', '___世界。', '___丰富。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '焦虑',
                'pinyin' => 'jiāo lǜ',
                'simplified' => '焦虑',
                'traditional' => '焦慮',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Anxious / Anxiety',
                'meaning_zh' => '焦虑',
                'example_sentence' => '感到焦虑。',
                'example_translation' => 'Feel anxious.',
                'definition' => 'Anxious, anxiety, worried',
                'sentences' => ['___不安。', '___症。', '___情绪。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '抑郁',
                'pinyin' => 'yì yù',
                'simplified' => '抑郁',
                'traditional' => '抑鬱',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Depressed / Depression',
                'meaning_zh' => '抑郁',
                'example_sentence' => '抑郁症。',
                'example_translation' => 'Depression.',
                'definition' => 'Depressed, depression, melancholy',
                'sentences' => ['___情绪。', '___症状。', '___治疗。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '压力',
                'pinyin' => 'yā lì',
                'simplified' => '压力',
                'traditional' => '壓力',
                'part_of_speech' => 'noun',
                'meaning' => 'Pressure / Stress',
                'meaning_zh' => '压力',
                'example_sentence' => '工作压力。',
                'example_translation' => 'Work pressure.',
                'definition' => 'Pressure, stress, strain',
                'sentences' => ['___大。', '___缓解。', '___管理。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '紧张',
                'pinyin' => 'jǐn zhāng',
                'simplified' => '紧张',
                'traditional' => '緊張',
                'part_of_speech' => 'adjective',
                'meaning' => 'Nervous / Tense',
                'meaning_zh' => '紧张',
                'example_sentence' => '感到紧张。',
                'example_translation' => 'Feel nervous.',
                'definition' => 'Nervous, tense, intense',
                'sentences' => ['___不安。', '___气氛。', '___情绪。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '乐观',
                'pinyin' => 'lè guān',
                'simplified' => '乐观',
                'traditional' => '樂觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Optimistic',
                'meaning_zh' => '乐观',
                'example_sentence' => '保持乐观。',
                'example_translation' => 'Stay optimistic.',
                'definition' => 'Optimistic, positive',
                'sentences' => ['___态度。', '___向上。', '___精神。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '悲观',
                'pinyin' => 'bēi guān',
                'simplified' => '悲观',
                'traditional' => '悲觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Pessimistic',
                'meaning_zh' => '悲观',
                'example_sentence' => '悲观情绪。',
                'example_translation' => 'Pessimistic mood.',
                'definition' => 'Pessimistic, negative',
                'sentences' => ['___态度。', '___失望。', '___预期。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '自信',
                'pinyin' => 'zì xìn',
                'simplified' => '自信',
                'traditional' => '自信',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Confident / Confidence',
                'meaning_zh' => '自信',
                'example_sentence' => '充满自信。',
                'example_translation' => 'Full of confidence.',
                'definition' => 'Confident, confidence, self-confidence',
                'sentences' => ['___心。', '___表现。', '___培养。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '自卑',
                'pinyin' => 'zì bēi',
                'simplified' => '自卑',
                'traditional' => '自卑',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Inferior / Inferiority',
                'meaning_zh' => '自卑',
                'example_sentence' => '自卑感。',
                'example_translation' => 'Sense of inferiority.',
                'definition' => 'Inferior, inferiority, self-abasement',
                'sentences' => ['___心理。', '___感。', '___克服。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '自尊',
                'pinyin' => 'zì zūn',
                'simplified' => '自尊',
                'traditional' => '自尊',
                'part_of_speech' => 'noun',
                'meaning' => 'Self-esteem / Self-respect',
                'meaning_zh' => '自尊',
                'example_sentence' => '维护自尊。',
                'example_translation' => 'Maintain self-esteem.',
                'definition' => 'Self-esteem, self-respect, dignity',
                'sentences' => ['___心。', '___受损。', '___保护。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '同情',
                'pinyin' => 'tóng qíng',
                'simplified' => '同情',
                'traditional' => '同情',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To sympathize / Sympathy',
                'meaning_zh' => '同情',
                'example_sentence' => '表示同情。',
                'example_translation' => 'Express sympathy.',
                'definition' => 'To sympathize, sympathy, compassion',
                'sentences' => ['___心。', '___理解。', '___关怀。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '嫉妒',
                'pinyin' => 'jí dù',
                'simplified' => '嫉妒',
                'traditional' => '嫉妒',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To be jealous / Jealous',
                'meaning_zh' => '嫉妒',
                'example_sentence' => '感到嫉妒。',
                'example_translation' => 'Feel jealous.',
                'definition' => 'To be jealous, jealous, envy',
                'sentences' => ['___心理。', '___别人。', '___羡慕。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '愤怒',
                'pinyin' => 'fèn nù',
                'simplified' => '愤怒',
                'traditional' => '憤怒',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Angry / Anger',
                'meaning_zh' => '愤怒',
                'example_sentence' => '表示愤怒。',
                'example_translation' => 'Express anger.',
                'definition' => 'Angry, anger, indignation',
                'sentences' => ['___情绪。', '___控制。', '___爆发。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '恐惧',
                'pinyin' => 'kǒng jù',
                'simplified' => '恐惧',
                'traditional' => '恐懼',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Fear / To fear',
                'meaning_zh' => '恐惧',
                'example_sentence' => '克服恐惧。',
                'example_translation' => 'Overcome fear.',
                'definition' => 'Fear, to fear, dread',
                'sentences' => ['___感。', '___心理。', '___症。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '欲望',
                'pinyin' => 'yù wàng',
                'simplified' => '欲望',
                'traditional' => '慾望',
                'part_of_speech' => 'noun',
                'meaning' => 'Desire / Appetite',
                'meaning_zh' => '欲望',
                'example_sentence' => '控制欲望。',
                'example_translation' => 'Control desires.',
                'definition' => 'Desire, appetite, craving',
                'sentences' => ['___强烈。', '___满足。', '___膨胀。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '动机',
                'pinyin' => 'dòng jī',
                'simplified' => '动机',
                'traditional' => '動機',
                'part_of_speech' => 'noun',
                'meaning' => 'Motive / Motivation',
                'meaning_zh' => '动机',
                'example_sentence' => '学习动机。',
                'example_translation' => 'Learning motivation.',
                'definition' => 'Motive, motivation, incentive',
                'sentences' => ['___不纯。', '___激发。', '___分析。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '潜意识',
                'pinyin' => 'qián yì shí',
                'simplified' => '潜意识',
                'traditional' => '潛意識',
                'part_of_speech' => 'noun',
                'meaning' => 'Subconscious',
                'meaning_zh' => '潜意识',
                'example_sentence' => '潜意识影响。',
                'example_translation' => 'Subconscious influence.',
                'definition' => 'Subconscious, unconscious mind',
                'sentences' => ['___中。', '___行为。', '___心理。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 165,
                'word' => '直觉',
                'pinyin' => 'zhí jué',
                'simplified' => '直觉',
                'traditional' => '直覺',
                'part_of_speech' => 'noun',
                'meaning' => 'Intuition / Instinct',
                'meaning_zh' => '直觉',
                'example_sentence' => '凭直觉。',
                'example_translation' => 'By intuition.',
                'definition' => 'Intuition, instinct, gut feeling',
                'sentences' => ['___判断。', '___敏锐。', '___感觉。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 166: Character and Personality - 性格与品格
        $characterVocab = [
            [
                'topic_id' => 166,
                'word' => '性格',
                'pinyin' => 'xìng gé',
                'simplified' => '性格',
                'traditional' => '性格',
                'part_of_speech' => 'noun',
                'meaning' => 'Character / Personality',
                'meaning_zh' => '性格',
                'example_sentence' => '开朗的性格。',
                'example_translation' => 'Cheerful personality.',
                'definition' => 'Character, personality, temperament',
                'sentences' => ['___特点。', '___形成。', '___温和。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '品格',
                'pinyin' => 'pǐn gé',
                'simplified' => '品格',
                'traditional' => '品格',
                'part_of_speech' => 'noun',
                'meaning' => 'Character / Moral character',
                'meaning_zh' => '品格',
                'example_sentence' => '高尚品格。',
                'example_translation' => 'Noble character.',
                'definition' => 'Character, moral character, quality',
                'sentences' => ['___高尚。', '___培养。', '___修养。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '气质',
                'pinyin' => 'qì zhì',
                'simplified' => '气质',
                'traditional' => '氣質',
                'part_of_speech' => 'noun',
                'meaning' => 'Temperament / Manner',
                'meaning_zh' => '气质',
                'example_sentence' => '优雅气质。',
                'example_translation' => 'Elegant temperament.',
                'definition' => 'Temperament, manner, disposition',
                'sentences' => ['___独特。', '___高雅。', '___出众。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '诚实',
                'pinyin' => 'chéng shí',
                'simplified' => '诚实',
                'traditional' => '誠實',
                'part_of_speech' => 'adjective',
                'meaning' => 'Honest / Truthful',
                'meaning_zh' => '诚实',
                'example_sentence' => '诚实守信。',
                'example_translation' => 'Honest and trustworthy.',
                'definition' => 'Honest, truthful, sincere',
                'sentences' => ['___可靠。', '___品质。', '___做人。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '谦虚',
                'pinyin' => 'qiān xū',
                'simplified' => '谦虚',
                'traditional' => '謙虛',
                'part_of_speech' => 'adjective',
                'meaning' => 'Modest / Humble',
                'meaning_zh' => '谦虚',
                'example_sentence' => '为人谦虚。',
                'example_translation' => 'Be modest.',
                'definition' => 'Modest, humble, unassuming',
                'sentences' => ['___态度。', '___低调。', '___学习。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '骄傲',
                'pinyin' => 'jiāo ào',
                'simplified' => '骄傲',
                'traditional' => '驕傲',
                'part_of_speech' => 'adjective',
                'meaning' => 'Proud / Arrogant',
                'meaning_zh' => '骄傲',
                'example_sentence' => '感到骄傲。',
                'example_translation' => 'Feel proud.',
                'definition' => 'Proud, arrogant, pride',
                'sentences' => ['___自满。', '___成绩。', '___情绪。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '勇敢',
                'pinyin' => 'yǒng gǎn',
                'simplified' => '勇敢',
                'traditional' => '勇敢',
                'part_of_speech' => 'adjective',
                'meaning' => 'Brave / Courageous',
                'meaning_zh' => '勇敢',
                'example_sentence' => '勇敢面对。',
                'example_translation' => 'Bravely face.',
                'definition' => 'Brave, courageous, bold',
                'sentences' => ['___精神。', '___挑战。', '___无畏。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '懦弱',
                'pinyin' => 'nuò ruò',
                'simplified' => '懦弱',
                'traditional' => '懦弱',
                'part_of_speech' => 'adjective',
                'meaning' => 'Cowardly / Weak',
                'meaning_zh' => '懦弱',
                'example_sentence' => '性格懦弱。',
                'example_translation' => 'Cowardly character.',
                'definition' => 'Cowardly, weak, timid',
                'sentences' => ['___胆小。', '___克服。', '___表现。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '坚强',
                'pinyin' => 'jiān qiáng',
                'simplified' => '坚强',
                'traditional' => '堅強',
                'part_of_speech' => 'adjective',
                'meaning' => 'Strong / Firm',
                'meaning_zh' => '坚强',
                'example_sentence' => '意志坚强。',
                'example_translation' => 'Strong will.',
                'definition' => 'Strong, firm, resilient',
                'sentences' => ['___勇敢。', '___不屈。', '___精神。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '脆弱',
                'pinyin' => 'cuì ruò',
                'simplified' => '脆弱',
                'traditional' => '脆弱',
                'part_of_speech' => 'adjective',
                'meaning' => 'Fragile / Vulnerable',
                'meaning_zh' => '脆弱',
                'example_sentence' => '心理脆弱。',
                'example_translation' => 'Psychologically fragile.',
                'definition' => 'Fragile, vulnerable, delicate',
                'sentences' => ['___敏感。', '___内心。', '___情感。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '慷慨',
                'pinyin' => 'kāng kǎi',
                'simplified' => '慷慨',
                'traditional' => '慷慨',
                'part_of_speech' => 'adjective',
                'meaning' => 'Generous',
                'meaning_zh' => '慷慨',
                'example_sentence' => '慷慨大方。',
                'example_translation' => 'Generous and magnanimous.',
                'definition' => 'Generous, liberal, magnanimous',
                'sentences' => ['___解囊。', '___捐赠。', '___行为。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '吝啬',
                'pinyin' => 'lìn sè',
                'simplified' => '吝啬',
                'traditional' => '吝嗇',
                'part_of_speech' => 'adjective',
                'meaning' => 'Stingy / Miserly',
                'meaning_zh' => '吝啬',
                'example_sentence' => '为人吝啬。',
                'example_translation' => 'Be stingy.',
                'definition' => 'Stingy, miserly, mean',
                'sentences' => ['___小气。', '___性格。', '___鬼。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '宽容',
                'pinyin' => 'kuān róng',
                'simplified' => '宽容',
                'traditional' => '寬容',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Tolerant / To tolerate',
                'meaning_zh' => '宽容',
                'example_sentence' => '宽容待人。',
                'example_translation' => 'Treat others with tolerance.',
                'definition' => 'Tolerant, to tolerate, lenient',
                'sentences' => ['___大度。', '___理解。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '固执',
                'pinyin' => 'gù zhí',
                'simplified' => '固执',
                'traditional' => '固執',
                'part_of_speech' => 'adjective',
                'meaning' => 'Stubborn / Obstinate',
                'meaning_zh' => '固执',
                'example_sentence' => '性格固执。',
                'example_translation' => 'Stubborn character.',
                'definition' => 'Stubborn, obstinate, headstrong',
                'sentences' => ['___己见。', '___不化。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '灵活',
                'pinyin' => 'líng huó',
                'simplified' => '灵活',
                'traditional' => '靈活',
                'part_of_speech' => 'adjective',
                'meaning' => 'Flexible / Agile',
                'meaning_zh' => '灵活',
                'example_sentence' => '思维灵活。',
                'example_translation' => 'Flexible thinking.',
                'definition' => 'Flexible, agile, nimble',
                'sentences' => ['___变通。', '___应对。', '___性。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '热情',
                'pinyin' => 'rè qíng',
                'simplified' => '热情',
                'traditional' => '熱情',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Enthusiastic / Enthusiasm',
                'meaning_zh' => '热情',
                'example_sentence' => '热情待人。',
                'example_translation' => 'Treat people with enthusiasm.',
                'definition' => 'Enthusiastic, enthusiasm, passionate',
                'sentences' => ['___高涨。', '___洋溢。', '___服务。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '冷漠',
                'pinyin' => 'lěng mò',
                'simplified' => '冷漠',
                'traditional' => '冷漠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Indifferent / Cold',
                'meaning_zh' => '冷漠',
                'example_sentence' => '态度冷漠。',
                'example_translation' => 'Indifferent attitude.',
                'definition' => 'Indifferent, cold, apathetic',
                'sentences' => ['___无情。', '___对待。', '___表情。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '真诚',
                'pinyin' => 'zhēn chéng',
                'simplified' => '真诚',
                'traditional' => '真誠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sincere / Genuine',
                'meaning_zh' => '真诚',
                'example_sentence' => '真诚待人。',
                'example_translation' => 'Treat people sincerely.',
                'definition' => 'Sincere, genuine, heartfelt',
                'sentences' => ['___诚实。', '___友谊。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '虚伪',
                'pinyin' => 'xū wěi',
                'simplified' => '虚伪',
                'traditional' => '虛偽',
                'part_of_speech' => 'adjective',
                'meaning' => 'Hypocritical / False',
                'meaning_zh' => '虚伪',
                'example_sentence' => '虚伪的人。',
                'example_translation' => 'Hypocritical person.',
                'definition' => 'Hypocritical, false, insincere',
                'sentences' => ['___做作。', '___面具。', '___表现。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 166,
                'word' => '毅力',
                'pinyin' => 'yì lì',
                'simplified' => '毅力',
                'traditional' => '毅力',
                'part_of_speech' => 'noun',
                'meaning' => 'Willpower / Perseverance',
                'meaning_zh' => '毅力',
                'example_sentence' => '坚强毅力。',
                'example_translation' => 'Strong willpower.',
                'definition' => 'Willpower, perseverance, determination',
                'sentences' => ['___坚持。', '___培养。', '___惊人。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($mediaVocab, $psychologyVocab, $characterVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
