<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic167to169Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [167, 169])->delete();

        // Topic 167: Philosophy and Values - 哲学与价值观
        $philosophyVocab = [
            [
                'topic_id' => 167,
                'word' => '哲学',
                'pinyin' => 'zhé xué',
                'simplified' => '哲学',
                'traditional' => '哲學',
                'part_of_speech' => 'noun',
                'meaning' => 'Philosophy',
                'meaning_zh' => '哲学',
                'example_sentence' => '研究哲学。',
                'example_translation' => 'Study philosophy.',
                'definition' => 'Philosophy, philosophical thought',
                'sentences' => ['___思想。', '___家。', '___观点。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '价值观',
                'pinyin' => 'jià zhí guān',
                'simplified' => '价值观',
                'traditional' => '價值觀',
                'part_of_speech' => 'noun',
                'meaning' => 'Values / Value system',
                'meaning_zh' => '价值观',
                'example_sentence' => '树立正确的价值观。',
                'example_translation' => 'Establish correct values.',
                'definition' => 'Values, value system, worldview',
                'sentences' => ['___不同。', '___形成。', '___教育。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '世界观',
                'pinyin' => 'shì jiè guān',
                'simplified' => '世界观',
                'traditional' => '世界觀',
                'part_of_speech' => 'noun',
                'meaning' => 'Worldview / Outlook on life',
                'meaning_zh' => '世界观',
                'example_sentence' => '改变世界观。',
                'example_translation' => 'Change worldview.',
                'definition' => 'Worldview, outlook on the world',
                'sentences' => ['___人生观。', '___形成。', '___不同。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '人生观',
                'pinyin' => 'rén shēng guān',
                'simplified' => '人生观',
                'traditional' => '人生觀',
                'part_of_speech' => 'noun',
                'meaning' => 'Outlook on life / Life philosophy',
                'meaning_zh' => '人生观',
                'example_sentence' => '积极的人生观。',
                'example_translation' => 'Positive outlook on life.',
                'definition' => 'Outlook on life, life philosophy',
                'sentences' => ['___价值观。', '___树立。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '真理',
                'pinyin' => 'zhēn lǐ',
                'simplified' => '真理',
                'traditional' => '真理',
                'part_of_speech' => 'noun',
                'meaning' => 'Truth',
                'meaning_zh' => '真理',
                'example_sentence' => '追求真理。',
                'example_translation' => 'Pursue truth.',
                'definition' => 'Truth, verity',
                'sentences' => ['___探索。', '___掌握。', '___永恒。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '本质',
                'pinyin' => 'běn zhì',
                'simplified' => '本质',
                'traditional' => '本質',
                'part_of_speech' => 'noun',
                'meaning' => 'Essence / Nature',
                'meaning_zh' => '本质',
                'example_sentence' => '事物的本质。',
                'example_translation' => 'The essence of things.',
                'definition' => 'Essence, nature, substance',
                'sentences' => ['___特征。', '___认识。', '___区别。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '观念',
                'pinyin' => 'guān niàn',
                'simplified' => '观念',
                'traditional' => '觀念',
                'part_of_speech' => 'noun',
                'meaning' => 'Concept / Notion',
                'meaning_zh' => '观念',
                'example_sentence' => '改变观念。',
                'example_translation' => 'Change concepts.',
                'definition' => 'Concept, notion, idea',
                'sentences' => ['___更新。', '___传统。', '___转变。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '意义',
                'pinyin' => 'yì yì',
                'simplified' => '意义',
                'traditional' => '意義',
                'part_of_speech' => 'noun',
                'meaning' => 'Meaning / Significance',
                'meaning_zh' => '意义',
                'example_sentence' => '重大意义。',
                'example_translation' => 'Great significance.',
                'definition' => 'Meaning, significance, sense',
                'sentences' => ['___深远。', '___重大。', '___理解。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '存在',
                'pinyin' => 'cún zài',
                'simplified' => '存在',
                'traditional' => '存在',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To exist / Existence',
                'meaning_zh' => '存在',
                'example_sentence' => '客观存在。',
                'example_translation' => 'Objective existence.',
                'definition' => 'To exist, existence, being',
                'sentences' => ['___问题。', '___价值。', '___意义。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '理性',
                'pinyin' => 'lǐ xìng',
                'simplified' => '理性',
                'traditional' => '理性',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Reason / Rational',
                'meaning_zh' => '理性',
                'example_sentence' => '理性思考。',
                'example_translation' => 'Think rationally.',
                'definition' => 'Reason, rational, rationality',
                'sentences' => ['___感性。', '___分析。', '___判断。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '感性',
                'pinyin' => 'gǎn xìng',
                'simplified' => '感性',
                'traditional' => '感性',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Perceptual / Emotional',
                'meaning_zh' => '感性',
                'example_sentence' => '感性认识。',
                'example_translation' => 'Perceptual knowledge.',
                'definition' => 'Perceptual, emotional, sensibility',
                'sentences' => ['___理性。', '___认知。', '___思维。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '逻辑',
                'pinyin' => 'luó ji',
                'simplified' => '逻辑',
                'traditional' => '邏輯',
                'part_of_speech' => 'noun',
                'meaning' => 'Logic',
                'meaning_zh' => '逻辑',
                'example_sentence' => '逻辑思维。',
                'example_translation' => 'Logical thinking.',
                'definition' => 'Logic, reasoning',
                'sentences' => ['___关系。', '___推理。', '___清晰。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '辩证',
                'pinyin' => 'biàn zhèng',
                'simplified' => '辩证',
                'traditional' => '辯證',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Dialectical / To analyze dialectically',
                'meaning_zh' => '辩证',
                'example_sentence' => '辩证思维。',
                'example_translation' => 'Dialectical thinking.',
                'definition' => 'Dialectical, to analyze dialectically',
                'sentences' => ['___唯物。', '___法。', '___关系。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '唯物',
                'pinyin' => 'wéi wù',
                'simplified' => '唯物',
                'traditional' => '唯物',
                'part_of_speech' => 'adjective',
                'meaning' => 'Materialistic',
                'meaning_zh' => '唯物',
                'example_sentence' => '唯物主义。',
                'example_translation' => 'Materialism.',
                'definition' => 'Materialistic, material',
                'sentences' => ['___主义。', '___辩证法。', '___观点。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '唯心',
                'pinyin' => 'wéi xīn',
                'simplified' => '唯心',
                'traditional' => '唯心',
                'part_of_speech' => 'adjective',
                'meaning' => 'Idealistic',
                'meaning_zh' => '唯心',
                'example_sentence' => '唯心主义。',
                'example_translation' => 'Idealism.',
                'definition' => 'Idealistic, idealist',
                'sentences' => ['___主义。', '___观点。', '___思想。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '客观',
                'pinyin' => 'kè guān',
                'simplified' => '客观',
                'traditional' => '客觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Objective',
                'meaning_zh' => '客观',
                'example_sentence' => '客观事实。',
                'example_translation' => 'Objective fact.',
                'definition' => 'Objective, impartial',
                'sentences' => ['___主观。', '___规律。', '___分析。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '主观',
                'pinyin' => 'zhǔ guān',
                'simplified' => '主观',
                'traditional' => '主觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Subjective',
                'meaning_zh' => '主观',
                'example_sentence' => '主观想法。',
                'example_translation' => 'Subjective idea.',
                'definition' => 'Subjective, personal',
                'sentences' => ['___客观。', '___臆断。', '___意识。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '抽象',
                'pinyin' => 'chōu xiàng',
                'simplified' => '抽象',
                'traditional' => '抽象',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Abstract / To abstract',
                'meaning_zh' => '抽象',
                'example_sentence' => '抽象概念。',
                'example_translation' => 'Abstract concept.',
                'definition' => 'Abstract, to abstract',
                'sentences' => ['___具体。', '___思维。', '___艺术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '具体',
                'pinyin' => 'jù tǐ',
                'simplified' => '具体',
                'traditional' => '具體',
                'part_of_speech' => 'adjective',
                'meaning' => 'Concrete / Specific',
                'meaning_zh' => '具体',
                'example_sentence' => '具体问题。',
                'example_translation' => 'Concrete problem.',
                'definition' => 'Concrete, specific, detailed',
                'sentences' => ['___抽象。', '___情况。', '___措施。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 167,
                'word' => '永恒',
                'pinyin' => 'yǒng héng',
                'simplified' => '永恒',
                'traditional' => '永恆',
                'part_of_speech' => 'adjective',
                'meaning' => 'Eternal / Everlasting',
                'meaning_zh' => '永恒',
                'example_sentence' => '永恒的真理。',
                'example_translation' => 'Eternal truth.',
                'definition' => 'Eternal, everlasting, perpetual',
                'sentences' => ['___不变。', '___主题。', '___价值。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 168: Morality and Ethics - 道德与伦理
        $moralityVocab = [
            [
                'topic_id' => 168,
                'word' => '道德',
                'pinyin' => 'dào dé',
                'simplified' => '道德',
                'traditional' => '道德',
                'part_of_speech' => 'noun',
                'meaning' => 'Morality / Ethics',
                'meaning_zh' => '道德',
                'example_sentence' => '社会道德。',
                'example_translation' => 'Social morality.',
                'definition' => 'Morality, ethics, moral',
                'sentences' => ['___标准。', '___规范。', '___品质。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '伦理',
                'pinyin' => 'lún lǐ',
                'simplified' => '伦理',
                'traditional' => '倫理',
                'part_of_speech' => 'noun',
                'meaning' => 'Ethics / Moral principles',
                'meaning_zh' => '伦理',
                'example_sentence' => '医学伦理。',
                'example_translation' => 'Medical ethics.',
                'definition' => 'Ethics, moral principles',
                'sentences' => ['___道德。', '___规范。', '___观念。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '良心',
                'pinyin' => 'liáng xīn',
                'simplified' => '良心',
                'traditional' => '良心',
                'part_of_speech' => 'noun',
                'meaning' => 'Conscience',
                'meaning_zh' => '良心',
                'example_sentence' => '凭良心。',
                'example_translation' => 'By conscience.',
                'definition' => 'Conscience, moral sense',
                'sentences' => ['___发现。', '___谴责。', '___问题。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '正义',
                'pinyin' => 'zhèng yì',
                'simplified' => '正义',
                'traditional' => '正義',
                'part_of_speech' => 'noun',
                'meaning' => 'Justice / Righteousness',
                'meaning_zh' => '正义',
                'example_sentence' => '伸张正义。',
                'example_translation' => 'Uphold justice.',
                'definition' => 'Justice, righteousness, just',
                'sentences' => ['___感。', '___公平。', '___维护。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '善良',
                'pinyin' => 'shàn liáng',
                'simplified' => '善良',
                'traditional' => '善良',
                'part_of_speech' => 'adjective',
                'meaning' => 'Kind / Kindhearted',
                'meaning_zh' => '善良',
                'example_sentence' => '善良的人。',
                'example_translation' => 'Kind person.',
                'definition' => 'Kind, kindhearted, good-natured',
                'sentences' => ['___心地。', '___本性。', '___待人。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '邪恶',
                'pinyin' => 'xié è',
                'simplified' => '邪恶',
                'traditional' => '邪惡',
                'part_of_speech' => 'adjective',
                'meaning' => 'Evil / Wicked',
                'meaning_zh' => '邪恶',
                'example_sentence' => '邪恶势力。',
                'example_translation' => 'Evil forces.',
                'definition' => 'Evil, wicked, sinister',
                'sentences' => ['___力量。', '___行为。', '___念头。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '美德',
                'pinyin' => 'měi dé',
                'simplified' => '美德',
                'traditional' => '美德',
                'part_of_speech' => 'noun',
                'meaning' => 'Virtue',
                'meaning_zh' => '美德',
                'example_sentence' => '传统美德。',
                'example_translation' => 'Traditional virtue.',
                'definition' => 'Virtue, moral excellence',
                'sentences' => ['___传承。', '___品质。', '___弘扬。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '恶习',
                'pinyin' => 'è xí',
                'simplified' => '恶习',
                'traditional' => '惡習',
                'part_of_speech' => 'noun',
                'meaning' => 'Bad habit / Vice',
                'meaning_zh' => '恶习',
                'example_sentence' => '改掉恶习。',
                'example_translation' => 'Get rid of bad habits.',
                'definition' => 'Bad habit, vice, bad practice',
                'sentences' => ['___不良。', '___纠正。', '___戒除。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '诚信',
                'pinyin' => 'chéng xìn',
                'simplified' => '诚信',
                'traditional' => '誠信',
                'part_of_speech' => 'noun',
                'meaning' => 'Integrity / Honesty',
                'meaning_zh' => '诚信',
                'example_sentence' => '讲诚信。',
                'example_translation' => 'Be honest.',
                'definition' => 'Integrity, honesty, credibility',
                'sentences' => ['___经营。', '___建设。', '___体系。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '欺骗',
                'pinyin' => 'qī piàn',
                'simplified' => '欺骗',
                'traditional' => '欺騙',
                'part_of_speech' => 'verb',
                'meaning' => 'To deceive / To cheat',
                'meaning_zh' => '欺骗',
                'example_sentence' => '不要欺骗别人。',
                'example_translation' => 'Don\'t deceive others.',
                'definition' => 'To deceive, to cheat, to trick',
                'sentences' => ['___行为。', '___消费者。', '___感情。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '责任',
                'pinyin' => 'zé rèn',
                'simplified' => '责任',
                'traditional' => '責任',
                'part_of_speech' => 'noun',
                'meaning' => 'Responsibility / Duty',
                'meaning_zh' => '责任',
                'example_sentence' => '承担责任。',
                'example_translation' => 'Bear responsibility.',
                'definition' => 'Responsibility, duty, obligation',
                'sentences' => ['___感。', '___重大。', '___履行。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '义务',
                'pinyin' => 'yì wù',
                'simplified' => '义务',
                'traditional' => '義務',
                'part_of_speech' => 'noun',
                'meaning' => 'Duty / Obligation',
                'meaning_zh' => '义务',
                'example_sentence' => '履行义务。',
                'example_translation' => 'Fulfill obligations.',
                'definition' => 'Duty, obligation, compulsory',
                'sentences' => ['___教育。', '___权利。', '___兵。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '尊重',
                'pinyin' => 'zūn zhòng',
                'simplified' => '尊重',
                'traditional' => '尊重',
                'part_of_speech' => 'verb',
                'meaning' => 'To respect',
                'meaning_zh' => '尊重',
                'example_sentence' => '互相尊重。',
                'example_translation' => 'Mutual respect.',
                'definition' => 'To respect, respect',
                'sentences' => ['___他人。', '___意见。', '___选择。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '侮辱',
                'pinyin' => 'wǔ rǔ',
                'simplified' => '侮辱',
                'traditional' => '侮辱',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To insult / Insult',
                'meaning_zh' => '侮辱',
                'example_sentence' => '人格侮辱。',
                'example_translation' => 'Personal insult.',
                'definition' => 'To insult, insult, to humiliate',
                'sentences' => ['___人格。', '___行为。', '___诽谤。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '羞耻',
                'pinyin' => 'xiū chǐ',
                'simplified' => '羞耻',
                'traditional' => '羞恥',
                'part_of_speech' => 'noun',
                'meaning' => 'Shame / Disgrace',
                'meaning_zh' => '羞耻',
                'example_sentence' => '感到羞耻。',
                'example_translation' => 'Feel ashamed.',
                'definition' => 'Shame, disgrace, humiliation',
                'sentences' => ['___心。', '___感。', '___无耻。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '荣誉',
                'pinyin' => 'róng yù',
                'simplified' => '荣誉',
                'traditional' => '榮譽',
                'part_of_speech' => 'noun',
                'meaning' => 'Honor / Glory',
                'meaning_zh' => '荣誉',
                'example_sentence' => '获得荣誉。',
                'example_translation' => 'Receive honor.',
                'definition' => 'Honor, glory, reputation',
                'sentences' => ['___称号。', '___感。', '___奖励。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '奉献',
                'pinyin' => 'fèng xiàn',
                'simplified' => '奉献',
                'traditional' => '奉獻',
                'part_of_speech' => 'verb',
                'meaning' => 'To dedicate / To devote',
                'meaning_zh' => '奉献',
                'example_sentence' => '无私奉献。',
                'example_translation' => 'Selfless dedication.',
                'definition' => 'To dedicate, to devote, dedication',
                'sentences' => ['___精神。', '___社会。', '___爱心。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '自私',
                'pinyin' => 'zì sī',
                'simplified' => '自私',
                'traditional' => '自私',
                'part_of_speech' => 'adjective',
                'meaning' => 'Selfish',
                'meaning_zh' => '自私',
                'example_sentence' => '不要自私。',
                'example_translation' => 'Don\'t be selfish.',
                'definition' => 'Selfish, self-centered',
                'sentences' => ['___自利。', '___行为。', '___无私。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '忠诚',
                'pinyin' => 'zhōng chéng',
                'simplified' => '忠诚',
                'traditional' => '忠誠',
                'part_of_speech' => 'adjective',
                'meaning' => 'Loyal / Faithful',
                'meaning_zh' => '忠诚',
                'example_sentence' => '忠诚可靠。',
                'example_translation' => 'Loyal and reliable.',
                'definition' => 'Loyal, faithful, devoted',
                'sentences' => ['___度。', '___朋友。', '___事业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 168,
                'word' => '背叛',
                'pinyin' => 'bèi pàn',
                'simplified' => '背叛',
                'traditional' => '背叛',
                'part_of_speech' => 'verb',
                'meaning' => 'To betray',
                'meaning_zh' => '背叛',
                'example_sentence' => '背叛朋友。',
                'example_translation' => 'Betray friends.',
                'definition' => 'To betray, betrayal',
                'sentences' => ['___信任。', '___行为。', '___者。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 169: Happiness and Success - 幸福与成功
        $happinessVocab = [
            [
                'topic_id' => 169,
                'word' => '幸福',
                'pinyin' => 'xìng fú',
                'simplified' => '幸福',
                'traditional' => '幸福',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Happy / Happiness',
                'meaning_zh' => '幸福',
                'example_sentence' => '感到幸福。',
                'example_translation' => 'Feel happy.',
                'definition' => 'Happy, happiness, well-being',
                'sentences' => ['___生活。', '___感。', '___美满。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '快乐',
                'pinyin' => 'kuài lè',
                'simplified' => '快乐',
                'traditional' => '快樂',
                'part_of_speech' => 'adjective',
                'meaning' => 'Happy / Joyful',
                'meaning_zh' => '快乐',
                'example_sentence' => '生活快乐。',
                'example_translation' => 'Live happily.',
                'definition' => 'Happy, joyful, cheerful',
                'sentences' => ['___成长。', '___时光。', '___心情。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '满足',
                'pinyin' => 'mǎn zú',
                'simplified' => '满足',
                'traditional' => '滿足',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To satisfy / Satisfied',
                'meaning_zh' => '满足',
                'example_sentence' => '感到满足。',
                'example_translation' => 'Feel satisfied.',
                'definition' => 'To satisfy, satisfied, content',
                'sentences' => ['___需求。', '___感。', '___条件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '成功',
                'pinyin' => 'chéng gōng',
                'simplified' => '成功',
                'traditional' => '成功',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Success / To succeed',
                'meaning_zh' => '成功',
                'example_sentence' => '取得成功。',
                'example_translation' => 'Achieve success.',
                'definition' => 'Success, to succeed, successful',
                'sentences' => ['___失败。', '___经验。', '___人士。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '失败',
                'pinyin' => 'shī bài',
                'simplified' => '失败',
                'traditional' => '失敗',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Failure / To fail',
                'meaning_zh' => '失败',
                'example_sentence' => '遭遇失败。',
                'example_translation' => 'Encounter failure.',
                'definition' => 'Failure, to fail, unsuccessful',
                'sentences' => ['___成功。', '___教训。', '___原因。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '成就',
                'pinyin' => 'chéng jiù',
                'simplified' => '成就',
                'traditional' => '成就',
                'part_of_speech' => 'noun',
                'meaning' => 'Achievement / Accomplishment',
                'meaning_zh' => '成就',
                'example_sentence' => '伟大成就。',
                'example_translation' => 'Great achievement.',
                'definition' => 'Achievement, accomplishment',
                'sentences' => ['___感。', '___辉煌。', '___取得。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '目标',
                'pinyin' => 'mù biāo',
                'simplified' => '目标',
                'traditional' => '目標',
                'part_of_speech' => 'noun',
                'meaning' => 'Goal / Objective',
                'meaning_zh' => '目标',
                'example_sentence' => '实现目标。',
                'example_translation' => 'Achieve goals.',
                'definition' => 'Goal, objective, target',
                'sentences' => ['___明确。', '___达成。', '___设定。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '理想',
                'pinyin' => 'lǐ xiǎng',
                'simplified' => '理想',
                'traditional' => '理想',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Ideal / Perfect',
                'meaning_zh' => '理想',
                'example_sentence' => '实现理想。',
                'example_translation' => 'Realize ideals.',
                'definition' => 'Ideal, perfect, aspiration',
                'sentences' => ['___信念。', '___状态。', '___追求。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '梦想',
                'pinyin' => 'mèng xiǎng',
                'simplified' => '梦想',
                'traditional' => '夢想',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Dream / To dream',
                'meaning_zh' => '梦想',
                'example_sentence' => '追求梦想。',
                'example_translation' => 'Pursue dreams.',
                'definition' => 'Dream, to dream, aspiration',
                'sentences' => ['___成真。', '___实现。', '___追逐。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '奋斗',
                'pinyin' => 'fèn dòu',
                'simplified' => '奋斗',
                'traditional' => '奮鬥',
                'part_of_speech' => 'verb',
                'meaning' => 'To struggle / To strive',
                'meaning_zh' => '奋斗',
                'example_sentence' => '努力奋斗。',
                'example_translation' => 'Strive hard.',
                'definition' => 'To struggle, to strive, to fight',
                'sentences' => ['___目标。', '___精神。', '___历程。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '拼搏',
                'pinyin' => 'pīn bó',
                'simplified' => '拼搏',
                'traditional' => '拼搏',
                'part_of_speech' => 'verb',
                'meaning' => 'To struggle / To fight',
                'meaning_zh' => '拼搏',
                'example_sentence' => '努力拼搏。',
                'example_translation' => 'Fight hard.',
                'definition' => 'To struggle, to fight, to strive',
                'sentences' => ['___进取。', '___精神。', '___事业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '坚持',
                'pinyin' => 'jiān chí',
                'simplified' => '坚持',
                'traditional' => '堅持',
                'part_of_speech' => 'verb',
                'meaning' => 'To persist / To insist',
                'meaning_zh' => '坚持',
                'example_sentence' => '坚持不懈。',
                'example_translation' => 'Persist unremittingly.',
                'definition' => 'To persist, to insist, to uphold',
                'sentences' => ['___原则。', '___梦想。', '___努力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '毅力',
                'pinyin' => 'yì lì',
                'simplified' => '毅力',
                'traditional' => '毅力',
                'part_of_speech' => 'noun',
                'meaning' => 'Willpower / Perseverance',
                'meaning_zh' => '毅力',
                'example_sentence' => '需要毅力。',
                'example_translation' => 'Need perseverance.',
                'definition' => 'Willpower, perseverance, stamina',
                'sentences' => ['___坚强。', '___培养。', '___考验。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '进取',
                'pinyin' => 'jìn qǔ',
                'simplified' => '进取',
                'traditional' => '進取',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'Enterprising / To forge ahead',
                'meaning_zh' => '进取',
                'example_sentence' => '积极进取。',
                'example_translation' => 'Be enterprising.',
                'definition' => 'Enterprising, to forge ahead',
                'sentences' => ['___精神。', '___心。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '勤奋',
                'pinyin' => 'qín fèn',
                'simplified' => '勤奋',
                'traditional' => '勤奮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Diligent / Hardworking',
                'meaning_zh' => '勤奋',
                'example_sentence' => '勤奋学习。',
                'example_translation' => 'Study diligently.',
                'definition' => 'Diligent, hardworking, industrious',
                'sentences' => ['___努力。', '___工作。', '___精神。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '懒惰',
                'pinyin' => 'lǎn duò',
                'simplified' => '懒惰',
                'traditional' => '懶惰',
                'part_of_speech' => 'adjective',
                'meaning' => 'Lazy / Indolent',
                'meaning_zh' => '懒惰',
                'example_sentence' => '不要懒惰。',
                'example_translation' => 'Don\'t be lazy.',
                'definition' => 'Lazy, indolent, slothful',
                'sentences' => ['___勤奋。', '___习惯。', '___克服。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '财富',
                'pinyin' => 'cái fù',
                'simplified' => '财富',
                'traditional' => '財富',
                'part_of_speech' => 'noun',
                'meaning' => 'Wealth / Fortune',
                'meaning_zh' => '财富',
                'example_sentence' => '创造财富。',
                'example_translation' => 'Create wealth.',
                'definition' => 'Wealth, fortune, riches',
                'sentences' => ['___积累。', '___精神。', '___分配。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '贫穷',
                'pinyin' => 'pín qióng',
                'simplified' => '贫穷',
                'traditional' => '貧窮',
                'part_of_speech' => 'adjective',
                'meaning' => 'Poor / Impoverished',
                'meaning_zh' => '贫穷',
                'example_sentence' => '摆脱贫穷。',
                'example_translation' => 'Get out of poverty.',
                'definition' => 'Poor, impoverished, poverty',
                'sentences' => ['___富裕。', '___落后。', '___地区。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '机遇',
                'pinyin' => 'jī yù',
                'simplified' => '机遇',
                'traditional' => '機遇',
                'part_of_speech' => 'noun',
                'meaning' => 'Opportunity / Chance',
                'meaning_zh' => '机遇',
                'example_sentence' => '抓住机遇。',
                'example_translation' => 'Seize the opportunity.',
                'definition' => 'Opportunity, chance, favorable occasion',
                'sentences' => ['___挑战。', '___难得。', '___把握。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 169,
                'word' => '挫折',
                'pinyin' => 'cuò zhé',
                'simplified' => '挫折',
                'traditional' => '挫折',
                'part_of_speech' => 'noun',
                'meaning' => 'Setback / Frustration',
                'meaning_zh' => '挫折',
                'example_sentence' => '面对挫折。',
                'example_translation' => 'Face setbacks.',
                'definition' => 'Setback, frustration, defeat',
                'sentences' => ['___困难。', '___克服。', '___教育。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($philosophyVocab, $moralityVocab, $happinessVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
