<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic179to181Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [179, 181])->delete();

        // Topic 179: Social Media and Influence - 社交媒体与影响力
        $socialMediaVocab = [
            [
                'topic_id' => 179,
                'word' => '社交',
                'pinyin' => 'shè jiāo',
                'simplified' => '社交',
                'traditional' => '社交',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Social / To socialize',
                'meaning_zh' => '社交',
                'example_sentence' => '社交媒体。',
                'example_translation' => 'Social media.',
                'definition' => 'Social, to socialize, social interaction',
                'sentences' => ['___网络。', '___平台。', '___能力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '平台',
                'pinyin' => 'píng tái',
                'simplified' => '平台',
                'traditional' => '平台',
                'part_of_speech' => 'noun',
                'meaning' => 'Platform',
                'meaning_zh' => '平台',
                'example_sentence' => '网络平台。',
                'example_translation' => 'Online platform.',
                'definition' => 'Platform, stage',
                'sentences' => ['___服务。', '___建设。', '___经济。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '发布',
                'pinyin' => 'fā bù',
                'simplified' => '发布',
                'traditional' => '發布',
                'part_of_speech' => 'verb',
                'meaning' => 'To publish / To release',
                'meaning_zh' => '发布',
                'example_sentence' => '发布消息。',
                'example_translation' => 'Publish news.',
                'definition' => 'To publish, to release, to announce',
                'sentences' => ['___信息。', '___会。', '___内容。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '分享',
                'pinyin' => 'fēn xiǎng',
                'simplified' => '分享',
                'traditional' => '分享',
                'part_of_speech' => 'verb',
                'meaning' => 'To share',
                'meaning_zh' => '分享',
                'example_sentence' => '分享经验。',
                'example_translation' => 'Share experience.',
                'definition' => 'To share, sharing',
                'sentences' => ['___生活。', '___快乐。', '___链接。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '转发',
                'pinyin' => 'zhuǎn fā',
                'simplified' => '转发',
                'traditional' => '轉發',
                'part_of_speech' => 'verb',
                'meaning' => 'To forward / To repost',
                'meaning_zh' => '转发',
                'example_sentence' => '转发微博。',
                'example_translation' => 'Repost Weibo.',
                'definition' => 'To forward, to repost',
                'sentences' => ['___消息。', '___朋友圈。', '___评论。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '点赞',
                'pinyin' => 'diǎn zàn',
                'simplified' => '点赞',
                'traditional' => '點贊',
                'part_of_speech' => 'verb',
                'meaning' => 'To like / To give a thumbs up',
                'meaning_zh' => '点赞',
                'example_sentence' => '为他点赞。',
                'example_translation' => 'Give him a like.',
                'definition' => 'To like, to give a thumbs up',
                'sentences' => ['___数量。', '___评论。', '___支持。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '评论',
                'pinyin' => 'píng lùn',
                'simplified' => '评论',
                'traditional' => '評論',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Comment / To comment',
                'meaning_zh' => '评论',
                'example_sentence' => '发表评论。',
                'example_translation' => 'Make a comment.',
                'definition' => 'Comment, to comment, review',
                'sentences' => ['___区。', '___家。', '___文章。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '关注',
                'pinyin' => 'guān zhù',
                'simplified' => '关注',
                'traditional' => '關注',
                'part_of_speech' => 'verb',
                'meaning' => 'To follow / To pay attention to',
                'meaning_zh' => '关注',
                'example_sentence' => '关注热点。',
                'example_translation' => 'Follow hot topics.',
                'definition' => 'To follow, to pay attention to',
                'sentences' => ['___度。', '___者。', '___公众号。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '取消关注',
                'pinyin' => 'qǔ xiāo guān zhù',
                'simplified' => '取消关注',
                'traditional' => '取消關注',
                'part_of_speech' => 'verb',
                'meaning' => 'To unfollow',
                'meaning_zh' => '取消关注',
                'example_sentence' => '取消关注他。',
                'example_translation' => 'Unfollow him.',
                'definition' => 'To unfollow, to stop following',
                'sentences' => ['___账号。', '___好友。', '___博主。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '私信',
                'pinyin' => 'sī xìn',
                'simplified' => '私信',
                'traditional' => '私信',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Private message / To send PM',
                'meaning_zh' => '私信',
                'example_sentence' => '发私信。',
                'example_translation' => 'Send a private message.',
                'definition' => 'Private message, to send PM, DM',
                'sentences' => ['___联系。', '___回复。', '___沟通。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '互动',
                'pinyin' => 'hù dòng',
                'simplified' => '互动',
                'traditional' => '互動',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Interaction / To interact',
                'meaning_zh' => '互动',
                'example_sentence' => '加强互动。',
                'example_translation' => 'Strengthen interaction.',
                'definition' => 'Interaction, to interact',
                'sentences' => ['___交流。', '___性。', '___平台。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '博主',
                'pinyin' => 'bó zhǔ',
                'simplified' => '博主',
                'traditional' => '博主',
                'part_of_speech' => 'noun',
                'meaning' => 'Blogger / Vlogger',
                'meaning_zh' => '博主',
                'example_sentence' => '知名博主。',
                'example_translation' => 'Famous blogger.',
                'definition' => 'Blogger, vlogger, blog owner',
                'sentences' => ['___推荐。', '___分享。', '___美妆。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '内容',
                'pinyin' => 'nèi róng',
                'simplified' => '内容',
                'traditional' => '內容',
                'part_of_speech' => 'noun',
                'meaning' => 'Content',
                'meaning_zh' => '内容',
                'example_sentence' => '优质内容。',
                'example_translation' => 'Quality content.',
                'definition' => 'Content, substance',
                'sentences' => ['___创作。', '___丰富。', '___营销。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '流量',
                'pinyin' => 'liú liàng',
                'simplified' => '流量',
                'traditional' => '流量',
                'part_of_speech' => 'noun',
                'meaning' => 'Traffic / Flow',
                'meaning_zh' => '流量',
                'example_sentence' => '网络流量。',
                'example_translation' => 'Internet traffic.',
                'definition' => 'Traffic, flow, data usage',
                'sentences' => ['___明星。', '___数据。', '___变现。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '曝光',
                'pinyin' => 'bào guāng',
                'simplified' => '曝光',
                'traditional' => '曝光',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Exposure / To expose',
                'meaning_zh' => '曝光',
                'example_sentence' => '增加曝光率。',
                'example_translation' => 'Increase exposure rate.',
                'definition' => 'Exposure, to expose',
                'sentences' => ['___度。', '___率。', '___丑闻。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '炒作',
                'pinyin' => 'chǎo zuò',
                'simplified' => '炒作',
                'traditional' => '炒作',
                'part_of_speech' => 'verb',
                'meaning' => 'To hype / To speculate',
                'meaning_zh' => '炒作',
                'example_sentence' => '恶意炒作。',
                'example_translation' => 'Malicious hype.',
                'definition' => 'To hype, to speculate, hype',
                'sentences' => ['___话题。', '___新闻。', '___热点。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '舆论',
                'pinyin' => 'yú lùn',
                'simplified' => '舆论',
                'traditional' => '輿論',
                'part_of_speech' => 'noun',
                'meaning' => 'Public opinion',
                'meaning_zh' => '舆论',
                'example_sentence' => '引导舆论。',
                'example_translation' => 'Guide public opinion.',
                'definition' => 'Public opinion, public sentiment',
                'sentences' => ['___压力。', '___导向。', '___监督。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '谣言',
                'pinyin' => 'yáo yán',
                'simplified' => '谣言',
                'traditional' => '謠言',
                'part_of_speech' => 'noun',
                'meaning' => 'Rumor',
                'meaning_zh' => '谣言',
                'example_sentence' => '传播谣言。',
                'example_translation' => 'Spread rumors.',
                'definition' => 'Rumor, false information',
                'sentences' => ['___止于智者。', '___澄清。', '___不实。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '审核',
                'pinyin' => 'shěn hé',
                'simplified' => '审核',
                'traditional' => '審核',
                'part_of_speech' => 'verb',
                'meaning' => 'To review / To examine',
                'meaning_zh' => '审核',
                'example_sentence' => '内容审核。',
                'example_translation' => 'Content review.',
                'definition' => 'To review, to examine, audit',
                'sentences' => ['___机制。', '___通过。', '___标准。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 179,
                'word' => '屏蔽',
                'pinyin' => 'píng bì',
                'simplified' => '屏蔽',
                'traditional' => '屏蔽',
                'part_of_speech' => 'verb',
                'meaning' => 'To block / To shield',
                'meaning_zh' => '屏蔽',
                'example_sentence' => '屏蔽广告。',
                'example_translation' => 'Block ads.',
                'definition' => 'To block, to shield, to screen',
                'sentences' => ['___好友。', '___信息。', '___功能。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 180: Critical Thinking - 批判性思维
        $criticalThinkingVocab = [
            [
                'topic_id' => 180,
                'word' => '批判',
                'pinyin' => 'pī pàn',
                'simplified' => '批判',
                'traditional' => '批判',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Criticism / To criticize',
                'meaning_zh' => '批判',
                'example_sentence' => '批判性思维。',
                'example_translation' => 'Critical thinking.',
                'definition' => 'Criticism, to criticize, critique',
                'sentences' => ['___精神。', '___态度。', '___分析。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '思维',
                'pinyin' => 'sī wéi',
                'simplified' => '思维',
                'traditional' => '思維',
                'part_of_speech' => 'noun',
                'meaning' => 'Thinking / Thought',
                'meaning_zh' => '思维',
                'example_sentence' => '逻辑思维。',
                'example_translation' => 'Logical thinking.',
                'definition' => 'Thinking, thought, mentality',
                'sentences' => ['___方式。', '___能力。', '___模式。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '质疑',
                'pinyin' => 'zhì yí',
                'simplified' => '质疑',
                'traditional' => '質疑',
                'part_of_speech' => 'verb',
                'meaning' => 'To question / To doubt',
                'meaning_zh' => '质疑',
                'example_sentence' => '提出质疑。',
                'example_translation' => 'Raise questions.',
                'definition' => 'To question, to doubt, query',
                'sentences' => ['___精神。', '___声音。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '怀疑',
                'pinyin' => 'huái yí',
                'simplified' => '怀疑',
                'traditional' => '懷疑',
                'part_of_speech' => 'verb',
                'meaning' => 'To doubt / To suspect',
                'meaning_zh' => '怀疑',
                'example_sentence' => '怀疑态度。',
                'example_translation' => 'Doubtful attitude.',
                'definition' => 'To doubt, to suspect, suspicion',
                'sentences' => ['___论。', '___主义。', '___精神。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '判断',
                'pinyin' => 'pàn duàn',
                'simplified' => '判断',
                'traditional' => '判斷',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To judge / Judgment',
                'meaning_zh' => '判断',
                'example_sentence' => '做出判断。',
                'example_translation' => 'Make a judgment.',
                'definition' => 'To judge, judgment, to determine',
                'sentences' => ['___能力。', '___标准。', '___正确。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '推断',
                'pinyin' => 'tuī duàn',
                'simplified' => '推断',
                'traditional' => '推斷',
                'part_of_speech' => 'verb',
                'meaning' => 'To infer / To deduce',
                'meaning_zh' => '推断',
                'example_sentence' => '合理推断。',
                'example_translation' => 'Reasonable inference.',
                'definition' => 'To infer, to deduce, inference',
                'sentences' => ['___结论。', '___过程。', '___依据。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '论证',
                'pinyin' => 'lùn zhèng',
                'simplified' => '论证',
                'traditional' => '論證',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To demonstrate / Argumentation',
                'meaning_zh' => '论证',
                'example_sentence' => '严密论证。',
                'example_translation' => 'Rigorous argumentation.',
                'definition' => 'To demonstrate, argumentation, proof',
                'sentences' => ['___过程。', '___充分。', '___方法。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '反驳',
                'pinyin' => 'fǎn bó',
                'simplified' => '反驳',
                'traditional' => '反駁',
                'part_of_speech' => 'verb',
                'meaning' => 'To refute / To rebut',
                'meaning_zh' => '反驳',
                'example_sentence' => '有力反驳。',
                'example_translation' => 'Powerful refutation.',
                'definition' => 'To refute, to rebut, refutation',
                'sentences' => ['___观点。', '___谣言。', '___证据。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '反思',
                'pinyin' => 'fǎn sī',
                'simplified' => '反思',
                'traditional' => '反思',
                'part_of_speech' => 'verb',
                'meaning' => 'To reflect / To rethink',
                'meaning_zh' => '反思',
                'example_sentence' => '深刻反思。',
                'example_translation' => 'Deep reflection.',
                'definition' => 'To reflect, to rethink, reflection',
                'sentences' => ['___自己。', '___错误。', '___总结。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '客观',
                'pinyin' => 'kè guān',
                'simplified' => '客观',
                'traditional' => '客觀',
                'part_of_speech' => 'adjective',
                'meaning' => 'Objective / Impartial',
                'meaning_zh' => '客观',
                'example_sentence' => '客观分析。',
                'example_translation' => 'Objective analysis.',
                'definition' => 'Objective, impartial',
                'sentences' => ['___事实。', '___评价。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '偏见',
                'pinyin' => 'piān jiàn',
                'simplified' => '偏见',
                'traditional' => '偏見',
                'part_of_speech' => 'noun',
                'meaning' => 'Prejudice / Bias',
                'meaning_zh' => '偏见',
                'example_sentence' => '消除偏见。',
                'example_translation' => 'Eliminate prejudice.',
                'definition' => 'Prejudice, bias, preconception',
                'sentences' => ['___歧视。', '___态度。', '___观念。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '片面',
                'pinyin' => 'piàn miàn',
                'simplified' => '片面',
                'traditional' => '片面',
                'part_of_speech' => 'adjective',
                'meaning' => 'One-sided / Partial',
                'meaning_zh' => '片面',
                'example_sentence' => '片面观点。',
                'example_translation' => 'One-sided view.',
                'definition' => 'One-sided, partial, biased',
                'sentences' => ['___性。', '___理解。', '___看法。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '全面',
                'pinyin' => 'quán miàn',
                'simplified' => '全面',
                'traditional' => '全面',
                'part_of_speech' => 'adjective',
                'meaning' => 'Comprehensive / All-round',
                'meaning_zh' => '全面',
                'example_sentence' => '全面分析。',
                'example_translation' => 'Comprehensive analysis.',
                'definition' => 'Comprehensive, all-round, overall',
                'sentences' => ['___发展。', '___考虑。', '___了解。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '深入',
                'pinyin' => 'shēn rù',
                'simplified' => '深入',
                'traditional' => '深入',
                'part_of_speech' => 'adjective/verb',
                'meaning' => 'In-depth / To go deep into',
                'meaning_zh' => '深入',
                'example_sentence' => '深入研究。',
                'example_translation' => 'In-depth research.',
                'definition' => 'In-depth, to go deep into, thorough',
                'sentences' => ['___了解。', '___分析。', '___探讨。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '肤浅',
                'pinyin' => 'fū qiǎn',
                'simplified' => '肤浅',
                'traditional' => '膚淺',
                'part_of_speech' => 'adjective',
                'meaning' => 'Superficial / Shallow',
                'meaning_zh' => '肤浅',
                'example_sentence' => '认识肤浅。',
                'example_translation' => 'Superficial understanding.',
                'definition' => 'Superficial, shallow',
                'sentences' => ['___理解。', '___看法。', '___知识。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '严谨',
                'pinyin' => 'yán jǐn',
                'simplified' => '严谨',
                'traditional' => '嚴謹',
                'part_of_speech' => 'adjective',
                'meaning' => 'Rigorous / Strict',
                'meaning_zh' => '严谨',
                'example_sentence' => '态度严谨。',
                'example_translation' => 'Rigorous attitude.',
                'definition' => 'Rigorous, strict, meticulous',
                'sentences' => ['___治学。', '___逻辑。', '___作风。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '求证',
                'pinyin' => 'qiú zhèng',
                'simplified' => '求证',
                'traditional' => '求證',
                'part_of_speech' => 'verb',
                'meaning' => 'To verify / To seek proof',
                'meaning_zh' => '求证',
                'example_sentence' => '实事求证。',
                'example_translation' => 'Seek truth from facts.',
                'definition' => 'To verify, to seek proof',
                'sentences' => ['___真相。', '___事实。', '___过程。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '辨别',
                'pinyin' => 'biàn bié',
                'simplified' => '辨别',
                'traditional' => '辨別',
                'part_of_speech' => 'verb',
                'meaning' => 'To distinguish / To identify',
                'meaning_zh' => '辨别',
                'example_sentence' => '辨别真假。',
                'example_translation' => 'Distinguish true from false.',
                'definition' => 'To distinguish, to identify, to discern',
                'sentences' => ['___能力。', '___是非。', '___方向。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '甄别',
                'pinyin' => 'zhēn bié',
                'simplified' => '甄别',
                'traditional' => '甄別',
                'part_of_speech' => 'verb',
                'meaning' => 'To screen / To distinguish',
                'meaning_zh' => '甄别',
                'example_sentence' => '甄别信息。',
                'example_translation' => 'Screen information.',
                'definition' => 'To screen, to distinguish, to identify',
                'sentences' => ['___真伪。', '___选拔。', '___审查。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 180,
                'word' => '独立思考',
                'pinyin' => 'dú lì sī kǎo',
                'simplified' => '独立思考',
                'traditional' => '獨立思考',
                'part_of_speech' => 'verb',
                'meaning' => 'Independent thinking',
                'meaning_zh' => '独立思考',
                'example_sentence' => '培养独立思考能力。',
                'example_translation' => 'Develop independent thinking ability.',
                'definition' => 'Independent thinking',
                'sentences' => ['___能力。', '___精神。', '___习惯。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 181: Argumentation and Discussion - 论证与讨论
        $argumentationVocab = [
            [
                'topic_id' => 181,
                'word' => '观点',
                'pinyin' => 'guān diǎn',
                'simplified' => '观点',
                'traditional' => '觀點',
                'part_of_speech' => 'noun',
                'meaning' => 'Viewpoint / Opinion',
                'meaning_zh' => '观点',
                'example_sentence' => '表达观点。',
                'example_translation' => 'Express viewpoint.',
                'definition' => 'Viewpoint, opinion, perspective',
                'sentences' => ['___不同。', '___明确。', '___鲜明。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '立场',
                'pinyin' => 'lì chǎng',
                'simplified' => '立场',
                'traditional' => '立場',
                'part_of_speech' => 'noun',
                'meaning' => 'Position / Stance',
                'meaning_zh' => '立场',
                'example_sentence' => '坚定立场。',
                'example_translation' => 'Firm position.',
                'definition' => 'Position, stance, standpoint',
                'sentences' => ['___态度。', '___一致。', '___明确。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '论点',
                'pinyin' => 'lùn diǎn',
                'simplified' => '论点',
                'traditional' => '論點',
                'part_of_speech' => 'noun',
                'meaning' => 'Argument / Point',
                'meaning_zh' => '论点',
                'example_sentence' => '提出论点。',
                'example_translation' => 'Present an argument.',
                'definition' => 'Argument, point, thesis',
                'sentences' => ['___清晰。', '___论据。', '___支持。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '论据',
                'pinyin' => 'lùn jù',
                'simplified' => '论据',
                'traditional' => '論據',
                'part_of_speech' => 'noun',
                'meaning' => 'Evidence / Argument',
                'meaning_zh' => '论据',
                'example_sentence' => '充分论据。',
                'example_translation' => 'Sufficient evidence.',
                'definition' => 'Evidence, argument, grounds',
                'sentences' => ['___充足。', '___支撑。', '___有力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '辩论',
                'pinyin' => 'biàn lùn',
                'simplified' => '辩论',
                'traditional' => '辯論',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Debate / To debate',
                'meaning_zh' => '辩论',
                'example_sentence' => '激烈辩论。',
                'example_translation' => 'Heated debate.',
                'definition' => 'Debate, to debate, argument',
                'sentences' => ['___赛。', '___技巧。', '___会。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '争论',
                'pinyin' => 'zhēng lùn',
                'simplified' => '争论',
                'traditional' => '爭論',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Argument / To argue',
                'meaning_zh' => '争论',
                'example_sentence' => '引发争论。',
                'example_translation' => 'Trigger argument.',
                'definition' => 'Argument, to argue, dispute',
                'sentences' => ['___不休。', '___焦点。', '___问题。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '讨论',
                'pinyin' => 'tǎo lùn',
                'simplified' => '讨论',
                'traditional' => '討論',
                'part_of_speech' => 'verb',
                'meaning' => 'To discuss / Discussion',
                'meaning_zh' => '讨论',
                'example_sentence' => '展开讨论。',
                'example_translation' => 'Start a discussion.',
                'definition' => 'To discuss, discussion',
                'sentences' => ['___会。', '___问题。', '___热烈。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '阐述',
                'pinyin' => 'chǎn shù',
                'simplified' => '阐述',
                'traditional' => '闡述',
                'part_of_speech' => 'verb',
                'meaning' => 'To expound / To elaborate',
                'meaning_zh' => '阐述',
                'example_sentence' => '详细阐述。',
                'example_translation' => 'Elaborate in detail.',
                'definition' => 'To expound, to elaborate, exposition',
                'sentences' => ['___观点。', '___理论。', '___清楚。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '陈述',
                'pinyin' => 'chén shù',
                'simplified' => '陈述',
                'traditional' => '陳述',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To state / Statement',
                'meaning_zh' => '陈述',
                'example_sentence' => '客观陈述。',
                'example_translation' => 'Objective statement.',
                'definition' => 'To state, statement',
                'sentences' => ['___事实。', '___意见。', '___清楚。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '反对',
                'pinyin' => 'fǎn duì',
                'simplified' => '反对',
                'traditional' => '反對',
                'part_of_speech' => 'verb',
                'meaning' => 'To oppose / To object',
                'meaning_zh' => '反对',
                'example_sentence' => '强烈反对。',
                'example_translation' => 'Strongly oppose.',
                'definition' => 'To oppose, to object, opposition',
                'sentences' => ['___意见。', '___声音。', '___派。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '赞成',
                'pinyin' => 'zàn chéng',
                'simplified' => '赞成',
                'traditional' => '贊成',
                'part_of_speech' => 'verb',
                'meaning' => 'To agree / To approve',
                'meaning_zh' => '赞成',
                'example_sentence' => '完全赞成。',
                'example_translation' => 'Completely agree.',
                'definition' => 'To agree, to approve, approval',
                'sentences' => ['___票。', '___意见。', '___支持。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '认同',
                'pinyin' => 'rèn tóng',
                'simplified' => '认同',
                'traditional' => '認同',
                'part_of_speech' => 'verb',
                'meaning' => 'To identify with / To agree',
                'meaning_zh' => '认同',
                'example_sentence' => '获得认同。',
                'example_translation' => 'Gain recognition.',
                'definition' => 'To identify with, to agree, recognition',
                'sentences' => ['___感。', '___观点。', '___价值。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '共识',
                'pinyin' => 'gòng shí',
                'simplified' => '共识',
                'traditional' => '共識',
                'part_of_speech' => 'noun',
                'meaning' => 'Consensus',
                'meaning_zh' => '共识',
                'example_sentence' => '达成共识。',
                'example_translation' => 'Reach consensus.',
                'definition' => 'Consensus, common understanding',
                'sentences' => ['___形成。', '___广泛。', '___社会。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '分歧',
                'pinyin' => 'fēn qí',
                'simplified' => '分歧',
                'traditional' => '分歧',
                'part_of_speech' => 'noun',
                'meaning' => 'Divergence / Disagreement',
                'meaning_zh' => '分歧',
                'example_sentence' => '存在分歧。',
                'example_translation' => 'There are disagreements.',
                'definition' => 'Divergence, disagreement, difference',
                'sentences' => ['___严重。', '___缩小。', '___解决。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '争议',
                'pinyin' => 'zhēng yì',
                'simplified' => '争议',
                'traditional' => '爭議',
                'part_of_speech' => 'noun',
                'meaning' => 'Controversy / Dispute',
                'meaning_zh' => '争议',
                'example_sentence' => '引起争议。',
                'example_translation' => 'Cause controversy.',
                'definition' => 'Controversy, dispute',
                'sentences' => ['___话题。', '___很大。', '___解决。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '妥协',
                'pinyin' => 'tuǒ xié',
                'simplified' => '妥协',
                'traditional' => '妥協',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To compromise / Compromise',
                'meaning_zh' => '妥协',
                'example_sentence' => '互相妥协。',
                'example_translation' => 'Mutual compromise.',
                'definition' => 'To compromise, compromise',
                'sentences' => ['___方案。', '___让步。', '___态度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '说服',
                'pinyin' => 'shuō fú',
                'simplified' => '说服',
                'traditional' => '說服',
                'part_of_speech' => 'verb',
                'meaning' => 'To persuade / To convince',
                'meaning_zh' => '说服',
                'example_sentence' => '说服他人。',
                'example_translation' => 'Persuade others.',
                'definition' => 'To persuade, to convince',
                'sentences' => ['___力。', '___工作。', '___成功。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '驳斥',
                'pinyin' => 'bó chì',
                'simplified' => '驳斥',
                'traditional' => '駁斥',
                'part_of_speech' => 'verb',
                'meaning' => 'To refute / To denounce',
                'meaning_zh' => '驳斥',
                'example_sentence' => '严厉驳斥。',
                'example_translation' => 'Severely refute.',
                'definition' => 'To refute, to denounce',
                'sentences' => ['___谬论。', '___观点。', '___有力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '结论',
                'pinyin' => 'jié lùn',
                'simplified' => '结论',
                'traditional' => '結論',
                'part_of_speech' => 'noun',
                'meaning' => 'Conclusion',
                'meaning_zh' => '结论',
                'example_sentence' => '得出结论。',
                'example_translation' => 'Draw a conclusion.',
                'definition' => 'Conclusion, finding',
                'sentences' => ['___正确。', '___下。', '___性。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 181,
                'word' => '总结',
                'pinyin' => 'zǒng jié',
                'simplified' => '总结',
                'traditional' => '總結',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To summarize / Summary',
                'meaning_zh' => '总结',
                'example_sentence' => '工作总结。',
                'example_translation' => 'Work summary.',
                'definition' => 'To summarize, summary',
                'sentences' => ['___经验。', '___报告。', '___会议。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($socialMediaVocab, $criticalThinkingVocab, $argumentationVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
