<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic170to172Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [170, 172])->delete();

        // Topic 170: Science and Innovation - 科学与创新
        $scienceVocab = [
            [
                'topic_id' => 170,
                'word' => '科学',
                'pinyin' => 'kē xué',
                'simplified' => '科学',
                'traditional' => '科學',
                'part_of_speech' => 'noun',
                'meaning' => 'Science',
                'meaning_zh' => '科学',
                'example_sentence' => '科学技术发展迅速。',
                'example_translation' => 'Science and technology develop rapidly.',
                'definition' => 'Science, scientific',
                'sentences' => ['___研究。', '___发展。', '___家。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '创新',
                'pinyin' => 'chuàng xīn',
                'simplified' => '创新',
                'traditional' => '創新',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Innovation / To innovate',
                'meaning_zh' => '创新',
                'example_sentence' => '鼓励科技创新。',
                'example_translation' => 'Encourage technological innovation.',
                'definition' => 'Innovation, to innovate, creative',
                'sentences' => ['___能力。', '___精神。', '___发展。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '发明',
                'pinyin' => 'fā míng',
                'simplified' => '发明',
                'traditional' => '發明',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To invent / Invention',
                'meaning_zh' => '发明',
                'example_sentence' => '伟大的发明。',
                'example_translation' => 'Great invention.',
                'definition' => 'To invent, invention',
                'sentences' => ['___创造。', '___专利。', '___家。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '研究',
                'pinyin' => 'yán jiū',
                'simplified' => '研究',
                'traditional' => '研究',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Research / To research',
                'meaning_zh' => '研究',
                'example_sentence' => '科学研究。',
                'example_translation' => 'Scientific research.',
                'definition' => 'Research, to research, to study',
                'sentences' => ['___成果。', '___项目。', '___院。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '实验',
                'pinyin' => 'shí yàn',
                'simplified' => '实验',
                'traditional' => '實驗',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Experiment / To experiment',
                'meaning_zh' => '实验',
                'example_sentence' => '做实验。',
                'example_translation' => 'Conduct an experiment.',
                'definition' => 'Experiment, to experiment, test',
                'sentences' => ['___室。', '___结果。', '___数据。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '理论',
                'pinyin' => 'lǐ lùn',
                'simplified' => '理论',
                'traditional' => '理論',
                'part_of_speech' => 'noun',
                'meaning' => 'Theory',
                'meaning_zh' => '理论',
                'example_sentence' => '理论和实践。',
                'example_translation' => 'Theory and practice.',
                'definition' => 'Theory, theoretical',
                'sentences' => ['___基础。', '___研究。', '___体系。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '假设',
                'pinyin' => 'jiǎ shè',
                'simplified' => '假设',
                'traditional' => '假設',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Hypothesis / To hypothesize',
                'meaning_zh' => '假设',
                'example_sentence' => '提出假设。',
                'example_translation' => 'Propose a hypothesis.',
                'definition' => 'Hypothesis, to hypothesize, to assume',
                'sentences' => ['___验证。', '___条件。', '___理论。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '证明',
                'pinyin' => 'zhèng míng',
                'simplified' => '证明',
                'traditional' => '證明',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To prove / Proof',
                'meaning_zh' => '证明',
                'example_sentence' => '科学证明。',
                'example_translation' => 'Scientific proof.',
                'definition' => 'To prove, proof, to demonstrate',
                'sentences' => ['___事实。', '___材料。', '___文件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '发现',
                'pinyin' => 'fā xiàn',
                'simplified' => '发现',
                'traditional' => '發現',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To discover / Discovery',
                'meaning_zh' => '发现',
                'example_sentence' => '重大发现。',
                'example_translation' => 'Major discovery.',
                'definition' => 'To discover, discovery, to find',
                'sentences' => ['___问题。', '___新事物。', '___规律。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '突破',
                'pinyin' => 'tū pò',
                'simplified' => '突破',
                'traditional' => '突破',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Breakthrough / To break through',
                'meaning_zh' => '突破',
                'example_sentence' => '技术突破。',
                'example_translation' => 'Technological breakthrough.',
                'definition' => 'Breakthrough, to break through',
                'sentences' => ['___瓶颈。', '___创新。', '___进展。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '成果',
                'pinyin' => 'chéng guǒ',
                'simplified' => '成果',
                'traditional' => '成果',
                'part_of_speech' => 'noun',
                'meaning' => 'Achievement / Result',
                'meaning_zh' => '成果',
                'example_sentence' => '研究成果。',
                'example_translation' => 'Research achievements.',
                'definition' => 'Achievement, result, fruit',
                'sentences' => ['___显著。', '___转化。', '___丰硕。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '应用',
                'pinyin' => 'yìng yòng',
                'simplified' => '应用',
                'traditional' => '應用',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To apply / Application',
                'meaning_zh' => '应用',
                'example_sentence' => '技术应用。',
                'example_translation' => 'Technology application.',
                'definition' => 'To apply, application, practical',
                'sentences' => ['___广泛。', '___领域。', '___软件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '探索',
                'pinyin' => 'tàn suǒ',
                'simplified' => '探索',
                'traditional' => '探索',
                'part_of_speech' => 'verb',
                'meaning' => 'To explore / To probe',
                'meaning_zh' => '探索',
                'example_sentence' => '科学探索。',
                'example_translation' => 'Scientific exploration.',
                'definition' => 'To explore, to probe, exploration',
                'sentences' => ['___未知。', '___道路。', '___精神。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '观察',
                'pinyin' => 'guān chá',
                'simplified' => '观察',
                'traditional' => '觀察',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To observe / Observation',
                'meaning_zh' => '观察',
                'example_sentence' => '仔细观察。',
                'example_translation' => 'Observe carefully.',
                'definition' => 'To observe, observation',
                'sentences' => ['___现象。', '___记录。', '___力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '分析',
                'pinyin' => 'fēn xī',
                'simplified' => '分析',
                'traditional' => '分析',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To analyze / Analysis',
                'meaning_zh' => '分析',
                'example_sentence' => '数据分析。',
                'example_translation' => 'Data analysis.',
                'definition' => 'To analyze, analysis',
                'sentences' => ['___结果。', '___原因。', '___方法。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '推理',
                'pinyin' => 'tuī lǐ',
                'simplified' => '推理',
                'traditional' => '推理',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To reason / Reasoning',
                'meaning_zh' => '推理',
                'example_sentence' => '逻辑推理。',
                'example_translation' => 'Logical reasoning.',
                'definition' => 'To reason, reasoning, to deduce',
                'sentences' => ['___能力。', '___过程。', '___小说。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '精确',
                'pinyin' => 'jīng què',
                'simplified' => '精确',
                'traditional' => '精確',
                'part_of_speech' => 'adjective',
                'meaning' => 'Precise / Accurate',
                'meaning_zh' => '精确',
                'example_sentence' => '精确测量。',
                'example_translation' => 'Precise measurement.',
                'definition' => 'Precise, accurate, exact',
                'sentences' => ['___数据。', '___计算。', '___度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '准确',
                'pinyin' => 'zhǔn què',
                'simplified' => '准确',
                'traditional' => '準確',
                'part_of_speech' => 'adjective',
                'meaning' => 'Accurate / Exact',
                'meaning_zh' => '准确',
                'example_sentence' => '准确无误。',
                'example_translation' => 'Accurate and correct.',
                'definition' => 'Accurate, exact, precise',
                'sentences' => ['___信息。', '___判断。', '___率。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '科技',
                'pinyin' => 'kē jì',
                'simplified' => '科技',
                'traditional' => '科技',
                'part_of_speech' => 'noun',
                'meaning' => 'Science and technology',
                'meaning_zh' => '科技',
                'example_sentence' => '高科技产品。',
                'example_translation' => 'High-tech products.',
                'definition' => 'Science and technology, technology',
                'sentences' => ['___发展。', '___创新。', '___进步。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 170,
                'word' => '学术',
                'pinyin' => 'xué shù',
                'simplified' => '学术',
                'traditional' => '學術',
                'part_of_speech' => 'noun',
                'meaning' => 'Academic / Scholarly',
                'meaning_zh' => '学术',
                'example_sentence' => '学术研究。',
                'example_translation' => 'Academic research.',
                'definition' => 'Academic, scholarly, learning',
                'sentences' => ['___论文。', '___交流。', '___界。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 171: Technology and AI - 技术与人工智能
        $technologyVocab = [
            [
                'topic_id' => 171,
                'word' => '技术',
                'pinyin' => 'jì shù',
                'simplified' => '技术',
                'traditional' => '技術',
                'part_of_speech' => 'noun',
                'meaning' => 'Technology / Technique',
                'meaning_zh' => '技术',
                'example_sentence' => '先进技术。',
                'example_translation' => 'Advanced technology.',
                'definition' => 'Technology, technique, skill',
                'sentences' => ['___发展。', '___人员。', '___水平。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '人工智能',
                'pinyin' => 'rén gōng zhì néng',
                'simplified' => '人工智能',
                'traditional' => '人工智能',
                'part_of_speech' => 'noun',
                'meaning' => 'Artificial Intelligence (AI)',
                'meaning_zh' => '人工智能',
                'example_sentence' => '人工智能技术。',
                'example_translation' => 'Artificial intelligence technology.',
                'definition' => 'Artificial intelligence, AI',
                'sentences' => ['___时代。', '___发展。', '___应用。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '算法',
                'pinyin' => 'suàn fǎ',
                'simplified' => '算法',
                'traditional' => '算法',
                'part_of_speech' => 'noun',
                'meaning' => 'Algorithm',
                'meaning_zh' => '算法',
                'example_sentence' => '优化算法。',
                'example_translation' => 'Optimize algorithm.',
                'definition' => 'Algorithm, computational method',
                'sentences' => ['___设计。', '___推荐。', '___研究。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '数据',
                'pinyin' => 'shù jù',
                'simplified' => '数据',
                'traditional' => '數據',
                'part_of_speech' => 'noun',
                'meaning' => 'Data',
                'meaning_zh' => '数据',
                'example_sentence' => '大数据分析。',
                'example_translation' => 'Big data analysis.',
                'definition' => 'Data, information',
                'sentences' => ['___处理。', '___库。', '___安全。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '程序',
                'pinyin' => 'chéng xù',
                'simplified' => '程序',
                'traditional' => '程序',
                'part_of_speech' => 'noun',
                'meaning' => 'Program / Procedure',
                'meaning_zh' => '程序',
                'example_sentence' => '编写程序。',
                'example_translation' => 'Write programs.',
                'definition' => 'Program, procedure, process',
                'sentences' => ['___设计。', '___员。', '___代码。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '软件',
                'pinyin' => 'ruǎn jiàn',
                'simplified' => '软件',
                'traditional' => '軟件',
                'part_of_speech' => 'noun',
                'meaning' => 'Software',
                'meaning_zh' => '软件',
                'example_sentence' => '安装软件。',
                'example_translation' => 'Install software.',
                'definition' => 'Software, computer program',
                'sentences' => ['___开发。', '___工程。', '___系统。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '硬件',
                'pinyin' => 'yìng jiàn',
                'simplified' => '硬件',
                'traditional' => '硬件',
                'part_of_speech' => 'noun',
                'meaning' => 'Hardware',
                'meaning_zh' => '硬件',
                'example_sentence' => '计算机硬件。',
                'example_translation' => 'Computer hardware.',
                'definition' => 'Hardware, physical equipment',
                'sentences' => ['___设备。', '___设施。', '___升级。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '网络',
                'pinyin' => 'wǎng luò',
                'simplified' => '网络',
                'traditional' => '網絡',
                'part_of_speech' => 'noun',
                'meaning' => 'Network / Internet',
                'meaning_zh' => '网络',
                'example_sentence' => '互联网络。',
                'example_translation' => 'Internet network.',
                'definition' => 'Network, internet, web',
                'sentences' => ['___安全。', '___技术。', '___平台。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '互联网',
                'pinyin' => 'hù lián wǎng',
                'simplified' => '互联网',
                'traditional' => '互聯網',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet',
                'meaning_zh' => '互联网',
                'example_sentence' => '互联网时代。',
                'example_translation' => 'Internet era.',
                'definition' => 'Internet, web',
                'sentences' => ['___公司。', '___经济。', '___+。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '数字化',
                'pinyin' => 'shù zì huà',
                'simplified' => '数字化',
                'traditional' => '數字化',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Digitalization / To digitalize',
                'meaning_zh' => '数字化',
                'example_sentence' => '数字化转型。',
                'example_translation' => 'Digital transformation.',
                'definition' => 'Digitalization, to digitalize, digital',
                'sentences' => ['___时代。', '___管理。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '自动化',
                'pinyin' => 'zì dòng huà',
                'simplified' => '自动化',
                'traditional' => '自動化',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Automation / To automate',
                'meaning_zh' => '自动化',
                'example_sentence' => '生产自动化。',
                'example_translation' => 'Production automation.',
                'definition' => 'Automation, to automate, automatic',
                'sentences' => ['___设备。', '___程度。', '___控制。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '智能',
                'pinyin' => 'zhì néng',
                'simplified' => '智能',
                'traditional' => '智能',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Intelligent / Intelligence',
                'meaning_zh' => '智能',
                'example_sentence' => '智能手机。',
                'example_translation' => 'Smartphone.',
                'definition' => 'Intelligent, intelligence, smart',
                'sentences' => ['___化。', '___设备。', '___系统。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '机器人',
                'pinyin' => 'jī qì rén',
                'simplified' => '机器人',
                'traditional' => '機器人',
                'part_of_speech' => 'noun',
                'meaning' => 'Robot',
                'meaning_zh' => '机器人',
                'example_sentence' => '工业机器人。',
                'example_translation' => 'Industrial robot.',
                'definition' => 'Robot, robotic',
                'sentences' => ['___技术。', '___产业。', '___应用。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '虚拟',
                'pinyin' => 'xū nǐ',
                'simplified' => '虚拟',
                'traditional' => '虛擬',
                'part_of_speech' => 'adjective',
                'meaning' => 'Virtual',
                'meaning_zh' => '虚拟',
                'example_sentence' => '虚拟现实。',
                'example_translation' => 'Virtual reality.',
                'definition' => 'Virtual, simulated',
                'sentences' => ['___世界。', '___货币。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '云计算',
                'pinyin' => 'yún jì suàn',
                'simplified' => '云计算',
                'traditional' => '雲計算',
                'part_of_speech' => 'noun',
                'meaning' => 'Cloud computing',
                'meaning_zh' => '云计算',
                'example_sentence' => '云计算服务。',
                'example_translation' => 'Cloud computing services.',
                'definition' => 'Cloud computing',
                'sentences' => ['___平台。', '___技术。', '___存储。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '区块链',
                'pinyin' => 'qū kuài liàn',
                'simplified' => '区块链',
                'traditional' => '區塊鏈',
                'part_of_speech' => 'noun',
                'meaning' => 'Blockchain',
                'meaning_zh' => '区块链',
                'example_sentence' => '区块链技术。',
                'example_translation' => 'Blockchain technology.',
                'definition' => 'Blockchain',
                'sentences' => ['___应用。', '___金融。', '___安全。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '编程',
                'pinyin' => 'biān chéng',
                'simplified' => '编程',
                'traditional' => '編程',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Programming / To program',
                'meaning_zh' => '编程',
                'example_sentence' => '学习编程。',
                'example_translation' => 'Learn programming.',
                'definition' => 'Programming, to program, coding',
                'sentences' => ['___语言。', '___技能。', '___教育。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '芯片',
                'pinyin' => 'xīn piàn',
                'simplified' => '芯片',
                'traditional' => '芯片',
                'part_of_speech' => 'noun',
                'meaning' => 'Chip / Microchip',
                'meaning_zh' => '芯片',
                'example_sentence' => '电脑芯片。',
                'example_translation' => 'Computer chip.',
                'definition' => 'Chip, microchip, integrated circuit',
                'sentences' => ['___技术。', '___产业。', '___制造。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '电子',
                'pinyin' => 'diàn zǐ',
                'simplified' => '电子',
                'traditional' => '電子',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Electronic / Electron',
                'meaning_zh' => '电子',
                'example_sentence' => '电子产品。',
                'example_translation' => 'Electronic products.',
                'definition' => 'Electronic, electron, digital',
                'sentences' => ['___邮件。', '___商务。', '___设备。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 171,
                'word' => '信息',
                'pinyin' => 'xìn xī',
                'simplified' => '信息',
                'traditional' => '信息',
                'part_of_speech' => 'noun',
                'meaning' => 'Information',
                'meaning_zh' => '信息',
                'example_sentence' => '获取信息。',
                'example_translation' => 'Obtain information.',
                'definition' => 'Information, message, news',
                'sentences' => ['___技术。', '___化。', '___时代。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 172: Environment and Sustainability - 环境与可持续发展
        $environmentVocab = [
            [
                'topic_id' => 172,
                'word' => '环境',
                'pinyin' => 'huán jìng',
                'simplified' => '环境',
                'traditional' => '環境',
                'part_of_speech' => 'noun',
                'meaning' => 'Environment',
                'meaning_zh' => '环境',
                'example_sentence' => '保护环境。',
                'example_translation' => 'Protect the environment.',
                'definition' => 'Environment, surroundings',
                'sentences' => ['___污染。', '___问题。', '___科学。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '生态',
                'pinyin' => 'shēng tài',
                'simplified' => '生态',
                'traditional' => '生態',
                'part_of_speech' => 'noun',
                'meaning' => 'Ecology / Ecological',
                'meaning_zh' => '生态',
                'example_sentence' => '生态平衡。',
                'example_translation' => 'Ecological balance.',
                'definition' => 'Ecology, ecological, ecosystem',
                'sentences' => ['___环境。', '___系统。', '___保护。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '污染',
                'pinyin' => 'wū rǎn',
                'simplified' => '污染',
                'traditional' => '污染',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Pollution / To pollute',
                'meaning_zh' => '污染',
                'example_sentence' => '空气污染。',
                'example_translation' => 'Air pollution.',
                'definition' => 'Pollution, to pollute, contamination',
                'sentences' => ['___源。', '___防治。', '___严重。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '排放',
                'pinyin' => 'pái fàng',
                'simplified' => '排放',
                'traditional' => '排放',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To emit / Emission',
                'meaning_zh' => '排放',
                'example_sentence' => '减少排放。',
                'example_translation' => 'Reduce emissions.',
                'definition' => 'To emit, emission, to discharge',
                'sentences' => ['___标准。', '___量。', '___控制。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '可持续',
                'pinyin' => 'kě chí xù',
                'simplified' => '可持续',
                'traditional' => '可持續',
                'part_of_speech' => 'adjective',
                'meaning' => 'Sustainable',
                'meaning_zh' => '可持续',
                'example_sentence' => '可持续发展。',
                'example_translation' => 'Sustainable development.',
                'definition' => 'Sustainable, sustainability',
                'sentences' => ['___性。', '___利用。', '___增长。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '资源',
                'pinyin' => 'zī yuán',
                'simplified' => '资源',
                'traditional' => '資源',
                'part_of_speech' => 'noun',
                'meaning' => 'Resources',
                'meaning_zh' => '资源',
                'example_sentence' => '自然资源。',
                'example_translation' => 'Natural resources.',
                'definition' => 'Resources, wealth',
                'sentences' => ['___利用。', '___丰富。', '___短缺。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '能源',
                'pinyin' => 'néng yuán',
                'simplified' => '能源',
                'traditional' => '能源',
                'part_of_speech' => 'noun',
                'meaning' => 'Energy',
                'meaning_zh' => '能源',
                'example_sentence' => '新能源。',
                'example_translation' => 'New energy.',
                'definition' => 'Energy, energy resources',
                'sentences' => ['___危机。', '___节约。', '___开发。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '再生',
                'pinyin' => 'zài shēng',
                'simplified' => '再生',
                'traditional' => '再生',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To regenerate / Renewable',
                'meaning_zh' => '再生',
                'example_sentence' => '再生能源。',
                'example_translation' => 'Renewable energy.',
                'definition' => 'To regenerate, renewable, recycling',
                'sentences' => ['___资源。', '___利用。', '___纸。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '节能',
                'pinyin' => 'jié néng',
                'simplified' => '节能',
                'traditional' => '節能',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'Energy-saving / To save energy',
                'meaning_zh' => '节能',
                'example_sentence' => '节能减排。',
                'example_translation' => 'Energy saving and emission reduction.',
                'definition' => 'Energy-saving, to save energy',
                'sentences' => ['___环保。', '___产品。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '低碳',
                'pinyin' => 'dī tàn',
                'simplified' => '低碳',
                'traditional' => '低碳',
                'part_of_speech' => 'adjective',
                'meaning' => 'Low-carbon',
                'meaning_zh' => '低碳',
                'example_sentence' => '低碳生活。',
                'example_translation' => 'Low-carbon lifestyle.',
                'definition' => 'Low-carbon',
                'sentences' => ['___经济。', '___环保。', '___出行。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '绿色',
                'pinyin' => 'lǜ sè',
                'simplified' => '绿色',
                'traditional' => '綠色',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Green / Eco-friendly',
                'meaning_zh' => '绿色',
                'example_sentence' => '绿色发展。',
                'example_translation' => 'Green development.',
                'definition' => 'Green, eco-friendly, environmental',
                'sentences' => ['___食品。', '___出行。', '___能源。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '回收',
                'pinyin' => 'huí shōu',
                'simplified' => '回收',
                'traditional' => '回收',
                'part_of_speech' => 'verb',
                'meaning' => 'To recycle / To recover',
                'meaning_zh' => '回收',
                'example_sentence' => '垃圾回收。',
                'example_translation' => 'Garbage recycling.',
                'definition' => 'To recycle, to recover, recycling',
                'sentences' => ['___利用。', '___站。', '___再利用。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '垃圾',
                'pinyin' => 'lā jī',
                'simplified' => '垃圾',
                'traditional' => '垃圾',
                'part_of_speech' => 'noun',
                'meaning' => 'Garbage / Trash',
                'meaning_zh' => '垃圾',
                'example_sentence' => '垃圾分类。',
                'example_translation' => 'Garbage classification.',
                'definition' => 'Garbage, trash, waste',
                'sentences' => ['___处理。', '___桶。', '___食品。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '废物',
                'pinyin' => 'fèi wù',
                'simplified' => '废物',
                'traditional' => '廢物',
                'part_of_speech' => 'noun',
                'meaning' => 'Waste / Rubbish',
                'meaning_zh' => '废物',
                'example_sentence' => '废物利用。',
                'example_translation' => 'Waste utilization.',
                'definition' => 'Waste, rubbish, refuse',
                'sentences' => ['___处理。', '___回收。', '___排放。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '气候',
                'pinyin' => 'qì hòu',
                'simplified' => '气候',
                'traditional' => '氣候',
                'part_of_speech' => 'noun',
                'meaning' => 'Climate',
                'meaning_zh' => '气候',
                'example_sentence' => '气候变化。',
                'example_translation' => 'Climate change.',
                'definition' => 'Climate, weather',
                'sentences' => ['___变暖。', '___条件。', '___异常。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '温室',
                'pinyin' => 'wēn shì',
                'simplified' => '温室',
                'traditional' => '溫室',
                'part_of_speech' => 'noun',
                'meaning' => 'Greenhouse',
                'meaning_zh' => '温室',
                'example_sentence' => '温室效应。',
                'example_translation' => 'Greenhouse effect.',
                'definition' => 'Greenhouse, hothouse',
                'sentences' => ['___气体。', '___栽培。', '___农业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '灾害',
                'pinyin' => 'zāi hài',
                'simplified' => '灾害',
                'traditional' => '災害',
                'part_of_speech' => 'noun',
                'meaning' => 'Disaster / Calamity',
                'meaning_zh' => '灾害',
                'example_sentence' => '自然灾害。',
                'example_translation' => 'Natural disaster.',
                'definition' => 'Disaster, calamity, catastrophe',
                'sentences' => ['___防治。', '___救援。', '___损失。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '森林',
                'pinyin' => 'sēn lín',
                'simplified' => '森林',
                'traditional' => '森林',
                'part_of_speech' => 'noun',
                'meaning' => 'Forest',
                'meaning_zh' => '森林',
                'example_sentence' => '保护森林。',
                'example_translation' => 'Protect forests.',
                'definition' => 'Forest, woods',
                'sentences' => ['___资源。', '___覆盖。', '___火灾。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '保护',
                'pinyin' => 'bǎo hù',
                'simplified' => '保护',
                'traditional' => '保護',
                'part_of_speech' => 'verb',
                'meaning' => 'To protect / Protection',
                'meaning_zh' => '保护',
                'example_sentence' => '环境保护。',
                'example_translation' => 'Environmental protection.',
                'definition' => 'To protect, protection, to safeguard',
                'sentences' => ['___措施。', '___动物。', '___区。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 172,
                'word' => '治理',
                'pinyin' => 'zhì lǐ',
                'simplified' => '治理',
                'traditional' => '治理',
                'part_of_speech' => 'verb',
                'meaning' => 'To manage / To control',
                'meaning_zh' => '治理',
                'example_sentence' => '环境治理。',
                'example_translation' => 'Environmental management.',
                'definition' => 'To manage, to control, to govern',
                'sentences' => ['___污染。', '___水平。', '___能力。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($scienceVocab, $technologyVocab, $environmentVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
