<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic176to178Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [176, 178])->delete();

        // Topic 176: Global Trends and Lifestyle - 全球趋势与生活方式
        $globalTrendsVocab = [
            [
                'topic_id' => 176,
                'word' => '全球',
                'pinyin' => 'quán qiú',
                'simplified' => '全球',
                'traditional' => '全球',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Global / Worldwide',
                'meaning_zh' => '全球',
                'example_sentence' => '全球化时代。',
                'example_translation' => 'Era of globalization.',
                'definition' => 'Global, worldwide, entire world',
                'sentences' => ['___化。', '___经济。', '___市场。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '趋势',
                'pinyin' => 'qū shì',
                'simplified' => '趋势',
                'traditional' => '趨勢',
                'part_of_speech' => 'noun',
                'meaning' => 'Trend / Tendency',
                'meaning_zh' => '趋势',
                'example_sentence' => '发展趋势。',
                'example_translation' => 'Development trend.',
                'definition' => 'Trend, tendency, inclination',
                'sentences' => ['___明显。', '___分析。', '___变化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '生活方式',
                'pinyin' => 'shēng huó fāng shì',
                'simplified' => '生活方式',
                'traditional' => '生活方式',
                'part_of_speech' => 'noun',
                'meaning' => 'Lifestyle / Way of life',
                'meaning_zh' => '生活方式',
                'example_sentence' => '健康的生活方式。',
                'example_translation' => 'Healthy lifestyle.',
                'definition' => 'Lifestyle, way of life',
                'sentences' => ['___改变。', '___选择。', '___多样。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '消费',
                'pinyin' => 'xiāo fèi',
                'simplified' => '消费',
                'traditional' => '消費',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Consumption / To consume',
                'meaning_zh' => '消费',
                'example_sentence' => '理性消费。',
                'example_translation' => 'Rational consumption.',
                'definition' => 'Consumption, to consume',
                'sentences' => ['___者。', '___水平。', '___观念。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '品牌',
                'pinyin' => 'pǐn pái',
                'simplified' => '品牌',
                'traditional' => '品牌',
                'part_of_speech' => 'noun',
                'meaning' => 'Brand',
                'meaning_zh' => '品牌',
                'example_sentence' => '知名品牌。',
                'example_translation' => 'Famous brand.',
                'definition' => 'Brand, trademark',
                'sentences' => ['___效应。', '___意识。', '___价值。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '奢侈',
                'pinyin' => 'shē chǐ',
                'simplified' => '奢侈',
                'traditional' => '奢侈',
                'part_of_speech' => 'adjective',
                'meaning' => 'Luxurious / Extravagant',
                'meaning_zh' => '奢侈',
                'example_sentence' => '奢侈品。',
                'example_translation' => 'Luxury goods.',
                'definition' => 'Luxurious, extravagant, lavish',
                'sentences' => ['___品。', '___浪费。', '___消费。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '简约',
                'pinyin' => 'jiǎn yuē',
                'simplified' => '简约',
                'traditional' => '簡約',
                'part_of_speech' => 'adjective',
                'meaning' => 'Simple / Minimalist',
                'meaning_zh' => '简约',
                'example_sentence' => '简约风格。',
                'example_translation' => 'Minimalist style.',
                'definition' => 'Simple, minimalist, concise',
                'sentences' => ['___主义。', '___设计。', '___生活。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '品质',
                'pinyin' => 'pǐn zhì',
                'simplified' => '品质',
                'traditional' => '品質',
                'part_of_speech' => 'noun',
                'meaning' => 'Quality',
                'meaning_zh' => '品质',
                'example_sentence' => '提高品质。',
                'example_translation' => 'Improve quality.',
                'definition' => 'Quality, character',
                'sentences' => ['___保证。', '___生活。', '___优良。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '休闲',
                'pinyin' => 'xiū xián',
                'simplified' => '休闲',
                'traditional' => '休閒',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Leisure / Recreational',
                'meaning_zh' => '休闲',
                'example_sentence' => '休闲娱乐。',
                'example_translation' => 'Leisure and entertainment.',
                'definition' => 'Leisure, recreational, relaxation',
                'sentences' => ['___时光。', '___活动。', '___服装。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '健身',
                'pinyin' => 'jiàn shēn',
                'simplified' => '健身',
                'traditional' => '健身',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Fitness / To work out',
                'meaning_zh' => '健身',
                'example_sentence' => '去健身房。',
                'example_translation' => 'Go to the gym.',
                'definition' => 'Fitness, to work out, bodybuilding',
                'sentences' => ['___房。', '___运动。', '___教练。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '养生',
                'pinyin' => 'yǎng shēng',
                'simplified' => '养生',
                'traditional' => '養生',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Health preservation / To keep healthy',
                'meaning_zh' => '养生',
                'example_sentence' => '注重养生。',
                'example_translation' => 'Pay attention to health preservation.',
                'definition' => 'Health preservation, to keep healthy',
                'sentences' => ['___之道。', '___保健。', '___观念。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '美容',
                'pinyin' => 'měi róng',
                'simplified' => '美容',
                'traditional' => '美容',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Beauty / Beautification',
                'meaning_zh' => '美容',
                'example_sentence' => '美容护肤。',
                'example_translation' => 'Beauty and skincare.',
                'definition' => 'Beauty, beautification, cosmetic',
                'sentences' => ['___院。', '___产品。', '___整形。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '旅游',
                'pinyin' => 'lǚ yóu',
                'simplified' => '旅游',
                'traditional' => '旅遊',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Tourism / To travel',
                'meaning_zh' => '旅游',
                'example_sentence' => '出国旅游。',
                'example_translation' => 'Travel abroad.',
                'definition' => 'Tourism, to travel, tour',
                'sentences' => ['___业。', '___景点。', '___者。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '度假',
                'pinyin' => 'dù jià',
                'simplified' => '度假',
                'traditional' => '度假',
                'part_of_speech' => 'verb',
                'meaning' => 'To vacation / To holiday',
                'meaning_zh' => '度假',
                'example_sentence' => '去海边度假。',
                'example_translation' => 'Go to the seaside for vacation.',
                'definition' => 'To vacation, to holiday',
                'sentences' => ['___村。', '___酒店。', '___胜地。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '购物',
                'pinyin' => 'gòu wù',
                'simplified' => '购物',
                'traditional' => '購物',
                'part_of_speech' => 'verb',
                'meaning' => 'To shop / Shopping',
                'meaning_zh' => '购物',
                'example_sentence' => '网上购物。',
                'example_translation' => 'Online shopping.',
                'definition' => 'To shop, shopping',
                'sentences' => ['___中心。', '___车。', '___狂欢。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '外卖',
                'pinyin' => 'wài mài',
                'simplified' => '外卖',
                'traditional' => '外賣',
                'part_of_speech' => 'noun',
                'meaning' => 'Takeout / Delivery food',
                'meaning_zh' => '外卖',
                'example_sentence' => '点外卖。',
                'example_translation' => 'Order takeout.',
                'definition' => 'Takeout, delivery food',
                'sentences' => ['___平台。', '___小哥。', '___服务。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '快递',
                'pinyin' => 'kuài dì',
                'simplified' => '快递',
                'traditional' => '快遞',
                'part_of_speech' => 'noun',
                'meaning' => 'Express delivery / Courier',
                'meaning_zh' => '快递',
                'example_sentence' => '收快递。',
                'example_translation' => 'Receive express delivery.',
                'definition' => 'Express delivery, courier',
                'sentences' => ['___公司。', '___员。', '___包裹。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '共享',
                'pinyin' => 'gòng xiǎng',
                'simplified' => '共享',
                'traditional' => '共享',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To share / Shared',
                'meaning_zh' => '共享',
                'example_sentence' => '共享经济。',
                'example_translation' => 'Sharing economy.',
                'definition' => 'To share, shared',
                'sentences' => ['___单车。', '___资源。', '___平台。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '便利',
                'pinyin' => 'biàn lì',
                'simplified' => '便利',
                'traditional' => '便利',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Convenient / Convenience',
                'meaning_zh' => '便利',
                'example_sentence' => '生活便利。',
                'example_translation' => 'Convenient life.',
                'definition' => 'Convenient, convenience',
                'sentences' => ['___店。', '___服务。', '___条件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 176,
                'word' => '高效',
                'pinyin' => 'gāo xiào',
                'simplified' => '高效',
                'traditional' => '高效',
                'part_of_speech' => 'adjective',
                'meaning' => 'Highly efficient / High-efficiency',
                'meaning_zh' => '高效',
                'example_sentence' => '高效工作。',
                'example_translation' => 'Work efficiently.',
                'definition' => 'Highly efficient, high-efficiency',
                'sentences' => ['___率。', '___管理。', '___利用。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 177: Work and Economy in Modern Society - 现代社会的工作与经济
        $workEconomyVocab = [
            [
                'topic_id' => 177,
                'word' => '职业',
                'pinyin' => 'zhí yè',
                'simplified' => '职业',
                'traditional' => '職業',
                'part_of_speech' => 'noun',
                'meaning' => 'Occupation / Profession',
                'meaning_zh' => '职业',
                'example_sentence' => '选择职业。',
                'example_translation' => 'Choose a profession.',
                'definition' => 'Occupation, profession, career',
                'sentences' => ['___规划。', '___发展。', '___素养。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '就业',
                'pinyin' => 'jiù yè',
                'simplified' => '就业',
                'traditional' => '就業',
                'part_of_speech' => 'verb',
                'meaning' => 'Employment / To get a job',
                'meaning_zh' => '就业',
                'example_sentence' => '大学生就业。',
                'example_translation' => 'College student employment.',
                'definition' => 'Employment, to get a job',
                'sentences' => ['___机会。', '___压力。', '___率。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '失业',
                'pinyin' => 'shī yè',
                'simplified' => '失业',
                'traditional' => '失業',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Unemployment / To lose job',
                'meaning_zh' => '失业',
                'example_sentence' => '失业问题。',
                'example_translation' => 'Unemployment problem.',
                'definition' => 'Unemployment, to lose job',
                'sentences' => ['___率。', '___保险。', '___人员。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '创业',
                'pinyin' => 'chuàng yè',
                'simplified' => '创业',
                'traditional' => '創業',
                'part_of_speech' => 'verb',
                'meaning' => 'To start a business / Entrepreneurship',
                'meaning_zh' => '创业',
                'example_sentence' => '自主创业。',
                'example_translation' => 'Start your own business.',
                'definition' => 'To start a business, entrepreneurship',
                'sentences' => ['___者。', '___精神。', '___项目。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '企业',
                'pinyin' => 'qǐ yè',
                'simplified' => '企业',
                'traditional' => '企業',
                'part_of_speech' => 'noun',
                'meaning' => 'Enterprise / Company',
                'meaning_zh' => '企业',
                'example_sentence' => '国有企业。',
                'example_translation' => 'State-owned enterprise.',
                'definition' => 'Enterprise, company, business',
                'sentences' => ['___管理。', '___文化。', '___家。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '公司',
                'pinyin' => 'gōng sī',
                'simplified' => '公司',
                'traditional' => '公司',
                'part_of_speech' => 'noun',
                'meaning' => 'Company / Corporation',
                'meaning_zh' => '公司',
                'example_sentence' => '上市公司。',
                'example_translation' => 'Listed company.',
                'definition' => 'Company, corporation, firm',
                'sentences' => ['___发展。', '___业务。', '___制度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '收入',
                'pinyin' => 'shōu rù',
                'simplified' => '收入',
                'traditional' => '收入',
                'part_of_speech' => 'noun',
                'meaning' => 'Income / Revenue',
                'meaning_zh' => '收入',
                'example_sentence' => '增加收入。',
                'example_translation' => 'Increase income.',
                'definition' => 'Income, revenue, earnings',
                'sentences' => ['___水平。', '___来源。', '___差距。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '工资',
                'pinyin' => 'gōng zī',
                'simplified' => '工资',
                'traditional' => '工資',
                'part_of_speech' => 'noun',
                'meaning' => 'Salary / Wage',
                'meaning_zh' => '工资',
                'example_sentence' => '发工资。',
                'example_translation' => 'Pay salary.',
                'definition' => 'Salary, wage, pay',
                'sentences' => ['___待遇。', '___水平。', '___增长。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '福利',
                'pinyin' => 'fú lì',
                'simplified' => '福利',
                'traditional' => '福利',
                'part_of_speech' => 'noun',
                'meaning' => 'Welfare / Benefit',
                'meaning_zh' => '福利',
                'example_sentence' => '员工福利。',
                'example_translation' => 'Employee benefits.',
                'definition' => 'Welfare, benefit, well-being',
                'sentences' => ['___待遇。', '___制度。', '___保障。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '晋升',
                'pinyin' => 'jìn shēng',
                'simplified' => '晋升',
                'traditional' => '晉升',
                'part_of_speech' => 'verb',
                'meaning' => 'To promote / Promotion',
                'meaning_zh' => '晋升',
                'example_sentence' => '职位晋升。',
                'example_translation' => 'Job promotion.',
                'definition' => 'To promote, promotion, advancement',
                'sentences' => ['___机会。', '___空间。', '___通道。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '竞争',
                'pinyin' => 'jìng zhēng',
                'simplified' => '竞争',
                'traditional' => '競爭',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Competition / To compete',
                'meaning_zh' => '竞争',
                'example_sentence' => '市场竞争。',
                'example_translation' => 'Market competition.',
                'definition' => 'Competition, to compete',
                'sentences' => ['___力。', '___激烈。', '___优势。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '合作',
                'pinyin' => 'hé zuò',
                'simplified' => '合作',
                'traditional' => '合作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Cooperation / To cooperate',
                'meaning_zh' => '合作',
                'example_sentence' => '团队合作。',
                'example_translation' => 'Team cooperation.',
                'definition' => 'Cooperation, to cooperate, collaboration',
                'sentences' => ['___伙伴。', '___项目。', '___精神。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '效率',
                'pinyin' => 'xiào lǜ',
                'simplified' => '效率',
                'traditional' => '效率',
                'part_of_speech' => 'noun',
                'meaning' => 'Efficiency',
                'meaning_zh' => '效率',
                'example_sentence' => '提高效率。',
                'example_translation' => 'Improve efficiency.',
                'definition' => 'Efficiency, effectiveness',
                'sentences' => ['___高。', '___低下。', '___优先。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '投资',
                'pinyin' => 'tóu zī',
                'simplified' => '投资',
                'traditional' => '投資',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Investment / To invest',
                'meaning_zh' => '投资',
                'example_sentence' => '吸引投资。',
                'example_translation' => 'Attract investment.',
                'definition' => 'Investment, to invest',
                'sentences' => ['___者。', '___回报。', '___风险。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '利润',
                'pinyin' => 'lì rùn',
                'simplified' => '利润',
                'traditional' => '利潤',
                'part_of_speech' => 'noun',
                'meaning' => 'Profit',
                'meaning_zh' => '利润',
                'example_sentence' => '获得利润。',
                'example_translation' => 'Make profit.',
                'definition' => 'Profit, gain',
                'sentences' => ['___率。', '___空间。', '___最大化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '成本',
                'pinyin' => 'chéng běn',
                'simplified' => '成本',
                'traditional' => '成本',
                'part_of_speech' => 'noun',
                'meaning' => 'Cost',
                'meaning_zh' => '成本',
                'example_sentence' => '降低成本。',
                'example_translation' => 'Reduce cost.',
                'definition' => 'Cost, expense',
                'sentences' => ['___控制。', '___高昂。', '___核算。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '市场',
                'pinyin' => 'shì chǎng',
                'simplified' => '市场',
                'traditional' => '市場',
                'part_of_speech' => 'noun',
                'meaning' => 'Market',
                'meaning_zh' => '市场',
                'example_sentence' => '开拓市场。',
                'example_translation' => 'Develop market.',
                'definition' => 'Market, marketplace',
                'sentences' => ['___经济。', '___份额。', '___需求。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '供需',
                'pinyin' => 'gōng xū',
                'simplified' => '供需',
                'traditional' => '供需',
                'part_of_speech' => 'noun',
                'meaning' => 'Supply and demand',
                'meaning_zh' => '供需',
                'example_sentence' => '供需关系。',
                'example_translation' => 'Supply and demand relationship.',
                'definition' => 'Supply and demand',
                'sentences' => ['___平衡。', '___矛盾。', '___变化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '产业',
                'pinyin' => 'chǎn yè',
                'simplified' => '产业',
                'traditional' => '產業',
                'part_of_speech' => 'noun',
                'meaning' => 'Industry',
                'meaning_zh' => '产业',
                'example_sentence' => '高科技产业。',
                'example_translation' => 'High-tech industry.',
                'definition' => 'Industry, sector',
                'sentences' => ['___链。', '___结构。', '___升级。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 177,
                'word' => '贸易',
                'pinyin' => 'mào yì',
                'simplified' => '贸易',
                'traditional' => '貿易',
                'part_of_speech' => 'noun',
                'meaning' => 'Trade / Commerce',
                'meaning_zh' => '贸易',
                'example_sentence' => '国际贸易。',
                'example_translation' => 'International trade.',
                'definition' => 'Trade, commerce',
                'sentences' => ['___战。', '___保护。', '___自由。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 178: Digital Life and Privacy - 数字生活与隐私
        $digitalPrivacyVocab = [
            [
                'topic_id' => 178,
                'word' => '数字',
                'pinyin' => 'shù zì',
                'simplified' => '数字',
                'traditional' => '數字',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Digital / Number',
                'meaning_zh' => '数字',
                'example_sentence' => '数字时代。',
                'example_translation' => 'Digital age.',
                'definition' => 'Digital, number, numeral',
                'sentences' => ['___化。', '___货币。', '___经济。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '隐私',
                'pinyin' => 'yǐn sī',
                'simplified' => '隐私',
                'traditional' => '隱私',
                'part_of_speech' => 'noun',
                'meaning' => 'Privacy',
                'meaning_zh' => '隐私',
                'example_sentence' => '保护隐私。',
                'example_translation' => 'Protect privacy.',
                'definition' => 'Privacy, private information',
                'sentences' => ['___权。', '___泄露。', '___安全。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '安全',
                'pinyin' => 'ān quán',
                'simplified' => '安全',
                'traditional' => '安全',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Safe / Safety',
                'meaning_zh' => '安全',
                'example_sentence' => '网络安全。',
                'example_translation' => 'Cybersecurity.',
                'definition' => 'Safe, safety, security',
                'sentences' => ['___问题。', '___保障。', '___措施。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '密码',
                'pinyin' => 'mì mǎ',
                'simplified' => '密码',
                'traditional' => '密碼',
                'part_of_speech' => 'noun',
                'meaning' => 'Password / Code',
                'meaning_zh' => '密码',
                'example_sentence' => '设置密码。',
                'example_translation' => 'Set a password.',
                'definition' => 'Password, code, cipher',
                'sentences' => ['___保护。', '___修改。', '___破解。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '加密',
                'pinyin' => 'jiā mì',
                'simplified' => '加密',
                'traditional' => '加密',
                'part_of_speech' => 'verb',
                'meaning' => 'To encrypt / Encryption',
                'meaning_zh' => '加密',
                'example_sentence' => '数据加密。',
                'example_translation' => 'Data encryption.',
                'definition' => 'To encrypt, encryption',
                'sentences' => ['___技术。', '___通信。', '___货币。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '账号',
                'pinyin' => 'zhàng hào',
                'simplified' => '账号',
                'traditional' => '賬號',
                'part_of_speech' => 'noun',
                'meaning' => 'Account',
                'meaning_zh' => '账号',
                'example_sentence' => '注册账号。',
                'example_translation' => 'Register an account.',
                'definition' => 'Account, account number',
                'sentences' => ['___登录。', '___管理。', '___被盗。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '身份',
                'pinyin' => 'shēn fèn',
                'simplified' => '身份',
                'traditional' => '身份',
                'part_of_speech' => 'noun',
                'meaning' => 'Identity / Status',
                'meaning_zh' => '身份',
                'example_sentence' => '身份验证。',
                'example_translation' => 'Identity verification.',
                'definition' => 'Identity, status, position',
                'sentences' => ['___证。', '___认证。', '___信息。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '个人信息',
                'pinyin' => 'gè rén xìn xī',
                'simplified' => '个人信息',
                'traditional' => '個人信息',
                'part_of_speech' => 'noun',
                'meaning' => 'Personal information',
                'meaning_zh' => '个人信息',
                'example_sentence' => '保护个人信息。',
                'example_translation' => 'Protect personal information.',
                'definition' => 'Personal information, personal data',
                'sentences' => ['___泄露。', '___安全。', '___收集。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '泄露',
                'pinyin' => 'xiè lòu',
                'simplified' => '泄露',
                'traditional' => '洩露',
                'part_of_speech' => 'verb',
                'meaning' => 'To leak / To disclose',
                'meaning_zh' => '泄露',
                'example_sentence' => '信息泄露。',
                'example_translation' => 'Information leak.',
                'definition' => 'To leak, to disclose',
                'sentences' => ['___秘密。', '___隐私。', '___事件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '黑客',
                'pinyin' => 'hēi kè',
                'simplified' => '黑客',
                'traditional' => '黑客',
                'part_of_speech' => 'noun',
                'meaning' => 'Hacker',
                'meaning_zh' => '黑客',
                'example_sentence' => '防范黑客。',
                'example_translation' => 'Prevent hackers.',
                'definition' => 'Hacker',
                'sentences' => ['___攻击。', '___入侵。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '病毒',
                'pinyin' => 'bìng dú',
                'simplified' => '病毒',
                'traditional' => '病毒',
                'part_of_speech' => 'noun',
                'meaning' => 'Virus / Computer virus',
                'meaning_zh' => '病毒',
                'example_sentence' => '电脑病毒。',
                'example_translation' => 'Computer virus.',
                'definition' => 'Virus, computer virus',
                'sentences' => ['___查杀。', '___防护。', '___软件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '防火墙',
                'pinyin' => 'fáng huǒ qiáng',
                'simplified' => '防火墙',
                'traditional' => '防火牆',
                'part_of_speech' => 'noun',
                'meaning' => 'Firewall',
                'meaning_zh' => '防火墙',
                'example_sentence' => '设置防火墙。',
                'example_translation' => 'Set up a firewall.',
                'definition' => 'Firewall',
                'sentences' => ['___保护。', '___系统。', '___配置。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '备份',
                'pinyin' => 'bèi fèn',
                'simplified' => '备份',
                'traditional' => '備份',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Backup / To back up',
                'meaning_zh' => '备份',
                'example_sentence' => '数据备份。',
                'example_translation' => 'Data backup.',
                'definition' => 'Backup, to back up',
                'sentences' => ['___文件。', '___恢复。', '___系统。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '下载',
                'pinyin' => 'xià zài',
                'simplified' => '下载',
                'traditional' => '下載',
                'part_of_speech' => 'verb',
                'meaning' => 'To download',
                'meaning_zh' => '下载',
                'example_sentence' => '下载文件。',
                'example_translation' => 'Download files.',
                'definition' => 'To download',
                'sentences' => ['___软件。', '___速度。', '___链接。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '上传',
                'pinyin' => 'shàng chuán',
                'simplified' => '上传',
                'traditional' => '上傳',
                'part_of_speech' => 'verb',
                'meaning' => 'To upload',
                'meaning_zh' => '上传',
                'example_sentence' => '上传照片。',
                'example_translation' => 'Upload photos.',
                'definition' => 'To upload',
                'sentences' => ['___文件。', '___视频。', '___速度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '在线',
                'pinyin' => 'zài xiàn',
                'simplified' => '在线',
                'traditional' => '在線',
                'part_of_speech' => 'adjective/adverb',
                'meaning' => 'Online',
                'meaning_zh' => '在线',
                'example_sentence' => '在线学习。',
                'example_translation' => 'Online learning.',
                'definition' => 'Online, on the internet',
                'sentences' => ['___服务。', '___教育。', '___支付。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '离线',
                'pinyin' => 'lí xiàn',
                'simplified' => '离线',
                'traditional' => '離線',
                'part_of_speech' => 'adjective/adverb',
                'meaning' => 'Offline',
                'meaning_zh' => '离线',
                'example_sentence' => '离线模式。',
                'example_translation' => 'Offline mode.',
                'definition' => 'Offline, disconnected',
                'sentences' => ['___使用。', '___下载。', '___状态。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '支付',
                'pinyin' => 'zhī fù',
                'simplified' => '支付',
                'traditional' => '支付',
                'part_of_speech' => 'verb',
                'meaning' => 'To pay / Payment',
                'meaning_zh' => '支付',
                'example_sentence' => '移动支付。',
                'example_translation' => 'Mobile payment.',
                'definition' => 'To pay, payment',
                'sentences' => ['___宝。', '___方式。', '___安全。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '扫码',
                'pinyin' => 'sǎo mǎ',
                'simplified' => '扫码',
                'traditional' => '掃碼',
                'part_of_speech' => 'verb',
                'meaning' => 'To scan QR code',
                'meaning_zh' => '扫码',
                'example_sentence' => '扫码支付。',
                'example_translation' => 'Scan to pay.',
                'definition' => 'To scan QR code, scan code',
                'sentences' => ['___付款。', '___登录。', '___点餐。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 178,
                'word' => '人脸识别',
                'pinyin' => 'rén liǎn shí bié',
                'simplified' => '人脸识别',
                'traditional' => '人臉識別',
                'part_of_speech' => 'noun',
                'meaning' => 'Facial recognition',
                'meaning_zh' => '人脸识别',
                'example_sentence' => '人脸识别技术。',
                'example_translation' => 'Facial recognition technology.',
                'definition' => 'Facial recognition, face ID',
                'sentences' => ['___系统。', '___解锁。', '___安全。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($globalTrendsVocab, $workEconomyVocab, $digitalPrivacyVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
