<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic182to184Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [182, 184])->delete();

        // Topic 182: Writing and Expression - 写作与表达
        $writingVocab = [
            [
                'topic_id' => 182,
                'word' => '写作',
                'pinyin' => 'xiě zuò',
                'simplified' => '写作',
                'traditional' => '寫作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Writing / To write',
                'meaning_zh' => '写作',
                'example_sentence' => '提高写作水平。',
                'example_translation' => 'Improve writing level.',
                'definition' => 'Writing, to write, composition',
                'sentences' => ['___能力。', '___技巧。', '___风格。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '表达',
                'pinyin' => 'biǎo dá',
                'simplified' => '表达',
                'traditional' => '表達',
                'part_of_speech' => 'verb',
                'meaning' => 'To express / Expression',
                'meaning_zh' => '表达',
                'example_sentence' => '清楚表达。',
                'example_translation' => 'Express clearly.',
                'definition' => 'To express, expression',
                'sentences' => ['___意见。', '___能力。', '___方式。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '措辞',
                'pinyin' => 'cuò cí',
                'simplified' => '措辞',
                'traditional' => '措辭',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Wording / To phrase',
                'meaning_zh' => '措辞',
                'example_sentence' => '措辞严谨。',
                'example_translation' => 'Rigorous wording.',
                'definition' => 'Wording, to phrase, diction',
                'sentences' => ['___准确。', '___委婉。', '___得体。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '修辞',
                'pinyin' => 'xiū cí',
                'simplified' => '修辞',
                'traditional' => '修辭',
                'part_of_speech' => 'noun',
                'meaning' => 'Rhetoric / Figure of speech',
                'meaning_zh' => '修辞',
                'example_sentence' => '修辞手法。',
                'example_translation' => 'Rhetorical device.',
                'definition' => 'Rhetoric, figure of speech',
                'sentences' => ['___方法。', '___技巧。', '___学。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '文体',
                'pinyin' => 'wén tǐ',
                'simplified' => '文体',
                'traditional' => '文體',
                'part_of_speech' => 'noun',
                'meaning' => 'Literary style / Genre',
                'meaning_zh' => '文体',
                'example_sentence' => '不同文体。',
                'example_translation' => 'Different genres.',
                'definition' => 'Literary style, genre, writing style',
                'sentences' => ['___形式。', '___特点。', '___活动。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '风格',
                'pinyin' => 'fēng gé',
                'simplified' => '风格',
                'traditional' => '風格',
                'part_of_speech' => 'noun',
                'meaning' => 'Style',
                'meaning_zh' => '风格',
                'example_sentence' => '独特风格。',
                'example_translation' => 'Unique style.',
                'definition' => 'Style, manner',
                'sentences' => ['___各异。', '___鲜明。', '___艺术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '结构',
                'pinyin' => 'jié gòu',
                'simplified' => '结构',
                'traditional' => '結構',
                'part_of_speech' => 'noun',
                'meaning' => 'Structure',
                'meaning_zh' => '结构',
                'example_sentence' => '文章结构。',
                'example_translation' => 'Article structure.',
                'definition' => 'Structure, composition',
                'sentences' => ['___清晰。', '___合理。', '___框架。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '段落',
                'pinyin' => 'duàn luò',
                'simplified' => '段落',
                'traditional' => '段落',
                'part_of_speech' => 'noun',
                'meaning' => 'Paragraph',
                'meaning_zh' => '段落',
                'example_sentence' => '分段落。',
                'example_translation' => 'Divide into paragraphs.',
                'definition' => 'Paragraph, section',
                'sentences' => ['___划分。', '___层次。', '___衔接。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '句式',
                'pinyin' => 'jù shì',
                'simplified' => '句式',
                'traditional' => '句式',
                'part_of_speech' => 'noun',
                'meaning' => 'Sentence pattern',
                'meaning_zh' => '句式',
                'example_sentence' => '多样句式。',
                'example_translation' => 'Varied sentence patterns.',
                'definition' => 'Sentence pattern, sentence structure',
                'sentences' => ['___变化。', '___丰富。', '___运用。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '词汇',
                'pinyin' => 'cí huì',
                'simplified' => '词汇',
                'traditional' => '詞彙',
                'part_of_speech' => 'noun',
                'meaning' => 'Vocabulary',
                'meaning_zh' => '词汇',
                'example_sentence' => '丰富词汇。',
                'example_translation' => 'Rich vocabulary.',
                'definition' => 'Vocabulary, lexicon',
                'sentences' => ['___量。', '___运用。', '___积累。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '润色',
                'pinyin' => 'rùn sè',
                'simplified' => '润色',
                'traditional' => '潤色',
                'part_of_speech' => 'verb',
                'meaning' => 'To polish / To embellish',
                'meaning_zh' => '润色',
                'example_sentence' => '文章润色。',
                'example_translation' => 'Polish the article.',
                'definition' => 'To polish, to embellish, to touch up',
                'sentences' => ['___修改。', '___语言。', '___加工。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '修改',
                'pinyin' => 'xiū gǎi',
                'simplified' => '修改',
                'traditional' => '修改',
                'part_of_speech' => 'verb',
                'meaning' => 'To revise / To modify',
                'meaning_zh' => '修改',
                'example_sentence' => '反复修改。',
                'example_translation' => 'Revise repeatedly.',
                'definition' => 'To revise, to modify, revision',
                'sentences' => ['___意见。', '___完善。', '___稿件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '草稿',
                'pinyin' => 'cǎo gǎo',
                'simplified' => '草稿',
                'traditional' => '草稿',
                'part_of_speech' => 'noun',
                'meaning' => 'Draft / Rough draft',
                'meaning_zh' => '草稿',
                'example_sentence' => '写草稿。',
                'example_translation' => 'Write a draft.',
                'definition' => 'Draft, rough draft, manuscript',
                'sentences' => ['___纸。', '___初稿。', '___修改。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '定稿',
                'pinyin' => 'dìng gǎo',
                'simplified' => '定稿',
                'traditional' => '定稿',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Final version / To finalize',
                'meaning_zh' => '定稿',
                'example_sentence' => '已经定稿。',
                'example_translation' => 'Already finalized.',
                'definition' => 'Final version, to finalize',
                'sentences' => ['___方案。', '___文件。', '___确定。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '主题',
                'pinyin' => 'zhǔ tí',
                'simplified' => '主题',
                'traditional' => '主題',
                'part_of_speech' => 'noun',
                'meaning' => 'Theme / Topic',
                'meaning_zh' => '主题',
                'example_sentence' => '明确主题。',
                'example_translation' => 'Clear theme.',
                'definition' => 'Theme, topic, subject',
                'sentences' => ['___突出。', '___鲜明。', '___曲。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '中心思想',
                'pinyin' => 'zhōng xīn sī xiǎng',
                'simplified' => '中心思想',
                'traditional' => '中心思想',
                'part_of_speech' => 'noun',
                'meaning' => 'Main idea / Central theme',
                'meaning_zh' => '中心思想',
                'example_sentence' => '把握中心思想。',
                'example_translation' => 'Grasp the main idea.',
                'definition' => 'Main idea, central theme',
                'sentences' => ['___明确。', '___概括。', '___理解。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '引用',
                'pinyin' => 'yǐn yòng',
                'simplified' => '引用',
                'traditional' => '引用',
                'part_of_speech' => 'verb',
                'meaning' => 'To quote / To cite',
                'meaning_zh' => '引用',
                'example_sentence' => '引用文献。',
                'example_translation' => 'Cite literature.',
                'definition' => 'To quote, to cite, citation',
                'sentences' => ['___资料。', '___经典。', '___格式。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '描写',
                'pinyin' => 'miáo xiě',
                'simplified' => '描写',
                'traditional' => '描寫',
                'part_of_speech' => 'verb',
                'meaning' => 'To describe / Description',
                'meaning_zh' => '描写',
                'example_sentence' => '生动描写。',
                'example_translation' => 'Vivid description.',
                'definition' => 'To describe, description',
                'sentences' => ['___细腻。', '___手法。', '___场景。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '叙述',
                'pinyin' => 'xù shù',
                'simplified' => '叙述',
                'traditional' => '敘述',
                'part_of_speech' => 'verb',
                'meaning' => 'To narrate / Narration',
                'meaning_zh' => '叙述',
                'example_sentence' => '详细叙述。',
                'example_translation' => 'Narrate in detail.',
                'definition' => 'To narrate, narration',
                'sentences' => ['___方式。', '___角度。', '___事件。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 182,
                'word' => '议论',
                'pinyin' => 'yì lùn',
                'simplified' => '议论',
                'traditional' => '議論',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To comment / Discussion',
                'meaning_zh' => '议论',
                'example_sentence' => '议论文。',
                'example_translation' => 'Argumentative essay.',
                'definition' => 'To comment, discussion, argument',
                'sentences' => ['___纷纷。', '___话题。', '___文。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 183: Reading and Comprehension - 阅读与理解
        $readingVocab = [
            [
                'topic_id' => 183,
                'word' => '阅读',
                'pinyin' => 'yuè dú',
                'simplified' => '阅读',
                'traditional' => '閱讀',
                'part_of_speech' => 'verb',
                'meaning' => 'To read / Reading',
                'meaning_zh' => '阅读',
                'example_sentence' => '广泛阅读。',
                'example_translation' => 'Read extensively.',
                'definition' => 'To read, reading',
                'sentences' => ['___理解。', '___能力。', '___习惯。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '理解',
                'pinyin' => 'lǐ jiě',
                'simplified' => '理解',
                'traditional' => '理解',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To understand / Understanding',
                'meaning_zh' => '理解',
                'example_sentence' => '深入理解。',
                'example_translation' => 'Understand deeply.',
                'definition' => 'To understand, understanding',
                'sentences' => ['___力。', '___意思。', '___正确。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '领会',
                'pinyin' => 'lǐng huì',
                'simplified' => '领会',
                'traditional' => '領會',
                'part_of_speech' => 'verb',
                'meaning' => 'To comprehend / To grasp',
                'meaning_zh' => '领会',
                'example_sentence' => '领会精神。',
                'example_translation' => 'Comprehend the spirit.',
                'definition' => 'To comprehend, to grasp, to understand',
                'sentences' => ['___意图。', '___深刻。', '___要领。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '领悟',
                'pinyin' => 'lǐng wù',
                'simplified' => '领悟',
                'traditional' => '領悟',
                'part_of_speech' => 'verb',
                'meaning' => 'To comprehend / To perceive',
                'meaning_zh' => '领悟',
                'example_sentence' => '领悟真谛。',
                'example_translation' => 'Comprehend the true essence.',
                'definition' => 'To comprehend, to perceive, insight',
                'sentences' => ['___能力。', '___道理。', '___深刻。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '体会',
                'pinyin' => 'tǐ huì',
                'simplified' => '体会',
                'traditional' => '體會',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To experience / Understanding',
                'meaning_zh' => '体会',
                'example_sentence' => '深刻体会。',
                'example_translation' => 'Deep experience.',
                'definition' => 'To experience, understanding, insight',
                'sentences' => ['___到。', '___感受。', '___心得。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '诠释',
                'pinyin' => 'quán shì',
                'simplified' => '诠释',
                'traditional' => '詮釋',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To interpret / Interpretation',
                'meaning_zh' => '诠释',
                'example_sentence' => '完美诠释。',
                'example_translation' => 'Perfect interpretation.',
                'definition' => 'To interpret, interpretation',
                'sentences' => ['___意义。', '___角色。', '___文本。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '解读',
                'pinyin' => 'jiě dú',
                'simplified' => '解读',
                'traditional' => '解讀',
                'part_of_speech' => 'verb',
                'meaning' => 'To interpret / To read',
                'meaning_zh' => '解读',
                'example_sentence' => '解读政策。',
                'example_translation' => 'Interpret policy.',
                'definition' => 'To interpret, to read, interpretation',
                'sentences' => ['___文本。', '___深入。', '___信号。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '含义',
                'pinyin' => 'hán yì',
                'simplified' => '含义',
                'traditional' => '含義',
                'part_of_speech' => 'noun',
                'meaning' => 'Meaning / Implication',
                'meaning_zh' => '含义',
                'example_sentence' => '深刻含义。',
                'example_translation' => 'Profound meaning.',
                'definition' => 'Meaning, implication, connotation',
                'sentences' => ['___丰富。', '___理解。', '___特殊。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '寓意',
                'pinyin' => 'yù yì',
                'simplified' => '寓意',
                'traditional' => '寓意',
                'part_of_speech' => 'noun',
                'meaning' => 'Moral / Implied meaning',
                'meaning_zh' => '寓意',
                'example_sentence' => '深刻寓意。',
                'example_translation' => 'Profound moral.',
                'definition' => 'Moral, implied meaning',
                'sentences' => ['___故事。', '___象征。', '___美好。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '内涵',
                'pinyin' => 'nèi hán',
                'simplified' => '内涵',
                'traditional' => '內涵',
                'part_of_speech' => 'noun',
                'meaning' => 'Connotation / Essence',
                'meaning_zh' => '内涵',
                'example_sentence' => '丰富内涵。',
                'example_translation' => 'Rich connotation.',
                'definition' => 'Connotation, essence, substance',
                'sentences' => ['___深刻。', '___文化。', '___提升。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '文本',
                'pinyin' => 'wén běn',
                'simplified' => '文本',
                'traditional' => '文本',
                'part_of_speech' => 'noun',
                'meaning' => 'Text',
                'meaning_zh' => '文本',
                'example_sentence' => '原始文本。',
                'example_translation' => 'Original text.',
                'definition' => 'Text, script',
                'sentences' => ['___分析。', '___编辑。', '___内容。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '上下文',
                'pinyin' => 'shàng xià wén',
                'simplified' => '上下文',
                'traditional' => '上下文',
                'part_of_speech' => 'noun',
                'meaning' => 'Context',
                'meaning_zh' => '上下文',
                'example_sentence' => '根据上下文。',
                'example_translation' => 'According to context.',
                'definition' => 'Context',
                'sentences' => ['___理解。', '___联系。', '___推断。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '概括',
                'pinyin' => 'gài kuò',
                'simplified' => '概括',
                'traditional' => '概括',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'To summarize / Summary',
                'meaning_zh' => '概括',
                'example_sentence' => '概括要点。',
                'example_translation' => 'Summarize key points.',
                'definition' => 'To summarize, summary, general',
                'sentences' => ['___能力。', '___性。', '___内容。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '归纳',
                'pinyin' => 'guī nà',
                'simplified' => '归纳',
                'traditional' => '歸納',
                'part_of_speech' => 'verb',
                'meaning' => 'To induce / To summarize',
                'meaning_zh' => '归纳',
                'example_sentence' => '归纳总结。',
                'example_translation' => 'Summarize and conclude.',
                'definition' => 'To induce, to summarize, induction',
                'sentences' => ['___法。', '___整理。', '___要点。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '推测',
                'pinyin' => 'tuī cè',
                'simplified' => '推测',
                'traditional' => '推測',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To speculate / Speculation',
                'meaning_zh' => '推测',
                'example_sentence' => '合理推测。',
                'example_translation' => 'Reasonable speculation.',
                'definition' => 'To speculate, speculation, conjecture',
                'sentences' => ['___结果。', '___原因。', '___意图。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '浏览',
                'pinyin' => 'liú lǎn',
                'simplified' => '浏览',
                'traditional' => '瀏覽',
                'part_of_speech' => 'verb',
                'meaning' => 'To browse / To skim',
                'meaning_zh' => '浏览',
                'example_sentence' => '快速浏览。',
                'example_translation' => 'Quick browse.',
                'definition' => 'To browse, to skim',
                'sentences' => ['___网页。', '___器。', '___信息。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '精读',
                'pinyin' => 'jīng dú',
                'simplified' => '精读',
                'traditional' => '精讀',
                'part_of_speech' => 'verb',
                'meaning' => 'Intensive reading / To read intensively',
                'meaning_zh' => '精读',
                'example_sentence' => '精读课文。',
                'example_translation' => 'Read text intensively.',
                'definition' => 'Intensive reading, to read intensively',
                'sentences' => ['___课程。', '___细读。', '___训练。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '略读',
                'pinyin' => 'lüè dú',
                'simplified' => '略读',
                'traditional' => '略讀',
                'part_of_speech' => 'verb',
                'meaning' => 'To skim / Skimming',
                'meaning_zh' => '略读',
                'example_sentence' => '略读大意。',
                'example_translation' => 'Skim for main idea.',
                'definition' => 'To skim, skimming',
                'sentences' => ['___方法。', '___技巧。', '___快速。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '摘要',
                'pinyin' => 'zhāi yào',
                'simplified' => '摘要',
                'traditional' => '摘要',
                'part_of_speech' => 'noun',
                'meaning' => 'Abstract / Summary',
                'meaning_zh' => '摘要',
                'example_sentence' => '写摘要。',
                'example_translation' => 'Write an abstract.',
                'definition' => 'Abstract, summary, synopsis',
                'sentences' => ['___内容。', '___简洁。', '___论文。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 183,
                'word' => '批注',
                'pinyin' => 'pī zhù',
                'simplified' => '批注',
                'traditional' => '批註',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Annotation / To annotate',
                'meaning_zh' => '批注',
                'example_sentence' => '做批注。',
                'example_translation' => 'Make annotations.',
                'definition' => 'Annotation, to annotate',
                'sentences' => ['___笔记。', '___说明。', '___文章。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 184: Advanced Grammar and Idioms - 高级语法与成语
        $grammarIdiomsVocab = [
            [
                'topic_id' => 184,
                'word' => '语法',
                'pinyin' => 'yǔ fǎ',
                'simplified' => '语法',
                'traditional' => '語法',
                'part_of_speech' => 'noun',
                'meaning' => 'Grammar',
                'meaning_zh' => '语法',
                'example_sentence' => '学习语法。',
                'example_translation' => 'Learn grammar.',
                'definition' => 'Grammar, syntax',
                'sentences' => ['___规则。', '___错误。', '___结构。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '成语',
                'pinyin' => 'chéng yǔ',
                'simplified' => '成语',
                'traditional' => '成語',
                'part_of_speech' => 'noun',
                'meaning' => 'Idiom / Set phrase',
                'meaning_zh' => '成语',
                'example_sentence' => '运用成语。',
                'example_translation' => 'Use idioms.',
                'definition' => 'Idiom, set phrase',
                'sentences' => ['___典故。', '___故事。', '___词典。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '惯用语',
                'pinyin' => 'guàn yòng yǔ',
                'simplified' => '惯用语',
                'traditional' => '慣用語',
                'part_of_speech' => 'noun',
                'meaning' => 'Idiom / Common expression',
                'meaning_zh' => '惯用语',
                'example_sentence' => '日常惯用语。',
                'example_translation' => 'Daily common expressions.',
                'definition' => 'Idiom, common expression',
                'sentences' => ['___表达。', '___运用。', '___学习。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '谚语',
                'pinyin' => 'yàn yǔ',
                'simplified' => '谚语',
                'traditional' => '諺語',
                'part_of_speech' => 'noun',
                'meaning' => 'Proverb / Saying',
                'meaning_zh' => '谚语',
                'example_sentence' => '民间谚语。',
                'example_translation' => 'Folk proverb.',
                'definition' => 'Proverb, saying, adage',
                'sentences' => ['___智慧。', '___俗语。', '___流传。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '俗语',
                'pinyin' => 'sú yǔ',
                'simplified' => '俗语',
                'traditional' => '俗語',
                'part_of_speech' => 'noun',
                'meaning' => 'Common saying / Colloquialism',
                'meaning_zh' => '俗语',
                'example_sentence' => '俗语说。',
                'example_translation' => 'As the saying goes.',
                'definition' => 'Common saying, colloquialism',
                'sentences' => ['___谚语。', '___民间。', '___通俗。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '歇后语',
                'pinyin' => 'xié hòu yǔ',
                'simplified' => '歇后语',
                'traditional' => '歇後語',
                'part_of_speech' => 'noun',
                'meaning' => 'Two-part allegorical saying',
                'meaning_zh' => '歇后语',
                'example_sentence' => '有趣的歇后语。',
                'example_translation' => 'Interesting two-part saying.',
                'definition' => 'Two-part allegorical saying',
                'sentences' => ['___幽默。', '___民间。', '___特色。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '词组',
                'pinyin' => 'cí zǔ',
                'simplified' => '词组',
                'traditional' => '詞組',
                'part_of_speech' => 'noun',
                'meaning' => 'Phrase / Word group',
                'meaning_zh' => '词组',
                'example_sentence' => '固定词组。',
                'example_translation' => 'Fixed phrase.',
                'definition' => 'Phrase, word group',
                'sentences' => ['___搭配。', '___结构。', '___动词。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '短语',
                'pinyin' => 'duǎn yǔ',
                'simplified' => '短语',
                'traditional' => '短語',
                'part_of_speech' => 'noun',
                'meaning' => 'Phrase',
                'meaning_zh' => '短语',
                'example_sentence' => '常用短语。',
                'example_translation' => 'Common phrases.',
                'definition' => 'Phrase',
                'sentences' => ['___动词。', '___介词。', '___固定。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '搭配',
                'pinyin' => 'dā pèi',
                'simplified' => '搭配',
                'traditional' => '搭配',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To match / Collocation',
                'meaning_zh' => '搭配',
                'example_sentence' => '词语搭配。',
                'example_translation' => 'Word collocation.',
                'definition' => 'To match, collocation, to pair',
                'sentences' => ['___合理。', '___固定。', '___颜色。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '语序',
                'pinyin' => 'yǔ xù',
                'simplified' => '语序',
                'traditional' => '語序',
                'part_of_speech' => 'noun',
                'meaning' => 'Word order',
                'meaning_zh' => '语序',
                'example_sentence' => '正确语序。',
                'example_translation' => 'Correct word order.',
                'definition' => 'Word order, sequence',
                'sentences' => ['___调整。', '___错误。', '___规则。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '语气',
                'pinyin' => 'yǔ qì',
                'simplified' => '语气',
                'traditional' => '語氣',
                'part_of_speech' => 'noun',
                'meaning' => 'Tone / Mood',
                'meaning_zh' => '语气',
                'example_sentence' => '委婉语气。',
                'example_translation' => 'Tactful tone.',
                'definition' => 'Tone, mood, manner of speaking',
                'sentences' => ['___词。', '___强硬。', '___助词。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '语态',
                'pinyin' => 'yǔ tài',
                'simplified' => '语态',
                'traditional' => '語態',
                'part_of_speech' => 'noun',
                'meaning' => 'Voice (grammar)',
                'meaning_zh' => '语态',
                'example_sentence' => '被动语态。',
                'example_translation' => 'Passive voice.',
                'definition' => 'Voice (grammar), grammatical voice',
                'sentences' => ['___主动。', '___转换。', '___使用。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '时态',
                'pinyin' => 'shí tài',
                'simplified' => '时态',
                'traditional' => '時態',
                'part_of_speech' => 'noun',
                'meaning' => 'Tense',
                'meaning_zh' => '时态',
                'example_sentence' => '过去时态。',
                'example_translation' => 'Past tense.',
                'definition' => 'Tense, grammatical tense',
                'sentences' => ['___变化。', '___现在。', '___将来。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '虚拟语气',
                'pinyin' => 'xū nǐ yǔ qì',
                'simplified' => '虚拟语气',
                'traditional' => '虛擬語氣',
                'part_of_speech' => 'noun',
                'meaning' => 'Subjunctive mood',
                'meaning_zh' => '虚拟语气',
                'example_sentence' => '使用虚拟语气。',
                'example_translation' => 'Use subjunctive mood.',
                'definition' => 'Subjunctive mood',
                'sentences' => ['___条件。', '___假设。', '___句型。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '倒装',
                'pinyin' => 'dào zhuāng',
                'simplified' => '倒装',
                'traditional' => '倒裝',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Inversion / To invert',
                'meaning_zh' => '倒装',
                'example_sentence' => '倒装句。',
                'example_translation' => 'Inverted sentence.',
                'definition' => 'Inversion, to invert',
                'sentences' => ['___句式。', '___语序。', '___结构。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '省略',
                'pinyin' => 'shěng lüè',
                'simplified' => '省略',
                'traditional' => '省略',
                'part_of_speech' => 'verb',
                'meaning' => 'To omit / Omission',
                'meaning_zh' => '省略',
                'example_sentence' => '省略号。',
                'example_translation' => 'Ellipsis.',
                'definition' => 'To omit, omission',
                'sentences' => ['___成分。', '___句。', '___不计。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '强调',
                'pinyin' => 'qiáng diào',
                'simplified' => '强调',
                'traditional' => '強調',
                'part_of_speech' => 'verb',
                'meaning' => 'To emphasize / Emphasis',
                'meaning_zh' => '强调',
                'example_sentence' => '强调重点。',
                'example_translation' => 'Emphasize key points.',
                'definition' => 'To emphasize, emphasis',
                'sentences' => ['___句。', '___重要性。', '___指出。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '双重否定',
                'pinyin' => 'shuāng chóng fǒu dìng',
                'simplified' => '双重否定',
                'traditional' => '雙重否定',
                'part_of_speech' => 'noun',
                'meaning' => 'Double negative',
                'meaning_zh' => '双重否定',
                'example_sentence' => '双重否定句。',
                'example_translation' => 'Double negative sentence.',
                'definition' => 'Double negative',
                'sentences' => ['___表示肯定。', '___句式。', '___用法。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '比喻',
                'pinyin' => 'bǐ yù',
                'simplified' => '比喻',
                'traditional' => '比喻',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Metaphor / To compare',
                'meaning_zh' => '比喻',
                'example_sentence' => '形象比喻。',
                'example_translation' => 'Vivid metaphor.',
                'definition' => 'Metaphor, to compare, simile',
                'sentences' => ['___手法。', '___恰当。', '___句。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 184,
                'word' => '反义词',
                'pinyin' => 'fǎn yì cí',
                'simplified' => '反义词',
                'traditional' => '反義詞',
                'part_of_speech' => 'noun',
                'meaning' => 'Antonym',
                'meaning_zh' => '反义词',
                'example_sentence' => '找反义词。',
                'example_translation' => 'Find antonyms.',
                'definition' => 'Antonym, opposite word',
                'sentences' => ['___对比。', '___配对。', '___词典。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($writingVocab, $readingVocab, $grammarIdiomsVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
