<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic173to175Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [173, 175])->delete();

        // Topic 173: Space and the Universe - 太空与宇宙
        $spaceVocab = [
            [
                'topic_id' => 173,
                'word' => '太空',
                'pinyin' => 'tài kōng',
                'simplified' => '太空',
                'traditional' => '太空',
                'part_of_speech' => 'noun',
                'meaning' => 'Space / Outer space',
                'meaning_zh' => '太空',
                'example_sentence' => '太空探索。',
                'example_translation' => 'Space exploration.',
                'definition' => 'Space, outer space',
                'sentences' => ['___站。', '___飞行。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '宇宙',
                'pinyin' => 'yǔ zhòu',
                'simplified' => '宇宙',
                'traditional' => '宇宙',
                'part_of_speech' => 'noun',
                'meaning' => 'Universe / Cosmos',
                'meaning_zh' => '宇宙',
                'example_sentence' => '宇宙的奥秘。',
                'example_translation' => 'The mysteries of the universe.',
                'definition' => 'Universe, cosmos',
                'sentences' => ['___飞船。', '___探索。', '___起源。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '星球',
                'pinyin' => 'xīng qiú',
                'simplified' => '星球',
                'traditional' => '星球',
                'part_of_speech' => 'noun',
                'meaning' => 'Planet / Star',
                'meaning_zh' => '星球',
                'example_sentence' => '遥远的星球。',
                'example_translation' => 'Distant planet.',
                'definition' => 'Planet, celestial body, star',
                'sentences' => ['___大战。', '___表面。', '___探测。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '行星',
                'pinyin' => 'xíng xīng',
                'simplified' => '行星',
                'traditional' => '行星',
                'part_of_speech' => 'noun',
                'meaning' => 'Planet',
                'meaning_zh' => '行星',
                'example_sentence' => '太阳系的行星。',
                'example_translation' => 'Planets of the solar system.',
                'definition' => 'Planet',
                'sentences' => ['___运行。', '___轨道。', '___系统。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '恒星',
                'pinyin' => 'héng xīng',
                'simplified' => '恒星',
                'traditional' => '恆星',
                'part_of_speech' => 'noun',
                'meaning' => 'Star / Fixed star',
                'meaning_zh' => '恒星',
                'example_sentence' => '恒星发光。',
                'example_translation' => 'Stars emit light.',
                'definition' => 'Star, fixed star',
                'sentences' => ['___系统。', '___演化。', '___质量。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '卫星',
                'pinyin' => 'wèi xīng',
                'simplified' => '卫星',
                'traditional' => '衛星',
                'part_of_speech' => 'noun',
                'meaning' => 'Satellite',
                'meaning_zh' => '卫星',
                'example_sentence' => '发射卫星。',
                'example_translation' => 'Launch a satellite.',
                'definition' => 'Satellite',
                'sentences' => ['___通信。', '___导航。', '___电视。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '航天',
                'pinyin' => 'háng tiān',
                'simplified' => '航天',
                'traditional' => '航天',
                'part_of_speech' => 'noun',
                'meaning' => 'Spaceflight / Aerospace',
                'meaning_zh' => '航天',
                'example_sentence' => '航天技术。',
                'example_translation' => 'Aerospace technology.',
                'definition' => 'Spaceflight, aerospace',
                'sentences' => ['___员。', '___工程。', '___事业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '飞船',
                'pinyin' => 'fēi chuán',
                'simplified' => '飞船',
                'traditional' => '飛船',
                'part_of_speech' => 'noun',
                'meaning' => 'Spacecraft / Spaceship',
                'meaning_zh' => '飞船',
                'example_sentence' => '载人飞船。',
                'example_translation' => 'Manned spacecraft.',
                'definition' => 'Spacecraft, spaceship',
                'sentences' => ['___发射。', '___返回。', '___对接。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '火箭',
                'pinyin' => 'huǒ jiàn',
                'simplified' => '火箭',
                'traditional' => '火箭',
                'part_of_speech' => 'noun',
                'meaning' => 'Rocket',
                'meaning_zh' => '火箭',
                'example_sentence' => '火箭发射。',
                'example_translation' => 'Rocket launch.',
                'definition' => 'Rocket, missile',
                'sentences' => ['___推进。', '___燃料。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '轨道',
                'pinyin' => 'guǐ dào',
                'simplified' => '轨道',
                'traditional' => '軌道',
                'part_of_speech' => 'noun',
                'meaning' => 'Orbit / Track',
                'meaning_zh' => '轨道',
                'example_sentence' => '进入轨道。',
                'example_translation' => 'Enter orbit.',
                'definition' => 'Orbit, track, trajectory',
                'sentences' => ['___运行。', '___交通。', '___调整。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '探测',
                'pinyin' => 'tàn cè',
                'simplified' => '探测',
                'traditional' => '探測',
                'part_of_speech' => 'verb',
                'meaning' => 'To explore / To probe',
                'meaning_zh' => '探测',
                'example_sentence' => '火星探测。',
                'example_translation' => 'Mars exploration.',
                'definition' => 'To explore, to probe, to detect',
                'sentences' => ['___器。', '___任务。', '___数据。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '登陆',
                'pinyin' => 'dēng lù',
                'simplified' => '登陆',
                'traditional' => '登陸',
                'part_of_speech' => 'verb',
                'meaning' => 'To land / To log in',
                'meaning_zh' => '登陆',
                'example_sentence' => '月球登陆。',
                'example_translation' => 'Moon landing.',
                'definition' => 'To land, to log in',
                'sentences' => ['___火星。', '___计划。', '___成功。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '重力',
                'pinyin' => 'zhòng lì',
                'simplified' => '重力',
                'traditional' => '重力',
                'part_of_speech' => 'noun',
                'meaning' => 'Gravity',
                'meaning_zh' => '重力',
                'example_sentence' => '失去重力。',
                'example_translation' => 'Lose gravity.',
                'definition' => 'Gravity, gravitational force',
                'sentences' => ['___作用。', '___场。', '___加速度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '引力',
                'pinyin' => 'yǐn lì',
                'simplified' => '引力',
                'traditional' => '引力',
                'part_of_speech' => 'noun',
                'meaning' => 'Gravitational force / Attraction',
                'meaning_zh' => '引力',
                'example_sentence' => '万有引力。',
                'example_translation' => 'Universal gravitation.',
                'definition' => 'Gravitational force, attraction',
                'sentences' => ['___波。', '___定律。', '___相互。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '天文',
                'pinyin' => 'tiān wén',
                'simplified' => '天文',
                'traditional' => '天文',
                'part_of_speech' => 'noun',
                'meaning' => 'Astronomy',
                'meaning_zh' => '天文',
                'example_sentence' => '天文学。',
                'example_translation' => 'Astronomy.',
                'definition' => 'Astronomy, astronomical',
                'sentences' => ['___观测。', '___数字。', '___台。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '星系',
                'pinyin' => 'xīng xì',
                'simplified' => '星系',
                'traditional' => '星系',
                'part_of_speech' => 'noun',
                'meaning' => 'Galaxy',
                'meaning_zh' => '星系',
                'example_sentence' => '银河系。',
                'example_translation' => 'Milky Way galaxy.',
                'definition' => 'Galaxy, stellar system',
                'sentences' => ['___形成。', '___演化。', '___结构。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '陨石',
                'pinyin' => 'yǔn shí',
                'simplified' => '陨石',
                'traditional' => '隕石',
                'part_of_speech' => 'noun',
                'meaning' => 'Meteorite',
                'meaning_zh' => '陨石',
                'example_sentence' => '陨石坑。',
                'example_translation' => 'Meteorite crater.',
                'definition' => 'Meteorite, meteorolite',
                'sentences' => ['___撞击。', '___研究。', '___样本。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '黑洞',
                'pinyin' => 'hēi dòng',
                'simplified' => '黑洞',
                'traditional' => '黑洞',
                'part_of_speech' => 'noun',
                'meaning' => 'Black hole',
                'meaning_zh' => '黑洞',
                'example_sentence' => '黑洞理论。',
                'example_translation' => 'Black hole theory.',
                'definition' => 'Black hole',
                'sentences' => ['___吸引。', '___形成。', '___研究。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '外星',
                'pinyin' => 'wài xīng',
                'simplified' => '外星',
                'traditional' => '外星',
                'part_of_speech' => 'adjective',
                'meaning' => 'Extraterrestrial / Alien',
                'meaning_zh' => '外星',
                'example_sentence' => '外星人。',
                'example_translation' => 'Extraterrestrial / Alien.',
                'definition' => 'Extraterrestrial, alien, outer space',
                'sentences' => ['___生命。', '___文明。', '___探索。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 173,
                'word' => '辐射',
                'pinyin' => 'fú shè',
                'simplified' => '辐射',
                'traditional' => '輻射',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Radiation / To radiate',
                'meaning_zh' => '辐射',
                'example_sentence' => '宇宙辐射。',
                'example_translation' => 'Cosmic radiation.',
                'definition' => 'Radiation, to radiate',
                'sentences' => ['___能量。', '___防护。', '___污染。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 174: Medicine and Health - 医学与健康
        $medicineVocab = [
            [
                'topic_id' => 174,
                'word' => '医学',
                'pinyin' => 'yī xué',
                'simplified' => '医学',
                'traditional' => '醫學',
                'part_of_speech' => 'noun',
                'meaning' => 'Medicine / Medical science',
                'meaning_zh' => '医学',
                'example_sentence' => '研究医学。',
                'example_translation' => 'Study medicine.',
                'definition' => 'Medicine, medical science',
                'sentences' => ['___发展。', '___院。', '___专业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '疾病',
                'pinyin' => 'jí bìng',
                'simplified' => '疾病',
                'traditional' => '疾病',
                'part_of_speech' => 'noun',
                'meaning' => 'Disease / Illness',
                'meaning_zh' => '疾病',
                'example_sentence' => '预防疾病。',
                'example_translation' => 'Prevent disease.',
                'definition' => 'Disease, illness, sickness',
                'sentences' => ['___控制。', '___传播。', '___治疗。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '诊断',
                'pinyin' => 'zhěn duàn',
                'simplified' => '诊断',
                'traditional' => '診斷',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To diagnose / Diagnosis',
                'meaning_zh' => '诊断',
                'example_sentence' => '医生诊断。',
                'example_translation' => 'Doctor diagnoses.',
                'definition' => 'To diagnose, diagnosis',
                'sentences' => ['___结果。', '___技术。', '___准确。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '治疗',
                'pinyin' => 'zhì liáo',
                'simplified' => '治疗',
                'traditional' => '治療',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Treatment / To treat',
                'meaning_zh' => '治疗',
                'example_sentence' => '接受治疗。',
                'example_translation' => 'Receive treatment.',
                'definition' => 'Treatment, to treat, therapy',
                'sentences' => ['___方案。', '___效果。', '___费用。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '手术',
                'pinyin' => 'shǒu shù',
                'simplified' => '手术',
                'traditional' => '手術',
                'part_of_speech' => 'noun',
                'meaning' => 'Surgery / Operation',
                'meaning_zh' => '手术',
                'example_sentence' => '做手术。',
                'example_translation' => 'Perform surgery.',
                'definition' => 'Surgery, operation, surgical procedure',
                'sentences' => ['___成功。', '___室。', '___风险。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '药物',
                'pinyin' => 'yào wù',
                'simplified' => '药物',
                'traditional' => '藥物',
                'part_of_speech' => 'noun',
                'meaning' => 'Medicine / Drug',
                'meaning_zh' => '药物',
                'example_sentence' => '服用药物。',
                'example_translation' => 'Take medicine.',
                'definition' => 'Medicine, drug, medication',
                'sentences' => ['___治疗。', '___副作用。', '___研发。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '疫苗',
                'pinyin' => 'yì miáo',
                'simplified' => '疫苗',
                'traditional' => '疫苗',
                'part_of_speech' => 'noun',
                'meaning' => 'Vaccine',
                'meaning_zh' => '疫苗',
                'example_sentence' => '接种疫苗。',
                'example_translation' => 'Get vaccinated.',
                'definition' => 'Vaccine, vaccination',
                'sentences' => ['___研发。', '___注射。', '___预防。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '症状',
                'pinyin' => 'zhèng zhuàng',
                'simplified' => '症状',
                'traditional' => '症狀',
                'part_of_speech' => 'noun',
                'meaning' => 'Symptom',
                'meaning_zh' => '症状',
                'example_sentence' => '出现症状。',
                'example_translation' => 'Show symptoms.',
                'definition' => 'Symptom, sign',
                'sentences' => ['___明显。', '___缓解。', '___描述。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '病毒',
                'pinyin' => 'bìng dú',
                'simplified' => '病毒',
                'traditional' => '病毒',
                'part_of_speech' => 'noun',
                'meaning' => 'Virus',
                'meaning_zh' => '病毒',
                'example_sentence' => '病毒传播。',
                'example_translation' => 'Virus spread.',
                'definition' => 'Virus',
                'sentences' => ['___感染。', '___变异。', '___防治。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '细菌',
                'pinyin' => 'xì jūn',
                'simplified' => '细菌',
                'traditional' => '細菌',
                'part_of_speech' => 'noun',
                'meaning' => 'Bacteria / Germ',
                'meaning_zh' => '细菌',
                'example_sentence' => '消灭细菌。',
                'example_translation' => 'Eliminate bacteria.',
                'definition' => 'Bacteria, germ, microbe',
                'sentences' => ['___感染。', '___培养。', '___耐药。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '免疫',
                'pinyin' => 'miǎn yì',
                'simplified' => '免疫',
                'traditional' => '免疫',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Immunity / To immunize',
                'meaning_zh' => '免疫',
                'example_sentence' => '增强免疫力。',
                'example_translation' => 'Strengthen immunity.',
                'definition' => 'Immunity, to immunize, immune',
                'sentences' => ['___系统。', '___功能。', '___力。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '康复',
                'pinyin' => 'kāng fù',
                'simplified' => '康复',
                'traditional' => '康復',
                'part_of_speech' => 'verb',
                'meaning' => 'To recover / To rehabilitate',
                'meaning_zh' => '康复',
                'example_sentence' => '身体康复。',
                'example_translation' => 'Physical recovery.',
                'definition' => 'To recover, to rehabilitate, rehabilitation',
                'sentences' => ['___训练。', '___中心。', '___治疗。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '护理',
                'pinyin' => 'hù lǐ',
                'simplified' => '护理',
                'traditional' => '護理',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Nursing / To nurse',
                'meaning_zh' => '护理',
                'example_sentence' => '专业护理。',
                'example_translation' => 'Professional nursing.',
                'definition' => 'Nursing, to nurse, care',
                'sentences' => ['___人员。', '___工作。', '___学。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '器官',
                'pinyin' => 'qì guān',
                'simplified' => '器官',
                'traditional' => '器官',
                'part_of_speech' => 'noun',
                'meaning' => 'Organ',
                'meaning_zh' => '器官',
                'example_sentence' => '器官移植。',
                'example_translation' => 'Organ transplant.',
                'definition' => 'Organ, body organ',
                'sentences' => ['___捐献。', '___功能。', '___衰竭。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '基因',
                'pinyin' => 'jī yīn',
                'simplified' => '基因',
                'traditional' => '基因',
                'part_of_speech' => 'noun',
                'meaning' => 'Gene',
                'meaning_zh' => '基因',
                'example_sentence' => '基因检测。',
                'example_translation' => 'Gene testing.',
                'definition' => 'Gene, genetic',
                'sentences' => ['___突变。', '___技术。', '___遗传。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '遗传',
                'pinyin' => 'yí chuán',
                'simplified' => '遗传',
                'traditional' => '遺傳',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'Heredity / Hereditary',
                'meaning_zh' => '遗传',
                'example_sentence' => '遗传疾病。',
                'example_translation' => 'Hereditary disease.',
                'definition' => 'Heredity, hereditary, genetic',
                'sentences' => ['___基因。', '___学。', '___物质。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '营养',
                'pinyin' => 'yíng yǎng',
                'simplified' => '营养',
                'traditional' => '營養',
                'part_of_speech' => 'noun',
                'meaning' => 'Nutrition',
                'meaning_zh' => '营养',
                'example_sentence' => '均衡营养。',
                'example_translation' => 'Balanced nutrition.',
                'definition' => 'Nutrition, nourishment',
                'sentences' => ['___丰富。', '___不良。', '___价值。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '保健',
                'pinyin' => 'bǎo jiàn',
                'simplified' => '保健',
                'traditional' => '保健',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Health care / To maintain health',
                'meaning_zh' => '保健',
                'example_sentence' => '注意保健。',
                'example_translation' => 'Pay attention to health care.',
                'definition' => 'Health care, to maintain health',
                'sentences' => ['___品。', '___医生。', '___知识。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '慢性',
                'pinyin' => 'màn xìng',
                'simplified' => '慢性',
                'traditional' => '慢性',
                'part_of_speech' => 'adjective',
                'meaning' => 'Chronic',
                'meaning_zh' => '慢性',
                'example_sentence' => '慢性疾病。',
                'example_translation' => 'Chronic disease.',
                'definition' => 'Chronic, long-term',
                'sentences' => ['___病。', '___炎症。', '___咳嗽。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 174,
                'word' => '急性',
                'pinyin' => 'jí xìng',
                'simplified' => '急性',
                'traditional' => '急性',
                'part_of_speech' => 'adjective',
                'meaning' => 'Acute',
                'meaning_zh' => '急性',
                'example_sentence' => '急性发作。',
                'example_translation' => 'Acute attack.',
                'definition' => 'Acute, sudden',
                'sentences' => ['___病。', '___感染。', '___疼痛。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 175: Pop Culture and Media - 流行文化与媒体
        $popCultureVocab = [
            [
                'topic_id' => 175,
                'word' => '流行',
                'pinyin' => 'liú xíng',
                'simplified' => '流行',
                'traditional' => '流行',
                'part_of_speech' => 'verb/adjective',
                'meaning' => 'Popular / To be popular',
                'meaning_zh' => '流行',
                'example_sentence' => '流行音乐。',
                'example_translation' => 'Pop music.',
                'definition' => 'Popular, to be popular, fashionable',
                'sentences' => ['___趋势。', '___文化。', '___歌曲。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '文化',
                'pinyin' => 'wén huà',
                'simplified' => '文化',
                'traditional' => '文化',
                'part_of_speech' => 'noun',
                'meaning' => 'Culture',
                'meaning_zh' => '文化',
                'example_sentence' => '传统文化。',
                'example_translation' => 'Traditional culture.',
                'definition' => 'Culture, civilization',
                'sentences' => ['___交流。', '___遗产。', '___产业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '媒体',
                'pinyin' => 'méi tǐ',
                'simplified' => '媒体',
                'traditional' => '媒體',
                'part_of_speech' => 'noun',
                'meaning' => 'Media',
                'meaning_zh' => '媒体',
                'example_sentence' => '新闻媒体。',
                'example_translation' => 'News media.',
                'definition' => 'Media, mass media',
                'sentences' => ['___报道。', '___传播。', '___平台。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '娱乐',
                'pinyin' => 'yú lè',
                'simplified' => '娱乐',
                'traditional' => '娛樂',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Entertainment / To entertain',
                'meaning_zh' => '娱乐',
                'example_sentence' => '娱乐节目。',
                'example_translation' => 'Entertainment program.',
                'definition' => 'Entertainment, to entertain, recreation',
                'sentences' => ['___圈。', '___活动。', '___产业。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '明星',
                'pinyin' => 'míng xīng',
                'simplified' => '明星',
                'traditional' => '明星',
                'part_of_speech' => 'noun',
                'meaning' => 'Star / Celebrity',
                'meaning_zh' => '明星',
                'example_sentence' => '电影明星。',
                'example_translation' => 'Movie star.',
                'definition' => 'Star, celebrity, famous person',
                'sentences' => ['___效应。', '___粉丝。', '___演唱会。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '偶像',
                'pinyin' => 'ǒu xiàng',
                'simplified' => '偶像',
                'traditional' => '偶像',
                'part_of_speech' => 'noun',
                'meaning' => 'Idol',
                'meaning_zh' => '偶像',
                'example_sentence' => '青年偶像。',
                'example_translation' => 'Youth idol.',
                'definition' => 'Idol, icon',
                'sentences' => ['___崇拜。', '___剧。', '___歌手。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '粉丝',
                'pinyin' => 'fěn sī',
                'simplified' => '粉丝',
                'traditional' => '粉絲',
                'part_of_speech' => 'noun',
                'meaning' => 'Fan / Follower',
                'meaning_zh' => '粉丝',
                'example_sentence' => '忠实粉丝。',
                'example_translation' => 'Loyal fan.',
                'definition' => 'Fan, follower, supporter',
                'sentences' => ['___数量。', '___群体。', '___经济。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '时尚',
                'pinyin' => 'shí shàng',
                'simplified' => '时尚',
                'traditional' => '時尚',
                'part_of_speech' => 'noun/adjective',
                'meaning' => 'Fashion / Fashionable',
                'meaning_zh' => '时尚',
                'example_sentence' => '追求时尚。',
                'example_translation' => 'Pursue fashion.',
                'definition' => 'Fashion, fashionable, trendy',
                'sentences' => ['___潮流。', '___界。', '___设计。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '潮流',
                'pinyin' => 'cháo liú',
                'simplified' => '潮流',
                'traditional' => '潮流',
                'part_of_speech' => 'noun',
                'meaning' => 'Trend / Current',
                'meaning_zh' => '潮流',
                'example_sentence' => '时代潮流。',
                'example_translation' => 'Current of the times.',
                'definition' => 'Trend, current, tide',
                'sentences' => ['___引领。', '___趋势。', '___文化。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '影视',
                'pinyin' => 'yǐng shì',
                'simplified' => '影视',
                'traditional' => '影視',
                'part_of_speech' => 'noun',
                'meaning' => 'Film and television',
                'meaning_zh' => '影视',
                'example_sentence' => '影视作品。',
                'example_translation' => 'Film and television works.',
                'definition' => 'Film and television, movies and TV',
                'sentences' => ['___产业。', '___制作。', '___剧。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '综艺',
                'pinyin' => 'zōng yì',
                'simplified' => '综艺',
                'traditional' => '綜藝',
                'part_of_speech' => 'noun',
                'meaning' => 'Variety show',
                'meaning_zh' => '综艺',
                'example_sentence' => '综艺节目。',
                'example_translation' => 'Variety show.',
                'definition' => 'Variety show, variety entertainment',
                'sentences' => ['___节目。', '___娱乐。', '___主持。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '直播',
                'pinyin' => 'zhí bō',
                'simplified' => '直播',
                'traditional' => '直播',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Live broadcast / To broadcast live',
                'meaning_zh' => '直播',
                'example_sentence' => '网络直播。',
                'example_translation' => 'Online live broadcast.',
                'definition' => 'Live broadcast, to broadcast live',
                'sentences' => ['___平台。', '___带货。', '___间。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '主播',
                'pinyin' => 'zhǔ bō',
                'simplified' => '主播',
                'traditional' => '主播',
                'part_of_speech' => 'noun',
                'meaning' => 'Anchor / Host / Streamer',
                'meaning_zh' => '主播',
                'example_sentence' => '网络主播。',
                'example_translation' => 'Online streamer.',
                'definition' => 'Anchor, host, streamer',
                'sentences' => ['___新闻。', '___直播。', '___人气。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '网红',
                'pinyin' => 'wǎng hóng',
                'simplified' => '网红',
                'traditional' => '網紅',
                'part_of_speech' => 'noun',
                'meaning' => 'Internet celebrity / Influencer',
                'meaning_zh' => '网红',
                'example_sentence' => '成为网红。',
                'example_translation' => 'Become an internet celebrity.',
                'definition' => 'Internet celebrity, influencer, online star',
                'sentences' => ['___经济。', '___打卡。', '___产品。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '热点',
                'pinyin' => 'rè diǎn',
                'simplified' => '热点',
                'traditional' => '熱點',
                'part_of_speech' => 'noun',
                'meaning' => 'Hot topic / Hotspot',
                'meaning_zh' => '热点',
                'example_sentence' => '社会热点。',
                'example_translation' => 'Social hot topic.',
                'definition' => 'Hot topic, hotspot, focus',
                'sentences' => ['___新闻。', '___问题。', '___话题。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '话题',
                'pinyin' => 'huà tí',
                'simplified' => '话题',
                'traditional' => '話題',
                'part_of_speech' => 'noun',
                'meaning' => 'Topic / Subject',
                'meaning_zh' => '话题',
                'example_sentence' => '热门话题。',
                'example_translation' => 'Hot topic.',
                'definition' => 'Topic, subject, talking point',
                'sentences' => ['___讨论。', '___人物。', '___榜。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '传播',
                'pinyin' => 'chuán bō',
                'simplified' => '传播',
                'traditional' => '傳播',
                'part_of_speech' => 'verb',
                'meaning' => 'To spread / To disseminate',
                'meaning_zh' => '传播',
                'example_sentence' => '信息传播。',
                'example_translation' => 'Information dissemination.',
                'definition' => 'To spread, to disseminate, propagation',
                'sentences' => ['___速度。', '___范围。', '___学。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '影响力',
                'pinyin' => 'yǐng xiǎng lì',
                'simplified' => '影响力',
                'traditional' => '影響力',
                'part_of_speech' => 'noun',
                'meaning' => 'Influence',
                'meaning_zh' => '影响力',
                'example_sentence' => '提高影响力。',
                'example_translation' => 'Increase influence.',
                'definition' => 'Influence, impact',
                'sentences' => ['___扩大。', '___巨大。', '___人物。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '观众',
                'pinyin' => 'guān zhòng',
                'simplified' => '观众',
                'traditional' => '觀眾',
                'part_of_speech' => 'noun',
                'meaning' => 'Audience / Spectator',
                'meaning_zh' => '观众',
                'example_sentence' => '吸引观众。',
                'example_translation' => 'Attract audience.',
                'definition' => 'Audience, spectator, viewer',
                'sentences' => ['___反应。', '___群体。', '___人数。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 175,
                'word' => '收视率',
                'pinyin' => 'shōu shì lǜ',
                'simplified' => '收视率',
                'traditional' => '收視率',
                'part_of_speech' => 'noun',
                'meaning' => 'Audience rating / Viewership',
                'meaning_zh' => '收视率',
                'example_sentence' => '提高收视率。',
                'example_translation' => 'Increase audience rating.',
                'definition' => 'Audience rating, viewership, ratings',
                'sentences' => ['___高。', '___统计。', '___冠军。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($spaceVocab, $medicineVocab, $popCultureVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
