<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HSK6Topic161to163Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clean existing data for these topics to avoid duplicates
        Vocabulary::whereBetween('topic_id', [161, 163])->delete();

        // Topic 161: Arts and Literature - 艺术与文学
        $artsVocab = [
            [
                'topic_id' => 161,
                'word' => '文学',
                'pinyin' => 'wén xué',
                'simplified' => '文学',
                'traditional' => '文學',
                'part_of_speech' => 'noun',
                'meaning' => 'Literature',
                'meaning_zh' => '文学',
                'example_sentence' => '中国文学。',
                'example_translation' => 'Chinese literature.',
                'definition' => 'Literature, literary works',
                'sentences' => ['___作品。', '___创作。', '___研究。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '诗歌',
                'pinyin' => 'shī gē',
                'simplified' => '诗歌',
                'traditional' => '詩歌',
                'part_of_speech' => 'noun',
                'meaning' => 'Poetry / Poem',
                'meaning_zh' => '诗歌',
                'example_sentence' => '朗诵诗歌。',
                'example_translation' => 'Recite poetry.',
                'definition' => 'Poetry, poem, verse',
                'sentences' => ['___创作。', '___鉴赏。', '___集。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '散文',
                'pinyin' => 'sǎn wén',
                'simplified' => '散文',
                'traditional' => '散文',
                'part_of_speech' => 'noun',
                'meaning' => 'Prose / Essay',
                'meaning_zh' => '散文',
                'example_sentence' => '写散文。',
                'example_translation' => 'Write prose.',
                'definition' => 'Prose, essay',
                'sentences' => ['___作品。', '___集。', '___家。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '戏剧',
                'pinyin' => 'xì jù',
                'simplified' => '戏剧',
                'traditional' => '戲劇',
                'part_of_speech' => 'noun',
                'meaning' => 'Drama / Play',
                'meaning_zh' => '戏剧',
                'example_sentence' => '戏剧表演。',
                'example_translation' => 'Drama performance.',
                'definition' => 'Drama, play, theater',
                'sentences' => ['___舞台。', '___艺术。', '___演员。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '绘画',
                'pinyin' => 'huì huà',
                'simplified' => '绘画',
                'traditional' => '繪畫',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Painting / To paint',
                'meaning_zh' => '绘画',
                'example_sentence' => '学习绘画。',
                'example_translation' => 'Learn painting.',
                'definition' => 'Painting, to paint, drawing',
                'sentences' => ['___艺术。', '___作品。', '___技巧。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '雕塑',
                'pinyin' => 'diāo sù',
                'simplified' => '雕塑',
                'traditional' => '雕塑',
                'part_of_speech' => 'noun',
                'meaning' => 'Sculpture',
                'meaning_zh' => '雕塑',
                'example_sentence' => '雕塑作品。',
                'example_translation' => 'Sculpture work.',
                'definition' => 'Sculpture, statue',
                'sentences' => ['___艺术。', '___家。', '___展览。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '摄影',
                'pinyin' => 'shè yǐng',
                'simplified' => '摄影',
                'traditional' => '攝影',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Photography / To photograph',
                'meaning_zh' => '摄影',
                'example_sentence' => '摄影艺术。',
                'example_translation' => 'Photographic art.',
                'definition' => 'Photography, to photograph',
                'sentences' => ['___作品。', '___师。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '音乐',
                'pinyin' => 'yīn yuè',
                'simplified' => '音乐',
                'traditional' => '音樂',
                'part_of_speech' => 'noun',
                'meaning' => 'Music',
                'meaning_zh' => '音乐',
                'example_sentence' => '欣赏音乐。',
                'example_translation' => 'Appreciate music.',
                'definition' => 'Music, musical',
                'sentences' => ['___会。', '___家。', '___创作。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '交响乐',
                'pinyin' => 'jiāo xiǎng yuè',
                'simplified' => '交响乐',
                'traditional' => '交響樂',
                'part_of_speech' => 'noun',
                'meaning' => 'Symphony',
                'meaning_zh' => '交响乐',
                'example_sentence' => '交响乐团。',
                'example_translation' => 'Symphony orchestra.',
                'definition' => 'Symphony, symphonic music',
                'sentences' => ['___演奏。', '___团。', '___作品。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '歌剧',
                'pinyin' => 'gē jù',
                'simplified' => '歌剧',
                'traditional' => '歌劇',
                'part_of_speech' => 'noun',
                'meaning' => 'Opera',
                'meaning_zh' => '歌剧',
                'example_sentence' => '观看歌剧。',
                'example_translation' => 'Watch opera.',
                'definition' => 'Opera, operatic performance',
                'sentences' => ['___院。', '___表演。', '___艺术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '舞蹈',
                'pinyin' => 'wǔ dǎo',
                'simplified' => '舞蹈',
                'traditional' => '舞蹈',
                'part_of_speech' => 'noun',
                'meaning' => 'Dance',
                'meaning_zh' => '舞蹈',
                'example_sentence' => '学习舞蹈。',
                'example_translation' => 'Learn dance.',
                'definition' => 'Dance, dancing',
                'sentences' => ['___表演。', '___家。', '___艺术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '芭蕾舞',
                'pinyin' => 'bā lěi wǔ',
                'simplified' => '芭蕾舞',
                'traditional' => '芭蕾舞',
                'part_of_speech' => 'noun',
                'meaning' => 'Ballet',
                'meaning_zh' => '芭蕾舞',
                'example_sentence' => '芭蕾舞表演。',
                'example_translation' => 'Ballet performance.',
                'definition' => 'Ballet, ballet dance',
                'sentences' => ['___演员。', '___团。', '___剧。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '创作',
                'pinyin' => 'chuàng zuò',
                'simplified' => '创作',
                'traditional' => '創作',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To create / Creation',
                'meaning_zh' => '创作',
                'example_sentence' => '文学创作。',
                'example_translation' => 'Literary creation.',
                'definition' => 'To create, creation, creative work',
                'sentences' => ['___灵感。', '___过程。', '___自由。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '鉴赏',
                'pinyin' => 'jiàn shǎng',
                'simplified' => '鉴赏',
                'traditional' => '鑒賞',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To appreciate / Appreciation',
                'meaning_zh' => '鉴赏',
                'example_sentence' => '艺术鉴赏。',
                'example_translation' => 'Art appreciation.',
                'definition' => 'To appreciate, appreciation, appraisal',
                'sentences' => ['___能力。', '___水平。', '___课。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '审美',
                'pinyin' => 'shěn měi',
                'simplified' => '审美',
                'traditional' => '審美',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Aesthetics / To appreciate beauty',
                'meaning_zh' => '审美',
                'example_sentence' => '审美观念。',
                'example_translation' => 'Aesthetic concept.',
                'definition' => 'Aesthetics, to appreciate beauty',
                'sentences' => ['___标准。', '___能力。', '___价值。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '风格',
                'pinyin' => 'fēng gé',
                'simplified' => '风格',
                'traditional' => '風格',
                'part_of_speech' => 'noun',
                'meaning' => 'Style',
                'meaning_zh' => '风格',
                'example_sentence' => '艺术风格。',
                'example_translation' => 'Artistic style.',
                'definition' => 'Style, manner, characteristic',
                'sentences' => ['___独特。', '___多样。', '___形成。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '流派',
                'pinyin' => 'liú pài',
                'simplified' => '流派',
                'traditional' => '流派',
                'part_of_speech' => 'noun',
                'meaning' => 'School (of thought) / Genre',
                'meaning_zh' => '流派',
                'example_sentence' => '艺术流派。',
                'example_translation' => 'Artistic school.',
                'definition' => 'School, genre, faction',
                'sentences' => ['___不同。', '___代表。', '___特点。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '杰作',
                'pinyin' => 'jié zuò',
                'simplified' => '杰作',
                'traditional' => '傑作',
                'part_of_speech' => 'noun',
                'meaning' => 'Masterpiece',
                'meaning_zh' => '杰作',
                'example_sentence' => '文学杰作。',
                'example_translation' => 'Literary masterpiece.',
                'definition' => 'Masterpiece, masterwork',
                'sentences' => ['___艺术。', '___传世。', '___不朽。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '名著',
                'pinyin' => 'míng zhù',
                'simplified' => '名著',
                'traditional' => '名著',
                'part_of_speech' => 'noun',
                'meaning' => 'Famous work / Masterpiece',
                'meaning_zh' => '名著',
                'example_sentence' => '世界名著。',
                'example_translation' => 'World famous works.',
                'definition' => 'Famous work, masterpiece, classic',
                'sentences' => ['___阅读。', '___文学。', '___欣赏。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 161,
                'word' => '灵感',
                'pinyin' => 'líng gǎn',
                'simplified' => '灵感',
                'traditional' => '靈感',
                'part_of_speech' => 'noun',
                'meaning' => 'Inspiration',
                'meaning_zh' => '灵感',
                'example_sentence' => '获得灵感。',
                'example_translation' => 'Get inspiration.',
                'definition' => 'Inspiration, creative inspiration',
                'sentences' => ['___来源。', '___迸发。', '___源泉。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 162: Education and Knowledge - 教育与知识
        $educationVocab = [
            [
                'topic_id' => 162,
                'word' => '启蒙',
                'pinyin' => 'qǐ méng',
                'simplified' => '启蒙',
                'traditional' => '啟蒙',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Enlightenment / To enlighten',
                'meaning_zh' => '启蒙',
                'example_sentence' => '启蒙教育。',
                'example_translation' => 'Enlightenment education.',
                'definition' => 'Enlightenment, to enlighten, initiation',
                'sentences' => ['___老师。', '___阶段。', '___思想。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '培养',
                'pinyin' => 'péi yǎng',
                'simplified' => '培养',
                'traditional' => '培養',
                'part_of_speech' => 'verb',
                'meaning' => 'To cultivate / To foster',
                'meaning_zh' => '培养',
                'example_sentence' => '培养人才。',
                'example_translation' => 'Cultivate talents.',
                'definition' => 'To cultivate, to foster, to train',
                'sentences' => ['___能力。', '___兴趣。', '___习惯。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '素质',
                'pinyin' => 'sù zhì',
                'simplified' => '素质',
                'traditional' => '素質',
                'part_of_speech' => 'noun',
                'meaning' => 'Quality / Caliber',
                'meaning_zh' => '素质',
                'example_sentence' => '提高素质。',
                'example_translation' => 'Improve quality.',
                'definition' => 'Quality, caliber, competence',
                'sentences' => ['___教育。', '___高低。', '___培养。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '能力',
                'pinyin' => 'néng lì',
                'simplified' => '能力',
                'traditional' => '能力',
                'part_of_speech' => 'noun',
                'meaning' => 'Ability / Capability',
                'meaning_zh' => '能力',
                'example_sentence' => '提高能力。',
                'example_translation' => 'Improve ability.',
                'definition' => 'Ability, capability, competence',
                'sentences' => ['___培养。', '___强弱。', '___水平。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '智慧',
                'pinyin' => 'zhì huì',
                'simplified' => '智慧',
                'traditional' => '智慧',
                'part_of_speech' => 'noun',
                'meaning' => 'Wisdom / Intelligence',
                'meaning_zh' => '智慧',
                'example_sentence' => '充满智慧。',
                'example_translation' => 'Full of wisdom.',
                'definition' => 'Wisdom, intelligence, sagacity',
                'sentences' => ['___结晶。', '___启迪。', '___人生。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '学术',
                'pinyin' => 'xué shù',
                'simplified' => '学术',
                'traditional' => '學術',
                'part_of_speech' => 'noun',
                'meaning' => 'Academic / Scholarly',
                'meaning_zh' => '学术',
                'example_sentence' => '学术研究。',
                'example_translation' => 'Academic research.',
                'definition' => 'Academic, scholarly, learning',
                'sentences' => ['___论文。', '___会议。', '___交流。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '理论',
                'pinyin' => 'lǐ lùn',
                'simplified' => '理论',
                'traditional' => '理論',
                'part_of_speech' => 'noun',
                'meaning' => 'Theory / Theoretical',
                'meaning_zh' => '理论',
                'example_sentence' => '理论知识。',
                'example_translation' => 'Theoretical knowledge.',
                'definition' => 'Theory, theoretical',
                'sentences' => ['___实践。', '___研究。', '___体系。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '实践',
                'pinyin' => 'shí jiàn',
                'simplified' => '实践',
                'traditional' => '實踐',
                'part_of_speech' => 'noun/verb',
                'meaning' => 'Practice / To practice',
                'meaning_zh' => '实践',
                'example_sentence' => '理论实践。',
                'example_translation' => 'Theory and practice.',
                'definition' => 'Practice, to practice, to put into practice',
                'sentences' => ['___经验。', '___活动。', '___证明。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '课程',
                'pinyin' => 'kè chéng',
                'simplified' => '课程',
                'traditional' => '課程',
                'part_of_speech' => 'noun',
                'meaning' => 'Course / Curriculum',
                'meaning_zh' => '课程',
                'example_sentence' => '选修课程。',
                'example_translation' => 'Elective courses.',
                'definition' => 'Course, curriculum, program',
                'sentences' => ['___设置。', '___内容。', '___安排。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '教材',
                'pinyin' => 'jiào cái',
                'simplified' => '教材',
                'traditional' => '教材',
                'part_of_speech' => 'noun',
                'meaning' => 'Teaching material / Textbook',
                'meaning_zh' => '教材',
                'example_sentence' => '编写教材。',
                'example_translation' => 'Compile teaching materials.',
                'definition' => 'Teaching material, textbook',
                'sentences' => ['___内容。', '___选择。', '___研发。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '师资',
                'pinyin' => 'shī zī',
                'simplified' => '师资',
                'traditional' => '師資',
                'part_of_speech' => 'noun',
                'meaning' => 'Teaching staff / Faculty',
                'meaning_zh' => '师资',
                'example_sentence' => '师资力量。',
                'example_translation' => 'Teaching staff strength.',
                'definition' => 'Teaching staff, faculty, teachers',
                'sentences' => ['___队伍。', '___培训。', '___水平。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '学位',
                'pinyin' => 'xué wèi',
                'simplified' => '学位',
                'traditional' => '學位',
                'part_of_speech' => 'noun',
                'meaning' => 'Degree (academic)',
                'meaning_zh' => '学位',
                'example_sentence' => '获得学位。',
                'example_translation' => 'Obtain a degree.',
                'definition' => 'Degree, academic degree',
                'sentences' => ['___证书。', '___授予。', '___论文。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '学历',
                'pinyin' => 'xué lì',
                'simplified' => '学历',
                'traditional' => '學歷',
                'part_of_speech' => 'noun',
                'meaning' => 'Educational background / Academic credentials',
                'meaning_zh' => '学历',
                'example_sentence' => '高学历。',
                'example_translation' => 'High educational background.',
                'definition' => 'Educational background, academic credentials',
                'sentences' => ['___要求。', '___证明。', '___水平。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '奖学金',
                'pinyin' => 'jiǎng xué jīn',
                'simplified' => '奖学金',
                'traditional' => '獎學金',
                'part_of_speech' => 'noun',
                'meaning' => 'Scholarship',
                'meaning_zh' => '奖学金',
                'example_sentence' => '获得奖学金。',
                'example_translation' => 'Receive a scholarship.',
                'definition' => 'Scholarship, fellowship',
                'sentences' => ['___申请。', '___评选。', '___资助。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '教学法',
                'pinyin' => 'jiào xué fǎ',
                'simplified' => '教学法',
                'traditional' => '教學法',
                'part_of_speech' => 'noun',
                'meaning' => 'Teaching method / Pedagogy',
                'meaning_zh' => '教学法',
                'example_sentence' => '改进教学法。',
                'example_translation' => 'Improve teaching methods.',
                'definition' => 'Teaching method, pedagogy',
                'sentences' => ['___创新。', '___研究。', '___多样。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '启发',
                'pinyin' => 'qǐ fā',
                'simplified' => '启发',
                'traditional' => '啟發',
                'part_of_speech' => 'verb',
                'meaning' => 'To inspire / To enlighten',
                'meaning_zh' => '启发',
                'example_sentence' => '启发思考。',
                'example_translation' => 'Inspire thinking.',
                'definition' => 'To inspire, to enlighten, to arouse',
                'sentences' => ['___式教学。', '___学生。', '___智慧。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '探索',
                'pinyin' => 'tàn suǒ',
                'simplified' => '探索',
                'traditional' => '探索',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To explore / Exploration',
                'meaning_zh' => '探索',
                'example_sentence' => '探索未知。',
                'example_translation' => 'Explore the unknown.',
                'definition' => 'To explore, exploration, to probe',
                'sentences' => ['___精神。', '___发现。', '___创新。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '钻研',
                'pinyin' => 'zuān yán',
                'simplified' => '钻研',
                'traditional' => '鑽研',
                'part_of_speech' => 'verb',
                'meaning' => 'To study intensively / To delve into',
                'meaning_zh' => '钻研',
                'example_sentence' => '钻研学问。',
                'example_translation' => 'Study intensively.',
                'definition' => 'To study intensively, to delve into',
                'sentences' => ['___精神。', '___业务。', '___技术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '掌握',
                'pinyin' => 'zhǎng wò',
                'simplified' => '掌握',
                'traditional' => '掌握',
                'part_of_speech' => 'verb',
                'meaning' => 'To master / To grasp',
                'meaning_zh' => '掌握',
                'example_sentence' => '掌握知识。',
                'example_translation' => 'Master knowledge.',
                'definition' => 'To master, to grasp, to control',
                'sentences' => ['___技能。', '___方法。', '___程度。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 162,
                'word' => '终身学习',
                'pinyin' => 'zhōng shēn xué xí',
                'simplified' => '终身学习',
                'traditional' => '終身學習',
                'part_of_speech' => 'noun',
                'meaning' => 'Lifelong learning',
                'meaning_zh' => '终身学习',
                'example_sentence' => '坚持终身学习。',
                'example_translation' => 'Persist in lifelong learning.',
                'definition' => 'Lifelong learning, continuous learning',
                'sentences' => ['___理念。', '___时代。', '___社会。'],
                'level' => 'HSK6',
            ],
        ];

        // Topic 163: Language and Communication - 语言与交流
        $languageVocab = [
            [
                'topic_id' => 163,
                'word' => '语言',
                'pinyin' => 'yǔ yán',
                'simplified' => '语言',
                'traditional' => '語言',
                'part_of_speech' => 'noun',
                'meaning' => 'Language',
                'meaning_zh' => '语言',
                'example_sentence' => '学习语言。',
                'example_translation' => 'Learn a language.',
                'definition' => 'Language, speech',
                'sentences' => ['___能力。', '___交流。', '___学习。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '方言',
                'pinyin' => 'fāng yán',
                'simplified' => '方言',
                'traditional' => '方言',
                'part_of_speech' => 'noun',
                'meaning' => 'Dialect',
                'meaning_zh' => '方言',
                'example_sentence' => '说方言。',
                'example_translation' => 'Speak dialect.',
                'definition' => 'Dialect, local language',
                'sentences' => ['___地区。', '___差异。', '___保护。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '口语',
                'pinyin' => 'kǒu yǔ',
                'simplified' => '口语',
                'traditional' => '口語',
                'part_of_speech' => 'noun',
                'meaning' => 'Spoken language / Colloquial',
                'meaning_zh' => '口语',
                'example_sentence' => '练习口语。',
                'example_translation' => 'Practice spoken language.',
                'definition' => 'Spoken language, colloquial, oral',
                'sentences' => ['___交流。', '___能力。', '___表达。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '书面语',
                'pinyin' => 'shū miàn yǔ',
                'simplified' => '书面语',
                'traditional' => '書面語',
                'part_of_speech' => 'noun',
                'meaning' => 'Written language',
                'meaning_zh' => '书面语',
                'example_sentence' => '书面语表达。',
                'example_translation' => 'Written language expression.',
                'definition' => 'Written language, formal written style',
                'sentences' => ['___正式。', '___规范。', '___口语。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '词汇',
                'pinyin' => 'cí huì',
                'simplified' => '词汇',
                'traditional' => '詞彙',
                'part_of_speech' => 'noun',
                'meaning' => 'Vocabulary',
                'meaning_zh' => '词汇',
                'example_sentence' => '扩大词汇。',
                'example_translation' => 'Expand vocabulary.',
                'definition' => 'Vocabulary, lexicon',
                'sentences' => ['___量。', '___学习。', '___积累。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '语法',
                'pinyin' => 'yǔ fǎ',
                'simplified' => '语法',
                'traditional' => '語法',
                'part_of_speech' => 'noun',
                'meaning' => 'Grammar',
                'meaning_zh' => '语法',
                'example_sentence' => '学习语法。',
                'example_translation' => 'Learn grammar.',
                'definition' => 'Grammar, grammatical rules',
                'sentences' => ['___规则。', '___错误。', '___结构。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '发音',
                'pinyin' => 'fā yīn',
                'simplified' => '发音',
                'traditional' => '發音',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Pronunciation / To pronounce',
                'meaning_zh' => '发音',
                'example_sentence' => '标准发音。',
                'example_translation' => 'Standard pronunciation.',
                'definition' => 'Pronunciation, to pronounce',
                'sentences' => ['___准确。', '___练习。', '___清楚。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '语调',
                'pinyin' => 'yǔ diào',
                'simplified' => '语调',
                'traditional' => '語調',
                'part_of_speech' => 'noun',
                'meaning' => 'Intonation / Tone',
                'meaning_zh' => '语调',
                'example_sentence' => '语调自然。',
                'example_translation' => 'Natural intonation.',
                'definition' => 'Intonation, tone, accent',
                'sentences' => ['___变化。', '___语气。', '___表达。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '表达',
                'pinyin' => 'biǎo dá',
                'simplified' => '表达',
                'traditional' => '表達',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To express / Expression',
                'meaning_zh' => '表达',
                'example_sentence' => '清楚表达。',
                'example_translation' => 'Express clearly.',
                'definition' => 'To express, expression, to convey',
                'sentences' => ['___能力。', '___观点。', '___方式。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '沟通',
                'pinyin' => 'gōu tōng',
                'simplified' => '沟通',
                'traditional' => '溝通',
                'part_of_speech' => 'verb',
                'meaning' => 'To communicate / Communication',
                'meaning_zh' => '沟通',
                'example_sentence' => '有效沟通。',
                'example_translation' => 'Effective communication.',
                'definition' => 'To communicate, communication',
                'sentences' => ['___交流。', '___障碍。', '___技巧。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '交际',
                'pinyin' => 'jiāo jì',
                'simplified' => '交际',
                'traditional' => '交際',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Social intercourse / To socialize',
                'meaning_zh' => '交际',
                'example_sentence' => '社交交际。',
                'example_translation' => 'Social intercourse.',
                'definition' => 'Social intercourse, to socialize',
                'sentences' => ['___能力。', '___圈。', '___场合。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '翻译',
                'pinyin' => 'fān yì',
                'simplified' => '翻译',
                'traditional' => '翻譯',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'To translate / Translation',
                'meaning_zh' => '翻译',
                'example_sentence' => '翻译文章。',
                'example_translation' => 'Translate articles.',
                'definition' => 'To translate, translation, interpreter',
                'sentences' => ['___准确。', '___工作。', '___技巧。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '口译',
                'pinyin' => 'kǒu yì',
                'simplified' => '口译',
                'traditional' => '口譯',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Interpretation / To interpret',
                'meaning_zh' => '口译',
                'example_sentence' => '同声口译。',
                'example_translation' => 'Simultaneous interpretation.',
                'definition' => 'Interpretation, to interpret orally',
                'sentences' => ['___员。', '___技能。', '___现场。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '笔译',
                'pinyin' => 'bǐ yì',
                'simplified' => '笔译',
                'traditional' => '筆譯',
                'part_of_speech' => 'verb/noun',
                'meaning' => 'Written translation / To translate in writing',
                'meaning_zh' => '笔译',
                'example_sentence' => '笔译工作。',
                'example_translation' => 'Written translation work.',
                'definition' => 'Written translation, to translate in writing',
                'sentences' => ['___文件。', '___准确。', '___质量。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '修辞',
                'pinyin' => 'xiū cí',
                'simplified' => '修辞',
                'traditional' => '修辭',
                'part_of_speech' => 'noun',
                'meaning' => 'Rhetoric / Figure of speech',
                'meaning_zh' => '修辞',
                'example_sentence' => '修辞手法。',
                'example_translation' => 'Rhetorical device.',
                'definition' => 'Rhetoric, figure of speech',
                'sentences' => ['___技巧。', '___方法。', '___艺术。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '成语',
                'pinyin' => 'chéng yǔ',
                'simplified' => '成语',
                'traditional' => '成語',
                'part_of_speech' => 'noun',
                'meaning' => 'Idiom / Set phrase',
                'meaning_zh' => '成语',
                'example_sentence' => '学习成语。',
                'example_translation' => 'Learn idioms.',
                'definition' => 'Idiom, set phrase, proverb',
                'sentences' => ['___典故。', '___运用。', '___故事。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '谚语',
                'pinyin' => 'yàn yǔ',
                'simplified' => '谚语',
                'traditional' => '諺語',
                'part_of_speech' => 'noun',
                'meaning' => 'Proverb / Saying',
                'meaning_zh' => '谚语',
                'example_sentence' => '民间谚语。',
                'example_translation' => 'Folk proverb.',
                'definition' => 'Proverb, saying, adage',
                'sentences' => ['___智慧。', '___流传。', '___俗语。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '语境',
                'pinyin' => 'yǔ jìng',
                'simplified' => '语境',
                'traditional' => '語境',
                'part_of_speech' => 'noun',
                'meaning' => 'Context / Linguistic context',
                'meaning_zh' => '语境',
                'example_sentence' => '理解语境。',
                'example_translation' => 'Understand context.',
                'definition' => 'Context, linguistic context',
                'sentences' => ['___中理解。', '___分析。', '___意义。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '语义',
                'pinyin' => 'yǔ yì',
                'simplified' => '语义',
                'traditional' => '語義',
                'part_of_speech' => 'noun',
                'meaning' => 'Semantics / Meaning',
                'meaning_zh' => '语义',
                'example_sentence' => '理解语义。',
                'example_translation' => 'Understand semantics.',
                'definition' => 'Semantics, meaning, sense',
                'sentences' => ['___分析。', '___学。', '___理解。'],
                'level' => 'HSK6',
            ],
            [
                'topic_id' => 163,
                'word' => '雄辩',
                'pinyin' => 'xióng biàn',
                'simplified' => '雄辩',
                'traditional' => '雄辯',
                'part_of_speech' => 'adjective/noun',
                'meaning' => 'Eloquent / Eloquence',
                'meaning_zh' => '雄辩',
                'example_sentence' => '雄辩的演说。',
                'example_translation' => 'Eloquent speech.',
                'definition' => 'Eloquent, eloquence, powerful argument',
                'sentences' => ['___口才。', '___有力。', '___说服。'],
                'level' => 'HSK6',
            ],
        ];

        // Insert all vocabularies using Eloquent
        foreach (array_merge($artsVocab, $educationVocab, $languageVocab) as $vocabData) {
            Vocabulary::create($vocabData);
        }
    }
}
