<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use App\Models\VocabularyTranslation;
use Illuminate\Database\Seeder;

class VocabularySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Topic 1: Chào hỏi cơ bản (Greetings)
        $greetingsVocab = [
            [
                'topic_id' => 1,
                'word' => '你好',
                'phonetic' => 'nǐ hǎo',
                'pinyin' => 'nǐ hǎo',
                'simplified' => '你好',
                'traditional' => '你好',
                'part_of_speech' => 'phrase',
                'meaning' => 'Hello, Hi',
                'meaning_vi' => 'Xin chào',
                'meaning_zh' => '你好',
                'example_sentence' => '你好，我叫李明。',
                'example_translation' => 'Hello, my name is Li Ming.',
                'example_highlight' => '你好',
                'definition' => 'Common greeting used at any time of day',
                'radical_info' => '亻(person)',
                'stroke_count' => 9,
                'tone_pattern' => '3-3',
                'related_words' => ['您好', '大家好', '嗨'],
                'similar_chars' => ['妳好'],
                'pronunciation_audio' => 'https://example.com/audio/nihao.mp3',
                'image_url' => 'https://example.com/images/nihao.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '你',
                'phonetic' => 'nǐ',
                'pinyin' => 'nǐ',
                'simplified' => '你',
                'traditional' => '你',
                'part_of_speech' => 'pronoun',
                'meaning' => 'You (singular, informal)',
                'meaning_vi' => 'Bạn',
                'meaning_zh' => '你',
                'example_sentence' => '你是学生吗？',
                'example_translation' => 'Are you a student?',
                'example_highlight' => '你',
                'definition' => 'Second person singular pronoun',
                'radical_info' => '亻(person)',
                'stroke_count' => 7,
                'tone_pattern' => '3',
                'related_words' => ['您', '你们', '你的'],
                'similar_chars' => ['妳', '尔'],
                'pronunciation_audio' => 'https://example.com/audio/ni.mp3',
                'image_url' => 'https://example.com/images/ni.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '再见',
                'phonetic' => 'zài jiàn',
                'pinyin' => 'zài jiàn',
                'simplified' => '再见',
                'traditional' => '再見',
                'part_of_speech' => 'phrase',
                'meaning' => 'Goodbye, See you again',
                'meaning_vi' => 'Tạm biệt',
                'meaning_zh' => '再见',
                'example_sentence' => '明天见，再见！',
                'example_translation' => 'See you tomorrow, goodbye!',
                'example_highlight' => '再见',
                'definition' => 'Common farewell expression',
                'radical_info' => '见(see)',
                'stroke_count' => 10,
                'tone_pattern' => '4-4',
                'related_words' => ['拜拜', '回见', '明天见'],
                'similar_chars' => ['見'],
                'pronunciation_audio' => 'https://example.com/audio/zaijian.mp3',
                'image_url' => 'https://example.com/images/zaijian.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '谢谢',
                'phonetic' => 'xiè xie',
                'pinyin' => 'xiè xie',
                'simplified' => '谢谢',
                'traditional' => '謝謝',
                'part_of_speech' => 'phrase',
                'meaning' => 'Thank you',
                'meaning_vi' => 'Cảm ơn',
                'meaning_zh' => '谢谢',
                'example_sentence' => '谢谢你的帮助。',
                'example_translation' => 'Thank you for your help.',
                'example_highlight' => '谢谢',
                'definition' => 'Expression of gratitude',
                'radical_info' => '言(speech)',
                'stroke_count' => 17,
                'tone_pattern' => '4-0',
                'related_words' => ['感谢', '多谢', '谢谢你'],
                'similar_chars' => ['謝'],
                'pronunciation_audio' => 'https://example.com/audio/xiexie.mp3',
                'image_url' => 'https://example.com/images/xiexie.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 1,
                'word' => '对不起',
                'phonetic' => 'duì bu qǐ',
                'pinyin' => 'duì bu qǐ',
                'simplified' => '对不起',
                'traditional' => '對不起',
                'part_of_speech' => 'phrase',
                'meaning' => 'Sorry, I apologize',
                'meaning_vi' => 'Xin lỗi',
                'meaning_zh' => '对不起',
                'example_sentence' => '对不起，我来晚了。',
                'example_translation' => 'Sorry, I am late.',
                'example_highlight' => '对不起',
                'definition' => 'Expression of apology',
                'radical_info' => '对(correct)',
                'stroke_count' => 16,
                'tone_pattern' => '4-0-3',
                'related_words' => ['抱歉', '不好意思', '对不住'],
                'similar_chars' => ['對'],
                'pronunciation_audio' => 'https://example.com/audio/duibuqi.mp3',
                'image_url' => 'https://example.com/images/duibuqi.jpg',
                'level' => 'HSK1',
            ],
        ];

        // Topic 2: Gia đình (Family)
        $familyVocab = [
            [
                'topic_id' => 2,
                'word' => '家',
                'phonetic' => 'jiā',
                'pinyin' => 'jiā',
                'simplified' => '家',
                'traditional' => '家',
                'part_of_speech' => 'noun',
                'meaning' => 'Home, family',
                'meaning_vi' => 'Nhà, gia đình',
                'meaning_zh' => '家',
                'example_sentence' => '我家有四口人。',
                'example_translation' => 'My family has four people.',
                'example_highlight' => '家',
                'definition' => 'Place where one lives; family unit',
                'radical_info' => '宀(roof)',
                'stroke_count' => 10,
                'tone_pattern' => '1',
                'related_words' => ['家人', '家庭', '回家'],
                'similar_chars' => ['豕'],
                'pronunciation_audio' => 'https://example.com/audio/jia.mp3',
                'image_url' => 'https://example.com/images/jia.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '爸爸',
                'phonetic' => 'bà ba',
                'pinyin' => 'bà ba',
                'simplified' => '爸爸',
                'traditional' => '爸爸',
                'part_of_speech' => 'noun',
                'meaning' => 'Father, dad',
                'meaning_vi' => 'Bố, ba',
                'meaning_zh' => '爸爸',
                'example_sentence' => '我爸爸是老师。',
                'example_translation' => 'My father is a teacher.',
                'example_highlight' => '爸爸',
                'definition' => 'Male parent',
                'radical_info' => '父(father)',
                'stroke_count' => 16,
                'tone_pattern' => '4-0',
                'related_words' => ['父亲', '老爸', '爹'],
                'similar_chars' => ['巴'],
                'pronunciation_audio' => 'https://example.com/audio/baba.mp3',
                'image_url' => 'https://example.com/images/baba.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 2,
                'word' => '妈妈',
                'phonetic' => 'mā ma',
                'pinyin' => 'mā ma',
                'simplified' => '妈妈',
                'traditional' => '媽媽',
                'part_of_speech' => 'noun',
                'meaning' => 'Mother, mom',
                'meaning_vi' => 'Mẹ, má',
                'meaning_zh' => '妈妈',
                'example_sentence' => '我妈妈很漂亮。',
                'example_translation' => 'My mother is very beautiful.',
                'example_highlight' => '妈妈',
                'definition' => 'Female parent',
                'radical_info' => '女(female)',
                'stroke_count' => 12,
                'tone_pattern' => '1-0',
                'related_words' => ['母亲', '老妈', '娘'],
                'similar_chars' => ['媽', '马'],
                'pronunciation_audio' => 'https://example.com/audio/mama.mp3',
                'image_url' => 'https://example.com/images/mama.jpg',
                'level' => 'HSK1',
            ],
        ];

        // Topic 3: Số đếm (Numbers)
        $numbersVocab = [
            [
                'topic_id' => 3,
                'word' => '一',
                'phonetic' => 'yī',
                'pinyin' => 'yī',
                'simplified' => '一',
                'traditional' => '一',
                'part_of_speech' => 'number',
                'meaning' => 'One, 1',
                'meaning_vi' => 'Một',
                'meaning_zh' => '一',
                'example_sentence' => '我有一个苹果。',
                'example_translation' => 'I have one apple.',
                'example_highlight' => '一',
                'definition' => 'The number one',
                'radical_info' => '一(one)',
                'stroke_count' => 1,
                'tone_pattern' => '1',
                'related_words' => ['一个', '一点', '一些'],
                'similar_chars' => ['丨'],
                'pronunciation_audio' => 'https://example.com/audio/yi.mp3',
                'image_url' => 'https://example.com/images/yi.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '二',
                'phonetic' => 'èr',
                'pinyin' => 'èr',
                'simplified' => '二',
                'traditional' => '二',
                'part_of_speech' => 'number',
                'meaning' => 'Two, 2',
                'meaning_vi' => 'Hai',
                'meaning_zh' => '二',
                'example_sentence' => '我有二十块钱。',
                'example_translation' => 'I have twenty yuan.',
                'example_highlight' => '二',
                'definition' => 'The number two',
                'radical_info' => '二(two)',
                'stroke_count' => 2,
                'tone_pattern' => '4',
                'related_words' => ['两', '二十', '第二'],
                'similar_chars' => ['三', '上'],
                'pronunciation_audio' => 'https://example.com/audio/er.mp3',
                'image_url' => 'https://example.com/images/er.jpg',
                'level' => 'HSK1',
            ],
            [
                'topic_id' => 3,
                'word' => '三',
                'phonetic' => 'sān',
                'pinyin' => 'sān',
                'simplified' => '三',
                'traditional' => '三',
                'part_of_speech' => 'number',
                'meaning' => 'Three, 3',
                'meaning_vi' => 'Ba',
                'meaning_zh' => '三',
                'example_sentence' => '他有三个孩子。',
                'example_translation' => 'He has three children.',
                'example_highlight' => '三',
                'definition' => 'The number three',
                'radical_info' => '一(one)',
                'stroke_count' => 3,
                'tone_pattern' => '1',
                'related_words' => ['三十', '第三', '三个'],
                'similar_chars' => ['二', '王'],
                'pronunciation_audio' => 'https://example.com/audio/san.mp3',
                'image_url' => 'https://example.com/images/san.jpg',
                'level' => 'HSK1',
            ],
        ];

        // Topic 4: Màu sắc (Colors)
        $colorsVocab = [
            [
                'topic_id' => 4,
                'word' => '红色',
                'phonetic' => 'hóng sè',
                'pinyin' => 'hóng sè',
                'simplified' => '红色',
                'traditional' => '紅色',
                'part_of_speech' => 'noun',
                'meaning' => 'Red color',
                'meaning_vi' => 'Màu đỏ',
                'meaning_zh' => '红色',
                'example_sentence' => '我喜欢红色的衣服。',
                'example_translation' => 'I like red clothes.',
                'example_highlight' => '红色',
                'definition' => 'The color red',
                'radical_info' => '纟(silk)',
                'stroke_count' => 12,
                'tone_pattern' => '2-4',
                'related_words' => ['红', '大红', '红颜色'],
                'similar_chars' => ['紅'],
                'pronunciation_audio' => 'https://example.com/audio/hongse.mp3',
                'image_url' => 'https://example.com/images/hongse.jpg',
                'level' => 'HSK2',
            ],
            [
                'topic_id' => 4,
                'word' => '白色',
                'phonetic' => 'bái sè',
                'pinyin' => 'bái sè',
                'simplified' => '白色',
                'traditional' => '白色',
                'part_of_speech' => 'noun',
                'meaning' => 'White color',
                'meaning_vi' => 'Màu trắng',
                'meaning_zh' => '白色',
                'example_sentence' => '雪是白色的。',
                'example_translation' => 'Snow is white.',
                'example_highlight' => '白色',
                'definition' => 'The color white',
                'radical_info' => '白(white)',
                'stroke_count' => 10,
                'tone_pattern' => '2-4',
                'related_words' => ['白', '雪白', '白颜色'],
                'similar_chars' => ['百', '自'],
                'pronunciation_audio' => 'https://example.com/audio/baise.mp3',
                'image_url' => 'https://example.com/images/baise.jpg',
                'level' => 'HSK2',
            ],
        ];

        // Combine all vocabularies
        $allVocabularies = array_merge(
            $greetingsVocab,
            $familyVocab,
            $numbersVocab,
            $colorsVocab
        );

        // Sample translations for some vocabularies
        $vocabTranslations = [
            1 => [ // 你好
                'vi' => ['meaning' => 'Xin chào', 'example_translation' => 'Xin chào, tôi tên là Lý Minh.'],
                'ja' => ['meaning' => 'こんにちは', 'example_translation' => 'こんにちは、私は李明です。'],
                'ko' => ['meaning' => '안녕하세요', 'example_translation' => '안녕하세요, 저는 이명입니다.'],
                'es' => ['meaning' => 'Hola', 'example_translation' => 'Hola, mi nombre es Li Ming.'],
                'fr' => ['meaning' => 'Bonjour', 'example_translation' => 'Bonjour, je m\'appelle Li Ming.'],
            ],
            2 => [ // 你
                'vi' => ['meaning' => 'Bạn', 'example_translation' => 'Bạn là học sinh phải không?'],
                'ja' => ['meaning' => 'あなた', 'example_translation' => 'あなたは学生ですか？'],
                'ko' => ['meaning' => '너', 'example_translation' => '너는 학생이니?'],
            ],
            3 => [ // 再见
                'vi' => ['meaning' => 'Tạm biệt', 'example_translation' => 'Hẹn gặp lại ngày mai, tạm biệt!'],
                'ja' => ['meaning' => 'さようなら', 'example_translation' => 'また明日、さようなら！'],
                'ko' => ['meaning' => '안녕', 'example_translation' => '내일 봐, 안녕!'],
            ],
        ];

        foreach ($allVocabularies as $vocab) {
            $vocabulary = Vocabulary::create($vocab);

            // Add translations if available
            if (isset($vocabTranslations[$vocabulary->id])) {
                foreach ($vocabTranslations[$vocabulary->id] as $langCode => $translation) {
                    VocabularyTranslation::create([
                        'vocabulary_id' => $vocabulary->id,
                        'language_code' => $langCode,
                        'meaning' => $translation['meaning'],
                        'example_translation' => $translation['example_translation'] ?? null,
                    ]);
                }
            }
        }
    }
}
